### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by anatalph** [nodeschool/discussions#1]
-bash: learnyounode: command not found

**Comment by TOyefule** [comment]
I am getting the same error, but different warnings:

$ sudo npm install -g learnyounode
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
/Users/UPennGrad/.npm-global/bin/learnyounode -> /Users/UPennGrad/.npm-global/lib/node_modules/learnyounode/bin/learnyounode
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: codeclimate-test-reporter@github:codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa (node_modules/learnyounode/node_modules/i18n-core/node_modules/codeclimate-test-reporter):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: /usr/bin/git ls-remote -h -t ssh://git@github.com/codeclimate/javascript-test-reporter.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xcrun: error: active developer path ("/Applications/Developement/Xcode.app/Contents/Developer") does not exist
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: See `man xcode-select` for more details.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: exited with error code: 1

+ learnyounode@4.2.1
updated 1 package in 8.433s
