### ISSUE TITLE
Request to add step to mac install suggestions

### ISSUE THREAD

**Issue by lsharkey** [nodeschool/discussions#1000]
Hello, thanks so much for including the install instructions.  I am on Mac OSX 10.9.6 (Mavericks), and I followed your advice to use HomeBrew.  One thing that I would like suggest adding to your help page:  Please suggest that if XCode is not already installed, it should be installed before Home Brew is installed.  
Reason:
The HomeBrew (Brew) install will automatically try to download and install XCode, if it is not already installed.  However, XCode is huge: > 2.5 GB.  The HomeBrew install errors out before the download finishes, and then the attempted XCode download gets all whacked.  I don't know if this is typical, but I had to uninstall HomeBrew after installing XCode and then re-install it.

**Comment by martinheidegger** [comment]
Issue #1000 and what a great issue it is! Will add your suggestions to the installation instructions. Thank you so much!

**Comment by lsharkey** [comment]
Thanks!  That was fast!
