### ISSUE TITLE
Can't get "Requesting you pull, please' challenge in Node School.git-it to find mod

### ISSUE THREAD

**Issue by erippy** [nodeschool/discussions#1001]
Worked thru all preceding challenges OK, but can't select any branch to requst pull. Have tried altering contributors/add-erippy.txt & adding/committing, no dice.

Any help appreciated,
Ed

**Comment by martinheidegger** [comment]
Hello @erippy not sure I understand "branch to request pull" but I try anyways: A pull request is telling(requesting) to someone to please pull your changes. This is a feature of github. In order for github to know your changes you have to have that branch in your repository. Did you push a branch to github?

**Comment by erippy** [comment]
AFAIK I did; the verifyer in the 'git-it' program said it was there. But I quit the prog & restarted it, so I think I may have gotten something out of sync there. I think it has a lot to do w/ the 'git-it' auto-scorer & challenge system.

**Comment by erippy** [comment]
Well, it's OK now -- I backtracked to an earlier lesson & redid the exercises on one session, & it worked. I prolly forgot to 'checkout' the branch. Thanks fer advice...

**Comment by martinheidegger** [comment]
:+1:
