### ISSUE TITLE
Looking for a basic get started guide

### ISSUE THREAD

**Issue by Sren001** [nodeschool/discussions#1002]
Hello, I've been looking around, but to be honest I'm utterly overwhelmed. Can someone point me in the direction of a guide explaining extremely thoroughly how I get node.js to work in my Sublime Text 2?

I'm planning on following http://nodeschool.io but I'm already stuck at installing the packages.

**Comment by moriame** [comment]
First, you need to install node.js on you system : https://nodejs.org

When you have installed node.js, npm will be available to run the first command line: 
```shell
$ npm install -g javascripting
```
After installation success, you can run the command 
```shell
$ javascripting
```

Sublime Text is just need to write your javascript files.
Not to run node.js script or use npm.
You need to use your shell for that purpose

**Comment by Sren001** [comment]
So basically the code is written and saved using Sublime, and then executed using my Terminal? Working from a Mac

**Comment by Sren001** [comment]
Just confused as to what all the Sublime npm commands do then? Such as install packages, run test, run etc.

**Comment by moriame** [comment]
there is no "sublime npm command".
npm's commands run in your shell.

I guess you make some mistake.
Sublime Text / Atom are different from nvm (https://github.com/creationix/nvm)

Did you already install node.js ?
Does this command run successfully on your shell ?
```shell
$ node --version
$ npm --version
```

If yes, you are ready to run the install command (```npm install -g <package name>```)

**Comment by Sren001** [comment]
I think I got it to work now. Now I just need to change the working directory so my Terminal can find the documents I've created and saved using Sublime.

**Comment by martinheidegger** [comment]
:+1:
