### ISSUE TITLE
Security Alert prevents completion of javascripting tut - Windows 7

### ISSUE THREAD

**Issue by JaredJames** [nodeschool/discussions#1004]
I am doing the nodeschool.io courses starting with javascripting to brush up. I installed with npm, and get to create introduction.js. I am on windows so I issue command 'NUL > introduction.js' this sets off a Windows Security alert. "Your Internet Security Settings prevented one or more files from being opened."

I am working in C:\Users\User\javascripting.

I am unable to determine which 'internet' setting would affect my ability to open this local file. Any suggestions on how to proceed?

**Comment by SomeoneWeird** [comment]
Sorry! I'll make sure that the readme explicitly says to type.. `type`, too.
