### ISSUE TITLE
Nodeschool's Stream-Adventure #12 Duplexer redux

### ISSUE THREAD

**Issue by nelson777** [nodeschool/discussions#1005]
It's been days since I'm trying several ways to solve this exercice. I give up. What am I doing wrong here ? Why am I getting "write after end" error if the event I'm using is the "end" event and I don't write anything to the pipe ? I'm just changing an object after it's use. Or at least I think so.

    var duplexer2 = require("duplexer2");
    var through = require('through2');
               
    module.exports = function (counter) {
        var countries = {};        
    
        var duplex = duplexer2(through.obj(function (obj, encoding, done) {
            if (obj.country in countries)
                countries[obj.country]++;
            else 
                countries[obj.country] = 1;  
            done();
        }), counter);
    
        duplex.on("finish", function() {
            counter.setCounts(countries);
        });
    
        counter.pipe(duplex);
        
        return duplex;
    };

If I substitute the line `counter.setCounts(countries);` for `console.log(countries)` I see that it's populated correctly.

Problem text: http://pastebin.com/vAM4vKZg

I have read this exercice test file and counldn't get any clue from it as it only compares the objects to see if they're correct.

**Comment by davecocoa** [comment]
Remove `counter.pipe(duplex);` and you should be fine. You're only supposed to return a duplex stream, you're not asked to do any piping yourself.

**Comment by nelson777** [comment]
Worked. Thanks. :)

**Comment by crazyyi** [comment]
I copied the same codes and verify it but it gave me an

**Comment by pmaroli** [comment]
Same here
