### ISSUE TITLE
Problem with excercise learnyounode ->make it modular

### ISSUE THREAD

**Issue by mwiacko** [nodeschool/discussions#1006]
Hello, 
can someone may try to help me explain why in my code filtered elements aren't push to array ? 

filterDirs.js file 

    var fs = require('fs');
    module.exports = function (dirName, ext, cb) {

    var arry = [];

    fs.readdir(dirName, function (err,files) {
        if(err) return cb(err);

        files.forEach(function (elem) {
            if (elem.split(/\./)[1] === ext) arry.push(elem);
        })
    });
    cb(null, arry);
    };

and here is main.js where I invoking function

    var filterFiles = require('./filterDirs');
    var data ;
    filterFiles(__dirname,'js',function(err,data){
        console.log(data);
    });

the output: 
    []

**Comment by SomeoneWeird** [comment]
Try moving your call to `cb` inside your `readdir` call :)

**Comment by mwiacko** [comment]
Oh my god <facepalm> :)
Thank you very much for your blazing fast response
