### ISSUE TITLE
Placement of callback in 'Make It Modular'

### ISSUE THREAD

**Issue by tbskm** [nodeschool/discussions#1009]
When I first wrote my solution to 'Make it Modular', my modular code was: 
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function (dirName, fileExt, callback) {
    var fileList = [];

    fs.readdir(dirName, function (err, list) {
        if (err) {
            return callback(err);
        }

        list.forEach(function (file) {
            if (path.extname(file) === '.' + fileExt) {
                fileList.push(file);
            }
        });
    });
    return callback(null, fileList);
};
```
Which gave me 
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "CHANGELOG.md"
   ""                                  !=    "LICENCE.md"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✗ Your additional module file [myModule.js] does not appear to pass back an error received from `fs.readdir()`.
  Use the following idiomatic Node.js pattern inside your callback to `fs.readdir()`:
        if (err)
          return callback(err)
✓ Additional module file handles errors properly

# FAIL

Your solution to MAKE IT MODULAR didn't pass. Try again!

Error cleaning up: testing
```
 when I used it in my main file. I moved `return callback(null, fileList);` into `readdir`, so it became 
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function (dirName, fileExt, callback) {
    var fileList = [];

    fs.readdir(dirName, function (err, list) {
        if (err) {
            return callback(err);
        }

        list.forEach(function (file) {
            if (path.extname(file) === '.' + fileExt) {
                fileList.push(file);
            }
        });
        return callback(null, fileList);
    });
};
```
and it worked perfectly. Which I don't really understand, because `fileList` was defined outside of `readdir`. If anyone could explain what's going on, it'd be greatly appreciated!

**Comment by jkbits1** [comment]
Thanks for sharing your progress through the tutorials with us.

What you have correctly spotted is the use of a concept known as a closure. A closure is created when a function is defined within the definition of another function, just as we have here. This closure makes variables defined between the functions (such as fileList) available to the inner function. This is also why the inner function can access fileExt and callback.

It's great that you are really studying your code closely, even when it works! :smile: 

Please get in touch if you have more questions, or if I have misinterpreted your question in some way.

**Comment by tbskm** [comment]
Ok, I think I might understand. So the reason it doesn't work is because `fileList` contained values from `list`, which was defined within the closure. So when `fileList` is called outside of the closure as an argument to `callback`, it can't access the values it was assigned inside the closure?

Thanks for the quick reply, btw!

**Comment by jkbits1** [comment]
The first code doesn't work because of timing, and the asynchronous behaviour of Node (rather than anything related to the closure itself).

In the non-working code, the callback will be called before fileList has had any data added to it, i.e. before the function passed to readdir has been called. In the working code, everything is where it should be to work in the correct order. The callback is called by the readdir function, so only when that function has been called, and then only after fileList has been populated.

The asynchronous way of programming will soon become second nature, once you've seen a few examples like these! :smile:

**Comment by tbskm** [comment]
Ooooooh, haha, I totally forgot about Node's asynchronous behavior! Sorry about that, but thanks for your help!

**Comment by jkbits1** [comment]
It's a pleasure, glad you got it working and found it interesting :+1:

**Comment by martinheidegger** [comment]
Closing the issue. Awesome work @jkbits1 ! Good luck @tbskm !
