### ISSUE TITLE
Restify vs Hapi

### ISSUE THREAD

**Issue by Quantium** [nodeschool/discussions#1012]
Hi Guys!

Guided by a deep scientific curiosity, We (@4yopping) have made a little benchmark to test who NodeJS API Framework is better to fit our needs, so @serchserch and @markotom have coded [this beautiful peace I hope you like it](https://github.com/4yopping/benchmark-restify-hapi).

Could you try it? I hope you enjoy it.

**Comment by martinheidegger** [comment]
Thanks for sharing your benchmark. However, since this is an "issue" tracker and I can't see the issue here I will close this issue.
