### ISSUE TITLE
how can i install & run node.js for arduino?

### ISSUE THREAD

**Issue by FrankOcean11** [nodeschool/discussions#1013]
how can i install this node/js ? is on my pc and everything but not sure what todo next

**Comment by Sequoia** [comment]
Hi! Are you working on `nodebot-workshop`? What have you tried & what error are you encountering?

**Comment by FrankOcean11** [comment]
hello, im not sure what you mean by working on ??? im just downloading it cuz i herd i can use it to control a robot who i can make “3d print” and out fit it with todays electronics “arduino”  im on windows 8.1 Pro2 i5






Sent from Surface Pro 2





From: Sequoia McDowell
Sent: ‎Thursday‎, ‎March‎ ‎19‎, ‎2015 ‎11‎:‎55‎ ‎PM
To: nodeschool/discussions
Cc: Franks DesigNature





Hi! Are you working on nodebot-workshop? What have you tried & what error are you encountering?

**Comment by Sequoia** [comment]
Well Frank I'm afraid I don't understand precisely what your issue is! Please answer the following questions for meaningful help:

1. What **specifically** are you trying to do? Please describe your goals in detail.
2. What **step** are you stuck on?
3. What have you **tried**?
4. What **error** are you getting?

:palm_tree:

**Comment by FrankOcean11** [comment]
can you help to get the program todo something?  how do i know if this is
working when i dont even know what todo with it?  all i want is to control
my arduino for my a robot im building


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by sudodoki** [comment]
@FrankOcean11 checkout https://github.com/rwaldron/johnny-five or https://github.com/jgautier/firmata. There's no way to directly install node on arduino, AFAIK, but only to use Firmata protocol to control it over the wire/wireless connection.

**Comment by FrankOcean11** [comment]
yes i know it is what i meant to say tho that is not working out for me






Sent from Surface Pro 2





From: Джон, просто Джон
Sent: ‎Monday‎, ‎March‎ ‎23‎, ‎2015 ‎6‎:‎40‎ ‎PM
To: nodeschool/discussions
Cc: Franks DesigNature





@FrankOcean11 checkout https://github.com/rwaldron/johnny-five or https://github.com/jgautier/firmata. There's no way to directly install node on arduino, AFAIK, but only to use Firmata protocol to control it over the wire/wireless connection.

**Comment by Sequoia** [comment]
@frankocean11 give it a try, if you get stuck feel free to come open another ticket!

**Comment by FrankOcean11** [comment]
ok i installed it but i dont know if is working as i cant get a version of the black screen when i click on the green app node.js

**Comment by rwaldron** [comment]
Have you installed `StandardFirmata` on the Arduino itself?

**Comment by FrankOcean11** [comment]
No I have not since there's no video on how to, I'm not even sure of what I
installed and how does it work at this point?

**Comment by rwaldron** [comment]
> No I have not since there's no video on how to, 

I'm not sure I understand this—is there a set of videos that you're following? I assumed you were trying to  recreate the https://github.com/tableflip/nodebot-workshop examples with an actual Arduino?

If yes or if no, here's how to get started with Johnny-Five and an Arduino: 

1. Download, install and open the [Arduino IDE](http://arduino.cc/en/main/software) (there may be additional drivers necessary for windows)
2. Plug in your Arduino or Arduino compatible microcontroller via USB
3. Open the Arduino IDE, select: File > Examples > Firmata > StandardFirmata
4. Click the "Upload" button.
5. Once StandardFirmata is uploaded, close the Arduino IDE, it's no longer necessary.
6. Open your terminal, create a directory for your project and enter that directory.
7. Run `npm init` and follow the prompts
8. Run `npm install johnny-five`
9. Create a new file called "led.js" in this project directory
10. Open the file and paste this: 
```js
var five = require("johnny-five");
var board = new five.Board();
board.on("ready", function() {
  var led = new five.Led(13);
  led.blink(500); // blink the led in half-second phases
});
```
11. In the terminal, run: `node led.js`


The built-in LED will be blinking, if not report back and I will help you figure it out.

**Comment by FrankOcean11** [comment]
im new to coding so im not following any tutorial that is going to
challange my code AS I DONT HAVE NONE what i want is to have node.js
working on my pc so i can use it with arduino example code as is not to
follow along some random lessons


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by FrankOcean11** [comment]
you know maybe there should be a video on how to set this up cuz dam wtf
1st of where is this  Firmata > StandardFirmata everyone speaks of that i
dont see in my arduino ide?
and if  StandardFirmata is uploaded,  how am i going to close the Arduino
IDE, when the terminal is in that ide? theres alot to download and install
im not sure why not just include everything in a .exe "arduino has
everything in it except its header files in respect to those who are new
and not in your library why so complicated ? Eclipse and DEV++ and other
ide terminal programs are all integrated why not this one? "if is supposed
to be and do much better

**Comment by rwaldron** [comment]
> 1st of where is this  Firmata > StandardFirmata everyone speaks of that i
dont see in my arduino ide?

*File > Examples > Firmata > StandardFirmata*

Start at the program's File menu. 

> and if  StandardFirmata is uploaded,  how am i going to close the Arduino
IDE, when the terminal is in that ide?

I was not referring to the Arduino IDE's Serial Monitor. I was talking about the Windows Command Prompt. This might be useful: http://www.altifysoftware.com/developing-node-js-in-windows/ There are probably better "getting started" articles out there, but you can google for them.

> theres alot to download and install

That's subjective, however I explained the minimum requirements for getting started.

**Comment by FrankOcean11** [comment]
ok thanks im getting up to speed with your new clarifications, well i found the example sketch to load to my arduino thanks to your patience now im just a little lost as to what todo after i click RUN  command and type in ' npm init 'im not sure what to do from this point i try to follow the prompts but its asking todo and save things on places i don't understand plus im not sure at which point im suppose to see arduino doing anything  

Download, install and open the Arduino IDE (there may be additional drivers necessary for windows)
Plug in your Arduino or Arduino compatible microcontroller via USB
Open the Arduino IDE, select: File > Examples > Firmata > StandardFirmata
Click the "Upload" button.
Once StandardFirmata is uploaded, close the Arduino IDE, it's no longer necessary.
Open your terminal, create a directory for your project and enter that directory.
Run npm init and follow the prompts
Run npm install johnny-five
Create a new file called "led.js" in this project directory
Open the file and paste this:

**Comment by martinheidegger** [comment]
@FrankOcean11 Do you mean you don't know what "Create a new file ... " means?

**Comment by FrankOcean11** [comment]
yes i do , but i dont kno how todo this from terminal


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by martinheidegger** [comment]
The directories/files that you create in terminal are the same you create with finder(Mac)/explorer(win) in terminal there are many tools to help you navigate and create folders and create/edit files. "mkdir <folder>" will allow you to create a folder. "vim <file>" will let you edit files but you should search the Internet on how to use it (it's a common but rather difficult editor at first)

**Comment by FrankOcean11** [comment]
seriously this is so dumb and not so complicated but yet not easy to run
with that i said fuck this .....i downloaded Snap4arduino and JUST LIKE
THAT im already prototyping using that ide not arduinos ide this shit must
be so hard that the person who thought about marketing this node.js
couldn't even do a how to video like i would have done if i wanted my
program to be used by everyone


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by FrankOcean11** [comment]
on a short note thanks anyhow


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by SomeoneWeird** [comment]
Glad you got something working.
