### ISSUE TITLE
Bugclinic scan challenge - wrong problem test ?

### ISSUE THREAD

**Issue by nelson777** [nodeschool/discussions#1014]
I'm doing bugclinic challanges, but I couldn't find any errors in scan exercice. 
The proposed server and client files pass verify with no errors. 
Although I have understood the concept of NODE_DEBUG I tought maybe I'm missing something here.

Is this a bug or it's me that's missing something ?

**Comment by finnp** [comment]
Hey, i don't exactly understand your problem. Your code is verifying but you're expecting it to have errors? Could you ellaborate a bit and maybe copy/paste an example with your code?
