### ISSUE TITLE
Other (may be better) solution for stream-adventure exercise CONCAT

### ISSUE THREAD

**Issue by emilioplatzer** [nodeschool/discussions#1016]
I think this solution is better because not need to split and join (and outputs to stdout):

```js
var concat=require('concat-stream')

process.stdin.pipe(concat(function (body) {
    Array.prototype.reverse.call(body);
    process.stdout.write(body);
}));
```

Is this the place to do this sugest?

**Comment by martinheidegger** [comment]
@emilioplatzer it is not wrong to suggest this here :) But a better way would be to write an issue to the [stream-adventure](https://github.com/substack/stream-adventure/issues) repository. Better still you could write a PR (shouldn't be that much work)!

**Comment by emilioplatzer** [comment]
Done (https://github.com/substack/stream-adventure/pull/129)

Thanks!
