### ISSUE TITLE
Really lost with this for-loop.js

### ISSUE THREAD

**Issue by miroryss1** [nodeschool/discussions#1017]
Here´s my code:

```JavaScript
var total;
var limit;
var total = "0";
var limit = "10";

for (i = 0; i < limit; total ++) {
	console.log(total);
};
```

And the solution should be 45.
Really think I´ve done all from the challenge details.

**Comment by sudodoki** [comment]
Two points:
1) You're initialising your total & limit variables as [Strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) & they should be [Numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)
2) the parens after [for](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for) keyword contain `initialization; condition; final-statement`. If you look closely, your `i` variable isn't being changed anywhere, so `i<limit` would be true forever - causing so called `infinite loop`. You should update `i` on each step to increment by 1 and also you would probably want to update your total to increment by current element.

**Comment by miroryss1** [comment]
Thanks a lot sudodoki for take second out of looking cat pictures and answering my problem ;) 
You corrected my learning curve from going the wrong direction!

Respect!

**Comment by SomeoneWeird** [comment]
Awesome! Open another issue if you need more help :)
