### ISSUE TITLE
Higher Order Functions (Functional JS Workshop)

### ISSUE THREAD

**Issue by UziMottyn** [nodeschool/discussions#1018]
Here is my solution for 2nd challenge of Functional JS Workshop

```JavaScript
function repeat(operation, num){
  if(num){
    operation();
    repeat(operation,num-1);
  }
}
module.exports = repeat
```

I know it is correct. Still it's not passing. "Error" msg:

```
# O-oh, something isn't working.
# But don't panic!
-------------------
## Check your solution:
Solution
===================
4140
Your Attempt
===================
Difference
===================
4140
```

What's wrong with answer checking???

**Comment by davecocoa** [comment]
Sure enough, that solution passes on my computer. Could you check and tell us your node version with `node -v` and your workshopper version with `function-javascript-workshop -v`? It's probably worth trying to update those.

**Comment by UziMottyn** [comment]
v0.10.33 - node version

functional-javascript@0.0.28 - workshop version

**Comment by UziMottyn** [comment]
Thank you! I simply ran sudo update/upgrade and it started working!

**Comment by davecocoa** [comment]
Fantastic! I'm glad it's working now =)
