### ISSUE TITLE
Why does setEncoding('utf8') not work with bl() in http_collect excercise?

### ISSUE THREAD

**Issue by brshewmaker** [nodeschool/discussions#1020]
First, please forgive me if I'm posting this question in the wrong place. 
I'm working through learnyounode, on the http collect problem.  I worked through the problem myself first and came up with this solution:

```JavaScript
http.get(url, function(response) {
	response.setEncoding('utf8');
	var completeString = '';
	var numChars = 0;
	response.on('data', function(chunk) {
		numChars += chunk.length;
		completeString = completeString + chunk;
	});
	response.on('end', function() {
		console.log(numChars);
		console.log(completeString);
	});
});
```
That works great.  Then i decided to try it using the bl library like so:

```
http.get(url, function(response) {
	response.setEncoding('utf8');
	response.pipe(bl(function(err, data) {
		if (err) console.log('There was an error with the GET request');
		else {
			console.log(data.length);
			console.log(data);
		}
	}));
});
```
However, that outputs the raw octet-stream like so:
`<Buffer 46 6c 61 74 20 6f 75 74 2. . . `
The trick is to use convert the data to string inside the bl callback function: `data = data.toString();`

My question is this:  why does `response.setEncoding('utf8');` not seem to affect the data stream piped into bl in my 2nd attempt?

**Comment by Sequoia** [comment]
Hmm... I'm no expert here but I imagine that `setEncoding` works for events on *that* stream object (i.e. `stream.stdout.read()` or `.on('data')` will be `toString`ed) but **`bl()` produces a different stream object** & that one gets buffers.

Maybe try:
```javascript
    var blStream = bl(function(err, data) {
        if (err) console.log('There was an error with the GET request');
        else {
            console.log(data.length);
            console.log(data);
        }
    });

    blStream.setEncoding('utf8');

    response.pipe(blStream);
```

See if that works! :pizza:

**Comment by arshdkhn1** [comment]
@Sequoia it doesnt work . I still get a buffer output.

**Comment by arshdkhn1** [comment]
Here is my program:
```js
  var http = require('http');
  var bl = require("bl");
  http.get(process.argv[2], function(res) {
      var bufList = bl(function(err, data) {
          if (err) console.log(err);
          console.log(data.length);
          console.log(data);
      });
      bufList.setEncoding("utf8");
      res.pipe(bufList);
      res.on("error", console.error);
  }).on("error", console.error);

```

**Comment by arshdkhn1** [comment]
It seems like there are no setEncoding function for bl stream. You can check [here](https://www.npmjs.com/package/bl). So to print in 'utf8' format one must use toString method.

**Comment by Sequoia** [comment]
OK I think I see the issue. From buffer examples

> `bl.append('hi')                     // bl will also accept & convert Strings`

"bl will also accept **& convert** Strings." `bl` is a tool for collecting **Buffers**, if you convert http response to strings & feed them to a `bl` instance, **it will convert them back to buffers**.

`bl` instances *do* have `.setEncoding` because they inherit from DuplexStream < ReadableStream & the latter has a `setEncoding` method. However, that will probably only run if you consume the buffer list **using the stream API**, i.e. using `.pipe`, which you are not doing here.

Summary: `bl` converts things to buffers, if you don't want buffers, don't use it :)
