### ISSUE TITLE
if-statement.js issue

### ISSUE THREAD

**Issue by marieae** [nodeschool/discussions#1023]
my code:
var fruit = 'orange';
if (fruit.length > 5) {
	console.log('The fruit name has more than five characters.');
} else {
	console.log('The fruit name has five characters or less.');
}

this is what i'm getting:
Solution
===================

128

Your Attempt
===================
The fruit name has more than five characters.

I'm confused. The answer is supposedly 128? It seems like my 'attempt' is correct... any help would be much appreciated!

**Comment by SomeoneWeird** [comment]
Hi! Did you select the correct challenge by running `javascripting`? 128 is the answer to the previous challenge :)

**Comment by marieae** [comment]
Ah ha! So i just re-entered javascripting and reopened the IfStatements chapter and ran it with success! Thank you! Maybe somewhere along the way of me messing up a few times, closing my computer, and coming back to it a few hours later messed up my terminal. Not sure what happened but thank you :)
