### ISSUE TITLE
learnyounode exits instantly upon running

### ISSUE THREAD

**Issue by MHolender** [nodeschool/discussions#1024]
Hello! I installed and ran the git-it workshop with no problems (thanks to all contributors!), but now I'm having trouble with learnyounode. I installed it, but as soon as I run the program it exits immediately. IIRC I tried running it from the node shell, git shell and powershell to no avail. I'm running Windows 7 Home Premium 64 bit. This is what I get when I try to run it:
![screenshot](https://github.com/MHolender/MHolender.github.io/blob/master/learnyounode.jpg?raw=true)
It just exits right back to the command prompt.

**Comment by martinheidegger** [comment]
This is a known problem with npm https://github.com/npm/npm/issues/7390 Since you are a (a lot less rare than though) in a setup problem perhaps you could contact me for a debugging session?
