### ISSUE TITLE
learnyounode tutorial 11 http file server parse error

### ISSUE THREAD

**Issue by jm1200** [nodeschool/discussions#1026]
My code:

```JavaScript
var http = require('http');
var fs = require('fs');

var server = http.createServer(function(req, res) {
    var src = fs.createReadStream(process.argv[3]);
    src.pipe(response);
});

server.listen(process.argv[2]);
```

The error I am getting:

Error connecting to http://localhost:14558: Parse Error

Any idea what I am doing wrong?

**Comment by davecocoa** [comment]
Hmm, I'm not sure what's different between your environment and mine, but if I run your code I get a much more descriptive error:

```
    src.pipe(response);
             ^
ReferenceError: response is not defined
    at Server.<anonymous> (/home/cocoa/prog.js:6:14)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
    at TCP.onread (net.js:527:27)
✗ Error connecting to http://localhost:22158: socket hang up
```

Does that help?

**Comment by jm1200** [comment]
Thanks. I fixed the response argument. But still getting that same "Parse Error". It completely freezes my console too. I always have to restart it. 

Any other idea why that would happen? I am running console2 on win 8.1 x64.

**Comment by davecocoa** [comment]
Hmm, that's unfortunate, it passes for me once the response argument is fixed. I'm afraid I don't have any other advice for debugging this apart from maybe making sure you have the latest node and the latest `learnyounode`.

**Comment by jm1200** [comment]
Ok! Thank you very much for your time! I'll move on to the next one.
