### ISSUE TITLE
failing on "Your additional module file [lsModule.js] did not return an Array with the correct number of elements as the second argument of the callback

### ISSUE THREAD

**Issue by tstockton** [nodeschool/discussions#1027]
Having this issue on the MAKE IT MODULAR lesson.

**Comment by tstockton** [comment]
Here is lsModule.js:

var fs = require('fs');

module.exports = function  (dirPath, extension, callback) {
    fs.readdir(dirPath, function (err, list){
        if (err){
            return callback(err);
        } else {   
            return callback (null, list);
        }
    });

};

**Comment by davecocoa** [comment]
This error most commonly occurs when you have logic implemented outside your module file. In this case, I can see that your function accepts three parameters `dirPath, extension, callback` but it never does anything with `extension`. This exercise requires that *all* of the work happens inside your module file, your other file should simply call your module with `process.argv[2]` and `process.argv[3]` and then log the result.

**Comment by martinheidegger** [comment]
@tstockton could @davecocoa 's advice help you?

**Comment by tstockton** [comment]
Yes, it was helpful.  What I did not understand is that the callback in the main was expressly for printing the filtered list (duh!).
