### ISSUE TITLE
learnyounode - variable scope, returning callbacks, and exporting my module

### ISSUE THREAD

**Issue by maffydavison** [nodeschool/discussions#1028]
I'm confused.

In my main module (which I haven't written, yet) I am assuming I will require my module to get the list of files in a directory filtered by a given extension.  I'm guessing it should be something like this:

```JavaScript
var gimme = require('./gimme');
gimme.getFiles(process.argv[2], process.argv[3], function(err, list) {
    if (err) {
      console.log("Something happened - not good...");
   }
  console.log(list);  
});
```

Total guess.  Still struggling with the module.

Generally, I'm confused about variable scope, callback notation for getting my module's output back to the caller, and the syntax for assigning my module to the module.exports. 

```JavaScript
var fs = require('fs');
var path = require('path');

function getFiles(filepath, extension, function(err, data) {
    var ext = '.' + extension;
    var filelist = fs.readdir(filepath, function(err, list) {
       var result = "";
       for (var i = 0; i < list.length; i++ {
           if (path.extname(list[i]) === ext) {
               result += list[i] + '\n';
           }           
      }
      return result;
    });
   return filelist;
});

module.exports = function getFiles(filepath, extension, function(err, data));
```

Obviously, I'm seriously confused...

Thanks!
Maffy

**Comment by davecocoa** [comment]
You may be confused but you're very close to the answer! For one thing, your main module is almost perfect. You do need to use `require` and then call a function but where you're calling `gimme.getFiles(...)` the exercise wants you to just call `gimme(...)`. This is the difference between a module exporting a function and a module exporting an object defined like `{ foo: "some string", bar: "other string"}` which happens to contain a function defined like `{ getFiles: function(filePath){ /* function stuff here */ } }`.

Mostly, I think you're getting confused because there are a few different ways to define functions. When you define a named function like this:
```js
function getFiles(filePath) {
  /* function stuff here */
}
```
That function becomes available using that name and it seems sort of special and separate from other things we define like numbers and strings. However, if we define the function a different way, we can see that it's not different:
```js
var getFiles = function(filePath) {
  /* function stuff here */
};
```
The concept I want to get across here is that we can store function in variables just like numbers, and we can pass them around in exactly the same way, this is true regardless of how we define the function, I just find it clearer when I use `var`. So, now that we know that, here's how we'd like to setup our `module.exports`:

```js
var getFiles = function(filePath) {
  /* function stuff here */
};

module.exports = getFiles;
```

The other thing we can do with functions as variables, is that we can pass them into other functions. From the outside (in the main module), this looks like this:

```js
  var gimme = require('gimme');

  gimme(process.argv[2], process.argv[3], function(err, list){
    /* do something with the err or the list */
  });
```

But maybe it's even clearer if we write it like this:

```js
  var gimme = require('gimme');

  var callback = function(err, list){
    /* do something with the err or the list */
  };

  gimme(process.argv[2], process.argv[3], callback);
```

Finally, from the other side (inside your module `gimme`), this looks like this:

```js
var getFiles = function(filePath, extension, callback) {
  /* function stuff here */
  // when you have the list ready:
  callback(list);
};

module.exports = getFiles;
```

I hope this helps you understand this exercise, if you have any questions just ask =)

**Comment by maffydavison** [comment]
Okay, I got it to run, but it's not passing verification.  When I run it
with params of my own, I see the expected results.  When I run with the
verifier, it fails.

                 ACTUAL                                 EXPECTED

────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"

   "LICENCE.md"                        ==    "LICENCE.md"

   "README.md"                         ==    "README.md"

   ""                                  ==    ""

   ""                                  !=

 Submission results did not match expected!
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✗ Your additional module file [gimme.js] does not appear to pass back an
error received from `fs.readdir()`.
  Use the following idiomatic Node.js pattern inside your callback to
`fs.readdir()`:
if (err)
  return callback(err)
✓ Additional module file handles errors properly


It is particularly confusing since the results say that the 'Additional
module file handles errors properly' AND 'Your additional module does not
appear to pass back an error..."

Thanks for your help.  I am going to nodeschool on Saturday, so, if you
don't have time, I can ask there, but thought I'd try to get through the
basics before class so I can get help on the higher functions.

Thanks again,
Maffy

Here's the code I'm running...

gimme.js now has this:

var fs = require('fs');
var path = require('path');

var getFiles = function(filepath, extension, callback) {
    var result = '';
    fs.readdir(filepath, function(err, list) {
        if (err) {
    callback(err);                                  // I tried this with
(err, null), (err, list) and just (err) ... all gave the same result
        }
        for (var i = 0; i < list.length; i++) {
        var ext = '.' + extension;
            if (path.extname(list[i]) ===  ext) {
            result += list[i] + '\n';
            }
        }
       callback(null, result);
   });
};

module.exports = getFiles;

and the main module has this:
var gimme = require('./gimme');

var callback = function(err, list) {
    if (err) {
      console.log("Got an error");
    } else {
      console.log(list);
    }
}

gimme(process.argv[2], process.argv[3], callback);







On Wed, Mar 25, 2015 at 5:10 PM, David McMullin <notifications@github.com>
wrote:

> You may be confused but you're very close to the answer! For one thing,
> your main module is almost perfect. You do need to use require and then
> call a function but where you're calling gimme.getFiles(...) the exercise
> wants you to just call gimme(...). This is the difference between a
> module exporting a function and a module exporting an object defined like {
> foo: "some string", bar: "other string"} which happens to contain a
> function defined like { getFiles: function(filePath){ /* function stuff
> here */ } }.
>
> Mostly, I think you're getting confused because there are a few different
> ways to define functions. When you define a named function like this:
>
> function getFiles(filePath) {
>   /* function stuff here */
> }
>
> That function becomes available using that name and it seems sort of
> special and separate from other things we define like numbers and strings.
> However, if we define the function a different way, we can see that it's
> not different:
>
> var getFiles = function(filePath) {
>   /* function stuff here */
> };
>
> The concept I want to get across here is that we can store function in
> variables just like numbers, and we can pass them around in exactly the
> same way, this is true regardless of how we define the function, I just
> find it clearer when I use var. So, now that we know that, here's how
> we'd like to setup our module.exports:
>
> var getFiles = function(filePath) {
>   /* function stuff here */
> };
> module.exports = getFiles;
>
> The other thing we can do with functions as variables, is that we can pass
> them into other functions. From the outside (in the main module), this
> looks like this:
>
>   var gimme = require('gimme');
>
>   gimme(process.argv[2], process.argv[3], function(err, list){
>     /* do something with the err or the list */
>   });
>
> But maybe it's even clearer if we write it like this:
>
>   var gimme = require('gimme');
>
>   var callback = function(err, list){
>     /* do something with the err or the list */
>   };
>
>   gimme(process.argv[2], process.argv[3], callback);
>
> Finally, from the other side (inside your module gimme), this looks like
> this:
>
> var getFiles = function(filePath, extension, callback) {
>   /* function stuff here */
>   // when you have the list ready:
>   callback(list);
> };
> module.exports = getFiles;
>
> I hope this helps you understand this exercise, if you have any questions
> just ask =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/1028#issuecomment-86259545>
> .
>



-- 
"Change is the end result of all true learning."
Leo Buscaglia
<http://www.brainyquote.com/quotes/authors/l/leo_buscaglia.html>

**Comment by davecocoa** [comment]
Ah, yes this is quite confusing! If your module is calling `callback(err)` which is good, but it's also continuing and calling `callback(null, result)` later on, particularly confusing because your result will still be an empty string. To avoid this you can use `return callback(err)`, which means the rest of your function will not be executed, or you can do ` if (err) {  callback(err); } else { /* rest of your code */ }`. Either way, you want to avoid running your success focused code as well as your error code.

**Comment by maffydavison** [comment]
Thanks a million!  Now I can move on to the next challenge... :)

On Thu, Mar 26, 2015 at 3:03 PM, David McMullin <notifications@github.com>
wrote:

> Ah, yes this is quite confusing! If your module is calling callback(err)
> which is good, but it's also continuing and calling callback(null, result)
> later on, particularly confusing because your result will still be an empty
> string. To avoid this you can use return callback(err), which means the
> rest of your function will not be executed, or you can do if (err) {
> callback(err); } else { /* rest of your code */ }. Either way, you want
> to avoid running your success focused code as well as your error code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/1028#issuecomment-86733370>
> .
>



-- 
"Change is the end result of all true learning."
Leo Buscaglia
<http://www.brainyquote.com/quotes/authors/l/leo_buscaglia.html>

**Comment by davecocoa** [comment]
Great! If your problem is solved, you can go ahead and close this issue. Well done! :tada: :confetti_ball:
