### ISSUE TITLE
(中國) how to use crypto

### ISSUE THREAD

**Issue by zbmychenghua** [nodeschool/discussions#1029]
我现在要用到加密，在前端用公钥加密，在后端用私钥解密，不知道怎么解决好

**Comment by Sequoia** [comment]
@martinheidegger if you know how to get help to this person in their native language that's awesome!! Assigned to you for now, if you can't do this just remove assign (I'm afraid the ticket will just sit tho).

**Comment by martinheidegger** [comment]
I don't speak chinese :cry:

**Comment by finnp** [comment]
@nodeschool/xi-an @xeodou Can anyone of you help out here with chinese? 谢谢
 :

**Comment by xeodou** [comment]
@Sequoia @martinheidegger @finnp 
@zbmychenghua  is asking crypto stuff, he said he has some encrypto , he want use asymmetric encryption, use pub key at front-end and decrypt at the backend. But he doesn't know too much.

@zbmychenghua 
不知道你是需要什么样的加密方式 
如果是不对称加密的话，你可以看下这个库 https://github.com/travist/jsencrypt
如果是对称加密的话，你可以看下 https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password
https://nodejs.org/api/crypto.html#crypto_crypto_createdecipher_algorithm_password

**Comment by finnp** [comment]
@xeodou Ok, thank you!
