### ISSUE TITLE
Just a horse_js_tweets question - how does day + '\xff' work?

### ISSUE THREAD

**Issue by mbonaci** [nodeschool/discussions#103]
I tried searching for an explanation but \xff is a bit tricky to search for.

How does this:  
`db.createReadStream({ start: day, end: day + '\xff' })`

produce an iterator that ends with the last entry in a `day`?
What does `'\xff'` even mean?

From [here](https://github.com/rvagg/levelmeup/blob/master/problems/horse_js_tweets/solution.js).

**Comment by serapath** [comment]
+1
