### ISSUE TITLE
Not able to run npm

### ISSUE THREAD

**Issue by ramovald** [nodeschool/discussions#1031]
I'm working in my work laptop but I'm not enable to install software on it, so I downloaded the binary version for 64 bits getting a node.exe file.
If I open it, not recognizes the npm command.
I also downloaded iojs.exe but is the same problem.

Can someone help me please?

Thanks in advance

**Comment by Sequoia** [comment]
Hi @ramovald! Where did you download from? I believe you need the `.msi` here: https://nodejs.org/download/ ; the `.exe` may be *just* node nothing else. The `.msi` is packaged with NPM

More info: https://docs.npmjs.com/getting-started/installing-node

**Comment by SMikeG** [comment]
I had the same problem until I realized you need to run it from the Node.js command prompt, not from node.js itself.  Don't ask me what the difference is yet.  Have to figure that out later.

**Comment by martinheidegger** [comment]
Did you try to look at the [Installation suggestions](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#windows)?
