### ISSUE TITLE
Stumped on Module Lesson of "Learn You Node"

### ISSUE THREAD

**Issue by cjordanball** [nodeschool/discussions#1032]
I have worked this problem to death, and am at the stage where I do not feel any further work is helpful.  I have tried the following code:

For program.js:
```js
var module = require('./module.js');
var dirName = process.argv[2];
var extName = process.argv[3];
function printIt(val) {
    console.log(val);
}
module(dirName, extName, printIt);

For module.js:

var fs = require('fs');
var path = require('path');
module.exports = function(dirName, extName, printIt) {
    fs.readdir(dirName, function(err, files) {
        if (err) {
            return printIt(err);
        }
        else {
            newFiles = files.filter(function(val) {
                return path.extname(val) === '.' + extName;
            });
            newFiles.forEach(function(val){
                printIt(val);
            });
        }
    });
}
```
My results match the expected results, but I am told that my module.js file returned an error on its callback for 'CHANGELOG.md' and for 'LICENCE.md' (but not for 'README.md').  I would appreciate any guidance.

**Comment by andreicioromila** [comment]
It says in the course that the callback function(printIt in your case) should have two arguments: one for error and one for the actual data.

*I am not sure if it's the correct answer. I am now learning node.js as well. But I managed to solve the exercise and this is the only difference I see that would be related to your returned error.

**Comment by geoffdavis92** [comment]
I'm getting the same error, @cjordanball. When I run my file, I get an error on callback. Specifically, my terminal output is:

`✗ Your additional module file [asyncModule.js] returned an error on its callback:
	{ [Error: ENOENT, scandir 'verify'] errno: -2, code: 'ENOENT', path: 'verify' }`

I have tried several ways to complete the program and several ways to figure out the actual error, however I have had no luck.

Main file (`modular.js`):
```javascript
    var async = require('./asyncModule');
    async();
```

Module file (`asyncModule.js`):

```javascript
var fs = require('fs');
var path = require('path');
module.exports = function asyncModule(dir, ext, callback){
    fs.readdir(process.argv[2], function (err, list) {
        if (err)
            return callback(err)
        list.forEach(function (file) {
  	    if (path.extname(file) === '.' + process.argv[3]){
    		console.log(file);
    	    }
  	 });
  	 return callback(null, list);
     });
 };
```

So I have all the correct output and all lesson elements, including the error callback; ironically, I cannot understand or fix the error that is on the callback function.

**Comment by martinheidegger** [comment]
@geoffdavis92 I can see a rather common oversight issue: You are trying to use 

```JavaScript
if (path.extname(file) === '.' + process.argv[3]) {
```

Instead of your `ext` parameter:

```JavaScript
if (path.extname(file) === '.' + ext) {
```

I think that should help you?

**Comment by icejungle** [comment]
Hey @geoffdavis92 ,

One suggestion: since the function you wrote in asyncModule.js, takes 3 arguments, you should supply three arguments when you call it in modular.js

Cheers
