### ISSUE TITLE
HTTP COLLECT question

### ISSUE THREAD

**Issue by lstecklov** [nodeschool/discussions#1033]
Hi, my http collect doesn't pass, however all the web sites I've tested with work OK, printing 2 lines, the correct character count and all the data received from the server. Here's my code: 

```javascript
var http = require ('http');
var bl = require('bl');
var url = process.argv[2];

var req = http.get(url, function(res) {
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    }).pipe(bl(function (err, data) {
    var raw = data.toString();
    console.log(raw.length)
    console.log(raw.replace(/\n|\r/g, ''));
  }));
  res.on('error', console.error);
});

req.end();
```
Here's the output of learnyounode verify:
```
ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

1.  ACTUAL:    "380"
1.  EXPECTED:  "380"

2.  ACTUAL:    "We're going mokkies my get a dog up ya ten clicks away. He's got a massive smokes how he hasn't got a two up.Flat out like a ute bloody as cross as a brumby. Get a dog up ya cab sav to get a dog up ya pint. She'll be right blowie piece of piss lets get some show pony. As stands out like jumbuck my lets get some metho. As dry as a bail out piece of piss she'll be right bikkie. "
2.  EXPECTED:  "We're going mokkies my get a dog up ya ten clicks away. He's got a massive smokes how he hasn't got a two up."

3.  ACTUAL:    ""
3.  EXPECTED:  "Flat out like a ute bloody as cross as a brumby. Get a dog up ya cab sav to get a dog up ya pint. She'll be right blowie piece of piss lets get some show pony. As stands out like jumbuck my lets get some metho. As dry as a bail out piece of piss she'll be right bikkie. "

4.  ACTUAL:    
4.  EXPECTED:  ""


ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
```
Thanks for any help pointing me in the right direction.

**Comment by Sequoia** [comment]
Hi @lstecklov! Initial reactions:
1. You're not really using the `data` event: the callback is empty & `.on` returns the stream (for chaining) so you can remove that bit & just do `res.pipe(bl(...` if you want to pipe to `bl`
2. "Note that when you use the callback method like this, the resulting data parameter is a **concatenation of all Buffer objects in the list.**" https://www.npmjs.com/package/bl is this really what you want?
3. You are `.replace`ing newlines with `''`, but the solution expects the newline to be present. Look into http://devdocs.io/javascript/global_objects/string/split

Good luck! If it's resolved plz close ticket, if you need more assistance leave a comment!
