### ISSUE TITLE
timeserver.js works on run but not on verify

### ISSUE THREAD

**Issue by admrply** [nodeschool/discussions#1034]
Here's the code for my time server problem:

    var net = require('net')
    var date = new Date()
    var server = net.createServer(function (socket) {
        socket.end(console.log(("0"+date.getFullYear()).slice(-2)+"-"+
                               ("0"+date.getMonth()).slice(-2)+"-"+
                               ("0"+date.getDate()).slice(-2)+" "+
                               ("0"+date.getHours()).slice(-2)+":"+
                               ("0"+date.getMinutes()).slice(-2))
        )
    })
    server.listen(process.argv[2])

And when I run `learnyounode run timeserver.js` I do get the expected response, but it fails when I run `learnyounode verify timeserver.js`. I have absolutely no idea where I'm going wrong!

![screen shot 2015-03-27 at 17 56 33](https://cloud.githubusercontent.com/assets/3727916/6873822/c88c2d90-d4aa-11e4-96c6-f03edb84cb1e.png)

**Comment by balajikandasamy** [comment]
console.log in a separate line and socket.end with the same formatted date with a new line character should make it work.

**Comment by yaronidan** [comment]
I'm having the same problem, but I can't understand why socket.end() should receive the date parameter. My code looks like this - 

var net = require("net");
var date = new Date();

var server = net.createServer(function(socket){
	var month = date.getMonth()+1;
	month = (month < 10 ? "0" : "")+month;
	console.log(date.getFullYear()+'-'+month+'-'+date.getDate()+' '+date.getHours()+':'+date.getMinutes());
	socket.end();
})

server.listen(process.argv[2]);

Any help?
