### ISSUE TITLE
Expressworks: Stylish CSS 

### ISSUE THREAD

**Issue by McQuinTrix** [nodeschool/discussions#1035]
I am getting a error:
```
Error: EACCES, open '/usr/lib/node_modules/expressworks/exercises/stylish_css/public/main.css'
    at Error (native)
Error: EACCES, open '/usr/lib/node_modules/expressworks/exercises/stylish_css/public/main.css'
    at Error (native)
```
can someone help? what is the problem ?(:

**Comment by Sequoia** [comment]
hi @McQuinTrix! Does [this comment](https://github.com/nodeschool/discussions/issues/956#issuecomment-88507658) help?

**Comment by caiocutrim** [comment]
I don't make any ideas...

**Comment by McQuinTrix** [comment]
Actually it was rather a silly problem. I had installed express module in different location. that is why it was not working. Thank you (:
