### ISSUE TITLE
how to create a spy that keep track of how many times a function is called

### ISSUE THREAD

**Issue by xiongk2008** [nodeschool/discussions#1036]
I don‘t have any idea about this question,

**Comment by Sequoia** [comment]
More info please. What lesson is this part of etc.?

Generally speaking, from a high level, spies look like:
```
function spyOn(fn){
  var spy = function(){
    this.calls++
    fn.apply(arguments or whatever)
  }
  spy.calls = 0;
}

function foo(){console.log('hello!');}
var spoof = spyOn(foo);
spoof.calls //0
spoof();
spoof.calls //1
```
Something like that. Does that help?

**Comment by jkbits1** [comment]
@Sequoia This question (I'm guessing) relates to Function Spies, from the functional javascript workshop

**Comment by martinheidegger** [comment]
To write it functional you only need to change your scopes a little:

```JavaScript
function createSpy(fn){
  var spy = function(){
    spy.calls++;
    fn.apply(this, arguments);
  }
  spy.calls = 0;
  return spy;
}

function methodToSpyOn(){console.log('hello!');}

var spoof = createSpy(methodToSpyOn);
spoof.calls //0
spoof();
spoof.calls //1
```

@xiongk2008 Does that answer your question?

**Comment by timoxley** [comment]
@xiongk2008

You need to replace the function with another function which tracks the number of invocations and also calls the original function (keeping track of the input and output it's supposed to have).

The solutions posted here are spoilers so I suggest not looking at them if you can.

**Comment by timoxley** [comment]
@xiongk2008 If you can elaborate on where the description text was confusing then we can improve it.

**Comment by Sequoia** [comment]
Removed "spoiler" responses . . . @timoxley's right that was just the solution itself.

**Comment by Sequoia** [comment]
Reopen if issue persists.
