### ISSUE TITLE
Nodeschool in emacs shell?

### ISSUE THREAD

**Issue by chrstfer** [nodeschool/discussions#1038]
Is there a way to get the Nodeschool modules to play nice with inferior shells (or eshell) within emacs? Right now the word-wrapping causes major issues, and when that's turned off the experience is even worse. It seems like it's definitely an emacs issue, but seems to be caused by the fact that the node modules printing extends as far as they're able; in emacs the buffers don't have a line length, and will either wrap or truncate printing. 
It's quite possible that I'm misunderstanding something quite fundamental here, and if so I apologize. I can't say that I understand the inner working of emacs/its shells, and I am *just* beginning with Node.js.

**Comment by Sequoia** [comment]
> I can't say that I understand the inner working of emacs/its shells, and I am just beginning with Node.js.

With this in mind I would recommend you [KISS](http://en.wikipedia.org/wiki/KISS_principle) & just run nodeschool modules in your typical shell :smile_cat:. Alternately you could file a bug [on workshopper](https://github.com/rvagg/workshopper/issues) or [on adventure](https://github.com/substack/adventure/issues) depending on what nodeschool course you're doing. Good luck!

**Comment by chrstfer** [comment]
Honestly, that came off more than a bit conceited. I get your point, That being said, note that I'd already started doing that when I opened this discussion. 

Anyway, I can't be the only one who has tried to use emacs for this purpose (I'd be surprised if I am, anyway), and it's a huge turn off to interrupt one's workflow for something like this.

**Comment by martinheidegger** [comment]
@chrstfer I don't think that @Sequoia suggested with "KISS" to give up but rather to focus on one thing at a time :) The various workshoppers work slightly differently so its not too easy to fix it generally. Also the content is made by volunteers so any contribution is always welcome.

**Comment by skang404** [comment]
Please post if someone got workshoppers working in emacs.
