### ISSUE TITLE
javascripting workshop: where to go?

### ISSUE THREAD

**Issue by dailha1972** [nodeschool/discussions#1039]
I am trying to use the javascripting workshop but somehow I am not going anywhere. Is there someone who can actually help? the steps on the workshop is very vague

**Comment by ET33** [comment]
* Installing: run command `npm install -g javascripting` in your terminal.
* Running: run command `javascripting` in your terminal. It should open a menu with lessons.
This worked for me... Ayei! (☞ﾟ∀ﾟ)☞

**Comment by ayningcao** [comment]
alex@alex-VirtualBox:~$ javascripting
/usr/bin/env: node: No such file or directory

javascripting has already been successfully installed, anyone knows this?

**Comment by vtoomas** [comment]
@ayningcao 
sudo apt-get autoremove node 
sudo apt-get install nodejs-legacy

Worked for me on Ubuntu. You haven't mentioned OS you are using or what exactly have you done.. 
Seems that some installations do not add node as executable, but only nodejs. This though doesn't work for the workshop.

**Comment by martinheidegger** [comment]
@dailha1972 Do the responses help you?

**Comment by ayningcao** [comment]
@vtoomas Cool! It works perfect, I am using Ubuntu in a VirtualBox, thanks again
