### ISSUE TITLE
learnyounode FILTERED LS args ignored

### ISSUE THREAD

**Issue by michaelfournier** [nodeschool/discussions#104]
hi,
in Filteredls, i try to pass 2 args (path & ext file) to learnyounode cmd line, but it seems to put some default values (located in /tmp directory).
When i test printing process.args array, here what i get

```
michael@linux ~/Workout/nodeschool $ learnyounode run filteredls.js /home/michael/Workout/nodeschool/ js
Running "FILTERED LS"...

args = /usr/bin/nodejs,filteredls.js,/tmp/learnyounode_7002,dat
michael@linux ~/Workout/nodeschool $ 
```

while running the same cmd under node give me the right result:

```
michael@linux ~/Workout/nodeschool $ node filteredls.js /home/michael/Workout/nodeschool/ js
args = node,/home/michael/Workout/nodeschool/filteredls.js,/home/michael/Workout/nodeschool/,js

```

and here is my filteredls.js

```
var fs = require('fs');
var mydir = process.argv[2];
var ext = process.argv[3];
console.log("args = " + process.argv);
var regx = /\.[js]+$/gi;

fs.readdir(mydir, function (err, list) {
    // if (err) throw err;
    // for(var key in list) {
    //  if (list[key].match(regx)) {
    //      console.log(list[key]);
    //  }
    // }
});
```

i work on linuxmint 16,
my node version is v0.10.21

**Comment by 11cs103** [comment]
![2](https://cloud.githubusercontent.com/assets/5787039/8307207/039a1e54-19db-11e5-83b9-426d39947fbf.png)

this works just fine. passing only one argument.
