### ISSUE TITLE
Stumped on Learnyounode readdir question

### ISSUE THREAD

**Issue by srhoades28** [nodeschool/discussions#1040]
Hello, 

I've been trying this question for too too long now and I was hoping someone might point me in the right direction. Here is what I have some far...

   var fs = require('fs');
   var path = require('path');
   var directoryName = process.argv[2];
   var fileType = process.argv[3];

   function filterByFileType(item){
	   return path.extname(item) === fileType;
   }

   fs.readdir(directoryName, function(err, list){
	   var filtered = list.filter(filterByFileType);
   	   console.log(filtered);
   });

Thanks for the help!

**Comment by davecocoa** [comment]
Just for future reference, it's helpful to show us the output when you tried your solution, and even better if you can explain what you expected to happen compared to what actually happened.

I think your solution is close but there are two parts of the the instructions which it doesn't deal with:

> For example, if you get **'txt'** as the second argument then you will need to filter the list to only files that end with **'.txt'**.

So, this is important, although `process.argv[3]` might be 'txt', you want to filter by '.txt'. Secondly:

> The list of files should be printed to the console, **one file per line**. You must use asynchronous I/O.

Currently your solution prints the whole array at once, I imagine you were probably going to fix this once you were seeing *something* output anyway =)

**Comment by davecocoa** [comment]
Just one more note, I was able to find your problem because I'm familiar with the exercise but if you're troubleshooting it yourself I'd recommend you just try logging more things and don't forget to use `learnyounode run` instead of `learnyounode verify` if you you don't see as much output as you expected to see. So, for example, if you logged `list` that would give you some information, and then logging each `item` would give you a little more, and then the really important bit would be logging `path.extname(item)`.

**Comment by srhoades28** [comment]
Dave, 

Thanks for the advice. Once I started using learnyounode run and logging every object and element step by step, these problems started becomin really easy. I guess it pays to be as systematic and methodical as possible in programming. Thanks!

**Comment by davecocoa** [comment]
That's great! :tada: :confetti_ball: 

If you've gotten past the problem described here could you please close this issue? You can always open a new one any time you get stuck =)

**Comment by kvedantmahajan** [comment]
@davecocoa 

> Currently your solution prints the whole array at once, 

I'm not sure how else to console if not inside the callback `console.log(data)`. I see the results line by line on console, but is there any other way to `readdir`? I think `readdir` is async method. So confused!

**Comment by francesmcmullin** [comment]
@kushalmahajan  Hi Kushal, it sounds like you're having a problem quite different to the one described in this issue, which was closed by the asker in 2015. I recommend opening a new issue with the code you're running and a clear description of what you've tried so far.

**Comment by kvedantmahajan** [comment]
@davecocoa I understood your point later on. never mind
