### ISSUE TITLE
The workshoper "learnyounode" has no content except exercises.

### ISSUE THREAD

**Issue by pgorbas** [nodeschool/discussions#1041]
According ot the website, a "Workshopper is the name used for the open source lesson modules associated with NodeSchool"..

But the chapter contents are NOT lesson nor tutorials as they provide no information or context.  All I am seeing is a exercise to use the skill and knowledge ( that should have been gained by going though this tutorial ) that is is assumed ( without stating ) that you have learned else where.

For instance, Exercise 6, MAKE IT MODULAR, has the student create a small program and that uses a module they are to create.  No where doe it explain what a module is, why one would use it, or how to make one.

According to Wikipedia, "A tutorial is a method of transferring knowledge and may be used as a part of a learning process. More interactive and specific than a book or a lecture; a tutorial seeks to teach by example and supply the information to complete a certain task."

No information is being transfered in these "tutorials", instead they are just testing knowlege gained else where.

**Comment by Sequoia** [comment]
Hm! It sounds like the question is, sort of

## How much context should be added to a lesson?

Stance 1: Nodeschool lessons should be 100% standalone & be 100% self-study ready.  One should be able to walk up to a nodeschool course & start it with no prior knowledge. Any prereq's should be clearly listed somewhere the user will find them before starting the lesson.

Stance 2: Nodeschool lessons are, generally speaking, self-study ready, but they are *not* 100% standalone or your one-stop-shop for everything you need to learn nodejs. They are, rather, a tool to **make it easy to run nodejs workshops** & self-study ready but the user must be prepared to do some legwork/research of her own.

I created sort of a strawman here with "Stance 1" but I think it's fair to say there's no way nodeschool courses can have *all* the information you need to learn everything about node.  For example:

> No where doe it explain what a module is, why one would use it, or how to make one.

Did you google "javascript module"? There is lots of information out there about modules & why to use them.

It's hard to write lessons that are appropriate for beginners, intermediates, and experts-- inevitably it's too hard for some & too boring for others. A balance must be struck between too much info & not enough & I think the answer here ultimately will be [GIYF](http://en.wiktionary.org/wiki/GIYF) & "some assembly required."

## Takeaways

I think you bring up a good point about context. For the course I'm creating I plan to create a readme with:
1. Install instructions
2. A small bit of context-- I assume people taking a workshop on building shell tools know what they are or else why are they taking the workshop, I'm not going to go back to "what is a terminal" etc., the course won't be "everything you need to know about shells from square 1"
3. **Prerequisites**: What you should know going in, links to `learnyounode` and `javascripting` for people who need some fundamentals first
4. FAQ

I do think lessons could use intro text in some way or another & yes, **Make It Modular** does seem to assume you know what a module is & why to use it.  Some lessons make more sense in the context of a workshop where someone can answer questions.  Thanks for bringing this up & for now hit google or here if you get stuck! :smile_cat: 

/cc @rvagg @timoxley @martinheidegger @maxogden

**Comment by martinheidegger** [comment]
"Make It Modular" has too steep of a learning curve imho. Many people get stuck there for various reasons. But else learnyounode doesn't do a all bad job explaining various chapters. Adding a motivational section to the workshoppers definitely will help. In any case: I think we can do better but I feel like the response from @pgorbas is going the wrong way: it would be better to provide actual improvements at actual places rather than general improvement ideas. I don't think that we need or should put up with too many rules for what a "workshopper" is or isn't but I did propose a quality guide for them once: https://github.com/nodeschool/organizers/issues/89

**Comment by pgorbas** [comment]
After i got over my preconception that a tutorial "should be" self contained but instead guide you to the api docs to figure things for yourself ... i found the hole module very helpful indeed. 


Sent from my Galaxy S®III

<div>-------- Original message --------</div><div>From: Martin Heidegger <notifications@github.com> </div><div>Date:04/03/2015  3:01 AM  (GMT-06:00) </div><div>To: nodeschool/discussions <discussions@noreply.github.com> </div><div>Cc: pgorbas <pgorbas@yahoo.com> </div><div>Subject: Re: [discussions] The workshoper "learnyounode" has no content except
  exercises. (#1041) </div><div>
</div>"Make It Modular" has too steep of a learning curve imho. Many people get stuck there for various reasons. But else learnyounode doesn't do a all bad job explaining various chapters. Adding a motivational section to the workshoppers definitely will help. In any case: I think we can do better but I feel like the response from @pgorbas is going the wrong way: it would be better to provide actual improvements at actual places rather than general improvement ideas. I don't think that we need or should put up with too many rules for what a "workshopper" is or isn't but I did propose a quality guide for them once: nodeschool/organizers#89

**Comment by Sequoia** [comment]
# proposal

1. Add a link to a good/concise/accessible article on why to write modules in JS to the **resources** section
2. Call this out in the lesson "If you're wondering why it's important to write modules, see the link in the 'resources' section"

**Comment by bdingwall** [comment]
I just myself got stuck in the same Modules section (Exercise 6 of Leanyouthenode), I think part of the issue is too many moving parts for a tutorial (and partially suggesting the student to use their code for filesystem stuff from the previous lessons is probably a bad idea as I got stuck trying to rework my existing code into a new concept).

I suggest the modules section be isolated from file system work learn in Exercise 5 and focused to be only on how modules can interact (and to verify references are implemented either synchronously or asynchronously, etc.)

**Comment by g3hk** [comment]
Unsubscribe me plz from this junk list

**Comment by martinheidegger** [comment]
@g3hk Please don't be rude. You can choose by yourself what notifications you get on github. Please unsubscribe in the github user interface.

Screenshot:
![screenshot 2015-04-24 00 04 46](https://cloud.githubusercontent.com/assets/914122/7300167/8fc4fa7a-ea15-11e4-890d-5cc50df886f3.png)
