### ISSUE TITLE
How to declare a variable in the command line.

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1043]
Dear Sirs,

Hi!
This is Hans.

I am a novice in Node.js command line.
I tried to declare a variable in the command line, but failed.
The line I made is like this:

       C:\>javascripting>type NUL>variables.js>var example = 'practicing node'

, which looks idiotic.

The declaration of string has the same problem.

Please show me how to do this correctly.
Your help will be greatly appreciated.

B.Regards.

**Comment by Sequoia** [comment]
Hi @Hans-Park! What is your goal here? What do you mean "declare a variable in the command line"?

If you want to execute javascript directly in the shell as it seems you do, launch the node-command-line with the following command:
```
 C:\> node
```

You'll then get a prompt where you can enter javascript:
```
> '  .dlrow olleH  '.split('').reverse().join('').trim();
'Hello world.'
```

Does that help?

**Comment by hwaqhamoda** [comment]
www.hwahamoda.eg.com

**Comment by hwaqhamoda** [comment]
h w a

**Comment by Hans-Park** [comment]
Dear Mr.Sequoia

This is Hans.
First of all, thank you very much for your so soonest reply.

I am learning the challenge of variables of javascripting.

The question is as follows.

0  I created a file named variables.js successfully.
0 Then, I tried to declare a variable named example in this file, but failed.
   How to declare this variable in the file of variables.js?

   Your help will be very helpful and appreciated.

   Sincerely,

**Comment by Sequoia** [comment]
Hi @hans-park! Can you paste the contents of your variables.js? Alternately, tell me if the following works:

### variables.js
```javascript
var example = 'hello';
console.log(example + ' world!');
```

Then
```
C:\> node variables.js
```

**Comment by Hans-Park** [comment]
Hi! Sequoia,

Thank you very much.

I am doing this with Node.js command prompt.

My working sequence as follows.

0  C:\Users\Evil Chan>variables.js  
0  C:\Users\Evil Chan>type NUL>example.js
0  C:\Users\Evil Chan>var example = 'hello';

then, the following diablo appears.

'var is not recognized as an internal or external command, operable program or
batch file.

Thank you.

**Comment by Hans-Park** [comment]
Dear Sequoia,

Hi!

The following codes you sent me does not work.

 var example = 'hello';
 console.log(example + ' world!');

C:\> node variables.js

Thank you.

**Comment by Sequoia** [comment]
@hans-park what happens when you run that? Is an error output?

**Comment by Hans-Park** [comment]
Dear Sequoia,

Hi!
I don't know ,but I think it is an error just like in the above-mentioned messages.

If possible, please tell me step by step how to declare a variable and strings in the command line .
Thank you.

**Comment by Hans-Park** [comment]
Dear Sequoia,
Hi!

We see the challenge of variables. I transfer its all sentences to here as follows.
Please show me how to declare a variable.

'''''''''''
Create a file named variable.js.
In that file declare a variable named example.
Make the variable example equal to the value 'some string'
Then use console.log<> to print the example variable to the console.
Check to see if your program is correct by running this command.
''''''''''''''''
I tried to declare a variable according to the above guideline, but failed.

Thank you.

**Comment by Sequoia** [comment]
Hi @Hans-Park! Tell me if this helps: https://www.youtube.com/watch?v=KCvLTLtRfwI

You do not need to use `vim`, you can use whatever editor you want.  Let me know if that helps!

**Comment by Hans-Park** [comment]
Dear Sequoia,

Hi!
I am sorry. It looks so simple, but It doesn't work.
My editor is Node.js command prompt, and my OS is Windows 7.

I expect that your help will make me to break through this barriers.

Thank you.

**Comment by Sequoia** [comment]
Hi @Hans-Park!

the node.js command prompt is **not an editor**.  Create a file **with a text editor**. If you are using windows, try [notepad++](http://notepad-plus-plus.org/).

Please read the following & if it's still not clear let me know:

1. [What is a text editor](http://www.text-editor.org/)
2. [How to create a text file](http://www.computerhope.com/issues/ch001359.htm)

**Comment by Hans-Park** [comment]
Hi! Sequoia,

After checking, studying every data and information you gave me, I will ask you another helps.
I will be back here soonest.

Thank you so much.

**Comment by Hans-Park** [comment]
Hi!
This is Hans.
Thank you very much.

Date: Sat, 4 Apr 2015 09:45:10 -0700

**Comment by Hans-Park** [comment]
Hi! Sequoia,

I downloaded Notepad according to your guideline, and tried to declare a variable.
I did the same procedure as the displaying in the youtube, which you recommended me to see.
My working sequence in the notepad as follows.
'''''''''''''''''
0  variables.js

  then,

0  var example = ' some string'

  then,

0  console.log()

  then,

0 javascripting verify variables.js

  then,

   Nothing happened. It does not work.

  I don't know why. 
  In the practicing the challenge, they seem to use Node.js command prompt. Don't they?

 Thank you.

**Comment by Hans-Park** [comment]
Hi! Sequoia,

 For practicing the javascripting  here in the nodeschool.io,
the text asks;
   
              open your terminal and run following command.

                                    javascripting

  0  Here, what does "your terminal" mean? Isn't it Node.js command prompt? I am confused because they show how to code   introduction.js file with this Node.js command prompt.

 Thank you.

**Comment by SomeoneWeird** [comment]
Yes, on windows `your terminal` can also mean the `Node.js command prompt`.

The reason your `console.log()` did not do anything is because you did not pass it any arguments, try putting something between the `(` and `)` and see if something happens then.

**Comment by Hans-Park** [comment]
Dear Mr. SomeoneWeird,

Hi!

0  I declared a file variables.js

      type>NUL>variables.js

     then,

0  I declared  a variable named example.

               var example ='some string'

    then, there appears the following text.

      'var' is not internal or external command, operable program or batch file.

    I don't know what this means.

   Your help to overcome this barrier will be very appreciated.

 Thank you.

**Comment by Hans-Park** [comment]
Dear Mr. Brady,
Hi!
Thank you so much for your helping me.
Please check the message I left in the  nodeschool/discussions.
I eagerly need help from you to solve this problem.
Please write  codes step by step for me to understand.
Thank you.

Date: Sun, 5 Apr 2015 01:13:26 -0700

**Comment by Hans-Park** [comment]
Dear Sirs,

The challenge of variables in nodeschool.io is  as follows.

Create a file named variables.js...................(1)
In that file declare a variable named example................(2)
Make the variable example equal to the value 'some string'.................(3)
Then use console.log() to print the example variable to the console...................(4)
Check to see if our program is correct by running this command........................(5))

According to the above instruction, I do as follows.

  (1) to create a file named variable.js, I make a code;

                     type NUL>varable.js

         then,
(2) to declare a variable named example in that file, I make a code;

                    var example = 'some string'

          then, the following diablo appears.

                    'var is not recognized as an internal or external command, operable program or
                     batch file.

       So, I cannot do anymore work. 
        My OS is windows7 ,and editor is Node.js command prompt.

       Please tell me what wrong I did.

      Thank you.

**Comment by martinheidegger** [comment]
@Hans-Park It would be nice if you could enter your answers using the github comment client in [proper markdown](https://help.github.com/articles/github-flavored-markdown/) because its hard to read your comments [here](https://github.com/nodeschool/discussions/issues/1043) without me reformatting your messages. (i had to fix some messages just to be able to somehow read them).

Aside from this:

"Node.js command prompt" is not an editor, its a command prompt that allows you to execute various things.

There are two things of importance: What files do you create? and How you executed them? This is not clear when reading your comments!

Maybe you can write it a little bit more like this:

I created following file:
`variable.js`

```JavaScript
var a = 1;
```

Then I tried to execute it like this:
```
C:\my\folder> javascripting verify variable.js
```

The output was following:

```
-------------------
# O-oh, something isn't working.
# But don't panic!
-------------------
## Check your solution:

Solution
===================
hello


Your Attempt
===================


Difference
===================
hello
````

What did I do wrong?

**Comment by Hans-Park** [comment]
Hi ! Mr. Martinheidegger,
I am sorry. I will rearrange everything. I think I need more basic knowledge about javascript and everything to ask my questions.

Thank you

**Comment by Sequoia** [comment]
@Hans-Park the issue I believe has to do with understanding of the shell. Consider the following:
```
C:\> node example.js
```
The block above can be split into three parts: the **prompt**, the **command** and the **arguments**. In this case:

1. prompt: `C:\>`
2. command: `node`
3. arguments: `example.js`

When you run `javascripting verify yourfile.js` it should look like this:
```
C:\path\to\foo\bar\whatever> javascripting verify yourfile.js
```

1. prompt: `C:\path\to\foo\bar\whatever>`
2. command: `javascripting`
3. arguments: `verify`, `yourfile.js`

:point_right: :warning: **Do not try to edit your file using the command prompt** :warning: Use a text editor

:point_right: :warning: **Do not attempt to run `javascripting` at the `node` prompt, which looks like this: `>`** :warning: You must run it at your cmd.exe or Powershell prompt.

**Comment by Hans-Park** [comment]
Hi! Mr.Sequoia,
Thank you very much for your helping me.

I am learning javascripting here in this site of nodeschool.io.

The Run the workshop of this nodeschool instructs as follows.

          "Open your terminal and run the following command."
                          
                                javascripting

So, I opened  "Node.js command prompt" , because I think
 that the terminal means Node.js command prompt.

In this command prompt, we find an instruction like 

                     "In that file declare a variable named example"

By this instruction, I tried to declare a variable in this command prompt, but
nothing happened as  I told you already.

Furthermore, I tried the same in the Sublime text 3 and also Atom, 
the result is the same.

I'd like to know how to declare a variable in that file just like the instruction asks.

Thank you very much.

**Comment by Sequoia** [comment]
Hey @Hans-Park,

My advice at this point is to find someone in your community/school/family who is a programmer or who is good with computers & ask them for help. I'm afraid I don't know how else to explain what to do! Reread the comments here, read the articles I linked, and see my youtube video. Good luck! :+1:

**Comment by Hans-Park** [comment]
Hi!

Thank you very much. Anyway,  I hope that you would help me in the future. I'll ask your help when I have problems.

   Thank you again.

**Comment by Sequoia** [comment]
@Hans-Park Absolutely! :smile_cat:
