### ISSUE TITLE
How to declare a variable in the command line.

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1044]
Dear Sirs,

Hi!
This is Hans.

I am a novice in Node.js command line.
I tried to declare a variable in the command line, but failed.
The line I made is like this:

       C:\>javascripting>type NUL>variables.js>var example = 'practicing node' , which looks idiotic.

The declaration of string has the same problem.

Please show me how to do this correctly.
Your help will be greatly appreciated.

B.Regards.

**Comment by Sequoia** [comment]
duplicate
