### ISSUE TITLE
Failing completely

### ISSUE THREAD

**Issue by SMikeG** [nodeschool/discussions#1046]
Guys this stuff is not even close to being intuitive.  I got Hello World yeah, but can't get Baby Steps right.

Call me clueless but I don't understand what they are asking us to do - it's just not clear.  Yeah I can figure out that argv is a zero-based array - doesn't state that in the HINT does it?  Then what?

Ready to give up and find another path through this.  Not learning anything except frustration.

And can someone edit the creepy title: "Learn You the Node.js for much win".  Is that some kind of inside joke?

**Comment by SomeoneWeird** [comment]
Have you been through http://github.com/sethvincent/javascripting ? It may be worth going through that if you don't know Javascript yet.

Also yes, the title is a joke. It's based on the same naming as the book [Learn You a Haskell for Great Good](http://learnyouahaskell.com/)

**Comment by SMikeG** [comment]
Thanks Mr. Weird.  I am actually doing that now and it makes a lot more sense.  

Guess I missed that book.  See?  More cluelessness.

**Comment by SomeoneWeird** [comment]
Awesome! Glad you're progressing. If you need more help open another issue :tada:
