### ISSUE TITLE
Javascripting workshopper

### ISSUE THREAD

**Issue by lewisrodneyl22** [nodeschool/discussions#1048]
I've run the command in my terminal and it completes but I'm not sure where to go from here.
below is the input and output in my terminal:

~ RL$ npm install -g javascripting
/usr/local/bin/javascripting -> /usr/local/lib/node_modules/javascripting/index.js
javascripting@1.12.0 /usr/local/lib/node_modules/javascripting
├── diff@1.3.2
├── colors@1.0.3
├── adventure@2.10.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, split@0.3.3, mkdirp@0.5.0, through2@0.5.1, terminal-menu@2.1.1)
└── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.7, cardinal@0.4.4)
~ RL$

**Comment by SomeoneWeird** [comment]
Yep! You've installed javascripting. Now if you just type `javascripting` in your terminal it should run!

**Comment by lewisrodneyl22** [comment]
thank you weird one!

**Comment by SomeoneWeird** [comment]
No problem haha. Open another issue if you have any more problems :)
