### ISSUE TITLE
How do I install javascripting module ?

### ISSUE THREAD

**Issue by amitwalke** [nodeschool/discussions#1049]
I installed nodejs on my windows machine.  After that downlaoded javascripting-master.zip from git. Please explain me further steps to install javascripting module.

**Comment by SomeoneWeird** [comment]
Instead of downloading the zip file, run `npm install javascripting -g` in a terminal. Then run `javascripting` to start the program :)

**Comment by amitwalke** [comment]
Hello,

I am getting below error after running the command  : npm install javascripting –g


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "javascripting" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log

D:\>javascripting
'javascripting' is not recognized as an internal or external command,
operable program or batch file.

Does npm install require admin rights on system ?

Best Regards,
Amit Walke.

**Comment by SomeoneWeird** [comment]
Are you behind a network proxy (maybe at work)?

**Comment by amitwalke** [comment]
Yes. Is that the reason ?

**Comment by SomeoneWeird** [comment]
It looks like your work environment is proxying all your requests through a device.

If you can figure out what the proxy host you're supposed to be using is, run `npm config set https-proxy “http://<proxy-name>:<proxy-port>” and you should be able to use npm.

**Comment by amitwalke** [comment]
Looks like it worked but after running command ‘javascripting’ at command prompt  error not recognized as an internal or external command is coming.

D:\>npm install javascripting -g
C:\Users\amit_walke\AppData\Roaming\npm\javascripting -> C:\Users\amit_walke\App
Data\Roaming\npm\node_modules\javascripting\index.js
javascripting@1.12.0 C:\Users\amit_walke\AppData\Roaming\npm\node_modules\javasc
ripting
├── diff@1.3.2
├── colors@1.0.3
├── adventure@2.10.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, mkdirp@0.5.0,
split@0.3.3, through2@0.5.1, terminal-menu@2.1.1)
└── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.7, cardinal@0.4.4
)

D:\>javascripting
'javascripting' is not recognized as an internal or external command,
operable program or batch file.

Best Regards,
Amit Walke.

**Comment by martinheidegger** [comment]
The error "is not recognised as an internal or external command" means that the PATH variable is not setup properly for some reason. Usually windows needs a restart for the PATH to be set right (for a reason I don't quite understand). In any case: it might be broken. Maybe running the [Node Command Prompt](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#windows) will works.

**Comment by riyadhalnur** [comment]
i would recommend trying to reinsintall node for windows with the .msi file. it will have an option to add node to `PATH`. see if that helps. if not, then you have to place it manually in the `PATH` variable.

**Comment by amitwalke** [comment]
My PATH variable on windows has this value :

C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Wind
owsPowerShell\v1.0\;C:\Program Files\PuTTY;C:\Program Files\nodejs\

Nodesj is in PATH.  Am I missing something here ?

**Comment by riyadhalnur** [comment]
Remove the trailing slash from the path. so it would be this `C:\Program Files\nodejs`

**Comment by riyadhalnur** [comment]
After you've got Node running, just follow the steps listed for the Javascripting module
