### ISSUE TITLE
HTTP UPPERCASERER does not pass/fail consistently

### ISSUE THREAD

**Issue by nadescape** [nodeschool/discussions#105]
First, here is my code for this problem:

``` js
var http = require('http');
var map  = require('through2-map');

var server = http.createServer(function(req, res) {
    if(req.method !== 'POST')
        return res.end('POST please');

    req.pipe(map(function(chunk) {
        return chunk.toString().toUpperCase();
    })).pipe(res);
});

server.listen(8000);
```

When I verify this, it does not pass or fail consistently. Sometimes it will pass, but sometimes it will fail with "" and null in either the actual or expected columns, and an uppercase word in the other, like I would expect. I've compared my code with issue https://github.com/nodeschool/discussions/issues/25 and it looks like I'm doing this same thing, so I'm not sure if the issue is in my code or with the test data learnyounode is using to verify.

**Comment by danielcdeng** [comment]
The following is my working code including the test html.

	// Command: node 12_http_uppercaser.js 8000

	var http = require('http');

	var postHTML = 
		'<html><head><title>Post Example</title></head>' +
		'<body>' +
		'<form method="post">' +
		'Input 1: <input name="input1" value=""><br>' +
		'Input 2: <input name="input2" value=""><br>' +
		'<input type="submit">' +
		'</form>' +
		'</body></html>';

	var server = http.createServer(function(req, res) {
		var body = "";
		req.on('data', function(chunk) {
			body += chunk;
		});
		req.on('end', function() {
			res.writeHead(200);
			if(postHTML) {
				res.end(postHTML);
				postHTML = undefined;
			}
			else if(body.length > 0) {
				res.end(body.toUpperCase());
			}
		});
	});

	console.log('Listening on http port ' + process.argv[2] + ' .........');
	server.listen(+process.argv[2]);
