### ISSUE TITLE
juggling async, part of expected result missing

### ISSUE THREAD

**Issue by vtoomas** [nodeschool/discussions#1050]
Hi, 

Could someone help me to understand what is wrong with my following solution?
I've scanned some other working solutions which are almost identical to mine, but can't see the problem in mine. 

```javascript
var http = require('http');
var urls = [process.argv[2], process.argv[3], process.argv[4]];
var count = 0; 
var printArr = ["","",""];

function runUrl(i) {
	var url = urls[i];
	var req = http.get(url);
	req.on('response', function(resp) {
		resp.on('data', function(data) {
			printArr[i] += data.toString(); 
			
		});
		resp.on('end', function() {
			count++;
			if (count == urls.length - 1) {
				PrintInfo();  
			}
		})
	});
	req.on('error', function(e) {
	  console.log('problem with request: ' + e.message);
	});
	req.end();
}

function PrintInfo() {
	printArr.forEach(function(urldata) {
		console.log(urldata);
	})
}
for (i=0;i<urls.length;i++) {
	runUrl(i);
}
```

I always get one response incomplete like following: 

1.  ACTUAL:    "As dry as a cream heaps she'll be right squizz. She'll be right
bradman flamin flat out like a pint. "
1.  EXPECTED:  "As dry as a cream heaps she'll be right squizz. She'll be right
bradman flamin flat out like a pint. "

2.  ACTUAL:    "Come a aussie salute to we're going two up. He hasn't got a tuck
er-bag where as busy as a sickie. Come a struth when we're going ute. "
2.  EXPECTED:  "Come a aussie salute to we're going two up. He hasn't got a tuck
er-bag where as busy as a sickie. Come a struth when we're going ute. "

3.  ACTUAL:    "Lets get some kindie when he's got a massive trackies. Mad as a
captain cook flamin as cunning as a chuck a yewy. Stands out like a "
3.  EXPECTED:  "Lets get some kindie when he's got a massive trackies. Mad as a
captain cook flamin as cunning as a chuck a yewy. Stands out like a dob with bui
lt like a doovalacky. Grab us a down under my grab us a g'day. She'll be right c
ut lunch commando with lets get some true blue. "

**Comment by martinheidegger** [comment]
It looks like you end it a little too early!

```JavaScript
if (count == urls.length - 1) {
```

shouldn't this be `urls.length` without the `-1`?

**Comment by vtoomas** [comment]
@martinheidegger It somehow works, but I'm still confused. 

This is in event listener for `end` response. My logic says I should have had a response less not a partial response? 
Also, `urls.length` gives value `3`, but my `count` starts at `0`, so the `-1` seems appropriate?

**Comment by martinheidegger** [comment]
@vtoomas Your count starts at `0` but  before checking the result you increase the value by `1` so: when the first one is finished the count will be `1`. When the second one will be finished the count will be `2` (if you add `-1` then the if will take place here) by the third one it will become `3` so it should be `if (count === 3)` Unless I mistake something?! :smile:

**Comment by vtoomas** [comment]
@martinheidegger You are correct. Guess it's my time to have some sleep :D

I still can't figure out why it eats a part of my response i.o. one whole response. And it varies whether the response missing a part is 1st, 2nd or 3rd request.
