### ISSUE TITLE
I am not able to run all of my code on c9.io

### ISSUE THREAD

**Issue by McQuinTrix** [nodeschool/discussions#1052]
I want to run learnyounode , expressworks and npm. But all the tests are not passing. For example in expressworks I was able to run "The Stylish CSS" challenge but I was not able to run the first challenge. Can anyone help me set it up in c9.io?

**Comment by Sequoia** [comment]
@McQuinTrix Can you add some more info? What do you mean you were "not able to run" the first challenge? If you can post the steps you took, issues you ran into, and any error output that would make it easier to help! :smile_cat:
