### ISSUE TITLE
What is the solution for MAKE IT MODULAR on the core Workshop

### ISSUE THREAD

**Issue by jpfernandezl** [nodeschool/discussions#1053]
I have the following code but does not work

```JavaScript
function listFiles(directory, extension, callback){
  extension = '.' + extension;

  var fs = require('fs');
  var files_array = fs.readdir(directory, function(err, data){

    extension = '.' + extension;
    var files_array = [];
    for (var i=0; i<data.length; i++) {
      if ( data[i].indexOf(extension, data[i].length - extension.length) !== -1     ) {
        files_array.push( data[i] );
      }
    }
    return files_array;
  });
  callback(null, files_array);
}

module.exports = {
   listFiles: listFiles
}
```

**Comment by davecocoa** [comment]
"does not work" is not very descriptive. Could you explain your problem some more? It helps if you tell us what you expected to see happen, what you saw happen instead and what you've tried so far, also if you can show us the contents of *both* files. Did you get the previous exercise to pass?

Looking at your code, I have a few questions.

 - Why do you have `extension = '.' + extension;` twice?
 - What do you expect to happen when you do `var files_array = fs.readdir(directory, function(err, data){` ?
 - Have you checked the documentation of [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_callback) to see what it returns? (note: if a return type is not mentioned it often means that a function does not return anything)
 - Have you tried adding `console.log` at different places in the code, to check what your variables look like?

**Comment by jpfernandezl** [comment]
Hi,

I am new to node but I have years of experience with PHP.
I am trying to do the following exercise from the node core Workshop


 LEARN YOU THE NODE.JS FOR MUCH WIN!
─────────────────────────────────────
 FILTERED LS
 Exercise 5 of 13

Create a program that prints a list of files in a given directory, filtered by t
he extension of the files. You will be provided a directory name as the first ar
gument to your program (e.g. '/path/to/dir/') and a file extension to filter by
as the second argument.

For example, if you get 'txt' as the second argument then you will need to filte
r the list to only files that end with .txt. Note that the second argument will
not come prefixed with a '.'.

The list of files should be printed to the console, one file per line. You must
use asynchronous I/O.

-------------------------------------------------------------------------------

## HINTS

The fs.readdir() method takes a pathname as its first argument and a callback as
 its second. The callback signature is:

    function callback (err, list) { /* ... */ }

where list is an array of filename strings.

**Comment by martinheidegger** [comment]
@jpfernandezl Additionally to the points that @davecocoa mentioned: It says that you should export a method, not an object.
