### ISSUE TITLE
Error in Node.js Command Prompt : "No adventure is currently selected. Select an adventure from the menu"

### ISSUE THREAD

**Issue by YSundeep** [nodeschool/discussions#1055]
I am getting this error "No adventure is currently selected. Select an adventure from the menu". 

I have started learning node.js from node school and in the first section of tutorial , it asks us to learn basics of java scripting . I have run the command and it did something . Later went to problems sections and created a new file and run the command . It shows this error . Am i missing anything ?Please help me

**Comment by SomeoneWeird** [comment]
Which adventure are you going through? `javascripting` or `learnyounode`?

**Comment by YSundeep** [comment]
I am going through javascripting.

**Comment by YSundeep** [comment]
can some one explain me this "adventure" thing ? what exactly does that mean ?

**Comment by SomeoneWeird** [comment]
Have you run `javascripting` in your terminal and selected the first problem?

**Comment by YSundeep** [comment]
I have run it . It showed me a menu in command prompt . I selected the Variables section . It showed me description of variables in javascript . I have already created a file variable.js . So i ran the command "javascripting verify variable.js"  and it shows this errro "{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }"

**Comment by SomeoneWeird** [comment]
What OS are you on?

**Comment by YSundeep** [comment]
I am working on Windows 7

**Comment by SomeoneWeird** [comment]
Do you know what terminal you are using?

**Comment by YSundeep** [comment]
I am using node.js terminal

**Comment by YSundeep** [comment]
Can you please let me know the steps i have to follow to get this done ?

**Comment by lalitb** [comment]
I am also getting same error as below :+1: 

$ uname -a
Linux lalitb 3.2.0-4-486 #1 Debian 3.2.60-1+deb7u3 i686 GNU/Linux
$ cat introduction.js 
console.log('hello')
$ javascripting verify introduction.js
ERROR: No adventure is currently selected. Select an adventure from the menu.
$

**Comment by madhurgarg71** [comment]
Hello everyone I was also facing same problem with Node.js terminal or cmd. Then I switched to Git and I got the problem solved.You can download git from here http://git-scm.com/

**Comment by SomeoneWeird** [comment]
Please reopen if needed.
