### ISSUE TITLE
first i/o challenge

### ISSUE THREAD

**Issue by haasDev** [nodeschool/discussions#1057]
I am getting an empty string when I do the following code

```JavaScript
var fs = require('fs');

var buf = fs.readFileSync('/Users/haaser84/Documents/development/learning/node/learnyounode/file.js');

var str = buf.toString();

var arr = str.split('\n');

console.log(arr);
```

**Comment by finnp** [comment]
Is there any chance that the file is empty? So when you do `console.log(str)` it will be empty as well?

**Comment by subch** [comment]
@finnp is correct. If you run your code w/ the file instead pointing at a file containing any data, it will return the data in an array.

**Comment by rachit-thariani** [comment]
May be your file is empty..check it with  console.log(arr.length);
