### ISSUE TITLE
How to use global variables - http collect

### ISSUE THREAD

**Issue by cytalansky** [nodeschool/discussions#1058]
I'm trying to the nodeschool tutorials and I'm not sure why this doesn't work
It looks like the bl is a global variable but does not seem to be keeping it's data once I go out of the       http.get function's scope?

```JavaScript
BufferList = require('bl')
var http = require('http')

bl = new BufferList()
http.get(process.argv[2], function (response) {
   response.setEncoding('utf8')
   response.on('data', function (chunk) {
       bl.append(chunk)
   });
   response.on('error', console.error)
})
console.log( bl.length)
console.log(bl.toString())
```

**Comment by finnp** [comment]
Hey, the reason is not that `bl` is not keeping its data, but that it is not assigned yet. The reason for that is that `http.get` is asynchronous. So, `console.log(bl.length)` is evaluated directly after the http.get() call, but the callback `function(response) {}` is only called when the http.get request data is incoming.

It's similar to this example:
```
var bl = 1
setTimeout(function() {
   bl = 2
}, 1)
console.log(bl) // prints `1`
```

Does this help?

**Comment by cytalansky** [comment]
Yes thanks!

**Comment by cytalansky** [comment]
Would this be considered a correct way to do it I see the official answer is different is there something wrong with this way?

    var BufferList = require('bl')
    var http = require('http')

    bl = new BufferList()
    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', function (chunk) {
        bl.append(chunk)
      });
	response.on('end', function (chunk) {
		console.log( bl.length)
		console.log(bl.toString())
      });
       response.on('error', console.error)
    })

**Comment by martinheidegger** [comment]
@cytalansky The "official answer" is only one way to solve the exercise. As long as what you do passes the test you can rearrange it as you want. However: In your example you used "bl" which isn't cheating but some people learn more from the exercise without external libraries. Sorry for the late feedback. Does that answer your question?
