### ISSUE TITLE
My first i/o challenge

### ISSUE THREAD

**Issue by Oscar3124** [nodeschool/discussions#1059]
My code works, but I just dont know what file is using the test.  I can´t complete the challenge.

![image](https://cloud.githubusercontent.com/assets/8062498/7081512/4c043350-df11-11e4-8742-d674ea50abdb.png)

``` javascript
var fs = require('fs');

// 'fs.html is a file I  created'
var buff = fs.readFileSync('program.js')
	.toString().split('\n');

console.log(buff.length + 1);
```

**Comment by SomeoneWeird** [comment]
Use one of the values from `process.argv` as the argument to `readFileSync`
