### ISSUE TITLE
can't install git-it

### ISSUE THREAD

**Issue by PokimLee** [nodeschool/discussions#1060]
npm WARN engine github-oauth@0.0.4: wanted: {"node":"v0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})

**Comment by finnp** [comment]
Hey, that is only a warning not an error. Are you able to run "git-it" after the installation?

**Comment by PokimLee** [comment]
thx, after installing the old Version of node, problem solved :)

**Comment by SomeoneWeird** [comment]
:tada:
