### ISSUE TITLE
Regarding challenge 7

### ISSUE THREAD

**Issue by jayadrath** [nodeschool/discussions#1061]
I have completed the 6th exercise but am wondering about the workings of the response.on function. From what I can infer from the output of the exercise is that the response.on function gets called multiple times until the entire 'data' is read from the stream. Am I correct in my assumptions?

**Comment by martinheidegger** [comment]
@jayadrath Thank you for your question. There is one important problem with it though. There are many tutorials on the Nodeschool page. What tutorial are you writing about? (I assume learnyounode)

"response.on" is a method to listen to an event. It's important to mention which event! Because the events are sent at different times and occasions. For example the `res.on('error', ...)` event is called only when an error occurs. Now having said that: the `data` event can occur after a response started for zero (I believe zero is a possibility, not entirely sure about that), one or multiple times *before* the `end` event as long as no `error` occurs.

Is that an answer to your question?

**Comment by jayadrath** [comment]
@martinheidegger Thank you for your prompt response. Yes I was referring to the learnyounode tutorial. What I am trying to say is that when I call the response.on function for receiving data, does it just receive the event one time or multiple times based on the amount of data. Let me illustrate what I mean to say:

http.get(url,callback);
function callback(response){
	response.setEncoding("utf8");
	response.on("data", function(data){
		console.log(data);
	});
	response.on("error", console.error); // Equivalent to function(data){console.error(error)}
}

When I run the above function will the console show all the data in the that is received as a response?

Thanks.

**Comment by martinheidegger** [comment]
A method that listens to an event is called listener. Say you have the function:

'''JavaScript
function myListener(){}
'''

and you make it listen to an event;

'''JavaScript
res.on("data", myListener)
'''

Then the listener will be called on every data event that the Eventemitter

**Comment by jayadrath** [comment]
@martinheidegger 

Thank you for the response. This is confusing to me as the problem statement for the next challenge is:

Write a program that performs an HTTP GET request to a URL provided to you as the first command-line argument. Collect all data from the server (not just the first "data" event) and then write two lines to the console (stdout).

The first line you write should just be an integer representing the number of characters received from the server. The second line should contain the complete String of characters sent by the server.

Note the problem statement says "all data". What is the difference?

**Comment by martinheidegger** [comment]
There is no difference. it just tries to be clear :) (I think it was possible to finished the former section with `once` correctly)

**Comment by jayadrath** [comment]
Please can you let me know of what went wrong in the below code for challenge 8(Correction on the challenge name: for the thread, it was 7)
var http = require('http');

var url = process.argv[2];

var userData = "";

http.get(url,callback);
function callback(response){
	response.setEncoding("utf8");
	response.on("data", function(data){
		userData +=data;
	});
	console.log(userData);
	response.on("error", console.error); // Equivalent to function(data){console.error(error)}
}

**Comment by martinheidegger** [comment]
Writing `res.on("anything", ...)` means you **registered** something to happen on this event. Then you can continue doing other things before at some point the event is triggered. In your case you registered on the data event but then you try to log the `userData` before any event could have possibly been sent.  Maybe you need to do that after the response has ended?

**Comment by jayadrath** [comment]
@martinheidegger  Hi Martin, thanks for the answer. I finally figured out the problem. You are right. Since I need to log the data after the response has been fully sent. I did the following and it worked:

http.get(url,callback);
function callback(response){
	response.setEncoding("utf8");
	response.on("data", function(data){
		userData +=data;
	}).on('end', function(){
		console.log(userData.length);
		console.log(userData);
	});
	response.on("error", console.error); // Equivalent to function(data){console.error(error)}
}
