### ISSUE TITLE
Make it modular, unexpected test failure

### ISSUE THREAD

**Issue by Maplesoup** [nodeschool/discussions#1063]
Ok so I'm attempting to do this test, and I'm pretty sure I've got it nailed. But then i get this error.

![nodeissue](https://cloud.githubusercontent.com/assets/7526769/7102035/5c4cd7a2-e06b-11e4-9770-79ecbb0db1cd.PNG)

And here is the code I'm using, Can anyone help me out with this.

    var myModule = require('./module.js');

    myModule(process.argv[2], process.argv[3], function(err, arr){
      if(err)
        console.log(err);
      else{
        for(var i = 0; i < arr.length; i++)
        {
            console.log(arr[i]);
        }
      }
    });

And the code for my module

    var fs = require('fs');
    var path = require('path');
    
    module.exports = function(dir, ext, callback){
      fs.readdir(dir, function(err, arr){
        if(err)
          return callback(err);

        var dataArr = Array();

        for(var i = 0; i < arr.length; i++)
        {
          var pathExt = path.extname(arr[i]);
          if(pathExt !== ext && pathExt.indexOf(ext) > -1){
            dataArr.push(arr[i]);
          }
        }
    
        callback(null, dataArr);
      });
    };

Also any tips are welcome, I'm not new to javascript but I'm not an everyday user.

**Comment by martinheidegger** [comment]
It says "Your solution to Filtered LS failed". Maybe it would be good to select "MAKE IT MODULAR" ? ;)

**Comment by Maplesoup** [comment]
God damn it, sorry for wasting your time on this one.

The thought did occur to me at one point "how does it know which task I'm attempting" 

I'm an idiot haha
