### ISSUE TITLE
Juggling Async

### ISSUE THREAD

**Issue by jayadrath** [nodeschool/discussions#1064]
I am facing an issue in this particular challenge. Here is my code:

```JavaScript
var http = require('http');

var dataArray = [];

var count = 0;
var index = 0;

for (var i = 2;i < process.argv.length; i++) {
	http.get(process.argv[i],callback);
}	

function callback(response){
	var userData = "";
	var callbackIndex = index++;
	response.setEncoding("utf8");
	response.on("data", function(data){
		userData +=data;
	}).on('end', function(){
		dataArray[callbackIndex] = userData;
		count++;
		printData();	
	});
	response.on("error", console.error); // Equivalent to function(data){console.error(error)}
}

function printData()
{
	if (count === 3) {
		for (var j = 0;j < count; j++){
			console.log(dataArray[j]);
		}

	}	
}
```

Here is the test results:

![juggling-async](https://cloud.githubusercontent.com/assets/4255189/7104393/6942e600-e0fb-11e4-9da1-dd8b2f504df9.png)

As you can see, even though I have specified a variable callbackIndex to assign an order to the callbacks it is still printing in a random order. 

Any help would be much appreciated. Thanks.

**Comment by davecocoa** [comment]
You need to pay really close attention to when each piece of code gets run. This line:

`var callbackIndex = index++;`

gets run inside your `http.get` callback, so after a response is ready. There is no guarantee that the three responses will become ready in the correct order, therefore your `callbackIndex` has no guarantee of being in the correct order.

**Comment by jayadrath** [comment]
Thanks, I got it. The index should be a variable that remains same for a particular callback.
