### ISSUE TITLE
Juggling Async - once again

### ISSUE THREAD

**Issue by StefanKrauth** [nodeschool/discussions#1065]
Hi,

I think I know the error, but I'm unable to figure out how to fix it.

```js
var http = require('http');

var result = [];
var count = 0;

for (var i = 2; i < process.argv.length; i++) {
	http.get(process.argv[i], readResponse);
}

function readResponse(response) {
	var body = '';
	response.setEncoding('utf8')
	response.on("data", function (data) {
		body += data.toString();
	});
	response.on("end", function () {
		result[count] = body;
		writeOutput();
		count++;
	});
	response.on("error", console.error);
}

function writeOutput(){
	if(count === 2){
		for (var i = 0; i < result.length; i++) {
			console.log(result[i]);
		}
	}
}
```

I think the http.get() fires up right away. So I assume, there are three http.get() functions executed in parallel. Each of them call readResponse() when complete.

I was trying to implement a counter, but I think setting count++ the the readResponse is already too late.

My thought about how it should work (without looking at the solution) is that , I would have to pass the counter when calling the readResponse callback inside the http.get loop. Something like this:

```js
for (var i = 2; i < process.argv.length; i++) {
	http.get(process.argv[i], readResponse(res, i));
}
```

Another way that came to my mind would be some kind of a process ID back from the http.get() function. Like something that looks like...

```js
var process = [];
for (var i = 2; i < process.argv.length; i++) {
	process[i] = http.get(process.argv[i], readResponse);
}
```

Then I would need something to relate the response to the process so I can pick up the ID in the response and save my result with it. Then I know which is is the calling order and I can relate the response order. Am I thinking into the right direction?

Kind Regards,
Stefan

**Comment by jkbits1** [comment]
Hi, thanks for being so clear about your code and your thinking, that's really helpful :+1: 

Your first suggestion ``` readResponse(data, i) ``` is closest in principle to the way this is done in Node. But, as we cannot change the parameter list of the function, we need another way to access ```i``` within the function. This is done by using something called a closure, which can be a tricky concept to get your head around at first.

A closure is created when one function is defined within another function. The inner function can then access any vars defined, or available, in the outer function. To do that here, take your definition of the function ```readResponse``` and put it in the actual ```http.get``` call. Then, wrap the ```http.get``` call itself in a function that takes ```i``` as a param (notice that you now have an inner function defined within an outer function). Then, this outer function is called in your ```for``` loop.  You can then change ```result[count]``` to ```result[i-2]```, just as if you'd passed ```i``` as a param.

Please feel free to ask more questions, as this is strange as first, and hard to describe well :smile:

**Comment by StefanKrauth** [comment]
Hi jkbits,
thanks! I think you explained it very well. So this way the inner function can access the outer function variables do to the fact the definition is inside the outer function? I'll ask google about closures...

Thank you very much for the hint!

**Comment by jkbits1** [comment]
@StefanKrauth It's a pleasure, I'm glad my response was helpful :smile: 
Thanks for your positive comments about my explanation, it is a quite tricky concept to put into words (and it would spoil the fun to simply provide the full answer). Your single sentence sums it up completely and correctly. It's a very common technique in Javascript code, and a very useful one.

Good luck, and more questions are always welcome here!
