### ISSUE TITLE
learnyounode : Cannot switch to old mode now

### ISSUE THREAD

**Issue by sindhukashyap** [nodeschool/discussions#1066]
When i run learnyounode after installing with "sudo npm install learnyounode -g" on MacOSX, i get the below error.

```
_stream_readable.js:74
throw new Error('Cannot switch to old mode now.');
```
I have node version 10.31 and npm version 1.4.27 installed on my MacOSX.

Please help me resolve this.

**Comment by finnp** [comment]
This might be an issue with npm. Could you try updating npm by running `sudo npm install npm -g` ?

**Comment by sindhukashyap** [comment]
I tried that, and updated to version 2.7.6, but the same error shows up.

**Comment by finnp** [comment]
Mh, I tried to replicate that issue with learnyounode and node -v0.31.31, but it worked for me. Could you install the latest node `v0.12.2`?

What MacOSX version are you using? Is there some more error output other than the one you posted?

**Comment by sindhukashyap** [comment]
Thank you so much that worked! I just updated node to the latest version. I am using Mac OS 10.10.1

**Comment by finnp** [comment]
Awesome :cherry_blossom: Have fun learning!
