### ISSUE TITLE
learnyounode

### ISSUE THREAD

**Issue by SeaBassTian** [nodeschool/discussions#1068]
Hello. My installation seems to have gone well but when I try to run it I get the following error: throw new Error(Cannot switch to old mode now.) and a lot of other gibberish. Not sure if I'm able to proceed.

**Comment by jasongroulx** [comment]
Im also experiencing the same error.

**Comment by finnp** [comment]
Please also open an issue over here: https://github.com/rvagg/learnyounode/issues (if there isn't a similar one yet). Thank you!

**Comment by finnp** [comment]
It already getting fixed: https://github.com/rvagg/learnyounode/issues/270. Closing this for now. Let us know if you have any more problems.
