### ISSUE TITLE
Connecting to MongoDB via NodeJS

### ISSUE THREAD

**Issue by PriyaVasudevan** [nodeschool/discussions#1069]
I am fairly new to NodeJS and am just trying my hands with the same - I have the following piece of code for connectivity with mongoDB
```
// Retrieve
var MongoClient = require('mongodb').MongoClient;

// Connect to the db
MongoClient.connect('mongodb://localhost:27017/hello1', function(err, db) {
  if(!err) {
    console.log("We are connected");
  }
});
```
I understand that the last parameter in the connection string refers to the database name. Apparently I have no DB with the name hello1 
show dbs in mongoDB displays the following:
```
> show dbs
admin  (empty)
kbase  0.078GB
local  0.078GB
```

I had expected the NodeJS code to exit without printing "we are connected".But when I execute the js file,I notice the following::
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
We are connected
```

Do let me know if the DB name isn't verified.

**Comment by SomeoneWeird** [comment]
That error is only a warning, it means you don't have `gcc` (and `g++`) installed, so your code actually worked! What OS are you on?

**Comment by PriyaVasudevan** [comment]
Windows 7 64-bit

**Comment by finnp** [comment]
MongoDB does create your database automatically when you connect to it and store data in it (as far as I can tell). Compare the documentation over her: http://mongodb.github.io/node-mongodb-native/

If you think there is an issue with mongodb, follow these steps to create an isseu: https://github.com/mongodb/node-mongodb-native#bugs--feature-requests
