### ISSUE TITLE
javascripting if-statement.js

### ISSUE THREAD

**Issue by Jonny-Suede** [nodeschool/discussions#1073]
I could use some help with the javascripting if-statement tutorial. 
The problem posed is:
## The challenge:

Create a file named if-statement.js.

In that file, declare a variable named fruit.

Make the fruit variable reference the value orange with the type of String.

Then use console.log() to print "The fruit name has more than five characters."
if the length of the value of fruit is greater than five.
Otherwise, print "The fruit name has five characters or less."

Check to see if your program is correct by running this command:

javascripting verify if-statement.js

Here is the code for my if-statement.js
var fruit = 'orange';
if (fruit.length > 5)
{ 
  
  console.log('The fruit name has more than five characters.');

}
else 
{
console.log('The fruit name has five characters or less.');
}

And here is the error message I receive when I verify my code:
# O-oh, something isn't working.

# But don't panic!

-------------------
## Check your solution:

Solution
===================

14

Your Attempt
===================

The fruit name has more than five characters.

Difference
===================

The fruit name has more than five characters.14

Any help would be appreciated.

**Comment by SomeoneWeird** [comment]
Have you selected the correct problem?

**Comment by Jonny-Suede** [comment]
Hello. Thanks for the response Adam. I was able to correct the problem. 
 Raymond J. Guenther

**Comment by SomeoneWeird** [comment]
Awesome :)
