### ISSUE TITLE
Load Webpages on 2 separate devices on keypress?

### ISSUE THREAD

**Issue by nbalcom** [nodeschool/discussions#1074]
Hi folks. I'm looking for a way to trigger an on key event to load web pages on 2 separate devices. Anyone have ideas? I want to assign 4 different keys to call web pages on 2 tablets when keys are pressed. 

Currently I'm running a node server that only restarts 2 tablets at a certain time. Now I need to create an option that reacts on keypress. When device 1 loads html.1 device 2 needs to load html.2. All in all I have 4 pages I'm looking to load on keypress.

**Comment by martinheidegger** [comment]
To trigger anything on another client than the javascript thats already running it would be probably best to start a socket server. Did you look into http://socket.io/ ?

**Comment by nbalcom** [comment]
Sorry I got pulled off of my project to work on something else for a week. Thanks  martinheidegger. I'll have to install socket.io. There's another guy here using it on a project he's working on as well. I'm a Nodejs nube so any guidance is appreciated while I'm learning.

**Comment by martinheidegger** [comment]
Well, going through the tutorials on the nodeschool site certainly helps. At least `learnyounode` and `how-to-npm` ones are really important. `socket.io` does have a few different concepts but overall it should be easy to get into it.

**Comment by nbalcom** [comment]
Thanks for the feedback. I'm running into errors right now when trying to install anything so I'll have to sort that out first, but I am slowly getting there.

**Comment by martinheidegger** [comment]
Alright. I am closing this issue. Just open a new one when you have a question :+1:

**Comment by nbalcom** [comment]
Cool beans thanks so much for the direction.
