### ISSUE TITLE
Javascripting 1st challenge 'hello', verification error

### ISSUE THREAD

**Issue by ssherm76** [nodeschool/discussions#1075]
Hi, any help would be appreciated.

I'm running Node v 0.12.2 <x64> and npm v2.7.4 on Windows 7 Professional (64 bit).

I'm attempting to go through the Javascripting tutorial from nodeschool.io.  I followed the instructions to install NodeJS, and then install Javascripting with npm.  I opened the terminal and ran the javascripting workshop, selected 'Introduction' from the menu, and followed the instructions to create the javascripting directory, and then changed the directory to the javascripting folder.  I created a file named introduction.js (using notepad) which contains the following:

console.log<'hello'>;

I saved the file in the Javascripting directory.  All went smoothly until I tried to verify the file.  Please see below.

```
C:\Users\ssherm76\javascripting>javascripting verify introduction.js
{ [Error: Command failed: C:\windows\system32\cmd.exe /s /c "node "C:\Users\sshe
rm76\javascripting\introduction.js""
C:\Users\ssherm76\javascripting\introduction.js:1
tion (exports, require, module, __filename, __dirname) { console.log<'hello'>;
                                                                             ^
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\windows\\system32\\cmd.exe /s /c "node "C:\\Users\\ssherm76\\javascr
ipting\\introduction.js""' }

C:\Users\ssherm76\javascripting>
```
I uninstalled and reinstalled twice, and can't figure out what's wrong.  Any ideas?

Thanks,
Steve

**Comment by dominhhai** [comment]
Did you try with `console.log('hello');`?
`()` instead of `<>`

**Comment by ssherm76** [comment]
You're a genius!  Thank you very much.
