### ISSUE TITLE
baby steps????

### ISSUE THREAD

**Issue by alenda** [nodeschool/discussions#1076]
```JavaScript
console.log(process.argv);

for(1 = 0; i < 3; i++) {
   process.argv[1] += process.argv[2] += process.argv[3];
}
```

this is not correct for sure, what is?

**Comment by dominhhai** [comment]
for(**1 = 0**; i < 3; i++)
`1 = 0`? I don't understand what you want to say.

**Comment by alenda** [comment]
ya, I apologize, 1 is i ... 

this is question in learnyounode:
__________________________________________________________________________
To get started, write a program that simply contains:

    console.log(process.argv)

Run it with node program.js and some numbers as arguments. e.g:

    $ node program.js 1 2 3

In which case the output would be an array looking something like:

    [ 'node', '/path/to/your/program.js', '1', '2', '3' ]

You'll need to think about how to loop through the number arguments so  you can output just their sum. The first element of the process.argv array is always 'node', and the second element is always the path to your program.js file, so you need to start at the 3rd element (index 2), adding each item to the total until you reach the end of the array.

Also be aware that all elements of process.argv are strings and you may need to coerce them into numbers. You can do this by prefixing the property with + or passing it to Number(). e.g. +process.argv[2] or Number(process.argv[2]).;
______________________________________________________________________
this is what I've done and is not correct:
console.log(process.argv);

for(i = 0; i < 3; i++) {
   process.argv[1] += process.argv[2] += process.argv[3];
}

**Comment by dominhhai** [comment]
Firstly, declare your var before using it. e.x:
`for (var i = 0; i < 3; i ++)`

Secondly, read the tutorial carefully again.
> you need to start at the 3rd element (index 2), adding each item to the total until you reach the end of the array

> Also be aware that all elements of process.argv are strings and you may need to coerce them into numbers

Thirdly, print out your sum of input params, not `process.argv`.
