### ISSUE TITLE
Can't run learnyounode

### ISSUE THREAD

**Issue by manmon42** [nodeschool/discussions#1077]
I have installed learnyounode through npm with the -g thing, but when I try and run learnyounode, I get  'RefrenceError: learnyounode is not defined' Any and all help would be welcome.

**Comment by SomeoneWeird** [comment]
Yup! You're trying to run `learnyounode` while inside the node prompt, try just running it at your normal command line.

**Comment by manmon42** [comment]
Then I get 'Error: Cannot switch to old mode now'

**Comment by SomeoneWeird** [comment]
Yep, try upgrading node to 0.12, this is a bug with the current version of `learnyounode`, but it doesn't happen if you install the latest version of node.

**Comment by manmon42** [comment]
Thanks, that solved the problem.
