### ISSUE TITLE
Make it modular Problems

### ISSUE THREAD

**Issue by oxylius** [nodeschool/discussions#1079]
Hi Guys

I'm pretty desperate. I looked up some other examples and my code won't work

Here is my program.js
```javascript
var mymodule = require('./mymodule');

var dir = process.argv[2];
var ext = '.' + process.argv[3];

mymodule(dir, ext, function (err, data) {
	if (err)
		console.log(err);
	for (var i = 0; i < data.length; i++) {
		console.log(data[i]);
	};
});
```
And here is mymodule.js
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function (err, list) {
		if (err);
			return callback(err);
		var array = [];
		for (var i = 0; i < list.length; i++) {
			if (path.extname(list[i]) == ext)
				array.push(list[i]);
		}

		callback(null, array);
	});
};
```
And here is my error:
![image](https://cloud.githubusercontent.com/assets/5864035/7164163/c731addc-e39e-11e4-9b13-c0607e59aa14.png)

Any ideas?
And thanks already in advance!

**Comment by smjordan** [comment]
In the program.js file I think you'll want to return the ```err``` instead of using ```console.log(err);```

In the second part of your module function you want to return the callback function:

```javascript
return callback(null, array);
```

**Comment by dominhhai** [comment]
1. Read the tutorial again:
> The filename extension argument must be the same as what was passed to your program. Don't turn it into a RegExp or prefix with "." or do anything except pass it to your module where you can do what you need to make your filter work.

2. In your `program.js`
If have any `err`, don't retrieve your `data `.
e.x: `if (err)    return console.log(err);`

3. Should not add  unnecessary semicolons because it can become a empty statement.

```javascript
for (var i = 0; i < data.length; i++) {
        console.log(data[i]);
 }; // remove ; here
```

--> should be

```javascript
for (var i = 0; i < data.length; i++) {
        console.log(data[i]);
 }
```

**Comment by oxylius** [comment]
That was the solution!

Need to have a better look on my JS-Syntax in future, after deleting and refactoring 1000 times ;-)

Thank you very much for your fast and comprehensible answer!

**Comment by SomeoneWeird** [comment]
Awesome, open another issue if you get stuck again! :tada:
