### ISSUE TITLE
My First IO: Instructions are misleading; says first argument is required file path

### ISSUE THREAD

**Issue by brianjsullivan** [nodeschool/discussions#1081]
Drawing off the code in solution.js, I have the following in my program.js:
![program.js contents](http://i.imgur.com/4Y7rSgw.jpg)

The exercise states the following:
![challenge instructions](http://i.imgur.com/IU7UsaY.jpg)

I'm confused by the fact that the instructions state that the full path against which the code checks for \n is the "first argument" of the command line. But if you print the command line - console.log(process.argv) - there are only two entries: 'node' and the program.js working directory.

Furthermore, the solution.js example references process.argv[2] as the path against which the logic tests for \n. If we are not required to make a custom file, and there is no 3rd argument from the command line, how can this be correct?

**Comment by SomeoneWeird** [comment]
Are you using `learnyounode run <file.js>` to test? It will pass extra command line arguments when executing the program so you can test, just like `verify` would. If you run it manually with `node` then you won't get any other values in `process.argv`

**Comment by brianjsullivan** [comment]
That was it, exactly; and I understand why this would result in the error. Thanks for pointing this out, I will be sure to test against learnyounode run in the future. However, I still think it's a bit misleading to say "first argument". While this is certainly true, it might be confusing for the newbie (like me) when in fact the user does not pass any arguments in the command line (they are added behind the scenes when running through learnyounode) and the pertinent path is not the first entry in the process.argv array.
