### ISSUE TITLE
NodeSchool in Chiang Mai?

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/discussions#1082]
It doesn't look like Thailand has had a NodeSchool yet, and I don't see any in Chiang Mai. Would anyone like to set one up with me in early May? I just hosted one in Bali that went relatively smoothly, would be fun to do it again.

**Comment by namuol** [comment]
:+1:

I am interested, and would offer my help to organize/mentor/whatever is needed.

**Comment by Hiswe** [comment]
Can help too.
Here until ± mid July :)

**Comment by RichardLitt** [comment]
Awesome! I have a space at Bibie, a coworking space on Nimman, that can fit 25 people. We'd have to buy internet, but it should be fairly cheap and I don't think we'd need a sponsor.

**Comment by lid** [comment]
Sounds fun. I might be able to help in a limited way (as in, I haven't touched Node in about a year). I'm in Chiang Mai 'til mid-May.

**Comment by RichardLitt** [comment]
Opened repository: https://github.com/nodeschool/chiang-mai

**Comment by martinheidegger** [comment]
:+1:
