### ISSUE TITLE
Guide me, please 

### ISSUE THREAD

**Issue by StanisDuViy** [nodeschool/discussions#1085]
Hello ,

Just started to learn nodejs and found out about express js which promises to make my life more easy. I thought Ok, and in 5 min I noticed Jade module, then ejs, hogan and something else, all modules seem different, and now i'm a little bit confused with a variety. and question is : 
What is the reliable framework? or maybe it's better not to use any?

**Comment by finnp** [comment]
Hey,
there are different web frameworks for node, express and hapi.js are two popular ones. Of course depending on what you do, you often don't need these frameworks at all.
Jade, ejs and hogan are different template engines. Choose one that you feel comfortable with, but don't spend to much time evaluating them. Thing about: Why do you need a template engine and does xy fullfull the job. Then it's fine. People have build great things with all of them.

Best,
Finn

**Comment by StanisDuViy** [comment]
Thank you Finn, getting clear now
I start trying express with <%=ejs engine. I have no idea yet what i m going to create:) 
but it would be smth special for sure...  
All the best ,
Stanislav
