### ISSUE TITLE
second lecture baby steps doesnt work as it is supposed to work it doesnt pass

### ISSUE THREAD

**Issue by EfthiasSoftware** [nodeschool/discussions#1087]
```js
var a = process.argv;
for (i=2;i<a.length;i++){
console.log(a[i]);
}
```
this is my code it is doing exactly what it must do but in verify part it doesnt pass

**Comment by bresson** [comment]
I concur. My code below works well with "learnyounode run program.js" but fails with "learnyounode verify program.js"

var arrayFromArgv = [];

for (var i = 2; i < process.argv.length; i++ ) {
    arrayFromArgv.push(process.argv[i])
}

console.log(arrayFromArgv);

var sum = arrayFromArgv.reduce( function( a, b) {
    console.log(a, b)
    return parseInt(a) + parseInt(b)
}, 0)

**Comment by davecocoa** [comment]
To both of you, it will help us understand your problem if you show us the output from your program. It's also important to pay close attention to the exercise instructions, you are only asked to print the sum of the numbers, nothing else.

**Comment by sms22j** [comment]
@EfthiasSoftware I thinkg you are a part of the solution, the aim is to display the sum, and for hint don't fogot that the first tow element of your table are (node and argv).
@bresson not too far from the solution, just read above and you will find the solution.
