### ISSUE TITLE
Mr,Sequoia,

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1088]

**Comment by Hans-Park** [comment]
Hi! Sequoia,
This is Hans.

I coded for ' for loops' as follows, but nothing happened.
What is the wrong I did?

=====
var total = 0;
var limit = 10;
total += i;
for(i =0; i<10; i++) {

         console.log(total);
}

      Your reply will be very appreciated.

**Comment by SomeoneWeird** [comment]
Try moving `total += i;` inside of the for loop.

**Comment by Hans-Park** [comment]
Mr. SomeoneWeird,

Hi!
Thank you very much for helping me, but

Could you show me the entire code of this issue?

Thank you.
Hans

**Comment by dmcclccam** [comment]
Hey @Hans-Park, you should move `console.log(total);` outside the loop (and bring `total += i;` inside, as @SomeoneWeird said).

Like this:

```javascript
var total = 0;
var limit = 10;

for (var i = 0; i < limit; i++) {
  total += i;
}

console.log(total)
```

**Comment by Hans-Park** [comment]
Hi!
Mr. dmcclddam,

At last, I got it!

Thank you so much.
Hans.

**Comment by abinchalyan** [comment]
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++) {
total += i;
}
console.log(total);
I had same issue. I copy pasted the codes from other forum but didn't work. Problem was with location not the code. It seems like windows command terminal switch user back to parent FOLDER every time the user goes to next task.

SOLUTION: check your file location. It should be C:\user\name\javascripting> javascripting verify for-loop.js
NOTE : don't forget to do 'cd javascripting'. Took me hours to figure out. :D
