### ISSUE TITLE
How to code for for-loop.js

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1090]
Dear Mr. Sequoia,
Hi!
This is Hans.

I tried to code for  "for loops" as follows, but getting the result is  failed.
What is the wrong I did?

==========
  var total = 0;
  var limit = 10;
  total += i;
  for( i =0; i<limit; i++) {
      
            console.log(total);
 }

  

   Your help will be very appreciated.

**Comment by babhishek21** [comment]
Your issue has been answered [here](https://github.com/nodeschool/discussions/issues/1088) by @SomeoneWeird.

**Comment by dmcclccam** [comment]
Actually @babhishek21 the solution is a little bit different than what [he](https://github.com/SomeoneWeird) suggest on #1088, but anyway, it's solved now.

**Comment by SomeoneWeird** [comment]
I wasn't trying to give him the entire solution, just a nudge in the right direction. There's no point in giving somebody the answer :)

**Comment by dmcclccam** [comment]
Sorry. I din't mean that. :neutral_face:
