### ISSUE TITLE
Trouble in starting javascripting module from ubuntu 14.04

### ISSUE THREAD

**Issue by anis016** [nodeschool/discussions#1091]
Hello

I have installed the "javascripting" module from the site: https://github.com/sethvincent/javascripting/  using the terminal.
cmd: sudo npm install -g javascripting

after installing, when i am typing "javascripting" then it is showing - "/usr/bin/env: node: No such file or directory".

However, node.js is installed.
nodejs -v
v0.10.25

please check the image attached.

![screenshot from 2015-04-20 12 07 21](https://cloud.githubusercontent.com/assets/6690216/7224575/f64d4260-e755-11e4-9e5d-e44859dd83d0.png)

Requesting to provide suggestion on how to start it in ubuntu

Thanks
Anis

**Comment by martinheidegger** [comment]
Hello Anis!

it seems like you have installed directly from the package manager, please take a look at

https://github.com/nodeschool/discussions/wiki/Installation-suggestions#ubuntudebian

Can you get it working with that?

**Comment by alecanales** [comment]
That's because ubuntu installs nodejs binary instead of node

make a symlink and it will work!

sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by anis016** [comment]
fantastic .. It started to work..

however, I earlier did input the command: sudo ln -s /usr/bin/nodejs /usr/bin/node but then after writting "javascritping" nothing was happening.
Now, I followed again the link given by martinheidegger and it is working.
Appreciate the help :)

Thanks
Anis
