### ISSUE TITLE
Trouble on "Make it modular"

### ISSUE THREAD

**Issue by Oscar3124** [nodeschool/discussions#1092]
![image](https://cloud.githubusercontent.com/assets/8062498/7234749/3bc10f74-e757-11e4-9255-a77ce18f92cd.png)

i don´t know where "undefined" come from, I´ll appreciate some help please.

**Comment by davecocoa** [comment]
`undefined` is coming from line 3 of `program.js`. Is your module returning anything?

**Comment by Oscar3124** [comment]
I had some errors on program.js but I fix it all, Thanks @davecocoa !

**Comment by davecocoa** [comment]
:+1: :boom: :confetti_ball:  Well done!
