### ISSUE TITLE
Intregration between NodeJS and AngularJS client

### ISSUE THREAD

**Issue by PriyaVasudevan** [nodeschool/discussions#1093]
I am writing my 1st SPA and am facing issues with sending the data fetched from mongoDB onto the front end angular client.
Here's the code for Node JS:
```js
var connect=require('connect'),
	servestatic=require('serve-static'),
	http=require('http');
var MongoClient = require('mongodb').MongoClient;
var port = 3000;
var app = connect();
MongoClient.connect('mongodb://localhost:27017/kbase',function(err, db) {
  if(!err) {
    console.log("connected to mongoDB ");
	}
var collection = db.collection('articles');

collection.findOne({title:'Drinks'},function(err, item) {
	 if(item!=null){
	 console.log("Data fetched" + item.body + " "+ item.title);
http.createServer(function(request, response) {  
        response.writeHeader(200, {"Content-Type": "text/html"});  
        response.write('./dashboardIndex.html',item);  
        response.end();  
    }).listen(port);
console.log('Connected via port'+port);
	 }
	});
	 });
```
My code in dashboardIndex.html is as shown below:
```html
<!DOCTYPE html>
<html>

<head>
<style>
table, th , td  {
  border: 1px solid grey;
  border-collapse: collapse;
  padding: 5px;
}
table tr:nth-child(odd)	{
  background-color: #f1f1f1;
}
table tr:nth-child(even) {
  background-color: #ffffff;
}
</style>
</head>

<body>
<script  type="text/javascript" src= "angular.min.js"></script>
<div ng-app="myApp" ng-controller="formCtrl"> 

 
<table>
<tr>
<th> Transaction Name </th>
<th> Missing Records </th>
<th> Faulty Records </th>
</tr>
<tr>
  <td>CREATE ORDER</td>
    <td><a href="" onClick="return popup(missingRecords.html,'Missing Records')"> {{missingRecord}}  </a></td>
    <td><a href="" onClick="return popup(faultyRecords.html,'Faulty Records')"> {{ faultyRecord }} </a></td>
  </tr>
</table>

</div>

<script>
var app = angular.module('myApp', []);
app.controller('formCtrl', function($http) {
	var test = this;
	$http.get("http://localhost:3000/dashboard").success(function result){
	test.item = result;
	}
});
</script>

</body>
</html>
```
I get to see the data fetched from mongoDB on the nodeJS console..but when I launch http://localhost:3000 or http://localhost:3000/dashboardIndex.html, it shows up ./dashboardIndex.html
I believe this is due to     response.write('./dashboardIndex.html',item);   in the NodeJS code.
Pls advise on how to fix this!!

**Comment by martinheidegger** [comment]
Hello @PriyaVasudevan 

`response.write` is a very "low-level" way to deal with http requests. I could go into detail why there are several problems with it but I think it would be easier if you would use [express](http://expressjs.com/), [hapi](http://hapijs.com/) or [sails](http://sailsjs.org/). There are even the workshoppers [make-me-hapi](https://github.com/hapijs/makemehapi) and [expressworks](https://github.com/azat-co/expressworks) available to learn these. Do you want me to go in detail on your problem or first try those tutorials (they are really helpful!)

**Comment by PriyaVasudevan** [comment]
Hello @martinheidegger

Thanks for the response - I moved onto express. But i seem to be stuck with how  JSON data from MongoDB is to be passed onto the angular client from the Node JS code

app.get('/', function(req, res) {
res.sendFile(__dirname + '/dashboardIndex.htm');
 });

This is the node JS code written to integrate the front end with node JS code.
I believe res.json(<JSON object>) is to be used to send the JSON data. However, both the HTML and the JSON object can't seem to be sent together.
Any suggestions??

**Comment by martinheidegger** [comment]
@PriyaVasudevan Sorry to have missed your question. A http response is always just one response. If you want to send different responses to different requests you need to create more `app.get('x',...)` handlers.

**Comment by SomeoneWeird** [comment]
Please reopen if needed.

**Comment by Harshitha30** [comment]
can i get connection with angular js and nodejs connection
