### ISSUE TITLE
Learnyounode - 11: HTTP File Server - "pipe" not recognised

### ISSUE THREAD

**Issue by scottg299** [nodeschool/discussions#1095]
Hi,

Here is the code I have so far:

```javascript
var http = require('http');
var fs = require('fs');

var port = process.argv[2];
var filepath = process.argv[3];

var server = http.createServer(function (req, res) {
    var fileStream = fs.createReadStream(filepath);
    fileStream.pipe(res);
});
server.listen(port);
```

When I run this using `learnyounode verify 11_httpfileserver.js`, I get the following error:

```
D:\scott\Documents\nodejs\learnyounode\11_httpfileserver.js:11
        data.pipe(res);
             ^
TypeError: undefined is not a function
    at D:\scott\Documents\Progs\nodejs\learnyounode\11_httpfileserver.js:11:14
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
? Error connecting to http://localhost:34651: read ECONNRESET
```

Any ideas? Thanks.

**Comment by scottg299** [comment]
... well I ran it again without changing anything and it now passes... so I'm not sure what happened there. Typical!

**Comment by jkbits1** [comment]
Thanks for letting us know how you're getting on and that the code works now :+1: 

I notice that the error refers to ``` data.pipe(res) ```, and your code has ``` fileStream.pipe(res) ```. Maybe the code was run before a change was saved? 

Feel free to ask more questions as you go through the tutorials :smile:
