### ISSUE TITLE
Syntax problems when writing JavaScript

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1097]

**Comment by Hans-Park** [comment]
Hi! Gentlemen,

I wrote codes as follows, but failed.
Please help me to correct  my errors.

,,,

        function eat('food'){
          return food + 'tasted really good.' ;
       }
          console.log(function eat('bananas'));
,,,
Thank you.

**Comment by SomeoneWeird** [comment]
`eat` is already a function here, so you can remove the `function` word from `function eat('bananas')` - you just want to call it.

**Comment by martinheidegger** [comment]
Also a parameter "food" needs to be without quotes

**Comment by Hans-Park** [comment]
Hi!  Martinheidegger,

I removed it as your instruction, but it does not work yet.
I don't know why.
Thank you.

**Comment by martinheidegger** [comment]
Can you copy+paste the code?

**Comment by Hans-Park** [comment]
Here we have code.
,,,

function eat('food'){
    return food + 'tasted really good.' ;
}
console.log(eat('bananas'));

Thank you.

**Comment by dominhhai** [comment]
Remove quotes (`'`) from `'food'`.

**Comment by Hans-Park** [comment]
Yes, I removed it from 'food' , but the result is the same. 
I did the code as follows.
,,,

functions eat(food){
       return food + 'tasted really food.';
}
       console.log(eat('bananas'));
,,,
Thank you.

**Comment by martinheidegger** [comment]
`function` not `functions` one `s` too much!

**Comment by Hans-Park** [comment]
I got;
,,,
bananastasted really good.
,,, 
So, I need a space between bananas and tasted. How to do that?
,,,
thanks

**Comment by martinheidegger** [comment]
Seriously? How about adding a space to the string?

**Comment by Hans-Park** [comment]
How idiotic I am!
 I got it.
Thank you so, so much!
How can I express my appreciation to you?
Thank you again.

**Comment by martinheidegger** [comment]
Try to give your best! That is enough appreciation! Good luck!

**Comment by Hans-Park** [comment]
Thank you very much  Mr. Martinheidegger.
I'll do my best.
