### ISSUE TITLE
Baby steps: Exercise 2 of 13. How to create a loop?

### ISSUE THREAD

**Issue by songproducer** [nodeschool/discussions#1098]
The instruction:

"You'll need to think about how to loop through the number arguments so  you can output just their sum."

How do I create a simple loop? I searched a bit for loop and nodejs but nothing immediately obvious stood out for me.

**Comment by martinheidegger** [comment]
@songproducer learnyounode is a workshop to explain the workings of nodejs to people that are familiar with javascript. A "simple loop" is a javascript concept ([for loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for) for example). If you are having problem with that I recommend you to start with `javascripting`.

**Comment by songproducer** [comment]
Thanks Martin, yes that's helpful!

**Comment by martinheidegger** [comment]
@songproducer Good luck with the tutorials. Feel free to write an issue here anytime you need.
