### ISSUE TITLE
functional-javascript-workshop [Basics call] arguments not an array?

### ISSUE THREAD

**Issue by tbelaire** [nodeschool/discussions#1099]
The Hint says:
  * The `arguments` variable, available in every function, is an *Object* that quacks like an *Array*

But that doesn't seem to be true.  I'm getting undefined when trying to access Array methods on it.  Here's my code:

```JavaScript
module.exports = function duckCount() {
    return arguments.reduce(function(count, duck) {
        //           ^ undefined?
        if(duck.hasOwnProperty('quack')) {
            return count+1;
        } else {
            return count;
        }
    }, 0);
};
```
And it's saying the `reduce` is undefined.  What's going on?

**Comment by davecocoa** [comment]
I suppose the language is not very clear. The idea is that it acts a *little* like an array, but not totally and it is not a real array. To the extent that it acts like an array - you can access items using `arguments[1]` and it has a `.length` property.

However, it is sufficiently array-like that you can execute array methods on it. For example, to execute reduce on an arguments object using [`Function.call`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call), you could do `Array.prototype.reduce.call(arguments, function(count, duck) { /* function body */ }, 0)`

**Comment by martinheidegger** [comment]
@tbelaire Does that clear up things? If not, could you post a PR/suggestion to the functional-javascript-workshop repository?

**Comment by g3hk** [comment]
can u unsubcribe me from this list

**Comment by martinheidegger** [comment]
@g3hk No, you have to do it yourself.
