### ISSUE TITLE
Potential problem with instructions on "My First I/O!" for Learnyounode

### ISSUE THREAD

**Issue by ethangodt** [nodeschool/discussions#1100]
The instructions say, "the full path to the file to read will be provided as the first command-line argument" but really it's being provided as the last argument. When I read process.argv[0] I got many thousand '\n'.

Am I missing something? I'm a noob. Just trying to help if this is an error.

**Comment by martinheidegger** [comment]
`process.argv` contains more than just the command line arguments. 

`process.argv[0]` is the binary that executes the script (usually node)
`process.argv[1]` is the javascript file that is the entry point to node scripts
`process.argv[2]` from position 2 onwards are all the arguments

**Comment by ethangodt** [comment]
Ahh, right. The instructions already said that... Thanks!

**Comment by martinheidegger** [comment]
No Problem :+1:
