### ISSUE TITLE
javscripting workshop || complier issue || Waitting online 

### ISSUE THREAD

**Issue by steve-wanglin** [nodeschool/discussions#1104]
It seems there are some issue with my compiler, i can't using javascripting verify command  in terminal ?
What could be the problem?

**Comment by dominhhai** [comment]
Can you provide more info about that?
Is other commands  OK?

**Comment by steve-wanglin** [comment]
Actually, the issue is all of the js file can't be  working with javascripting verify command, I think there are some wrong in comliper, cause the same js file is working in html file. 
Ex, the code in js is like ''console.log('hello');"
but it's display  as below:



# O-oh, something isn't working.

# But don't panic!

-------------------
## Check your solution:

Solution
===================

pizza is wonderful


Your Attempt
===================

hello


Difference
===================

hpizza is wonderfullo


## Additional troubleshooting:

- Did you type the name of the file correctly? You can check by running ls introduction.js, if you see ls: cannot access introduction.js: No such file or directory then you should create new file / rename existing or change directories to the one with file
- Make sure you didn't omit parens, since otherwise compiler would not be able to parse it
- Make sure you didn't do any typos in the string itself

**Comment by dominhhai** [comment]
The `javascripting run your_file_name.js` is OK?

**Comment by steve-wanglin** [comment]
this command is working fine in terminal

**Comment by dominhhai** [comment]
Did you try to run `verify` with correct solution?

**Comment by steve-wanglin** [comment]
Could you tell me what's the meaning of verify with correct solution? I am not very clearly about this?

**Comment by dominhhai** [comment]
Write a correct solution for a challenge, then verify it with `verify` command.

**Comment by steve-wanglin** [comment]
ok, let me try and update to you.

**Comment by steve-wanglin** [comment]
It seems it's not working with me.

romote:~ Steve-Wang$ verify revising-strings.js
-bash: verify: command not found
promote:~ Steve-Wang$

**Comment by dominhhai** [comment]
E.x: For [introduction challenge](https://github.com/sethvincent/javascripting/blob/master/problems/introduction/problem.md):
---
# INTRODUCTION

To keep things organized, let's create a folder for this workshop. 

Run this command to make a directory called `javascripting` (or something else if you like):

`mkdir javascripting`

Change directory into the `javascripting` folder:

`cd javascripting`

Create a file named `introduction.js`:

`touch introduction.js` or if you're on windows, `type NUL > introduction.js` (`type` is part of the command!)

Open the file in your favorite editor, and add this text:

```js
console.log('hello');
```

Save the file, then check to see if your program is correct by running this command:

`javascripting verify introduction.js`

---  

Did you try this?

**Comment by steve-wanglin** [comment]
promote:javascriptingtest Steve-Wang$ type NUL>introduction.js
-bash: type: NUL: not found

**Comment by steve-wanglin** [comment]
is a big problem with the env,isn't it? 
the first time I using javascripting verify command ,it's works, after sometime, it doesn't work for me

**Comment by SomeoneWeird** [comment]
If you're not on windows, you need to use `touch introduction.js` instead of `type NUL>introduction.js`

**Comment by steve-wanglin** [comment]
the error as below even I am using sublime to edit introduction.js（utf-8) file.

promote:javascriptingtest Steve-Wang$ javascripting verify introduction.js
-------------------
# O-oh, something isn't working.

# But don't panic!

-------------------
## Check your solution:

Solution
===================

pizza is wonderful


Your Attempt
===================

hello


Difference
===================

hpizza is wonderfullo


## Additional troubleshooting:

- Did you type the name of the file correctly? You can check by running ls introduction.js, if you see ls: cannot access introduction.js: No such file or directory then you should create new file / rename existing or change directories to the one with file
- Make sure you didn't omit parens, since otherwise compiler would not be able to parse it
- Make sure you didn't do any typos in the string itself


Need help? Ask a question at: github.com/nodeschool/discussions/issues

**Comment by steve-wanglin** [comment]
nobody knows what's the exactly issue?

**Comment by steve-wanglin** [comment]
I just complete challege(NUMBERS), it works. It's seems javascripting verify filename.js which include character 。。Can someone encounter this issue before?

**Comment by martinheidegger** [comment]
@steve-wanglin I am not sure what the question is?! Can you try to rephrase it?

**Comment by steve-wanglin** [comment]
hello martin, the thing is javascripting verify command is not working  properly for me

**Comment by martinheidegger** [comment]
@steve-wanglin It seem to be working as intended. What is your issue?

**Comment by steve-wanglin** [comment]
when  I was used  command javascripting verify string.js  the code as below 
var someString = 'this is a string';
console.log(someString);

It should be display "this is a string" as expected, but it was showing  "this is a string2"

**Comment by martinheidegger** [comment]
@steve-wanglin Sorry for the late response (busy organising international day): It looks like you run the wrong file (wrong folder?) Can you make sure that you actually run the correct file in the right folder?
