### ISSUE TITLE
npm ERR! 404 'learnyournode' is not in the npm registry.

### ISSUE THREAD

**Issue by dittoslash** [nodeschool/discussions#1106]
pi@archen ~ $ sudo npm install -g learnyournode
npm ERR! 404 404 Not Found: learnyournode
npm ERR! 404
npm ERR! 404 'learnyournode' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by dittoslash** [comment]
on a RPi 2 connected to the internet.

**Comment by sudodoki** [comment]
> learnyou**r**node
Should be learnyounode

**Comment by dittoslash** [comment]
well then... i thought i tried that.

**Comment by sudodoki** [comment]
@dittoslash could you please try that and confirm it's not working for you, please?

**Comment by AkiraLaine** [comment]
@dittoslash Try sudo npm install learnyounode -g

**Comment by SomeoneWeird** [comment]
@AkiraLaine that is definitely not the problem.

**Comment by SomeoneWeird** [comment]
Closing this.
