### ISSUE TITLE
MAKE IT MODULAR 

### ISSUE THREAD

**Issue by reportbase** [nodeschool/discussions#1107]
I'm getting the following error with learnyounode.

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✓ Additional module file handles errors properly
✓ Additional module file handles callback argument
✗ Your additional module file [learnyounode6.js] returned an error on its callback:
	{ [Error: ENOENT, scandir 'm'] errno: -2, code: 'ENOENT', path: 'm' }

# FAIL

Your solution to MAKE IT MODULAR didn't pass. Try again!

```JavaScript
var mymodule = require('./learnyounode6.js')

mymodule(process.argv,"md",
    function(err,data)
    {
        if (err)
            console.log("aa");
    })
```

```JavaScript

    var fs = require('fs')
    var path = require('path')

module.exports = function (args,b,callback)
{
    fs.readdir(args[2], function (err, data)
    {
            if (err)
              return callback(err)

          data.forEach(function (file)
          {
            if (path.extname(file) === '.' + args[3])
              console.log(file)
          })

          return callback(null,data)
        });

}
```

**Comment by martinheidegger** [comment]
You shouldn't log within your module (the error message is very weird)

**Comment by reportbase** [comment]
Where are the answers?   I give up.   I've been trying to get that error message to go away, I've had no success.  I removed the log command from the module.

**Comment by martinheidegger** [comment]
Sorry for the briefness: In your module you logged the data but that is something that the main file is supposed to do:

```Javascript
mymodule(process.argv,"md",
    function(err,data)
    {
        if (err)
            console.log("aa");
       else
           data.forEach(function (entry) {
              console.log(entry)
           })
    })
```
When you fixed that it should be a correct solution. Do you want to give it a try?

**Comment by reportbase** [comment]
Same error.    Heres my code.  Thanks.     

    var fs = require('fs')
    var path = require('path')

var mymodule = require('./learnyounode6.js')

mymodule(process.argv,"md",
    function(err,data)
    {
        if (err)
            console.log("aa");
       else
           data.forEach(function (entry) {
              console.log(entry)
           })

    })
    
module.exports = function (args,b,callback)
{
    fs.readdir(args[2], function (err, data)
    {
            if (err)
              return callback(err)

          data.forEach(function (file)
          {
            if (path.extname(file) === '.' + args[3])
              console.log(file)
          })

        });

}

**Comment by martinheidegger** [comment]
Oh! I overlooked one other thing: Your module is not supposed to take an array with the path. I it is supposed to take the path and extension that are both given in `process.argv`:

```Javascript
mymodule(process.argv[2], process.argv[3], function(er...
```

**Comment by reportbase** [comment]
Fixed.    Thanks.

**Comment by martinheidegger** [comment]
Nice!
