### ISSUE TITLE
array-filtering.js

### ISSUE THREAD

**Issue by Jordantcarlisle** [nodeschool/discussions#1108]
My solution to array-filtering.js is correct; however, I'm still a bit confused. In line 2 and 3 are we calling and defining a function? Specifically, is evenNumbers(number) now a function that returns even numbers, so we can call it again? If so, what is an example where we would use that? 

```JavaScript
var numbers = [1,2,3,4,5,6,7,8,9,10];
var filtered = numbers.filter(function evenNumbers (number) {
  return number % 2 === 0;
});

console.log(filtered);
```

**Comment by dominhhai** [comment]
JavaScript function is [higher-order function](http://en.wikipedia.org/wiki/Higher-order_function) - can take one or more functions as an input. For array filter, it uses [Criteria Design Pattern](http://en.wikipedia.org/wiki/Criteria_Pattern) to filter any elements which meets the predefined condition by a input function.
For example, your filter function (predefined condition) is `eventNumbers` function - which pass (`return true`) with even numbers.
Exactly, following the Criteria Design Pattern, you can implement your own filter functions. Some things like that:

````javascript 
function (array, filter) {
    var result = []
    for (var i in array) {
        if (filter(array[i]))  result.push(array[i])
    }
    return result
}
````
