### ISSUE TITLE
Bootstrapping workshopper translations

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/discussions#1109]
@rburns made a script which checks for [translations of workshoppers](https://github.com/nodeschool/chiang-mai/issues/4#issuecomment-95827292). Here is the current list:
- stevekane/promise-it-wont-hurt -- en, fr
- azat-co/expressworks -- en, fr
- timoxley/functional-javascript-workshop -- en, fr
- npm/how-to-npm -- none
- bulkan/async-you -- en, fr
- sporto/planetproto -- en, fr
- stackgl/webgl-workshop -- none
- tableflip/nodebot-workshop -- none
- othiym23/bug-clinic -- none
- alexmackey/IntroToWebGLWithThreeJS -- none
- koajs/kick-off-koa -- en, fr
- domenic/count-to-6 -- none
- substack/browserify-adventure -- none
- mdunisch/lololodash -- en, fr
- robertkowalski/learnyoucouchdb -- none
- thlorenz/learnuv -- none
- isRuslan/learn-generators -- en, fr
- jlord/git-it -- none
- substack/stream-adventure -- none
- sethvincent/javascripting -- es, ja, ko
- rvagg/levelmeup -- none
- maxogden/bytewiser -- none
- spumko/makemehapi -- en, fr
- gl-modules/shader-school -- none
- rvagg/learnyounode -- en, es, fr, ja, pt-br, ru, zh-cn, zh-tw
- rvagg/goingnative -- none
- finnp/test-anything -- none

I'm looking at nodeschool.io, and I don't see any clear guide to help translating these modules into foreign languages. I'm not sure what this would look like, but I think there ought to be a discussion about how best to help local chapters choose which workshoppers to translate and how to best do that for various international nodeschools. What do you think?

**Comment by Sequoia** [comment]
/cc @martinheidegger, patron saint of Nodeschool l10n :smile_cat:

@RichardLitt: note that there are 2 main libs people use to build nodeschool workshops, substack/adventure & rvagg/workshopper. The former is more flexible & has less built in; one of the things it does *not* have built in is i18n tools, so it's much easier to i18n a `workshopper` based workshop. Furthermore, it looks like this script **only** checks for `workshopper` style l10ns. To wit, there [are translation](https://www.npmjs.com/package/stream-adventure-fr)(s) of stream-adventure, but they are forks, not inlined into the same repo.

Very salient point about discovery tho-- there is no good way currently to discover translations w/o installing, running, and seeing if it prompts you for language.  Proposals?

**Comment by Sequoia** [comment]
note: ideally any proposals to address this discovery issue would work with **both** popular nodeschool workshop frameworks, not just one or the other.

**Comment by rburns** [comment]
I can modify the script to try and pick up localized forks through npm searches. I had a quick look at doing so through github, but there didn't seem to be an obvious automated approach available.

two other related issues:

https://github.com/substack/adventure/issues/6 
https://github.com/nodeschool/organizers/issues/64

and a pull request
https://github.com/substack/adventure/pull/7

**Comment by RichardLitt** [comment]
I think what would be more important is a document outlining _how_ to translate both types, not necessarily discovering if there are translations. An overall list would also be great, of course, to show coverage in a particular language. 

Mostly I'm concerned that language is a barrier to entry and it's not clear from a translator's perspective what is best to translate, or how to help on that end.

**Comment by martinheidegger** [comment]
Okay, my 2cnt.

I have been working quite successfully at writing at a fork of `workshopper` that makes it "adventure-compatible" all that is missing is one stressful little feature (stream support for the output) but basically most adventure based tutorials are already translatable the same way that workshoppers are. What would be needed was some documentation on how to translate things (or: how to write workshoppers in general). 

`workshopper` now moved to a workshopper organisation which is sadly moving far to slow for my taste.

My ideal setup for translation would look like this:

- We have translation teams in NodeSchool like [i18n-japanese](https://github.com/orgs/nodeschool/teams/i18n-japanese) that allows us to address people in teams. Both for the Homepage and the workshoppers. (Now thinking of it: It would be good to have repo's for them too)
- There is no "workshopper" or "adventure" anymore. Just "Tutorials" (calling them either workshoppers or adventures, my feeling is "workshopper")
- The description of workshoppers in the homepage is taken from the repositories (not as currently part of the homepage)
- We have a "git-hook" that listens at all the repositories for a "i18n-x:" prefix and when it occurs notifies the not-in-the-loop members about the change, so they know that that they need to translate as well.

**Comment by RichardLitt** [comment]
Who could we talk to about writing that documentation? I wish I could help, but I don't speak any other languages fluently and wouldn't be the right person to write that. I think this is a pain point, though, as I have had no information on how to start translations for workshoppers, in general, that I could point local Thai or Balinese noders to. 

I think translation teams are smart, but I'm worried that a lot of useful information would then be locked away in their own repos. 

Workshoppers is a better term, although it does suggest groups of people should do them together. 

The description should be taken. I think we should open an issue for this. We should also say if those workshoppers are translated on the home page, into which languages, and update that accordingly as they are changed. What do you think? 

The git loop is tricky - I don't have much experience with that, but might work.

**Comment by martinheidegger** [comment]
I am giving this an update. https://github.com/workshopper/list is now a repo. Anybody willing to jump in and maintain it? It should also contain a translation status-quo of things?

**Comment by RichardLitt** [comment]
It looks like @linclark is maintaining it, currently?

**Comment by martinheidegger** [comment]
No one in particular is working on it right now afaik.

**Comment by claudiopro** [comment]
on a related note, do existing workshoppers have a translation howto? A need for instructions came up in the [javascripting repo](https://github.com/workshopper/javascripting/issues/76#issuecomment-275871872). I'd like to make it a template since they all share a similar structure.
