### ISSUE TITLE
javascripting...introduction.js won't verify

### ISSUE THREAD

**Issue by joel-powers** [nodeschool/discussions#1111]
> javascripting/introduction.js

I've tried verifying the following code:

    console.log('hello');

 here is the output:

    { [Error: Command failed: /bin/sh -c node "/home/joel/projects/javascripting/introduction.js"
    /home/joel/projects/javascripting/introduction.js:1
    nction (exports, require, module, __filename, __dirname) { console.log 'hello'
                                                                           ^^^^^^^
    SyntaxError: Unexpected string
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    ]
      killed: false,
      code: 1,
      signal: null,
      cmd: '/bin/sh -c node "/home/joel/projects/javascripting/introduction.js"' }

hope that's helpful.

**Comment by dominhhai** [comment]
This is similar to https://github.com/nodeschool/discussions/issues/1075#event-282096895

**Comment by joel-powers** [comment]
While it may be similar, I'm not having any luck applying that advice to my issue. I was hopeful when I realized I'd missed the semicolon, but adding that hasn't changed the output.

**Comment by SomeoneWeird** [comment]
So, your second line of code is actually the correct answer, but it seems you've got all 3 lines in the file you're trying to verify. The code on the first line is invalid syntax, which is why it's failing, try only leaving the correct line and verifying.

**Comment by joel-powers** [comment]
I'm sorry I wasn't clear. I have tried each of those permutations as the answer, as opposed to all of them simultaneously. my code is:

    console.log('hello');

**Comment by dominhhai** [comment]
Can you try again then show the result (E.x: debug-log)?

**Comment by joel-powers** [comment]
could you explain what you mean by `debug-log` ?

**Comment by dominhhai** [comment]
Show the output of your execution.

**Comment by joel-powers** [comment]
the output hasn't changed:
    $ javascripting verify introduction.js
    { [Error: Command failed: /bin/sh -c node "/home/joel/projects/javascripting/introduction.js"
    /home/joel/projects/javascripting/introduction.js:1
    nction (exports, require, module, __filename, __dirname) { console.log 'hello'
                                                                           ^^^^^^^
    SyntaxError: Unexpected string
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    ]
      killed: false,
      code: 1,
      signal: null,
      cmd: '/bin/sh -c node "/home/joel/projects/javascripting/introduction.js"' }

**Comment by dominhhai** [comment]
Did you try with `javascripting run introduction.js` command or `node introduction.js`?
And your output with these command?

**Comment by SomeoneWeird** [comment]
The output of that command has `console.log 'hello'` and not `console.log('hello')` - this is your problem. Are you sure you're updating the correct file?

**Comment by joel-powers** [comment]
D'oh!

that's embarrassing! @SomeoneWeird - You nailed it! I was editing the contents of a different file. Got it now. Sorry to take up your time with this... [SOLVED!]

**Comment by SomeoneWeird** [comment]
All good! Happens quite often. Open another issue if you have any more problems :tada:

**Comment by jalderwood** [comment]
I had the same problem but it was because the instructions for Introduction said the statement should read: 
<b>console log 'hello';</b>
After I read this I put the correct statement in the file, <b>console.log('hello');</b> and that worked. Only took a day to figure that out.
