### ISSUE TITLE
cannot run javascripting workshop

### ISSUE THREAD

**Issue by UguDave** [nodeschool/discussions#1112]
I am trying to install the core workshop for javascripting but am having issues. Install using npm works fine:

```
C:\Program Files (x86)\nodejs>npm install --global javascripting
C:\Users\David\AppData\Roaming\npm\javascripting -> C:\Users\David\AppData\Roaming\npm\node_modules\javascripting\index.js
javascripting@1.12.0 C:\Users\David\AppData\Roaming\npm\node_modules\javascripting
├── diff@1.3.2
├── colors@1.1.0
├── adventure@2.10.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, mkdirp@0.5.0, split@0.3.3, through2@0.5.1, terminal-menu@2.1.1)
└── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.8, cardinal@0.4.4)
```

but if i try and run 'javascripting' I get 

'javascripting' is not recognized as an internal or external command,
operable program or batch file.

any help please? I am running windows 8.1

**Comment by UguDave** [comment]
I am running windows 8.1

**Comment by martinheidegger** [comment]
The `PATH` environment variable at your system is for some reason not set correctly. Can you take a look at https://github.com/nodeschool/discussions/wiki/Installation-suggestions#windows and see if it has some valuable information for you?
