### ISSUE TITLE
Pass extra parameters to readdir callback function

### ISSUE THREAD

**Issue by mp19uy** [nodeschool/discussions#1115]
Currently I'm with MAKE IT MODULAR from learnyournode and I have the following question:
I wan't to know alternative ways to pass extra parameters to a callback function with fixed parameters.
Looking for solutions I found this way, creating a annonymous function with the fixed callback parameters and then inside of it, call the function I want with all the parameters.

I would like to know from experience programmers:
1) if there is another way to do this? (keep in mind I still want to use the onXXXX functions I defined, I know that if I use anonymous functions the problem I'm having gets solved).
2) and if the way I did it it's acceptable.

Here's my code.

```node
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function(err,dir){ onRead(err,dir,ext,callback) });
}

function onRead(err, list, ext, callback) {
	if (err)
		return callback(err);
	
	list = list.filter(filterExt, ext);
	callback(null, list);
}

function filterExt(file) {
	return (path.extname(file) === '.' + this);
}
```

**Comment by martinheidegger** [comment]
Did you think of writing it this way?

```JavaScript
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
    fs.readdir(dir, onRead.bind(null, dir, ext) );
}

function onRead(list, ext, err, callback) {
    if (err)
        return callback(err);

    list = list.filter(filterExt, ext);
    callback(null, list);
}

function filterExt(file) {
    return (path.extname(file) === '.' + this);
}
```

**Comment by mp19uy** [comment]
@martinheidegger yes, looking for alternatives, I found examples that uses .bind(), but didn't know about bind or what it does (and I'm going to read about it now), I'm a novice to JS and NODE.
And now that I see your example, I find tidier the .bind() alternative.

**Comment by martinheidegger** [comment]
@mp19uy Unfortunately i can not help you more. Are you okay with this?
