### ISSUE TITLE
Unable to start learnyounode on ubuntu

### ISSUE THREAD

**Issue by kirtan95** [nodeschool/discussions#1116]
I have ran following commands on my ubuntu 14.04 - 

npm install -g learnyounode
learnyounode

However, when i type learnyounode on terminal, nothing happens
![screenshot from 2015-05-01 22 13 26](https://cloud.githubusercontent.com/assets/8456197/7433481/5889a49e-f04f-11e4-87ce-ae34e8fd167c.png)

**Comment by davecocoa** [comment]
I've found npm on ubuntu sometimes doesn't set up your PATH immediately, could you try re-opening your terminal and see if that helps?

**Comment by martinheidegger** [comment]
@kirtan95 What does `node -v` say?

**Comment by systemovich** [comment]
On Kubuntu 14.04, I installed it with sudo:

    $ sudo npm install -g learnyounode

**Comment by kirtan95** [comment]
@martinheidegger Thanks, its output was also the same -  blank, so it got me thinking, then i remembered i installed node using `sudo apt-get install node` instead of `sudo apt-get install nodejs`

I purged it and then installed the nodejs package, and finally, it worked :) 
Thank you everyone for your support :)
