### ISSUE TITLE
User registeration  in node with express framework

### ISSUE THREAD

**Issue by Anurag-Pareek** [nodeschool/discussions#1117]
Hi All,
         I am a newbie in  this awesome technology want to know how user registration takes place  in  Node.js.
 Its my request to all the delegates  here please if any link you can provide me or some piece of code that would be fine for me .

Thanx

**Comment by martinheidegger** [comment]
@Anurag-Pareek Google is your friend with these regular questions! I think the second entry in my search should help you a lot: https://orchestrate.io/blog/2014/06/26/build-user-authentication-with-node-js-express-passport-and-orchestrate/ Does that work for you?
