### ISSUE TITLE
Creating a New File

### ISSUE THREAD

**Issue by Hans-Park** [nodeschool/discussions#1119]
Dear Gentlemen,

I am going to learn "learnyounode" workshop.
The instruction of HELLO WORLD says;

  "Write a  program that prints the text "HELLO WORLD".

In this regard, do I write the program in a text editor or in Git Bash?

Your step by step explanation  will be very appreciated.

Thank you.

**Comment by finnp** [comment]
You can write this in any text editor. However there are some editors that are better for coding (they offer features like syntax highlighting). One of them is Atom for example: https://atom.io/

**Comment by Hans-Park** [comment]
Hi! finnp,

But Atom is for Linux only. Isn't it? Mine is window. So I use Sublime Text 3.

Do I need any previous definition in Git Bash before writing a program in a text editor?

Thank you.

**Comment by Hans-Park** [comment]
Thank you Mr.finnp.
