### ISSUE TITLE
learnyounode: MAKE IT MODULAR question

### ISSUE THREAD

**Issue by swicp12** [nodeschool/discussions#1124]
I'm getting the following error message upon submitting my code:

>Your additional module file [mymodule.js] did not return an Array with the correct number of elements as the second argument of the callback

Everything else seems to be okay. I was wondering if someone could help me out. This is my code:

```js
// program.js

var fs = require("fs");
var module = require("./mymodule.js");
var path = require("path");

var program = function (dir, ext) {
	module(dir, ext, function(err, files) {
		if (err) {
			throw err;
		}	
		files.forEach(function(file) {
			if (path.extname(file) === "." + ext) {
				console.log(file);
			}	
		});
	});	
}		
	
program(process.argv[2], process.argv[3]);

// END

// mymodule.js

var fs = require('fs');

module.exports = function(dir, ext, callback) {
	fs.readdir(dir, callback);
}	

// END
```

Thanks a lot in advance. I've been stuck on this problem for a while and it's taken me hours to get this far. I saw other people had similar problems but I'm scared that I'll look at their code and see spoilers.

**Comment by swicp12** [comment]
I ended up solving the problem. Here is my solution:

// program.js

var fs = require("fs");
var module = require("./mymodule.js");
var path = require("path");

var program = function (dir, ext) {
	module(dir, ext, function(err, files) {
		if (err) {
			throw err;
		}	
		files.forEach(function(file) {
				console.log(file);
		});	
	});
};		

program(process.argv[2], process.argv[3]);

// END

// mymodule.js

var fs = require('fs');
var path = require('path');

module.exports = function(dir, ext, callback) {
	var value;
	fs.readdir(dir, function(err, data) {
		if (err) {
			return callback(err);
		}
		value = data.filter(function(file) {
			if (path.extname(file) === "." + ext) {
				return file;
			}
		});		
		callback(null, value);
	});	
}	

// END

**Comment by martinheidegger** [comment]
Congratulations, sorry for being late helping you!

**Comment by swicp12** [comment]
No problem at all! Thanks for continuing to support those of us that are still learning.
