### ISSUE TITLE
#6 Make It Modular "did not return an Array with the correct number of elements as the second argument of the callback"

### ISSUE THREAD

**Issue by johnteakdigital** [nodeschool/discussions#1125]
Not sure what I'm doing wrong here... Everything else is working perfectly, any help or extra hints would be greatly appreciated, thanks!

`makeitmod.js`
````JavaScript
var input = process.argv,
		mymod = require('./mimmod')

mymod(input[2], input[3], function(err) {
	if (err) return console.error('There was an error')
})
````
`mimmod.js`
````JavaScript
var path = require('path'),
		fs = require('fs')

module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function(err, data) {
		if (err) return callback(err)
		
		data.forEach(function(file) {
			if (path.extname(file) === '.' + ext) {
				console.log(file)
			}
		})
		callback(null, data)
	})
}
````

**Comment by martinheidegger** [comment]
Hello @johnteakdigital ! You do a lot of things right here.
You created a module that has the expected setup, you use the callback correctly and you didn't mistake the extension check logic. Those are all mistakes that often occur - so: congratulations for your progress. 

About what is missing: Your module is still sending things to `console.log`. The only code to send output should be in `makeitmod.js`. If you make sure that the array in  `callback(null, data);` contains only the entries that match the extension and that all the logging takes place in `makeitmod.js` then you should be able to finish this exercise in no time!

Does that work for you?

**Comment by johnteakdigital** [comment]
Ah! Yes, thank you for replying so quickly. That was totally the issue, and it makes sense since you wouldn't want to dedicate a module to always outputting the same data. This way that data can be extracted but then you can do with it what you like.

**Comment by martinheidegger** [comment]
:+1:
