### ISSUE TITLE
learnyounode: Make It Modular - Help!

### ISSUE THREAD

**Issue by AkiraLaine** [nodeschool/discussions#1126]
After running my program for 'Make It Modular' I get the green tick for everything except for:
* ✗ Your additional module file [E6-module.js] did not return an Array with the correct number of elements as the second argument of the callback

I don't know what wrong, could anyone help? Here is my code:

module.js:
```javascript
var fs = require("fs");
var path = require("path");

module.exports = function(dirname,extension,callback){
    var list = [];
    var i = 0;

    fs.readdir(dirname, function(err,files){
        if(err){
            return callback(err);
        }
        else{
            files.forEach(function(fileName){
                if(path.extname(fileName) === extension){
                    list.push(fileName);
                }
            })
        }
        return callback(null,list);
    })
};
```

main.js
```javascript
var filemodule = require("./module.js");

var dir = process.argv[2];
var ext = "." + process.argv[3];

filemodule(dir,ext,function(err,files){
    if(err){
        throw new Error("Error");
    }
    else{
        for(var i = 0; i < files.length; i++){
            console.log(files[i]);
        }
    };
});
```

**Comment by dominhhai** [comment]
Don't handle extension on your main file (`main.js`). Pass the original extension for your module file (`module.js:`)

**Comment by AkiraLaine** [comment]
@dominhhai That doesn't really solve the issue.

**Comment by dominhhai** [comment]
Can you show your code here?

**Comment by AkiraLaine** [comment]
@dominhhai I didn't change it since it didn't work. Still same as above.

**Comment by AkiraLaine** [comment]
@dominhhai Do you mind showing me how to do it. I tried different things but doesn't work.

**Comment by dominhhai** [comment]
Handle extension in the module. something like:

module.js:
```javascript
var fs = require("fs");
var path = require("path");

module.exports = function(dirname,extension,callback){
    var list = [];

    fs.readdir(dirname, function(err,files){
        if(err){
            return callback(err);
        }
        else{
            extension = '.' + extension
            files.forEach(function(fileName){
                if(path.extname(fileName) === extension){
                    list.push(fileName);
                }
            })
        }
        return callback(null,list);
    })
};
```

main.js
```javascript
var filemodule = require("./module.js");

var dir = process.argv[2];
var ext = process.argv[3];

filemodule(dir,ext,function(err,files){
    if(err){
        throw new Error("Error");
    }
    else{
        for(var i = 0; i < files.length; i++){
            console.log(files[i]);
        }
    };
});
```

**Comment by dominhhai** [comment]
Can you show me the result after run: `learnyounode  run main.js` ?

**Comment by AkiraLaine** [comment]
```
/home/ubuntu/workspace/fcc-tutorials/main.js:8
        throw new Error("Error");
              ^
Error: Error
    at /home/ubuntu/workspace/fcc-tutorials/main.js:8:15
    at /home/ubuntu/workspace/fcc-tutorials/module.js:9:20
    at Object.oncomplete (fs.js:108:15)
```

**Comment by ClaudioCimarelli** [comment]
had the same problem...

![lyn makeitmodular](https://cloud.githubusercontent.com/assets/7337279/7549225/e381607c-f62c-11e4-89e8-6a67a31a7b2d.PNG)

this is the main file with the callback
![mainjs](https://cloud.githubusercontent.com/assets/7337279/7549233/4cd80e0e-f62d-11e4-95cb-e2b921d9cdf0.PNG)

this is the module 
![mymodulejs](https://cloud.githubusercontent.com/assets/7337279/7549234/534d6572-f62d-11e4-9daa-75ec7ed84269.PNG)

**Comment by martinheidegger** [comment]
@AkiraLaine The error that is thrown is your error, and that is actually quite a good example to learn about exceptions! When you `throw new Error("error")` then you usually don't find out what error occured.
It would be better if you would throw something like: `throw new Error ("Error trying to read the directory! cause: " + err)` 

Could you please change your code and run it again.


@ClaudioCimarelli I doubt its the same problem ;)

**Comment by AkiraLaine** [comment]
@martinheidegger I changed main.js to this:
```javascript
var filemodule = require("./module.js");

var dir = process.argv[2];
var ext = process.argv[3];

filemodule(dir,ext,function(err,files){
    if(err){
        //Do nothing....
    }
    else{
        for(var i = 0; i < files.length; i++){
            console.log(files[i]);
        }
    };
});
```

When I run this it gives me:
* Error connecting to localhost:10770: connect ECONNREFUSED 

The value '10770' changes every time I run main.js.

**Comment by AkiraLaine** [comment]
@martinheidegger I re-ran the code that @dominhhai gave me and for some reason it works.
``` throw new Error("Error")``` is not giving me any problems - weird. I'm going to close this issue - thanks for all your help.

@ClaudioCimarelli - I think you should open a new issue for your problem.
