### ISSUE TITLE
One of stream-adventure's dependencies needs python

### ISSUE THREAD

**Issue by sroe** [nodeschool/discussions#1127]
Hi,

if I run `npm install -g stream-adventure` (in a Git-Bash on Windows 8.1), I'm getting this output: "error: Can't find Python executable "python", you can set the PYTHON env variable.".
So if I run stream-adventure now and select the first lesson it is just doing nothing.

That should be said in help or somewhere else to help beginners understand that this is because stream-adventure needs node-gyp and node-gyp needs python...
Like explained here: http://stackoverflow.com/a/21366601/3111930
So it is not related to Windows-Users only.

Btw: learnyounode and how-to-npm did not need pyhton.

Regards,
Sebastian

**Comment by martinheidegger** [comment]
Hello Sebastian,

there are many libraries that require python (and other things) to compile. Mostly they "just work" (tm) but I agree it can be problematic. 

I raised an issue in the two modules that are used by stream-adventure:

https://github.com/websockets/bufferutil/issues/5
and
https://github.com/websockets/utf-8-validate/issues/4
