### ISSUE TITLE
Processing Inputs

### ISSUE THREAD

**Issue by st2641** [nodeschool/discussions#1128]
I have a project that I am currently working on to create a registration form for a church camp. I have never used Node.js and I am curious as to whether this framework would be appropriate to process the user inputs from a registration form and create outputs in the form of reports and/or emails.

Thank you for your input and direction in advance.

**Comment by bdeanindy** [comment]
Yes, you can use Node.js to handle this...but it may take more time to get yourself up to speed on how to use Node.js to set everything up for the web server, create the client and server side code, connect to a database, and generate the reports depending upon the deadline.

While you're welcomed to run with Node.js to resolve this solution, you might find something like Google Forms, FormStack, or SurveyMonkey more useful to solve this use case quickly. </my $0.02>

**Comment by martinheidegger** [comment]
@st2641 Do you need more help?

**Comment by st2641** [comment]
@martinheidegger I could definitely use the direction to get me going in the right direction. Although the project I discussed in my first post will be due on May 20, I am afraid that the slope of my learning curve may not be adequate enough to get the solution implemented.

My HTML form is complete. I am trying to decide if a back-end solution is overkill or create a simple JS program to handle the inputs and email them to the administrator. I think the latter is more prudent, but not as much fun and nothing to learn there. :)

I will defer to the communities experience (and yours) on whether this is a monumental undertaking or something that could be deployed with less than 15 hrs of commitment. I am at an intermediate level with JS and 0 Node.js experience.

I look forward to your direction and comments.

**Comment by martinheidegger** [comment]
@st2641I am sorry for the late reply. It is definitely not a "monumental undertaking". Node has many libraries to deal with emails, forms and notifications of various kind. It is just important that you know that server code (no matter if its javascript, php or python) has a long list of "things to know". It might be simpler than you think depending on your experience.
