### ISSUE TITLE
skipping workshopper exercises

### ISSUE THREAD

**Issue by seacdwt** [nodeschool/discussions#1130]
I've been working my way through the learnyounode workshopper on my PC at work.  I would like to continue over the weekend at home on a different PC.  Is there a way to skip the exercises I've already completed on a different PC?

**Comment by jkbits1** [comment]
Glad to hear the workshopper has got your interest :smile:  You can install the workshopper on your PC at home, and just start working on the next exercise. The earlier exercises won't be marked as completed, but you don't have to do them again.

Feel free to ask if you have more questions about the workshopper.
