### ISSUE TITLE
Javascripting Rounding Number Tutorial

### ISSUE THREAD

**Issue by qh881** [nodeschool/discussions#1132]
Hi All,
I am a newb to Javascript & Node.js but trying to be methodical with my learning so going through NodeSchool, with Javascript first. At the Rounding Numbers tutorial, I can't seem to get this correct.
My current rounding-numbers is:
```javascript
var roundUp = '1.5';
Math.round(roundUp);
console.log(rounded);
```
I suspect this is wrong but reading the spec on Math.round does not clear up this issue for me and I'd like to know where is a good explanation on Math.round and passing output into further functions?
TIA, QH.

**Comment by dominhhai** [comment]
> The Math.round() function returns the value of a number rounded to the nearest integer.

So, you can take the rounded value with : `var x = Math.round(number)`.
For example: 
```javascript
var roundUp = '1.5';
var rounded = Math.round(roundUp);
console.log(rounded);
```

Check it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) for more info.

**Comment by qh881** [comment]
Hi Dominhhai,
Thanks for that, I get it, I didn't not declare or define the rounded function.
Cool, QH.
