### ISSUE TITLE
Query on No Solutions for Learnyounode Workshop.

### ISSUE THREAD

**Issue by ghost** [nodeschool/discussions#1135]
Hi All,

I finished the Javascripting workshop and discovered while lurking through the HELP, that there was actually a "javascripting solution" option. I might have used it on the two times I was horrendously stuck, if not to complete the exercise, to reverse engineer and work out why the solution was as it was.

Conversely in the Learnyounode workshop, there is no solution option (That I can see) which I feel is an oversight. Not that I am one for taking the easy path, but coming to Node.js, with little Javascript knowledge other than standard web forms etc, the learning curve is a bit steep.

A given solution with key indicators for tricky concepts may be helpful. At the moment I am jammed at "My First I/O" ... I've been through the API Docs, googled relentlessly and yet the solution evades me. Some hand holding would be of value in this case of being stuck before frustration sets in. 

Just my $0.02.

Thanks, QH.

**Comment by breaksy** [comment]
Thank qh881 for taking the words right out of my mouth. I finished the Javascripting workshop without viewing any of the solutions.  It took me a while, but I eventually figured it out. Then I got to Learnyounode. It took me 2 hours to successfully complete Baby-Steps, and I too am now stuck on My First I/O, and have been here for going on 4 hours, which I've spent going through the API docs, etc.

I think logically, I know exactly what should happen, but I may not have sufficient background in Javascript to know the protocol.

This is the first programming I've ever touched in my life (besides a teensy bit of Rails).

**Comment by martinheidegger** [comment]
@breaksy @qh881 The tutorials that are here do require (depending on which you choose) different levels of expertise. `learnyounode` is basic but it requires that you know a little bit of coding. We are discussing on how to close the gap between `javascript` and `learnyounode` but havn't found a good solution yet. Maybe you should join a nodeschool event and get hands-on help by a mentor?

**Comment by breaksy** [comment]
@martinheidegger Unfortunately, I don't currently see any upcoming nodeschool events in my area of the globe.

I'm sure the simplest solution, as @qh881 mentioned, would be to add solutions to the learnyounode workshop as, at the very least, we could read the specific API docs on the elements we see in the solutions and educate ourselves that way.

Until then, I'll work on my `javascript` knowledge and come back to `learnyounode` when I've increased the size of my toolkit.

**Comment by qh881** [comment]
Hi Martin,

Thanks for the tip but like Breaksy, there are no workshops scheduled anywhere close. I can appreciate the efforts that your team must be taking internally to close that gap, but to be honest the context and hint provision for the Learnyounode workshops are not very clear, logical nor helpful.

However I can also appreciate your comments that the Learnyounode workshop requires some knowledge of coding but it seems for some, there is a real conceptual leap that must be made, and sadly some (like myself) will fail. I'd rather do 30 smaller tutorials, with logical incremental steps building up to more complex code successfully, than run head on into a brain buster, such as the "My First I/O".

A long time ago I learnt to use all sort of weapons, vehicles, communications platforms and tactics through managed incremental learning, reinforcement, testing and extension ... that process works however dumb it may seem to outsiders.

Again my $0.02 but in the meantime I will try to find a local Node.js expert or programmer to explain these concepts.

TIA, QH.

**Comment by qh881** [comment]
@martinheidegger 

Hi Martin,

I had a good think about what was causing me issues with conceptually understanding what was/is being asked in the Learnyounode workshops and it was the actual instructions themselves, not so much the concepts of the Node.js/Javascript code.

I rewrote one of the instructions for a Learnyounode workshop as a primer for your team to examine and perhaps implement, in part, to ease the difficulty that some Learnyounode (and other) workshops users may have.

Where do I send the rewrite?

TIA, QH.

**Comment by martinheidegger** [comment]
@qh881 You can propose your changes in the `learnyounode` repository: Either with PR or with issues: https://github.com/workshopper/learnyounode/issues
