### ISSUE TITLE
Stream-Adventure #5 (Lines) - Solution tests as correct, but output is not right

### ISSUE THREAD

**Issue by lsharkey** [nodeschool/discussions#1140]
Hi, I'm a bit confused on the "lines" exercise.  I thought it was wrong because of the output, and decided to verify to see if the test response would help me narrow down the problem.  To my surprise, my solution passed!?!

Here is my code:

```javascript
//lines.js
/*jslint node:true, nomen: true, unparam: true */

'use strict';
var through = require('through2'),
    split = require('split'),
    sData,
    stream,
    counter = 1;

stream = through(function (buff, _, next) {
    sData = buff.toString();
    if (counter % 2 === 0) {
        sData = sData.toUpperCase() + '\n';
    } else {
        sData = sData.toLowerCase() + '\n';
    }
    this.push(sData);
    counter += 1;
    next();
});

process.stdin
        .pipe(split('\n'))
        .pipe(stream)
        .pipe(process.stdout);
```

and this is the output I get when I run it:
```
riverrun, past eve and adam's, from swerve of shore to bend of bay, brings us by a commodius vicus of recirculation back to    howth castle and environs. sir tristram, violer d'amores, fr'over the short sea, had passen- core rearrived from north armorica on this side the scraggyisthmus of europe minor to wielderfight his penisolate war: nor    had topsawyer's rocks by the stream oconee exaggerated themselse   to laurens county's gorgios while they went doublin their mumper   all the time: nor avoice from afire bellowsed mishe mishe to   tauftauf thuartpeatrick: not yet, though venissoon after, had a   kidscad buttended a bland old isaac: not yet, though all's fair in    vanessy, were sosie sesthers wroth with twone nathandjoe. rot a   peck of pa's malt had jhem or shen brewed by arclight and rory    end to the regginbrow was to be seen ringsome on the aquaface.
```

and when I verify it:

```
TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
ok 2 should be equal
ok 3 successful exit code

1..3
# tests 3
# pass  3

# ok

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@     YOUR SOLUTION IS CORRECT!     @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

I think my code should work, and it does pass, but I'm confused by the output.

**Comment by martinheidegger** [comment]
It doesn't make sense to me either.

**Comment by lsharkey** [comment]
Thanks, Martin, so as far as you can see, is my solution correct, or should it have not passed?

**Comment by jkbits1** [comment]
@lsharkey Hi, I'm just chipping in here, not answering on behalf of @martinheidegger at all.

Quite possibly I'm missing something subtle, but to me this situation relates to certain end of line characters behaving differently on different OS's.

I'm using Windows, and for me your output appears correctly, i.e. on multiple lines.

If your OS responds differently to `\n`, it may not show the line-break, but the stream-adventure workshopper will successfully detect the end of line character that your code inserts, and the total output of your code will match against the workshopper's own internal test version of the result.

**Comment by lsharkey** [comment]
@jkbits1 - thanks, that's an interesting idea.  I don't think that's the issue, though.  I'm on a Mac, so different than you, but I haven't run into issues with any other exercises that rely on looking at new lines.

**Comment by jkbits1** [comment]
@lsharkey You'd certainly know better than me about Macs. As another test (of uncertain value), I just ran your code (again on Windows), and pasted the output into Notepad++, and the line break symbols are definitely in there.

Although the main thing is that your code is correct, it'd be good if it displayed correctly on your machine! Perhaps someone else will be able to throw some light on this.

**Comment by lsharkey** [comment]
@jkbits1 - Thanks for testing!  It's nice to know at least that my code is correct.  I appreciate you taking the time to let me know!

@martinheidegger - I'm ok with this now - it looks like my code is right, but I'm not sure whether I should leave this issue open so that someone can take a look at the exercise, or if I should close it.  Please let me know if I should colse.  Thanks!  This is

**Comment by jkbits1** [comment]
@lsharkey It's a pleasure to help, and it's much appreciated that you've formatted your code so well. 

Do ask any more questions you have as you work through the tutorial

**Comment by martinheidegger** [comment]
@lsharkey It would be good if you open an issue at the stream-adventure repo.

**Comment by lsharkey** [comment]
OK, thanks Martin, I will do that, and close this one.

**Comment by dlgood** [comment]
Coming in a bit late but thought I'd help - the issue I see is that you are switching *all* of sData back and forth between upper and lower case, instead of just the chunk you are receiving.  You should use a different variable in your if statement to cover just the new data, and append that to sData.
