### ISSUE TITLE
javascripting working not other modules

### ISSUE THREAD

**Issue by CodeSourceiOSDev** [nodeschool/discussions#1141]
HI!
I just completed javascripting core tutorial... very good!

now,, im trying to install the node first module
```sh
sudo npm install learnyounode -g
```

it all looks fine,

but when I type
```sh
$ learnyounode
```
I get `:: -bash: learnyounode: command not found`

what do I need to run it? thanks

**Comment by martinheidegger** [comment]
@CodeSourceiOSDev I should have installed properly without a problem: What is the output of `sudo npm install learnyounode -g` and what is the output of `echo $PATH`?
