### ISSUE TITLE
different ways of making modules.

### ISSUE THREAD

**Issue by samriddhi** [nodeschool/discussions#1143]
I was working on make it modular tutorial, this is just a small complaint. There are multiple ways to make modules but this tutorial expects me to do it only one way and says i didnt complete it right. I looked at the node.js documentation to create the module so i think that the module should be accepted.

https://nodejs.org/api/modules.html

**Comment by martinheidegger** [comment]
@samriddhi The whole process of creating modules can grow very complex. This particular example requires you to do it this way: If you want to learn the whole - complex - process of packages it might be better to continue on something like https://github.com/npm/how-to-npm , wouldn't you agree?

**Comment by samriddhi** [comment]
Hmmm thats another options but my syntax was a little different shouldn't a
coding tute be able to teach and understand different types of code even if
it's one or two.
Not that I'm saying this is a bad way to learn it's awesome but I just
wished that it told me I failed when I got the right answer and followed
all the criteria

**Comment by martinheidegger** [comment]
@samriddhi I don't think that this basic introduction workshop needs to show/support different approaches but maybe something can be done about the wording. If you think it can be improved you should open an issue or better a PR at learnyounode!
