### ISSUE TITLE
Trouble with Filtered LS

### ISSUE THREAD

**Issue by TheEndIsNear** [nodeschool/discussions#1145]
Having trouble with this one. When I run the code using node `program.js '.' '.js'`, I get a list of all of the .js files in my current directory. But when I run the code using `learningnode program.js`, it returns nothing. 

Here is the code I have so far.
 
```JavaScript
var fs = require('fs');
var path = require('path');
var dir = process.argv[2];
var filter = process.argv[3];

function filterDir() {
    fs.readdir(dir, function (err, files) {
        if(err) {
            throw err;
        }

        var file = files.filter(function (file) {
            return path.extname(file) == filter;
        });
        printFileList(file);
    });
}

function printFileList(files) {
    for (var i = 0; i < files.length; i++) {
        console.log(files[i]);
    }
}

filterDir();
```

**Comment by martinheidegger** [comment]
I am guess its because none of the files `path.extname(file)` matches `filter`. Did you try log the extensions that `path.extname(file)` returns?

**Comment by TheEndIsNear** [comment]
Ok, the problem is, I didn't read the instructions carefully enough to notice that the input would not include a . in front of the extension name. Added the . to the filter and everything works properly.

**Comment by martinheidegger** [comment]
:+1:
