### ISSUE TITLE
HTTP Client exercise issue

### ISSUE THREAD

**Issue by doyouevenNode** [nodeschool/discussions#1146]
I was able run my solution and then started receiving a weird error (no code changes between runs)

First run

```
C:\Users\chouchen\learnyounode>learnyounode run httpclient.js
Roo bar
Spit the dummy
Kindie
Trackies
Boardies
Parma
Esky
Rack off
Bradman
Waratah
```

Immediately ran it again with verify and got this-

```
C:\Users\chouchen\learnyounode>learnyounode verify callModule.js
There was an error: { [Error: ENOENT, scandir 'C:\Users\chouchen\learnyounode\http:\localhost:63588']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\chouchen\\learnyounode\\http:\\localhost:63588' }

Your submission results compared to the expected:
...
```

Thanks for any assistance.

**Comment by hokennethk** [comment]
Hi @doyouevenNode,

I noticed that you ran httpclient.js the first time, but are verifying callModule.js the second time. Did you mean to verify httpclient.js?
