### ISSUE TITLE
my solution for Juggling Async does Not work ?

### ISSUE THREAD

**Issue by newbeebin** [nodeschool/discussions#1148]
my following solution for  Juggling Async works. However, when I replace the calling to my function myGet() with the content of the function, it does not work. Can anyone give me a reason ? thanks.

```javascript
var http = require('http');
var res = ['','',''] ;
var collect=0;

function out() {
    for(var i =0;i<3;i++)
        console.log(res[i]);
}

function myGet(idx) {
    http.get(process.argv[idx+2], function (response) {
        response.setEncoding('utf8')
        response.on('data', function(resp) { 
            res[idx]+= resp;
        }) .on('end', function() {
            collect++; 
            if(collect==3) 
                out();
        })
    })
}

for( idx = 0 ; idx<3; idx++ ) {
    myGet(idx);
}

The above code works( I use learnyounode verify myCode.js to check it). 

The code below does not work.  But I think they should be equivalent

var http = require('http');
var res = ['','',''] ;
var collect=0;

function out() {
    for(var i =0;i<3;i++)
        console.log(res[i]);
}

for( idx = 0 ; idx<3; idx++ ) {
    http.get(process.argv[idx+2], function (response) {
        response.setEncoding('utf8')
        response.on('data', function(resp) { 
            res[idx]+= resp;
        }).on('end', function() {
            collect++; 
            if(collect==3) 
                out();
        })
    }) 
}

**Comment by davecocoa** [comment]
The difference is that in the working version, you have two different `idx` variables. The `idx` variable in the for loop goes from 0 to 3 and then stays at 3 forever. The `idx` variable in the function `myGet` is set when the function is called (new and different variable for every time the function is called) and it never changes.

If you take the contents of `myGet` and put it inside the for loop, your single `idx` variable will be `3` by the time your http calls return.

**Comment by martinheidegger** [comment]
@newbeebin does that work for you?

**Comment by newbeebin** [comment]
Thanks Davecocoa , your explanation is really helpful. 
Could u please explain more about how the node.js interpreter deals with the call back functions? for example , you said:"in the working version, you have two different idx variables. The idx variable in the for loop goes from 0 to 3 and then stays at 3 forever. The idx variable in the function myGet is set when the function is called (new and different variable for every time the function is called) and it never changes." how does node.js interpreter make the call back function remember the three different values of the idx? does it create an idx variable each time when myGet is called ? and does node.js also made three copies of the callback function ,so that it can remember the different value or address of the idx variables ?

Thanks.

**Comment by davecocoa** [comment]
Firstly, I do not have experience with the internals of node.js or any other JavaScript interpreter, I just know how they behave from the outside.

Essentially, every time a function is called, that creates a new distinct context containing all the variables within that function, without actually copying the function body itself. So yes, it creates a new `idx` variable each time `myGet` is called.

This is often referred to as a closure, you can get some more examples and info on MDN : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by martinheidegger** [comment]
(PS.: @davecocoa It is a good idea to end your response with a question, this way the other person knows that their input is "wanted")

**Comment by davecocoa** [comment]
Great point, thanks!

@newbeebin Does that answer your question? The way I think of it, every time a function is called, it creates a new piece of memory related to that particular call, does that make sense to you?

**Comment by newbeebin** [comment]
Yes，your answer and the link are very helpful for me to understand the closure mechanism of JS.
Thanks a lot.
Btw another question: currently I have finished the 13 excercises of learnyounode. what should I study next step to improve my node.js skill ?
Thanks.

**Comment by davecocoa** [comment]
:clap: :tada: :confetti_ball:  Well done for finishing `learnyounode`! If you're interested in learning more about node in particular, I'd recommend looking at other exercises on [nodeschool.io](http://nodeschool.io/index.html#workshopper-list), maybe `stream-adventure` or `levelmeup`, there are lots to choose from!

If that answers your question, could you close this issue?

**Comment by newbeebin** [comment]
Thanks, got it.
