### ISSUE TITLE
HTML Banner

### ISSUE THREAD

**Issue by marksmall** [nodeschool/discussions#1149]
Hi there,

Sorry if this is the wrong place to post this.

We have been supplied with some 3rd party code that inserts an HTML Expandable Banner on the top of our page.  It is easy to add a script tag to get the javascript imported so it can do this.  What I would like to do is to convert this into a general module so it can be imported as a npm or bower package.

So, what do I really want to do?
I would like to write a module that adds a banner immediately after the body tag.  I created a bower module that has a JavaScript function, it just does a number of document.createElement('...'); statements and finally appends all this to the body.

What I need to know is what is the best way to do this?  Any advice is welcome.

**Comment by martinheidegger** [comment]
Did you try http://browserify.org/?

**Comment by marksmall** [comment]
In the end I created the raw HTML, copied that to a string variable inside some JavaScript.  I then use JavaScript to insert this HTML as the first child of the Body element.  I created Data URIs of the images used and inserted them into the HTML.  I created a bower package specifying the JavaScript and CSS files as the main files (these are then injected into my app via browserif).

May not be the best solution and I'm open to ideas for improvements.  You can see the repo at: https://github.com/edina/jisc-banner

**Comment by martinheidegger** [comment]
Thank you for the follow-up. Looks like you solved your issue!
