### ISSUE TITLE
Help needed with module exports

### ISSUE THREAD

**Issue by WalterPhillips** [nodeschool/discussions#1150]
This is the error I get:

✓ Submission results match expected
✗ Your additional module file [fileFilter.js] does not export a single function. You must use the `module.exports = function () {}` pattern.

This is my code in the module:
```javascript
  module.exports.filter  = function (directory, extFilter) {
     //// blah blah blah
  };
```
Can someone help?

Thanks.

**Comment by WalterPhillips** [comment]
I found my mistake.

The module file's code should look like:
```javascript
 module.exports  = function (directory, extFilter) {
     //// blah blah blah
  };
```

And the file calling the module should look like, without expecting the function name filter as previously specified. Should be as below:
```javascript
var fileModule = require('./theModule.js');
var returnObj = fileModule(args).;
```

**Comment by jkbits1** [comment]
That's great you solved it :tada:  thanks for letting us know :+1: 

Please ask any more questions you have as you go through the tutorial
