### ISSUE TITLE
Make it Modular complaining about not handling error in callback

### ISSUE THREAD

**Issue by WalterPhillips** [nodeschool/discussions#1151]
I am getting the following error when submitting my solution:

✗ Your additional module file [fileFilter.js] does not appear to pass back an error received from `fs.readdir()`.
  Use the following idiomatic Node.js pattern inside your callback to `fs.readdir()`:
        if (err)
          return callback(err)

But I am passing back the error. 

Below is the module code:
```javascript
module.exports = function (directory, extFilter, callback) {

    // some code
    fs.readdir(directory, function (err, fileList) {
        if (err) {
            return callback(err);
        }
        
        // other portion of the code
        });
    });
    
    return callback(null, filteredFiles);
}
```
The code calling the module:
```javascript
// Getting the input data
var directory = process.argv[2];
var extFilter = process.argv[3];

// Defining callback to be passed to function module
var myCallbackFunc = function(err, data) {
    if (err) {
       console.log(err);
    }
    // more code
}

var fileList = require('./fileFilter.js');
fileList(directory, extFilter, myCallbackFunc);
```
And in the calling 
Any pointers in what I'm doing wrong here?

**Comment by jkbits1** [comment]
Thanks for letting us know how you're getting on.

The code behind the tutorial for this particular test is a bit tricky, and unfortunately doesn't always manage to report the error accurately. As you say, your code pattern looks correct. It may well be that you have a different error to the one reported.

By all means, show us more of your code if you can't see any obvious mistakes anywhere.

**Comment by WalterPhillips** [comment]
Thanks for responding, Jon. 

Below is the module code:
```javascript
module.exports = function (directory, extFilter, callback) {

    var fileFilter = "." + extFilter;
    var fs = require("fs");
    var filteredFiles = [];
    
    fs.readdir(directory, function (err, fileList) {
        if (err) {
            return callback(err);
        }
    
        var path = require('path');
        
        fileList.forEach(function (file) {
            if (path.extname(file) === fileFilter) {
                console.log(file);
                filteredFiles.push(file);
            } 
        });
    });
    
    return callback(null, filteredFiles);
}
```

**Comment by WalterPhillips** [comment]
Thanks for responding Jon.
It turns out to be exactly as you said, something else in a different portion of the code. In pasting the code here, I noticed the error... I was logging the output from the module code instead of the calling code.  Fixing that resolved the issue.

**Comment by jkbits1** [comment]
I'm glad I could help. Great to hear you're getting on well :smile:
