### ISSUE TITLE
Exercice 8: http collect

### ISSUE THREAD

**Issue by Djabx** [nodeschool/discussions#1152]
For the excercice 8 I wrote this:

``` javascript

var http = require('http')

http.get(process.argv[2],
  function(response) {
    response.setEncoding('utf8')
    var result = [];
    response.on("data", result.push)
    response.on("error", console.error)
    response.on("end",
      function () {
        var s = result.join('')
        console.log(s.length)
        console.log(s)
      }
    )
  }
)
```

But it does not work, the `result` is always empty.
Can somebody explain why to me ? 

BTW this solution work well :
```javascript
var http = require('http')

http.get(process.argv[2],
  function(response) {
    response.setEncoding('utf8')
    var result = [];
    response.on("data", function (data){result.push(data)})
    response.on("error", console.error)
    response.on("end",
      function () {
        var s = result.join('')
        console.log(s.length)
        console.log(s)
      }
    )
  }
)
```

**Comment by davecocoa** [comment]
So, your question is, "what's the difference between `result.push` and `function (data){result.push(data)}`?", right?

The answer is context. In JavaScript, object properties have no automatic ties to their parent object. For example, if I define an object `b` as `var b = { c: 7 }` and then I call a function like `add(4, b.c)`: the function `add` receives the numbers `4` and `7`, and it has no idea that the number `7` happened to be attached to the object `b`. It works the same for functions:

```js
var b = {
  total: 0,
  add: function(num){
    this.total = this.total + num;
  }
};

b.add(7); // call the function b.add with the context of b
console.log(b.total); // 7

var badAdd = b.add; // store the function b.add in the variable badAdd
badAdd(4); // call the function badAdd with no context
console.log(b.total); // 7
```
More specifically, context relates to the value of `this`. The [MDN docs about `this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) are well worth a read. For this specific problem, you can use [Function.bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to produce a new function with its context bound to the correct object: `result.push.bind(result)`.

I hope that answers your question at least a little, there's plenty to be confused about here so feel free to ask more questions if anything is unclear =)

**Comment by Djabx** [comment]
Thank you !

I'm going to read the MDN article rigth away !

I'm coming from the python world where we do not have this kind of problems ;)
