### ISSUE TITLE
LearnYouNode: Make It Modular. Beginning programmer.

### ISSUE THREAD

**Issue by hunterlester** [nodeschool/discussions#1153]
My first post ever:
-I've searched through other questions about lesson 6 (Make It Modular) but they seem to be made by more experienced people than myself. Reading others' code solutions confuses me more unless I have a basis for understanding.
-Art-of-node has been wonderfully helpful and I feel like I'm mentally grasping callbacks. Asynchronous file operations make sense and I was able to complete the previous exercises.
-Now, I need a foundation for understanding how to build this module.

Thank you so much for your help.

Module File

    var fs = require('fs');
    var path = require('path');

    var fileFilter = function(dir, extfilter, callback) {
	    fs.readdir(dir, function (err, list){
		    for (var file in list) {
			    if (path.extname(list[file]) === '.' + extfilter) {
				    return list[file];
			    }
		    }
	    });
    };

    module.exports = fileFilter;

File which calls the module

    var fileFilter = require('./fileFilter.js');

    fileFilter(process.argv[2], process.argv[3], function (err, list)) {
	    if (err) {
		    return function (err);
	    }
	    //Here I should console.log the returned filtered files?
	    //And then callback(null, data)?
	
    };

**Comment by cypherrage** [comment]
>    //Here I should console.log the returned filtered files?
>    //And then callback(null, data)?

All you have to do where these comments are is loop through and print the contents of 'list'.

callback(null, data) should be returned in your module file.

**Comment by hunterlester** [comment]
Thank you cypherrage, I'll try to get that to work today.

**Comment by hunterlester** [comment]
I'm getting closer I think. The files no longer return errors at least.

Module File

    var fs = require('fs');
    var path = require('path');

    var fileFilter = function(dir, extfilter, callback) {
	    fs.readdir(dir, function(err, list) {
		   if (err)
			    return callback(err);

		    for (var file in list) {
			    if (path.extname(list[file]) === '.' + extfilter) {
				    return list[file];
			    }
		    }
		    callback(null, list);
	    })

	
    };

    module.exports = fileFilter;

File which calls Module

    var fileFilter = require('./ex6.js');

    fileFilter(process.argv[2], process.argv[3], function(err, list) {
	    console.log(list);	
    });

**Comment by cypherrage** [comment]
Just create a temporary array and push each good file you find to it, then just return that.  I think that should clear things up.

**Comment by hunterlester** [comment]
Module File
    var fs = require('fs');
    var path = require('path');



    var fileFilter = function (dir, extfilter, callback) {
	    fs.readdir(dir, function(err, list) {
		    if (err)
			    return callback(err);

		    var fileList = [];

		    for (var file in list) {
			    if (path.extname(list[file]) === '.' + extfilter) {
				    fileList.push(list[file]);
			    }
		    }
		    // return fileList;
		    callback(null, list);
	    })

	
    };

    module.exports = fileFilter;

File calling module

    var fileFilter = require('./ex6.js');

    fileFilter(process.argv[2], process.argv[3], function (err, list) {
	    if (err)
		    return err

	    console.log(list);
    });

I notice that when I try to return anything, the console.log is blank. However, when I comment out the return, the console logs the directory.

Is this what you meant by adding an array, pushing to it, and returning it?

**Comment by cypherrage** [comment]
Basically, you sent the directory of the file to read and the type of file you wanted to filter from the 1st to the 2nd module.  In the 2nd module, you filtered the type of file you wanted based on the extension.  When you found something you wanted, you put it on your "list", or array in this case.  Finally, when you were done, you used the "callback" function to print the list of files to the console.  The trick here is that you made a "printer" function that you SENT into the 2nd module; this way you are technically not printing from the 1st module but the 2nd one.  When you type callback(null, newlist), that is you invoking the function that you created when calling fileFilter in your primary module.

If you have any other questions just let me know.

**Comment by hunterlester** [comment]
Thank you for your time and for helping me understanding this lesson. This was a big one for me. I'm going to let it all sink in.
