### ISSUE TITLE
(MAC)I downloaded Node.js correctly, but get an error when I run npm install -g learnyounode

### ISSUE THREAD

**Issue by Felisan** [nodeschool/discussions#1157]
Hi! I checked that node is correctly installed using the command node -v (which returns v0.12.3), and I have even updated npm to latest version just in case, by using the sudo npm install npm -g. But still, when trying to run npm install -g learnyounode, I get this error message: 
FELICITASs-MacBook-Air:~ feli$ npm install -g  learnyounode
npm ERR! tar.unpack untar error /Users/feli/.npm/learnyounode/2.5.2/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "learnyounode"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0
npm ERR! path /usr/local/lib/node_modules/learnyounode
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/learnyounode',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/learnyounode',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/feli/npm-debug.log

Can anyone help me with this issue? Thank you so much!

**Comment by dominhhai** [comment]
How about: `sudo npm install -g learnyounode` ?

**Comment by Felisan** [comment]
yes! Thank you! that did the trick!
