### ISSUE TITLE
Promise It Won't Hurt, Challenge 1: Include description of defer.resolve()

### ISSUE THREAD

**Issue by michealparks** [nodeschool/discussions#1158]
In the first challenge the parent object of .resolve() isn't made clear, which may be confusing to newcomers. (is it defer.resolve? is it promise.resolve?)

Suggestion: add a short descriptor for how Q resolves promises.

Example: "In Q, promises are resolved using the "resolve" method of the defer that is created."

**Comment by martinheidegger** [comment]
@michealparks Can you open a PR at promise-it-wont-hurt?

**Comment by michealparks** [comment]
@martinheidegger Sure! What's the repo's URL?

**Comment by martinheidegger** [comment]
https://github.com/stevekane/promise-it-wont-hurt
