### ISSUE TITLE
functional-javascript higher order functions exercise

### ISSUE THREAD

**Issue by SOSANA** [nodeschool/discussions#1159]
Hi all,

Curious if this is acceptable alternative way of doing this exercise. It passes, gets the same results but is different than the offical solution.

``` JavaScript
function repeat(operation, num) { 
    // SOLUTION GOES HERE
    var someOperation = operation(num);
    return someOperation;
} 
```

**Comment by martinheidegger** [comment]
@SOSANA It is no problem if your solution is different from the official solution. As long as you learn along the way and enjoy the trip, everything is fine :smile:

**Comment by SOSANA** [comment]
@martinheidegger that is the best response I have read. 
" It is no problem if your solution is different from the official solution. As long as you learn along the way and enjoy the trip, everything is fine :smile:"

:+1:  

At first it looks though the solution I provided shouldn't work. But kept brainstorming about the following: 

```
* Arguments
 * operation: A Function, takes no arguments, returns no useful value.
 * num: the number of times to call `operation`.
'''

what a cool way to pass in other functions around. 

Would be correct to say I am injecting other functions as arguments that executes the passed in function num times?

**Comment by davecocoa** [comment]
Does that solution pass when you run `functional-javascript-workshop verify`? It doesn't pass on my machine...

**Comment by SOSANA** [comment]
@davecocoa Here is a screen shot of it passing :)

![image](https://cloud.githubusercontent.com/assets/2634185/7798455/4dd757d8-02b7-11e5-809d-cdd75faac44a.png)

**Comment by davecocoa** [comment]
Well, I'm not sure what else to tell you. That solution definitely shouldn't pass, are you sure you're using the correct file name?
