### ISSUE TITLE
learnyounode excerise#3(My first I/O)

### ISSUE THREAD

**Issue by TriumphantAkash** [nodeschool/discussions#1161]
Here is my code:
---------------------------------------------------------

```JavaScript
var fs = require('fs');
var buf = fs.readFileSync(process.argv[0]);//read the data from file specified and saves it in Buffer type object
var str = buf.toString();//convert Buffer type object into string
var str1 = str.split("\n");//split the whole string into parts using "\n" as delimiter
console.log(str1.length - 1); //print the number of \n in the whole long string
```
---------------------------------------------------------
It does not pass the test case, I am not able to figure out the error

**Comment by martinheidegger** [comment]
@TriumphantAkash If you post the error output its a lot faster for people to help. My assumption is that your count is 1 off

**Comment by TriumphantAkash** [comment]
learnyounode verify fileread.js 

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "88337"                             !=    "28"                               
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!
✓ Used synchronous method: fs.readFileSync()

# FAIL

Your solution to MY FIRST I/O! didn't pass. Try again!

**Comment by martinheidegger** [comment]
Oh! Hint: The content of `process.argv` is not like you think it is! Did you try to check the content of `process.argv`?

**Comment by TriumphantAkash** [comment]
when I try to run my javascript file without using learnyounode it gives me the following error:
----------------------------------------
node fileread.js abcd 
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'node'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/home/akash/Desktop/NodeJS/nodeSchool/fileread.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

----------------------------------------

**Comment by Imahmedz** [comment]
When executing a Node file, you use the command node myfile.js /path/to/file.
When using the process.argv[], you need to pay attention to the index. process.argv[0] stands for node, argv[1] for myfile.js and argv[2] for /path/to/file.
In the exercise, we want the path, so we want to use the argv[2] as an argument in readFileSync.
You just need to change the index, everything is fine ;)

**Comment by flacoman91** [comment]
I also had this same issue.  The instructions for the mission says:

```

The full path to the file to read will be provided as the first command-line argument. 
You do not need to make your own test file.

```

**Comment by martinheidegger** [comment]
My hint obviously didn't help you @TriumphantAkash but @Imahmedz did explain it clearer. Did you complete the exercise?

**Comment by TriumphantAkash** [comment]
@Imahmedz pointed out my mistake. I corrected my code now it works fine.
@martinheidegger @flacoman91 @Imahmedz thank you guys for quick response and helping me out
