### ISSUE TITLE
Node Fail

### ISSUE THREAD

**Issue by SPManore** [nodeschool/discussions#1162]
Installed node, launched it.  
Anything I do generates a ReferenceError

even Node -v results in: ReferenceError: Node is not defined.

I've obviously gone off the rails.

**Comment by martinheidegger** [comment]
@SPManore I am guessing that you installed it in windows? Maybe you are launching the wrong command? The windows installation comes with `Node.js` and `Node Command Prompt`. The 2nd one is the one you might be looking for. If not, perhaps you could give a little more information?

**Comment by SPManore** [comment]
Yes, that was it.  Feeling sheepish.  Thanks.
