### ISSUE TITLE
bytewiser line_splitter exercise

### ISSUE THREAD

**Issue by kevin2r** [nodeschool/discussions#1163]
Exercise:
The argument given to you from `process.argv[2]` will be a path to a file.
Read this file and split it by newline characters ('\n'). You should log
one Buffer per line.
Bonus points if you never use `.toString()`.

Here is my code:
-------------------------------------------------------------------------------------------------
```js
var fs = require('fs');

fs.readFile(process.argv[2], function (err, data){
  if (err) throw err;

  var offset = 0;

  for (var i = 0; i < data.length; i++ ){

    if (data[i] === 0xA) {     
      console.log(data.slice(offset, i));
      offset = i + 1; 
    }
  }
});

```
---------------------------------------------------------------------------------------

And no pass the bytewiser test

if you execute my code on text file, for example:
----------------------------------------------
asd
bsd
csd
dsd
esd

-----------------------------------

Exit:
```
Buffer 61 73 64
Buffer 62 73 64
Buffer 63 73 64
Buffer 64 73 64
Buffer 65 73 64
Buffer 
Buffer 
```
What is wrong here?

Thanks!!

**Comment by martinheidegger** [comment]
`fs.readFile` does not return a String by default. It returns a Buffer object. This object can be easily converted to a string with `toString`. Does that help?
