### ISSUE TITLE
Javascription install

### ISSUE THREAD

**Issue by mkawsar** [nodeschool/discussions#1164]
How to javascripting install on ubuntu 14.04?

**Comment by Imahmedz** [comment]
After installing Nodejs on your machine (please refer to this link: https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager )

You can use npm to install Javascription, using the command : npm install -g javascripting

**Comment by martinheidegger** [comment]
Did you read https://github.com/nodeschool/discussions/wiki/Installation-suggestions#ubuntudebian ?
