### ISSUE TITLE
MY FIRST ASYNC I/O! not working, even with the correct solution

### ISSUE THREAD

**Issue by henkel0** [nodeschool/discussions#1165]
I'm trying to pass "My First ASYNC I/O" problem, but it keeps telling me that I'm not using the assynchronus method, but I do use it.

I've tried with a lot of different options but it says the same. Even with the correct answer given here https://github.com/workshopper/learnyounode/blob/master/exercises/my_first_async_io/solution/solution.js

Here's the code:
```javascript
var fs = require('fs')
var file = process.argv[2]

fs.readFile(file, function (err, contents) {
  // fs.readFile(file, 'utf8', callback) can also be used
  var lines = contents.toString().split('\n').length - 1
  console.log(lines)
})
```
And the aswer in the terminal:
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "39"                                ==    "39"                               
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✗ Used asynchronous method: fs.readFile()

# FAIL

Your solution to MY FIRST I/O! didn't pass. Try again!
```
Any idea of what is wrong?

**Comment by jurasec** [comment]
Hi, you must use s.readFileSync( );

The hints say:

## HINTS
All synchronous (or blocking) filesystem methods in the fs module end with 'Sync'. To read a file, you'll need to use fs.readFileSync('/path/to/file'). This method will return a Buffer object containing the complete contents of the file.

**Comment by henkel0** [comment]
@jurasec I'm sorry, I had a mistake in the title but it was the asynchronous excercise. But suddenly it worked with the answer that I already have. Thanks.

**Comment by jurasec** [comment]
Cool! :-]
