### ISSUE TITLE
async juggle error

### ISSUE THREAD

**Issue by polizz** [nodeschool/discussions#1166]
I get the following error on my solution and the solution provided by the exercise:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)

Not totally sure what else to provide, so if you ask for more information, I'll try to add it.

**Comment by martinheidegger** [comment]
Can you try to restart your mac?

**Comment by polizz** [comment]
Just rebooted and tried again, same error. When I print all the args out, this is what I'm getting:

C:\Program Files\nodejs\node.exe
C:\Users\Andrew\Documents\js\async-juggle2.js
http://localhost:49614
<<end of args>>

What's weird is when I try to verify, it's says it's expecting a fourth printed item.

**Comment by martinheidegger** [comment]
I think I understand the issue now (and its a *b....*) There are two factors that play into that issue. 1) A wonky/not-existant internet connection and/or 2) proxies. It is possible to set http proxies and my short research told me that learnyounode will not work if you have set a http proxy. Also I think that a internet connection is required to start a local server. but that would be weird somehow.

**Comment by polizz** [comment]
I'm working on a surface pro 3, but it's been docked or plugged in at home. I'm constantly browsing the web for while I work the exercises too.

I tried disabling the Windows Firewall and an Adblocker but no change. I also had set a proxy the other day but had disabled it (I confirmed this).

Below is the full error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
✗ Error connecting to http://localhost:59081/api/parsetime?iso=2015-05-24T13:29:30.072Z: connect ECO
NNREFUSED
C:\Users\Andrew\AppData\Roaming\npm\node_modules\learnyounode\exercises\http_json_api_server\exercis
e.js:75
        var data = _data.toString()
                        ^
TypeError: Cannot read property 'toString' of undefined
    at BufferList.onData [as _callback] (C:\Users\Andrew\AppData\Roaming\npm\node_modules\learnyouno
de\exercises\http_json_api_server\exercise.js:75:25)
    at BufferList.<anonymous> (C:\Users\Andrew\AppData\Roaming\npm\node_modules\learnyounode\node_mo
dules\bl\bl.js:16:14)
    at DestroyableTransform.emit (events.js:107:17)
    at ClientRequest.<anonymous> (C:\Users\Andrew\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\hyperquest\index.js:13:19)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by polizz** [comment]
Like the program overall though man! I just finished it and I learned a lot! Just downloaded more packages today :)

**Comment by marocchino** [comment]
that TypeError is fixed with workshopper/learnyounode#301 but, real problem is verify against http_json_api_server.

can you run  `learnyounode current` on console?

**Comment by polizz** [comment]
![image](https://cloud.githubusercontent.com/assets/10888433/7798826/c8675f5e-02c4-11e5-870c-7aa83d3d2e18.png)

```C:\Users\Andrew\Documents\js>learnyounode current
HTTP JSON API SERVER```
