### ISSUE TITLE
Having trouble installing first workshopper

### ISSUE THREAD

**Issue by Chrinkus** [nodeschool/discussions#1167]
Just found this resource and wanted to get started. I downloaded node.js and tried to install the first workshop. It was suggested I try running command as root/ADMINISTRATOR which I should be because its my Mac.
I tried to upload the debug log as requested but it was rejected.

**Comment by SomeoneWeird** [comment]
What's the actual error?

**Comment by Chrinkus** [comment]
its an EACCES error. just found an installation guide that indicates this is common.
