### ISSUE TITLE
Why can't I turn cat to cats?

### ISSUE THREAD

**Issue by Welly0902** [nodeschool/discussions#1169]
```JavaScript
var pets=['cat','dog','rat']
for(i=0;i<=2;i++){
  pets[i] = pets[i]+'s';
}
console.log(pets[i])
````

I want to add an s into the array
but the result shows"undefined"
Can anyone tells me where am I wrong :stuck_out_tongue:

**Comment by davecocoa** [comment]
Your `console.log` line is outside the `for` loop, so it runs when the `for` loop is 'finished'. When the `for` loop has finished running, the value of the `i` variable will be `3`. Looking at `pets`, we can see that since it only has 3 elements, `pets[3]` will be undefined.

**Comment by martinheidegger** [comment]
@Welly0902 Is dave's explanation good for you?
