### ISSUE TITLE
Tutorial colour scheme

### ISSUE THREAD

**Issue by archieopteryx** [nodeschool/discussions#1170]
I've installed the javascripting tutorial, on a Windows 7 machine, and when I go into a lesson I have the occasional word in dark blue on a black background, which is unreadable unless I am a few inches from the screen.

Can these colours be changed?

Forgive me if this is a basic question, but it's not something I've had to consider before.

**Comment by martinheidegger** [comment]
There is a discussion on this :disappointed: . Any help welcome https://github.com/nodeschool/organizers/issues/24

**Comment by archieopteryx** [comment]
@martinheidegger thanks for the reply, and the link.
