### ISSUE TITLE
learnyounode Exercise 3 File IO Wrong?

### ISSUE THREAD

**Issue by fhariyadi** [nodeschool/discussions#1171]
I think there is a bug on this exercise.

Everyone solutions involve substract 1:
console.log(contents.split('\n').length - 1);

Is this correct?
I tried with my own file, it always short 1 line. I believe the right solution does not need to substract 1

**Comment by jerrychoubear** [comment]
I think the reason why substract 1 is that every line has a '\n' at the end except the last one.

**Comment by fhariyadi** [comment]
Logically it is wrong.

Take this as example:
Line 1: abc \n
Line 2: abcd

If you split by "\n", you have array with length = 2 already. 

I think the hint is for other algorithm. suppose if you count the number of lines by the occurance of "\n", then you need to ADD 1 (As the last line usually does not have \n.

I think this is a bug In learn you node.

**Comment by martinheidegger** [comment]
A PR for this already exists. https://github.com/workshopper/learnyounode/pull/237/files
