### ISSUE TITLE
Error: EACCES, permission denied 'gulpfile.js'

### ISSUE THREAD

**Issue by neocarvajal** [nodeschool/discussions#1173]
hi i have some troubles with the nodejs you can help me? i used node source instalation.

```
   create gulpfile.js
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EACCES, permission denied 'gulpfile.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at BespokeGenerator.<anonymous> (/usr/lib/node_modules/generator-bespoke/node_modules/yeoman-generator/lib/actions/actions.js:209:10)
    at EventEmitter.g (events.js:199:16)
    at EventEmitter.emit (events.js:107:17)
    at /usr/lib/node_modules/generator-bespoke/node_modules/yeoman-generator/lib/util/conflicter.js:58:20
    at EventEmitter.collision (/usr/lib/node_modules/generator-bespoke/node_modules/yeoman-generator/lib/util/conflicter.js:143:12)
    at /usr/lib/node_modules/generator-bespoke/node_modules/yeoman-generator/lib/util/conflicter.js:57:18
    at /usr/lib/node_modules/generator-bespoke/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21

```

i have created a new group for nodejs and i try to change all directories in node_modules
but still the problem with **Error: EACCES, permission denied 'gulpfile.js'** :rage:

**Comment by martinheidegger** [comment]
It looks like the user that runs the node process does not have access to the gulpfile.js. Can you check your permissions?

**Comment by neocarvajal** [comment]
i have the owner rights to those files :
![node-2](https://cloud.githubusercontent.com/assets/3886811/7797560/9de8de2c-02b7-11e5-8efe-c229471e111e.png)

**Comment by neocarvajal** [comment]
Here is the problem that i commented : 
![node-1](https://cloud.githubusercontent.com/assets/3886811/7797594/21512a08-02b8-11e5-9129-acfd14745503.png)
