### ISSUE TITLE
how-to-npm, lesson 3, unable to add user

### ISSUE THREAD

**Issue by CalliEliza** [nodeschool/discussions#1174]
Hello,

I keep getting the error below when I try to add user.  I type in a username, password, and an email address and get the messages below.  Any help is appreciated.  Thanks. 

npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "adduser"
npm ERR! node v0.10.35
npm ERR! npm  v2.10.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:callie
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by marocchino** [comment]
npm/npm#8198 ?

**Comment by CalliEliza** [comment]
Thanks... I thought I had looked and didn't see this posted anywhere.
