### ISSUE TITLE
break statements in async maps 

### ISSUE THREAD

**Issue by thivyae** [nodeschool/discussions#1175]
I wan to  break from this async map when element text is equal to expected text and come out of the loop and click on element .
Im not able to perform click action as the console.log gets executed continously for all map  elements  and click is never performed

My code:

``` JavaScript
DefaultRecipePage.prototype.goToCustomizeRecipePage =function() {
 var expectedText="Ristretto";
 return  this.driver.elementsByClassName('android.widget.TextView').then(function(elements,callback){
    async.map(elements,function (element){
      var elementText=element.text();
      return elementText.then(function(text,element){
        console.log('Text is'+text);
        if(text===expectedText)
        {
          console.log('going to click');
          return element;
        }  
      });
      this.driver.element.click();
    });
    callback();
  });
}
```

**Comment by martinheidegger** [comment]
Hello @thivyae 
I took the liberty to format your code. If you read it now you can see that `this.driver.element.click()` is after the return statement. Code after any return statement will not be called.

**Comment by thivyae** [comment]
Hi 
I'm still facing the issue..
I have changed my function now..here is snippet:

DefaultRecipePage.prototype.goToCustomizeRecipePage =function() {
 var expectedText= 'ristretto' ;
 var deferred = Q.defer();
 var that=this;
 return  this.driver.elementsByClassName('android.widget.TextView').then(function(elements,callback){
 async.each(elements,function (element,callback){
      var elementText=element.text();
       elementText.then(function(text){
        console.log('Text is'+text);
        if(text===expectedText)
        {
          console.log('going to click');
          deferred.resolve(element.click(that.driver));
          return deferred.promise;
        }
      });
      console.log("looping back");
      callback() ;
    });
callback(); 
  });
};
now the method which calls the above method is below:::

this.pages.defaultRecipePage.goToCustomizeRecipePage(defaultRecipe).then(function(){
      console.log("complete");
      callback();
    }); 
Now,my problem is the element is clicked but the control is not returning back...console.log("complete") is not printed..
