### ISSUE TITLE
learnyounode command does nothing

### ISSUE THREAD

**Issue by bhaumikkothari** [nodeschool/discussions#1177]
Installed Node.js
& done:
sudo npm install learnyounode -g

Then running learyounode command does nothing.
Platform: Ubuntu
nodejs version: 0.10.37

Thanks,

**Comment by SomeoneWeird** [comment]
Try running `sudo apt-get install nodejs-legacy` and then try again.

**Comment by bhaumikkothari** [comment]
done! Thanks.
