### ISSUE TITLE
Issue while running installing global javascripting

### ISSUE THREAD

**Issue by ANKUR1983** [nodeschool/discussions#1178]
Hi there,

I am new to the node.js world and keen to learn it. I have downloaded the 'node-v0.12.4-x64' for my Windows & machine. I am trying to follow the beginners tutorial. However, I don't understand what does the following mean 
Open your terminal and run this command:
npm install --global javascripting

Is it that I have to dun the npm command script? 

Appreciate your assitance.

**Comment by scotchbrite** [comment]
When you installed node.js npm was automatically added to your PATH. just open a command prompt (cmd) and run npm install --global javascripting. It should work ;)

**Comment by ANKUR1983** [comment]
thanks a lot mate. It's working fine now.
