### ISSUE TITLE
I'm trying to get back to the beginning...

### ISSUE THREAD

**Issue by Angelfirenze** [nodeschool/discussions#1179]
Because I got stuck in the Github tutorial and I'm already listed as a contributor.  Every time I delete the repository to start back at the beginning, I'm now getting error messages because the information I'm pulling down from Github when cloning includes the information that lists me as a contributor.

I'm not sure what to do because, as a result of these errors, I cannot move forward with the exercise.

**Comment by martinheidegger** [comment]
pinging @jlord - sounds like a bug?
