### ISSUE TITLE
learnyounode or javascripting

### ISSUE THREAD

**Issue by adityabtech** [nodeschool/discussions#1180]
Hi I am very much new to nodejs. just came to know what is nodejs and was trying to install two of the given features in tutorial page. javascripting and learnyounode using npm install command. after installing I have run the command javascripting I don't see anything.

FYI: I am using ubuntu 14.04 version on my dell laptop. Please suggest on what am I missing and how to see what is javascripting features does or learnyounode used for

**Comment by martinheidegger** [comment]
Just to make sure: Did you follow the [installation suggestions](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#ubuntudebian)?

**Comment by codingant007** [comment]
I face the same problem.Installation completed successfully using `npm install --global javascripting` but when I run `javascipting` in the terminal, nothing shows up.Cursor simply waits for the next command.

**Comment by codingant007** [comment]
Thank you 

`ln -s /usr/bin/nodejs /usr/bin/node`

This thing from the installation suggestions helped.

**Comment by SomeoneWeird** [comment]
Awesome :)
