### ISSUE TITLE
About #3 My first I/O! and the line numbers.

### ISSUE THREAD

**Issue by Lundelll** [nodeschool/discussions#1181]
So I'm new to the javascript and node scene and my question is that I got everything to work, but I had to look up the solution online because I got 1 row too many.

my code was: 
```javascript
var fs = require('fs');
var link = process.argv;
var buffer = fs.readFileSync(link[2]);
console.log(buffer.toString().split('\n').length );
```
The problem here was one too many, but if I wrote a text file containing:
```javascript
test1
test2
test3
```
so I used "node {myprogram}.js {testfile}.txt" and it prints 3
But when I used "learnyounode verify {myprogram}.js" I got one extra row. 
**Why do I have to add the - 1 to the length?**

**Same in My first async I/O**
code:
```javascript
var fs = require('fs');
var link = process.argv;
fs.readFile(link[2], function callback(err, data) {
  if(err) return console.error(err);
  var splitstring = data.toString().split('\n');
  console.log(splitstring.length - 1);
});
```

**Comment by bratanon** [comment]
Note sure if this helps, but in the problem.md file this note was stated.

> Note that the test file does not have a newline character ('\n') at the end of the last line, so using this  method you'll end up with an array that has one more element than the number of newlines.

**Comment by martinheidegger** [comment]
@Lundelll @bratanon The unclear similarity to `wc -l` has been noted in a recent [PR](https://github.com/workshopper/learnyounode/pull/237) I think we can close this?

**Comment by leeggco** [comment]
var fs = require('fs');
var file = process.argv;
var bf = fs.readFileSync(file[2]).toString();

console.log(bf.split('\n').length - 1);

It'is work.

**Comment by Atcold** [comment]
I think the absence of `\n` at the end of the test file is confusing...
Why would anyone finish their file without a new-line? (And I'm not talking about an empty line at the end of the file.)
