### ISSUE TITLE
Functional Javascript Exercise 2 - Can someone explain how this actually works?

### ISSUE THREAD

**Issue by GroundedSage** [nodeschool/discussions#1183]
``` JavaScript
 function repeat(operation, num) {
      if (num <= 0) return
      operation()
      return repeat(operation, --num)
    }
```

This makes absolutely no sense to me and I think it would be good practice to actually explain official solutions when they are so abstract..

**Comment by martinheidegger** [comment]
@CommonCreative This is a recursive function! Once you wrote your first recursive function it might be a little less abstract ;) Here is how the function works:

Example code:
```JavaScript
function foo() {
  console.log("hi")
}

repeat(foo, 2)
```

1. Calling `repeat(foo, 2)' (A)
2. num is 2 which is bigger than 0 so it will not directly return
3. Calles `foo` -> Output `hi`
4. Calling `repeat(foo, 1)` ( `--num` returns `1`) (B)
5. num is 1 which is bigger than 0 so it will not directly return
6. Calles `foo` -> Output `hi`
7. Calling `repeat(foo, 0)` (`--num` returns `0`) (C)
9. num is 0 which is smaller equal 0 so it will directly return 
10. finished calling (B): return
11. finished calling (A): return

Result: `foo` is called two times. An explanation might be good but I think it is nice for a tinkering brain to try to figure it out by one-selves (sorry for robbing you of that option :wink: ) 

Would you still prefer an explanation after reading this?

**Comment by CommonCreative** [comment]
Yea I had played a little with recursions. Only just getting used to dropping blocks and semi colons so that's where the confusion was. 

I now see that the code works like this 
 function repeat(operation, num) {
      if (num <= 0) { return }
      operation();
      return repeat(operation, --num);
    }

Thanks for that explanation!

**Comment by martinheidegger** [comment]
Oh! the missing braces :) Could you write an issue (or PR)  at async-you that lets people know that it should have braces in the the solution. 

PS.: can you close this issue?
