### ISSUE TITLE
Stream Adventure Concat Stream

### ISSUE THREAD

**Issue by neoms21** [nodeschool/discussions#1184]
I'm trying to run the official solution which is 
var concat = require('concat-stream');

```JavaScript
var result = '';
process.stdin
       .pipe(concat( function(buffer){
        process.stdout.write(buffer.toString().split('').reverse().join(''))
        process.stdout.write('\n')
    }))
```

but I can't get it working on console. Verify command passes fine but I can't see the reversed strings on console because the function inside concat never fires.  What would I need to make it fire when testing from console.

I've tried from MAC and windows both but same behaviour. Can someone please tell me what am I missing here ???

Thanks
MS

**Comment by gyaresu** [comment]
@neoms21 Are you talking about [stream-adventure > CONCAT](https://github.com/substack/stream-adventure/blob/master/problems/concat/problem.txt)?

Because the code you link above is not the same as the `solution.js`

**Comment by neoms21** [comment]
@gyaresu 

Yes I'm talking about the concat from stream adventure. I've tried with the official solution as well but the result is same.

var concat = require('concat-stream');
  
  process.stdin.pipe(concat(function (src) {
      var s = src.toString().split('').reverse().join('');
      console.log(s);
  }));

http://screencast.com/t/0dGCVq2jS6

I know I'm doing something wrong but I don't what!!!

**Comment by martinheidegger** [comment]
@neoms21 It seems you try to manipulate the stdin like this. I think you want to use `streamadventure run solution.js`

**Comment by neoms21** [comment]
@martinheidegger Thanks for that and yes that does work fine but my question is how do I supply input to 'stream.js' and get the output (reversed) locally like I can do with all other examples and they work fine?

**Comment by neoms21** [comment]
Found the way how it is to be done locally. phewww
