### ISSUE TITLE
exercise #9 - Juggling async

### ISSUE THREAD

**Issue by mesteves** [nodeschool/discussions#1187]
Hello,

I'm starting with angular and in ex#9 i'm having some troubles in undestanding the results (it doesn't verify with success):

![image](https://cloud.githubusercontent.com/assets/3369185/7857063/a1c1883a-0525-11e5-8336-44f1d420df42.png)

My code is the following:

// code
```js
var http = require('http');
var bl = require('bl')

var request1 = { url:process.argv[2] , response: null};
var request2 = { url:process.argv[3] , response: null};
var request3 = { url:process.argv[4] , response: null};

var requests = [request1, request2, request3];
var requestsDone = 0;

var onResponse = function (response)
{
	response.pipe(bl(function (err, data) 
	{
		if(!err)
		{
			/* console.log('=> ' +data.toString()) */

			requests[requestsDone].response = data.toString();
			
			//console.log('requests['+requestsDone+'].response = ' + requests[requestsDone].response);
				
			requestsDone++;
			
			if(requestsDone === 3)
			{
				PrintResponses(requests);
			}
		}
	}));
		
	//response.on("data", function (chuck) { console.log('\n=> ' + chuck); })	
	//response.on("error", function (e) { console.error('error'); })	
	response.on("end", function (data) 
	{ 
		//console.log('end ' + requestsDone); 
		
	})	
}

function ProcessRequest (request)
{			
	http.get(request.url, onResponse);	
}

var PrintResponse = function (request)
{
	console.log(request.response);
}

var PrintResponses = function (requests)
{
	//console.dir(requests);
	requests.forEach(PrintResponse);
}

requests.forEach(function(req)
{
	//console.log('\n [' + requestsDone + '] Request for url => ' + req.url);
	ProcessRequest(req);
	//console.log(' [' + requestsDone + '] Responded with => ' + req.response);
});
```

Thanks in advance,

Manuel

**Comment by marocchino** [comment]
```js
requests[requestsDone].response = data.toString();
requestsDone++;
```

This code means faster response comes first.
You should input your response in request order.

**Comment by mesteves** [comment]
Hi marocchino,

Thanks for your reply, it makes sense what you are saying, but....isn't the code similar to the one that is  provided as the solved exercise?

It's the similarities that are leaving me confused... 


```js
results[index] = data.toString()
count++
```

this code as well as the one that i've provided also run's at the response.pipe level...

What am i missing ? 

Thanks,

**Comment by mesteves** [comment]
Marocchino,

After taking a closer look, i see the point. I can't control the index position in the array with the count of processes requests.  

Closing this Issue.

Thank you! :+1: 
Manuel

**Comment by marocchino** [comment]
Maybe [this link](http://stackoverflow.com/questions/7053965/when-using-callbacks-inside-a-loop-in-javascript-is-there-any-way-to-save-a-var) can help you.

**Comment by marocchino** [comment]
Oops, too late! :+1:

**Comment by mesteves** [comment]
Thanks once again ;)
