### ISSUE TITLE
async-you map localhost:3131/one ECONNRESET

### ISSUE THREAD

**Issue by huntonas** [nodeschool/discussions#1188]
I keep getting an error on the first parameter url: [Error: socket hand up] code: 'ECONNRESET'.
The second parameter works fine. I thought that it might be hitting the server before it had started, but after setting a timeout, I realized that is not the case. I manually replaced the first parameter with the second url, and I got 'two greater than one' for both values in the array, but I have no idea why it is breaking on the first parameter. Any ideas?

my code:

``` javascript
var http = require('http'),
    async = require('async');


async.map([process.argv[2], process.argv[3]], function (item, done) {
    var body = '';
    console.log(item + '\n');
    var req = http.get(item, function (res) {
        res.on('data', function (chunk) {
            body += chunk.toString();
        });
        res.on('end', function () {
            return done(null, body);
        });
    }).on('error', function (err) {
        console.log(err);
        return done(null, err);
        //return done();
    });
    req.write(item);
    req.end();
}, function (err, results) {
    if (err) return console.log(err);
    console.log(results);
});
```

**Comment by martinheidegger** [comment]
This seems to be a connection issue. Can you check that:

- restarted your computer
- you disable any proxy in your internet settings
- you are connected to the internet

Maybe one of these things is blocking the system?

**Comment by huntonas** [comment]
I thought all of those too. It is only with the first url though. I can hit
the /two with no issues. It might be a proxy issue which I will look at
tomorrow, but I would think that if that was the case, I wouldn't be able
to hit either url.
