### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by bernardodesousa** [nodeschool/discussions#1191]
Hey!

I get "The system cannot find the path specified." on Windows 8.1 for both "scope-chains-closures" and "sccjs". Any help is much appreciated.

**Comment by marocchino** [comment]
Is it same issue with #1189 ?

**Comment by jesstelford** [comment]
@marocchino is right: It's the same issue as #1189.
@SomeoneWeird's PR has fixed the issue, and it is now published in **v1.0.3**.

To update: `npm install -g scope-chains-closures`
