### ISSUE TITLE
#6 MAKE IT MODULAR

### ISSUE THREAD

**Issue by prkstaff** [nodeschool/discussions#1192]
Im having Submission results match expected, but dont know why: 
Your additional module file [module_to_import.js] does not export a single function. You must use the module.exports = function () {} pattern.

import.js

```javascript
var loaded_module = require('./to_import.js');

path = process.argv[2];
file_extension = process.argv[3];
loaded_module.list_file_with_extension(path, file_extension, function(err,list){
   if(!err) {
      console.log(list);
   }else{
      console.error(err);
   }
});
```
to_import.js

```javascript
var fs = require('fs');

function list_file_with_extension(path, ext, callback){
    list_of_files_in_dir = fs.readdir(path,function(err, dir_list){
        if(err){
            callback(err)
        }else{
            for(var i = 0;i<dir_list.length;i++){
                loop_file = dir_list[i];
                if(loop_file.split('.')[1] === ext){
                    callback(null,loop_file)
                }
            }
        }

    });
}
module.exports.list_file_with_extension = list_file_with_extension;
```
cant figure what i'm doing wrong.

**Comment by prkstaff** [comment]
Im having Submission results match expected, but dont know why: 
Your additional module file [module_to_import.js] does not export a single function. You must use the `module.exports = function () {}` pattern.

import.js 

var loaded_module = require('./module_to_import.js');

path = process.argv[2];
file_extension = process.argv[3];
loaded_module.list_file_with_extension(path, file_extension, function(err,list){
    if(!err) {
        console.log(list);
    }else{
        console.error(err);
    }
});

to_import.js

var loaded_module = require('./module_to_import.js');

path = process.argv[2];
file_extension = process.argv[3];
loaded_module.list_file_with_extension(path, file_extension, function(err,list){
    if(!err) {
        console.log(list);
    }else{
        console.error(err);
    }
});

**Comment by marocchino** [comment]
Do `module.exports = list_file_with_extension` instead of `module.exports.list_file_with_extension = list_file_with_extension`.
And you can use it with `var list_file_with_extension = require('./to_import.js');`.

**Comment by prkstaff** [comment]
Thank you, i also changed:
loaded_module.list_file_with_extension(
 to 
loaded_module(

full code working:

```javascript

var loaded_module = require('./module_to_import.js');

path = process.argv[2];
file_extension = process.argv[3];
loaded_module(path, file_extension, function(err,list){
    if(!err) {
        for(item in list){
            console.log(list[item]);
        }
    }else{
        console.error(err);
    }
});

```

```javascript

var fs = require('fs');

function list_file_with_extension(path, ext, callback){
    list_of_files_in_dir = fs.readdir(path,function(err, dir_list){
        if(err){
            callback(err)
        }else{
            list = [];
            for(var i = 0;i<dir_list.length;i++){
                loop_file = dir_list[i];
                if(loop_file.split('.')[1] === ext){
                    list.push(loop_file);
                }
            }
            callback(null,list);
        }

    });
}
module.exports = list_file_with_extension;

```

**Comment by SomeoneWeird** [comment]
Awesome!
