### ISSUE TITLE
scope-chains-closures workshop doesn't work on Windows

### ISSUE THREAD

**Issue by varungupta85** [nodeschool/discussions#1193]
This is the console output after installation and run

C:\Users\vagupta\nodeschool>npm install -g scope-chains-closures
C:\Users\vagupta\AppData\Roaming\npm\scope-chains-closures -> C:\Users\vagupta\AppData\Roaming\npm\node_modules\scope-chains-closures\runner.js
C:\Users\vagupta\AppData\Roaming\npm\sccjs -> C:\Users\vagupta\AppData\Roaming\npm\node_modules\scope-chains-closures\runner.js
scope-chains-closures@1.0.2 C:\Users\vagupta\AppData\Roaming\npm\node_modules\scope-chains-closures
├── estraverse@4.1.0
├── escope@1.0.3 (estraverse@2.0.0)
├── msee@0.1.1 (marked@0.3.3, chalk@0.4.0, nopt@2.1.2, xtend@2.1.2, cardinal@0.4.4)
├── adventure@2.10.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, mkdirp@0.5.1, split@0.3.3, through2@0.5.1, terminal-menu@2.1.1)
├── adventure-verify@2.2.0 (tap-parser@0.5.0, tap-colorize@1.2.0, tape@2.14.0)
└── babel-core@5.4.7 (fs-readdir-recursive@0.1.2, shebang-regex@1.0.0, trim-right@1.0.0, slash@1.0.0, leven@1.0.2, private@0.1.6, to-fast-properties@1.0.1, path-is-absolute@1.0.0,
strip-json-comments@1.0.2, globals@6.4.1, esquery@0.4.0, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.0, ast-types@0.7.6, home-or-tmp@1.0.0, bluebird@2.9.27, line-numbers
@0.2.0, resolve@1.1.6, debug@2.2.0, output-file-sync@1.1.0, detect-indent@3.0.1, chalk@1.0.0, repeating@1.1.3, source-map@0.4.2, is-integer@1.0.4, source-map-support@0.2.10, minima
tch@2.0.8, acorn-jsx@1.0.1, lodash@3.9.3, regexpu@1.1.2, core-js@0.9.13, regenerator@0.8.27)

C:\Users\vagupta\nodeschool>scope-chains-closures
**'/bin/sh' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by varungupta85** [comment]
I was able to get this to run after changing the scope-chains-closures, scope-chains-closures.cmd and runner.js according to the learnyounode module. Basically point to node.exe instead of /bin/sh.

**Comment by SomeoneWeird** [comment]
Yep. I've submitted a PR for this [here](https://github.com/jesstelford/scope-chains-closures/pull/4).

**Comment by jesstelford** [comment]
@SomeoneWeird's PR has fixed the issue, and it is now published in **v1.0.3**.

To update: `npm install -g scope-chains-closures`
