### ISSUE TITLE
Javascripting Introduction (making a command prompt for windows)

### ISSUE THREAD

**Issue by charle5adam5** [nodeschool/discussions#1194]
Hi guys! I'm very new to using Node.js and cant seem to figure out how to get started. I'm trying to make the introduction.js file like this: 
    C:\users\owner\javascripting>type NUL>introduction.js
But whenever I type that in and hit Enter nothing happens. What should I do? And thank you in advance!

**Comment by martinheidegger** [comment]
Did you use the "Node Command Prompt" as suggested [here](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#windows)?

**Comment by clsatw** [comment]
thank guys. it is working now after adding required paths into windows environment.

**Comment by dominhhai** [comment]
:+1:
