### ISSUE TITLE
Solution to HTTP JSON API SERVER weird if check

### ISSUE THREAD

**Issue by n0f3** [nodeschool/discussions#1196]
Hello, I was just reading through the solution that was provided for the HTTP JSON API SERVER challenge, and I'm a little bit at a loss to what the following construct does and what it represents:

if (/^\/api\/parsetime/.test(req.url))

Anyone knows that /^ / creates?

**Comment by SomeoneWeird** [comment]
Did you figure this out?

**Comment by n0f3** [comment]
Hi Adam yes I got some help on the node irc channel and it seems as is a regex object being used there so I'm going to study up on that tomorrow! What are the benefits of doing that vs a switch case? (is what I've done in my own solution)

Thanks! 



—
