### ISSUE TITLE
Make it modular: passing error on its callback.

### ISSUE THREAD

**Issue by TH3Mjuss** [nodeschool/discussions#1197]
Hi,

I don't understand what I did wrong in the "Make it modular" exercise since I list the files well using a module but when I launch the `verify` command, I get the following error: 
`✗ Your additional module file [listFilesByExtArgs.js] returned an error on its callback:
	[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]`

Please tell me if you need my code, I'm not sure I can post it here.

Here is my code:
**function.js:**

```javascript
var fs = require('fs');
var path = require('path');

function getFilesByExtArgs (dir, ext, callback) {
    fs.readdir(dir, function (err, data) {
            if (err) {
                return callback(err);
            }
            var results = [];
            for (var i = 0; i < data.length; i++) {
                if (path.extname(data[i]) == ('.' + ext)) {
                    results.push(data[i]);
                }
            }
            callback(results);
        });
}

module.exports = getFilesByExtArgs;
```

**module.js:**

```javascript
var myModule = require('./listFilesByExtArgs');

myModule(process.argv[2], process.argv[3], function(results){
        if (results instanceof Error)
            console.log("An error occured !");
        for (var i = 0; i < results.length; i++) {
            console.log(results[i]);
        }
});
```

**Comment by martinheidegger** [comment]
Code would always be better but I think this works without: There is a code-convention in node.js that says that `callback` will have two arguments. The first one being an error object, the second the value. If no error occurred, then error will be null.

So probably you have in your code somewhere something like:

```JavaScript
callback(array);
```

and it should really be

```JavaScript
callback(null, array);
```

**Comment by TH3Mjuss** [comment]
@martinheidegger I edited my post with my code. I don't understand how I should edit my code. If I update my callback function to be like 
````javascript
callback(null, array);
``` 
my code doesn't work anymore..

**Comment by marocchino** [comment]
I think, your codes work correctly. but, Our validator treats first argument as error. 
`callback(err, result)` is more common pattern in node.js world.

This thins is also described in exercise 

> The callback function must be called using the idiomatic node(err, data) convention. This convention stipulates that unless there's an error, the first argument passed to the callback will be null, and the second will be your data.

**Comment by marocchino** [comment]
oh, You should change `module.js` part, too.

**Comment by martinheidegger** [comment]
@TH3Mjuss @marocchino is spot on: When you change the signature of the callback you also need to change the callback listener. If you are still struggling, could you provide the code?

**Comment by navkmurthy** [comment]
//program-module-test.js
var myModule = require('./program6-module.js');

myModule(process.argv[2], process.argv[3], function(err,results){
        if (err) {
        console.log(err);
        return;
    }
           
        for (var i = 0; i < results.length; i++) {
            console.log(results[i]);
        }
});

**Comment by navkmurthy** [comment]
//program6-module.js
var fs = require('fs');
var path = require('path');

function getFilesByExtArgs (dir, ext, callback) {
    fs.readdir(dir, function (err, data) {
            if (err) {
                return callback(err);
            }
            var results = [];
            for (var i = 0; i < data.length; i++) {
                if (path.extname(data[i]) == ('.' + ext)) {
                    results.push(data[i]);
                }
            }
            callback(null,results);
        });
}

module.exports = getFilesByExtArgs;

**Comment by TH3Mjuss** [comment]
Thanks for your help, I fixed my code and now I understand well how callbacks are used !
