### ISSUE TITLE
JUGGLING ASYNC Problem

### ISSUE THREAD

**Issue by HellBlazzar** [nodeschool/discussions#1199]
Hello everyone , I'm a new comer of nodejs.I have some problems when I do JUGGLING ASYNC in nodeschool.

Here is my code:
```
var http = require('http');
var URL_stack = [process.argv[2] , process.argv[3] , process.argv[4]];

process.nextTick(function(){
    
	var _callee = arguments.callee;
    var URL = URL_stack.shift();

	http.get(URL , function(response) {

	    var result = [];
	    response.setEncoding('utf8');
	    
	    response.on('data' , function(data) {
		    result.push(data);
	    });
	
    	response.on('error' , function(error) {
		    console.log(error);
	    });
	
	    response.on('end',function() {
		    console.log(result.join(""));
		});
		
		if(URL_stack.length > 0){
		    process.nextTick(_callee);
		}
    });
});

```

When I use ```learnyounode verify``` to check my answer, sometimes it will passed,but sometime it will failed.I really hope someone can tell me what's my fault,thanks.

**Comment by davecocoa** [comment]
You're calling `process.nextTick(_callee);` as soon as a `response` object is ready, but really you should wait until that response object has fully finished loading, which corresponds to the `end` event.

Also, while your solution is fine, you might find it interesting to try and write a solution which begins all three requests immediately, and then collects the results and prints them once all three are ready.

**Comment by HellBlazzar** [comment]
Thank you davecocoa.Now I know what's problem with my code,I'll try to fix it.

But, my solution and your suggestion(just like the solution the learnyounode gave), which one will run more faster? Or their execution time are close to each other,I don't have to care about that?

**Comment by davecocoa** [comment]
I would expect the solution from `learnyounode` to run faster for most cases. When all the requests are started at the same time, the total run time is equal to the time of the slowest request, if each request starts when the previous request finishes, the total run time is equal to the sum of all the request run times.

For example, if the requests take 300, 500 and 200 milliseconds, the `learnyounode` solution will take approximately 500 milliseconds to complete, but your solution would take approximately 1000 milliseconds to complete.

**Comment by HellBlazzar** [comment]
Thank you,davecocoa.I got it.

And I fix my bug by moving if statement into end event:

```
	    response.on('end',function() {
		    console.log(result.join(""));
			if(URL_stack.length > 0){
		        process.nextTick(_callee);
		    }
		});

```

Then I take your suggestion,write new answer to this question:

```
var http = require('http');
var Results = {};
var URL_stack = [process.argv[2],process.argv[3],process.argv[4]];
var Finish = {};

function URL_caller() {
	URL_stack.forEach(function(single_URL , index , all_URLs) {
		HTTP_Getter(single_URL , index);
		Results['Result' + index] = "";
		Finish['Finish' + index] = false;
	});
}

function Results_checker() {
    for(var finished_or_not in Finish){
		if(Finish[finished_or_not] == false){
			return false;
		}
	}
	return true;
}

function HTTP_Getter(URL , index){
	http.get(URL , function(response) {
	    var result = [];
	    response.setEncoding('utf8');
	    
	    response.on('data' , function(data) {
		    result.push(data);
	    });
	
    	response.on('error' , function(error) {
		    console.error(error);
	    });
	
	    response.on('end',function() {
			Results['Result' + index] = result.join("");
			Finish['Finish' + index] = true;
		});
	});
}


URL_caller();

var Interval = setInterval(function() {
	if(Results_checker() == true){
		for(var result in Results){
			console.log(Results[result]);
		}
		clearInterval(Interval);
	}
},1000);

```

I'm very appreciate your suggestion.

**Comment by davecocoa** [comment]
That's brilliant! Well done! :confetti_ball: :tada: :clap: 

If you're happy with your solution, you can close this issue using the button at the bottom of this page. Good job!

**Comment by SomeoneWeird** [comment]
Weeee!
