### ISSUE TITLE
HTTP File server (Ex.11 of 13 on learnyounode): verify error

### ISSUE THREAD

**Issue by herbbetz** [nodeschool/discussions#1201]
The following code works in my browser (firefox 38.0.5 on win8.1) but not in learnyounodes verify, where there is a never ending batchtest trying to connect to strange ports:
"? Error connecting to http://localhost:2678: connect ENCONNREFUSED"
Unluckily I don't know, how to get the proper solution out of learnyounode, when my code is not verified.
My code:

```JavaScript
var http = require('http');
var fs = require('fs');

var server = http.createServer(function(req,res){
	try{
		var fp = fs.createReadStream(process.argv[2]); 
		fp.pipe(res);
	}catch(er){
		console.log(er.message);
	}
});
server.listen(8000);
```

**Comment by davecocoa** [comment]
I would recommend taking a closer look at the error, and also at the exercise instructions. Notice that the error occurs when connecting to "localhost:**2678**". Which port is your program listening on?

```
Your server should listen on the port provided by the first argument to your program.
```

**Comment by herbbetz** [comment]
Oh, sorry, I completely overread this ... The verify worked ... Thanks a lot for the fast answer ...
