### ISSUE TITLE
NodeJs and Ldap

### ISSUE THREAD

**Issue by aHumanBeing** [nodeschool/discussions#1202]
Not sure if this is the right place to ask.  I'm writing a web app that requires login via ldap.  Additionally, the forms will have links / buttons which should be visible / accessible via user permissions in ldap.  Which module should I use to implement this?  Thanks

**Comment by martinheidegger** [comment]
When I researched this topic [ldapjs](https://www.npmjs.com/package/ldapjs) has been the best choice. Did you try it?

**Comment by aHumanBeing** [comment]
Hey thanks! I'll definitely give this a try and report my findings here for all to see.

**Comment by aHumanBeing** [comment]
Hello again.  I was able to implement this using the passport-ldapauth module.  

https://www.npmjs.com/package/passport-ldapauth.  I'm not sure how detailed my response should be at this point so if there's anything I may add please let me know.
