### ISSUE TITLE
LeranyouNode ex.7 error (http GET request)

### ISSUE THREAD

**Issue by TH3Mjuss** [nodeschool/discussions#1203]
Hi, 
When I try to display the content of the page given as the first argument of my program, I get the following error: `getaddrinfo ENOTFOUND http://localhost:53920`. I also tried to open www.google.com which worked well.

What can I do to solve that since I guess it comes from learnyounode it self ?

**Edit:**
I think there's a problem in my code too since it shows me some buffer instead of raw text.

Here's my code:
```javascript
var http = require('http');

function httpGet() {
    var options = {
        host: process.argv[2],
        port: 80,
    };
    //console.log(process.argv[2]);
    http.get(options, function(res) {
            //console.log("Got response: " + res.statusCode);

            res.on("data", function(chunk) {
                    console.log(chunk);
                });
        }).on('error', function(e) {
                console.log("Got error: " + e.message);
            });
}
httpGet();
```

***Edit 2:***
Buffer problem solved by adding ```res.setEncoding('utf8');```before ```res.on("data", function(chunk) {```. But I still can't verify my code.

**Comment by martinheidegger** [comment]
The first argument of the program (the url) is only available during the "run" of the exercise. It will be closed soon. Maybe you havn't heard that Node.js offers a way to access url requests? https://nodejs.org/api/http.html#http_http_get_options_callback

**Comment by TH3Mjuss** [comment]
I tried again to launch my program with `learnyounode run myprogram.js` instead of `learnyounode verify myprogramg.js` and I got the same problem..

**Comment by martinheidegger** [comment]
@TH3Mjuss I fear I didn't explain it well:

The confirmation process of `verify` and `run` creates a server that offers a file at a localhost port (`http://localhost:53920` in your case). At the time when `run` or `verify` is finished this server will also be automatically shut down so its only possible to access the server for the very short period between starting learnyounode  and when it closes. The point of the exercise though is not to load the file with your browser the point of the exercise is that you use a script to load a file from a browser. This you can do using the `http.get` method that I linked above. Did you try that?

**Comment by TH3Mjuss** [comment]
I tried to use commands run then verify, but it didn't started the server.. I always get the same error.
Concerning the code, I tried to use `http.get` and make my own `httpGet()` function but both didn't worked.

**Comment by SomeoneWeird** [comment]
Can you paste the code you have?

**Comment by TH3Mjuss** [comment]
@SomeoneWeird , Here is my code:

```javascript
var http = require('http');

function httpGet() {
    var options = {
        host: process.argv[2],
        port: 80,
    };
    //console.log(process.argv[2]);
    http.get(options, function(res) {
            //console.log("Got response: " + res.statusCode);

            res.on("data", function(chunk) {
                    console.log(chunk);
                });
        }).on('error', function(e) {
                console.log("Got error: " + e.message);
            });
}

httpGet();```

**Comment by TH3Mjuss** [comment]
@martinheidegger @SomeoneWeird Any ideas on how I can solve my issue ?

**Comment by TH3Mjuss** [comment]
I finally found what was wrong and it came from my code. My code was a mix between ```http.request()``` and ```http.get()```and the problem came from the ```option``` object which isn't useful in that case. 
Here's a simple code that works well:
```javascript
var http = require('http');

function httpGet() {
    http.get(process.argv[2], function(res) {
            res.setEncoding('utf8');
            res.on("data", function(data) {
                    console.log(data);
                });
        }).on('error', function(e) {
                console.log(e.message);
            });
}

httpGet();
```
