### ISSUE TITLE
JUGGLING ASYNC - A solution similar to the official solution keeps failing - please point out the bug

### ISSUE THREAD

**Issue by ngochoan1011** [nodeschool/discussions#1204]
This is my first answer to the problem, and I think it is almost the same with the official solution, but I don't know why it keeps failing. Hope someone could help me point out the bug, thanks a lot:

```JavaScript
var http = require('http');
var bl = require('bl');
var content = [];
var counter = 3;

for (var i = 0; i < 3; i++ ) {
	http.get(process.argv[i + 2], function(response) {
		response.pipe(bl(function (err, data) {
			if (err) throw err;

			content[i] = data.toString();
			counter --;
			if (counter === 0) {
				console.log(content[0]);
				console.log(content[1]);
				console.log(content[2]);
			}
		}));
	});	
}

```

Reference: https://github.com/nodeschool/discussions/issues/203

**Comment by martinheidegger** [comment]
Hello @ngochoan1011, thank you for taking the time to repost it.

You seem to have forgot to account for the asynchronicity. At the time when you call `http.get` then `i` is correctly `0`, `1` or `2` but then some time happens and when the response arrives `i` has been set to `2` so `content[i]  = data.toString()` all writes into `content[2]`. Does that help?

**Comment by ngochoan1011** [comment]
Thanks a lot @martinheidegger for your response.

I guess the problem is as you described. However, the output I got for content[i] are all "undefined" which I cannot understand.
![screen shot 2015-06-08 at 9 30 26 am](https://cloud.githubusercontent.com/assets/3677211/8027386/7d1eb2b0-0dc1-11e5-9561-c5df80fdfcb3.png)

If we accept your explanation then content[i] should have some values (same values). Or am I missing somethings here?

**Comment by dominhhai** [comment]
@ngochoan1011 Can you show your code?

**Comment by marocchino** [comment]
You can do `console.log(content);` for look inside of the content.

BTW, you should not use `i` inside of callback. it will called after `for` statement is over.
so your content will be `[undefined, undefined, undefined, "something"]` for now.

**Comment by martinheidegger** [comment]
@ngochoan1011 Hah, in my pride I forgot to count to 3 (quite literally). The for loop is having the condition `i<3` which means that `i` is not `2` but `3` when the for loop stops.

**Comment by ngochoan1011** [comment]
Thanks a lot @marocchino and @martinheidegger. I totally see the problem right now :+1:

**Comment by lutepluto** [comment]
I think wrapping the loop body in a closure would fix the problem you guys came up with.

```javascript 
for (var i = 0; i < 3; i++ ) {
    (function(index) {
        http.get(process.argv[index + 2], function(response) {
            response.pipe(bl(function (err, data) {
                if (err) throw err;

                content[index] = data.toString();
                counter --;
                if (counter === 0) {
                    console.log(content[0]);
                    console.log(content[1]);
                    console.log(content[2]);
                }
            }));
        });
    })(i); 
}
```

**Comment by fabichoi** [comment]
@lutepluto Thanks for your code. but I have a question.
What is the mean (i) in your code at the last part of loop statement?
I tested except that (i), result wasn't right.

**Comment by lutepluto** [comment]
@fabichoi This is so called Immediately-Invoke-Function-Expression(IIFE). Add (i) at the end makes i passed in the anonymous function and executes the function immediately. Because of the asynchronous fact of http.get, when the time http.get really get executed, the loop has iterated the i variable to the value 3, not 0, 1, 2 in the loop. So here comes IIFE to rescue this kind of situation. which let i be the correct value when http.get executes asynchronously because we pass i into the anonymous function. Hope I explain this clearly :)

**Comment by fabichoi** [comment]
@lutepluto thanks for your comment! I finally understand now.
