### ISSUE TITLE
Trying to install 'javascripting' but get Administrator/Root error

### ISSUE THREAD

**Issue by lavert** [nodeschool/discussions#1205]
Hello,
I've installed node.js, ran the command in terminal (I'm using a mac) 'node' and get the < symbol. However, when I enter in terminal the command to install 'javascripting' ( npm install -g javascripting ), I get an error saying: please try running this command again as root/administrator .

I am logged in as administrator though. I've attached a photo of my terminal screen with the commands/errors.
![screen shot 2015-06-05 at 10 24 10 am](https://cloud.githubusercontent.com/assets/12758461/8011370/105e9c68-0b6d-11e5-9d80-cefac3402dd9.png)

I'm not very good with terminal, but I'm trying to learn more about it so I can figure these out myself. Any advice?

**Comment by martinheidegger** [comment]
Hello @lavert Thanks for trying NodeSchool!

Did you try installing using `sudo npm install -g javascript` ? There are some security issues with mac and the default installation (We wrote together something here: https://github.com/nodeschool/discussions/wiki/Installation-suggestions#mac)

**Comment by lavert** [comment]
Hello Martin and thank you for your help. I tried the command you gave, " sudo nom install -g javascript ", then when I typed the workshopper name " javascripting " nothing happened. 

I also read your link, about using Homebrew to install this, but from what I understand I would have to uninstall node.js and then install Homebrew and then have that install node.js again/fresh..? My issue is I can not find the commands to uninstall node.js? I find it frustrating that a beginner course on this would require such knowledge of ssh commands to manage, it simply does not make sense to me. I've tried to find resources on how to use ssh but they are very few and difficult to find, much less find commands that actually work.

So now I believe that I have either node.js or a partial install of node.js on my computer, neither of which allows me to begin the tutorial " javascripting ", and since I can't find how to uninstall node.js I can not install Homebrew.

This is quite frustrating.

**Comment by b-a-chua** [comment]
Hi lavert, your question was from 21 days ago, so I hope that it's already been resolved.  

Could you make sure that you typed "sudo npm install -g javascript" instead of "sudo nom install -g javascript"  (pls. take note that it's letter p, not letter o).
