### ISSUE TITLE
Learnyounode - Time Server Task - problem

### ISSUE THREAD

**Issue by PPolczynski** [nodeschool/discussions#1206]
Hello !
I recently started learning JS and Node.js with your Tutorials.
I encountered problem with Time Server task:
I wrote a code that 50% of time turns out to be correct. My knowledge of JS  is not sufficient to solve or even comprehend why this is happening. Since i store my nodejs journey on github here is a link to the repo and folder containing the code that generates the problem.  https://github.com/PPolczynski/NodeJSLearning/tree/master/learnyounode/010_TimeServer
screenshot of output:
![timeserver](https://cloud.githubusercontent.com/assets/12174645/8025738/327fe964-0d61-11e5-9116-086b83dc1654.png)

Please let me know if this is issue with code i wrote and if so any way of improving it :)
Thank you for awesome tutorial and challenge!

**Comment by marocchino** [comment]
Hi, I looks just omit newline in your code.

> For each connection you must write the current date & 24 hour time in the format:
> "YYYY-MM-DD hh:mm"
> followed by a newline character.

**Comment by marocchino** [comment]
> I wrote a code that 50% of time turns out to be correct. 

This thing looks like a bug of workshopper.

**Comment by martinheidegger** [comment]
Agreed, maybe has to do with ubuntu?

**Comment by marocchino** [comment]
@martinheidegger  I reproduce this in osx. (\w node v2.2.1)

**Comment by PPolczynski** [comment]
Thank you for ur feedback ! I will correct my code . It's embarrassing but honestly i liked the task bit too much which might have result in less patient reading :) 
Hopefully my mistake will help you in finding and patching of this bug. 
I see you ware able to reproduce it, but if you 'd be in need of any specs or additional info let me know.
