### ISSUE TITLE
Getting an error on Challenge #6: 

### ISSUE THREAD

**Issue by josiahdavis** [nodeschool/discussions#1207]
Hey folks - I've been spinning my wheels on the 6th challenge of *Learn You Node*

> Create a program that prints a list of files in a given directory, filtered by the extension of the files. The first argument is the directory name and the second argument is the extension filter. Print the list of files (one file per line) to the console. You must use asynchronous I/O.... You must write a module file to do most of the work.

Can't quite seem to wrap my head around it. What I'm doing makes logical sense to me, and I'm pretty much clueless about what I'm doing wrong. Any help is appreciated! Thanks!

*program.js*

```javascript
var mymodule = require('./myModule.js');
mymodule(process.argv[2], process.argv[3]);
```

*myModule.js*

```javascript
var fs = require('fs')
var path = require('path') 

module.exports = fs.readdir(fileLocation, ext, function (err, list) {
                      list.forEach(function (file) {
                        if (path.extname(file) == '.' + ext)
                           console.log(file);
                        })
                    })
```

**Comment by martinheidegger** [comment]
`make it modular` has been a big challenge for many people. But if you follow the description to the dot it is possible to do it by yourself. In any case here two hints:

```JavaScript
module.exports = "Hello world"
```
means that any value passed in through this will later be available outside of this module with `require('./myModule.js') == "Hello world"`. Your task is to offer a function to the outside so you need to write something like this:

```JavaScript
module.exports = function (fileLocation, ext, callback) {
  //.. 
}
```

Another hint is that you have written `console.log` inside of `myModule`. The goal is that only `program.js` uses `console.log`

Maybe these two hints will bring you a few steps further. Can you try it and let us know if it helped you?

**Comment by Shawful** [comment]
I'm having a similar issue, but my problem lies in knowing where exactly to define my callback function and how to have the callback function accept possibly one or two arguments.

**Comment by Shawful** [comment]
figured it out by looking at the solution, but I must say that after reading and re-reading the documentation provided when I typed "learnyounode" to start the lesson could absolutely be improved to be more like the previous exercises, which did not need guesswork.

**Comment by josiahdavis** [comment]
Thanks for the feedback Shawn, what you said was helpful. I resonate with my fellow student's feedback. Up to this point I have been able to complete the exercises, and have found the pace to be quite good. 

I found this particular exercise to be 1-2 orders of magnitude more difficult than the previous exercises and I was only able to complete it after reading the solution. I think the most confusing part to me, was all of the nested functions. I get the point of "Make it Modular", I think, but I wonder if there is a way to provide more guidance on the structure of the nested functions or start with an easier example. For me, it kind of warps my mind to think about nesting a function, within a function, within a function, and then exporting the function, and then passing a function within a function to the exported function, etc.... Perhaps it's possible to make it so that the first modular exercise is easier, with less function nesting, and then you build up to that in a later challenge? 

All this to say, I have really enjoyed all of the tutorials up to this point, and I am definitely planning to continue working through them. I am learning a lot! Thanks again for all your help!

**Comment by martinheidegger** [comment]
@Shawful NodeSchool and the tutorials you find on the site are a result of community effort. If you feel they are insufficient it would be very awesome if you could work on a improvement. learnyounode is opensource!

**Comment by Jwan622** [comment]
Can someone post a solution?

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
