### ISSUE TITLE
Help to understand my error in Challenge #2

### ISSUE THREAD

**Issue by Forsskieken** [nodeschool/discussions#1210]
This is my code.
var index
var sum = 0
console.log(process.argv);
for	(index = 2; index < process.argv.length; index++) {
    sum += Number(process.argv[index]);
}
console.log(sum)

but when I try it I get error, although node program.js 1 2 3 4 give me a output of 10

**Comment by dominhhai** [comment]
Did you get error with the `run` or `verify` command?

**Comment by singhal451** [comment]
run your for loop <= instead of <

**Comment by dominhhai** [comment]
@singhal451  `<=` will be made the `out of bound` error for the last loop.

**Comment by singhal451** [comment]
var x= process.argv.length
var s=0;
for(var i=2;i<x;i++)
s+=Number(process.argv[i]);
console.log(s);

**Comment by hokennethk** [comment]
@Forsskieken the test only expects certain items to be logged to the console. When you run verify, you can see what the test expects the output will be. Compare that output to the Actual column. In your code, you'll see that you are logging more things to the console than required.

**Comment by Forsskieken** [comment]
Hi Thanks for answering all,

I noticed the difference between my solution and the one offered by
singhal451.
The only problem is that I got a different result for run the code and
verify the code.
In run I got the correct result and therefore I'm not convinced that my
solution was wrong.
Why was/is there a difference between run and verify?

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
