### ISSUE TITLE
Error with MAKE IT MODULAR:can't return array with the correct number of elements.

### ISSUE THREAD

**Issue by fishzhe** [nodeschool/discussions#1213]
Hi, folks, I'm learning the 6th challenge of Learn You Node. Got an error said: 
![capture](https://cloud.githubusercontent.com/assets/5561117/8099047/7ef3ae50-0fac-11e5-9704-d045b5633f19.PNG)

Here's mymodule.js:
```
module.exports=function (dirname, ext, callback){
	var fs = require('fs');
	var path = require('path');
	fs.readdir(dirname, function read(err, list){
		if(err)
			return callback(err);
		var data = [];
		for(var i=0; i<list.length; i++){
			if(path.extname(list[i])==ext)
				data.push(list[i]);
		}	
		callback(null, data);
	});
};
```

and program.js:
```
var mymodule = require('./mymodule');
mymodule(process.argv[2], "."+process.argv[3], function read(err, list){
	for(var i = 0; i<list.length; i++){ 
		console.log(list[i]);
	}	
});
```
Any help is appreciated! Thanks!

**Comment by davecocoa** [comment]
Ah, the verification output in this case really isn't helpful, I'm sorry for the confusion. The exercise wants you to pass `process.argv[2]` and `process.argv[3]` directly into your module, with no changes whatsoever. In this way, it will be your module's responsibility to add the `"."` to `process.argv[3]`. You basically already have the correct answer at this stage, the verification is just not very clear.

**Comment by fishzhe** [comment]
@davecocoa Thank you so much! You saved my day friends! It almost drive me crazy.
