### ISSUE TITLE
Javascripting verify error Command failed

### ISSUE THREAD

**Issue by mscanferlato** [nodeschool/discussions#1217]
Hello .
I started trying to learn javascript with javascripting 
On the first pass I replaced the file name from introduction.js to prova.js.
When i type javascripting verify introduction.js  I get the error below. 
How do you solve ?
![javascripting_error](https://cloud.githubusercontent.com/assets/12863069/8134384/20ea097e-112f-11e5-9df0-11e8b73999b1.jpg)

**Comment by SomeoneWeird** [comment]
The windows terminal can sometimes look like it's displaying `(` and `)` as `<` and `>` which is what has happened in your case. If you change `<>` to `()` it should work :)

**Comment by mscanferlato** [comment]
just like that, thanks.

**Comment by SomeoneWeird** [comment]
:tada:
