### ISSUE TITLE
node-oracledb installation

### ISSUE THREAD

**Issue by stevrubills** [nodeschool/discussions#1218]
I have oracle 11g xe in my system
installed oracle instant client and 
OCI_LIB_DIR
OCI_INC_DIR
has been set
but when I execute npm install oracledb
there are lot of errors 
even I googled I have not got any answer could ay 1 help me
My os is Windows8.1

**Comment by SomeoneWeird** [comment]
What are the errors?

**Comment by SomeoneWeird** [comment]
Reopen if still an issue.
