### ISSUE TITLE
Missing Something (Probably Obvious) in Node tExercise 3

### ISSUE THREAD

**Issue by anonRegions** [nodeschool/discussions#1225]

**Comment by SomeoneWeird** [comment]
What's your issue?

**Comment by anonRegions** [comment]
Wow--you got to me before I submitted it. Here's the scoop:

These are the instructions:

"Write a program that uses a single synchronous filesystem operation to
read a file and
print the number of newlines (\n) it contains to the console (stdout),
similar to running
cat file | wc -l."

This is my code:

//load fs module from Node core library
var fs = require('fs');
//read file, returning Buffer object containing file contents
var buf = fs.readFileSync('path');
//convert Buffer object to string, splitting it into array of substrings
var str = buf.toString().split('\n');
var countNewlines = function(str) {
var count = 0;
for(i = 0; i < str.length; i++) {
//need if statement built around regex search for '\n'?
count += i;
}
return count;
};
console.log(countNewlines(str));

This is the error message in my console (Windows):

"fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags),
mode);
                 ^
Error: ENOENT, no such file or directory
'C:\Users\Ethan\OneDrive\Documents\Prog
ramming\Languages\JavaScript\NodeSchool\learnyounode\path'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.<anonymous>
(C:\Users\Ethan\OneDrive\Documents\Programming\Languag
es\JavaScript\NodeSchool\learnyounode\myFirstIO.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3"

I don't know what this means; nor do I understand what I'm getting wrong
because I've never written i/o stuff before & can't seem to output
individual stages of this to check my code as I go.

Please advise.

**Comment by anonRegions** [comment]
Here's my latest attempt:

//load fs module from Node core library
var fs = require('fs');
//get path to file
var path = process.argv[2];
//read file, returning Buffer object containing file contents
//function traverses array, using data as iterator
fs.readFileSync(path, function(errMsg, data) {
	//convert Buffer object to string, splitting it into array of substrings
	var substr = data.toString().split('\n').length - 1;
	return substr;
});
//console.log(buf(str));

Now I'm getting this error message: "throw new TypeError('Bad arguments');"

I'm following the examples I've seen in the documentation (I think) plus examples I've seen, but I don't know what the problem is with my arguments. 

Please advise.

Thanks.

**Comment by marocchino** [comment]
Are you doing my_first_async_io?
`fs.readFileSync` is not receive second argument.
Maybe it should be `fs.readFile` here.

**Comment by anonRegions** [comment]
I'm working on the 3rd exercise. The instructions, IIRC, indicate that
fs.readFileSync is to be used.

**Comment by marocchino** [comment]
You do not need to pass callback method.
just `data = fs.readFileSync(path)` and console.log that.

**Comment by anonRegions** [comment]
OK. This is weird: Every time I run the code below, I get a different number. Obviously, something's wrong, but I don't know what.

//load fs module from Node core library
var fs = require('fs');
//get path to file
var path = process.argv[2];
/* read file, returning Buffer object containing file contents;
Then convert to string & split into array of lines  */
var data = fs.readFileSync(path).toString().split('\n');
console.log(data.length-1);

Please advise.

Thanks.

**Comment by jkbits1** [comment]
The workshopper will pass your code a different file each time, so it's valid to have different outcomes. Does the verify stage give you a successful result?

**Comment by anonRegions** [comment]
I haven't tried that yet, not having seen (I thought) any correct outputs.
Now that you've told me that, I'll check & let you know.

Thanks!

**Comment by anonRegions** [comment]
Well, shiver me timbers! It worked!

Thank you very much, Jon, Adam Brady & marocchino!

**Comment by jkbits1** [comment]
We're delighted to have helped! Good luck with the rest of the tutorial, please feel free to ask more questions :smile:

**Comment by KBWild** [comment]
You can use myfirstio.js app anywhere as long as you have it in the folder with the file you want to count the newlines.

1.Go to Node.js CMD
2.Go to the path where it has your nodejs file (using CD change directory etc)
3. Type the arguments in the command line in format 
node 'nodejsapp.js' filetoberead.ext

.ext - file extension

C:\Users\John\Documents\Personal Docs\nodeschool\learnyounode>node myfirstio.js penne.txt
0
