### ISSUE TITLE
Tryd to start javascripting workshop but i dont see the table

### ISSUE THREAD

**Issue by john32** [nodeschool/discussions#1227]
hi im on ubuntu,

did
sudo apt-get update
sudo apt-get install node
sudo apt-get install npm
sudo npm install -g learnyounode
learnyounode
sudo learnyounode
(no error occurs, just jumping to next line)
sudo npm install -g javascripting
javascripting
sudo javascripting
(no error occurs, just jumping to next line, apparently there should be a nice table opening up)

any help ? :)

**Comment by SomeoneWeird** [comment]
Hi, please follow the instructions [here](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories#installing-node-js-v0-12) for installing node on Ubuntu.

**Comment by john32** [comment]
great this passage helped me :

# Note the new setup script name for Node.js v0.12
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

# Then install with:
sudo apt-get install -y nodejs

thank you very much :)

**Comment by SomeoneWeird** [comment]
Yay :)
