### ISSUE TITLE
Trouble verifying lesson#2 - weird numbers

### ISSUE THREAD

**Issue by waterjerome** [nodeschool/discussions#1228]
I created a working solution to #2:
---
jeromes-MacBook-Pro:learn jeromemiller$ node program.js 1 2 4
[ 'node', '/Users/jeromemiller/learn/program.js', '1', '2', '4' ]
7

...but when I go to verify I get this:
---
jeromes-MacBook-Pro:learn jeromemiller$ learnyounode verify program.js 1 2 4

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "[ '/usr/local/bin/node',"          !=    "362"                              
   "  '/Users/jeromemiller/learn/program.js'," !=    ""                                 
   "  '58',"                           !=                                       
   "  '69',"                           !=                                       
   "  '2',"                            !=                                       
   "  '64',"                           !=                                       
   "  '29',"                           !=                                       
   "  '45',"                           !=                                       
   "  '61' ]"                          !=                                       
   "362"                               !=                                       
   ""                                  !=                                       

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to BABY STEPS didn't pass. Try again!

When I try to verify again, it has a different numbers. What it going on?
-

OSX Yosemite
node -v = v0.12.4
npm -v = 2.10.1
learnyounode@2.5.2

**Comment by waterjerome** [comment]
I figured it. I left other code at the top of my test file.
-
console.log(process.argv);

Removed it and it passed fine.

**Comment by SomeoneWeird** [comment]
Woo! Sorry nobody responded, normally somebody does :)
