### ISSUE TITLE
how-to-npm doesn't understand windows paths with spaces

### ISSUE THREAD

**Issue by timmr99** [nodeschool/discussions#1229]
I'm taking the how-to-npm workshop and am having trouble completing challenges because how-to-npm doesn't understand windows paths with spaces.  Please review the output of this image for an example of the issue. 

![capture](https://cloud.githubusercontent.com/assets/7883581/8216317/087fdd56-14f3-11e5-943a-800f778fb955.PNG)

I would appreciate any help with this issue! Thanks in advance!

**Comment by SomeoneWeird** [comment]
It might be worth opening up an issue for how-to-npm as I don't think this is a problem with the other workshops.

**Comment by timmr99** [comment]
I've actually seen it in Scope and Stream modules, also.
