### ISSUE TITLE
Error when attempting to install "learnyournode" on Windows 7 (x64)

### ISSUE THREAD

**Issue by peterkmurphy** [nodeschool/discussions#1230]
This is not a welcome introduction to nodejs. Tutorials that need to be installed is one thing, but tutorials that fail on installation is another.

```
C:\Program Files\nodejs>npm install -g learnyournode
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyournode"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyournode"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>
```

**Comment by SomeoneWeird** [comment]
Are you behind a corporate proxy?

**Comment by peterkmurphy** [comment]
Yes. Would that prevent installation?

**Comment by peterkmurphy** [comment]
I found
To add to this bug, I discovered how to configure the proxy settings for node.js. (Note: I strongly, *strongly*, **strongly** suggest you add some documentation to your NodeSchool page so that nobody else is tripped up by the same issue):
```
npm config set proxy http://proxy:3128
npm config set https-proxy http://proxy:3128
```
Once I can do that, the error seems to go away.

**Comment by vacri** [comment]
G'day Peter - it looks like the issue is that your corporate firewall is switching out security certificates, hence the self-signed cert error. The fix you've found is local to your networking environment - http://proxy is not an address that exists on the internet (try it outside your corporate environment).

**Comment by SomeoneWeird** [comment]
Glad you got it working. Thanks @vacri
