### ISSUE TITLE
[Scope Chains]: Closures exercice

### ISSUE THREAD

**Issue by naimkhalifa** [nodeschool/discussions#1233]
Hi there!

I'm following the scope-chains-closures lessons and I'm stucked at excercice 4 on closures. 

It might be obvious but I can't understand what I did wrong with:

Here is the challenge:
*Modify your solution from the previous lesson to set bar = true inside zip(),
then return the function zip as the result of foo()*
```js
function foo() {
	var bar;
	quux = 3;
	
	function zip() {
		var quux = 2;
		bar = true;
	}		
	return zip();
}
```

Did I miss something?

**Comment by SomeoneWeird** [comment]
Very close. You're actually returning the result of `zip` when doing `zip();` (it's being called), you want to return the actual function, so don't invoke it.

**Comment by naimkhalifa** [comment]
Yes. Such a beginner mistake :)

Thanks a lot!
