### ISSUE TITLE
Exercise # 9 Juggling Async-- need help

### ISSUE THREAD

**Issue by ammark47** [nodeschool/discussions#1236]
This is my code write now 
```js
var http = require('http');
var bl = require('bl');
var url1 = process.argv[2],
	url2 = process.argv[3],
	url3 = process.argv[4];
var urls = [url1, url2, url3];

function printData(urls, callback) {
	var total = 0;
	var dataStrings = [];
	var str = "";
	urls.forEach(function (url) {

		http.get(url, function (res) {
				res.setEncoding('utf8');
				res.on('data', function(data){
					str += data;

				});
				res.on('end', function() {
					dataStrings.push(str);
					//str= "";

					total++;
					if (total === urls.length - 1) {
						callback(dataStrings);
					}
			});
		});
	});
}

printData(urls, callback);

function callback(dataStrings) {

	for (var i = 0; i < dataStrings.length; i++) {
		//dataStrings[i].join(',');
		console.log(dataStrings[i].text);
	}
}
```

This is my output:
```
1.  ACTUAL:    "undefined"
1.  EXPECTED:  "We're going pozzy where get a dog up ya clacker. It'll be joey piece of piss shazza got us some fair dinkum. As busy as a billy piece of piss come a bogan. As busy as a jug flamin gutful of ten clicks away. "

2.  ACTUAL:    "undefinedGrab us a plonk no worries watch out for the aerial pingpong. Mad as a flake my as dry as a mongrel. Built like a give it a burl bloody come a mates. Lets get some corker mate flat out Built like like a a doovalacky. esky how built like a lippy. Trent from punchy greenie heaps gutful of dunny. As busy as a maccas with lets throw a tucker. She'll be We're right going snag pozzy heaps where he get hasn't a got dog a up brass ya razoo. clacker. "
2.  EXPECTED:  "Grab us a plonk no worries watch out for the aerial pingpong. Mad as a flake my as dry as a mongrel. Built like a give it a burl bloody come a mates. Lets get some corker mate flat out like a doovalacky. "

3.  ACTUAL:    "undefined"
3.  EXPECTED:  "Built like a esky how built like a lippy. Trent from punchy greenie heaps gutful of dunny. As busy as a maccas with lets throw a tucker. She'll be right snag heaps he hasn't got a brass razoo. "

4.  ACTUAL:    "undefined"
4.  EXPECTED:  ""
```

I'm not sure what I should do to move forward or if I'm going in the right direction.

**Comment by jkbits1** [comment]
@ammark47 Thanks for letting us know how you're getting on :smile:  You've provided us with well-presented information, too, which is great.

Your code isn't far off, you are definitely going in the right direction! There are two areas that need a relatively small amount of attention. First, you only have a single `str` variable at the printData scope. Looking at your actual output above, can you see why it might be helpful to have that variable declared within one of the functions within prinData? A trial and error process might help you there, by seeing how the results differ.

Secondly, the responses must be shown in the order the urls are provided to the code, but using dataStrings.push will put them on the array in the order that responses are received (which could be in any order). You are using forEach to go through your array, which is a good choice. As well as providing the array value (the url), forEach can provide the array index as well, if you change `function (url)` to `function (url, index)`. Can you see how you might use `index` with dataStrings (and without using push) to put the responses in the array in the order required? Again, a bit of trial and error might help.

Good luck, and let us know how you get on!

**Comment by ammark47** [comment]
Ahh you're the best! Its makes so much sense when you explain it :)

**Comment by SomeoneWeird** [comment]
:tada:
