### ISSUE TITLE
Decrementing a variable in function parameters

### ISSUE THREAD

**Issue by jimseverino** [nodeschool/discussions#1237]
I'm curious why this works:

```javascript
function repeat(func, num) {
  if (num <= 0) { return 0; }
  func();
  num--;
  repeat(func, num);
}

repeat(function foo() {
  console.log('foo ran');
}, 3);
```

And this works:

```javascript
function repeat(func, num) {
  if (num <= 0) { return 0; }
  func();
  repeat(func, num -= 1);
}

repeat<...same as before...>
```

But this loops endlessly:

```javascript
function repeat(func, num) {
  if (num <= 0) { return 0; }
  func();
  repeat(func, num--);
}

repeat<...same as before...>
```

It seems like the decrement operator (num--) isn't decrementing num when used as a function parameter. What can explain this?

Thanks in advance for your help.

**Comment by jkbits1** [comment]
@jimseverino Well spotted! :+1:  It's great that you're trying out the different possibilities and being very aware of the different results :smile: 

The reason for this behaviour is that Javascript considers `num--` to be different from `--num` (not one of your options above). The specific terminology is postfix and prefix, respectively. The postfix usage returns the value of `num` and then decrements it (and prefix decrements it and then returns the value). So in your example, `num` is decremented, but only after the non-decremented value is passed to the function, leading to the endless loop.

Here's the mozilla page on this and related operators:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Decrement

Please ask any more questions you have, as you work through the tutorial.

**Comment by jimseverino** [comment]
Thanks @jkbits1 - That explains it.
