### ISSUE TITLE
Learnyounode Juggling Async - I'm stuck!

### ISSUE THREAD

**Issue by suitcasemedia** [nodeschool/discussions#1239]
Hello guys Im trying to solve the problem:

"You must collect the complete content provided to you by each of the URLs and print it to the console (stdout). You don't need to print out the length, just the data as a String; one line per URL. The catch is that you must print them out in the same order as the URLs are provided to you as command-line arguments."

I've tried counting the callbacks in a variable called waiting and then calling a complete() function when it has counted 3 callbacks, but the data always comes back in the wrong order and I don't know why....

    var http = require('http');
    var bl = require('bl');
    var url = []
    url[0] = process.argv[2];
    url[1] = process.argv[3];
    url[2] = process.argv[4];
    var waiting  = 0 ;
    for(i=0; i < url.length ; i++){
                var output = [] ;
                http.get( url[i], function(res){

                        res.setEncoding('utf8');
                        res.pipe(bl(function(err,data){
                                output.push(data.toString());
                                waiting++ ;
                                if( waiting == 3){
                                    complete(output);
                                }

                         }));

                });
    }

    var  complete= function (output){
        for(i=0; i < output.length ; i++) {
             console.log( output[i]);
                                }
    }

**Comment by suitcasemedia** [comment]
Hello I got some help from here http://stackoverflow.com/questions/30979122/why-are-my-async-callback-functions-not-returning-the-data-requests-in-order
but my corrected( I changed 
        output.push(data.toString());
to:

       output[i] = data.toString();
but the  answer still fails: .

       var http = require('http');
        var bl = require('bl');
        var url = []
        url[0] = process.argv[2];
        url[1] = process.argv[3];
        url[2] = process.argv[4];
        var waiting  = 0 ;
        for(i=0; i < url.length ; i++){
                var output = [] ;
                http.get( url[i], function(res){

                    res.setEncoding('utf8');
                    res.pipe(bl(function(err,data){
                            output[i] =  data.toString();
                            waiting++ ;
                            if( waiting == 3){
                                complete(output);
                            }


                     }));

            });
    }

    var  complete= function (output){
        for(i=0; i < output.length ; i++) {
             console.log( output[i]);
                            }
    }

**Comment by suitcasemedia** [comment]
This is what I got back: ..although the code had worked when I tested it myself

Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "undefined"
1.  EXPECTED:  "It'll be truckie to as stands out like thongs. She'll be right billabong where as dry as a garbo. "

2.  ACTUAL:    "undefined"
2.  EXPECTED:  "Grab us a sleepout mate flat out like a big smoke. Grab us a waggin' school heaps she'll be right holy dooley!. You little ripper chokkie no worries built like a ripper. Get a dog up ya fremantle doctor piece of piss shazza got us some bogan. "

3.  ACTUAL:    "undefined"
3.  EXPECTED:  "As cross as a bottle-o when watch out for the cactus mate. As cunning as a sook also mad as a sook. Get a dog up ya dog's balls where trent from punchy yabber. "

4.  ACTUAL:    "It'll be truckie to as stands out like thongs. She'll be right billabong where as dry as a garbo. "
4.  EXPECTED:  ""


────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to JUGGLING ASYNC did

**Comment by marocchino** [comment]
actually, the `output[i]` is always to be `output[3]`. You should not use `i` inside of callback.

**Comment by suitcasemedia** [comment]
marocchino can you explain a little more ? output[3] is just one callback- I need to loop through callbacks to get data 3 times hence output[i], so that I can loop through output[0], output[1], output[2]

Why should I not loop inside a callback?

**Comment by marocchino** [comment]
Because It executed after loop. Your code is basically same with this:
```js
arr = []
for(i=0; i < 3 ; i++){
setTimeout(function() { arr[i] = i; }, 1);
}
console.log(arr)
```

**Comment by suitcasemedia** [comment]
I guess this explains why in the test I get the correct answer for test 1 in text 4. Test 1, 2 and 3 executed before the callback completes ?

Do you have any examples of places where I can read up about queuing multiple callbacks so that I can try to understand it properly and  do the question correctly ?

**Comment by marocchino** [comment]
I know this is not best answer for this question. but, simplest way is just export inside of `for` statement.
```js
var arr = []
function doSomething(i) {
  setTimeout(function() { arr[i] = i; }, 1);
};
for(var i=0; i < 3 ; i++){
  doSomething(i);
}
console.log(arr)
```

**Comment by suitcasemedia** [comment]
Can't see how that's different from what I did... thanks for your help, I think I'm going to try to read up on this some more then come back to it...

**Comment by suitcasemedia** [comment]
I've looked at other peoples code and re-factored a bit but still my code won't pass. In the test my fourth response matches the actual first response and my other responses are undefined. It seems it takes to long for my code to execute or something...

    var http = require('http');
    var bl = require('bl');
    var waiting  = 0 ;
    var run = function(idx){

                var output = [] ;
                http.get( process.argv[idx], function(res){
                           res.setEncoding('utf8');
                            res.pipe(bl(function(err,data){
                                output[i] = data.toString()  ;
                               waiting++ ;
                               if( waiting == 3){
                                    complete(output);
                               }
                              }));
                          });
      }

    for(i=2; i < process.argv.length ; i++){
    run(i);

    }
    var  complete = function (output){
      for(i=0; i < output.length ; i++) {
           console.log( output[i]);
         }
     }

 
Here is my test


Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "undefined"
1.  EXPECTED:  "Lets get some two up flamin he's got a massive g'day. We're going bonza bloody lets get some donger. He hasn't got a apples no dramas get a dog up ya sook. Gutful of buckley's chance no dramas he hasn't got a ocker. He hasn't got a rack off mate you little ripper bodgy. "

2.  ACTUAL:    "undefined"
2.  EXPECTED:  "She'll be right clacker bloody trent from punchy ironman. You little ripper bundy my stands out like a big smoke. Get a dog up ya stubby holder with as busy as a mates. "

3.  ACTUAL:    "undefined"
3.  EXPECTED:  "Gutful of bikkie piece of piss she'll be right ropeable. Come a oldies bloody we're going slaps. Lets throw a fair go to get a dog up ya dob. "

4.  ACTUAL:    "undefined"
4.  EXPECTED:  ""

5.  ACTUAL:    "Lets get some two up flamin he's got a massive g'day. We're going bonza bloody lets get some donger. He hasn't got a apples no dramas get a dog up ya sook. Gutful of buckley's chance no dramas he hasn't got a ocker. He hasn't got a rack off mate you little ripper bodgy. "
5.  EXPECTED:

6.  ACTUAL:    ""
6.  EXPECTED:

**Comment by dominhhai** [comment]
Your `output ` array will be re-defined after calling the `run` function since it is in the `run` scope. So, you can not get the full result after all `run` operations finished.

**Comment by suitcasemedia** [comment]
Thanks so much for your help. What you are saying is very interesting. I am trying to understand what you mean, but am finding this exercise very tricky. After reading your comment I made a closure to create a private scope hoping that if output is in a different scope to run it will not be redeclared. My test result is the same. It seems I am not fully grasping the rules. Can you suggest any resources or make more comments that will help me finally 'get it'.

    var http = require('http');
    var bl = require('bl');
    var waiting  = 0 ;
    var run = function(idx){

                var output = [] ;
                http.get( process.argv[idx], function(res){

                        res.setEncoding('utf8');
                        res.pipe(bl(function(err,data){
                                output[i] = data.toString()  ;
                          waiting++ ;

                         if( waiting == 3){
                                complete(output);

                           }
                        }));

                      });
      }
    var init = (function(){
    for(i=2; i < process.argv.length ; i++){
    run(i);

       }})();
    
     var  complete = function (output){
       for(i=0; i < output.length ; i++) {
           console.log( output[i]);
          }
        }


Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "undefined"
1.  EXPECTED:  "As busy as a bonzer heaps lets get some chrissie. As cross as a nipper no worries as cunning as a yabber. "

2.  ACTUAL:    "undefined"
2.  EXPECTED:  "She'll be right cranky also he hasn't got a ridgy-didge. As stands out like true blue my she'll be right donger. Built like a dag how as stands out like shag on a rock. Gutful of rack off mate as stands out like pav. "

3.  ACTUAL:    "undefined"
3.  EXPECTED:  "It'll be feral no dramas watch out for the trackies. It'll be cark it flamin he hasn't got a tinny. We're going booze flamin she'll be right chuck a yewy. As busy as a dipstick to it'll be bog standard. "

4.  ACTUAL:    "undefined"
4.  EXPECTED:  ""

5.  ACTUAL:    "As busy as a bonzer heaps lets get some chrissie. As cross as a nipper no worries as cunning as a yabber. "
5.  EXPECTED:

6.  ACTUAL:    ""
6.  EXPECTED:


────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to JUGGLING ASYNC didn't pass. Try again!

**Comment by dominhhai** [comment]
`output[i] = data.toString()  ;` should be `output[idx] = data.toString()  ;`

and move `output` to out of `run` scope. Exactly, the same scope with `waiting`.

**Comment by suitcasemedia** [comment]
Thanks again for your help. I think I must be getting closer.. see below the updated code and test result...

clear
   var http = require('http');
    var bl = require('bl');
    var waiting  = 0 ;
    var output = [] ;
    var run = function(idx){


                http.get( process.argv[idx], function(res){

                        res.setEncoding('utf8');
                        res.pipe(bl(function(err,data){
                                output[idx] = data.toString()  ;
                          waiting++ ;


                          if( waiting == 3){
                                complete(output);

                           }
                        }));


                         });
      }
    var init = (function(){
    for(i=2; i < process.argv.length ; i++){
    run(i);

    }})();
    var  complete = function (output){
      for(i=0; i < output.length ; i++) {
           console.log( output[i]);
         }
     }


Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "undefined"
1.  EXPECTED:  "Flat out like a bush bash how he hasn't got a mongrel. Come a wuss and she'll be right truckie. Lets throw a ute and come a road train. "

2.  ACTUAL:    "undefined"
2.  EXPECTED:  "Mad as a ridgy-didge mate lets get some barrack. Come a cleanskin heaps it'll be mokkies. "

3.  ACTUAL:    "Flat out like a bush bash how he hasn't got a mongrel. Come a wuss and she'll be right truckie. Lets throw a ute and come a road train. "
3.  EXPECTED:  "He's got a massive spit the dummy also flat out like a arvo. It'll be clacker no dramas stands out like a coldie. Shazza got us some bikkie to it'll be compo. As stands out like oldies to as cunning as a trackie dacks. "

4.  ACTUAL:    "Mad as a ridgy-didge mate lets get some barrack. Come a cleanskin heaps it'll be mokkies. "
4.  EXPECTED:  ""

5.  ACTUAL:    ""
5.  EXPECTED:


────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to JUGGLING ASYNC didn't pass. Try again!

**Comment by marocchino** [comment]
wow! much closer.
some advice:
1. currently i of `process.argv` is 2, 3, 4 but `i` of `output` should be 0, 1, 2.
2. init function is not necessary. so, this code can be reduce.
```
    var init = (function(){
    for(i=2; i < process.argv.length ; i++){
    run(i);
    }})();

# after
    for(i=2; i < process.argv.length ; i++){
      run(i);
    }
```
3. some variable's name is not proper. maybe `waiting` could be `endCount`, `complete` could be `print`.

**Comment by suitcasemedia** [comment]
Thanks again for your help...
My code passed! Hurray. I will have a think about how to make it shorter...
  
  var http = require('http');
    var bl = require('bl');
    var endCount  = 0 ;
    var output = [] ;
    var run = function(idx){
         http.get( process.argv[idx], function(res){

                        res.setEncoding('utf8');
                        res.pipe(bl(function(err,data){
                                output[idx - 2] = data.toString()  ;
                          endCount++ ;


                          if( endCount == 3){
                                print(output);

                           }
                        }));


                         });
      }
    var init = (function(){
    for(i=2; i < process.argv.length ; i++){
    run(i);

    }})();
    var  print  = function (output){
      for(i=0; i < output.length ; i++) {
           console.log( output[i]);
         }
     }

**Comment by marocchino** [comment]
good job! :clap:

**Comment by dominhhai** [comment]
:star2:

**Comment by suitcasemedia** [comment]
Thanks!
