### ISSUE TITLE
behavior of http.createServer

### ISSUE THREAD

**Issue by bfang-yseop** [nodeschool/discussions#124]
I am running through stream-adventure: http server when I first stumbled upon this oddity.

when I wrote my code like so:

```
var through = require('through');
var http = require('http');

var ts = through(function (buf){
    this.queue(buf.toString().toUpperCase());
})

var server = http.createServer(function (req, res) {


    if (req.method === 'POST'){
        req.pipe(ts).pipe(res);
    } else {
        res.end("Will I dream? \n")
    }
});

server.listen(process.argv[2])
```

I got extra results that I could not explain. However, when I moved `var ts = ...` into `createServer`'s callback function the program ran as expected.

Can anyone explain what happened? Why would declaring ts outside of `createServer` produce different results?

**Comment by RichardBansal** [comment]
@timoxley thanks for clarifying this concept +1:
