### ISSUE TITLE
npm ERR! 404 Not Found: learnyournode

### ISSUE THREAD

**Issue by ganeshkbalaji** [nodeschool/discussions#1240]
npm ERR! 404 404 Not Found: learnyournode
npm ERR! 404
npm ERR! 404 'learnyournode' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/ganeshkb/.nvm/v0.10.39/bin/node" "/Users/ganeshkb/.nvm/v0.10.39/bin/npm" "install" "-g" "learnyournode"
npm ERR! cwd /Users/ganeshkb
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ganeshkb/npm-debug.log
npm ERR! not ok code 0

**Comment by fiveisprime** [comment]
You've got a typo there, it's `learnyounode` - "learn you node" rather than "learn you*r* node." :+1:

**Comment by ganeshkbalaji** [comment]
Got it Thanks!
