### ISSUE TITLE
Get radio button values

### ISSUE THREAD

**Issue by syameficaz** [nodeschool/discussions#1242]
How can I get the values of dynamically generated radio buttons posted to another page.

Example:
Name of the radio button goes like this..
ans_radio[54]
ans_radio[54]
ans_radio[54]
ans_radio[54]
ans_radio[55]
ans_radio[55]
ans_radio[55]
ans_radio[55]

I want to get the values using req.body.ans_radio or something.. Can anybody help please..

**Comment by SomeoneWeird** [comment]
Please do not create another issue with the same content.

You need to be more specific with what you're doing, and what libraries/frameworks you're using.

Are you using express?

**Comment by syameficaz** [comment]
I am using express framework..

**Comment by syameficaz** [comment]
I had done this using php before by giving the name of radio button as array (like radio[1],radio[2]..) and get the value as an array by calling the name only. Like that I used array names for radio buttons in node. But not able get those values. If I use radio1, radio2 etc I am getting the values by calling req.body.radio1

**Comment by SomeoneWeird** [comment]
I think you need to use some kind of middleware to parse form values submitted, it's been a long time since I've used actual forms :)

**Comment by SomeoneWeird** [comment]
Have a look at [formidable](https://github.com/felixge/node-formidable)

**Comment by syameficaz** [comment]
Okay.. I will check ... Thank you for your suggestion :)

**Comment by syameficaz** [comment]
I found the issue... Changed the parameter "extended" to true in the bodyparser module which was false. 
app.use(bodyParser.urlencoded({ extended: true }));
console.log(req.body.ans_radio);
Got the value as json.. 
( [ 'value 1', 'value 2' ] -- values of the radio buttons checked)

Thanks for your support.. :+1:

**Comment by SomeoneWeird** [comment]
Awesome! :tada:
