### ISSUE TITLE
Exercise 5--Path Dilemma

### ISSUE THREAD

**Issue by anonRegions** [nodeschool/discussions#1243]
The code below yields no output when sent to console.log & I don't understand why:
```js
var fs = require('fs');
var path = require('path');
var dirName = process.argv[1] + '.' + path.extname(dirName);
console.log(dirName);
```
The above is a test which I set up because the full code (below)
```js
var fs = require('fs');
//load path module from node library
var path = require('path');
//get directory name, concatenate w/ separator
var dirName = process.argv[1] + '.' + path.extname(dirName);

var outputLines = function(item) {
	console.log(item);
};

fs.readdir(path, function(err, list){
	if (err) throw err;
	for(var i = 0; i < list.length; i++){
		outputLines(list[i].toString() + '\n');
	}
});
```
yields the following error message:
```
"fs.js:660
  binding.readdir(pathModule._makeLong(path), callback);
          ^
TypeError: path must be a string
    at Object.fs.readdir (fs.js:660:11)
    at Object.<anonymous> (C:\Users\Ethan\OneDrive\Documents\Programming\Languages\JavaScript\NodeSchool\learnyounode\filteredLs.js:12:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
[Finished in 0.2s with exit code 8]"
```
Please advise.

Thanks.

**Comment by SomeoneWeird** [comment]
The first argument your passing to `fs.readdir` is wrong, did you mean to pass `dirName`?

**Comment by anonRegions** [comment]
Um, yes, I did.

Having changed it to dirName, I now get this error message:

"Error: ENOENT, readdir 'C:\[path]\filteredLs.js'"

Under Expected are 3 .md files & "". Actual is "". 

Is my path wrong or am I missing something about these node methods?

**Comment by anonRegions** [comment]
The code below points to a directory different from the one I'm supposed to be getting via path.dirname(process.argv[1]). Can anyone help me to understand why that is?

//load fs module from node library
var fs = require('fs');
//load path module from node library
var path = require('path');
//get directory name
var dirName = path.dirname(process.argv[1]);
//get extension
var ext = path.extname(process.argv[2]);	//yields .js
//function to output each line passed by fs.readdir()
var outputLines = function(item) {
	console.log(item.toString() + '\n');
};

//loop thru directory, passing each line to outputLines() to print
fs.readdir(dirName, function(err, list){
	if (err) throw err;
	for(var i = 0; i < list.length; i++){
		if(path.extname(list[i]) === ext);
			outputLines(list[i]);
	}
});

**Comment by patterncoder** [comment]
dirname is at process.argv[2] and extension is at [3]
Remember that [0] is 'node' and [1] is the full path of the file you are executing.

**Comment by anonRegions** [comment]
Thank you, patterncoder! I didn't realize that at all.

**Comment by patterncoder** [comment]
You are most welcome!  ;-)

----------------------------------------

**Comment by SomeoneWeird** [comment]
Yay!
