### ISSUE TITLE
npm in node js problem

### ISSUE THREAD

**Issue by copterbuzz** [nodeschool/discussions#1244]
I have just started to use node js, and I don't know where to install modules. I tried pasting it alongside node.exe, and when I execute

npm install -g learnyounode

I get:

npm should be run outside of the node repl, in your normal shell.

What does that mean?
Thanks!

**Comment by dominhhai** [comment]
simply, open your normal windows's command line terminal and type `npm install -g learnyounode`.
search with `cmd` keyword in your start search box may help :+1:

**Comment by SomeoneWeird** [comment]
Reopen if still an issue.
