### ISSUE TITLE
downloading basic Javascript info

### ISSUE THREAD

**Issue by evanthes** [nodeschool/discussions#1245]
Im sure this is a simple question, but when I type in:

npm install -g javascripting

I get:

npm install -g javascripting
npm ERR! tar.unpack untar error /Users/evan/.npm/javascripting/2.0.3/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "javascripting"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /usr/local/lib/node_modules/javascripting
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }

how can i get past this?

Thanks,

Evan

**Comment by dominhhai** [comment]
Did you try `sudo npm install -g javascripting` ?

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
