### ISSUE TITLE
javascripting for loops - verify is incorrect

### ISSUE THREAD

**Issue by hupiper** [nodeschool/discussions#1246]
When I verify my answer for FOR LOOPS, I am told I have an error, that the result should say 45, but mine says 10. 

Here are the directions:
Create a file named for-loop.js.
In that file define a variable named total and make it equal the number 0.
Define a second variable named limit and make it equal the number 10.
Create a for loop with a variable i starting at 0 and increasing by 1 each time through the loop. The loop should run as long as i is less than limit.
On each iteration of the loop, add the number i to the total variable. To do this,
total += i;
After the for loop, use console.log() to print the total variable to the terminal.

The answer is 10.

**Comment by SomeoneWeird** [comment]
Can you paste your code?

**Comment by bryson11** [comment]
var total = 0,
      loop = 10;
for(var a = 0 ; a < loop ; a++){
  total += a;
}
console.log(total);
// THIS IS TRUE CODE

**Comment by SomeoneWeird** [comment]
Are you sure? If I run that code I get 45.

**Comment by bryson11** [comment]
Yes, I am sure
Test it...

**Comment by SomeoneWeird** [comment]
```
➜  cat a.js
var total = 0,
loop = 10;
for(var a = 0 ; a < loop ; a++){
total += a;
}
console.log(total);

➜  node a.js
45
```

**Comment by jamc92** [comment]
Hi everyone, I found the mistake.

Your output was 9 because the exercise was not saying the example properly at this: total =+ i;

"On each iteration of the loop, add the number i to the total variable. To do this, you can use this statement:

total =+ i;" instead of saying: total += i;

It seems is already fixed and now the example is: total += i;

That could was your confusion.

**Comment by hupiper** [comment]
Yep - I caught that this weekend. Thanks! I'll close the issue.

**Comment by crlee3** [comment]
Ok so the code that worked for me was:

var total = 0
var limit = 10

for(var i = 0; i < limit; i++){
	total += i;
}
console.log(total);


My question is why wouldn't this work:

var total = 0 
var limit = 10

for(total; total < limit; total++){
     console.log(total)
};

Isn't "total" equal to 0? Why do we set another "var i = 0"? is that what the "total += i is"? Is that saying that replace "i" with "total"?? Sorry for the machine gun style questions. Just a big noob here looking for understanding. Thanks.

**Comment by Maamun** [comment]
@ jamc92 thx so much
