### ISSUE TITLE
How to solve function argument javascripting

### ISSUE THREAD

**Issue by bryson11** [nodeschool/discussions#1248]
In that file, define a function named math that takes three arguments. It's important for you to understand that arguments names are only used to reference them.

Name each argument as you like.

The function math should multiply the second and third arguments, then add the first argument to the outcome of the multiplication and return the value obtained.

After that, inside the parentheses of console.log(), call the math() function with the number 53 as first argument, the number 61 as second and the number 67 as third argument.

**Comment by ddata999** [comment]
I need help with this one. what would the correct code look like?

**Comment by NathanaelS** [comment]
*First post to github, hope I do this right*

```javascript
        function math(a, b, c) {
        return (b*c)+a
}

console.log(math(53, 61, 67)
```

**Comment by jebalert** [comment]
The correct answer is
 function math (a, b, c) {
	return (b*c)+a;
}

console.log(math(53, 61, 67));

**Comment by NathanaelS** [comment]
The only difference I am seeing between my answer and your answer is the semi colons, but my answer worked for me, both when I verified it, and when I ran it. So what than is the significance of the semi colons? In SQL it denotes the end of the command, but I haven't had to do that with Javascript

**Comment by jebalert** [comment]
When I execute the code without the semi colons, it fails. As of 3 minutes ago, that is.

**Comment by NathanaelS** [comment]
That is so weird, because I am executing without semi colons and it works. Just tried.

**Comment by NathanaelS** [comment]
https://www.dropbox.com/s/kmx79qbgocmhjhw/Screenshot%202015-07-25%2012.45.33.png?dl=0

The first verification is without semi colons. I then run it. I then modified the code to what you see on the right (with the semi colons), ran it, and then verified it. These are my results.

**Comment by jebalert** [comment]
Nate, both answers DO work. I verified them both.

**Comment by NathanaelS** [comment]
Ok cool. Glad it got straightened out. Was even more confused when I saw your one comment was deleted lol
