### ISSUE TITLE
Problem with javascripting

### ISSUE THREAD

**Issue by catalinbararu** [nodeschool/discussions#1249]
Hi, 
I run javascripting and choose something.
I do that assignment and when i type javascripting verifi aaa.js it says :"No active exercise found. Select one from the menu". Any help ?
Thank you

**Comment by SomeoneWeird** [comment]
What does `javascripting current` return?

**Comment by catalinbararu** [comment]
It return ?en.exercise.null? 
The thing is that after i choose a program from the list, the program is printed and i get returned to the console

**Comment by SomeoneWeird** [comment]
Weird, what version do you have installed?

`javascripting -v`

**Comment by catalinbararu** [comment]
2.0.3 is my version

**Comment by SomeoneWeird** [comment]
hm, what OS are you on?

**Comment by catalinbararu** [comment]
I'm using ubuntu 14.04

**Comment by SomeoneWeird** [comment]
Right, and what version of node? Sorry for all the questions haha, just trying to work out what could be the issue.

**Comment by catalinbararu** [comment]
node : v0.10.25

**Comment by SomeoneWeird** [comment]
Can you update your node and see if that fixes your issue?

**Comment by catalinbararu** [comment]
Hmm, when i try apt-get install nodejs it says there are no new versions

**Comment by SomeoneWeird** [comment]
You might need to follow the instructions [here](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) again, to install 0.12

**Comment by catalinbararu** [comment]
I think i found a solution. If i tried to run something like "node a.js" it did not work (using ide to run scripts). So i checked online and a hash -r command seems to have done the thing. Thank for your help :+1:

**Comment by catalinbararu** [comment]
Seems to be ok now. Thank you. Using v0.12.4

**Comment by SomeoneWeird** [comment]
Awesome! It seems it doesn't work with an older version of node. Open another issue if you run into any more problems :tada:
