### ISSUE TITLE
Need help with exercise 11

### ISSUE THREAD

**Issue by ammark47** [nodeschool/discussions#1250]
My code:

/*jslint node: true*/
var http = require('http');
var fs = require('fs');

var server = http.createServer(function(req, res) {
	//var wstream = fs.createWriteStream(res.url);
	var input = process.argv[3];
	var rstream = fs.createReadStream(input);
	rstream.pipe(res);
	console.log(res.url);
	res.end();
});
server.listen(process.argv[2]);

My output:
" "

I'm not sure how to move forward. Any help is appreciated

**Comment by davecocoa** [comment]
Why are you calling `res.end();`? When you pipe a read stream (the file stream) into a write stream (the response stream), in general you can stand back and let the write stream end itself automatically when it receives the end event from the read stream.

**Comment by ammark47** [comment]
Thanks I took that and console.log out and it worked. I must have put that to troubleshoot the server hanging.
