### ISSUE TITLE
help with exercise 12 

### ISSUE THREAD

**Issue by ammark47** [nodeschool/discussions#1251]
My code:
/*jslint node: true*/
var map = require('through2-map');
var http = require('http');

var server = http.createServer(function(req,res) {
	req.pipe(map(function (chunk) {
		return chunk.toString().split('').toUpperCase.join('')
	})).pipe(res);
	console.log(req.toString());
}).listen(process.argv[2]);

Output: Cannot call method 'join' of undefined

I'm not really sure how to proceed with this question or if I'm heading in the right direction. I'm not sure where the data (chunks) are coming from as well.

**Comment by davecocoa** [comment]
It's generally a good idea to add a bit of extra logging when you're stuck. In this particular case, something in your code is `undefined`, but we know even more than that, we know that you're trying to call `join` on something that's undefined. In particular, the line `return chunk.toString().split('').toUpperCase.join('')` has a lot going on (4 method calls!), so it might help to split that up and log some of the intermediate values.

**Comment by ammark47** [comment]
Thanks that helped a bit. However, I still haven't solved it completely

My code: 
/*jslint node: true*/
var map = require('through2-map');
var http = require('http');

var server = http.createServer(function(req,res) {
	var group = [];

	req.pipe(map(function (chunk) {
		group.push(chunk.toString().toUpperCase());
	})).pipe(res);

});
server.listen(process.argv[2]);

My output is correct but I can't get it to the output it in the correct place (where lyn wants me to)
I tried a for loop outside the pipe but that doesn't work either

**Comment by ammark47** [comment]
nevermind I just tried returning each value and it worked. Appreciate your help
