### ISSUE TITLE
How is the lesson 9 LearnYouNode solution Async?

### ISSUE THREAD

**Issue by PaulBeaudet** [nodeschool/discussions#1252]
solution here- https://github.com/workshopper/learnyounode/blob/master/exercises/juggling_async/solution/solution.js

I'm having a hard time getting my head around line 17. Unless somehow "index" becomes a property of each specific callback. In which case how is that the case? Isn't just the URL passed to the first callback? Otherwise this would have to be a blocking operation.

My main question is how is this solution asynchronous? Specifically how is the index tracked "after" it has changed. The second anonymous "bl" callback is occurs long after index has been changed twice in the case this is truly asynchronous.

**Comment by davecocoa** [comment]
Every time a function is called it gets a fresh set of instance variables - this includes any variables defined using `var` and any arguments passed into the function. Therefore, there are three different instances of the `index` variable and they do not interfere with each other.

**Comment by PaulBeaudet** [comment]
Thank you Dave for replying, I appreciate it,

Once I think about it looking the solution over again, what you are saying makes sense. If a function is instantiated for a callback an implied instance of index is created. (only if index is used? or for each callback regardless?).

So my first question is mostly clear now, but it leads to a follow up question. Lets say I'm trying to avoid future callback hell and I want to instantiate the second callback (line 13) outside of the httpGet function, how would index then be able to be passed to the callback?

**Comment by davecocoa** [comment]
For each callback regardless.

What do you mean by instantiate the second callback? If you mean defining the function you pass to `bl`, you have two options. You can either define that function inside a scope with access to `index` (you could move it outside the function started on line 12, but not outside the function `httpGet` started on line 11), or you can define it in an outer scope and pass `index` into it.

```
function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(resultsReady(index))
  })
}

function resultsReady(index){
  return function (err, data) {
      if (err)
        return console.error(err)

      results[index] = data.toString()
      count++

      if (count == 3)
        printResults()
    }
}
```

**Comment by PaulBeaudet** [comment]
"for each callback regardless" - sounds like that could get messy with potential namespace conflict but maybe not so much in practical use, good to know

Indeed was referring to the function passed to bl. That answer helps, I'm probably less familiar with JavaScript than I should be to tackle these learnyounode lessons. Makes for a real crash course in getting started with JavaScript. Coming from a more strongly typed programming language all of these anon functions are mind boggling. Nesting a function in a function to pass a param would have been my last thought if left to my own devices, but it seems to makes sense when everything is treated as an object. 

Thank you again!
