### ISSUE TITLE
Levelmeup Basic GET function expression vs function statement

### ISSUE THREAD

**Issue by sayedasadali** [nodeschool/discussions#1253]
I am fairly new to "asynchronous" thinking and am not being able to figure out why two similar-looking solutions to this problem give varying results.

###  Approach 1 : Function Statement (WRONG ANSWER)
```javascript
var level    = require('level');
var db   = level(process.argv[2]);
for (var i = 0; i <= 100; i++) {
	(getKey('key' + i));
};
var getKey = function(key){
		db.get(key, function(err, value){
			if (err) return;
			console.log(key + '=' + value);
		});
	};
```

### Approach 2 - Function Expresssion (CORRECT ANSWER)
```javascript
var level    = require('level');
var db   = level(process.argv[2]);
for (var i = 0; i <= 100; i++) {
	(function(key){
		db.get(key, function(err, value){
			if (err) return;
			console.log(key + '=' + value);
		});
	}('key' + i));
};
```
To an untrained eye these two look the same. What am I missing?

**Comment by davecocoa** [comment]
When you say "varying results", what do you mean exactly? One thing which I find very useful when using these workshops, is using `run` instead of `verify` when I'm stuck - this will display any errors occurring in your program.

**Comment by sayedasadali** [comment]
Approach 1 does not provide the correct answer. It does not output anything at all. Almost as if `getKey()` is never called. But when I defined it inline, it works fine.

**Comment by davecocoa** [comment]
And what happens if you try using `run` instead of `verify`?

**Comment by sayedasadali** [comment]
i see where I went wrong. Dint define the function before using it. The `run` trick worked.

Thank you :)

**Comment by davecocoa** [comment]
Nice! :tada: :confetti_ball:
