### ISSUE TITLE
Javascripting - Scope (last challenge)

### ISSUE THREAD

**Issue by jamc92** [nodeschool/discussions#1254]
The exercise says that you need to create a file named 'scope.js' to put your code inside.
But at the end it says:
"To verify your program, run: javascripting verify program.js"
It should say **scope.js** instead of program.js

I was trying to make a pull request about it but i did not get it.

**Comment by SomeoneWeird** [comment]
Hm, either you don't have the latest version, or the version with this fixed hasn't been published yet, but it's definitely correct [here](https://github.com/sethvincent/javascripting/blob/master/problems/scope/problem.md).

**Comment by jamc92** [comment]
Thank you.
