### ISSUE TITLE
Learnyounode - #8 HTTP COLLECT: why use bl/concat-stream?

### ISSUE THREAD

**Issue by Ntangen** [nodeschool/discussions#1257]
I finished this exercise and made sure figure it out using both approaches suggested: using multiple data events vs bl (buffer list) vs concat-stream. My code all works. Rather, I'm a little confused conceptually: why would we want to use a third party package to do this anyway?

My code for the exercise using my own data events was pretty short and sweet as it was. Using bl or concat-stream just seems to add more complexity. Is the advantage here mostly in just knowing *how* to use third-party npm modules, or in showing us that you can avoid writing new code by using them? Because beyond that, I'm not really getting why you would want to use something else in this case.

**Comment by peteconz** [comment]
and ignore hint #1 using 'end' event. not needed. solution doesn't use either.

**Comment by FireOfChina** [comment]
I think it's just trying to say there is more than one way to solve one problem, do not know whether other solution is relevant to some efficiency.

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
