### ISSUE TITLE
Exercise 6--Modular Befuddlement

### ISSUE THREAD

**Issue by anonRegions** [nodeschool/discussions#1258]
I. Here's my main (calling) file:

var dir = process.argv[2];
var ext = process.argv[3];
var ext = '.' + ext;
var fileList = require('./makeItModular_module');

fileList(dir, ext, function(err, data) {
	for (var i = 0; i < data.length; i++) {
		console.log(data[i]);
	}
});

II. And here's my module:

var fs = require('fs');
//load path module
var path = require('path');
//function to be exported, containing 3 args:
//dir name, extension & callback function
var printMod = function (dir, ext, printer) {
	var arr = [];
	//loop thru list, printing each line separately
	fs.readdir(dir, function(err, list) {
		if (err) return printer(err);
		for(var i = 0; i < list.length; i++) {
			if(path.extname(list[i]) === ext) {
				//build arr
				arr.push(list[i]);
			}
		}
		//console.log(arr);
		//call callback function printer, passing results to orig file
		printer(null, arr);
	});
};

module.exports = printMod;

III. Here are my submission results:

                 ACTUAL                                 EXPECTED
───────────────────────────────────────────────────────────────
   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

IV. And here's why it fails:

√ Submission results match expected
√ Additional module file exports a single function
√ Additional module file exports a function that takes 3 arguments
√ Additional module file handles errors properly
√ Additional module file handles callback argument
√ Additional module file returned two arguments on the callback function
√ Additional module file returned correct number of elements as the second argum
ent of the callback
? Your additional module file [makeItModular_module.js] did not return an Array
with the correct number of elements as the second argument of the callback

I've been logging to the console all over the place, but I still can't figure out the source of the objection. Please advise. Thanks.

**Comment by davecocoa** [comment]
Aha, I'm sorry for the confusion here, the exercise feedback is not very clear in this case. The intention is that your main (calling) file will not change the command line arguments (`process.argv`) in any way. If you add the move the line `ext = '.' + ext;` from your main file to your module, it should pass the exercise just fine.

**Comment by anonRegions** [comment]
@davecocoa: That did the trick. Thank you!

**Comment by SomeoneWeird** [comment]
:tada:
