### ISSUE TITLE
Convert time from GMT to localtime

### ISSUE THREAD

**Issue by ahmedsa1983** [nodeschool/discussions#1261]
Hey Guys
I need your help to learn how can I change the time received with data from GMT to local time. I'm sending event from my Spark Core device to the cloud, and then receiving these data on my local PC by using the NodeJS on the command line. The issue is that I'm receiving the Timestamp with my data in console in GMT format while it shoed in the cloud in the local format. How can I change or convert the time from GMT to local to save it in the text file in local format?
Thank in advance
Best.
Ahmed

**Comment by quarterpi** [comment]
Hi @ahmedsa1983,
Have you tried ```toLocalString()```? If you just want the Time portion of the UTC string you could try ```toLocalTimeString()``` and if you only want the Date portion, try ```toLocalDateString()```.
I hope this helps.

**Comment by ahmedsa1983** [comment]
Thanks @quarterpi 
Actually, I tried that ,but I didn't know how can I change it.
Here is my code:

https://gist.github.com/ahmedsa1983/ef94c5a37ec982a57ab6

How can I convert the time that is provided by the (published_at) , which is in GMT, to be a locale time?
Thanks in advance.
Ahmed

**Comment by quarterpi** [comment]
I left a suggestion at https://gist.github.com/ahmedsa1983/ef94c5a37ec982a57ab6

Let me know if it helped.

**Comment by SomeoneWeird** [comment]
Reopen if still an issue.
