### ISSUE TITLE
Space between the comma and the next word

### ISSUE THREAD

**Issue by b-a-chua** [nodeschool/discussions#1262]
Hi everyone or anyone, 

This is a question about the 2 of the "Javascripting" exercises. 

In "Scope":
So was this intentional for there to be no space between the last comma and "c:"?

![no_space_after_comma](https://cloud.githubusercontent.com/assets/2820053/8398360/e903c996-1d9f-11e5-99c6-0c4c44721fa8.PNG)

I changed my code so that there's no space between them, just for the sake of passing.  But putting a space between the comma and "c:" just seems to make more sense grammatically and aesthetically.  

In "Functions":
I originally capitalized "bananas" because it was in the beginning of the sentence, but I guess the checking mechanism wanted an exact match?  

![cannot_capitalize_first_letter_of_sentence](https://cloud.githubusercontent.com/assets/2820053/8398423/8c977f06-1da2-11e5-92b0-99ff926a769f.PNG)

Like the other one, I changed it to a small letter just so I can pass the activity.  

Both of these are not a big deal, but I thought you'd like to know.

**Comment by SomeoneWeird** [comment]
Hi! The c: issue was fixed this morning, somebody else filed a PR, so the next version of javascripting shouldn't have that problem. And yes, it's looking for an exact match the solution, so capitalisation will make things not work.

**Comment by b-a-chua** [comment]
Thanks!

**Comment by SomeoneWeird** [comment]
:tada:
