### ISSUE TITLE
troubleshooting error message

### ISSUE THREAD

**Issue by Ptr-E** [nodeschool/discussions#1264]
![screen shot 2015-06-29 at 9 34 21 am](https://cloud.githubusercontent.com/assets/12686936/8412990/3b157a70-1e42-11e5-9971-3d1bd355a122.png)
I have downloaded the pack and has been stored in usr/local/bin but a) i cant find the files b) the following message keeps showing up 

what do I need to do to work with node.js

Thank you

**Comment by sudodoki** [comment]
@Ptr-E could you please try updating npm (by running `npm update -g npm`)

**Comment by Ptr-E** [comment]
Just did, this is the response… see picture

Thank you!

**Comment by SomeoneWeird** [comment]
@Ptr-E can you try installing node through homebrew? Currently you're running into permission errors, homebrew handles all of that, though.

**Comment by Ptr-E** [comment]
So now I have homebrew downloaded. what is the next step? would I re install the node.js package?

Thank you!

**Comment by Ptr-E** [comment]
It still is giving me permission issues. how do I get around that

**Comment by SomeoneWeird** [comment]
Try running `sudo rm -Rf /usr/local/lib/node_modules` to remove the directory, if you then try to reinstall something with npm it should work.

**Comment by Ptr-E** [comment]
I removed used the sudo line and it appears to have worked. Now when I try running npm install -g javascript it tells me files dont exist

Thank you!

**Comment by Ptr-E** [comment]
It still is giving me permission issues. how do I get around that

**Comment by edrickchu** [comment]
try ```-sudo npm install -g javascripting``` from the get-go

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
