### ISSUE TITLE
Real basics......

### ISSUE THREAD

**Issue by GrahamGIGA** [nodeschool/discussions#1265]
I installed atom, and node.js.  Then I ran npm to get the javascripting module.   Solved the sudo issue :-))

But now what?  How do I run the lesson etc?

Cheers

**Comment by dominhhai** [comment]
Go to http://nodeschool.io/#workshopper-list then select a workshop to begin :+1:

**Comment by davecocoa** [comment]
If you already got the `javascripting` module, then you can run it by just typing `javascripting` in the same place you ran `npm`

**Comment by GrahamGIGA** [comment]
Thanks!   Got it :-))

**Comment by SomeoneWeird** [comment]
:tada:
