### ISSUE TITLE
learnyounode isn't recongnized as an internal or external command.

### ISSUE THREAD

**Issue by clsatw** [nodeschool/discussions#1266]
after installing node.js and npm install -g learnyounode,  i get an error as subject when typing learnyounode at command window. please help.

**Comment by dominhhai** [comment]
Are you using Windows?
Tell me more info.

**Comment by clsatw** [comment]
i'm using windows 7. 
node is installed correctly. if i type in "learnyounode" in the node prompt, i get reference Error: learnyounode is not defined. not knowing where went wrong. thanks dominhhai.

**Comment by dominhhai** [comment]
Config your environment variable (`PATH`) like:

```
C:\Users\your_name\AppData\Roaming\npm;C:\Users\your_name\AppData\Local\atom\bin
```

**Comment by jemdkyl** [comment]
You have to add the path to the system variables. I have never used Windows 7 but this link looks about right.

http://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7

**Comment by niravaga** [comment]
I had the same issue and the solution by @dominhhai worked for me. Thanks!
