### ISSUE TITLE
How-To-NPM, publish ECONNREFUSED

### ISSUE THREAD

**Issue by PaulBeaudet** [nodeschool/discussions#1267]
For the publish parts of these lessons I keep getting an "ECONNREFUSED" error. Is publish actually trying throw my test empty project onto a public server? If so, that would seem a bit silly. Also my (not under my control) network router is probably blocking everything except for essential ports.  

The tutorial says you are not creating a real account/package but I see no reason why it would create a fakes given the commands. What is "publish" doing / actually trying to accomplish in the context of lessons 08 and 10?

**Comment by SomeoneWeird** [comment]
ping @linclark

**Comment by Mycroft1891** [comment]
If you did exercise 2 you should have created a fake user which you will NEED to accomplish all the other exercises. 

When you publish your module - npm publish, you are only publishing it to a local file but for that you have to make sure you created a user and that you are logged in.

run:
npm whoami

This should return your username. If you get an error redo exercise 2.

**Comment by howardjones** [comment]
I am getting the same error. I am "logged in" to the fake npm registry (confirmed with `npm whoami`). I am reading this as the fake npm server on localhost isn't listening...

    npm ERR! publish Failed PUT undefined
    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
    npm ERR! node v6.9.5
    npm ERR! npm  v3.10.10
    npm ERR! code ECONNREFUSED
    npm ERR! errno ECONNREFUSED
    npm ERR! syscall connect

    npm ERR! Error: connect ECONNREFUSED 127.0.0.1:15443
    npm ERR!     at Object.exports._errnoException (util.js:1022:11)
    npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
    npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
    npm ERR!  { Error: connect ECONNREFUSED 127.0.0.1:15443
    npm ERR!     at Object.exports._errnoException (util.js:1022:11)
    npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
    npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
    npm ERR!   code: 'ECONNREFUSED',
    npm ERR!   errno: 'ECONNREFUSED',
    npm ERR!   syscall: 'connect',
    npm ERR!   address: '127.0.0.1',
    npm ERR!   port: 15443 }
    npm ERR!
    npm ERR! If you are behind a proxy, please make sure that the
    npm ERR! 'proxy' config is set properly.  See: 'npm help config'

**Comment by howardjones** [comment]
After re-running `how-to-npm` just in case something was timing out, I now get a 404 error instead, but still no love...

    npm ERR! publish Failed PUT 404
    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
    npm ERR! node v6.9.5
    npm ERR! npm  v3.10.10
    npm ERR! code E404

    npm ERR! 404 missing : @anotherhowie/node-learn
    npm ERR! 404
    npm ERR! 404  '@anotherhowie/node-learn' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\Howard Jones\Documents\Code\node-learn\npm-debug.log
