### ISSUE TITLE
Can't run Workshops

### ISSUE THREAD

**Issue by studeo14** [nodeschool/discussions#1269]
I've installed the `git-it` and `how-to-npm` workshops using the `npm install -g` command. When I attempt to run either of the workshops I receive:

`\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);`
 Followed by:
`TypeError: undefined is not a function
    at module.exports...`

Is the install corrupt? Or did I miss a configuration step?

**Comment by SomeoneWeird** [comment]
What version of node do you have installed?

**Comment by studeo14** [comment]
v0.12.4
