### ISSUE TITLE
Juggling Async unexpected output

### ISSUE THREAD

**Issue by Tachii** [nodeschool/discussions#1270]
So here is my code:
```
var http = require('http');
var dataStream = [];
var dataArr = [];
var count = 0;
/*
 Function to print results
 @dataArr - array
*/
function printResults(dataArr) {
  for (var i = 0; i < process.argv.length - 2; i++)
    console.log(dataArr[i]);
}

/*
  Function to get data from http
  @i - int
  Getting command line arguments as parametrs.
*/
function httpGet(i) {
  http.get(process.argv[2 + i], function(res) {

    res.setEncoding('utf8');

    res.on('data', function(data) {
      dataStream.push(data);
    });

    res.on('end', function() {
      dataArr[i] = (dataStream.join(""));
      dataStream = [];
      count++;
      if (count == process.argv.length - 2) {
        printResults(dataArr);
      }
    });

    res.on('error', function(e) {
      console.log("Got error: " + e.message);
    });
  });
}

for (var i = 0; i < process.argv.length - 2; i++) {
  httpGet(i);
}
```

And for some strange reason sometimes if i run:
```learnyounode verify program.js``` 
It show that everything is correct, sometimes it shows that there is an error.

Why can it be happening?

**Comment by davecocoa** [comment]
Your code makes the assumption that the 3 http responses will not overlap - that a `data` event for one response will never occur before the `end` event of the previous response, this is not always the case. I recommend you move the definition of your `dataStream` variable inside your `httpGet` function, this way each request/response will have its own variable and they cannot interfere with each other, regardless of timing.

**Comment by Tachii** [comment]
@davecocoa Thanks for the answer!

I kinda switched my solution a bit:
```
var http = require('http');
var dataArr = [];
var count = 0;
/*
 Function to print results
 @dataArr - array
*/
function printResults(dataArr) {
  for (var i = 0; i < process.argv.length - 2; i++) {
    console.log(dataArr[i].replace('undefined', ''));
  }
}

/*
  Function to get data from http
  @i - int
  Getting command line arguments as parametrs.
*/
function httpGet(i) {
  http.get(process.argv[2 + i], function(res) {

    res.setEncoding('utf8');

    res.on('data', function(data) {
        dataArr[i] += data;
    });

    res.on('end', function() {
      count++;
      if (count == process.argv.length - 2) {
        printResults(dataArr);
      }
    });

    res.on('error', function(e) {
      console.log("Got error: " + e.message);
    });
  });
}

for (var i = 0; i < process.argv.length - 2; i++) {
  httpGet(i);
}
```

But I had a problem.

While adding data to array element, I always had ```undefined``` in the begining of my string.
More info here:
http://stackoverflow.com/questions/31181385/how-to-prevent-undefined-data-string-while-reading-data-from-stream

**Comment by davecocoa** [comment]
Why not put `dataArr[i] = "";` at the start of `httpGet`, this way you'll have an empty string ready to add the data to, instead of attempting to add data to `undefined`.

**Comment by Tachii** [comment]
@davecocoa Indeed, I should try this. Thanks again for the help!

**Comment by SomeoneWeird** [comment]
:tada:
