### ISSUE TITLE
Error when creating a file

### ISSUE THREAD

**Issue by alexandra-pickle** [nodeschool/discussions#1271]
When I try to create a new file 

node program.js

I get an error: 

module.js:338
throw err
Error: Cannot find module 'C:\Users\UserName\program.js'
at Function.Module._resolveFilename (module.js.336.15)
at Function.Module_load (module.js:278:25)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

**Comment by SomeoneWeird** [comment]
You need to create the file `program.js` in another text editor, like Sublime Text or Atom. When you do `node program.js` - it tries to run a file that doesn't exist, which is why you're getting an error.
