### ISSUE TITLE
How to use API docs? (newbie)

### ISSUE THREAD

**Issue by gherson** [nodeschool/discussions#1272]
The solution to learnyounode Exercise 11 includes code
`... http.createServer(function (request, response) { ...`

How would I know that code is possible from the API documentation, https://nodejs.org/api/http.html#http_http_createserver_requestlistener?  It has only
> http.createServer([requestListener])#
> Returns a new instance of http.Server.
> 
> The requestListener is a function which is automatically added to the 'request' event.

`requestListener` is unlinked therein.  Googling `site:nodejs.org/api/ requestlistener` provides a good example but not a straightforward answer to my question.  Thanks in advance.

**Comment by davecocoa** [comment]
You're right that some more linking would help here. The keyword here is not so much `requestListener` as "the `request` event", if you skip down a few sections you will find a description of the `request` event: https://nodejs.org/api/http.html#http_event_request

**Comment by gherson** [comment]
Good to know, thanks.

Does "The requestListener is a function which is automatically added to the 'request' event" mean that the `function (request, response) { ... }` is the requestListener?  If yes, then how do we link a mention of requestListener here to that information?

**Comment by davecocoa** [comment]
Yes, the connection is implied by the language of events and listeners. The name `requestListener` implies a function which will be triggered by the `request` event. Listeners are functions which are called when events happen, they are usually setup or attached using the `on` method, like this:

```js
var eventEmitter = require('some_event_emitter');

function fireListener(fireType){
  // do something about the fire?
}
eventEmitter.on('fire', fireListener);
```

So in this example, if I wanted to know more about the `fireType` argument, I would look for documentation on the `fire` event.

**Comment by gherson** [comment]
Noted.  Thanks.
