### ISSUE TITLE
I wanna learn javascript especially node,after installing all the requirement from node.org what next?

### ISSUE THREAD

**Issue by Robdryl1** [nodeschool/discussions#1275]
I need all the help that I can get please.
Many thanks.

**Comment by SomeoneWeird** [comment]
take a look at the [nodeschool website](http://nodeschool.io)

**Comment by Ntangen** [comment]
Yeah, knowing something about javascript will be really important in getting through Node. I strongly recommend the ["How to Learn Javascript Properly"](http://javascriptissexy.com/how-to-learn-javascript-properly/) self-paced course and the [Code School track.](https://www.codeschool.com/paths/javascript)

**Comment by SomeoneWeird** [comment]
There is also the `javascripting` workshop, which will teach you the basics of javascript.
