### ISSUE TITLE
learnyounode "My First Async I/O" -- I want to understand Asynchronous I/O better than what's in the exercise.

### ISSUE THREAD

**Issue by BerniceChua** [nodeschool/discussions#1277]
Hi everyone,

In learnyounode "My First Async I/O", I was able to complete the exercise, and I understand the concept of Asynchronous I/O and why it is useful from the explanations here:
https://github.com/maxogden/art-of-node
and here:
http://www.nodewiz.biz/your-doing-node-js-wrong-avoid-synchronous-code/
and here:
http://www.toptal.com/nodejs/why-the-hell-would-i-use-node-js

It seems that asynchronous I/O is one of the big features of Node.js, so I want to understand it better.  

I'm a visual learner, so it's easier for me to understand something if I can see the differences or see what goes on, etc.  

So maybe the example in the exercise is too short to really show anything, but I really cannot see any difference between this one, and the synchronous I/O exercise, aside from the difference in the code.  Although I know they are supposed to be different because this current exercise is supposed to be reading the file not continuously.

Is there something else out there that anyone can recommend for me to practice one/read/learn from?  Thanks in advance.

**Comment by Sequoia** [comment]
@BerniceChua does this help? http://plnkr.co/edit/33ihz60jaeC1EFsmN0JL?p=preview
(look at "script.js")
It's a contrived illustration of sync vs. async execution. Let me know if it helps at all!
