### ISSUE TITLE
Exercise 6: Does not export a single function?

### ISSUE THREAD

**Issue by craigrow** [nodeschool/discussions#1278]
My results match the expected results but I'm failing with the message, "? Your additional module file [MakeItModMod.js] does not export a single function. You must use the `module.exports = function () {}` pattern."

Here is my module:

```
module.exports.filteredls = function(dir, ext, callback) {
	fs.readdir(dir, function doneReading(err, files) {
		callback(files)
	})
}
```

Could somebody help me I understand what I've done wrong please?

**Comment by SomeoneWeird** [comment]
Yep, if you remove `.filteredls` you will just export the function. At the moment you're exporting an object like `{ filteredls: function() {} }`

**Comment by craigrow** [comment]
Thanks for the help @SomeoneWeird 

I had to make some other modifications, of course, but got it to pass. :+1:

**Comment by SomeoneWeird** [comment]
Awesome! Open another issue if you need more help.
