### ISSUE TITLE
learnyounode JUGGLING ASYNC

### ISSUE THREAD

**Issue by re-curse-r** [nodeschool/discussions#1279]
There is my solution below. While I try to verify it, it passes all test but the last one. The last test says:
5.ACTUAL: ""
5.EXPECTED:
Why does that happen?
var http = require('http');
var bl = require('bl');
function serve (i) {	
	http.get(process.argv[4 + i],
		function (response) {
			response.pipe(bl(
					function (err, data) {
						if(err)
							return console.error(err);
						var info = data.toString();
						console.log(info);
						if(i > 0) 
							return;
						else
							return serve(i + 1);
					}
				)
			);
		}
	);
};

serve(-2);

**Comment by re-curse-r** [comment]
var http = require('http');
var bl = require('bl');
function serve (i) {
http.get(process.argv[4 + i],
function (response) {
response.pipe(bl(
function (err, data) {
if(i > 0)
return;
if(err)
return console.error(err);
var info = data.toString();
console.log(info);
return serve(i + 1);
}
)
);
}
);
};

serve(-2);

**Comment by re-curse-r** [comment]
I found out the error!
The correct version is above this comment!
:D

**Comment by SomeoneWeird** [comment]
Cool :)
