### ISSUE TITLE
learnyounode TIME 

### ISSUE THREAD

**Issue by re-curse-r** [nodeschool/discussions#1280]
I am using the strftime module to solve this problem, but every time I verify it, it shows a time which is neither the local time nor the GMT. How can I solve this ?

var net = require('net')
var strftime = require('strftime')
var myStrftime = strftime.timezone('+0015')
var server = net.createServer(
    function (socket) {
        socket.write(myStrftime('%F %M:%S'))
        socket.end();
    }
)
server.listen(process.argv[2]);

**Comment by McBrown** [comment]
I used MomentJS, no issues there. Also, documentation is very rich in content.
