### ISSUE TITLE
Callback passing in buffer.

### ISSUE THREAD

**Issue by matt-mcdaniel** [nodeschool/discussions#1281]
I'm working on lesson 4, "My first async I/O", and trying to understand how the callback function would operate on an async file read.

I know that I can read from a file asynchronously with `var content = fs.readFile('/path/to/file')`. This is supplied automatically by the lesson as the first and only argument, so I would write `var content = fs.readFile(process.argv[2])`. The lesson says that I should create a callback function of the nature `function callback(err, data)` and that I can check whether or not there is an error, presumably with an `if` statement. My question is how do I "call" the function. I tried to something like this:

```
var fs = require('fs');

var content = fs.readFile(process.argv[2]);
content(function(err, data) {
    if (err) {
        console.log(err);
    } else {
        var str = data.toString();
        var arr = str.split('\n');
        console.log(arr.length - 1);
    }
});
```

I'm not sure how to attach the callback in this case. Can someone help point me in the right direction?

**Comment by SomeoneWeird** [comment]
When you call asynchronous functions you have to pass a function as an argument

```js
fs.readFile(process.argv[2], function(err, data) {
   // check for err etc
});
```

**Comment by truckfondue** [comment]
I too am having a difficult time with this challenge. As it stands now, I have:

var fs = require('fs');

fs.readFileSync(process.argv[2], function(err, data) {
	// if (err) {
	// 	console.log(err);
	// } else {
	// 	var words = data.toString().split('\n');
	// 	console.log(Number(words.length - 1));
	// }
	str = process.argv[2];
	buf = new Buffer(str);
	arr = buf.split('\n')
	console.log(arr.length-1);
	

});

I suppose that I don't wuite grasp how to connect 'process.argv[2]' to the data argument of the callback?
