### ISSUE TITLE
Stuck on "My First I/O" of LearnYouNode

### ISSUE THREAD

**Issue by jspring1** [nodeschool/discussions#1283]
I can't seem to get the solution to verify on section 3 of Learnyounode.  Here's the code that I've written so far: 
```    
    var fs = require('fs');
    var buf = fs.readFileSync(process.argv[0]);
    var str = buf.toString();
    var strAr = str.split('/n');
    console.log(strAr.length - 1);
```

When I run this using `learnyounode run program.js` , I consistently get the answer '65', but this doesn't seem to be the answer that the program is looking for when I run `learnyounode verify program.js`.  In fact, the verify answer seems to change each time I run the verify.  The expected answer can change every time.  10, 18, 40, etc.  Not sure how I'm supposed to get the correct number of lines, if the answer changes each time.  Does anyone have any insight into what I'm doing wrong?  Where in my code have I messed up?  Thank you!

**Comment by sudodoki** [comment]
Answer changes everytime because input text is changing with each call to make sure people just don't hardcode the value. It's usually off by one issue because of `\n` positioning

**Comment by jspring1** [comment]
Thanks sudodoki.  I guessed that the program might be changing the file size every time to discourage people from cheating.  But then why is my program always returning '65'?  Shouldn't it change too?  It's not just off by one from the expected answer.

**Comment by SomeoneWeird** [comment]
`process.argv[0]` is always `"node"`, `process.argv[1]]` is always the path to your process, user supplied arguments start at `process.argv[2]` - you need to use that.

**Comment by jspring1** [comment]
Using `process.argv[2]` doesn't seem to help either.  

```javascript
var fs = require('fs');
var buf = fs.readFileSync(process.argv[2]);
var str = buf.toString();
var strAr = str.split('/n');
console.log(strAr.length - 1);
```

Yields this result:
`C:\Users\Joel>learnyounode run program.js`
`0`

**Comment by jspring1** [comment]
Ha! It was a typo on the newline delimiter.  

I had used `/n` when I should have used `\n`.  Go figure.
