### ISSUE TITLE
Puzzling Over Filtered-LS (learnyounode)

### ISSUE THREAD

**Issue by grampers** [nodeschool/discussions#1284]
I have a solution that works with node but won't verify.  Appreciate a look and comments.

My 'solution'
var fs = require('fs');
var path = require('path');
function filter_by_type(item){
if (path.extname(item) === ',' + process.argv[3]{

**Comment by grampers** [comment]
Sorry - I'll try again:
My 'solution'
var fs = require('fs');
var path = require('path');
function filter_by_type(item){
if (path.extname(item) === '.
' + process.argv[3]{
return item;
}
fs.readdir(process.argv[2],function(err,list){
if (err) throw err;
console.log(list.filter(filter_by_type));
});
The errors:    "[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]" !=    "CHANGELOG.md"                     
   ""                                  !=    "LICENCE.md"                       
                                       !=

**Comment by jkbits1** [comment]
@grampers thanks for letting us know how you're getting on :+1: 

Your code is almost there, one more step is needed to pass verification. As it is now, the code prints out the results as an array (the array returned by filter). The verification stage is expecting each file to be printed individually using console.log().

Does that help to suggest the next step to take?

**Comment by grampers** [comment]
Thanks for that Jon - guess I didn't hoist in that aspect. But now I have,
and it all works!

**Comment by jkbits1** [comment]
@grampers that's great :tada: 

I'm really glad I was able to help and that you are enjoying the workshop. If you are done with this issue, it will help the organisers if you close it. If you have more questions, though, it's fine to keep it open and ask those, too.

Please do ask more questions and open new issues as you go through the tutorial, they are always welcome ! :smile:
