### ISSUE TITLE
Node.js Baby Steps problem

### ISSUE THREAD

**Issue by EduardoCHenrique** [nodeschool/discussions#1285]
Hi, i have a question about this lesson. I've got the correct return but it is not a valid answer. Thats my code: 

``` js
function soma(){
        var sum = 0;
        for(var i = 1; i<process.argv.length; i++){
                if(i>1){
                        sum+=parseInt(process.argv[i]);
                }
        }
        console.log(sum);
        return sum;
}
soma();
```

Its Working but the system doesnt let me go to the next lesson. =/ You know why?

Tks,
PS: Really aprreciate the project guys, thats awesome!

**Comment by davecocoa** [comment]
Can you explain what you mean by Working? The system won't mark this as solved because, as you've written it here, it doesn't solve the given exercise, it throws an error on the third line.

**Comment by C00kie-** [comment]
isn't your return sum useless at the end of your function, in case of you did'nt called it as a parameter ? I don't know I come from C language :)

**Comment by Ntangen** [comment]
Looks like you might be overthinking it. You don't need the return there, since you've already spit out sum to console.log. This doesn't even need to be a function, and if you just start the for loop with i=2 (i.e. process.argv[2], you can get rid of the if statement too.
