### ISSUE TITLE
Are there any good tutorials to understand how to make it modular?

### ISSUE THREAD

**Issue by segmentationfaulter** [nodeschool/discussions#1287]
I am new to node and finding difficulty with "MAKE IT MODULAR" exercise, can anybody suggest a reading to understand the concepts involved?
Thank you!

**Comment by b-a-chua** [comment]
I found these to be useful:

http://www.sitepoint.com/understanding-module-exports-exports-node-js/

http://stackoverflow.com/questions/26407593/difference-between-using-a-module-pattern-and-instantiating-new-objects

http://stackoverflow.com/questions/22906662/javascript-design-pattern-difference-between-module-pattern-and-revealing-modul

http://stackoverflow.com/questions/11764313/what-is-the-difference-between-modules-in-js-and-classes-in-php

http://stackoverflow.com/questions/7137397/module-exports-vs-exports-in-node-js

https://blog.tableflip.io/the-difference-between-module-exports-and-exports/

Hope that helps. ^_^
