### ISSUE TITLE
http://nodeschool.io/ Belgium

### ISSUE THREAD

**Issue by stijncalis** [nodeschool/discussions#1289]
Hi,

Is there anyone aware of nodeschool workshops in Belgium? What parties are needed to start or supporting workshops? I think it would be received very well.

Stijn

**Comment by SomeoneWeird** [comment]
If you find another person or two that lives in belgium and want to help, you can start your own nodeschool chapter there :)

**Comment by bojoer** [comment]
This is an old(er) discussion but I was looking for NodeSchool Belgium and am interested in helping to create, host and provide workshops in Belgium so if there is still some interest let it know here.

Kind Regards!

**Comment by stijncalis** [comment]
Aha, ok, great news! Still interest, yes
