### ISSUE TITLE
Just created a nodeschool subreddit! Also: Approach to fix Getting-Started barriers

### ISSUE THREAD

**Issue by cookiengineer** [nodeschool/discussions#1291]
Hey guys,

we founded the nodeschool Mannheim and nodeschool Heidelberg around here in Germany. We had a couple of issues getting started and getting people to actually start programming. The issue was most likely related to the lack of bash scripting skills and setup issues. And, I think, in modern age of programming - most people aren't used to an ncurses-like application.

Also, there was no central point for people to go to when they have questions. So we started a little nodeschool telegram chat and a subreddit.

In case anyone wants to join, you are very much welcome. If you want to help out as a mod, say so :)
- [https://www.reddit.com/r/nodeschool/](https://www.reddit.com/r/nodeschool/)

Also, what we wanted to ease up is the getting started process. I'm currently coding a little prototype for a workshopper-server variant where you can host a webserver that "compiles" the code serverside (and checks it).

For now, the idea is to use Rasbian, install the nodeschool-server.deb on it and have a ready-to-use access point setup that other people can connect to. So they can start coding immediately in their web browser (well, or see a fancy step-by-step guide that helps them setup nodejs / iojs).

What do you think about the idea?

**Comment by SomeoneWeird** [comment]
I'm +0 leaning towards -1 for the subreddit. I think it would be a good idea if there was nowhere to go to ask questions, but we have this discussions repository for exactly that - I just think it may be a bad idea to segregate the community.

**Comment by finnp** [comment]
> Also, there was no central point for people to go to when they have questions.
That's the purpose of this repository as well as the gitter chat. If people want to use reddit, that's fine. But most meetups are referring this repo, which generally has the best chances of getting help.
