### ISSUE TITLE
Incorrect characters in cmd

### ISSUE THREAD

**Issue by oleole90** [nodeschool/discussions#1293]
Simply installed learnyoureact from cmd. Ran it then this issue apeared. Changed the font from 
Properties>Font, no effect.
System: Windows 7 (64bit)

![image](https://cloud.githubusercontent.com/assets/4123376/8637713/04bd2b64-28c2-11e5-8ef6-b7faf2706e30.png)

**Comment by SomeoneWeird** [comment]
Strange, what version of node and learnyoureact do you have installed?

**Comment by oleole90** [comment]
Version:**0.9.8**
Git bash also has the same issue.

**Comment by SomeoneWeird** [comment]
What version of node do you have installed?

**Comment by oleole90** [comment]
**v0.10.24**
(Sorry, missed that part.)

**Comment by SomeoneWeird** [comment]
Can you try updating to 0.12 and see if the issue still occurs?

**Comment by oleole90** [comment]
Dude! Nevermind! Deafult selected language wasn't English!
![image](https://cloud.githubusercontent.com/assets/4123376/8644761/9c995b32-2963-11e5-98ad-e3f95a3ab8f7.png)

After selecting English everything is great now. Thanks for your time!

**Comment by tako-black** [comment]
In v0.9.9, I changed the default selected language to English.
I think this problem has been fixed.

Could someone close this issue, please?
