### ISSUE TITLE
Clear console after start javascripting

### ISSUE THREAD

**Issue by daniel1302** [nodeschool/discussions#1295]
Hi, I installed nodeJS, npm, javascripting, workshopper and i have problem with start javascripting tutorial. I'm using Linux Ubuntu 15.

When i run command 
![zrzut ekranu z 2015-07-14 22 16 56](https://cloud.githubusercontent.com/assets/1239637/8683961/1465dea2-2a76-11e5-8420-85b34168c589.png)

This problem is in all lessons, How to run lesson and how to fix it?

**Comment by SomeoneWeird** [comment]
Try following the commands [here](https://github.com/nodeschool/discussions/issues/190#issuecomment-34568209) to install the latest version of node.

**Comment by daniel1302** [comment]
Ok thanks i forgot about this post. I found sollution. I installed the least version of node from source code. NPM couldnt update self and node. This topic is to close. Thanks

**Comment by SomeoneWeird** [comment]
Sorry it took so long to reply! Glad it's working now though :tada:
