### ISSUE TITLE
Trouble installing Node.js

### ISSUE THREAD

**Issue by Tachxz** [nodeschool/discussions#1297]
I'm just trying to run the install and I'm getting the following:
- /usr/local/lib/node_modules/npm/AUTHORS
  logout

Can someone point out what I'm doing wrong, I'll appreciate the help.

**Comment by SomeoneWeird** [comment]
What are you doing exactly?

**Comment by Tachxz** [comment]
I am using the homebrew method and I'm getting not link message

**Comment by Tachxz** [comment]
now I also got this one after trying a second time:

brew link node
Linking /usr/local/Cellar/node/0.12.7... 
Error: Could not symlink include/node/android-ifaddrs.h
Target /usr/local/include/node/android-ifaddrs.h
already exists. You may want to remove it:
  rm '/usr/local/include/node/android-ifaddrs.h'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node

**Comment by SomeoneWeird** [comment]
Well, I have no idea where `android-ifaddrs.h` is coming from, but i'm pretty certain it's not node.

**Comment by Tachxz** [comment]
I try uninstalling but I get the same results

**Comment by SomeoneWeird** [comment]
Do you have the android-sdk install with brew by any chance?

**Comment by Tachxz** [comment]
I think androidsfades.h is just the first directory that is targeting to link

**Comment by Tachxz** [comment]
I don't think so, or I don't know , it is that include in the package from the homebrew site?
