### ISSUE TITLE
node installation without npm and path

### ISSUE THREAD

**Issue by ngodoy2015** [nodeschool/discussions#1298]
My pc has windowws 7 as OS. I've installed node from your page in my pc. To proof it, I ran cmd command and type node. The window showed ">" symbol. Then I typed "node -v" and appears an error message: node is not defined. Same situation ocurred with npm. Message npm is not defined  appears.
What did i make wrong? 
Thanks

**Comment by SomeoneWeird** [comment]
What page did you install node from?
