### ISSUE TITLE
4/13 - MY FIRST ASYNC I/O! Workshop learnyounode error verify 

### ISSUE THREAD

**Issue by 123blog** [nodeschool/discussions#1299]
Khi tôi chạy `learnyounode run io-not-sync.js` thì nhận được kết quả là 7. Nhưng khi tôi chạy `learnyounode verify io-not-sync.js` thì kết quả lại sai! Tôi thì mới bắt đầu với nodejS. Vui lòng xem giúp tôi.

File program.js

``` js
sum = 0;
length = process.argv.length;
for (i = 2; i<length; i++)
{
  sum += Number(process.argv[i]);
}
console.log(sum);
```

File io-not-sync.js

``` js
var fs = require('fs');
fs.readFile('program.js','utf8',function callback(err, data){
    if(err) throw err;
    var count = data.split('\n').length - 1;
    console.log(count);
});
```

**Comment by cristianhosu** [comment]
Verify has it's own testing data. when you use run i believe it does not enforce the data, and it runs with your file "program.js" as test. Verify will use it's own file and assert the results.
instead of 'program.js' get the file from process.argv
