### ISSUE TITLE
Help with learnyounode exercise 13

### ISSUE THREAD

**Issue by konejoo387** [nodeschool/discussions#1301]
Cant figure out this part:

"Add second endpoint for the path 'api/unixtime' wich accepts the same query string but returns UNIX epoch time in milliseconds"

I know that the require('url').parse(request.url , true) returns: 

{
protocol: null,
slashes: null,
.
.
.
pathname: '/api/parsetime',
path: 'api/parsetime?iso=2015-07-16T00:41:51.101Z',
href: 'api/parsetime?iso=2015-07-16T00:41:51.101Z' }

i dont know where to add the "second endpoint". I've already have that unix time in a variable but dont know how to proceed, here's my code:
______________________________________________________________
var http = require('http');

http.createServer( function(request , response){
	
	if(request.method != "GET"){
		return response.end('Send me a GET!');
	}
	else {

		var path  = require('url').parse(request.url , true).pathname;
		var q     = require('url').parse(request.url , true).query.iso; 
		
		var date = new Date(q);
		var unix = date.getTime();
		
		var J = {
			
			"hour"   : date.getHours(),
			"minute" : date.getMinutes(),
			"second" : date.getSeconds()
			
		} 

		var U = {
			"unixtime" : unix
		}
		
		response.writeHead(200, {
			'Content-Type': 'text/plain' 
		});
		
		response.end(JSON.stringify(J));
		//console.log(require('url').parse(request.url));
	}

}).listen(process.argv[2]);
______________________________________________________________________
*.- And i'm confused because it gives me this output in the console... twice:

{"hour":11,"minute":51,"second":20}
{"hour":11,"minute":51,"second":20}

**Comment by jupmorenor** [comment]
just verify if the pathname is parsetime or unixtime to do what is correct in each case, the tests includes 2 messages, one for each case, you are processing both messages in the same way, so it prints the same.

**Comment by konejoo387** [comment]
Thanks :D! it worked!

**Comment by SomeoneWeird** [comment]
:+1:
