### ISSUE TITLE
Exercise 6: Make It Modular - Does not export a single function

### ISSUE THREAD

**Issue by jonathantzh** [nodeschool/discussions#1304]
Encountered an issue with Exercise 6: Make It Modular. Here's my code:

filterlist.js:
```js
listmodule = require('./listmodule.js');
var listdir= process.argv[2];
var extStr = process.argv[3];

listmodule(listdir, extStr, function(err, data) {
    if (err) {
        return console.log(err)
    }
    else {
        console.log(data);
    }
})
```
listmodule.js:
```js
var fs = require('fs');
var path = require('path');
var data = '';

module.exports = function(listdir, extStr, callback){
    fs.readdir(listdir, function(err, list) {
        if (err) {
            return callback(err);
        }
        for (i=0; i<=list.length-1; i++) {
            if (path.extname(list[i]) == '.' + extStr) {
                data = data + list[i] + '\n'
            }
        }
        callback(null, data);
    })
}
```

My results match the expected results but I'm failing with the message, "? Your additional module file [filterlist.js] does not export a single function. You must use the module.exports = function () {} pattern."

Any help would be appreciated, thanks!

**Comment by youngdeer** [comment]
the second argument of callback 'data' must be a array!

**Comment by jimbolatte** [comment]
I am having the exact same problem. Somehow the "verify" routine does not recognize the correct module file, but erroneously assumes the main file (here: filterlist.js) to export the filter function.

The official solution is pretty much identical to my solution, but does not verify as well. 
I am not proficient enough to debug the verify routine....

**Comment by jonathantzh** [comment]
Thanks for your replies! 

@youngdeer: I attempted initializing the data variable as an array but the same error shows up (i.e. `var data = []`). Maybe it's something to do with what jimbolatte mentioned.

@jimbolatte: Yes, I just attempted the official solution and you're right, the same error shows up.

**Comment by jimbolatte** [comment]
I am going to move past this, because I'm confident my solution behaves correctly. Though it would be nice if someone fixed this bug.

**Comment by jonathantzh** [comment]
Great, same here. :)

**Comment by SomeoneWeird** [comment]
@jonathantzh Which solution did you test? I just looked at the official solution and it passes for me.

**Comment by jonathantzh** [comment]
Strangely, re-attempting the official solution worked this time (after restarting node.js). Thanks for testing it out.

Also, reusing my original solution yielded a different result:
![image](https://cloud.githubusercontent.com/assets/10126769/8827743/ffbdfd58-30c0-11e5-987f-3c06b8201756.png)

Which leaves the conversion to an Array as suggested by @youngdeer. I'm ready to close the issue once @jimbolatte is able to sort out his issue with the original solution.

Thanks everyone for your inputs.

**Comment by SomeoneWeird** [comment]
Very strange. If this happens to anyone else too we'll look into it more closely.

**Comment by jimbolatte** [comment]
I should have mentioned that I was working under Windows 7 x64.
```C:\>node -v
v0.12.7```

The official solution does not verify as is:

```
C:\Users\me\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\solution>learnyounode verify solution.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✗ Your additional module file [solution.js] does not export a single function. You must use the `module.exports = function () {}` pattern.

# FAIL

Your solution to MAKE IT MODULAR didn't pass. Try again!

There was an error: { [Error: ENOENT, scandir 'C:\Users\me\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\solution\verify']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\exercises\\make_it_modular\\solution\\verify' }
```
However if I copy both solution files to another directory (e.g c:\temp), verification happens without error. 


Also tried on Linux Mint 17.1 with the same version 0.12.7 of Node. It behaves correctly and verifies.

**Comment by vlad373** [comment]
The expression "module.exports" should be on the first line of your module and all the requirements inside the brackets.

**Comment by vlad373** [comment]
The exercise is not bugged.
![makeitmodular](https://cloud.githubusercontent.com/assets/13435199/8849938/0faea964-3144-11e5-85bd-494016540615.png)

**Comment by eveningkid** [comment]
I think there's clearly something wrong with this exercice's intructions. If so many people are getting lost, maybe reformulate the whole thing might help future learners...

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
