### ISSUE TITLE
Question to learnyounode Time Server Exercise

### ISSUE THREAD

**Issue by iuvbio** [nodeschool/discussions#1305]
Hi, I have a question to the Time Server exercise. 

This is my code:

    var net = require("net");

    function date () {
    var today = new Date();
    var dd = today.getDay;
    var mm = today.getMonth + 1;
    var yyyy = today.getFullYear;
    var hh = today.getHours;
    var min = today.getMinutes;
    
    if (dd < 10) {
        dd = "0" + dd;
    };

    if (mm < 10) {
        mm = "0" + mm;
    };

    if (hh < 10) {
        hh = "0" + mm;
    };

    if (min < 10) {
        min = "0" + min;
    };

    today = yyyy + "-" + mm + "-" + dd + " " + hh + ":" + min + "\n";
    return today;
    };

    var server = net.createServer(function (socket) {
    socket.end(date());
    });

    server.listen(process.argv[2]);

After looking at the solution I know that there is definitely a better way to do this, but I don't understand why my code doesn't produce the same result.

Also, I don't understand the `(i < 10 ? "0" : '')` in the solution. I know what it does but I've never seen this before. Can someone explain what the ? and the : do?

Thanks for any help.

**Comment by SomeoneWeird** [comment]
`(i < 10 ? "10" : "")` is equivalent to
```js
if(i < 10) {
  return "10";
} else {
  return "";
}
```

Take a look at the docs for the [ternary operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

**Comment by iuvbio** [comment]
Thanks!

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by iuvbio** [comment]
It shouldn't really be closed yet though, since the main part of my question is still unanswered. Why did my code not return the same result as the solution?

**Comment by SomeoneWeird** [comment]
Oh, my bad! I didn't read your question properly. So, things like `getDay` and `getMonth` on a Date object are actually functions, which means you have to call them. Does that help? :)

**Comment by iuvbio** [comment]
Yes, how stupid of me I forgot the brackets. Thanks a lot. Still, after fixing this I get

       "2015-07-06 16:01"                  !=    "2015-07-18 16:01"                 
       ""                                  ==    ""                                 

so something seems to be wrong with my day. Any ideas?

**Comment by SomeoneWeird** [comment]
Yep, you're just calling the wrong function - [getDay](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) vs [getDate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate)

**Comment by iuvbio** [comment]
Ahh.. that doesn't really make sense, but it works. Thank you.

**Comment by SomeoneWeird** [comment]
`getDay` returns the day of the week 0-6 (Sunday to Saturday if i recall correctly) - to get the actual date you have to use `getDate`

**Comment by iuvbio** [comment]
Got it, thank you!
