### ISSUE TITLE
newbie: errors on verify

### ISSUE THREAD

**Issue by walshlg** [nodeschool/discussions#1306]
this is new to me using windows 8.1, command prompt is quite foreign!

I think I have things installed properly, got the javascripting tutorial running, used wordpad to make introduction.js but when I try to verify I get an error:

C:\Users\Lyle\javascripting>javascripting verify introduction.js
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "node "C:\Users\Lyle
\javascripting\introduction.js""
C:\Users\Lyle\javascripting\introduction.js:1
(function (exports, require, module, __filename, __dirname) { {\rtf1\ansi\ansi
                                                               ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "node "C:\\Users\\Lyle\\javascripti
ng\\introduction.js""' }

I am at a loss on how to procede.

**Comment by SomeoneWeird** [comment]
What's in your `introduction.js` file?

**Comment by walshlg** [comment]
Figured it out :  DO NOT USE WORDPAD in windows - it uses rich text format and saves all sort of gibberish in the file!  If you are using windows use ONLY a text editor such as Notepad.

THanks for your quick help

**Comment by SomeoneWeird** [comment]
Ah yes, that would cause it. I would recommend looking into a proper editor too, maybe something like [atom](http://atom.io). :tada:
