### ISSUE TITLE
learnyounode excercise 13 JSON

### ISSUE THREAD

**Issue by iuvbio** [nodeschool/discussions#1307]
Hi I have a question to the "model" solution of the last exercise. I got to the solution myself and my code works fine and returns the expected result. But I'm unsure about some of the code used in the solution give in the program. Specifically these:

     if (/^\/api\/parsetime/.test(req.url))
        result = parsetime(time)
      else if (/^\/api\/unixtime/.test(req.url))
        result = unixtime(time)

I don't understand the conditions here. For comparison my code looks like this and works fine:

    if (req.method === "GET" && reqUrl.pathname === "/api/parsetime") {
        result = isotime(time);
    }
    else if (req.method === "GET" && reqUrl.pathname === "/api/unixtime") {
        result = unixtime(time);
    };

Furthermore, what does the `if (result)` at the end do?

Thanks for the help.

**Comment by drd13** [comment]
The answer they propose uses regex objects, the code  / / creates a regex object, and test is a regex method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

**Comment by iuvbio** [comment]
Ah ok, thanks that already helps. But could you explain to me what the backslashes and the ^ are used for? And what the `if (result)` at the end does? I mean what's the condition here?

**Comment by SomeoneWeird** [comment]
The backslashes are used to escape the other slashes, so they don't end the regex prematurely. The ^ is used to signify the start, so `/^hello/` will match `hello world` but not `world hello` (because it's not at the start).

`if (result) {` is basically `if(result == true) {`

**Comment by iuvbio** [comment]
Thank you, got it! :)
