### ISSUE TITLE
Exercise 8 problem with string concatenation

### ISSUE THREAD

**Issue by divyesh2506** [nodeschool/discussions#1308]
I wrote 2 solutions, but the first one does not work .Could you please guide me, why the first solution does not work properly
The 2 solutions are as follows:-
1

```javascript
 fs=require('fs')
http=require('http')
var count=0
var str=''
function collector(){
	http.get(process.argv[2],function (response){
		response.setEncoding('utf8')
		response.on('data',function(data){str.concat(data)})

		response.on("end",function(){
			console.log(str.length)
			console.log(str)			
		})	
	})
}
collector()

```

The above solution gives a length of 0
and no output is produced while printing the data

2
```javascript
fs=require('fs')
http=require('http')
var count=0
var result=[]
function collector(){
	http.get(process.argv[2],function (response){
		response.setEncoding('utf8')
		response.on('data',function(data){
			result.push(data)
		})

		response.on("end",function(){
			var ans=result.join('');
			console.log(ans.length)
			console.log(ans)
		})	
	})
}
collector() 
```

This one works fine
So, in short using the String concatenation creates a problem , whereas appending elements in an array is not a problem. Why?

**Comment by davecocoa** [comment]
I think you may have misunderstood how the `concat` method works. It does not change the string you call it on, it simply returns a new string. No matter how many times you call `str.concat(data)`, `str` will remain the same. I think what you want to do is `str = str.concat(data)`. I don't think there's any string method equivalent to the array `push` method.

**Comment by divyesh2506** [comment]
Okay I get it now!
I just misunderstood the concat function.
