### ISSUE TITLE
I followed the OS X instructions but getting lot of errors in terminal trying to install git-it! 

### ISSUE THREAD

**Issue by aleith** [nodeschool/discussions#1309]
I installed Git for OS X and despite the instructions saying select the 'install command line tools option" i wasn't presented with that choice. none the less I can issue git commands in terminal. (not that I know which ones to issue). and I have node install with npm and node is working fine.

anyhow when i attempt installation of a tutorial I get a bunch of errors and I'm not sure where to go next.
https://www.dropbox.com/s/dpazagbuzlu36ty/Screenshot%202015-07-20%2011.35.15.png?dl=0
npm ERR! tar.unpack untar error /Users/aleith/.npm/git-it/1.6.8/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "git-it"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/git-it
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/git-it'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/git-it']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/git-it',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/git-it',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aleith/npm-debug.log

**Comment by jesstelford** [comment]
You have a permissions error because `/usr/local/lib` is owned by the Administrator account on OSX, but npm wants to install its modules there.

Based on "Option 2" of [the instructions here](https://docs.npmjs.com/getting-started/fixing-npm-permissions), you should be able to fix the permissions like so:

```
mkdir ~/npm-global
npm config set prefix '~/npm-global'
echo 'export PATH=~/npm-global/bin:$PATH' >> ~/.profile
source ~/.profile
```

Then test it by trying the installation again:

```
npm install -g git-it
```

**Comment by aleith** [comment]
Okay thanks heaps. I followed the through the whole video. The first instruction to do a recursive `chowd -R usr/local/` didn't seem to work but everything after that went well. 

I think I have git-it tutorial installed okay now here's the install log 
npm WARN engine github-oauth@0.0.4: wanted: {"node":"v0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/Users/aleith/npm-global/bin/git-it -> /Users/aleith/npm-global/lib/node_modules/git-it/git-it.js
git-it@1.6.8 /Users/aleith/npm-global/lib/node_modules/git-it
├── marked@0.3.3
├── github-oauth@0.0.4 (request@2.12.0)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── concat-stream@1.2.1 (bops@0.0.6)
├── ecstatic@0.5.8 (mime@1.3.4, minimist@1.1.1, he@0.5.0)
├── cheerio@0.17.0 (entities@1.1.1, lodash@2.4.2, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.7.3)
├── request@2.30.0 (aws-sign2@0.5.0, forever-agent@0.5.2, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.3, tough-cookie@0.9.15, http-signature@0.10.1, hawk@1.0.0, form-data@0.1.4)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── workshopper-jlord@0.0.6 (map-async@0.1.1, tuple-stream@0.0.2, split@0.2.10, through@2.3.8, mkdirp@0.3.5, optimist@0.6.1, colors-tmpl@0.1.1, xtend@2.1.2, terminal-menu@0.2.0, msee@0.1.1)

**Comment by SomeoneWeird** [comment]
Yep! That worked, you should be able to run `git-it` now

**Comment by aleith** [comment]
thanks for your help I didn't think to go back to npm site for help, was a couple of weeks ago I installed node.js. :-)
