### ISSUE TITLE
COMMAND-LINE ARGUMENT

### ISSUE THREAD

**Issue by youngdeer** [nodeschool/discussions#1310]
when I learn my first I/O ，it say 'the full path to the file to read will be provided as the first command-line argument' , so how can I see the command-line argument? anyone can help me ?

**Comment by SomeoneWeird** [comment]
The command line arguments are put into `process.argv`, it's an array - the first item in the array is always `node`, the second item is the path of your node file, and the third item forward are the command line arguments you want.

**Comment by youngdeer** [comment]
thanks Weird!
