### ISSUE TITLE
Make it modular problem

### ISSUE THREAD

**Issue by MatejMatula** [nodeschool/discussions#1312]
Hi , im trying to solve make it modular exercise . here is my code 

module.js 
```js
module.exports = function (one, two, callback) {
    var fs = require("fs");
    var path = require("path");
    var konc = "." + two;
    fs.readdir(one, function (err, list) {
        if (err) return callback(err);
        var list = list.filter(function (x) {
            return path.extname(x) == konc;
        });
        callback(null, list)
    })
}
```

and world.js
```js
var module=require("./module.js");
module(process.argv[2],process.argv[3],function(err,list){
if(err) return console.log("error",err);
list.forEach(function(v){
	console.log(v)
})
})
```
but it results in erro = 
? Submission results did not match expected!
? Did not use an additional module file, you must require() a module to help sol
ve this exercise

# FAIL

it says i did not include module while i did. where is the problem? Thanks for answers

Your solution to MAKE IT MODULAR didn't pass. Try again!

**Comment by unrar** [comment]
On `module.js` remove the `var`:

```
        list = list.filter(function (x) {
            return path.extname(x) === konc;
        });
```
Remember that you use the keyword `var` when you're defining a variable, but here you're using an already defined variable as it's an argument.

I can also see a few missing semicolons.

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
