### ISSUE TITLE
Learnyounode #2: Baby Steps

### ISSUE THREAD

**Issue by TSchnaars** [nodeschool/discussions#1313]
Hi nodeSchool,

I wanted to see if you could give me some insight into why this code is not passing on Lesson #2: Baby Steps
```````
var args = process.argv;
var count = 0;
for (var i = 2; i < args.length; i++) {
	count += Number(args[i]);
	console.log(count);
}
```````
Thanks a bunch!

**Comment by SomeoneWeird** [comment]
Very close, you only need to log the final count. Your `console.log` is in the for loop, which means it will be executed each time, if you move it outside of the for, it should pass.

**Comment by TSchnaars** [comment]
Thanks @SomeoneWeird 
That did work!
Have a groovy day!

**Comment by SomeoneWeird** [comment]
:tada:
