### ISSUE TITLE
Cannot GET /home

### ISSUE THREAD

**Issue by ankitverma2211** [nodeschool/discussions#1317]
Why this is hapenning

**Comment by SomeoneWeird** [comment]
What is your code?

**Comment by ankitverma2211** [comment]
The code is :

var express = require('express');
var app = express();
app.get('/',function(req,res){
        res.end("Hello World!");
});

app.listen(process.argv[2]);

Althoughg I got my mistake :

' / ' should be ' /home '

**Comment by SomeoneWeird** [comment]
Yep! :tada:
