### ISSUE TITLE
beginner stuck on objects lesson

### ISSUE THREAD

**Issue by walshlg** [nodeschool/discussions#1321]
its probably something obvious but I just can't see what I am doing wrong.  Here is objects.js that i made for the objects lesson in javascripting
```js
var pizza = (
	toppings: ['cheese', 'sauce', 'pepperoni'],
	crust: 'deep dish',
	serves: 2
);
console.log(pizza);
```
here is my error message:  - do I need to specify toppings, etc, as variables too perhaps??
```
C:\Users\Lyle\javascripting>javascripting verify objects.js
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "node "C:\Users\Lyle
\javascripting\objects.js""
C:\Users\Lyle\javascripting\objects.js:2
        toppings: ['cheese', 'sauce', 'pepperoni'],
                ^
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "node "C:\\Users\\Lyle\\javascripti
ng\\objects.js""' }
```

**Comment by SomeoneWeird** [comment]
Ah yeah. Sometimes the font in windows terminals makes things look different, your `(` and `)` should actually be `{` and `}`.

**Comment by walshlg** [comment]
oh my poor old eyes!  Thanks, I figured it must be something simple

I hate the black backgrounds especially with dark text.  That dark blue on
black is almost invisible and the font size doesn't seem to be adjustable
either.  Arrgghh.  enough with the bad colors IMHO.

thanks again

**Comment by SomeoneWeird** [comment]
No problem! Open another issue if you get stuck again :tada:
