### ISSUE TITLE
Stuck on the 6th programming exercise for 'learnyounode'

### ISSUE THREAD

**Issue by wgwz** [nodeschool/discussions#1325]
I am brand new to node and javascript.
Enjoying learning so far. 
The 'learnyounode' program is very nice.

I'm not sure why I am interested in node yet, and as I said I have no experience with javascript.
I just like tinkering, and I have seen that the node.js tool (if it's valid to call it that) seems to be exploding in popularity.
Eventually going to be trying out things like noduino and maybe even play around with the tessel board.  

I will admit I am not entirely comfortable with callbacks yet, if someone asked me to explain it all i could really say is that it tells functions to wait for an async process to finish before evaluating. It still feels confusing, thinking about placement of callbacks, etc.. 

Anyway my current problem is that "Your additional module file [program6.js] does not export a single function." As far as I can tell I am exporting *only one* function. 

Look forward to hearing back on the noob-ness of my code. 

Here is the output of verify on the relevant script
---------------------------

    learnyounode verify program6-couple.js

    Your submission results compared to the expected:

                     ACTUAL                                 EXPECTED                

    "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
    "LICENCE.md"                        ==    "LICENCE.md"                       
    "README.md"                         ==    "README.md"                        
    ""                                  ==    ""                                 

    ✓ Submission results match expected
    ✗ Your additional module file [program6.js] does not export a single function. You must use the `module.exports = function () {}` pattern.

    # FAIL

    Your solution to MAKE IT MODULAR didn't pass. Try again!

Here is program6.js
---------
It looks like I am exporting only one function.

    var fs = require('fs');

    module.exports.directory_sort = function directory_sort(directory, extension){
	
	    var re = new RegExp('.'+extension) ;

	    fs.readdir(directory, function callback (err, list){
		    for (var i = 0 ; i < list.length ; i++){
			    try{
				    console.log(re.exec(list[i]).input);
			    }
			    catch(e){} 
		    }	
	    })
    }

Here is program6-couple.js
---------

    var m = require('./program6');
    var directory = String(process.argv[2]);
    var extension = String(process.argv[3]);

    m.directory_sort(directory,extension);

**Comment by callmeskywalker** [comment]
Here is my latest attempt at solving this, which I think is closer:

    //program6-template.js    
    var fs = require('fs');

    module.exports.directory_sort = function main_function(directory, extension, callback){
	    var re = new RegExp('.'+extension);
	    fs.readdir(directory, function (err,data) {
		    if (err){return callback(err)}
		    for (var i = 0; i < data.length; i++){
			    try{
				    console.log(re.exec(data[i]).input);
			    }
			    catch(e){}
		    }
		    callback(null,data);
	    })
    }

Upon running node interactively and importing the module:

    > var m = require('./program6-template')
    undefined
    > m.directory_sort('/home/kblawlor/code/bronx/node-learn','txt')
    undefined
    > number.txt
    program3.txt
    TypeError: undefined is not a function
        at /home/kblawlor/code/bronx/node-learn/program6-template.js:13:3
        at FSReqWrap.oncomplete (fs.js:95:15)

I realize that I'm not supposed to be printing from the module but that aside, does anyone know why I am getting this error?

**Comment by davecocoa** [comment]
You're calling `directory_sort` without a `callback`.

**Comment by callmeskywalker** [comment]
Do you mean in the module or in the interactive session?

**Comment by davecocoa** [comment]
Both. Also, for this exercise, the idea is that your module would only export the function, so you would just have `module.exports = function main_function(` and `var directory_sort = require('./program6-template')`.

**Comment by callmeskywalker** [comment]
What else is the `module.exports.directory_sort` line exporting? I was under the impression that it would export just the function `main_function`. Is it also exporting things like the regular expression  that are within the function body?

**Comment by davecocoa** [comment]
By default, `module.exports` is an object. So when you do `module.exports.directory_sort`, you are defining a property on that object - you module is exporting an object with a function property. If, on the other hand, you just have `module.exports`, you export just the function.

**Comment by callmeskywalker** [comment]
I will think about that some more, thank you for the information though. It makes more sense now. 

So now if I were to change the line in module to export just the function, then set up an interactive session with `var directory_sort = require('./program6-template')`, `directory_sort` would be the function? So I could then use `directory_sort(some_directory, some_extension)`, but I need to add a `callback` as the third argument in the function?

**Comment by davecocoa** [comment]
Yes, that's it exactly =)

**Comment by callmeskywalker** [comment]
OK, I am sure that I am missing something fundamental here.
Here is the module file:
```
var fs = require('fs');

module.exports = function main_function(directory, extension, callback){
        var re = new RegExp('.'+extension);
        fs.readdir(directory, function (err,data) {
                if (err){return callback(err)}
                for (var i = 0; i < data.length; i++){
                        try{
                                console.log(re.exec(data[i]).input);
                        }
                        catch(e){}
                }
                callback(null,data);
        })
}

``` 
Here is the output from the interactive session:
```
> var directory_sort = require('./program6-template')
undefined
> directory_sort('directory','txt',callback)
ReferenceError: callback is not defined
    at repl:1:61
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
> directory_sort('directory','txt',callback())
ReferenceError: callback is not defined
    at repl:1:61
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
```
What am I missing here? I know I am butchering this and not using callback correctly..

For good measure, here is what happens when I try calling the function, without a callback:
```
> var directory_sort = require('./program6-template')
undefined
> directory_sort
[Function: main_function]
> directory_sort('directory','txt')
undefined
> number.txt
program3.txt
TypeError: undefined is not a function
    at directory:13:3
    at FSReqWrap.oncomplete (fs.js:95:15)
```
The program kind of works as you can see, but it messes up the stdout.

**Comment by davecocoa** [comment]
You need to pass in a function as the `callback` parameter, in the same way as you have `directory_sort('directory','txt')` instead of `directory_sort(directory, extension)`, you need to pass in a function as the callback parameter. Here, try `directory_sort('directory','txt', function(list){console.log(list)})`

**Comment by callmeskywalker** [comment]
I'm pretty lost, I think I need to step back from this for a while. Do you have any suggested references I could read in the mean time? Thanks for all the help thus far, I just need step away from it for a day or two.
