### ISSUE TITLE
Tool used to write the teaching materials?

### ISSUE THREAD

**Issue by marktyers** [nodeschool/discussions#1327]
I have a question regarding the tools you used to create the teaching materials. Are these open source and could they be used to write further teaching packages? If the answer is yes, please can you steer me to the relevant materials?

Cheers

**Comment by SomeoneWeird** [comment]
They sure are. Most of them use [workshopper](https://github.com/workshopper/workshopper), but some use [adventure](https://github.com/substack/adventure) :+1:

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
