### ISSUE TITLE
last exercise in javascripting tut what do the + mean?

### ISSUE THREAD

**Issue by walshlg** [nodeschool/discussions#1328]
last exercise ( on variable scope) 
has the output line

console.log("a: "+a+", b: "+b+",c: "+c);

what do the + mean?  they don't seem to do anything

Second question: are ' and " both equivalent for text?

**Comment by SomeoneWeird** [comment]
`+` when used with strings, is a concatenation, it joins the string together. So if the variable `a` contains the string "hello", and you do `a + "world"` the result will be `"hello world"`.

And yes, in javascript both `'` and `"` are equivalent for text.

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
