### ISSUE TITLE
error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by DennisMatveyev** [nodeschool/discussions#1329]
Hi!
Enter in the command line --> node app
In the beginning answer is --> Listening on port 3000
but then (over 2-3 seconds) the error:
C:\nodeprojects\Express\photo\node_modules\mongoose\node_modules\mongodb\lib\ser
ver.js:228
        process.nextTick(function() { throw err; })
                                                                ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Thanks a lot for helping!

**Comment by SomeoneWeird** [comment]
It looks like you're trying to use mongoose, and it's having trouble connecting to your mongodb server? Do you have one running?

**Comment by DennisMatveyev** [comment]
:) I am idiot ... I did not run mongodb... thank you very much

**Comment by SomeoneWeird** [comment]
:tada: open another issue if you have any more problems
