### ISSUE TITLE
Juggling async

### ISSUE THREAD

**Issue by Bournegit** [nodeschool/discussions#1331]
I am using the following code but the problem is the data are not correctly matched with each other.The code runs but the data of actual and expected are not matching .2nd one matches the first one and so on.

```js
var http=require('http');
var bl=require('bl');

function rahul(callback){

	http.get(process.argv[2],function (response){
	
	response.pipe(bl(function (err,data)
	{
		if(err)
			return console.error(err);
		data=data.toString();
		console.log(data);
		

	}));

});
callback(bhuwan2);
}

function bhuwan1(callback)
{
http.get(process.argv[3],function (response){
	
	response.pipe(bl(function (err,data)
	{
		if(err)
			return console.error(err);
		data=data.toString();
		console.log(data);
		

	}));
callback();
});

}
function bhuwan2(){
http.get(process.argv[4],function (response){
	
	response.pipe(bl(function (err,data)
	{if(err)
			return console.error(err);
		
		data=data.toString();
		console.log(data);
		

	}));

});
}
rahul(bhuwan1);
```

**Comment by MaxSchumacher** [comment]
Hi Bournegit,

The fact that the http.get() functions return at different times is exactly the point, this exercises seeks to illustrate how one can deal with functions that return values asynchronously (an extremely important concept in node.js!).

As I've pondered with this exercise for quite a while myself, I can recommend you take another look at the hint section. It mentions something about a counter.

Your code is currently very redundant, the only thing that changes is the index of that argv-array, a loop could significantly improve readability and make debugging easier.

Best of luck going forward,
Max

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
