### ISSUE TITLE
Nodeschool Organization gone?

### ISSUE THREAD

**Issue by zhdzmn** [nodeschool/discussions#1333]
I dont see myself in the organization anymore. There was an email saying the repo is deleted.
how are we going to look for recovering this?

**Comment by jesstelford** [comment]
Yep, got the same email, so guessing it's not scammy.

Did someone click the big red button by mistake?

Who was the original maintainer?

**Comment by SomeoneWeird** [comment]
https://twitter.com/nodeschool/status/625937111321948160

org has been recovered and we're working on users.

**Comment by az7arul** [comment]
I guess by someone named 'aitnasser' and probably by accident. But this line `This email is to confirm that you’ve deleted your account ‘nodeschool’ from GitHub.` almost gave me a heart attack

**Comment by maxogden** [comment]
Pretty much everything is back up and running now

I opened an issue on the organizers discussions with a report of what happened https://github.com/nodeschool/organizers/issues/248
