### ISSUE TITLE
Where can I get a official solution?

### ISSUE THREAD

**Issue by wodog** [nodeschool/discussions#1334]
Where can I get a official solution?

**Comment by SomeoneWeird** [comment]
Which solution are you after?

**Comment by wodog** [comment]
I got a official solution when I passed BABY STEPS, How can I get rest of them?

**Comment by Andersos** [comment]
There are multiple ways to solve most problems but if you are looking for a solution there is a folder in each of the [exercises called](https://github.com/workshopper/learnyounode/tree/master/exercises) `solution` where you can find a solution =)
