### ISSUE TITLE
ffg

### ISSUE THREAD

**Issue by siuk-kritika** [nodeschool/discussions#1335]
test

**Comment by jshowatt** [comment]
I'm new to node, too, so have no real experience but pretty sure socket.io isn't your only option. Take a look at the [Stream Handbook](https://github.com/substack/stream-handbook), specifically the [scuttlebutt](https://github.com/substack/stream-handbook#distributed-partition-tolerant-chat) and [distributed partition-tolerant chat](https://github.com/substack/stream-handbook#distributed-partition-tolerant-chat) topics, for a possible alternative.

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
