### ISSUE TITLE
javascripting

### ISSUE THREAD

**Issue by pungggi** [nodeschool/discussions#1337]
It is boring to always rename a .js file. Keep using always the same name like app.js or something.

**Comment by SomeoneWeird** [comment]
What do you mean?

**Comment by RichardLitt** [comment]
Each exercise asks you to make a new file with a new name. Instead of creating a new file, most students probably just rename an old one, which can get annoying.

**Comment by pungggi** [comment]
exactly

**Comment by patmorgan235** [comment]
nodeschool dosent require you to use a specific file name it just gives you an example file name. you can type $ <youNodeSchoolWorkshop> verify <anyFileName>

**Comment by SomeoneWeird** [comment]
@RichardLitt that's up to them, i'm not sure how we can fix that?

**Comment by pungggi** [comment]
It can be fixed saying in the beginning, that the filename can be always
the same
Am 19.08.2015 03:13 schrieb "Adam Brady" <notifications@github.com>:

**Comment by RichardLitt** [comment]
Merged! Thanks @pungggi.
