### ISSUE TITLE
8th programming exercise for 'learnyounode' trying to seperate in two methods

### ISSUE THREAD

**Issue by nabilallam** [nodeschool/discussions#1338]
Hi,
I solved the 8th exercise. But I'm trying to understand how callbacks are used. So I separated my code in:

``` js
var http = require('http')
var concat = require('concat-stream')
var url = process.argv[2]

function modUrl(url, callback){
  http.get(url, function(response) {
    response.pipe(concat(callback(data)))
  })
}

modUrl(url, function(data){
  console.log(data.toString())
})
```

Executing this code leads to the error:

```
response.pipe(concat(callback(data)))
                                  ^
ReferenceError: data is not defined
```

What am I doing wrong.
To compare my working code:

``` js
  http.get(url, function(response) {
    response.pipe(concat(function(data){
      console.log(data.toString().length)
      console.log(data.toString())
    }))
  })
```

Thanks for help...

**Comment by nabilallam** [comment]
I find out the cause of error.
It is a callback, and it is not the same as calling a function.
The code works if it looks like:

```js
function modUrl(url, callback){
  http.get(url, function(response) {
    response.pipe(concat(callback))
  })
}

modUrl(url, function(data){
  console.log(data.toString())
})
```

Any Idea of an article/tutorial which describes the concept of callbacks in node JS.

**Comment by ishtiaque23** [comment]
The concept of callback is actually introduced in the Exercise 4(My first async I/O) of learnyounode workshop. It also shares a pretty good link where you can learn almost everything about callback. Here is the link: https://github.com/maxogden/art-of-node#callbacks

**Comment by danielinux7** [comment]
Two concepts are part of this exercise:
1- prototypical inheritance:
pipe is a function that is extended and added to the prototype chain of the response object in node, this occurs when you npm install concat.
2- callbacks;
The concat function is executed right away, returns an object that is made available to the pipe function, as soon as all data is collected, an event with pipe is triggered, the callback function that is probably a property of the returned object is used, in our case to write to the console.
