### ISSUE TITLE
Issue with third exercise: my first i/o

### ISSUE THREAD

**Issue by kevin-sang** [nodeschool/discussions#1340]
I am getting the following error:

TypeError: undefined is not a function

It points to the instance in my code in which I split the string array, using '\n' as the delimiter. Below is my code:

```js
var fs = require('fs');

var file = process.argv[2];

var buf = fs.readFileSync(file);

var str = buf.toString;

var str1 = str.split('\n');

var finalString = str1.length - 1;

console.log(finalString);
```

**Comment by stonemirror** [comment]
On Jul 30, 2015, at 6:19 PM, kevin-sang <notifications@github.com> wrote:
> 
> I am getting the following error:
> 
> TypeError: undefined is not a function
> 
> It points to the instance in my code in which I split the string array, using '\n' as the delimiter.
> 

I’d say your problem’s on the preceding line.

**Comment by tgfjt** [comment]
Please try `buf.toString()` instead of `buf.toString` :smile:

**Comment by kevin-sang** [comment]
oh i see! whoops...

**Comment by SomeoneWeird** [comment]
:tada:
