### ISSUE TITLE
Unable to install packages recommended in exercise #8

### ISSUE THREAD

**Issue by Rlin415** [nodeschool/discussions#1342]
I am receiving this error when I run either one of these commands:
``npm install bl ``
`` npm install concat-stream ``

## Result

```
npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install" "bl"
npm ERR! node v0.10.35
npm ERR! npm  v2.13.2
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:905:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:896:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   parent: '@rlin415/workspace' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

```
I set my proxy to null and am using a personal laptop. I can solve the problem without installing the packages, but I want to know why I am unable to. Can someone please help me? Thanks.

**Comment by javiervelezreyes** [comment]
You have a node process already running and catching a port. Open process
manager in your OS and kill node. Then retry.

**Comment by Rlin415** [comment]
Could you elaborate a little on how I can do that? I am using Cloud 9 btw. I tried looking at the process list and I did not find a node running.

**Comment by danielinux7** [comment]
ps -ax | grep -i node
kill [node's pid]

**Comment by bradford-hamilton** [comment]
npm install bl -g

**Comment by the-dsw** [comment]
you need to delete the file .npmrc and is ok

**Comment by mtHuberty** [comment]
@the-dsw Holy cow I struggled with this for days but this fixed it. I'm using Cloud9 IDE (in AWS) and I just had to figure out how to show hidden files so I could delete it, but this 100% worked. Thank you!

**Comment by yvasilyev92** [comment]
@the-dsw @mtHuberty  Thank you!!! It was hiding in the Hidden Files section. Deleted it and problem solved!
