### ISSUE TITLE
unable to filter the array / exercise 5 from learnyounode. 

### ISSUE THREAD

**Issue by SJ04** [nodeschool/discussions#1343]
hi guys!

i am going through learnyounode and at 5 exercise here is my code

fs = require ('fs');
path = require ('path')
var myargvs = process.argv.slice(2);
var dir = myargvs[0];
var ext = myargvs[1];

fs.readdir(dir, function (err,list)
{
	if (err)
	{
		return console.log(err)
	}
	
	console.log(list);
	var x = list.filter(ext,function(err,file)
	{
		if(err)
		{
			return console.log(err);
		}
		console.log(file);
	})
	
	console.log(x);
	
})

how can i filter this array , thanks guys!

**Comment by Rlin415** [comment]
You've got to use the path.extname method on each file to extract the name of the extension, then return which file's extension name matches the given ext by the test.

**Comment by SJ04** [comment]
@Rlin415 thanks for the Tip! this is solved now.

**Comment by SJ04** [comment]
Here is my Solution
fs = require ('fs');
path = require ('path')
var myargvs = process.argv.slice(2);
var dir = myargvs[0];
var ext = myargvs[1];

fs.readdir(dir, function (err,list)
{
	if (err)
	{
		return console.log(err)
	}
for (i in list)
{
	var temp = list[i].split(".");
	if(temp [1] == ext) {
		console.log(list[i]);
	}
}
});
