### ISSUE TITLE
npm upgrade destroyed npm

### ISSUE THREAD

**Issue by tad** [nodeschool/discussions#1344]
I just tried to upgrade to the latest npm by doing:

npm install npm -g

And that threw a bunch of errors, and now npm is busted.

Do I need to reinstall node?

**Comment by tad** [comment]
I have since closed that terminal window (dumb, I know) so I can't share the errors that were thrown.

They all mostly looked like access/permissions errors.

I haven't had any problems with npm in the past.

**Comment by tad** [comment]
I found this:

https://github.com/npm/how-to-npm/issues/27

Apparently that one npm install requires to be run via sudo. I've installed tons of other npm modules globally without sudo, but I guess from now on I'll always use sudo.

**Comment by tad** [comment]
I did reinstall node and then I was able to successfully upgrade npm by using sudo.

**Comment by stonemirror** [comment]
> On Jul 31, 2015, at 11:13 AM, Tad Donaghe <notifications@github.com> wrote:
> 
> I found this:
> 
> npm/how-to-npm#27
> 
> Apparently that one npm install requires to be run via sudo. I've installed tons of other npm modules globally without sudo, but I guess from now on I'll always use sudo.
> 

In my experience, any global (i.e. "-g") install needs escalated privileges.

**Comment by SomeoneWeird** [comment]
You should never upgrade npm by running `npm upgrade npm`, you should always do `npm install npm@latest -g`
