### ISSUE TITLE
Sr Software Engineer 

### ISSUE THREAD

**Issue by nirmalsunadham** [nodeschool/discussions#1346]
I want to learn how to use Git ! There is Git, Git bash, Git  Gui, that i downloaded and don't know where and how to start. also i downloaded the node.js need to know how to use it also.

**Comment by koddsson** [comment]
Hey @nirmalsunadham. Have you checked out the [git-it workshop](https://github.com/jlord/git-it)?

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
