### ISSUE TITLE
My First I/O - Guidance Appreciated

### ISSUE THREAD

**Issue by Diope** [nodeschool/discussions#1349]
So right now I'm having quite the time figuring out where the issue lies with my solution to the problem.
This is what I've come up with

```js
var fs = require('fs');
var path = process.argv[2];

fs.readFileSync(path, 'utf8', function (err, data) {
  if(err) throw err;
  var line = data.split('\n').length-1;
  console.log(line);
});
```
Running tests on it nothing is printed despite the fact I'm passing line through the console log. Any direction/hint on where I might need to look in order to find the solution to my problem would be much appreciated.

Edit: Not sure how to apply a label to the question. I apologize for that.

**Comment by photocurio** [comment]
Maybe you need to convert your buffer to a string with `str = data.toString();` before you use split.

**Comment by thealkimist** [comment]
Can't use a callback for `readFileSync`. Remember that any method with a `Sync` at the end is synchronous.

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.
