### ISSUE TITLE
process.argv additional numbers

### ISSUE THREAD

**Issue by bmcilw1** [nodeschool/discussions#1351]
process.argv is capturing digits that are defiantly not supplied in the command line. Prints the same numbers even if you cast the numbers with Number(process.argv[i]). Mac bug?

System: Mac os X 10.10.4
file sumTest.js:
```js
console.log(process.argv)
```
no unseen characters etc are present in commands
command: `learnyounode run sumTest.js`
output: 
```
[ '/usr/local/bin/node',
  '/Users/bmcilw1/Public/sumTest.js',
  '38',
  '26',
  '51',
  '12' ]```
What are the last four numbers here and where do they come from?

command: `learnyounode run sumTest.js 12 22 33`
output: 
```
[ '/usr/local/bin/node',
  '/Users/bmcilw1/Public/sumTest.js',
  '77',
  '70',
  '63',
  '65',
  '79',
  '34',
  '93',
  '45' ]
```
None are 12, 22, or 33

**Comment by SomeoneWeird** [comment]
When you use `learnyounode verify` and `learnyounode run` it will automatically inject command line variables for you to use. If you just run `node <file>` you won't see the numbers.

**Comment by bmcilw1** [comment]
lol. Thanks.

**Comment by SomeoneWeird** [comment]
No problem :tada: open another issue if you have more problems
