### ISSUE TITLE
Error Installing npm install -g javascripting

### ISSUE THREAD

**Issue by benoss90** [nodeschool/discussions#1352]
I'm trying to install the javascripting module, and I get the following error:

Benos-MacBook-Pro:~ benosuriano$ npm install -g javascripting
npm ERR! tar.unpack untar error /Users/benosuriano/.npm/javascripting/2.0.3/package.tgz
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "javascripting"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/javascripting
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benosuriano/npm-debug.log

What am I doing wrong?

**Comment by julianduque** [comment]
Hello @benoss90 it seems your user doesn't have permissions to install global npm packages, please try again using `sudo` like:

``` bash
$ sudo npm install -g javascripting
```
And enter your password

**Comment by benoss90** [comment]
Thank you @julianduque... that worked!

**Comment by derrickjdesigns** [comment]
It took me a while to figure this out and quite a few times of instalIing and uninstalling but I arrived at a more robust solution in which I did not have to use `sudo` or `chown` folders.  I installed via homebrew and moved the install location to a folder in which I had permissions to read and write. There are instructions  here on how to do it http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/
