### ISSUE TITLE
learnyounode baby steps understanding the for loop

### ISSUE THREAD

**Issue by derrickjdesigns** [nodeschool/discussions#1353]
I am working on step 2 of learn you node "baby steps"
I see that the answer is as follows but just need a little help understanding how this works.

```js
var result = 0;
for (var i = 2; i < process.argv.length; i++){
       result += Number(process.argv[i]);
}
console.log(result);
```

I am trying to dissect this answer to understand how the code is working so I did this to see what numbers I might get. 

```js
var testArray = ['node', 'program.js', '4', '6', '13'];
var result = 0;
for (var i = 2; i < testArray.length; i++){
      result += Number(testArray[i]);
}
console.log(i);
console.log(result);
```

The code logged 5 then 23 to the console. I see that the result was correct but if `i = 5` after the loop is executed then shouldn't `testArray[i]` just return the string that is in the fifth placeholder of `testArray` which is 13. Then if that is case shouldn't `result += Number(testArray[i]` return 13 as well. So I tried this 

```js
var testArray = ['node', 'program.js', '4', '6', '13'];
var result = 0;
for (var i = 2; i < testArray.length; i++){
     result += Number(testArray[i];
}
console.log(testArray[i]);
console.log(result);
```

When this code was executed the console returned undefined and 23. Again not what I was expecting. So I did this just to see if I might get some thing else besides undefined. 

```js
console.log(+testArray[i]);
```

The console returned NaN and 23.

I just am not really understanding how this code is working because it seems contradicting to me. Can someone please explain.

**Comment by derrickjdesigns** [comment]
Oh I just realized that if I try to recall `i` outside of it's lexical environment which is inside the `if` loop  that when the code is executed it will try to find the value of variable `i` in the global context. So then I ran this code to see what would happen. 
`var testArray = ['node', 'program.js', '4', '6', '13'];

var result = 0;

for (var i = 2; i < testArray.length; i++){
  	console.log(testArray[i]);
        result += Number(testArray[i]);
}
 console.log(result);`

The console logged 4, 6, 13, 23 which makes a little more sense to me. So if `testArray[i] == '4', '6', '13'` then i suppose `result += Number(testArray[i]) == 23` and I deduced it's this way because this code would be the sum of 4, 6, and 13. This sum would then be stored in the variable `result`. Is this logic correct? Sorry I'm new to Javascript so my understanding is limited.

**Comment by derrickjdesigns** [comment]
So I guess all that I need to know is how exactly the `for` loop works. How I understand it is each time the code in the parentheses runs and `i` in incremented by one a value is stored into `i` which creates an array for the variable `i`. Can someone please tell me if this is correct?

**Comment by edrickchu** [comment]
having just as much trouble understanding the syntax for this too!

particularly, don't really get what the properties of '''
process.argv
''' are, or what the '''
result
'''
function is doing.

Also, confused as to how the answer code determines its input numbers arguments.

**Comment by n30r3b3l** [comment]
@derrickjdesigns 
There is not an array for the variable i. i gets overwritten each time the for loop is run. `for(i = 2; i < testarray.length; i++)`. The for loop works like this:
When you enter the for loop, i is set to 2. 
Check to see if i < testarray.length (4), if it is run all code inside the for loop.
i++ which means increment i by 1
Run all code inside the for loop
Then check to see if i < testarray.length
Keep doing this until i < testarray.length is false

The reason i = 5 after the for loop has finished is because i is incremented each time the condition is tested. On the last run the program checks if i < testarry.length, it is not but i still gets incremented and then the code inside the loop is bypassed. One thing to remember with for loops is you always have to be extremely careful to make sure that your condition returns false at some point, or you will end up with an infinite loop. For instance if your for loop looked like this `for(i = 10; i > 5; i++)` the condition would never return false because i would always be greater than 5 and you would be stuck inside the loop forever.
Please let me know if this helps and don't hesitate to ask for clarification.

**Comment by n30r3b3l** [comment]
@eafelix `process.argv` is an array which contains the whole command line invocation. Meaning if you run `node program.js 2 4 6` from command line, 
`process.argv[0]` would be node,
 `process.argv[1]` would be program.js. 
`process.argv[2]` would be 2, and so on. 
So if you are wanting to access the arguments passed to your program, you would start at `process.argv[2]` and go to the end of the array
So the answer code runs your program with arguments like 4 6 13, and it knows what the sum of those numbers is.
The `result += Number(process.argv[i])` adds whatever number is in that position of the process.argv array to result. writing `result += 4` would be the same as `result = result + 4`, which just means take result, add 4 to it and store that new number in the result variable. All of the items stored in the process.argv array are strings, the `Number(process.argv[i])` just means turn the string stored there into a number.
I hope this helps, let me know if this helps or if I need to clarify anything.

**Comment by derrickjdesigns** [comment]
Ok I think I get it now. So the code in the curly braces of the `for` loop is run each time the code in the parentheses is true. Previously I thought the code in the curly braces only gets ran if the code in the parentheses is false. So in my example the variable `result` starts as 0 then when `i ==2, result =  4` then when `i = 3, result = 10` then when `i = 4, result = 23` and then the code in the curly braces is bypassed when `i = 5`.  I tested this by running this code.
```javascript
var testArray = [ 'node', 'program.js', '4', '6', '13' ];

var result = 0;

for (var i = 2; i < testArray.length; i++) {
  result += Number(testArray[i]);
  console.log(result);
}

console.log(result);
```
This code logged 4, 10, 23, and then 23 again after the `for` loop. Get it now. Thanks you for the explanation @n30r3b3l it really helped clear things up for me.
