### ISSUE TITLE
unable to start on ubuntu it sais : /usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by dumitriucristian** [nodeschool/discussions#1355]

**Comment by tmcgoo** [comment]
Hi dumitriucristian,

As you have probably noticed in Ubuntu you run node with 'nodejs' in the command line.
On other operating systems it is just 'node'. This package was written using the this command.

Go into /usr/local/lib/node_modules/scope-chains-closures/runner.js and then change the first line from...

#!/usr/bin/env node

to ...

#!/usr/bin/env nodejs

Hopefully that you do the trick

**Comment by leksstar** [comment]
I've found this is often a misnaming error, if you install from a package manager you bin may be called nodejs so you just need to symlink it like so "ln -s /usr/bin/nodejs /usr/bin/node"
