### ISSUE TITLE
Running learnyounode not as obvious

### ISSUE THREAD

**Issue by bibhas2** [nodeschool/discussions#1356]
(This page)[https://github.com/workshopper/learnyounode] says:

3. Run learnyounode

But how? This is not obvious for newcomers who will presumably need to use this tutorial. In Ubuntu the process was far from obvious. I had to:

1. ``cd /usr/local/lib/node_modules/learnyounode``
2. ``nodejs learnyounode.js``

**Comment by bibhas2** [comment]
OK, the issue is that in Ubuntu the ``nodejs`` executable is not linked to ``node`` by default. So I had to do this:

```
sudo ln -s /usr/bin/nodejs /usr/bin/node
```
After that I can simply run ``learnyoucode`` from the command line.

**Comment by SomeoneWeird** [comment]
:tada:
