### ISSUE TITLE
colors in "javascripting"

### ISSUE THREAD

**Issue by erkkiruohtula** [nodeschool/discussions#1358]
The exercises use a number of colors that make them hard to read on my white-background Linux terminal. For example, the yellow text is almost impossible for my eyes to discern. In fact, the whole color scheme reminds me of the old MS-DOS IDEs that by default went overboard in coloring every kind of item in different color, and induced headaches... Please use color sparingly, and preferably not at all.

**Comment by SomeoneWeird** [comment]
Most workshoppers use colors to discern information that are either commands or code. Yellow comes up quite readable on my terminal. 

Relevant: https://github.com/sethvincent/javascripting/issues/3

**Comment by erkkiruohtula** [comment]
Yellow? Clearly your mileage varies. On my terminal and with my eyes, the yellow text on white is illegible. Light blue is almost as bad. As someone who has written hundreds of pages of documentation, I am well aware of the usefulness of typographically distinguishing literal input and output, and explanatory prose. But going too far with effects makes it tiresome both for the writer and the readers. With displays, you also cannot precisely control what hue the user sees. I would suggest using just two colors: black, and blue (or green), and boldface for headers. Good layout of the text takes care of the rest of the disambiguation.

**Comment by SomeoneWeird** [comment]
I am well aware of this. It's just the way the creator has written it, you're more than welcome to submit a pull request if you feel the need.

**Comment by MaxSchumacher** [comment]
For the duration of the tutorial you could also change your terminal's background color to something darker.

 It will be hard to accommodate readability on all different shells with all possible configurations. For my part, everything is perfectly readable.

**Comment by martinheidegger** [comment]
Note: there is a '--no-color' option in javascripting to remove the color

**Comment by wachr** [comment]
That '--no-color' option is necessary for me using the mosh client on my Chromebook Pixel. Otherwise, the syntax highlighting results in black text on a black background.
