### ISSUE TITLE
I can't get npm to install

### ISSUE THREAD

**Issue by wgottschalk** [nodeschool/discussions#1359]
I ran `npm install -g javascripting` and ended up getting this error report:
`<npm ERR! tar.unpack untar error /Users/WillG/.npm/javascripting/2.0.3/package.tgz`
`npm ERR! Darwin 14.3.0`
`npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "javascripting"`
`npm ERR! node v0.12.7`
`npm ERR! npm  v2.11.3`
`npm ERR! path /usr/local/lib/node_modules/javascripting`
`npm ERR! code EACCES`
`npm ERR! errno -13`

`npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting'`
`npm ERR!     at Error (native)`
`npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting']`
`npm ERR!   errno: -13,`
`npm ERR!   code: 'EACCES',`
`npm ERR!   path: '/usr/local/lib/node_modules/javascripting',`
`npm ERR!   fstream_type: 'Directory',`
`npm ERR!   fstream_path: '/usr/local/lib/node_modules/javascripting',`
`npm ERR!   fstream_class: 'DirWriter',`
`npm ERR!   fstream_stack: `
`npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',`
`npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',`
`npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }`
`npm ERR! `
`npm ERR! Please try running this command again as root/Administrator.`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/WillG/npm-debug.log`

can someone help me make sense of this? usr/local/bin is in my $PATH I'm pretty sure so I don't really understand what's wrong here.

**Comment by stonemirror** [comment]
Your problem isn’t /usr/local/bin, I’d guess, but /usr/local/lib.

Run it under sudo.

**Comment by wgottschalk** [comment]
Thank you so much! I'm kind of a noob here and didn't realize you need a sudo command if your computer has password protection.
