### ISSUE TITLE
How to return to the time before initial commit? I wrongly push my code

### ISSUE THREAD

**Issue by GMKH** [nodeschool/discussions#1360]
I am new to Git. I wrongly pushed my code instead of pulling it down.  Is there any way to clean the repository (like the first time that I created it) and pull my code? 
NB: I can not delete the repository and I am only one who contributes at these stage, others will contribute later,so I am not worry other's contribution now.

**Comment by stonemirror** [comment]
git fetch origin
git reset --hard origin/master

**Comment by khosravi** [comment]
I did it. It said that HEAD is now at initial commit but It seem that nothing changed to me.I can see my initial commit on Github yet.

**Comment by riyadhalnur** [comment]
@khosravi you have to force push to GitHub after you've hard reset on local. Let me know if that solves your problem.
