### ISSUE TITLE
Scope.js

### ISSUE THREAD

**Issue by rick10605** [nodeschool/discussions#1365]
I am having trouble with an exercise about scope.js.  Below is the assigned code and challenge.  I keep getting the error: TypeError: number is not a function;  
I am very new to this.  Can someone help me through?

Thanks!
______________________________

 The challenge:

Create a file named scope.js.

In that file, copy the following code:

var a = 1, b = 2, c = 3;

(function firstFunction(){
    var b = 5, c = 6;

    (function secondFunction(){
        var b = 8;

        (function thirdFunction(){
            var a = 7, c = 9;

            (function fourthFunction(){
                var a = 1, c = 8;

            })();
        })();
    })();
})();

Use your knowledge of the variables' scope and place the following code inside one of the functions in 'scope.js'
so the output is a: 1, b: 8,c: 6

console.log("a: "+a+", b: "+b+",c: "+c);

**Comment by awong650** [comment]
can you copy the exact error into this thread? What have you done so far?

**Comment by rick10605** [comment]
Thanks for the quick reply!
Here is the entire error text:

(function firstFunction(a){

^

TypeError: number is not a function

    at Object.<anonymous> (/Users/Rick2/javascripting/scope.js:2:1)

    at Module._compile (module.js:460:26)

    at Object.Module._extensions..js (module.js:478:10)

    at Module.load (module.js:355:32)

    at Function.Module._load (module.js:310:12)

    at Module.require (module.js:365:17)

    at require (module.js:384:17)

    at Object.exports.run
(/usr/local/lib/node_modules/javascripting/lib/problem.js:48:5)

    at Adventure.runExercise
(/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/adventure.js:454:32)

    at Adventure.execute
(/usr/local/lib/node_modules/javascripting/node_modules/workshopper-adventure/adventure.js:197:17)


I've tried to insert the console.log code in multiple places and still get
the same error.  Please excuse my ignorance...

*RG*

**Comment by awong650** [comment]
did you copy and paste the code?  why is there an extra argument in firstFunction?

**Comment by rick10605** [comment]
I copied and pasted the code directly from the example. I don't understand
why the code is written as it is. It seems like there is an easier way to
get the end result. That is part of my confusion

**Comment by awong650** [comment]
I would double check your code.  Your error indicates that it was not copied and pasted correctly. FirstFunction should have an empty parenthesis.

**Comment by rick10605** [comment]
It does have an empty parenthesis. The font is just not clear in the copy I sent to you.

**Comment by awong650** [comment]
Please copy and paste your program here

**Comment by rick10605** [comment]
var a = 1, b = 2, c = 3

function firstFunction(){
    var b = 5, c = 6
	
    function secondFunction(){
        var b = 8
		
        function thirdFunction(){
            var a = 7, c = 9

            function fourthFunction(){
                var a = 1, c = 8
            }  
		}
    }
}

**Comment by MaxSchumacher** [comment]
Rick, the program you start with should be:

```javascript
var a = 1, b = 2, c = 3;

(function firstFunction(){
    var b = 5, c = 6;

    (function secondFunction(){
        var b = 8;

        (function thirdFunction(){
            var a = 7, c = 9;

            (function fourthFunction(){
                var a = 1, c = 8;

            })();
        })();
    })();
})();
```
The question now into which function do you post this statement.

```javascript
console.log("a: "+a+", b: "+b+",c: "+c);
```

**Comment by rick10605** [comment]
Excellent!  Now, it seems that I do not understand exactly where to post
such a statement.  Unless I post it outside of the function, I only get an
error.  I know I need to learn more about scope but I am stuck here.  I
have re-read the exercise multiple times to no avail. Can you direct me
towards a solution?

Thanks so much!


*Rick *

**Comment by rick10605** [comment]
Max!
I am so sorry!  I was posting the statement in the wrong location!  I now have the solution!
Thank you for your patience!
Rick

**Comment by MaxSchumacher** [comment]
Great! :)

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by optimalsean** [comment]
Which function do you put the statement "console.log("a: "+a+", b: "+b+",c: "+c);" into?

**Comment by rajmsp430** [comment]
var a = 1, b = 2, c = 3;

(function firstFunction(){
	var b = 5, c = 6;

	(function secondFunction(){
		var b = 8;
		console.log("a: "+a+", b: "+b+", c: "+c);
		(function thirdFunction(){
			var a = 7, c = 9;

			(function fourthFunction(){
				var a = 1, c = 8;

			})();
		})();
	})();
})();

**Comment by Skhoshhal** [comment]
I can't find a solution for this challenge is some one to help me?
My code consist of: 

var a = 1, b = 2, c = 3;  

     (function firstFunction(){  
         var b = 5, c = 6;  

         (function secondFunction(){  
             var b = 8;  
console.log("a: "+a+", b: "+b+",c: "+c);
             (function thirdFunction(){  
                 var a = 7, c = 9;  

                 (function fourthFunction(){  
                     var a = 1, c = 8;  

                 })();  
             })();  
         })();  
     })();  
 I tried console.log at the end of the code but not worked.
