### ISSUE TITLE
array.filter confusion, functional javascript, basic filter exercise

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1368]
function getShortMessages(messages) {
	var sortedMessages = messages.filter(function(index){
		if(index.length<50) {return index}
	})
	return sortedMessages;
}

module.exports = getShortMessages;

I am a little confused why my code isn't working.  I thought the array.filter was supposed to take an array and return all parts that met the filter criterium(a) i.e. callback function.  I suspect index.length is not correct.  But, I do not know why.  I also don't know why the hint suggests nesting array.filter with array.map.  If someone could help me figure out if I am conceptualizing this correctly, I would appreciate it.  Thank you.

**Comment by javiervelezreyes** [comment]
The callback function should return a boolean value not the element. Change
the if statement by simply return index.length > 50;

**Comment by awong650** [comment]
I see.  So, unlike map, it does not return the value.  Thanks.
