### ISSUE TITLE
Chapter request for Gurgaon

### ISSUE THREAD

**Issue by nikhilbethlabs** [nodeschool/discussions#1369]
Hi All,

4 Years of Experience in Community building. Notable work with FOSS India and Technokriti.
Cheerfully supported Open Source Softwares, Android.
Working on a project from past 3 Months using Node.js and socket.io
Looking towards sharing and gaining more with Local Lads under the Nodeschool name-Gurgaon,India

**Comment by SomeoneWeird** [comment]
Do you have anybody else to start this chapter with?

**Comment by nikhilbethlabs** [comment]
We are well supported by our organization (Prayog-http://prayog.me)
Our organization is working on node from last 1 year and is ready to support a dev community here itself.

**Comment by finnp** [comment]
Would you mind reading up on https://github.com/nodeschool/organizers#how-to-start-a-new-nodeschool-chapter and open another issue over there? I am closing the issue here.
