### ISSUE TITLE
[Scope Chains]: Lesson 3 - Global Scope & Shadowing

### ISSUE THREAD

**Issue by edrickchu** [nodeschool/discussions#1371]
Need help with this please!

```
Your Mission
Starting with your solution from the previous lesson, assign a value to quux
inside foo() (don't use var or let). The value should be different to the
value assigned when defining quux inside zip().
```

Once complete, execute scope-chains-closures verify <your-file.js> to verify your
solution.

This is my code:
```function foo() {
  quux = 15;
  function zip() {
    var quux = 2;
  }
}```

This is the error I get:
```    
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\t\tzip()\n\t\t- var quux'
    actual:
      '(global)\n\tfoo()\n\t- quux = ?\n\t\tzip()\n\t\t- var quux'
```

npm -v = 2.12.1
node -v = v0.12.7

Plmk. Thanks!

**Comment by jesstelford** [comment]
The output is a little hard to read, but once you remove those `\n` and `\t` it becomes more obvious what the differences are:

*expected*:
```
(global)
  foo()
  - var bar
  - quux = ?
    zip()
    - var quux
```

*actual*:
```
(global)
  foo()
  - quux = ?
    zip()
    - var quux
```

Once you spot the difference you can update your solution and try again :)

**Comment by edrickchu** [comment]
Wooo! Got it :)

Seems like I just needed to keep ```var bar``` in the solution, though, I had the scope chain correct!

One more question, what do the ```\n``` and ```\t``` mean?

Thanks!!

**Comment by jesstelford** [comment]
You're welcome - really glad you're enjoying it!

> what do the `\n` and `\t` mean?

* `\n` means *newline*
* `\t` means *tab*

but that's just for output display, it doesn't mean you necessarily need to have exactly one newline and exactly one tab, etc. The code is normalised before being compared against the expected output of other normalised code.

**Comment by iyogeshjoshi** [comment]
It doesn't worked for me. Here is my code
```javascript
function foo() {
  var bar;
  quxx = 1;
  function zip() {
    var quux = 2;
  }
}
```

still it's clearing only 1/2 test

```bash
# (anonymous)
ok 1 Solution loaded
not ok 2 The structure is correct
  ---
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\t\tzip()\n\t\t- var quux'
    actual:
      '(global)\n\tfoo()\n\t- var bar\n\t- quxx = ?\n\t\tzip()\n\t\t- var quux'
```
I don't get it how expected is different from actual!

**Comment by jesstelford** [comment]
@iyogeshjoshi Looks like you've got a spelling mistake there - `quxx` instead of `quux`.

**Comment by iyogeshjoshi** [comment]
@jesstelford sorry my bad!

**Comment by SomeoneWeird** [comment]
:tada:
