### ISSUE TITLE
Lesson module load errors

### ISSUE THREAD

**Issue by Dynalt-glj1** [nodeschool/discussions#1375]
I tried to load the how-to-npm and Git-It modules and get failtures:
 npm i -g how-to-npm
pm ERR! TypeError: Object #<RegClient> has no method 'get'
pm ERR!     at addNameRange (K:\NODEJS\node_modules\npm\lib\cache.js:640:12)
pm ERR!     at K:\NODEJS\node_modules\npm\lib\cache.js:572:5
pm ERR!     at K:\NODEJS\node_modules\npm\lib\cache.js:1174:7
pm ERR!     at K:\NODEJS\node_modules\npm\node_modules\lockfile\lockfile.js:121
23
pm ERR!     at K:\NODEJS\node_modules\npm\node_modules\lockfile\lockfile.js:121
23
pm ERR!     at K:\NODEJS\node_modules\npm\node_modules\lockfile\lockfile.js:136
14
pm ERR!     at Object.oncomplete (fs.js:107:15)
pm ERR! If you need help, you may report this log at:
pm ERR!     http://github.com/isaacs/npm/issues
pm ERR! or email it to:
pm ERR!     npm-@googlegroups.com

pm ERR! System Windows_NT 6.1.7601
pm ERR! command "K:\NODEJS\\node.exe" "K:\NODEJS\node_modules\npm\bin\n
m-cli.js" "i" "-g" "how-to-npm"
pm ERR! cwd K:\NODEJS
pm ERR! node -v v0.10.1
pm ERR! npm -v 1.2.15
pm ERR! type undefined_method
pm ERR!
pm ERR! Additional logging details can be found in:
pm ERR!     K:\NODEJS\npm-debug.log
pm ERR! not ok code 0

:\NODEJS
how-to-npm
NT: Unknown command "how-to-npm"

:\NODEJS

---

Windows 7 64-bit with all updates
node --version
0.10.1

npm --version
.2.15

Where did I go wrong?
## 

Thanks,

Garold L. Johnson

**Comment by stonemirror** [comment]
On Aug 13, 2015, at 4:14 PM, Dynalt-glj1 <notifications@github.com> wrote:
> 
> I tried to load the how-to-npm and Git-It modules and get failtures:
> npm i -g how-to-npm
> 
You need to “sudo” a global install.

Try

sudo npm i -g how-to-npm
