### ISSUE TITLE
javascripting translation to pt_br is in github but npm cannot load i18n

### ISSUE THREAD

**Issue by nunesigor** [nodeschool/discussions#1377]
I install javascripting to study and when I saw that pt_br translations is not present in package, Ive got the idea "i can contribute with pt_pr transcription" but when i checked in repository, the transcription pt_br is in the repo. how can I load the transcription ?

**Comment by koddsson** [comment]
It seems that the javascripting version that includes the `pt_br` translations hasn't been pushed to npm. You can install it from the master branch like so if you're feeling brave:

`npm install -g git+https://git@github.com/sethvincent/javascripting.git`
