### ISSUE TITLE
functional javascript basic: reduce question

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1381]
so, I know that my code is a little funky. But, if someone could help by giving me a clue as to where I should look to fix it.  That would be very appreciated.  Basically, the code is supposed to take an array of strings e.g. [a, b, b, a, e, c, d, ...] and turn it into an array of objects [a:2, b:2, e:1...] where the objects have properties of the string name followed by the number of times it occurred in the original array.  The following is my admittedly idiosyncratic code.  I am currently looking on the Javascript MDN, but it is very long.  I think that I am misunderstanding objects in Javascript.  But, maybe not.  Any advice would be appreciated.

```js
function countWords (inputWords) {
	var outputWords = [];
	inputWords.reduce(function(prevValue, currValue) {
		if(prevValue !== currValue) outputWords.length = currValue:1
		else outputWords.currValue++
	}, 'undefined');
	return outputWords
}

module.exports = countWords(inputWords);
```

**Comment by cerkiewny** [comment]
I am not sure what you are trying achieve, its not really clear from your description.
I am assuming you want the following: 
given an array with a set of values reduce it to the other array storing the number of times given object
occurred in the array so for instance given:

[a, b, a, c] it will produce [a: 2, b:1, c:1]

the elements do not need to be next to each other

If this is the case I think you are misunderstanding the syntax of getting the array element which should be [something] rather then .something. So this assignment `<outputWords.length = currValue:1>` should look more like: `<outputWords[currValue] =1>` this will set the value labeled as curValue to one, but also you need to make sure this value doesn't already exist if it does just increase it.  Same applies here   `<outputWords.currValue++>` rather then this you want  `<outputWords[currValue]++>`. Also your condition on `<prevValue !== currValue>` suggests you are trying to check whether current value and previous is the same, suggesting you want only take action if two values next to each other are the same. This should be changed slightly to take action always, and either create the counting element in outputWords labeled as current value with `<outputWords[currValue] = 1>` if it doesn't exist or increase it if it already was created.

**Comment by awong650** [comment]
Thank you for your response.  Your understanding of the problem is mostly correct except for instead of taking arrays of values, my problem only takes arrays of strings and then reduces it to an array of objects with the string name and number of instances of the string in the original array.

where do I find javascript array syntax guides?  

with regard to the <outputWords.length = currValue:1>, I was attempting to call the method length for array objects and add the current value to the end of the array.  I see now that this is not the behavior that I want.  But, this is the correct means of calling a method, right?

with regard to expressions like <outputWords[currValue]>, can this be a test condition in an if statement even if the object doesn't currently exist?

Thanks.

Andrew

**Comment by Alicjaliliana** [comment]
The if statement does the evaluation of the given value to a bool value, in other words it is changing the value given to true/false. The best way of trying to figure out what it will do with not defined array field is to write the test program. 

The following program:

```javascript
a  = []
if(a[2]){ 
   console.log("b")
} else { console.log("a")}
```

This will print "a" so it can be the test which tells you that "nothing" evaluates to "false".
a[2] does not exist therefor the javascript will return you "nothing" object, you can test it by doing
console.log(a[2])

All the guides are on the javascript official documentation for instance the mozilla group stores [one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources) you have for instance some resources here, but they are quite hard for beginners. Also w3school is good place to look those things up the basic concepts are describe [there](http://www.w3schools.com/js/js_arrays.asp).

Regarding the call to outputWords.lenght it is a correct way of getting the length of the array. However there are number of issues with your understanding. The length works more like a field from your point of view. Calling function is always realised by "()" so if it would be function it would be  outputWords.length(). So you are taking the PROPERTY of the array called length. The other issue is the assignment and types. You need to understand that each object has its type. The outputWords.length is an integer. If you are trying to assign something to the outputWords.length you are trying to assign it to a length of the array. This is nearly always not what you want. What you may want is two things, either assign the element to the last place of the array (there is a function array.push(newelement) for this purpose), or you want to modify the last existing element, for which you would take the array, apply the selection (subscription) operator "[]" and request the element. For instance outputWords[1]. If element does exist you will get the element back and you can assign it to something, or you can assign to this element respectively: a = outputWords[1] or outputWords[1] = "something". 

Hope this helps.

Also try reading this [tutorial on arrays](https://javascriptweblog.wordpress.com/2010/07/12/understanding-javascript-arrays/) hope it will clear your understanding on arrays.

**Comment by cerkiewny** [comment]
The if statement does the evaluation of the given value to a bool value, in other words it is changing the value given to true/false. The best way of trying to figure out what it will do with not defined array field is to write the test program. 

The following program:

```javascript
a  = []
if(a[2]){ 
   console.log("b")
} else { console.log("a")}
```

This will print "a" so it can be the test which tells you that "nothing" evaluates to "false".
a[2] does not exist therefor the javascript will return you "nothing" object, you can test it by doing
console.log(a[2])

All the guides are on the javascript official documentation for instance the mozilla group stores [one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources) you have for instance some resources here, but they are quite hard for beginners. Also w3school is good place to look those things up the basic concepts are describe [there](http://www.w3schools.com/js/js_arrays.asp).

Regarding the call to outputWords.lenght it is a correct way of getting the length of the array. However there are number of issues with your understanding. The length works more like a field from your point of view. Calling function is always realised by "()" so if it would be function it would be  outputWords.length(). So you are taking the PROPERTY of the array called length. The other issue is the assignment and types. You need to understand that each object has its type. The outputWords.length is an integer. If you are trying to assign something to the outputWords.length you are trying to assign it to a length of the array. This is nearly always not what you want. What you may want is two things, either assign the element to the last place of the array (there is a function array.push(newelement) for this purpose), or you want to modify the last existing element, for which you would take the array, apply the selection (subscription) operator "[]" and request the element. For instance outputWords[1]. If element does exist you will get the element back and you can assign it to something, or you can assign to this element respectively: a = outputWords[1] or outputWords[1] = "something". 

Hope this helps.

Also try reading this [tutorial on arrays](https://javascriptweblog.wordpress.com/2010/07/12/understanding-javascript-arrays/) hope it will clear your understanding on arrays.

**Comment by awong650** [comment]
This helps immensely.  Out of curiosity can I do the following.  outputWords[outputWords.length] = ... to put something at the end of an array just like push?  (I forgot about push!  Memorizing all these methods hasn't happened for me yet).  Thanks again for all your help.

Andrew

**Comment by cerkiewny** [comment]
Yes you should be able to do the outputWords[outputWords.length] =

Regards

**Comment by awong650** [comment]
Yay.  My code worked.  I am still a little puzzled about the solution.  what does this mean?

countMap[word] = ++countMap[word] || 1 

I am confused about || and what it is called.  I want to learn more about it.  It seems possibly useful for future work.

Thanks.

Andrew

**Comment by cerkiewny** [comment]
This is a cheeky way of doing initialization  if element doesn't exist.
For better readability of code you could do this:
```javascript
if(countMap[word]){
 ++countMap[word] ;
} else {
  countMap[word] ;
}
```

This works as well because if you have "||" operator it evaluates the 2 parts and returns them as result
if first part (increment) evaluates to any number except 0 the || operator will return first part
if not then it will return 2nd part, since you are increasing a number the only way of the first part failing is that it is "nothing". But I would avoid using such syntax as it is javascript specific afaik.

**Comment by awong650** [comment]
ok, thank you.  I will avoid it.  But, basically it will return the first part if it evaluates to true otherwise return the second part?

I do have one question about .reduce.  According to the mozilla site, reduce takes a callback that can take 4 arguments: previousValue, currentValue, index, array.  How come the callback for the solution looks like this?:

return arr.reduce(function(countMap, word) {
    countMap[word] = ++countMap[word] || 1 // increment or initialize to 1
    return countMap

Instead of the value previously returned in the last invocation of the callback, the solution is passing a variable that is turned into an array and then returned from the callback.  Why is this allowed?  Am I missing something important?  Or, are they just using an unused variable to store the result?

Andrew

**Comment by cerkiewny** [comment]
It is because the reduce is returning the previous value of reduce to another reduction call.

So basically having reduce as `function(p, n) {return p + n}` and array `are = [0, 1, 2, 3]`
you will get the following

function(0, 0) -> returns 0 -> function (0, 1) -> returns 1 -> function(1,2) -> returns 3 -> function (3, 3) -> returns 6 
therefore the result of the reduction is 6.

In your case you are not "chaining" the number through the reduction chain but your array which gets the fields added or increased.

**Comment by awong650** [comment]
I see.  So basically, the function returns countMap array and stores that as previous value and then performs the function on the new modified countMap array(previous value) that was modified by the previous callback.
