### ISSUE TITLE
Exercise 12 HTTP Uppercaserer - can't install through2-map

### ISSUE THREAD

**Issue by smashzen** [nodeschool/discussions#1385]
This exercise asks you to install through2-map module using command 

$ npm install through2-map

However, everytime I input this command, I get a barrage of error messages. It won't install. I tried the lesson anyway, but got "Error: Cannot find module 'through2-map'" fail as expected. Any suggestions?

**Comment by MaxSchumacher** [comment]
Hi smashzen,

please specify the barrage of error message so we can help you most effectively.

npm install -g through2-map installs the module globally, did you maybe execute the command in the wrong directory?

**Comment by smashzen** [comment]
I eventually figured it out with help from FCC help gitter. Using "sudo" before the command did the trick. Thank you for your help.
