### ISSUE TITLE
A problem in learnyounode #6

### ISSUE THREAD

**Issue by breddy80** [nodeschool/discussions#1386]
The answer shows submition results match expected.
The only problem is "Your additional module file [module.js] didn't call the callback argurment"

I really can't find where the problem is, Please give me some advice, any help is appreciated!
here' the code :

module.js

```
var fs = require('fs');
var path = require('path');
function test(first, second, cb){
    fs.readdir(first, function(err, files){
        if(err)
        {
            return cb(err);
        }
        else
        {
            for(var i = 0; i < files.length; i++)
            {
                if(second === path.extname(files[i]))
                {
                    cb(files[i]);
                }
            }

        }
});
}
module.exports = test;
```

program.js

```
var module = require('./module');
var fir = process.argv[2];
var sec = '.' + process.argv[3];

function cb(out){
        console.log(out);
}

module(fir, sec, cb);
```

**Comment by breddy80** [comment]
Sorry, it's the first time i use github, don't know how to style the text, here's the code again:

module.js

```
var fs = require('fs');
var path = require('path');

function test(first, second, cb){
	fs.readdir(first, function(err, files){
		if(err)
		{
			return cb(err);
		}
		else
		{
			for(var i = 0; i < files.length; i++)
			{
				if(second === path.extname(files[i]))
				{
					cb(files[i]);
				}
			}
			
		}
});
}
module.exports = test;
```

program.js

```
var module = require('./module');
var fir = process.argv[2];
var sec = '.' + process.argv[3];

function cb(out){
		console.log(out);
}

module(fir, sec, cb);
```

**Comment by kwpeters** [comment]
Perhaps the output you are receiving is  a little misleading.  I think your module's exported function is supposed to call the callback only once, passing it an *array* of the matching files.  Instead, your module's function is calling the callback multiple times, each time with a single matching file.

**Comment by breddy80** [comment]
hello kwpeters!  I just tried what you said, It seems like i have to call the callback multiple times. If i pass an array as the argument of the callback, The answer shows submition results didn't match expected, really thanks for you help,it's the first time i use github, it's really convenient.

**Comment by breddy80** [comment]
still can't find the problem. please help me. thanks!

**Comment by kwpeters** [comment]
I think the problem is that you are not following the Node convention used for callback functions.  Typically, a callback function has two parameters; the first is an error object and the second is the result.  In your code, you are sometimes calling the callback function with the first parameter being an error (correct), but other times you are calling it with the first parameter as the result (incorrect). 

For example, in module.js, you are (correctly) calling cb like this in the error case:
```
return cb(err);
```
But further down where readdir() is successful, you are calling it like this:
```
cb(files[i]);
```
This code is incorrect, because you are not following the cb(err, result) convention.  It should be:
```
cb(null, files[i])
```

Also, you should follow this convention in program.js too.  The code:
```
function cb(out){
        console.log(out);
}
```
should be:
```
function cb(err, out) {
    if (err) {
        console.log(err);
        return;
    } else {
        console.log(out);
    }
}
```

**Comment by pavelcreates** [comment]
The problem is within your program.js file. Concatenate the "." to the extension in the module.

**Comment by breddy80** [comment]
Hello pavelcreates! Sorry,english is not my mother languange. Do you mean that i shouldn't add "." to the sec variable?  If i don't add ".", the program won't print anything. The answer shows result didn't match expected!

**Comment by breddy80** [comment]
Hello kwPeters! thank you so mucn for you help! you're really a nice people, i tried what you said, it still didn't work. It seems that's not the problem,but what you said give me a lot of thinking. Really nice to meet you here. hope we can talk more later!

**Comment by pavelcreates** [comment]
It's not a problem with your code. But I had this problem before, the solution is to add the "." to the extension within the module, not in the file that is calling the module.

**Comment by pavelcreates** [comment]
Its just what they wanted you to do for the exercise, but they we're not very clear about it... or I overlooked the instructions.
