### ISSUE TITLE
Will you check my code? Learn You Node #6 - Make it Modular

### ISSUE THREAD

**Issue by xchelm** [nodeschool/discussions#1388]
Hi! I'm passing all the tests except for the last one. I was wondering if you could eye my code to give me a better idea on how to correct "Your additional module file [make-modular.js] did not return an Array with the correct number of elements as the second argument of the callback"

entry.js
```javascript
var modular = require('./make-modular');
var callback = function (err, data) {
	if (err){
		return console.error(err);
	}
	
	data.forEach( function (elem){
		console.log(elem);
	});
}

modular(process.argv[2], process.argv[3], function (err, list){
	if (err){
		return console.log(err);
	}
	else list.forEach(function (file){
		console.log(file);
	})
});
```

make-modular.js
```javascript
var fs = require('fs')

module.exports = function(dirName, extName, callback){

fs.readdir(dirName, function (err, contents){
	var cont = [];
	if (err){
		return callback(err)
	}

	for(var i = 0; i < contents.length; i++){
			var comp = contents[i].split('.')
			if(comp[1] == extName){
				console.log(contents[i])
			}
		}
		callback(null, cont)
	});
};
```

Thank you,
Xchel

**Comment by kwpeters** [comment]
In make-modular.js, you are never adding the matching file names to the `cont` array (which is eventually passed to the callback).  Instead, you are just `console.log()`-ing it.

Try:
```
...
if(comp[1] === extName){
    cont.push(contents[i]);
}
...
```

Also, please note the `===` in the above code instead of the `==`.  It's safer.

**Comment by gdjdsjh** [comment]
Thank U for your help, I understand what mistake I made just now. Now I have passed the No.6 test.

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by xchelm** [comment]
@kwpeters You are awesome. Thanks for the professional eye!
