### ISSUE TITLE
learnyounode exercise 5 FILTERED LS: code works fine but fails to verify

### ISSUE THREAD

**Issue by leonfeng** [nodeschool/discussions#1391]
Greetings.

Here's my code for this exercise:
```javascript
var fs = require('fs');
var path = require('path');
var pathToDir = process.argv[2];
var extension = process.argv[3];

fs.readdir(pathToDir, function (err, list) {
  for (var i = 0; i < list.length; i++) {
    if (path.extname(list[i]) === extension) {
      console.log(list[i]);
    }
  }
});
```
It produces desired output, but just won't pass the tests. Please see the screenshot below.
![screen shot 2015-08-23 at 1 07 41 pm](https://cloud.githubusercontent.com/assets/241553/9427040/0c432a12-4999-11e5-82f9-a546e1c928c2.png)

What am I missing? I have node 0.12.7 and npm 2.12.1. Thanks in advance!

**Comment by 0xh3v3r1337** [comment]
I encountered the same problem! Node 0.12.2, npm 2.7.4

**Comment by davecocoa** [comment]
The extension parameter passed to your function will be without the `.`, your function needs to add it.

**Comment by leonfeng** [comment]
Thank you! I totally misread the instructions. Teaches me not to do coding exercises while tired…
