### ISSUE TITLE
I need help in 12th exercise 

### ISSUE THREAD

**Issue by gdjdsjh** [nodeschool/discussions#1392]
Q:Write an HTTP server that receives only POST requests and converts incoming POST body characters to upper-case and returns it to the client.

But, I don't know how to get the POST body in this exercise :(
Anyone can help me?

**Comment by SomeoneWeird** [comment]
What code do you have at the moment?

**Comment by gdjdsjh** [comment]
I use the req.on('data',function(){}) method to get the data in POST body, and it passed. But I don't know whether it is allowable.
here is the code:

var http = require('http');
var server = http.createServer(function (req,res){
	if (req.method === 'POST'){
		var data = '';
		req.on('data',function(chunk){
			data += chunk.toString().toUpperCase();
		})
		req.on('end',function(){
			res.writeHead(200,"OK",{'content-type':'text/plain'});
			res.end(data);
		})
	}
})
server.listen(process.argv[2]);

**Comment by cerkiewny** [comment]
It is allowed to use all the node functions it is even mentioned in the exercise "While you're not restricted to using the streaming capabilities of the request and response objects, it will be much easier if you do.
"

So as long as it does a job it should be fine, but for the purpose of this lesson it would be much easier for you to just use the mentioned input stream.

I think this is a shorter solution:

```javascript

var http = require('http');
var map = require('through2-map')
var server = http.createServer(function (req,res){
  req.pipe(map(function (chunk) {
    return chunk.toString().toUpperCase();
  })).pipe(res);
});

server.listen(process.argv[2]);

```

**Comment by gdjdsjh** [comment]
Thank U very much !
