### ISSUE TITLE
Looping through arrays

### ISSUE THREAD

**Issue by AlbertGoRythm** [nodeschool/discussions#1393]
I am having trouble with the node school lesson looping through arrays. I have followed the directions the best I know how and searched other sources for clues. Trying to pluralize the elements in the array. Can someone tell me what's wrong with my code or give a hint.

var pets = ['cat', 'dog', 'rat'];

for (pets[i] = pets[i] + 's'){
}
console.log(pets);

**Comment by cerkiewny** [comment]
The for loop is wrongly used.

For iterating through the array you need to define how to traverse it

```javascript

var pets = ['cat', 'dog', 'rat'];

for (var i = 0; i < pets.length; i++){
   pets[i] = pets[i] + 's';
}
console.log(pets);

```
Alternatively there is a function which iterates through entire array for you it is called the foreach and accepts the function as parameter:

this is more advance solution.

```javascript


var test =  ['cat', 'dog', 'rat']

test.forEach(function (part, index, arr) { arr[index] = arr[index] + 's';});
console.log(test);

```

**Comment by AlbertGoRythm** [comment]
Thanks cerkiewny!

**Comment by cerkiewny** [comment]
No worries, if it solves your issues you can close a thread :)
