### ISSUE TITLE
babysteps

### ISSUE THREAD

**Issue by Franquiro** [nodeschool/discussions#1398]
Hi, I'm stuck trying to begin with the learnyounode workshop of nodeschool.io
the second excercise in the series tells me to run a program that recieves arguments from the console, and tells me to try starting with ¨console.log(process.argv)" as my program code and run it with program.js 1 2 3.
in the description it says I should see an array of values with [node itself, program directory, arg1, arg2, arg3]

when I run the program, I get the following:
(I ran)         learnyounode run babysteps.js 1 2 3
(output)      ['C:\...node.exe', 'C:\...babysteps.js', '8' , '57' , '89' , '59' , '62' , '62']
while I should be getting:
['C:\...node.exe', 'C:\...babysteps.js', '1' , '2' , '3']

**Comment by SomeoneWeird** [comment]
`learnyounode run` automatically adds parameters for you. If you want to add your own like `1 2 3`, try running `node babysteps.js 1 2 3` instead.

**Comment by Franquiro** [comment]
Thanks @SomeoneWeird. Will "learnyounode verify" add it's own parameters as well?

**Comment by SomeoneWeird** [comment]
Yup, it will :)
