### ISSUE TITLE
Proxy Setup

### ISSUE THREAD

**Issue by jbrychka** [nodeschool/discussions#1400]
What is the correct syntax for adding a proxy to the configuration file?  I used the following syntax but i didn't know how to put in the id and password.

proxy=ip address:8080
https-proxy=ip address:8080

**Comment by SomeoneWeird** [comment]
Proxy for what?

**Comment by koustuvsinha** [comment]
@jbrychka if you are trying o set proxy for npm, use

 `npm config set proxy http://{username}:{password}@{ip_address}:{port}`

In any case, behind a corporate firewall you set the proxy in the following convention unless specific userId password fields are present : 

proxy=http://{username}:{password}@{ip_address}:{port}
