### ISSUE TITLE
functional javascript workshop recursion question

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1401]
I am still not clear what this exercise wants.  This is what I have so far.

```js
function reduce(arr, fn, initial) {
	var obj = initial;
	if (!arr.length) return obj;
	var head = arr[0];
	return fn(obj, head, index, arr) {
		obj = head;
	};
	reduce(arr.slice(1), fn, obj);
}

module.exports = reduce;
```

basically, I think I want as my initial step to run the reduce function on the three initial parameters.  For my next step, I want to change my parameters to `arr.slice(1)`, `fn`, and changing my initial to the object returned from the previous call.  Finally, my return I think I want to return once my `arr.length() = 0`.  Is my thinking correct?  If so, can someone give me a hint why my code is not correct?

Thank you.

Andrew

**Comment by awong650** [comment]
I wonder if this is any better.

function reduce(arr, fn, initial) {
	var obj = initial;
	if (!arr.length) return obj;
	var head = arr[0];
	var index = 1;
	obj = fn(obj, head, index, arr);
	reduce(arr.slice(1), fn, obj);
}

module.exports = reduce;

**Comment by davecocoa** [comment]
You're really close! There are just two small issues:
 - You're using an `index` of one every time. This doesn't actually get tested by the workshop though
 - You're not returning anything. `reduce` is supposed to return the final result after it finishes working through the array

**Comment by awong650** [comment]
Oh... right.  Oops.  return reduce(...)

regarding index, I thought the program would always run the first item of the array and then call reduce on the next item of the array (arr. slice(1)) so that it is always index = 1 for each step through the recursion.  Is this not correct?

**Comment by davecocoa** [comment]
I suppose from that perspective, yes, but the consumer of your `reduce` function doesn't know that you're gradually removing elements from an array, from their perspective, they expect to receive index `0` first, relating to the first element in the array they passed in, followed by index `1` on the next iteration, followed by `2` and so on until the last item in the array.

Perhaps this example will help:

```js
reduce([1,2,3], function(obj, head, index){
  console.log(head, index);
})
// 1, 1
// 2, 1
// 3, 1
```
If I asked you, what is the index in this array of the element `3`, would you say `1`?

The more generally expected output would be:
```js
// 1, 0
// 2, 1
// 3, 2
```
(Another point to note, indexes start at 0 instead of 1, because [computers are confusing](https://en.wikipedia.org/wiki/Zero-based_numbering))

**Comment by awong650** [comment]
I see.  So, the preferred method for indexing even with regard to recursion is to increase the reduce index even if I am always working with the first element of the array.  Alternatively, I suppose a comment is the best way to tell the user that I am doing this recursively.  Thanks so much for your help.

Andrew

**Comment by zzz6519003** [comment]
> I suppose from that perspective, yes, but the consumer of your `reduce` function doesn't know that you're gradually removing elements from an array, from their perspective, they expect to receive index `0` first, relating to the first element in the array they passed in, followed by index `1` on the next iteration, followed by `2` and so on until the last item in the array.
> 
> Perhaps this example will help:
> 
> ```js
> reduce([1,2,3], function(obj, head, index){
>   console.log(head, index);
> })
> // 1, 1
> // 2, 1
> // 3, 1
> ```
> 
> If I asked you, what is the index in this array of the element `3`, would you say `1`?
> 
> The more generally expected output would be:
> 
> ```js
> // 1, 0
> // 2, 1
> // 3, 2
> ```
> 
> (Another point to note, indexes start at 0 instead of 1, because [computers are confusing](https://en.wikipedia.org/wiki/Zero-based_numbering))

i'm close to you XD
