### ISSUE TITLE
Fail to run the program

### ISSUE THREAD

**Issue by jannyHou** [nodeschool/discussions#1403]
When I run learnyounode in the command line, it says ' Please start this in a tty-compatible terminal program.'

**Comment by SomeoneWeird** [comment]
What OS are you on?

**Comment by freddy01288** [comment]
i have the same problem, i use the new Git bash on windows 7

**Comment by laisafcardoso** [comment]
If windows 7, enter in CMD and read learnyounode, in folder file

**Comment by HaiderMalik12** [comment]
# Please start this in a tty-compatible terminal program.

**Comment by jannyHou** [comment]
I am on windows 7 too. 64bit.

**Comment by ajaysunarthi** [comment]
Windows 7
Node version : 4.1.2

I tried few workshoppers 

javascripting, learnyounode works perfectly well on node

planet proto, bytewiser gives error as :  Please start this in a tty-compatible terminal program.

Any update over this issue ?

**Comment by tedmx** [comment]
Git Bash (MinGW) seems to handle the `learnyounode` console interface (that is, `simple-terminal-menu`'s one) with noticeable bugs, but here is a workaround if you want to try anyway:

`node "$(cygpath -aw "C:\Users\ted\AppData\Roaming\npm\node_modules\learnyounode\bin\learnyounode")"`

Change the path accordingly to point to where your `learnyounode` package is installed, and to the (only) file inside your `bin` folder.

So the general solution is just to run the file in the `bin` folder with `node`.

### Findings on the `learnyounode` bug for Git Bash

Running 
`learnyounode` 
in the console creates object for `process.stdin` which is just a `Socket` and has no TTY-related properties.

Running scripts with `node` the usual way, on the other hand, makes `ReadStream` object for `process.stdin` and adds TTY-related properties. 

Vague guess for the bug source is that running just `learnyounode` spawns child process in a stripped configuration, not TTY-ready, but that child process actually does the whole work and gets checked for TTY-compatibility in all places.

**Comment by Pradeep1026** [comment]
guys you all can run tty-compatible program in Window PowerShell.
