### ISSUE TITLE
functional javascript workshop basic call map question

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1405]
I think I already know the answer. But, if I call "map" with a function with an if statement, will it only return objects when the if statement is true?  I have a hunch it will just return objects in both cases or if I create an else statement setting the object to null, I will have an array with objects and nulls.  This is my code.  I haven't found the explicit answer anywhere.  I suppose I should just use filter.

```js
function duckCount() {
	return Array.prototype.slice.call(arguments).map(function (index) {
		if(Object.prototype.hasOwnProperty.call(index, 'quack')) return index;
	}).length
}

module.exports = duckCount;
```

**Comment by fonzerelly** [comment]
Well, map is there to convert an array of length n to a modified array of the same length.

So if your if-statement will not work , your funktion will return undefined as default.

So if you pass in this array:
[{quack: true}, {}, {quack:false}]

it would return 
[{quack: true}, undefined, {quack:false}]

For your usecase filter would be better.
function duckCount() {
    return Array.prototype.slice.call(arguments).filter(function(index) {
        return index.hasOwnProperty('quack');
    }).length;
}
You could also use reduce to get the same effect.
function duckCount() {
    return Array.prototype.slice.call(arguments).reduce(function(init, index) {
        if(index.hasOwnProperty('quack')) {
             init.push(index);
        }
        return init;
    }, []).length
}

**Comment by awong650** [comment]
Thank you.  That is helpful.  I thought this was the case, but couldn't find confirmation from the mozilla doc.  I appreciate your help.

Andrew
