### ISSUE TITLE
Can't run the learnyounode comand

### ISSUE THREAD

**Issue by BernardZhang** [nodeschool/discussions#1407]
Can't run the learnyounode comand after install the learnyounode with global
![image](https://cloud.githubusercontent.com/assets/3273449/9524047/5e487c12-4d0f-11e5-9f6b-1b880531cd8b.png)

知道了，path没有配置，解决了：）

**Comment by SomeoneWeird** [comment]
What does it say?

**Comment by tgfjt** [comment]
I guess:
This is a issue "Command not found". 
After a while,
Understood that it was need to add node PATH. It was resolved.
