### ISSUE TITLE
LearnYouNode - #6 - Make it Modular. Having issues with CallBack (ReferenceError : Call back not defined)

### ISSUE THREAD

**Issue by hdoucet** [nodeschool/discussions#1410]
Hello,
I am having issue getting CallBack function working/recognised.
When i run the program is get following error. 

/Users/hdoucet/Documents/personel/Coding/NodeJS/mymodule.js:21
   		callback(null, data)
   		^
TypeError: object is not a function
    at endofdir (/Users/hdoucet/Documents/personel/Coding/NodeJS/mymodule.js:21:6)
    at FSReqWrap.oncomplete (fs.js:95:15)

	//This is mymodule.js

	var fs = require('fs')
	var path = require('path')
	var data = []

	module.exports = 
    function filter(dir, ext,callback) {
      
      fs.readdir(dir, function endofdir (err, files) {
 		if (err) {
          return  callback(err)} // early return
    
        // ... no error, continue doing cool things with `data`
    	console.log(err,files) // Added for trouble shooting
    	for (var i = 0; i < files.length; i++){
			//console.log(data.length, i)
				if (path.extname(files[i]) == ("." + ext)) {
					data.push(files[i])};
					console.log(data) // Added for troubleshooting
				} 
        // all went well, call callback with `null` for the error argument
   		callback(null, data)
   		
      })
    }
#######

     //This is program.js

    var input = require('./mymodule.js')
    var a = process.argv
    var data = []

    input(a[2], a[3], data)
    console.log(data)

I have an error with both callback functions. Any suggestions how to change to callback syntaxx to make it work.

Thank you,
Hugo

**Comment by koustuvsinha** [comment]
Hi Hugo,

You should pass a callback function in your `input` function call's last argument. that function is essentially the `callback` in your mymodule.js. Now in that callback function, get the first arg as `err` and second as `data`, and then print that data per line. hope that helps! :)

**Comment by hdoucet** [comment]
Tx .. helped to solve this issues. I looked for hours into the modules.file .. But the issue was in the main.js file. Tx for your respond.
