### ISSUE TITLE
Problem with Baby Steps Exercise

### ISSUE THREAD

**Issue by jinsd** [nodeschool/discussions#1411]
The following code:
var sum = 0;
for(i = 2; i < process.argv.length; i++) {
    console.log(process.argv[i]);
    sum += Number(process.argv[i]);
}
console.log(sum);

Results in:
$ learnyounode run program.js
71
4
72
147
$ learnyounode verify program.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
─────────────────────────────────────────────
   "97"                                !=    "382"                              
   "80"                                !=    ""                                 
   "43"                                !=                                       
   "46"                                !=                                       
   "38"                                !=                                       
   "382"                               !=                                       
   ""                                  !=                                       
─────────────────────────────────────────────
Submission results did not match expected!

FAIL

Your solution to BABY STEPS didn't pass. Try again!

**Comment by SomeoneWeird** [comment]
You should remove the first `console.log` call in your code, it's only looking for the total.

**Comment by jinsd** [comment]
Yes...thank you...the console.log in the for loop was a sanity check for me.

**Comment by jinsd** [comment]
So removing the first console.log and running verify worked.

Thank you SomeoneWeird for the suggestion!

**Comment by TheProjectMarch** [comment]
Thank you so much, SomeoneWeird! Came wondering what the heck was going on as the code was perfectly fine but I still had a `console.log();` at the very top of the script from the part where it said 


```bash 

To get started, write a program that simply contains:

console.log(process.argv);

```

I best pay attention strictly to what it's asking for. 

Thanks again!
