### ISSUE TITLE
How to extract string portion from html file to make a new file

### ISSUE THREAD

**Issue by selfsecure** [nodeschool/discussions#1416]
Hello,

I am looking for some help.
I would like to extract string from html source to create a new file.

Who can help me.

Thanks

**Comment by tgfjt** [comment]
Would you give us more details? :smiley_cat:

**Comment by selfsecure** [comment]
I have a Hexadecimal string stored in a HTML file 
I would like to extract this string to convert this in file (txt or xls file) and launch it
