### ISSUE TITLE
http file server

### ISSUE THREAD

**Issue by w1-GrootSam** [nodeschool/discussions#1418]
Hello 

Im stuck at http file server.  I cant find my error.

here is my code:
```js
var http = require('http')
var fs = require('fs')

var portnumber = Number((process.argv[2]))

var server = http.createServer(function(req, res)
{
	res.writehead(200, {'content-type' : 'text/plain'})

	fs.createReadStream(process.argv[3]).pipe(res)
});

server.listen(portnumber)
```

I have checked the solution and have compared it with my code. but i dont see what im doing wrong.

Thanks in advance.

**Comment by awong650** [comment]
I am no expert at javascript.  Your code looks good to me except, you have the open bracket for server on a new line.  I think automatic semicolon insertion will basically make this not work.  Also, why does you code have a grey line of code in it?  Are there any hidden characters that are no displaying in your original post?

Andrew

**Comment by w1-GrootSam** [comment]
awong650 thank you for your response. the green line of code.. i dont know what it is. No hidden characters.

I found the error. on the line res.writehead, it has to be res.writeHead. with capital H
