### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by T-G-P** [nodeschool/discussions#1419]
There is a bug with this lesson. I got the solution to pass, by looking at the actual and expected output.  However, it doesn't make sense.  To get this to pass, I had to do this:

``` javascript
function foo() {
    var bar;
    quux = true;
    return zip
    function zip() {
        bar = true;
        var quux;
    }
}
```

I'm not sure why I needed to set quux to true outside of its scope, but it passed.

**Comment by davecocoa** [comment]
I tried running verify on that program and it didn't pass:

```
$ scope-chains-closures verify prog.js 

TAP version 13
# (anonymous)
ok 1 Solution loaded
not ok 2 The structure is correct
  ---
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t\tzip()\n\t\t- var quux'
    actual:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
  ...

1..2
# tests 2
# pass  1
# fail  1
```

Maybe try running `npm install -g scope-chains-closures@latest` to make sure your exercise is up to date?

**Comment by haomaggiewu** [comment]
Because the exercise is followed by former steps.

`# Your Mission

Modify your solution from the previous lesson to set bar = true inside zip(),
then return the function zip as the result of foo()
`

There was a previous lesson let you set a value for quux inside foo().
