### ISSUE TITLE
functional javascript workshop function spies

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1420]
I have two questions about syntax.  The official solution invokes the original method of the function and stores it as a variable like so:
`var originalFunction = target[method]`

But, according to w3schools, you access methods like this
`originalFunction = target.method();`

This is what I tried.  It did not work.  I seem to be misunderstanding something.

Also, the official solution uses function.prototype.apply instead of function.prototype.call.  But, the prompt says  method: a string with the name of the method on `target` to spy on.  I thought call was used for strings and apply was used for arrays.  I am so confused.

This is a very easy problem.  It only wants you to count each time the method for the object is invoked by overwriting the original method and adding an additional counting function.  For reference, the full official solution is below.  

``` js
function Spy(target, method) {
  var originalFunction = target[method]

  // use an object so we can pass by reference, not value
  // i.e. we can return result, but update count from this scope
  var result = {
    count: 0
  }

  // replace method with spy method
  target[method] = function() {
    result.count++ // track function was called
    return originalFunction.apply(this, arguments) // invoke original function
  }

  return result
}

module.exports = Spy
```

**Comment by tgfjt** [comment]
Hi, would you try this below to understand to access the propery of object?

```js
function sample(target, method) {
  console.log(method);
  console.log(target.method());
  console.log(target[method]);
}

sample(
  {
    method: function() {
      return 'this is target.method!';
    }
  },
  'this is "method"!!'
);


sample(
  {
    hello: function() {
      return 'hello!!';
    }
  },
  'hello'
);
```

**Comment by PWAckerman** [comment]
To piggyback on this question, what do function Spies have to do with the functional programming paradigm? I don't understand why they are a part of this workshop.

**Comment by ajw650** [comment]
It still says target.method() is not a function.

**Comment by pirfalt** [comment]
@ajw650 You can read properties (including methods) in two ways, `object.property` or `object['peroperty']`. If you know the name of the property at coding time you should normally use the `.` form, if you don't (say all you have is a string variable) you need to use the `[]` form.

```js
result = target.method()  // Invoke method and save result
result = target.method  // No invocation, just save the Function
result = target['method']()  // Invoke method and save result
result = target['method']  // No invocation, just save the Function
```

**Comment by ajw650** [comment]
I see thanks

**Comment by ajw650** [comment]
Can anyone explain the reason why the solution uses apply instead of call?

And why we need to create and return the result object instead of just returning a count variable?

Thanks

**Comment by pirfalt** [comment]
you could use `call` instead of `apply`, but you would have to know how many arguments you had since `call` takes positional arguments just like function invocation. While `apply` takes an array of arguments (or the "arraylike" arguments variable).

```js
// Exactly three arguments
function (arg0, arg1, arg2) {
  return originalFunction.call(this, arg0, arg1, arg2)
}

// Variable number of arguments
function () {
  return originalFunction.apply(this, arguments)
}
```

The reason we return an object with a count instead of just the count is so that we can change it after its returned from the spy function. Numbers are passed (including returned) by value, while objects are passed by reference. So 

```js
function clock() {
  var count = 0 // This local var will change.
  setInterval(function () {
    count++
  }, 500)
  return count
}
var zero = clock() // This returned copy will always be zero


function clockWorking() {
  var localObj = { count: 0 } // The count field in this local var will change.
  setInterval(function () {
    localObj.count++
  }, 500)
  return localObj
}
var object = clockWorking() // This returned reference points to `localObj`, reading or writing fields on `object` will change the `localObj` as well.
```

**Comment by ajw650** [comment]
Thank you so much.  I really appreciate the help.
