### ISSUE TITLE
learnyounode exercise 3: way of calculating lines

### ISSUE THREAD

**Issue by cinqs** [nodeschool/discussions#1423]
Hello everyone,
I am new to <code>node.js</code> and just tried 3rd exercise in learnyounode.
Here is my question:
for a file has 12 lines in total, it has 11<code>\n</code> in total,
So, if use <code>.split()</code> to an string by <code>\n</code>, it should resulted in 12 elements for an array. so the length should echo the real lines of a file, no need to <code>-1</code>.
Am I right?

**Comment by cerkiewny** [comment]
You are not right, the last character of a file is EOF and there is the '\n' prior to that added implicitely if you want to check this behaviour simply split the file and do the array print.

For my file:

```javascript
1  var fs = require('fs');
2  var name = process.argv[2];
3  var text = fs.readFileSync(name).toString();
4
5  var counter = 0;
6  var index = 0;
7  var tab = text.split('\n');
8  console.log( tab );
9 
10 console.log(counter);
```

The resulting array is:

```
[ 'var fs = require(\'fs\');',
  'var name = process.argv[2];',
  'var text = fs.readFileSync(name).toString();',
  '',
  'var counter = 0;',
  'var index = 0;',
  'var tab = text.split(\'\\n\');',
  'console.log( tab );',
  '',
  'console.log(counter);',
  '' ]
```

Notice the empty '' at the end the array is always one element bigger due to implicit \n at the end.

**Comment by jichangfeng67** [comment]
Thanks for your reply and so as what I learned, you mean whether you break or not in the end of a file, there will always be a <code>\n</code> in the end of the file?

**Comment by cerkiewny** [comment]
Yes that is what I mean.

**Comment by jichangfeng67** [comment]
Ah, Thanks. I got it.
