### ISSUE TITLE
learnyounode workshop exercise 7 httpclient

### ISSUE THREAD

**Issue by rock626** [nodeschool/discussions#1426]
I am having trouble with http client workshop.
Getting an error with command-line argument for process.argv[2] which worked for all previous workshops/exercises

var url = process.argv[2];
                      ^
TypeError: Cannot read property '2' of undefined
    at Object.<anonymous> (/Users/geethabujji/workspace/web/node/nodeschool/httpclient.js:10:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by cerkiewny** [comment]
Can you paste the entire program?

**Comment by rock626** [comment]
var http = require('http');

function process(response){
	response.setEncoding('utf-8');
	console.log("Got response "+response.statusCode);
	response.on("data",function(data){
		console.log(data);
	});
};
var url = process.argv[2];
http.get(url,process);

**Comment by cerkiewny** [comment]
change the name of your function from "process" to something else.

If you have two variables with a same name one is "hiding" the other
in your case you have a function named "process" and a module "process"
the interpreter can't tell the difference between a two so it will use the more local one.
And as such your "process" function has no "argv" member. This is also called
name collision if you have don it in mistake as you had.

I hope this helps.

**Comment by rock626** [comment]
thanks for the help..
