### ISSUE TITLE
scope-chains-closures doesn't work finely

### ISSUE THREAD

**Issue by CodeSourceiOSDev** [nodeschool/discussions#1427]
hi, I install this lesson globally and locally on folder, how to run and evaluate properly?

$npm install scope-chains-closures

it installs fine,

but to run it,[I only know to run it with] : $ node runner.js

how to run it?
documentation says:
$ scope-chains-closures # or, shorter: sccjs

but this wont work

also how to verify?

thanks

**Comment by cerkiewny** [comment]
If you use the "scope-chains-closure" in the console it should just work.

Works for me at least....
What operating system are you using?
If it did install correctly it looks like it is not on your "PATH" variable.

**Comment by tgfjt** [comment]
Hi:smile_cat:  Did you do a global install?
`npm install -g scope-chains-closures`

**Comment by CodeSourceiOSDev** [comment]
hi, Im using OSX,
Is fixed now,

I had to:
1. delete javascripting from modules [unmet dependecies]
2. install again scope-chains-closures
3. add my /Users/iosdev/npm-global/bin to /etc/paths

 Working now thanks!

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by CodeSourceiOSDev** [comment]
thanks a lot Guys! now to learn more node :]
