### ISSUE TITLE
array-filtering.js

### ISSUE THREAD

**Issue by danielle-b** [nodeschool/discussions#1429]
Hi everyone,
I can't seem to get this to pass. Everytime I try to pass it I get this message:

![javascripting](https://cloud.githubusercontent.com/assets/10361140/9703994/1e31448c-5463-11e5-875f-8462a5011bc4.JPG)

Here is my code:
```js
var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
var filtered = numbers.filter(evenNumbers(number)

function evenNumbers (number) {
    return number % 2 === 0;
}
console.log(filtered);
```

**Comment by SomeoneWeird** [comment]
You're very close, the issue you have is how you're trying to do `numbers.filter(evenNumbers(number)`. 
You need to pass a function to `numbers.filter`, so all you need to do is pass `evenNumbers` to it. Does this help? :)

**Comment by danielle-b** [comment]
That solved it! Thank you.

**Comment by SomeoneWeird** [comment]
:tada:
