### ISSUE TITLE
(Exercise 6 of 13) Not able to make my program modular :(

### ISSUE THREAD

**Issue by d3vil0p3r** [nodeschool/discussions#1430]
Hello Everyone, Here's my code for exercise 6 of learnyounode:

ex6m.js

``` javascript
var fs = require('fs')
var dir = require('path')
var path = process.argv[2]
var exten = '.'+process.argv[3]

function callback1(info){
    console.log(info);
}

function read(path, exten, callback1){
    fs.readdir(path, function(err, data){
        if (err){
            return callback1(err)
        }
        var book = data.toString().split(',')
        for (i=0; i<=book.length; i++){
            //console.log(book[i], dir.extname(book[i]));
            if (dir.extname(book[i]) === exten){
                console.log(book[i]);
            }
        }
    })
}
read(path, exten, callback1)
module.exports = read;
```

ex6.js

``` javascript
var mod = require('./ex6m')
function callback(datas){
    //console.log(datas)
}
mod(process.argv[2], process.argv[3], callback)
```

The problem is, whenever I'm running this via _learnyounode verify ex6.js_ (to verify the 6th exercise), it says "Your additional module file [ex6m.js] did not call the callback argument" and that "Your solution to MAKE IT MODULAR didn't pass. Try again!"

PLEASE HELP ME OUT! I'm actually enjoying this but I'm struck at this point, and yeah, node's awesome (^_^)

**Comment by davecocoa** [comment]
The expectation is that your module file `ex6m.js` will only export a function, it should not call the function and it should not access `process.argv`. The outer file, `ex6.js`, should call the function and log the result in the callback.
