### ISSUE TITLE
Question about buffer

### ISSUE THREAD

**Issue by bumi001** [nodeschool/discussions#1431]
console.log(new Buffer("a","ascii"));
prints
&lt;Buffer 61&gt;

It is printing utf-8 value. How can I make it print 97?

**Comment by bumi001** [comment]
console.log((new Buffer("a","ascii")[0]);
prints 97. So, it looks like 61 is the internal representation.

**Comment by SomeoneWeird** [comment]
`0x61` is the ASCII code for `a`. `0x65` is actually a capital `A`.
