### ISSUE TITLE
Getting errors when attempting to install tutorials

### ISSUE THREAD

**Issue by adam-griffiths** [nodeschool/discussions#1433]
Each Tutorial I attempt to install fails with similar errors, often a dependency or some such. Here is the error details for the basic javascripting tutorial.

npm http GET https://registry.npmjs.org/javascripting
npm http 200 https://registry.npmjs.org/javascripting
npm http GET https://registry.npmjs.org/javascripting/-/javascripting-2.1.0.tgz
npm http 200 https://registry.npmjs.org/javascripting/-/javascripting-2.1.0.tgz
npm http GET https://registry.npmjs.org/cli-md
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/diff
npm http GET https://registry.npmjs.org/workshopper-adventure
npm http 200 https://registry.npmjs.org/cli-md
npm http 200 https://registry.npmjs.org/diff
npm ERR! Error: No compatible version found: cli-md@'^0.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","1.0.0"]
npm ERR!     at installTargetsError (/Users/adam/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /Users/adam/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/Users/adam/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/adam/.nvm/v0.8.28/bin/node" "/Users/adam/.nvm/v0.8.28/bin/npm" "install" "-g" "javascripting"
npm ERR! cwd /Users/adam/Documents/node/01_Javascripting
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm http 200 https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/workshopper-adventure
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/adam/Documents/node/01_Javascripting/npm-debug.log
npm ERR! not ok code 0

...and again for the functional javascript tutorial...

npm http GET https://registry.npmjs.org/functional-javascript-workshop
npm http 304 https://registry.npmjs.org/functional-javascript-workshop
npm http GET https://registry.npmjs.org/deep-eql
npm http GET https://registry.npmjs.org/lorem-ipsum
npm http GET https://registry.npmjs.org/workshopper
npm http GET https://registry.npmjs.org/workshopper-exercise
npm http 304 https://registry.npmjs.org/lorem-ipsum
npm ERR! Error: No compatible version found: lorem-ipsum@'^1.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","1.0.0","1.0.1","1.0.2","1.0.3"]
npm ERR!     at installTargetsError (/Users/adam/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /Users/adam/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/Users/adam/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/adam/.nvm/v0.8.28/bin/node" "/Users/adam/.nvm/v0.8.28/bin/npm" "install" "-g" "functional-javascript-workshop"
npm ERR! cwd /Users/adam/Documents/node/func-jscript
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm http 304 https://registry.npmjs.org/workshopper-exercise
npm http 304 https://registry.npmjs.org/workshopper
npm http 304 https://registry.npmjs.org/deep-eql
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/adam/Documents/node/func-jscript/npm-debug.log
npm ERR! not ok code 0

Any assistance would be hugely appreciated.

**Comment by koustuvsinha** [comment]
Seems like npm upgradation might solve the issue : https://github.com/npm/npm/issues/4984
