### ISSUE TITLE
Learnyounode Baby steps

### ISSUE THREAD

**Issue by KawaiL** [nodeschool/discussions#1435]
console.log(process.argv);
var sum = 0;
for (var i = 2; i < (process.argv.length); i++){
  sum = sum + Number(process.argv[i]);
};
console.log ('The sum is ' +sum);
--------------
It ran fine with the run command, but as soon as I use the verify command, it fails on me. Any ideas? Thanks.
-------------
Mona-Lisa:lesson2_learnyounode kwli$ learnyounode run program2.js
[ '/usr/local/Cellar/node/0.12.7_1/bin/node',
  '/Users/kwli/Lesson2_learnyounode/program2.js',
  '33',
  '55',
  '32',
  '83',
  '96',
  '78',
  '44',
  '14',
  '86' ]
The sum is 521
Mona-Lisa:lesson2_learnyounode kwli$ learnyounode verify program2.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "[ '/usr/local/Cellar/node/0.12.7_1/bin/node'," !=    "192"                              
   "  '/Users/kwli/Lesson2_learnyounode/program2.js'," !=    ""                                 
   "  '77',"                           !=                                       
   "  '51' ]"                          !=                                       
   "The sum is 192"                    !=                                       
   ""                                  !=                                       

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to BABY STEPS didn't pass. Try again!

**Comment by davecocoa** [comment]
Well done for solving the challenge! I can see you successfully added the numbers together, which is great! Computers however, if I may flatter myself, are often not as perceptive as humans. In this case, the `learnyounode` program expects a very specific output, and it will fail if it sees anything even *slightly* different. Fortunately, it lists the expected output on the right, so you can see the difference between your output and the expected output.

So where your program outputs the contents of `process.argv` and then `'The sum is ' +sum`, `learnyounode` was expecting to see just a single number output. Do you think you can change your program so that its output looks more like `learnyounode`'s expectation?

**Comment by KawaiL** [comment]
I tried removing the extras 'The sum is ', and just printout the sum, still it did not verify, but ran okay. Suggestions?
--------------
console.log(process.argv);
var sum = 0;
for (var i = 2; i < process.argv.length; i++){
  sum = sum + Number(process.argv[i])
};
console.log (sum);
----------------
Mona-Lisa:lesson2_learnyounode kwli$ learnyounode run program2.js
[ '/usr/local/Cellar/node/0.12.7_1/bin/node',
  '/Users/kwli/Lesson2_learnyounode/program2.js',
  '75',
  '97',
  '39' ]
211
Mona-Lisa:lesson2_learnyounode kwli$ learnyounode verify program2.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "[ '/usr/local/Cellar/node/0.12.7_1/bin/node'," !=    "481"                              
   "  '/Users/kwli/Lesson2_learnyounode/program2.js'," !=    ""                                 
   "  '64',"                           !=                                       
   "  '12',"                           !=                                       
   "  '34',"                           !=                                       
   "  '3',"                            !=                                       
   "  '79',"                           !=                                       
   "  '40',"                           !=                                       
   "  '66',"                           !=                                       
   "  '1',"                            !=                                       
   "  '13',"                           !=                                       
   "  '93' ]"                          !=                                       
   "481"                               !=                                       
   ""                                  !=                                       

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to BABY STEPS didn't pass. Try again!

**Comment by davecocoa** [comment]
You're nearly there! Your program is still outputting (using `console.log`) more than just the final `sum`, can you find any other `console.log` statements that might be causing this problem?

**Comment by KawaiL** [comment]
I guess I misunderstood, I thought you need to call the process.argv first before it can be used. Anyway, I removed the first console.log(process.argv), and ran the program using the 'node program2.js 1 2 3 4', it ran okay. But using the 'learnyounode run program2.js' command, the return is 'NaN'. Any ideas? Thanks for all your help davecocoa!
---------
var sum = 0;
for (var i = 2; i < process.argv.length; i++){
  sum = sum + Number(process.argv[i])
};
console.log (sum);
---------------

**Comment by davecocoa** [comment]
Great progress! Yes, you can use `process.argv` in your program at any time. I'm afraid I don't know why you're getting `NaN` at this stage, I tried running the program on my machine and it worked fine with both `node program2.js 1 2 3 4` and `learnyounode run program2.js`. I would double check you're using the correct file name, and that you have definitely saved the file.

**Comment by KawaiL** [comment]
I ran it again and it worked. I really don't know why either. Yay! Finally I passed. Thanks for all your help Dave.

**Comment by davecocoa** [comment]
Excellent! Well done! :clap: :clap: :clap: :confetti_ball:
