### ISSUE TITLE
How to start nodeschool on windows?

### ISSUE THREAD

**Issue by Rylaihzh** [nodeschool/discussions#1436]
I used to install the nodeschool classes on Mac(not my PC).But when I install it on my dell,it ended suddenly when I try to open it on my terminal.What can I do?(BTW my English is poor,sorry :0 )

**Comment by SomeoneWeird** [comment]
How did you install them? How did you run them?

**Comment by Rylaihzh** [comment]
I installed them with "npm install --global javascripting".
I ran them in git bash.I opened ".cmd" files by clicking them twice.
