### ISSUE TITLE
Select Menu doesn't work

### ISSUE THREAD

**Issue by prijindal** [nodeschool/discussions#1438]
Select menu is not working on Win8.1
I am using iojs version 2.5.0 and npm version 2.13.2
I have tried it in CMD, git bash as well as in Power Sheell
It is opening and showing all the data, but arrow keys are not working and you can't actually select anything.

**Comment by prijindal** [comment]
Note: this is not working for any modules
I have tested it for javascripting, learnyounode and how-to-npm

**Comment by prijindal** [comment]
I tried to update my npm version to 2.14.3 but still this is not working

**Comment by SomeoneWeird** [comment]
Try updating to node 4.0.0.

**Comment by mneston** [comment]
I am have the same problem.
My node version is 4.0.0 and I am using Windows 10 but I can't navigate on Start Menu

**Comment by mneston** [comment]
I tried on my other computer with Ubuntu 15.04 and i couldn't run.
After typing 'javascripting' the workshop did not open

**Comment by mneston** [comment]
I solved this. I am using Node v0.10.36 on Windows

**Comment by SomeoneWeird** [comment]
Did nothing happen? Are you able to screenshot?

**Comment by amit133** [comment]
@mneston, what is your solution?

**Comment by mneston** [comment]
i don't have solution yet, i only tried using an older version and worked
very well.

Em dom, 13 de set de 2015 às 21:06, amit133 <notifications@github.com>
escreveu:

**Comment by SomeoneWeird** [comment]
It seems to be a combination of Windows 10 + Node 4. I'll look into it tomorrow hopefully.

**Comment by TylerMoeller** [comment]
If it helps, the Expressworks workshop runs fine. It's the only one I've found so far with a functional menu on Win10.

**Comment by SomeoneWeird** [comment]
#1448

**Comment by chris567** [comment]
I had the same problem with node 5.0.0 on windows 10

**Comment by SomeoneWeird** [comment]
Yes, this was fixed in 5.1.0

**Comment by karanjoisher** [comment]
Having the same issue on Windows 10, node v.5.7.0 and npm v3.7.5

**Comment by robert23mg** [comment]
I also had the same problem with the menu not working for any module.
I fixed this by removing node (v5.8) and reinstalling it (v4.4.0) and the menus are working again.
