### ISSUE TITLE
How to install nodejs v4.0.0 in Ubuntu

### ISSUE THREAD

**Issue by silverbolt2014** [nodeschool/discussions#1439]
Hello,
I am trying to install nodejs on a new install of ubuntu 14.04 64 bit virtual machine.
i went to nodejs.org and downloaded the following file
https://nodejs.org/dist/latest/node-v4.0.0-linux-x64.tar.gz

I ran the following command
$ gunzip node-v4.0.0-linux-x64.tar.gz
$ tar -xvf node-v4.0.0-linux-x64.tar

A directory is created called "node-v4.0.0-linux-x64"
However I am confused as to what I need to do next.
I "cd"ed into the directory
And here is what I see:
![image_node1](https://cloud.githubusercontent.com/assets/7999722/9770253/24ce1814-56fd-11e5-9352-66bff2ca226d.png)

Could someone please advice me on what to do next.  Other articles I found online seem to reference older versions of nodejs.

**Comment by TylerMoeller** [comment]
Try this:

1. `wget http://nodejs.org/dist/latest/node-v4.0.0-linux-x64.tar.gz`
2. `tar -C /usr/local --strip-components 1 -xzf node-v4.0.0-linux-x64.tar.gz`
3. `ls -l /usr/local/bin/node`
4. `ls -l /usr/local/bin/npm`

**Comment by silverbolt2014** [comment]
Thanks that worked!
I want to add that I added "sudo " at the beginning of the second line to get it to work.
