### ISSUE TITLE
Not able to navigate through the guides of workshoppers with node.js v4.0.0

### ISSUE THREAD

**Issue by amit133** [nodeschool/discussions#1442]
I upgraded node.js to v4.0.0. The menu options in the guide of a workshopper (I tried javascripting, git-it and learnyounode) open up whenever I try to execute the workshopper. However, it does not allow to navigate to various challenges listed in that menu. Even the exit is not allowed until I close it using ctrl^c

![capture](https://cloud.githubusercontent.com/assets/10413604/9828569/af554068-58ef-11e5-8682-bca394f9eaf2.PNG)

It is working fine with an older version of node.js v0.12.7

Operating System: Windows10 Pro

**Comment by SomeoneWeird** [comment]
#1448
