### ISSUE TITLE
Learnyounode - HTTP CLIENT official solution doesn't seem right.

### ISSUE THREAD

**Issue by danielinux7** [nodeschool/discussions#1444]
The official solution seems to be missing the data as an argument to console.log. 

   var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log) <<< console.log(data)
      response.on('error', console.error)
    })

**Comment by davecocoa** [comment]
Have you tried running the solution with your suggested change?

**Comment by danielinux7** [comment]
Yes.

**Comment by SomeoneWeird** [comment]
Your suggested change won't work, but I don't think the official solution is right either, unless it's doing some tricky binding stuff in the background (and if it's what you've posted)

**Comment by danielinux7** [comment]
A picture is worth a thousand word.

![image](https://cloud.githubusercontent.com/assets/2645266/9843627/c560d6ae-5a81-11e5-8f70-0cf0c9d4ca2d.png)

**Comment by SomeoneWeird** [comment]
Okay, the official solution does work. What issues are you having?

**Comment by danielinux7** [comment]
This is my solution passing!

**Comment by SomeoneWeird** [comment]
Sorry I'm confused. You're suggesting that the official solution is incorrect and `console.log)` should be replaced with `console.log(data);` correct?

**Comment by danielinux7** [comment]
I was. 
Now that I'm looking at it again, I think both solutions are correct, though the official solution solution is cool.

The official solution is doing something similar to this:
print('something to be printed', console.log);
function print(str,callback){
callback.call(console,str);
}

**Comment by SomeoneWeird** [comment]
Can you paste the code for your solution? Because I don't see how it can work how you've said it does.

**Comment by danielinux7** [comment]
var http  = require('http');
var url = process.argv[2];
http.get(url, function(res){
  res.setEncoding('utf8');
  res.on('data',function(data){
    console.log(data);
  });
  res.on('error',function(error){
    console.error('This is the error message:' + error);
  });
});

**Comment by SomeoneWeird** [comment]
Oh! Yes. That works. I thought you were doing something like
```js
res.on('data', console.log(data));
```

Both your solution are doing pretty much exactly the same, the official solution is just passing the `console.log` function directly as a callback, while you are calling it explicitly.

**Comment by danielinux7** [comment]
My bad, I should've given more illustration, but hey, I learned something today!

**Comment by SomeoneWeird** [comment]
No problem :)
