### ISSUE TITLE
BABY STEPS-learnyounode

### ISSUE THREAD

**Issue by CostasChaitas** [nodeschool/discussions#1445]
var sum;

for(var i=2; i<process.argv.length; i++){
    sum += Number(process.argv[i]);
}

console.log(sum);

whats the wrong with my code?can you help me?

**Comment by cerkiewny** [comment]
You define the Sum but not assign any value to it at the beginning. 

And as you may know the summation is not only based on the things passed but also on the type
of the things you are summing. For instance if you are summing integer with a integer the result is 
integer. If you are adding the floating value to the integer result is floating point.

But if you are adding the color to a car what the result should be?

In your case the var sum is defined but it's type is not so it is seen as not a number.
If you are adding a integer to not a number the result is not a number, so you need to 
define the sum as  0 at the beginning.

Hope it helps.

**Comment by daniellevine** [comment]
Yep, @rasakos you need to define the sum as 0 as @cerkiewny mentions. You can try out the code here: https://tonicdev.com/daniel/issue-1445
