### ISSUE TITLE
learnyounode http collect issue

### ISSUE THREAD

**Issue by orphord** [nodeschool/discussions#1446]
Hey-
I hope I'm posting this in the right place, but I am confident that I followed the instructions of the http collect (number 8) of the learnyounode series, but the verify tests failed.

I'm using node 4.0 on Ubuntu 15.04 and tested a few (ie > 2) solutions that I found searching and they produced the same output as I did, as follows:
orphord@AndrePosse:~/Dropbox/Programming/Node/LearnYouNode$ learnyounode verify learn8.js 

Your submission results compared to the expected:

```
             ACTUAL                                 EXPECTED                
```

────────────────────────────────────────────────────────────────────────────────

   "68"                                !=    "Ridgy-didge"  
   "Ridgy-didgeBush bashBikkieBig SmokeSpewin'MoolahDunnyBrekkieSnagKero" !=    "Bush bash"  
   ""                                  !=    "Bikkie"  
                                       !=    "Spewin'"  
                                       !=    "Moolah"  
                                       !=    "Dunny"  
                                       !=    "Brekkie"  
                                       !=    "Snag"  
                                       !=    "Kero"  
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────
✗ Submission results did not match expected!
# FAIL

Your solution to HTTP CLIENT didn't pass. Try again!

Can anyone advise?  I'm enjoying the process, and would minimally like to move on to number 9.

Thanks very much.
Jeff

**Comment by cerkiewny** [comment]
Please provide the code it looks like your code is not splitting the words correctly, rather then this it is merging everything into one blob of text and then printing the number of its letters and entire text.

But I can't tell why it is behaving in this way until I will see a code.

Regards

**Comment by orphord** [comment]
//var http = require('http');
//
//var URL = process.argv[2];
//
//http.get(URL, function(res) {
// var result = '';
// res.setEncoding('utf8');
// res.on('data', function(data) {
// result += data;
// });
// res.on('end', function() {
// console.log(result.length);
// console.log(result);
// });
// res.on('error', console.error);
//});

// One of the solutions from the web
var http = require('http')
var bl = require('bl')
http.get(process.argv[2],
function (request) {
 request.pipe(bl(function (err, data) {
 if (err) return console.error(data) data = data.toString()
console.log(data.length) console.log(data) })) })

**Comment by orphord** [comment]
Sorry, I hit send without finishing formatting and explaining myself.

The top commented out code is my solution, and the bottom code is the code
I found when I searched for a solution.

Thanks.
Jeff

**Comment by cerkiewny** [comment]
Your code is working fine for me, are you sure you are not just checking the code with wrong exercise?

To verify which one you have currently selected type learnyounode print.

**Comment by cerkiewny** [comment]
It looks like you have exercise 7 selected and you are trying to check exercise 8 code with the 7th, type the learnyounode and select the http collect exercise before verifying this should be all you need to do.

Regards

**Comment by orphord** [comment]
Woah!  Really?  Is there any way you can send me the text of the test
result?

I am away from that machine right now, but am 98% certain that it was the
right exercise as I kept bringing up the directions to make sure I was
following the requirements properly.

Thank you I'll double check when I get home.
Jeff

**Comment by cerkiewny** [comment]
I get nearly the same error if i run it with exercise 7,
If i do it with exercise 8 it is running along nicely
```
 "73"                                !=    "Stoked"                           
   "StokedCrookCactus mateSlabAmber fluidGarboMoolahWobblyHit the turpsRipper" !=    "Crook"                            
   ""                                  !=    "Cactus mate"                      
                                       !=    "Amber fluid"                      
                                       !=    "Garbo"                            
                                       !=    "Moolah"                           
                                       !=    "Wobbly"                           
                                       !=    "Hit the turps"                    
                                       !=    "Ripper"                           
                                       !=    ""             
```

With 7 selected.

```
1.  ACTUAL:    "467"
1.  EXPECTED:  "467"

2.  ACTUAL:    "We're going cut snake flamin watch out for the fairy floss. As cross as a mate mate mad as a thongs. You little ripper franger with flat out like a wobbly. She'll be right slacker mate gutful of ankle biter."
2.  EXPECTED:  "We're going cut snake flamin watch out for the fairy floss. As cross as a mate mate mad as a thongs. You little ripper franger with flat out like a wobbly. She'll be right slacker mate gutful of ankle biter."

3.  ACTUAL:    "Shazza got us some hottie how watch out for the bizzo. Mad as a divvy van bloody lets throw a buck's night. As dry as a barrack and she'll be right flanno. We're going shazza where he hasn't got a blow in the bag. As busy as a dag also built like a offsider. "
3.  EXPECTED:  "Shazza got us some hottie how watch out for the bizzo. Mad as a divvy van bloody lets throw a buck's night. As dry as a barrack and she'll be right flanno. We're going shazza where he hasn't got a blow in the bag. As busy as a dag also built like a offsider. "

4.  ACTUAL:    ""
4.  EXPECTED:  ""

```

With 8 selected.

Regards

**Comment by orphord** [comment]
Wow, could I be that much of a dumba$$??  Sorry again, and thank you.

**Comment by cerkiewny** [comment]
Well, glad to be of help. Good luck!

**Comment by orphord** [comment]
Thank you again, really enjoy the product (outside of my own incompetence).
:-)
