### ISSUE TITLE
Tests pass when no input is provided

### ISSUE THREAD

**Issue by herschel666** [nodeschool/discussions#145]
While hacking on the Stream-Adventure challenges it occured twice, that I passed a challenge due to missing input. "Actual" was an empty string as well as "Expected". So the test passes though I didn't find the correct solution.

![stream-adventure](https://f.cloud.github.com/assets/520258/1846769/aef4569c-7618-11e3-89d5-ef7b37baa68b.png)

Maybe it should be checked during verifying if there's input at all.

Best regards & thanks for the great node learning resource!

**Comment by Sequoia** [comment]
Does this need per-workshop impl or can it be built in as a `workshopper` feature? /cc @rvagg

**Comment by rvagg** [comment]
Probably a combination of changes in workshopper and individual workshoppers. These should probably be treated as bugs and filed against the parent repos.

**Comment by Sequoia** [comment]
looks like this is tracked here: https://github.com/substack/stream-adventure/issues/53
