### ISSUE TITLE
Cannot Navigate To Different Exercises in Learnyounode

### ISSUE THREAD

**Issue by darthink** [nodeschool/discussions#1451]
Hello there, 

I'm going through the "Learnyounode" tutorial, and I've completed the first, but I cannot access the others. I simply cannot use the arrow keys, or any key for that matter, to choose the next exercise. I've uninstalled/re-installed node.js, I've used a different Windows computer. Nothing. 

Any suggestions? 

![screenshot 2015-09-17 12 07 34](https://cloud.githubusercontent.com/assets/1986347/9938725/b1ebfe2c-5d34-11e5-9776-f84459679c6d.png)

Thanks!
Kenny

**Comment by SomeoneWeird** [comment]
Known issue #1448

**Comment by iplusplus** [comment]
Me too.  So annoying.

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0

**Comment by JavaSlasher** [comment]
I had the same problem. Looks like there is bug in newer versions of Node.js. Steps I followed, try n let me know.
- go to https://nodejs.org/dist/v4.4.3/node-v4.4.3-x86.msi
- after installing got to nodejs command prompt and type  "npm install npm -g"
- npm install learnyounode -g
- learnyounode

viola!!! it works.
