### ISSUE TITLE
Juggling async

### ISSUE THREAD

**Issue by dancancro** [nodeschool/discussions#1453]
I would like this to work, but it doesn't. The idea is to concatenate chunks in the 'data' events. Then when this is finished in the 'end' events put the full response text in a map keyed on the url. Finally after all 3 responses are in the map, loop through them in the order of the input, and look up the response text for each url.

But I don't know how to retrieve the request url from the response object.

```javascript
var http = require('http');
var responses = {"length": 0};

function callback(res) {
    res.setEncoding('utf8');

    var str = '';

    res.on('data', function (chunk) {
      str += chunk;
    });

    res.on('end', function () {
      responses[res.url] = str;    // Here, I want to save the full response text keyed by the url, but 
      responses.length++;         // I don't know how to retrieve the url
      if (responses.length == 3) {
        for (var j = 2; j < 5; ++j) {
          console.log(responses[process.argv[j]])  // Here it looks up the correct response for a given url
        }
      }
    });
  }



function myhttp(i) {
    http.get(process.argv[i], callback).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(j);
}
```

**Comment by cerkiewny** [comment]
Instead of getting the url from the res you could just use some number.

So the trick is to pass the number to a callback function,
In fact there is no method of "expanding" the callback by another parameter.
Ok, how about adding the additional parameter inside the function which will be called.

We can do this instead.

So, instead of calling callback, we will call anonymous function and pass the number, (or url if you prefer it).


So how to create the function which will be passing the additional parameter?

We will change this calling of "callback" to call of the anonymous function which will add 
additional parameter:

```javascript
function myhttp(i) {
    http.get(process.argv[i], callback).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}
```

To:

```javascript
function myhttp(i) {
    http.get(process.argv[i], function(res){callback(res, url)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}
```

Now this will change the callback function to have additional parameter:

```javascript
function callback(res, number){
 console.log(number);
}
```

If you decide to pass the url instead you can do it as well, for instance like this:
```javascript
function myhttp(url, i) {
    http.get(process.argv[i], function(res){callback(res, url)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(process.argv[j], j);
}
```

Hope it helps.

**Comment by dancancro** [comment]
Thanks. I don't understand this on a number of levels. I'll start with just this one...

Why do you have to pass both `process.argv[j]` and `j` to myhttp? Why won't the following work?

```javascript
function myhttp(i) {
    http.get(process.argv[i], function(res){callback(res, process.argv[i])}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(j);
}
```
or
```javascript
function myhttp(i) {
    var url = process.argv[i];
    http.get(process.argv[i], function(res){callback(res, url)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(j);
}
```

or

```javascript
function myhttp(url) {
    http.get(url, function(res){callback(res, url)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(process.argv[j]);
}
```

I replaced your anonymous function with a named one, but suspect that this is not possible and I don't know why. Leaving myhttp with two parameters it would look like the following. Why can't I use a named function here? Under what conditions must you use anonymous functions?
```javascript
function myhttp(url, i) {
    http.get(process.argv[i], callback1).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
} 
```

Actually, I'd rather shave a day off the Q&A cycle, so here's another part I don't get. Which of the three values of `url` will be used in this part at the later time when `callback(res, url)` is executed from within http.get(), and why?

```javascript
function myhttp(url, i) {
    http.get(process.argv[i], function(res){callback(res, url)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}
```

If `url` gets a fixed value (process.argv[2], process.argv[3], or process.argv[4]) at the time the loop is running, why is it treated differently from `res`, the other parameter, which gets a value at the later time the response comes back?

**In higher order Javascript it's really hard to know when and from where symbols are getting their values and what is in scope at a given spot in your code.**

Here's what I want to work now. It doesn't.

```javascript
var http = require('http');
var resps = ['','',''];
var respCounter = 0;

function callback1(res) {
  callback2(res, number);
}

function callback2(res, number) {
    res.setEncoding('utf8');

    var str = '';

    res.on('data', function (chunk) {
      str += chunk;
    });

    res.on('end', function () {
      resps[number] = str;
      respCounter++;
      if (respCounter== 3) {
        resps.forEach(function(resp) {console.log(resp);})
      }
    });
  }



function myhttp(i) {
    http.get(process.argv[i], callback1).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(j);
}
```

**Comment by dancancro** [comment]
Okay, I got it using my original approach - a map object and retrieving the request URL from the response, then looping through items in the original order. 

To get the request URL from the response, use `"http://" + res.req.getHeader("Host")` 

@cerkiewny I'm afraid I still don't understand your approach. I'm quite sure that you cannot add another parameter to the callback function as you described.

Incidentally, the official solution uses the 'bl' library even though the hints say to not use any external libraries for this.

**Comment by davecocoa** [comment]
Hi @dancancro , glad you found a solution. I'll try and answer some of the questions you had.

> I replaced your anonymous function with a named one, but suspect that this is not possible and I don't know why. Leaving myhttp with two parameters it would look like the following. Why can't I use a named function here? Under what conditions must you use anonymous functions?

Why do you suspect it's not possible? You *can* use a named function here. You can use a named function anywhere that you can use an anonymous function. What matters is *where* you define the function. I recommend this article about [scope and context](http://ryanmorr.com/understanding-scope-and-context-in-javascript/) if you want to learn more in this area.

```js
function myhttp(url, i) {
    http.get(process.argv[i], callback1).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
} 
// this won't work, i is not in scope
function callback1(res){ callback(res, i); }
```

```js
function myhttp(url, i) {
    http.get(process.argv[i], callback1).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
  // this works fine, i is in scope
  function callback1(res){ callback(res, i); }
}
```

> Actually, I'd rather shave a day off the Q&A cycle, so here's another part I don't get. Which of the three values of url will be used in this part at the later time when callback(res, url) is executed from within http.get(), and why?

Whichever value of `url` was passed into `myhttp` corresponding to this call to `http.get()`. Essentially, you get a fresh set of variables every time you call a function, and they are kept consistent with function nesting. Here's an example:

```js
function saveThenLog(str){
  return function(){
    console.log(str);
  };
}
var call1 = saveThenLog('Hi there!');
var call2 = saveThenLog('Bye now!');

// at this stage, there are two different values of str, but they are kept separate.
call1(); // Hi there!
call2(); // Bye now!
```

> If url gets a fixed value (process.argv[2], process.argv[3], or process.argv[4]) at the time the loop is running, why is it treated differently from res, the other parameter, which gets a value at the later time the response comes back?

`url` and `res` are different because they are arguments to different functions. `url` gets a value when `myhttp` is called, `res` gets a value when `callback1` is called.

> In higher order Javascript it's really hard to know when and from where symbols are getting their values and what is in scope at a given spot in your code.

You are absolutely right! This is why people often go to great effort to avoid nesting their javascript too deep, often referred to as [callback hell](http://callbackhell.com/). I can see you have tried to tidy up your code with named functions, but you were caught out with scope problems. There is a trick you can use in this case to quickly create modified versions of your functions using [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FFunction%2Fbind):

```js
var http = require('http');
var resps = ['','',''];
var respCounter = 0;

function callback1(res) {
  callback2(res, number);
}

function callback2(number, res) {
    res.setEncoding('utf8');

    var str = '';

    res.on('data', function (chunk) {
      str += chunk;
    });

    res.on('end', function () {
      resps[number] = str;
      respCounter++;
      if (respCounter== 3) {
        resps.forEach(function(resp) {console.log(resp);})
      }
    });
  }



function myhttp(i) {
    http.get(process.argv[i], callback2.bind(null, i)).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

for (var j = 2; j < 5; ++j) {
  myhttp(j);
}
```
[`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FFunction%2Fbind) basically allows you to 'curry' functions, an idea you learn more about in the functional javascript workshop, if you're interested =)

**Comment by dancancro** [comment]
@davecocoa

> Why do you suspect it's not possible?

I guessed it was impoosible thinking that this is how @cerkiewny passed the values of `url` from the loop into the callback. I'm glad I was wrong about that because it didn't make sense.

> url and res are different because they are arguments to different functions. url gets a value when myhttp is called, res gets a value when callback1 is called.

I was referring to @cerkiewny 's 
function myhttp(url, i) {
     http.get(process.argv[i], function(res){callback(**res, url**)}).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}

They look like parameters to the same function to me. They're right next to each other within the same parentheses. So I'm confused why how they get values works differently. `callback` is executed after the loop has finished, and `url` seems to take the value that was available during the specific iteration while the loop was running, but `res` doesn't get a value until later. Had a value for `res` been passed to myhttp, would that be the value of `res` later on when `callback` runs which would then be overwritten by a different `res` provided by http.get()?

> I can see you have tried to tidy up your code with named functions, but you were caught out with scope problems.

This seems like a consequence of moving the function, rather than giving it a name. So if I had put it inside the myhttp function it may have worked.

**Comment by davecocoa** [comment]
> I was referring to @cerkiewny 's 
```js
function myhttp(url, i) {
http.get(process.argv[i], function(res){callback(res, url)}).on('error', function(err) {
console.error("Got error: " + err.message);
});
}
```
>They look like parameters to the same function to me. They're right next to each other within the same parentheses. So I'm confused why how they get values works differently. callback is executed after the loop has finished, and url seems to take the value that was available during the specific iteration while the loop was running, but res doesn't get a value until later. Had a value for res been passed to myhttp, would that be the value of res later on when callback runs which would then be overwritten by a different res provided by http.get()?

If a value for `res` had been passed to `myhttp`, just as with `url`, it could not have been overwritten by later calls to `myhttp`. Everytime we use `function`, we are creating a new function, with its own scope. So every time you're calling `http.get`, you are passing in a *different* function, with a different scope, and different variables. There can never be any mixing or overwriting. This is why the location of the function definition matters - if the function is defined globally, you are passing in the *same* function to `http.get`, but if the function is defined inside `myhttp`, you get a new function definition on every run.

As far as `callback` is concerned, yes, `res` and `url` arrive at the same time, and can be accessed at the same time. However, from `myhttp`'s perspective, `res` does not exist at all. The anonymous callback has a scope which includes `url` from `myhttp` and its own `res` passed in by `http.get`.

The timing is not the important point here, only the function nesting and calling. Basically, you get a totally different set of variables every time a function is called, they are not shared at all. By variables here, I mean arguments passed in and new variables created using `var`. How about a more complex example:

```js
function createAdder(initialNumber){
  var increment = initialNumber
  return function add(optionalIncrement){
    if(optionalIncrement){ increment = optionalIncrement; }
    initialNumber = initialNumber + increment;
    return initialNumber;
  };
}

var a1 = createAdder(1); // a1 has an increment of 1
var a2 = createAdder(2); // a2 has an increment of 2

console.log(a1());   // 2   (a1's increment is still 1)
console.log(a1());   // 3   (a1's increment is still 1)
console.log(a2());   // 4   (a2's increment is 2)
console.log(a2(7)); // 11 (a2's increment is now 7)
console.log(a1());   // 4   (a1's increment is still 1)
console.log(a1(4)); // 8   (a1's increment is now 4)
console.log(a2());   // 18 (a2's increment is still 7)
```
Even though there are two copies of `initialNumber` and `increment`, they are kept totally separate and never interact, timing will not change this. In contrast, if there was a variable defined at a scope shared by `a1` and `a2` (the global scope), then they would both be able to change it and timing would be very important.

**Comment by iam-peekay** [comment]
duh, thank you! ;)

I got this to work: 

```javascript
var bl = require('bl');
var http = require('http');
var resObj = {};
var curIndex = 0;

var callback = function (res, i) {
  res.setEncoding('utf8');
  res.pipe(bl(function (err, data) { 
    if (err) {
      return console.error(err);
    }
    data = data.toString();
    resObj[i] = data;
    curIndex++;

    if (curIndex === 3) {
      for (var k = 2; k < 5; k++) {
        console.log(resObj[k]);
      } 
    }
  }));
};

function myhttp(i) {
  http.get(process.argv[i], function (res) { callback(res, i) }).on('error', function(err) {
    console.error('Got error: ' + err.message);
  });
}

for (var j = 2; j < 5; j++) {
  myhttp(j);
}
```

**Comment by davecocoa** [comment]
Woo! Well done! :clap: :tada: :confetti_ball:
