### ISSUE TITLE
Error when running javascripting

### ISSUE THREAD

**Issue by kevtakaoka** [nodeschool/discussions#1454]
I'm trying to learn javascript and ran

javascripting

but the below error came up:

-bash: javascripting: command not found

Could anyone know how to fix it?

Thanks,
Kevin

**Comment by zhdzmn** [comment]
did you do `npm install javascripting -g` ?

**Comment by kevtakaoka** [comment]
Thanks, zhdzmn. Yes I did. I have found out the issue in PATH and fixed it. Thanks anyways!

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by zhdzmn** [comment]
Welcome to javascript :)
