### ISSUE TITLE
javascripting -   No such file or directory

### ISSUE THREAD

**Issue by MaximDzhezhelo** [nodeschool/discussions#1456]
When I Open your terminal and run the following command:   javascripting
 I not  see the menu: 
Answer : /usr/bin/env: node: Нет такого файла или каталога
      eng.                                No such file or directory

what am I doing wrong&

**Comment by koustuvsinha** [comment]
Please provide system info. Also, did you install it via `npm install -g javascripting` , having the `-g` flag ?

**Comment by akimsullec** [comment]
sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by MaximDzhezhelo** [comment]
very big thanks)
