### ISSUE TITLE
Can't move using arrow keys

### ISSUE THREAD

**Issue by jsk5755** [nodeschool/discussions#1457]
I discovered nodeschool.io yesterday and installed javascripting. When the list of topics appear in blue screen, i can not move up or down using arrow keys. Is there something i am doing wrong?

Thank You.

**Comment by TylerMoeller** [comment]
Assuming you are on Windows 10, this is a known issue under investigation. https://github.com/nodeschool/discussions/issues/1448

To see all open issues, visit: https://github.com/nodeschool/discussions/issues

**Comment by slurricane** [comment]
try c9.io for windows nodeschool

**Comment by stefanstranger** [comment]
Hi found a workaround to get it working on Windows 10 using Console2. 

See https://github.com/nodeschool/discussions/issues/1476

HTH
Stefan

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0
