### ISSUE TITLE
lololodash: getting started issue

### ISSUE THREAD

**Issue by metasean** [nodeschool/discussions#1461]
I'm on the very first exercise in lololodash and I can't figure out what I'm doing wrong, and frustratingly, don't even know where to start looking for help.

For what it's worth:
 - My `node -v` is `v0.12.0`
 - I installed lodash globally and restarted my terminal.

My '01.js':
```
// include the Lo-Dash library
var _ = require("lodash");

// do awesome stuff in the worker
var worker = function(c) {
	_.where(c, { 'active': true });
};

// export the worker function as a nodejs module
module.exports = worker;
```

The (not so informative) result of `lololodash run 01.js`:
```
-------------------
Input
[ { "id": 22,
  "username": "martin",
  "active": true },
 { "id": 23,
  "username": "max",
  "active": false },
 { "id": 24,
  "username": "linda",
  "active": false }]
-------------------
Output
undefined
-------------------
Output should be:
[ { "id": 22,
  "username": "martin",
  "active": true }]
-------------------
✗ Test
```

This seems like a really simple exercise.  The exercise itself is specifying to "give back only
the active users (active === true)", but I've also tried specific ids, specific usernames, none of which seems to matter (or help) because all I get is 'undefined'.  On the chance that my variable name was causing a conflict I've tried a range of variable names (`l`, `c`, `list`, `collection`, even `randomLongNonConflictingVar`); still, all I get is 'undefined'.

*What <undoubtedly, terribly, obvious thing> am I missing?*

**Comment by koddsson** [comment]
Hey @metasean. 

You've almost got it, the return value of the function that's exported in your code is `undefined` though.

**Comment by metasean** [comment]
@koddsson - Thank you!  (I knew it had to be something blatantly obvious.)

**Comment by koddsson** [comment]
Glad to be of assistance :smile: :tada: :100:
