### ISSUE TITLE
Chapter on Tabasco, México.

### ISSUE THREAD

**Issue by gartox** [nodeschool/discussions#1467]
Someone in Tabasco to start a chapter of node school or one previously created?.

I want to share about NodeJS and I'm interested on meet someone located on Tabasco in the south of México. Or how can I create a chapter here?

**Comment by mikeal** [comment]
@maxogden can you set this up, i'm not an owner in the org anymore :(

**Comment by SomeoneWeird** [comment]
@gartox Done, you need to accept the invite.

@mikeal You are :)

**Comment by mikeal** [comment]
since when? i was removed in the "great migration" after the accidental org delete :)

**Comment by gartox** [comment]
Thanks @SomeoneWeird.
