### ISSUE TITLE
'learn-sass' final challenge verification issue

### ISSUE THREAD

**Issue by d3moid** [nodeschool/discussions#1468]
This was my first workshop and found the challenges very educating :+1:  

I believe there's a minor verification issue on exercise 12 "WHILE LOOP" 

The verification expects the while loop to generate headings in order from 1 to 6 whereas the actual output using a while loop would generate headings from 6 to 1. 

**VERIFICATION (ACTUAL vs EXPECTED)**

   "h6 {"                              !=    "h1 {"
   "  font-size: 6px; }"               !=    "  font-size: 21px; }"

   "h5 {"                              !=    "h2 {"
   "  font-size: 9px; }"               !=    "  font-size: 18px; }"

   "h4 {"                              !=    "h3 {"
   "  font-size: 12px; }"              !=    "  font-size: 15px; }"

   "h3 {"                              !=    "h4 {"
   "  font-size: 15px; }"              !=    "  font-size: 12px; }"

   "h2 {"                              !=    "h5 {"
   "  font-size: 18px; }"              !=    "  font-size: 9px; }"

   "h1 {"                              !=    "h6 {"
   "  font-size: 21px; }"              !=    "  font-size: 6px; }"

My code:
`
$i: 6;
@while $i > 0 {
	h#{$i} {
		font-size: 24px - 3px * $i;
	}
	$i: $i - 1;
}
`

This was my first hands-on experience with SASS so I might be wrong.

Whatever the case thanks you for making this! Really helped me out.

**Comment by gaboesquivel** [comment]
run the loop 1 to 6 instead of 6 to 1, like this

`$i: 1; @while $i <= 6 { h#{$i} { font-size: 24px - 3px * $i; } $i: $i + 1; } `

http://sassmeister.com/gist/0cc7509638f95ad4951e

**Comment by d3moid** [comment]
Many thanks! I had a feeling I was missing something. 

Thanks for sharing sassmeister.com also. It'll prove useful going forward.
