### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by neilscudder** [nodeschool/discussions#1472]
console.log "hello" 

Does not work, yet it is the first code in the first lesson of the two projects I checked, J
javascripting and learnyounode.

console.log ("hello") 

Does work.   Why are there no parenthesis in the lesson text? 

Forgive the messy screenshot, I tested on desktop too.

![screenshot_2015-10-02-17-39-59](https://cloud.githubusercontent.com/assets/7809818/10260565/d02e34be-692c-11e5-9704-51674b9d6800.png)

**Comment by neilscudder** [comment]
It was the solarized palette - the parenthesis are there, I just could not see them. And I tried in two different terminals, I just love solarized.

**Comment by tgfjt** [comment]
Thank you for your report!
Related issue: https://github.com/workshopper/learnyounode/issues/96
