### ISSUE TITLE
Error: Cannot find module 'workshopper/node_modules/colors-tmpl' - lololodash

### ISSUE THREAD

**Issue by imwithsam** [nodeschool/discussions#1473]
I was able to install and finish the javascripting tutorial. I installed the lololodash tutorial with `npm install -g lololodash`, seemingly without any issues, but after I select any of the lololodash exercises I receive the following error:

```
Error: Cannot find module 'workshopper/node_modules/colors-tmpl'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/lololodash/lib/verify.js:9:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by gaboesquivel** [comment]
What is your node version and OS ?

**Comment by imwithsam** [comment]
npm 3.3.5
Node 4.1.1
OS X Yosemite (10.10.5)

**Comment by koddsson** [comment]
Weird. I just tried re-producing this with the same setup but it seems to be working for me.

**Comment by imwithsam** [comment]
I tried uninstalling and reinstalling, but I still get the same error message.

**Comment by gaboesquivel** [comment]
Yes, same here... same setup.. installation works fine. 
what output do you get on the console when you type `npm ls -global lololodash` ?

**Comment by imwithsam** [comment]
/usr/local/lib
└── lololodash@0.6.0

**Comment by gaboesquivel** [comment]
you can try going to `/user/local/lib//lib/node_modules/lololodash`  delete the `node_modules` folder and then run `npm install` inside that lololodash directory.

**Comment by imwithsam** [comment]
I still get the same error.

**Comment by imwithsam** [comment]
Inside the `/usr/local/lib/node_modules/lololodash/node_modules/workshopper/node_modules` folder there are only 4 folders: `ansi-styles`, `chalk`, `mkdirp`, and `strip-ansi`

**Comment by imwithsam** [comment]
There is, however, a `colors-tmpl` folder under `/usr/local/lib/node_modules/lololodash/node_modules`

**Comment by gaboesquivel** [comment]
that's weird, I can't tell what is wrong. As a workaround, you could uninstall node and reinstall it [using nvn](http://gaboesquivel.com/blog/2015/automatic-node-dot-js-version-switching/) . Then install lololodash again...

 if setup correctly, `where lololodash` will return `/Users/username/.nvm/versions/node/v4.1.1/bin/lololodash`

**Comment by imwithsam** [comment]
I did an uninstall of Node with Homebrew. Homebrew stated "node 0.12.7_1 is still installed" so I did a `brew uninstall --force node` to get rid of that installation. After reinstalling Node with Homebrew and lololodash with npm, lololodash works.

Thanks for your help!
