### ISSUE TITLE
Ex.11 HTTP File Server: correct solution is not accepted by 'verify'

### ISSUE THREAD

**Issue by seanttaylor** [nodeschool/discussions#1474]
I don't **think** I've seen any issues quite like mine. Code below returns the correct string for the exercise to `stdout` but the `ACTUAL` field in the test from the `verify` command is always empty `""`. 

I know that readStreams are supposed to close themselves automatically once the stream is complete but my code is not closing the readStream (hence the `response.end()`.) After the string prints the process just hangs without errors.

```javascript 
var fs = require('fs'), http = require('http'), server;

server = http.createServer( function (request, response) {
  var incomingData = fs.createReadStream(process.argv[3]);
  incomingData.pipe(process.stdout);
  response.end();
});

server.listen(process.argv[2]);
```

I feel like the solution is something simple but I just can't see it.

**Comment by davecocoa** [comment]
This exercise doesn't ask you to send anything to `stdout`, you need to pipe your stream into the http response, once you do this you'll be able to omit the `response.end();`.

**Comment by seanttaylor** [comment]
Duh. Got it man! Thanks so much for that pointer. Knew it was something simple like that.
