### ISSUE TITLE
Getting errors on "rounding numers js"

### ISSUE THREAD

**Issue by ajakaiye33** [nodeschool/discussions#1475]
I have written:
```js
var roundUp = 1.5;
var rounded = Math.round(roundUp);
console.log(rounded);
```
Please am I doing something wrong ... help

**Comment by dominhhai** [comment]
Can you specify the errors?
Anw, I don't find any problems in your code.

**Comment by ajakaiye33** [comment]
@dominhhai  I thought so too but just cant move forward. here is the sample of the error:

Quote
{ [Error: Command failed: /bin/sh -c node "/Users/ajakaiye/javascripting/rounding-numbers.js"
/Users/ajakaiye/javascripting/rounding-numbers.js:2
var rounded = Math.round(roundUp);
^^^
SyntaxError: Unexpected token var
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  Unquote

**Comment by ajakaiye33** [comment]
I have found a way around it. How stupid, forgot to close line one statement with a semicolon on the text editor! Thanks
