### ISSUE TITLE
Javascripting navigation

### ISSUE THREAD

**Issue by stefanstranger** [nodeschool/discussions#1476]
Hi people,
I installed Node.JS on Windows 10 and installed javascripting workshop using npm. After running javascript in nodejs console I'm not able to navigate with up & down arrow keys. 
![javascripting](https://cloud.githubusercontent.com/assets/2125385/10268195/8d7baa76-6ab1-11e5-9e66-f5e360e852b5.gif)

**Comment by stefanstranger** [comment]
Ok this seems to be an issue on Windows 10 after looking at other issues.

**Comment by stefanstranger** [comment]
Ok solved the issue. I just installed Console2 and now I can go ahead :-)

**Comment by SomeoneWeird** [comment]
#1448

**Comment by stefanstranger** [comment]
It turned out that using console2 didn't always worked. Current workaround I used:
1. Install NodeJS v12 from https://nodejs.org/dist/v0.12.7/x64/ into new directory. Example: C:\Program Files\nodejsv12
2. Create shortcut to C:\Windows\System32\cmd.exe /k "C:\Program Files\nodejsv12\nodevars.bat"
3. Open Node js console via shortcut and start javascripting

HTH
Stefan

**Comment by kakaroto1500** [comment]
hello good solution would be to remove the window or install a virtual linux box with -_-

I recommend and indicate the ubuntu

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0
