### ISSUE TITLE
Stuck on exercise 6

### ISSUE THREAD

**Issue by ImaCrea** [nodeschool/discussions#1477]
Hi folks,
I'm stuck on exercice 6 "make it modular" :(

There's something I can't grasp with callbacks, I hope you'll be able to help me. :pray: 

Here's what "verify" returns:
>✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✗ Your additional module file [step6Module.js] does not appear to pass back an error received from `fs.readdir()`.
  Use the following idiomatic Node.js pattern inside your callback to `fs.readdir()`:
	if (err)
	  return callback(err)

Here's my source code:
step6.js :
```javascript
var myModule = require('./step6Module')

myModule(null,process.argv[2],process.argv[3])
```

step6Module:
```javascript
var fs = require('fs')
var path = require('path')

module.exports = function (err,dir,extent) {
	if (err) throw err

	fs.readdir(dir,function(err,files){
		if (err) throw err

		files.forEach(function(file){
			if (path.extname(file) === ("."+extent)) console.log(file)
		})
	})	

}
```

Thanks for your help! :)

**Comment by davecocoa** [comment]
You're nearly there, you just got the callback relationship reversed. Instead of `step6.js` potentially passing an error to `step6Module`, `step6.js` should be passing a callback function into `step6Module`. So the arguments for `step6Module` should be `(dir, extent, callback)`, and then if `fs.readdir` throws an error, you do `callback(err)`, and once you have a filtered list of files, you do `callback(null, files)`.

Does that make sense?

**Comment by ImaCrea** [comment]
Hi Dave, thanks for your help!

Here's what "verify" returns now:
>✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✓ Additional module file handles errors properly
✓ Additional module file handles callback argument
CHANGELOG.md
LICENCE.md
README.md
✓ Additional module file returned two arguments on the callback function
✓ Additional module file returned correct number of elements as the second argument of the callback
✓ Additional module file correctly handles '.'-prefixed extension
✗ Your additional module file [step6Module.js] did not return an Array with the correct number of elements as the second argument of the callback

Looks almost there!

Here's my source code:
step6.js :
```javascript
var myModule = require('./step6Module')

myModule(process.argv[2],process.argv[3])
```

step6Module:
```javascript
var fs = require('fs')
var path = require('path')

module.exports = function (dir,extent,callback) {
	fs.readdir(dir,function(err,files){
		if (err) return callback(err)

		files.forEach(function(file){
			if (path.extname(file) === ("."+extent)) console.log(file)
		})

		callback(null,files)

	})	

}

```

Before going further, frankly I don't manage to get it. I see it works, but I can't explain clearly myself why. It's very frustrating and blocking as what's important for me is to understand what I do. If you could help me in that or if you know a place where callbacks are well explained for that usage I'd be grateful :)

thanks for your help,
Max

**Comment by davecocoa** [comment]
Could you be more specific about what you don't understand? Googling for pages about callbacks I found [this](http://recurial.com/programming/understanding-callback-functions-in-javascript/) which seemed good but really it depends on exactly what you're not understanding. Basically, functions in JavaScript are objects like anything else, so you can pass a function into another function. I'm happy to answer any questions you have, maybe if you describe what you expect the code to do and how it's behaving differently to what you expect? Or if there's a specific line or syntax you're not sure of?

Looking at your code now, I can give you two hints:
 - Your `step6Module` function expects three parameters (`dir,extent,callback`), but `step6.js` only passes in two parameters (`process.argv[2],process.argv[3]`). You need to pass in a function as that third parameter, and that function should be the only place you use `console.log`
 - Your `files` array still contains all the file names when you call `callback(null,files)`, you need to somehow filter it before you send the array into the callback.

**Comment by DLUK44** [comment]
I hope you don't mind me jumping in to ask a related question in this thread. I think I am in a similar position to ImaCrea. I have got this almost working but still don't quite understand how.

6a.js
```javascript
var myModule = require ("./6b.js");

var dir = process.argv[2];
var ext = process.argv[3];

myModule (dir, ext);
```

6b.js

```
var fs = require ('fs');
var path = require('path');
var files;

module.exports = function (dir, ext, callback)
	{
		fs.readdir(dir, function(err,list){
			if (err) {return callback(err);}
			list.forEach(function(file){
				if (path.extname(file) === "."+ext)
				{
					files+=file;
				}
			});
			
			callback (null,files);
	})}
	
	
function callback (err,data)
{
	console.log ("This is the callback function");
}
```

I don't understand why am I allowed to call the myModule function from 6a.js with just two arguements when the function is defined in 6b.js as having three. When I run this code I get the following error:

TypeError: callback is not a function
    at 6b.js:16:11

My question is, isn't it?

Thanks for any help you can offer.
David.

**Comment by davecocoa** [comment]
Hi @DLUK44 , in general it's still preferable to open a new issue for any issue that comes up so please do that in future.

For your particular questions, Javascript will not check how many arguments you pass to functions against what that function expects, when you call `myModule (dir, ext)`, your module is called with the arguments `(dir, ext, undefined)`. Later, when you attempt to do `callback (null,files)`, `callback` is indeed `undefined` and not a function. I can see you have defined *another variable* with the name `callback` but since it is defined outside your module function, it is ignored in favour of the closer scoped variable `callback` which is part of your module's arguments list.

**Comment by jimlonero** [comment]
I was getting the same problem as:

✗ Your additional module file [step6Module.js] did not return an Array with the correct number of elements as the second argument of the callback

This is the solution I got to work:
primary file: MakeItModular.js:
-------------------------------------------------------------------------------------------------------
var mymodule = require('./MakeItModularExports');

var myCallback = function(err, list) {
    if (err) { return console.error(err); }
    list.forEach(function (data) {
        console.log(data);
    });
}

mymodule(process.argv[2], process.argv[3], myCallback);
-------------------------------------------------------------------------------------------------------

secondary file: MakeItModularExports.js
-------------------------------------------------------------------------------------------------------
var fs = require('fs');
module.exports = function(dir, fe, callback) {
     fs.readdir(dir, function (err, list) {
        if (err) {
            return callback(err, null);
        }
        else {
            var filteredList = [];
            var fullExtension = '.' + fe;
            list.forEach(function (data) {
                if (data.indexOf(fullExtension) > 0){
                    filteredList.push(data);
                }
            })
            callback(null, filteredList);
        }
    })
}
-------------------------------------------------------------------------------------------------------

Hopefully, this helps.
