### ISSUE TITLE
lololodash fail.module_not_found

### ISSUE THREAD

**Issue by sabondano** [nodeschool/discussions#1481]
Any ideas on why I can't get the first lololodash exercise to pass?

mac 10.10.5
node 4.1.1
npm 3.3.6
workshop: lololodash@0.6.0

```
var _ = require("lodash");

var worker = function(userList) {
               return _.where(userList, { active: true };
             };

module.exports = worker;
```

When I run 
```
lololodash verify getting-started.js
```

I get this error:
```
$ lololodash verify getting-started.js
✗ ?exercises.1: Getting Started.fail.module_not_found || common.exercise.fail.module_not_found?

# FAIL

Your solution to 1: Getting Started didn't pass. Try again!
```

**Comment by davecocoa** [comment]
You have a syntax error, you should get a more helpful error message by doing `lololodash run getting-started.js`

**Comment by sabondano** [comment]
Thank you. Got the same error:
```
$ lololodash run getting-started.js
✗ ?exercises.1: Getting Started.fail.module_not_found || common.exercise.fail.module_not_found?
```

**Comment by imwithsam** [comment]
You're missing a closing parentheses on the `where` call.

**Comment by sabondano** [comment]
Thank you @imwithsam! I don't know how I missed that haha.

**Comment by imwithsam** [comment]
No problemo. I think I did the exact same thing on Exercise 2. :smiley:
