### ISSUE TITLE
functional-javascript-workshop -> Partial Application without Bind

### ISSUE THREAD

**Issue by martinerk0** [nodeschool/discussions#1485]
Hello, could anyone provide more examples or some explanation? I'm stuck with this example for 3 days and I cannot seem to move forward. I have read all documentation on MDN but it didn't help.

**Comment by kurzninja** [comment]
+1

**Comment by martinheidegger** [comment]
If you read the documentation it actually gives quite a few, very good hints on how to solve this, but here are a little more:

1) A function can return a function that has access to the parent scope!

```JavaScript
function foo(x) {
  return function(y) {
     return x + y
  }
}
var bar = foo("a")
var baz = foo("b")

bar(1) // a1
baz(1) // b1
```

2) JavaScript has a special variable called `arguments` which contains all the arguments of a method. It l

```JavaScript
function foo(a) {
  console.log(a) // x
  console.log(arguments[0]) // x
  console.log(arguments[1]) // y
  console.log(arguments.length) // 2
}

foo("x", "y")
```

3) The `arguments` variable is not an array! To work with it as array it needs to be converted to one:

```JavaScript
function foo() {
  console.log(typeof arguments.unshift) // undefined
  var argsAsArray = Array.prototype.slice.call(arguments
  console.log(typeof argsAsArray.unshift) // function
}

foo()
```

I think the same thing was explained in the documentation for this exercise.
