### ISSUE TITLE
I'm doing learnyounode on windows, httpFileServer.js problems.

### ISSUE THREAD

**Issue by tomarone** [nodeschool/discussions#1486]
I"m testing the http connection and file transfer with chrome, seems ok there.
But 'learnyounode verify httpfileserver.js' crashes with exception.
  ECONNREFUSED connecting to localhost::23196 or whatever port it might use.
events.js:85
throw er; // Unhandled 'error' event'
Error: listen EACCES
at Server._listen2 etc. (do you need all the output?)
Any way to debug this?
code is basic, nothing special:
var aport = process.argv[3];
var aFN = process.argv[2];
var http = require('http');
var fs = require('fs');
http.createServer(function(req, res) {
   var readStream = fs.createReadStream(aFN);   // (file works, have tried appending to __dirname)
   readStream.on('open', function () {
   readStream.pipe(res);
  });
  readStream.on('error', function(err) {
    res.end(err);
  });
}).listen(aport);

i also noticed that in general the http client-server connection usually happens TWICE on my windows machine, and I don't know why.  The transactions are usually doubled up (after the first one it seems when I keep refreshing the browser connection)
Thanks!
Todd.

**Comment by davecocoa** [comment]
You're really close you just have the arguments mixed up. From the exercise instructions (emphasis mine):

```
Your server should listen on the port provided by the *first* argument to your 
program.

You will be provided with the location of the file to serve as the *second* 
command-line argument.
```

**Comment by tomarone** [comment]
Wow thanks so much!  What debugger do you think is the best to use?  I should've thought to just look at those params!

**Comment by davecocoa** [comment]
For problems like this `console.log` is usually enough to figure out what's going on, if you find your logs aren't appearing it's often helpful to use `learnyounode run` instead of `learnyounode verify`.
