### ISSUE TITLE
I'm using sequelize and i want to know the current connections number

### ISSUE THREAD

**Issue by sammffl** [nodeschool/discussions#1487]
sequelize version is 1.7.10
if someone know this pls tell me ！

**Comment by lvivier** [comment]
1.7.10 is over a year old, but I'll try to help anyway.

Sequelize's mysql dialect uses [generic-pool](https://www.npmjs.com/package/generic-pool) to manage connection pooling. You can call the `getPoolSize()` method of the pool to see how many objects (connections) there are:

```js
// sequelize instance
var sql = new Sequelize(config)

// with mysql dialect
var size = sql.connectorManager.pool.getPoolSize()
```

Remember connections are asynchronous, if you try to get the pool size immediately it will be `0`.

In the current version of Sequelize, all dialects except sqlite use the same method of connection pooling, same as above but `connectorManager` is now called `connectionManager`.
