### ISSUE TITLE
Javascripting Lesson 10 #For Loop

### ISSUE THREAD

**Issue by denizenkofi** [nodeschool/discussions#1490]
I've created the file named for-loops.js which the lesson says to create:

````
var total = 0
var limit = 10

for (var i = 0; total += i; i < limit) {
  console.log(total)
}

````

the lesson says the solution is supposed to be 45, but I don't see how that's possible. Help!

**Comment by riyadhalnur** [comment]
You are supposed to add the value of the iterator, in this case `i` to the total on each pass of the loop. This is mentioned in the problem description  
> Create a for loop with a variable `i` starting at 0 and increasing by 1 each time through the loop. The loop should run as long as `i` is less than `limit`.

> On each iteration of the loop, add the number `i` to the `total` variable. To do this, you can use this statement: 

I hope that helps you. Not sharing the code/solution here. If you still can't figure it out then post here again and we can go through the solution.

**Comment by denizenkofi** [comment]
thanks Riyad. I figured it out. This is what ended up being the solution:
````var total = 0
var limit = 10

for (var i = 0; i < limit; i++) {
total += i;

}
console.log(total)

**Comment by riyadhalnur** [comment]
awesome. glad you got it to work :)
