### ISSUE TITLE
Stuck on ex. 2

### ISSUE THREAD

**Issue by adelin2011** [nodeschool/discussions#1494]
I am stuck on exercise 2. I have my code as: 
var example; 

var example ='some string'; 
console.log('example'); 

I keep getting the notification that something isn't working and cannot figure out what I am doing wrong.

**Comment by adobley** [comment]
You should not have quotes around the variable name example in the
console.log

**Comment by adelin2011** [comment]
thank you

**Comment by SomeoneWeird** [comment]
:tada:
