### ISSUE TITLE
Question with for-loops

### ISSUE THREAD

**Issue by adelin2011** [nodeschool/discussions#1495]
I have this code and am lost on where I am going wrong. Can someone explain this to me? 
```js
var total = 0; 
var limit = 10; 

	for (i = 0; i++, i< 10) {
    limit += i;
}

console.log(total); 
```

**Comment by SomeoneWeird** [comment]
You're very close. You have the second and third argument for `for` the wrong way around. Also, you need to increment `total`, not `limit`.

**Comment by cloveangel** [comment]
```
var total = 0,
	limit = 10;
for (var i = 0; i < limit; i++){
	total += i;
}
console.log(total);
```
