### ISSUE TITLE
Http Client learnyounode

### ISSUE THREAD

**Issue by chinchaun** [nodeschool/discussions#150]
Hello, first of all thanks for doing this proyect is very helpful
Can someone explain how the hppt.get function works, for what i read in the documentation this is what i did:

``` js
http.get(url,function(response){
    response.setEncoding('utf8');
    response.on("error", function(e){
                                                console.log(e); 
                                                  });
    response.on("data", function(m){
                                          console.log(m);
                                                  });

    });
```

and obviously didn't work, looking around here i found the right way 

``` js
http.get(url,function(response){
    response.setEncoding('utf8');
    response.on("error", console.error);
    response.on("data", console.log);

    });
```

but i don't understand how the response.on really work,
thanks in advance!

**Comment by chiadt** [comment]
var http = require('http')
    
    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)
    })

**Comment by HumanSprout** [comment]
I've run into the same problem as above using the same code, using node v 4.4.0
