### ISSUE TITLE
Cleaner workshop start

### ISSUE THREAD

**Issue by mvcds** [nodeschool/discussions#1500]
I found difficult to start using node through NodeSchool (which was the reference I had on node.org) when I didn't know anything about how node works.

It was only after I start going to node meetups and watch some tutorials that I realized I should run the command to install the "learnyoucode" package and run the package. For me it's not clear for begginers on node, I suggest userd to be explitly told that they should type "npm install learnyounode", per example.

(I don't feel like I'm being clear here, so if so, let me know and I'll clarify - and I also don't know if here was the best place to post it).

**Comment by riyadhalnur** [comment]
@mvcds Thank you for reaching out. There are actually modules on learning `npm` as well as the basics of node with `learnyounode` and JavaScript itself with `javascripting`. 

If you're looking to learn the fundamentals of NodeJS though and how it works though before you dive in to the exercises, you should look at the [NodeJS](http://nodejs.org) itself.

As for installation instructions, the command to install each individual module on your machine is provided underneath each of the module's descriptions.

![screen shot 2015-10-20 at 10 55 07 pm](https://cloud.githubusercontent.com/assets/3457571/10614732/a4323a2c-777d-11e5-8c6a-ba18ff8dbd3a.png)

**Comment by mvcds** [comment]
I got it, and i'm enjoying the workshops - I think I've done four or five so far. 

The problem is that as I was not used to the command line it never crossed my mind to open my terminal and type the commands. I'm wondering if there are people "dumb" as me for this kind of things who would benefit from a more direct guidence like simpling writting "Open your terminal and type the command to install the workshop".

**Comment by riyadhalnur** [comment]
@mvcds that's what the meet-ups are for :)

**Comment by mvcds** [comment]
I think you're half right on that one, @riyadhalnur,  meetups are good to learn things but I don't think they fully cover self-learning which seems the pourpouse of the workshops.

I "had the idea" of using the command line after a meetup, but how long would have passed until I realize what seems obvious to lots of people if I hadn't gone there?

**Comment by riyadhalnur** [comment]
I think that essentially comes down to basics at the end of the day. All programming languages are terminal based essentially when you go down far enough and I think it's important to atleast have some basic knowledge before diving in to programming in the first place.
