### ISSUE TITLE
Workshop for currying

### ISSUE THREAD

**Issue by kishorsharma** [nodeschool/discussions#1503]
I have started developing a workshop for [function currying in javascript](https://github.com/kishorsharma/currying-workshopper). [Currying](https://en.wikipedia.org/wiki/Currying) is a mathematical concept and I found it very helpful in functional programming.
Please let me know if there is already one (I searched and found none) for the same. 

Here are the list of exercises for the workshop:
1. Identity function - A function which simply return argument passed.
2. Binary function to add - A two argument function which will return addition of two input
3. Function to add on second invocation - A unary function which return another unary function and which adds two provided arguments.
4. Function takes one int value in each invocation and adds them on first no parameter invocation
5. What is call?
6. What is apply?
7. Function to make passed function a curry function
8. Using currying function in ajax call.

Any help or suggestion will be greatly appreciated.

To know more about the currying, check below links:
- [Curried JavaScript functions](http://www.crockford.com/javascript/www_svendtofte_com/code/curried_javascript/index.html)

**Comment by maximumhallinan** [comment]
[The Functional JavaScript workshop](https://github.com/timoxley/functional-javascript-workshop) includes at least one curried function lesson. I think a workshop focused on currying would be valuable. Many online resources make the technique appear more complicated than it is. The Functional JavaScript Workshop does an excellent job of simplifying the concept. Unfortunately, someone looking for an introduction to currying might not understand that it is a technique commonly used in functional programming and so think to look for it in the Functional JavaScript Workshop.

A few thoughts:
- What about expanding the scope of the workshop to cover currying *and* partial application? They're related techniques and there is as much practical use for partial application.
- It would be good not just to teach the technique of currying but demonstrate use of currying in an application.

**Comment by kishorsharma** [comment]
@maximumhallinan Thanks for you valuable suggestion and I agree on both points. 
Third exercise *Function to add on second invocation* is for partial application (I think here I need to be more descriptive about my exercise than just provide title..).  
I have one example where in an ajax call using promises extract information from response.

**Comment by kishorsharma** [comment]
Hi friends,

I have added few exercises into the current workshop. It will be appreciated if anyone can help in review and provide their valuable suggestion... :)
