### ISSUE TITLE
Omission of semicolon in node tutorials

### ISSUE THREAD

**Issue by raymondyin** [nodeschool/discussions#1504]
Hi,

I'm wondering why in the tutorials, code instructions would have something like "var fs = require('fs')". Did the creators wish the students to write javascripts without using semicolons?

**Comment by maxogden** [comment]
hi,

there is no one correct way to write javascript, everyone has their own
personal style. more info is available at these links:

http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding
http://inimino.org/%7Einimino/blog/javascript_semicolons
https://www.youtube.com/watch?v=gsfbh17Ax9I

On Sunday, October 18, 2015, Raymond Xiwei Yin <notifications@github.com>
wrote:

> Hi,
>
> I'm wondering why in the tutorials, code instructions would have something
> like "var fs = require('fs')". Did the creators wish the students to write
> javascripts without using semicolons?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/1504>.
>


-- 
Sent from my phone

**Comment by raymondyin** [comment]
Hi maxogden,

The information is helpful. I guess the usage of semicolon in Javascript is about personal preference.  Thanks for the reply.
