### ISSUE TITLE
Baby Steps

### ISSUE THREAD

**Issue by lockykeaney** [nodeschool/discussions#1505]
I am just trying to do the second activity, and I don't understand the question.

Am I trying to write a .js file that will do everything when run? Or do I have to take information from the command line? 

This is my .js: console.log(+process.argv[2])

And here is the output:

Your submission results compared to the expected:

```
             ACTUAL                                 EXPECTED                
```

────────────────────────────────────────────────────────────────────────────────

   "50"                                !=    "596"  
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!
# FAIL

Your solution to BABY STEPS didn't pass. Try again!

I just don't get the question.

**Comment by lvivier** [comment]
In Baby Steps, your program will receive several arguments on the command line. Each one is a number, and you have to print the sum of the numbers. If you just write

```js
console.log(process.argv)
```

in your program file and run it with a few arguments, you'll see how they end up on the `process.argv` array:

```
$ node program.js 15 23 88
[ '/usr/local/bin/iojs',
  '~/program.js',
  '15',
  '23',
  '88' ]
```

The numbers you'll be working with will be in this array, and you don't know in advance how many there will be. Does that help?
