### ISSUE TITLE
Exercise 6 - Make it Modular

### ISSUE THREAD

**Issue by veronikabenkeser** [nodeschool/discussions#1507]
The code below results in the following error:  "Used asynchronous method from the `fs` module." If the second return statement in the Mod.js file is changed to "callback(error,data);", the answer shows up as being correct. It makes sense that we don't really need to put "return" because the callback function will get called anyway, but I'm a little confused as to why it would be incorrect as opposed to just being unnecessary. Thank you so much!

myMain.js
var myModule = require("./mod.js");

myModule(process.argv[2],process.argv[3],function(error,data){
    if(error){
        console.log("error : "+error);
    }else{
     data.forEach(function(item){
      console.log(item); 
     });
    }
});

Mod.js
var fs=require('fs');
var path = require("path");

module.exports = function(dirName,ext,callback){
    fs.readdir(dirName, function(error,data){
        if (error){
            return callback(error);
        }
       data= data.filter(function(item){
           return path.extname(item) === "."+ext;
        });
        return callback(error,data);
    });
};

**Comment by davecocoa** [comment]
That may be a bug in the workshop code. If I run your code on my machine, without any changes, it passes.

**Comment by veronikabenkeser** [comment]
Oh ok, thank you!
