### ISSUE TITLE
Javascripting Function Arguments 

### ISSUE THREAD

**Issue by Koohoots** [nodeschool/discussions#1508]
I almost made it thought the whole Javascripting corse when I finally got beat on the second to last tutorial: Function Arguments.

Can anyone point out what I am doing wrong? Here is my code:

function math ('x', 'y', 'z') {
	math('y' * 'z' + 'x');
}
console.log(math('53', '61', '67'));

**Comment by scottcorgan** [comment]
Looks like your arguments in your function don't need to be in quotes

```js
function (x, y z) {

}
````

**Comment by Koohoots** [comment]
I tried running this and still didn't work:

function math (x, y, z) {
	math(y * z + x);
}
console.log(math('53', '61', '67'));

**Comment by scottcorgan** [comment]
Do you have a little bit more context for writing that function? I haven't done the tutorials, but I'd love to help

**Comment by Koohoots** [comment]
I will copy the challenge here:

-------------------
# FUNCTION ARGUMENTS

A function can be declared to receive any number of arguments. Arguments can be from any type. An argument could be a string, a number, an array, an object and even another function.

Here is an example:

function example (firstArg, secondArg) {
  console.log(firstArg, secondArg);
}

We can call that function with two arguments like this:

example('hello', 'world');

The above example will print to the terminal hello world.

## The challenge:

Create a file named function-arguments.js.

In that file, define a function named math that takes three arguments. It's important for you to understand that arguments names are only used to reference them.

Name each argument as you like.

The function math should multiply the second and third arguments, then add the first argument to the outcome of the multiplication and return the value obtained.

After that, inside the parentheses of console.log(), call the math() function with the number 53 as first argument, the number 61 as second and the number 67 as third argument.

Check to see if your program is correct by running this command:

javascripting verify function-arguments.js

-------------------

**Comment by SomeoneWeird** [comment]
```js
function math (x, y, z) {
  math(y * z + x);
}
```

When `math` is called initially, it's going to call `math`, then `math` is going to call `math` and you're going to get an infinite loop. What you need to do is `return` the sum of all the arguments you get.

**Comment by Koohoots** [comment]
Ok so I just ran this but still didnt pass:

function math (x, y, z) {
	return (y * z + x);
}
console.log(math('53', '61', '67'));

**Comment by SomeoneWeird** [comment]
Yep! Much closer. The problem you have now is that you're passing strings as arguments, not numbers. They don't need to be quoted either. :)

**Comment by Koohoots** [comment]
Got it! That was so simple. Thanks for the help!!
Here is the final result:

function math (x, y, z) {
	return (y * z + x);
}
console.log(math(53, 61, 67));

**Comment by SomeoneWeird** [comment]
Awesome! Open another issue if you run into more problems :tada:
