### ISSUE TITLE
Time Server verify doesn't work !

### ISSUE THREAD

**Issue by modul8com** [nodeschool/discussions#151]
I just tried my version:
```js
var net = require('net');
var portnumber = Number(process.argv[2]);

var server = net.createServer(function(socket) {
    var date = new Date();
    var year = date.getFullYear();
    var month = date.getMonth() + 1;
    var day = date.getDate();
    var hours = date.getHours();
    var minutes = date.getMinutes();

    var returnString = pad(year, 4) + '-' + pad(month, 2) + '-' + pad(day, 2) + ' ' + pad(hours, 2) + ':' + pad(minutes, 2) + '\n';

    socket.write(returnString);
    socket.end();
});

server.listen(portnumber);

function pad(number, zeroes) {
    var lotsOfZeroes = '00000000000000000000';
    return (lotsOfZeroes + number.toString()).slice(-zeroes);
}

Which is almost identical to the solution:

var net = require('net');


function zeroFill(i) {
    return (i < 10 ? '0' : '') + i;
}


function now () {
    var d = new Date();
    return d.getFullYear() + '-'
        + zeroFill(d.getMonth() + 1) + '-'
        + zeroFill(d.getDate()) + ' '
        + zeroFill(d.getHours()) + ':'
        + zeroFill(d.getMinutes());
}


var server = net.createServer(function(socket) {
    socket.end(now() + '\n');
});
server.listen(Number(process.argv[2]));
```
But neither one works when trying a "learnyounode verify timeserver.js" or "learnyounode verify timeserversolution.js".

They both respond with this output:

Verifying "TIME SERVER"...

ACTUAL                             EXPECTED
------                             --------
"Error connecting to localhost:60241: connect ECONNREFUSED" != "Error connecting to localhost:60242: connect ECONNREFUSED"
# FAIL

Your solution to TIME SERVER didn't match the expected output.
Try again!

Now what ?

Michael

**Comment by Marqin** [comment]
@martinheidegger , please re-open this bug. On my OS X 10.10 I'm getting:

    ✗ Error connecting to localhost:20952: connect ECONNREFUSED

    Your submission results compared to the expected:

                     ACTUAL                                 EXPECTED                
    ────────────────────────────────────────────────────────────────────────────────

       "2015-08-02 20:08"                  !=    ""                                 
       ""                                  !=                                       

    ────────────────────────────────────────────────────────────────────────────────

    ✗ Submission results did not match expected!

    # FAIL

    Your solution to TIME SERVER didn't pass. Try again!

with code:

    var net = require('net');

    function putZero ( x ) {
        return ( ( x < 10 ) ? "0" : "") + x;
    }

    var server = net.createServer( function( socket ) {
      var date = new Date();
      var timedate = date.getFullYear() + "-" + putZero(date.getMonth()+1) + "-" + putZero(date.getDate());
      timedate += " " + putZero(date.getHours()) + ":" + putZero(date.getMinutes());

      socket.write( timedate + "\n" );
      socket.end();
    });

    server.listen( process.argv[2] );

Of course, `learnyounode run time.js` prints right time. Also running with `node time.js 20952` and telneting to it works OK.

**Comment by SomeoneWeird** [comment]
What OS does it not pass on?

**Comment by Marqin** [comment]
> On my OS X 10.10 I'm getting:

On Arch Linux with kernel 4.1 it's working ok.

**Comment by monarchjhaveri** [comment]
same error here. Ubuntu 14.04 LTS

**Comment by SomeoneWeird** [comment]
Please open another issue.
