### ISSUE TITLE
Javascripting navigation arrows not working

### ISSUE THREAD

**Issue by TangentialAlan** [nodeschool/discussions#1511]
Hi I'm using the javascripting command to learn js. In the nodejs command prompt, when I enter javascripting, I can't navigate the screen with my arrow keys. How can I fix this?
https://gyazo.com/7fe8e4d2b10ab35ebb3f708f7a08dd50

**Comment by SomeoneWeird** [comment]
#1448

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0
