### ISSUE TITLE
array filtering learnyounode

### ISSUE THREAD

**Issue by duvan01** [nodeschool/discussions#1512]
I have a problem with the var "filtered", the console displays [], but it should be [2, 4, 6, 8, 10], according to the exercise.

var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

var filtered = numbers.filter(function evenNumbers (number) {
	return number / 2 === 0;
});
console.log(filtered);

thanks for the feedback.

**Comment by SomeoneWeird** [comment]
The issue you have here is that `number / 2 === 0` is always going to return false, because even if `number` is `1` then `1 / 2` is `0.5`. You need to use something like `Math.floor`.

**Comment by davecocoa** [comment]
You are using the division operator `/` but I think you intended to use the remainder AKA modulo operator `%`.

**Comment by duvan01** [comment]
davecocoa you're right, I change the operator and run. thank you very much and also to SomeoneWeird.
