### ISSUE TITLE
¿que aplicaciones se pueden hacer con node?

### ISSUE THREAD

**Issue by mamez** [nodeschool/discussions#1513]
Hola me gusta node y quiero entrar en este mundo de programación, pero quiero saber que aplicaciones se pueden hacer con node ya que e escuchado que solo se pueden hacer chasts.
¿se pueden hacer aplicaciones empresariales?

**Comment by duvan01** [comment]
Se puede hacer cualquier tipo de aplicación , desde aplicaciones escalables como servidor - cliente y servidor -servidor. mucha suerte! y para empezar te recomiendo javascripting, te ayudara a familiarizarte con el entorno node.
