### ISSUE TITLE
Exercise 6 : Make it modular - Issue

### ISSUE THREAD

**Issue by dispix** [nodeschool/discussions#1514]
Hi everyone ! I'm really stuck on this one and can't see why my test doesn't succeed : 

My module :
```javascript
var fs = require('fs')
var path = require('path')
module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function(err, list){
		if (err) return callback(err)
		list.forEach(function(el, ind, arr){
			if (path.extname(el) == '.'+ext) {
				callback(el)
			}
		})
	})
}
```

My program :
```javascript
var mymodule = require('./modular_module.js')
mymodule(process.argv[2], process.argv[3], console.log)
```

And finally what the console says when I try to pass the test :
>Your submission results compared to the expected:
>
>                 ACTUAL                                 EXPECTED                
>────────────────────────────────────────────────────────────────────────────────
>
>   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
>   "LICENCE.md"                        ==    "LICENCE.md"                       
>   "README.md"                         ==    "README.md"                        
>   ""                                  ==    ""                                 
>
>────────────────────────────────────────────────────────────────────────────────
>
>✓ Submission results match expected
>✓ Additional module file exports a single function
>✓ Additional module file exports a function that takes 3 arguments
>✓ Additional module file handles errors properly
>✓ Additional module file handles callback argument
>✗ Your additional module file [modular_module.js] returned an error on its callback:
>	'CHANGELOG.md'
>✗ Your additional module file [modular_module.js] returned an error on its callback:
>	'LICENCE.md'
>/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:177
>    processors[i].call(self, mode, function (err, pass) {
>                 ^
>TypeError: Cannot read property 'call' of undefined
>    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:177:18)
>    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:184:7
>    at callback (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:27:15)
>    at modFileError (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:32:5)
>    at /usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:113:18
>    at /Users/Dispix/node/modular_module.js:9:5
>    at Array.forEach (native)
>    at /Users/Dispix/node/modular_module.js:7:8
>    at FSReqWrap.oncomplete (fs.js:95:15)

Any hint for this kind of error ? Really struggling to find my way out :(

**Comment by siddhantvan** [comment]
Try using '===' in your module in the if condition. Not sure what the comparison operator in js is, and it might not work

**Comment by dispix** [comment]
Nope, tried that but sadly that doesn't change anything :/

**Comment by lvivier** [comment]
The node convention for callbacks signatures is `(err, data)`. The first argument to a callback should either be an error or `null`. So when your module calls back it should be `callback(null, el)`. That'll get you to the next test. Good luck!

**Comment by dispix** [comment]
Thanks for the answer but I already tried that and it also fails, this is
the response I get when doing this :

>                 ACTUAL                                 EXPECTED


>────────────────────────────────────────────────────────────────────────────────

>

>   "null 'CHANGELOG.md'"              * != *   "CHANGELOG.md"


>   "null 'LICENCE.md'"                * != *   "LICENCE.md"


>   "null 'README.md'"                 * != *   "README.md"


>   ""                                 * == *   ""


>

>────────────────────────────────────────────────────────────────────────

2015-10-24 7:18 GMT+02:00 Luke Vivier <notifications@github.com>:

> The node convention for callbacks signatures is (err, data). The first
> argument to a callback should either be an error or null. So when your
> module calls back it should be callback(null, el). That'll get you to the
> next test. Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/1514#issuecomment-150756580>
> .
>



-- 
*Octave RAIMBAULT*

**Comment by davecocoa** [comment]
You won't be able to pass this exercise by simply passing `console.log` to your module, you need to pass a function which understands the difference between an error and a result, and logs the result on its own when there is no error.

**Comment by dispix** [comment]
I don't understand what that really means. Care to give a hint ?

**Comment by lvivier** [comment]
@dispix in your program, you pass `console.log` as the third argument to your module. You need to write a function that takes the callback signature `(err, data)` and passes on the data to `console.log`.

Your module also needs to call back once, with an Array of elements, instead of once for each element as in the code above. The callback in your program will need to expect an array and display each element in the array on its own line.

When you run `$ learnyounode verify {yourprogram}`, pay close attention to the test cases. The failing cases with a red **✗** are telling you what you still need to change.

**Comment by dispix** [comment]
Thanks for that last answer. Got it this time!

**Comment by malipetek** [comment]
I also thought I may callback multiple times. It would be better if logs proper error message.

**Comment by lvivier** [comment]
@malipetek this is the hardest exercise in the whole workshopper imo…seems to throw everyone off.
