### ISSUE TITLE
My First I/O Help - TypeError: path must be a string

### ISSUE THREAD

**Issue by JelaniThompson** [nodeschool/discussions#1515]
Hey guys, I'm working on a NodeSchool project called My First I/O. I THINK I might be close to finishing but I'm getting this one weird error:

```
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/jelanithompson/Downloads/NodeJS Projects/file_system.js:3:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

Here's my code: 
```
//Enable us to use fileSystems module
var fileSystem = require('fs');
var readFile = fileSystem.readFileSync(process.argv);
var string = readFile.toString()
string.split("\n");
```

Does anyone know what the issue might be? Thanks!

**Comment by riyadhalnur** [comment]
`process.argv` is an array where the first element is always `node` and the second will be the path of the file. User provided arguments will start at `process.argv[2]`. Referring to the correct element in the array will fix your problem. Hope that helps.

**Comment by JelaniThompson** [comment]
@riyadhalnur Thanks! I made that fix but for some reason, it's not returning anything. Here's what I get: https://gist.github.com/JelaniThompson/bd3e0619fd18aa798097

Is there any way I could provide a value to process.argv manually since the Node project doesn't seem to be doing it automatically?

**Comment by riyadhalnur** [comment]
@JelaniThompson What module is this?

**Comment by JelaniThompson** [comment]
@riyadhalnur Did you mean this section?

```
 //Enable us to use fileSystems module
var fileSystem = require('fs');
```

**Comment by riyadhalnur** [comment]
@JelaniThompson no, the tutorial you're on now

**Comment by riyadhalnur** [comment]
@JelaniThompson ok, in order to complete the lesson, you have to log the results to the console using `console.log`

**Comment by JelaniThompson** [comment]
@riyadhalnur Oh, ok. Thanks again for the support!

**Comment by riyadhalnur** [comment]
@JelaniThompson glad to help. anytime. cheers :)
