### ISSUE TITLE
stream-adventure Duplexer cannot succeed

### ISSUE THREAD

**Issue by MarkAltenbernd** [nodeschool/discussions#1517]
I have developed a response for the Duplexer challenge, but it will not pass the verify test. I checked my work against the reference solution, and it was essentially identical, with only a couple of differences in variable names. I then tried to verify the reference solution, and it failed in exactly the same way as my own solution: what the test expected was about twice as long as what the solutions actually provided::

```
operator: equal
expected:
  'vuffiih\nvsny\nvoa\nvuffiih\nvoa\nvstuhnchy\nvivvch\nvir\nvcmwocn\nvolliq'
actual:
  'vuffiih\nvsny\nvoa\nvuffiih\nvoa'
```

This problem was consistent across a number of iterations  of the test with both the reference solution and my own. Here is the content of the reference solution:
    // Here's the reference solution:

```
  var spawn = require('child_process').spawn;
  var duplexer = require('duplexer2');

  module.exports = function (cmd, args) {
      var ps = spawn(cmd, args);
      return duplexer(ps.stdin, ps.stdout);
  };
```

Have others seen this issue? This seems to be a problem with the test apparatus - is that a reasonable conclusion? Is there a way to complete the test successfully?

Thanks for any help.

**Comment by davecocoa** [comment]
Could you give us more info about your environment? Your Operating System, version of node, npm and stream-adventure? That solution passes fine on my machine (ubuntu/node 4.0/ npm 2.14.2/ stream-adventure 4.0.4)

**Comment by MarkAltenbernd** [comment]
Windows 7 64-bit, Node v4.1.2, NPM v2.14.4, whatever the current version of streram-adventure is (I downloaded it about a week ago).

**Comment by NorthPointDLubin** [comment]
I'm having this exact same issue. OSX El Capitan, Node v4.2.1, NPM v2.14.7, I downloaded stream-adventure within the last week.

**Comment by kkennis** [comment]
Same here - OSX El Capitan, Node v4.2.1, NPM v2.14.7, downloaded stream-adventure over the weekend. I'm getting this output as part of my solution: 

```
    operator: equal
    expected:
      'piu\npfûzés\npmnobhwbs\npmhs\npmnobhwbs\npoh\npfûzés\npoys\npoys\nponoof\npmnobhwbs\npchhzs\npmnobhwbs\npseisohv'
    actual:
      'piu\npfûzés\npmnobhwbs'
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/stream-adventure/node_modules/concat-stream/index.js:36:43)
```

which would lead me to believe that however the solution is being verified, its usage of concat-stream is somehow not running in the right way. I went to the line number specified in the concat-stream source and it is the exact line and column where concat-stream executes the callback. Maybe there's something in there?

**Comment by jgkim** [comment]
I had the same issue on OX X El Capitan with Node v5.0.0 and NPM v3.3.10. The solution from the second update of @kkennis's comment works for me!

**Comment by NorthPointDLubin** [comment]
@kkennis's comment worked for me as well. Thanks!

**Comment by paulochavesbr** [comment]
I had this issue on Ubuntu 15.10 with Node v4.2.2 and npm 2.14.7. The solution was change the versioning for stream-combiner2 and run `npm install` inside the stream-adventure directory.
@kkennis's comment worked for me as well! Thank's very much!

**Comment by MarkAltenbernd** [comment]
Sorry to have been inattentive to the discussion for the past couple of weeks - I have been on a short, high-intensity project that has just wrapped up.

The stream-combiner2 version change did not work for me. (on Windows 7 64-bit, Node v4.1.2, NPM v2.14.4). I found the package.json file in the AppData\Roaming\npm\npm-modules\stream-adventure folder and removed the caret from the dependency for stream-combiner2 so that it *should* have loaded v1.0.2. I CDed to my stream-adventure development directory and did an npm install of stream-adventure, piping the output to a text file. Examining the file, I found this:
    ├── stream-combiner2@1.1.1 (duplexer2@0.1.4, readable-stream@2.0.4)
It seems that somehow the specification in the package.json file is being superseded, but I am unable to find an alternative file that may be used during the installation. 

At this point, I am still unable to verify the DUPLEXER challenge.

**Comment by tomothumb** [comment]
Same problem here

**Comment by deubaka** [comment]
Same issue, same solution as expected, and running Mac OS X El Capitan, Node v5.1.0.

```
ok 1 stream-adventure verify YOURFILE.js
ok 2 solution exports a function
not ok 3 should be equal
  ---
    operator: equal
    expected:
      'cbmmppo\ncpccjo\nczuf\ncmjq\ncjuf\ncbu\ncbmmppo\ncvh\ncffumf\nczuf\ncpy\nczuf'
    actual:
      'cbmmppo\ncpccjo'
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/stream-adventure/node_modules/concat-stream/index.js:36:43)
```

Tried @kkennis #2 suggestion, still wasn't able to successfully run it. Will investigate further if I'm missing something.

**Comment by deubaka** [comment]
Got it working now with multiple options. 

The first one is to downgrade `stream-adventure` to `v3.0.0`, everything works should work there. 

The second be overriding `stream-combiner2` to use `v1.0.2` only as follow,
- Removed module references to `stream-combiner2` latest (v1.1.1), that means removing it in your libs both global and local
- Within the `stream-adventure` module directory, re-install `stream-combiner2` at `v1.0.2` via `npm install  --save stream-combiner@1.0.2`
- Re-run verify and should show a solution passed now

**Comment by crw** [comment]
In trying to fix the above issue, I now run into https://github.com/npm/npm/issues/10686

In comment https://github.com/nodeschool/discussions/issues/1517#issuecomment-161170352, if I am not mistaken ```npm install --save stream-combiner@1.0.2``` should actually read ```npm install --save stream-combiner2@1.0.2```. I do not know for certain as I couldn't get it to work. :(

**Comment by zcaceres** [comment]
I am having the same problem (OSX Sierra). Identical to reference solution and even tried the ref. solution.
