### ISSUE TITLE
Finished javascripting on node school, now what?

### ISSUE THREAD

**Issue by PastNoMore** [nodeschool/discussions#1519]
I tried the course and completed it no problem, I tried some of the others and the difficulty is far more advanced. How can I transition into javascript from here. What would you recommend?

**Comment by SomeoneWeird** [comment]
Did you try `learnyounode`? That's usually the next step after `javascripting`.

**Comment by PastNoMore** [comment]
Yeah, I had a bit of difficulty getting it working, - I'll go for round 3 and follow up.

**Comment by SomeoneWeird** [comment]
No problem. Let me know how you go :)
