### ISSUE TITLE
No response after I type in command: learnyounode

### ISSUE THREAD

**Issue by Teemobustin** [nodeschool/discussions#1521]
└> learnyounode
fish: Unknown command 'learnyounode'

Please anyone can help with this?

**Comment by lvivier** [comment]
Did you install `learnyounode` with the `-g` option to npm?

    $ npm install -g learnyounode

I've never used fish, but I would confirm the following:

- Is npm's global install directory in your PATH for fish?
- Does `$ which learnyounode` give output in bash/sh?
- Does npm correctly install other modules with `-g`?

**Comment by onedeadear** [comment]
Are you running it using a regular Windows command prompt? Try running it using the node.js Command Prompt if so.
