### ISSUE TITLE
javascripting won't launch

### ISSUE THREAD

**Issue by naunauyoh** [nodeschool/discussions#1525]
After installing javascripting using npm,when I type "javascripting" the Windows command line does not recognize 'javascripting'. What should I do ?

**Comment by martinheidegger** [comment]
Did you install using the `-g` option?

Correct: `npm i javascripting -g`
Wrong: `npm i javascripting`

Can you show the output of your console after the installation?

**Comment by naunauyoh** [comment]
Dear Mr. Heidegger,

Thank you for your help.
[image: Images intégrées 1] here is the result I get.


Sincerely yours,
Arnaud Massenet

2015-11-04 20:38 GMT-05:00 Martin Heidegger <notifications@github.com>:

**Comment by martinheidegger** [comment]
I am sorry but the image is not visible

**Comment by naunauyoh** [comment]
Ohh sorry, I put it in the word file

2015-11-05 13:44 GMT-05:00 Martin Heidegger <notifications@github.com>:

**Comment by Ij888** [comment]
When I try to run the expressworks, learnyoumongo and test-anything workshops i get the following error on windows. What could please be the problem?

![image](https://cloud.githubusercontent.com/assets/2773674/11401735/e48aba84-938b-11e5-90a3-7cb5d216350e.png)
