### ISSUE TITLE
learnyounode - make it modular - callback

### ISSUE THREAD

**Issue by bessieatrazoyo** [nodeschool/discussions#1526]
I don’t understand how to make the callback function.  I keep staring at this instruction:  “The module must export a single function that takes three arguments:  the directory name, the filename extension string and a callback function.”

My face melts and I wonder:  “What is the callback function that I need to use?”

This is what I have for mymodule.js:

module.exports = function (arg1, arg2) {
        var fs = require('fs');
        var path = require('path');
        var ext = '.' + arg2;

        fs.readdir(arg1,
                function (err, list) {
                  if (err) {
                        throw err;
                  } else {
                        for (var i = 0, x = list.length;
                             i < x;
                             i++) {
                                if (path.extname(list[i]) === ext) {
                                        console.log(list[i]);
                                }
                        }
                  }
                });
}

This is what I have for program.js

var mymodule = require('./mymodule.js');
mymodule(process.argv[2], process.argv[3]);

**Comment by lvivier** [comment]
You're off to a good start modularizing your program. This is a tricky exercise for a lot of people, so there are [lots of issues about Make It Modular](https://github.com/nodeschool/discussions/issues?q="make+it+modular"+%7C+6). In your case, your module needs to export an interface like this:

```js
// "must export a single function that takes three arguments..."
module.exports = function (dirname, ext, callback) {}
```

The callback function should use the `(err, data)` signature that's common to most node APIs:

```js
// "callback function must be called using the idiomatic node convention"
callback(err, dirlist)
```

Right now your program doesn't do anything but call the module. What you'll need to do is change it so that it passes a callback function as the third argument, and that callback's responsibility will be to log the list of directories to the console.

Good luck!

**Comment by bessieatrazoyo** [comment]
Thanks!  I figured it out.  (Spoiler alert for those trying to learn.  The following code works.)

─────────────────────────────────────────────
program.js:
var mymodule = require('./mymodule.js');
function printArray(error, data) {
        if (error != null) {
                console.log("Error: " + error);
        } else {
                for (var i = 0, x = data.length; i < x; i++) {
                        console.log(data[i]);
                }
        }
}

mymodule(process.argv[2], process.argv[3], printArray);
─────────────────────────────────────────────
mymodule.js:
module.exports = function (dirname, ext, callback) {
        var fs = require('fs'),
            path = require('path'),
            ext = '.' + ext;

        fs.readdir(dirname,
                function (err, list) {
                  if (err) {
                        callback(err);
                  } else {
                        var data = [];
                        for (var i = 0, x = list.length;
                             i < x;
                             i++) {
                                if (path.extname(list[i]) === ext) {
                                        data.push(list[i]);
                                }

                        }

                  callback(null, data);
                  }
                });

**Comment by lvivier** [comment]
@bessieatrazoyo good going! :+1:
