### ISSUE TITLE
learyounode: "Cannot find ansicolors" error

### ISSUE THREAD

**Issue by TacoBelle** [nodeschool/discussions#1528]
- Windows 8.1 64bit
- Installed learnyounode.js with -g
- nodejs path: C:\Program Files\nodejs 
- npm path: C:\Users\MelinaAccount\AppData\Roaming\npm
- When trying to run learnyounode.js and hitting enter on "Hello World" I get the following error: 
  module.js:339
  throw err;
  ^

Error: Cannot find module 'ansicolors'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\workshopper-adventure\node_modules\@leichtgewicht\msee\lib\syntaxColor.js:1:76)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
- Things I tried (with the same result)
  
  ```
    - Cleared out cache
    - Clicked on learnyounode.js 
    - Updated node to last version
    - Javascripting appears to be working (it's installed in the same path)
    - Reinstalled learnyounode.js at least 3 times
    - Ansicolors is installed both under C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\@leichtgewicht\msee\node_modules\cardinal\node_modules\ansicolors and C:\Program Files\nodejs\node_modules\npm\node_modules
  ```

Hopefully I'm just missing something. Any help appreciated!

**Comment by martinheidegger** [comment]
I have published a new version of learnyounode today. This problem should
be fixed.

**Comment by TacoBelle** [comment]
Thanks. 
I re-installed twice. The first time, the installation didn't work and  I got the following error when trying to run learnyounode:  C:\Users\MelinaAccount>learnyounode
C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\explicit\lib\schem
a\options.js:15
        Joi.array().includes(Plugin, Joi.string()),
                    ^

TypeError: Joi.array(...).includes is not a function
    at Object.<anonymous> (C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\explicit\lib\schema\options.js:15:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\explicit\lib\validate\options.js:5:27)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

I cleared out the cache, re-installed and got the following error (not sure you need it but just in case you do)

C:\Users\MelinaAccount>npm install -g learnyounode
npm WARN install:estraverse ENOENT: no such file or directory, rename 'C:\Users\MelinaAccount\AppDa
a\Roaming\npm\node_modules\learnyounode\node_modules\escope\node_modules\estraverse' -> 'C:\Users\M
linaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\escope\node_modules\estraver
e'
npm WARN install:doctrine ENOENT: no such file or directory, rename 'C:\Users\MelinaAccount\AppData
Roaming\npm\node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\doctrine' -> 'C:\
sers\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\no-shadow-relaxed\nod
_modules\doctrine'
npm WARN install:inquirer ENOENT: no such file or directory, rename 'C:\Users\MelinaAccount\AppData
Roaming\npm\node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\inquirer' -> 'C:\
sers\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\no-shadow-relaxed\nod
_modules\inquirer'
estraverse@3.1.0 node_modules\learnyounode\node_modules\escope\node_modules\estraverse -> node_modu
es\learnyounode\node_modules\escope\node_modules\estraverse
esrecurse@3.1.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandic
\node_modules\lab\node_modules\eslint\node_modules\escope\node_modules\esrecurse -> node_modules\le
rnyounode\node_modules\esrecurse
escope@3.2.0 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\n
de_modules\lab\node_modules\eslint\node_modules\escope -> node_modules\learnyounode\node_modules\es
ope
object-assign@4.0.1 node_modules\learnyounode\node_modules\globby\node_modules\object-assign -> nod
_modules\learnyounode\node_modules\file-entry-cache\node_modules\object-assign
minimist@0.0.8 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\minimist -> no
e_modules\learnyounode\node_modules\lab\node_modules\minimist
mkdirp@0.5.1 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\mkdirp -> node_m
dules\learnyounode\node_modules\lab\node_modules\mkdirp
minimatch@2.0.10 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandi
o\node_modules\lab\node_modules\eslint\node_modules\minimatch -> node_modules\learnyounode\node_mod
les\minimatch
glob@5.0.15 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\rimraf\node_m
dules\glob -> node_modules\learnyounode\node_modules\glob
globby@3.0.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\n
de_modules\lab\node_modules\eslint\node_modules\file-entry-cache\node_modules\flat-cache\node_modul
s\del\node_modules\globby -> node_modules\learnyounode\node_modules\globby
del@2.0.2 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\node
modules\lab\node_modules\eslint\node_modules\file-entry-cache\node_modules\flat-cache\node_modules\
el -> node_modules\learnyounode\node_modules\del
flat-cache@1.0.10 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\command
co\node_modules\lab\node_modules\eslint\node_modules\file-entry-cache\node_modules\flat-cache -> no
e_modules\learnyounode\node_modules\flat-cache
file-entry-cache@1.2.4 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\co
mandico\node_modules\lab\node_modules\eslint\node_modules\file-entry-cache -> node_modules\learnyou
ode\node_modules\file-entry-cache
doctrine@0.6.4 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\doctrine -> no
e_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\doctrine
inquirer@0.8.5 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\inquirer -> no
e_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\inquirer
ansi-regex@2.0.0 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\ansi-regex -
 node_modules\learnyounode\node_modules\simple-terminal-menu\node_modules\ansi-regex
ansi-styles@2.1.0 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\ansi-styles
-> node_modules\learnyounode\node_modules\simple-terminal-menu\node_modules\ansi-styles
has-ansi@2.0.0 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\has-ansi -> no
e_modules\learnyounode\node_modules\simple-terminal-menu\node_modules\has-ansi
strip-ansi@3.0.0 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\strip-ansi -
 node_modules\learnyounode\node_modules\simple-terminal-menu\node_modules\strip-ansi
supports-color@2.0.0 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\supports
color -> node_modules\learnyounode\node_modules\simple-terminal-menu\node_modules\supports-color
chalk@1.1.1 node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\chalk -> node_mod
les\learnyounode\node_modules\simple-terminal-menu\node_modules\chalk
simple-terminal-menu@1.1.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_module
\simple-terminal-menu -> node_modules\learnyounode\node_modules\simple-terminal-menu
eslint@0.24.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\
ode_modules\lab\node_modules\eslint-plugin-hapi\node_modules\no-shadow-relaxed\node_modules\eslint
> node_modules\learnyounode\node_modules\no-shadow-relaxed\node_modules\eslint
no-shadow-relaxed@1.0.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\c
mmandico\node_modules\lab\node_modules\eslint-plugin-hapi\node_modules\no-shadow-relaxed -> node_mo
ules\learnyounode\node_modules\no-shadow-relaxed
eslint-plugin-hapi@1.2.2 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\
ommandico\node_modules\lab\node_modules\eslint-plugin-hapi -> node_modules\learnyounode\node_module
\eslint-plugin-hapi
eslint@1.5.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\n
de_modules\lab\node_modules\eslint -> node_modules\learnyounode\node_modules\eslint
lab@5.18.1 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandico\nod
_modules\lab -> node_modules\learnyounode\node_modules\lab
commandico@2.0.0 node_modules\learnyounode\node_modules\workshopper-adventure\node_modules\commandi
o -> node_modules\learnyounode\node_modules\commandico
- C:\Users\MelinaAccount\AppData\Roaming\npm\node_modules\learnyounode\node_modules\simple-terminal
menu node_modules\learnyounode\node_modules\simple-terminal-menu
C:\Users\MelinaAccount\AppData\Roaming\npm
└── (empty)

npm ERR! code 1

Any suggestions? Thanks!
