### ISSUE TITLE
Lessons Menu Gets Stuck....

### ISSUE THREAD

**Issue by tomarone** [nodeschool/discussions#1532]
I updated to node 5.0.0 I am running a windows laptop, (it's 8.1)
The first time the menu is OK. (for lessons such as 'learnyounode' etc.)
After a code test and run, the menu gets stuck, the keys up/down do not work
Is there another way to Up/Down the menu? (other than keys ↑↓)
(this is the lesson progress menu: white text over blue background.)
What module needs to be fixed here?

**Comment by SomeoneWeird** [comment]
#1448

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0
