### ISSUE TITLE
Question on Making it Modular

### ISSUE THREAD

**Issue by MichaelLSmith** [nodeschool/discussions#1534]
In the official solution file filter.js, what does line 14 do?

```
callback(null, list)
```

**Comment by markthethomas** [comment]
@MichaelLSmith can you include a link to the source?

**Comment by lvivier** [comment]
[source](https://github.com/workshopper/learnyounode/blob/master/exercises/make_it_modular/solution/solution_filter.js#L14)

@MichaelLSmith in the solution, on line 4 the third argument is `callback`, which should be a function. On line 8, `callback` is called with an error, and on line 14, `callback` is called with `null` (signifying "no error" in the node callback style) and the array of directory names.

**Comment by markthethomas** [comment]
what @lvivier said, in context:
```
var fs = require('fs')
var path = require('path')

module.exports = function (dir, filterStr, callback) {

  fs.readdir(dir, function (err, list) {
    if (err)
      // the callback fn returned here would only have err set; list is null
      return callback(err)

    // no error, so we can define the list value to return
    list = list.filter(function (file) {
      return path.extname(file) === '.' + filterStr
    })

    // no error to return, so send null and the list value back. This style of callback lets you check for an       
    //  error *and* the returned value. Something like promises take a different approach by (usually) 
    // bifurcating the value/error into `.then()` and `.catch()`
    callback(null, list)
  })
}
```

**Comment by MichaelLSmith** [comment]
Thank you guys. That really makes sense. I'm slowly getting this.

**Comment by markthethomas** [comment]
:+1:
