### ISSUE TITLE
Stream-Adventure TRANSFORM exercise not working - curious as to potentially why?

### ISSUE THREAD

**Issue by scottpatrickwright** [nodeschool/discussions#1535]
The exercise is simple and I am not having any trouble following it appears however the through2 callback is never called - even when I test with the official solution. Any idea why?

here is my code:
```
    var through = require('through2');
    var tr = through(function (buf, _, next) {
        console.log('I never see this log and the output letters are not uppercased');
        this.push(buf.toString().toUpperCase());
        next();
    });
    process.stdin.pipe(tr).pipe(process.stdout);
```

**Comment by scottpatrickwright** [comment]
Simple UI problem - need to hit enter to update the stream. I expected it to update on keypress

**Comment by shon3005** [comment]
i still don't know why the code isn't working

**Comment by noffle** [comment]
`stdin` tends to buffer complete lines until they are ended with a newline (`\n`) character.

Try running your program, typing in 'hello', then hitting enter. You should see your output once you hit enter. e.g.

Assuming your code is in `trans.js`:
```
$ node trans.js 
foo       <--- type this in then hit ENTER; the below text will appear
I never see this log and the output letters are not uppercased
FOO
```

**Comment by scottpatrickwright** [comment]
Thats makes sense thanks @noffle

**Comment by shon3005** [comment]
thanks!
