### ISSUE TITLE
lesson isn't working

### ISSUE THREAD

**Issue by dogis** [nodeschool/discussions#1539]
![nodeschool-learnyounodecapture](https://cloud.githubusercontent.com/assets/14012643/11162296/dc1cee3e-8ad6-11e5-801c-8e70f78cf95f.PNG)
i can't switch to 2nd exercise, the selection is not responding to neither arrow keys nor mouse click. how to proceed to next exercise?

**Comment by SomeoneWeird** [comment]
Known issue, unfortunately #1448

**Comment by dogis** [comment]
i see.. should i close this issue?

**Comment by SomeoneWeird** [comment]
Keep it open until the issue if fixed :)

You should be able to work around the issue by doing `learnyounode select <number>`

**Comment by dogis** [comment]
Alright, thanks for the workaround @adam

**Comment by dogis** [comment]
TylerMoeller commented 3 hours ago
Verified as fixed with Node v5.1.0. All menus working as expected on my Win10 64bit install. Thanks for getting this checked in. Windows Nodeschoolers will be much happier now.
