### ISSUE TITLE
json api server Error connecting to http://localhost:32213: connect ECONNREFUSED

### ISSUE THREAD

**Issue by michaelshum** [nodeschool/discussions#154]
When doing the JSON API Server exercise it always throws this error

Error: connect ECONNREFUSED
at: errnoException (net.js:901:11)
at Object.afterConnect [as oncomplete] (net.js:892:19)

What is wrong?

**Comment by martinheidegger** [comment]
Closing this entry because it is too mixed (and seems to be resolved)
