### ISSUE TITLE
baby steps

### ISSUE THREAD

**Issue by samcyn** [nodeschool/discussions#1540]
i don't really understand what's going on in the this exercise.  i have written down this code in my program.js file. believing i'm correct, i decided to test run and as well verify. the test ran but wasn't verified.
 
```js
console.log(process.argv);
var output = 0;
for(var i =2; i < process.argv.length; i++){
    output += Number(process.argv[i]);
}

console.log(output);
```

**Comment by kohei-takata** [comment]
Hi, @samcyn !

Your code is almost correct.
Would you try to comment out the line 1?
Like this.
```
// console.log(process.argv);
```

You should output only the sum of numbers.

**Comment by samcyn** [comment]
thanks @kohei-takata it worked. cheers.

**Comment by SomeoneWeird** [comment]
:tada:
