### ISSUE TITLE
Algiers Chapter

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/discussions#1541]
Being the first chapter in Maghreb countries(Algeria,Libya, Morocco and Tunisia) north Africa, is an honor for us.
Knowing the fact that we have a lot of students and developers interested in learning JavaScript generally and  Node.js  specifically here in Algeria(north africa).
With a simple command line based courses, learning JavaScript is funny and exciting.
Simply this is why we want to start our own chapter here in Algeria, i have with me a group of motivated and experienced  awesome people.
I hope my request will be accepted, thank you for this great work and can't wait to start this chapter and why not collaborating with other chapters. Thank you again and have a nice day/night(wherever you are )

**Comment by martinheidegger** [comment]
Please open a request in https://github.com/nodeschool/organizers/issues

**Comment by martinheidegger** [comment]
I have been a little in a hurry and forgot my manners: It is awesome that you want to create a chapter! It would be nice to have the conversation in the right place. Would you mind to open a request in the organizers repo?

**Comment by ismnoiet** [comment]
Ok  no problem
