### ISSUE TITLE
learnyounode ex 11 http file server 

### ISSUE THREAD

**Issue by annandr12** [nodeschool/discussions#1543]
My code:

``` javascript
    var http = require('http');
  var fs = require('fs');

var server = http.createServer(function callback (request, response) {
  var income = fs.createReadStream(process.argv[3]); 
  income.pipe(response);
});
server.listen(Number(process.argv[2]));
```

When I run the code, I get an answer, and no errors.
But when I verify the code, then nothing happens. Maybе connection does not close. I don't know.  What should I do?

**Comment by davecocoa** [comment]
That code passes when I run `verify`, could you tell us your version of node and which operating system you're using?

**Comment by annandr12** [comment]
Version of node is v0.12.7
____
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
