### ISSUE TITLE
Weird selection bug

### ISSUE THREAD

**Issue by DonRichards** [nodeschool/discussions#1546]
After completing the first task and run the command again it won't select the next item. On "Going Native" I could hit Enter once and then use the up and down arrow keys but on "Learn your react" I'm unable to progress to the second step. This issue happens with a few of the tutorials. Has anyone else experienced this? 

Node v5.0.0
Windows 10
Cmder v1.2

I tried it in cmd & Cmder

**Comment by SomeoneWeird** [comment]
Update to node 5.1.0 and it should fix your issue :)

**Comment by DonRichards** [comment]
That's it! Thanks!
