### ISSUE TITLE
[Scope Chains]:CLOSURES

### ISSUE THREAD

**Issue by jlixerkun** [nodeschool/discussions#1547]
I can't figure this out. Apparently it's too easy, but I keep getting the same error.

My version of node is 4.2.2
and i'm running it on windows 8.1

I have this code:

```
function foo() {
    var bar;
    quux = 6;
    function zip() {
        bar = true;
        return bar;
    }
    return zip();
}
```

When I run this file, the console output says:

```
TAP version 13
# (anonymous)
ok 1 Solution loaded
not ok 2 The structure is correct
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t
\t- var quux\n\t\t- bar = ?'
    actual:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\t\tzip()\n\t\t- bar = ?\n\
t\t- bar = ?\n\t\treturn bar'

1..2
# tests 2
# pass  1
# fail  1
```

I've browsed arround but I don't understand what is wrong in my code...
Any help is much appreciated

**Comment by riyadhalnur** [comment]
@jlixerkun Almost there. You have to define `quxx` inside the `zip` function but this time with a different value than the one you assigned to the global `quxx` inside the `foo` function. Something in the lines of -    

```js
function foo() {
  quxx = 6;
  function zip() {
    var quxx = 10;
  }
}
```

**Comment by jlixerkun** [comment]
I'm about to try that, but then again, I can't select the proper exercise to run validation... O.o

**Comment by osvfr** [comment]
function foo() {
 var bar;
 quux = 7;
 return zip;

 function zip() {
   var quux = 'quux';
   bar = true;
 }
}
