### ISSUE TITLE
Can't move to next exercise

### ISSUE THREAD

**Issue by jlixerkun** [nodeschool/discussions#1552]
I was doing fine on the scope-chains-closures workshop. However, i can no longer select the next exercise to continue the workshop.

I installed the latest version of node (4.2.2), re-installed the workshop and tried again, but to no avail.

I installed another workshop (functional javascript) and it behaves in the same manner....

**Comment by riyadhalnur** [comment]
@jlixerkun are you on Windows?

**Comment by jlixerkun** [comment]
Thankyou very much for your attention. 
I am running these on the windows command line, yes. And the OS is Windows 8.1.
It was working fine, right until I reached the closures exercise on the sccjs workshop. 
Strange huh?

**Comment by jlixerkun** [comment]
I Even tried it on another machine and get the same result. 
Can't move with the arrows to select different challenge

**Comment by riyadhalnur** [comment]
You can try selecting an exercise using `learnyounode select <exercise_number>`

**Comment by SomeoneWeird** [comment]
Please update to node 5.1.0, it fixes a bug that makes moving fail on windows.
