### ISSUE TITLE
Hi guys what you think about nodeschool workshops manager

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/discussions#1556]
Hi, hope you're doing good.
I've created a node package called **nodeschool-workshops** , and i think it is an awesome tool to make it even easier to learn with nodeshcool workshops 

here is the github repo : 
https://github.com/ismnoiet/nodeschool-workshops-manager

and the npmjs page : 
https://www.npmjs.com/package/nodeschool-workshops

Any feedback or suggestion or anything else is more then welcome
Thank you for your time :)

**Comment by martinheidegger** [comment]
As said in gitter conversation. I think it is a step in the right direction. Need to think of some way to centralise the data structure (same for homepage & cli tool would be good.

**Comment by ismnoiet** [comment]
@martinheidegger you're right as usual the workshops information should be stored somewhere in a centralized place

**Comment by sotayamashita** [comment]
@ismnoiet I am creating workshops in Electron to centralise data of it. it is still private repo. if you would like to see it, please let me know. I will add you as a collaborators.

**Comment by ismnoiet** [comment]
@sotayamashita thx for the invitation i'm very excited to see what you're developing  :+1: 
come find me in gitter as **ismnoiet**

**Comment by sotayamashita** [comment]
@ismnoiet I just started it. If you have suggestion, feel free to create issue.
