### ISSUE TITLE
Chapter in Havana, Cuba 

### ISSUE THREAD

**Issue by robertkowalski** [nodeschool/discussions#1562]
Hi!

I want to run a Nodeschool in Havana, Cuba - which is kind of a special location as most Cubans don't have direct access to the internet. I definitely want to bring JavaScript to Cuba.

I am there in April for http://www.cubaconf.org/ but I don't live in Cuba. I already know Pablo from Havana who would help us and I am searching for more people from Cuba and/or people that are in Cuba in April. :)

I recently blogged about software development in Cuba after I saw a talk from Pablo in Germany, I hope it can provide some additional background informations about Cuba and Open Source Software: http://kowalski.gd/blog/software-development-in-cuba/

**Comment by SomeoneWeird** [comment]
Sorry! I'm surprised nobody else got back to you on this. Are you still looking at running one?

**Comment by robertkowalski** [comment]
Thanks for asking @SomeoneWeird! Yes, I'm still interested and finally found [a doc](https://github.com/nodeschool/organizers#how-to-start-a-new-nodeschool-chapter) with more details on organizing the event, especially how to start a chapter (I just read http://nodeschool.io/host.html before, which points to https://github.com/nodeschool/organizers/wiki). 

Also found that most chapter requests happen on https://github.com/nodeschool/organizers

I thought I open an issue on https://github.com/nodeschool/organizers once we are three people, as nobody replied to this issue.

**Comment by SomeoneWeird** [comment]
Yeah, that would be ideal. Usually we ask that chapters have more than one organiser, so if you find a couple other people to help, open another issue over on the organizers repo and we'll handle it from there :+1:
