### ISSUE TITLE
Failed to install learnyounode

### ISSUE THREAD

**Issue by opn** [nodeschool/discussions#1563]
Installation is failing node v5.0.0 and npm v3.3.6 on OSX El Capitan.
Initial errors - https://gist.github.com/opn/1dd567d2cb51fe1a5284
after npm un learnyounode I still get errors

Other  workshoppers function fine. Mabe due to an earlier install - how can I remove / fix?

**Comment by opn** [comment]
OK - fixed it - npm uninstall -g learnyounode followed by npm install -g learnyounode

**Comment by SomeoneWeird** [comment]
:)
