### ISSUE TITLE
Organizing a Node.js project and looking for contributors

### ISSUE THREAD

**Issue by komputes** [nodeschool/discussions#1564]
Hi Node Devs,

jobhere.ca is a web application which revolutionizes the way we look for work. Version 1.0 allows users from Toronto, Montreal and Vancouver to geographically visualize job listing data, offering a simple, efficient, and convenient job search experience. The project was conceived for the 2015 Koding/IBM Hackathon and will be intentionally limited in scope. The mandate of the web application for the Hackathon is to be able to search and parse recent job listings data from Indeed.com for Toronto, Montreal and Vancouver and plot them onto Google Maps using a location provided by the listing or acquired through other means. We hope to get funded through this hackathon and become a globally distributed startup in 2016.

Time being a major factor, we are continuously developing while looking for talented creative thinkers (hackers, developers and mathematicians) to join the team. If you'd like to contribute, get in touch with me.

If you can't, but you like the idea, please consider spreading the word in your network.

Best regards,

David Bensimon
514-836-2399

Site specifications:
http://jobhere.ca:4000/jekyll/blog/dev/update/2015/11/28/welcome-to-jobhere.html

**Comment by SomeoneWeird** [comment]
Not here either.
