### ISSUE TITLE
Exercise #4 of scope-chains-closures is not verifying a (supposed) correct solution?

### ISSUE THREAD

**Issue by zedee** [nodeschool/discussions#1569]
On the exercise number 4 of scope-chains-closures, I'm not having the exercise validated.

**My code**:
```
function foo() {
  var bar;
  quux = 1;
  
  return function zip() {    
    var quux = 0;
    bar = true;
  };
}
```

But it's failing the test... 
**Verify Output**:

```
 expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
    actual:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
```

I've tested this very same code in Chrome Dev Tools and it does indeed return function zip(), not the result of zip(), as the task states.

Result from Chrome Dev Tools (screenshot):

![Chrome DevTools Result](http://i.imgur.com/KsULZWb.png)

I'm pretty sure I'm missing something, but have no clue what...

**Comment by darrenjaworski** [comment]
function foo() {
  var bar;
  quux = 1;

  function zip() {    
    var quux = 0;
    bar = true;
  };
return zip;
}

**Comment by TomDeFrank** [comment]
Aren't these the same thing?

`  function zip() {    
    var quux = 0;
    bar = true;
  };
  return zip;`

and 

`return function zip() {    
    var quux = 0;
    bar = true;
  };`

**Comment by noffle** [comment]
@TomDeFrank can you give more context?

**Comment by TomDeFrank** [comment]
@noffle 
`function zip() { var quux = 0; bar = true; }; return zip;`
fails the fourth exercise but
return function zip() { var quux = 0; bar = true; };
passes

They are effectively the same thing so I am asking why they don't both pass.

**Comment by noffle** [comment]
@TomDeFrank Can you share your full solution? I'm trying this on my end but this is passing:

```js
function foo () {
  var bar
  quux = 17

  function zip () {
    var quux = 0
    bar = true
  }
  return zip
}
```

**Comment by TomDeFrank** [comment]
this will not:

`function foo () {
  var bar
  quux = 17

  function zip () {
    var quux = 0
    bar = true
  }
  return zip
}`

**Comment by noffle** [comment]
@TomDeFrank: It doesn't look like this failing because of any error in reasoning on your behalf, it's seems that the test harness expects a specific structure that matches against:

```
'(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
```

Your `return function zip()` answer is also 100% correct!

**Comment by zedee** [comment]
All right, so the reasoning is correct but not the expected result of the test!

Now I see it clear, thanks! :+1:

**Comment by riyadhalnur** [comment]
Yeah, the exercise expects you to write the solution a certain way. Otherwise, there's no difference at all between the 2 code samples you mentioned.
