### ISSUE TITLE
Can't choose menu on terminal

### ISSUE THREAD

**Issue by setyows** [nodeschool/discussions#1571]
I can't select a menu in the terminal of any given challenge, I've been using the navigation up and down but there was no movement, and I can't choose.
I use windows 10 pro and node.js version 4.2.3-x64, what causes it? Please help. Thank you.

**Comment by SomeoneWeird** [comment]
Known issue, please update to node 5.1.0.

**Comment by setyows** [comment]
thanks master, is working now :)
