### ISSUE TITLE
My First I/O!

### ISSUE THREAD

**Issue by yiweiang** [nodeschool/discussions#1572]
For some reason, I'm getting the right results, but my solution didn't pass - how do I troubleshoot?

Your submission results compared to the expected:

```
             ACTUAL                                 EXPECTED                
```

   "49"                                ==    "49"  
   ""                                  ==    ""                                 

 ✓ Submission results match expected  

```
 # FAIL  
```

Your solution to MY FIRST I/O! didn't pass. Try again!

**Comment by kishanera** [comment]
Can you please post your code.

**Comment by andrii-skliar** [comment]
Hi! What file path should I use in fs.readFileSync(....) invocation in order to pass verification with test data?

**Comment by andrii-skliar** [comment]
My code is:
(function () {
    'use strict';
    
    let fs = require('fs');
    let buffer = fs.readFileSync(**'???'**);
    let content = buffer.toString();
    let newLines = content.split('\n').length - 1;            
                
    console.log(newLines);
    
})();
