### ISSUE TITLE
how to move up and down on command line while using javascripting

### ISSUE THREAD

**Issue by krishnamedikeri** [nodeschool/discussions#1574]
![learnyounode](https://cloud.githubusercontent.com/assets/12498264/11660431/1d5e5836-9df3-11e5-92e7-3d93f343f2e6.png)

I have installed learnyounode from npm installer, while going through the tutorial I'm unable to move up and down through arrow buttons.
How to move up and down.

**Comment by ismnoiet** [comment]
Simply use the **vi** style meaning 
**j** : for going down 
**k** : for going up

**Comment by krishnamedikeri** [comment]
I'm using windows 10, j and k are not working.

**Comment by alagiboy** [comment]
I assume that you trying to doing this with the mouse. 

If so, you can accomplish this by using your arrow up and down keys, hit enter when on the problem and that problem will be opened in your terminal, once submitted and it passed you will see that its marked completed and next problem will be highlighted.

**Comment by bartoszbinda** [comment]
I can't do the same thing. I sumbitted the HELLO WORLD, it's marked as complete but if i press enter, i t still wants to do the same thing. I am using win8

**Comment by alagiboy** [comment]
ok another way  you can do this is by calling the specific exercise. 

eg. javascripting select variables 

running that code in your terminal will open the variables exercise. 
I hope this helps.

**Comment by riyadhalnur** [comment]
If you're using Node version 4.x, please upgrade to version 5.x. This is a known issue in v4.

**Comment by shachaoshu** [comment]
@riyadhalnur, thanks for the suggestion. I had the safe issue with node version 4.2.3, and after upgrade node to version 5.2.0, the problem was gone.

**Comment by riyadhalnur** [comment]
@shachaoshu glad it works now :smiley:
