### ISSUE TITLE
Can't verify introduction.js

### ISSUE THREAD

**Issue by jalderwood** [nodeschool/discussions#1575]
Win7/64 + NodeJS 5.1

I created and modified introduction.js as directed. When I try to verify I get the following error.

C:\Dev\nodejs\javascripting>javascripting verify introduction.js
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "node "C:\Dev\nodejs
\javascripting\introduction.js""
C:\Dev\nodejs\javascripting\introduction.js:1
(function (exports, require, module, __filename, __dirname) { console log 'hello
';
                                                                      ^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\Windows\system32\cmd.exe /s /c "node "C:\Dev\nodejs\javascripti
ng\introduction.js""' }

**Comment by XLCM** [comment]
This is the first activity in the Javascripting track?

Can you post your code?

**Comment by jalderwood** [comment]
I just found someone with a similar problem on these forums. FYI the problem is that the instructions for Introduction say to put <b>console log 'hello';</b> rather than <b>console.log('hello');</b> which I just figured out and it works now. I wasn't counting on the instructions being wrong..
