### ISSUE TITLE
Dumb questions, just started, how can you select an exercise in cmd?

### ISSUE THREAD

**Issue by cKevinn** [nodeschool/discussions#1577]
So I just started this learnyournode module, when I get this menu in cmd, I can hit enter for the first exercise.
But I can't hit arrow up and down to get to the second exercise in that menu?

**Comment by SomeoneWeird** [comment]
Known issue, if you update to the latest node version it should work :)

**Comment by cKevinn** [comment]
I've installed the LTS (v4.2.3) version of node yesterday, so I already have the latest version?
Or do i need the stable one, v5.2.0

**Comment by SomeoneWeird** [comment]
Yeah, it was fixed in 5.1.0. Should really be backported into LTS though.

**Comment by cKevinn** [comment]
How do I actually update from v4.2.3 to 5.1.0? By first uninstalling node from my computer and downloading 5.1.0?

**Comment by riyadhalnur** [comment]
@cKevinn Download 5.2.0 and install as normal. It will overwrite version 4 :smile:
