### ISSUE TITLE
I use process.argv,it show nodejs's absolute path 

### ISSUE THREAD

**Issue by hualuomoli** [nodeschool/discussions#1584]
i want to print like `[ 'node', '/path/to/your/program.js']`,but which i print like below
`[ 'C:\\Program Files\\nodejs\\node.exe',
  'E:\\github\\nodeSchool\\program.js' ]`

**Comment by lvivier** [comment]
`process.argv[0]` is equal to `process.execPath` (see [src/node.js:49](https://github.com/nodejs/node/blob/master/src/node.js#L49)). You can get the command name with `process.title` though:

```bash
$ node -e 'console.log(process.title, process.argv)'
node [ '/path/to/node' ]
```

**Comment by hualuomoli** [comment]
try it
