### ISSUE TITLE
Trouble with modules. Exercise 6 Make it modular (learnyounode)

### ISSUE THREAD

**Issue by Pranjal5** [nodeschool/discussions#1585]
var fs = require('fs')
var path = require('path')
var dir = process.argv[2];
var filterStr = process.argv[3];

module.exports = function(dir, filterStr, callback){
	function bar(callback){
		foo(function(err, data){
			if(err)
				return callback(err)

			list = list.filter(function(file){
				return path.extname(file) === '.'+ filterStr
			})
			callback(null, data)
		})
	}
}

**Comment by noffle** [comment]
It would be helpful to write a bit about the code you've pasted: what is the problem? What do you think this code should do vs what does it do?

**Comment by Pranjal5** [comment]
This is problem I wrote the code for..

Create a program that prints a list of files in a given directory,
  filtered by the extension of the files. The first argument is the
  directory name and the second argument is the extension filter. Print the
  list of files (one file per line) to the console. You must use
  asynchronous I/O.

  You must write a module file to do most of the work. The module must
  export a single function that takes three arguments: the directory name,
  the filename extension string and a callback function, in that order. The
  filename extension argument must be the same as what was passed to your
  program. Don't turn it into a RegExp or prefix with "." or do anything
  except pass it to your module where you can do what you need to make your
  filter work.

  The callback function must be called using the idiomatic node(err, data)
  convention. This convention stipulates that unless there's an error, the
  first argument passed to the callback will be null, and the second will be
  your data. In this exercise, the data will be your filtered list of files,
  as an Array. If you receive an error, e.g. from your call to
  fs.readdir(), the callback must be called with the error, and only the
  error, as the first argument.

**Comment by noffle** [comment]
What is the behaviour you're getting compared to what you'd like it to do, *in your own words*?

**Comment by Pranjal5** [comment]
Instead of getting file names of specified extension and the output is ""
For example there are many file with different extensions and user enters the extension .txt so it should give all files with extension .txt instead it gives nothing.

**Comment by noffle** [comment]
In your `module.exports` function, I see this code:

```
function bar(callback){
  foo(function(err, data){
    if(err)
      return callback(err)
    list = list.filter(function(file){
      return path.extname(file) === '.'+ filterStr
    })
    callback(null, data)
  })
}
```

Some clarifying questions:

1. You're defining a function `bar` but not doing anything with it. Consider this equivalent block of code:

```
function hello() {
  function baz() {
    console.log('hello')
  }
}
```

When you run `hello()`, this would print nothing, since all the function does is define another function called `baz`. You **could** call `baz` to call the inner function:

```
function hello() {
  function baz() {
    console.log('hello')
  }
  baz()
}
```

This would work and print 'hello'. But the inner function is redundant, much like in your code. You can simplify this to just

```
function hello() {
  console.log('hello')
}
```

2. What is your understanding of your other inner function, `foo`? It's a function you're trying to call that isn't defined anywhere. What do you want `foo` to do?
