### ISSUE TITLE
learnyounode time server verify does not complete

### ISSUE THREAD

**Issue by dzjc** [nodeschool/discussions#1586]
Hello!
For some reason the verification does not complete for me.
I get the following output after entering 'learnyounode verify timeServer.js"
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "2015-12-18 13:21"                  ==    "2015-12-18 13:21"    
```

From googling around it seems like it should print out the new line after the date/time but nothing happens even after waiting a few minutes.

Here's my timeServer.js code

```javascript
var net = require('net');
var date = new Date();
var port = Number(process.argv[2]);

var server = net.createServer(function(socket){
	socket.write(getTime1());
});
server.listen(port);

var twoPadd = function(data){
	return (data >= 10) ? data : '0' + data.toString();
};

var getTime1 = function(){
	var time = date.getFullYear();
	time +='-' + twoPadd(date.getMonth() + 1);
	time +='-' + twoPadd(date.getDate());
	time +=' ' + twoPadd(date.getHours());
	time +=':' + twoPadd(date.getMinutes()) + '\n';
	return time;
};
```

Any help would be much appreciated thanks !

**Comment by noffle** [comment]
Awesome code! There's just this little bit in the **HINTS** section that might tip you off to what the last piece is:

>  Use socket.write(data) to write data to the socket **and socket.end() to close the socket**. Alternatively, the .end() method also takes a data object so you can simplify to just: socket.end(data).

`write()` will write data to the socket, while `end()` will write to the socket and then close the connection. Your `learnyounode verify` step is hanging because there is still a socket connection alive.

**Comment by dzjc** [comment]
Thank you! I've closed the socket and it verifies fine now.
Of course the solution was right in front of me the whole time...
