### ISSUE TITLE
Confused How to start

### ISSUE THREAD

**Issue by feteezuk** [nodeschool/discussions#1588]
How should i start?

**Comment by noffle** [comment]
What OS are you on? Do you have Node installed? There's a bit labeled "Get Going" under *Workshoppers* that links to Node and NPM, and the commands to run to get the first workshopper going. Is there a particular step you're stumped on?

**Comment by feteezuk** [comment]
Osx 10.10.2.  It says err run as root/administrator when i run code "npm install -g learnyounode". How do i become the administrator of my terminal?

**Comment by noffle** [comment]
The 'sudo' command lets you do this. Try

sudo npm install -g learnyounode

You might find 'javascripting' a gentler intro if you're new to programming.

**Comment by feteezuk** [comment]
So, for some reason that still gave me the error message.  I was able to
get in using sudo -s, and then plugging in the install code.  But i was
logged in under a #bash which was weird.  What is a #bash mean??

**Comment by cguilhermef** [comment]
You are using El Capitan OSX? 
Maybe it can help you:

https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

**Comment by HiOrange** [comment]
sudo commands helped. I am on OS-X :-)
