### ISSUE TITLE
regarding ENOENT stat error

### ISSUE THREAD

**Issue by ramsk4u** [nodeschool/discussions#1589]
Hi, 

I am using sendFile option to view the uploaded file. I used try catch to handle exception like if the file is not found i am showing file not found error. In my local system(windows 10) this code ios working but in the server(linux) its showing ENOENT, stat error.. what could be the reason. how to fix it.

Early help is requested. Thanks in Advance.

**Comment by finnp** [comment]
Sorry, this is probably the wrong place for ask this kind of questions. Also your description is a bit too vague. Maybe http://stackoverflow.com/ can help you. Good luck!
