### ISSUE TITLE
learn-sass: ENOENT error during verify stage

### ISSUE THREAD

**Issue by isvicbhasme** [nodeschool/discussions#1590]
When I try to verify the first exercise I get the following error.

```
C:\Users\ibhasme\Apps\learnSass>learn-sass verify variables.scss
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\ibhasme\AppData\Roaming\npm\node_modules\learn-sass\node_modules\node-sass\bin\node-sass ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

The contents of variable.scss is as below

```
$color: #000;
body {
    color: $color;
}
```

I'm using node v4.2.3
May I'm missing some libraries/modules. Could someone help me with this please.

Thank you.

**Comment by dogfeat** [comment]
I have an almost identical problem when I try to verify my stylesheet. I named my stylesheet stylesheet.scss then I tried main.scss. Im inside the directory containing the stylesheet when I run learn-sass.

**Comment by rhymeswithfate** [comment]
Same error. Tried everything. The code matches the actual solution, so I don't get why it won't verify.

**Comment by robert23mg** [comment]
same error here, did anyone found a fix?

**Comment by riyadhalnur** [comment]
Try rebuilding `node-sass`. Do note that if you have upgraded Node versions, you will need to rebuild `node-sass` anyways. You can use `npm rebuild node-sass` to rebuild it.

**Comment by robert23mg** [comment]
I rebuilt node-sass i still get that error when verifying.
node v4.4.0
npm 3.8.2

I will try with the latest node version, which i had installed, but reverted to 4.4.0 because with the latest version the menus were not working.

**Comment by miljko1984** [comment]
Hello,

Same issue here, can anyone help? Stuck at 1 level....

**Comment by koddsson** [comment]
The error `ENOENT` indicates that the environment cannot find a file or directory and in the original issue you run `learn-sass verify variables.scss` but later in the text you call it `variable.scss`.

Have you made sure that you are typing in the filename correctly?

**Comment by miljko1984** [comment]
I got that error "ENOENT", i am sure that all is typed ok.

**Comment by miljko1984** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14349343/14077608/7d7c5c80-f4ed-11e5-978b-7e10916f3e1f.png)

**Comment by koddsson** [comment]
Ok I just wanted to make sure! This seems to be only affecting windows machines and I don't have one on hand so I can't really check this out until I get my hands on one.

I'll see if I can get a virtual machine going.

**Comment by miljko1984** [comment]
Thank you very much for your quick respond. Take care.

**Comment by lelo81** [comment]
Any update on this? I face same issue with Windows...

**Comment by JimmyBonez** [comment]
So I am getting the same error, and it seems to just be a common thing for Windows users. So here is my solution,(and due note that I have just started learning front-end development 4 months ago...) Ok, Step 1. Unplug your Windows computer. Step 2. Pick up your Windows computer Step 3. Throw it out the Window. Because it seems to be that almost every time I decide to learn something new on my Windows computer either I have to download a metric XXXX ton of things just to make it compatible to do it, or it just won't do it. So erase system 32, write Bill Gates tell him he is an xxxclown for designing a computer that needs countless updates, and comes with absolutely nothing to learn anything other than his one-sided things.....hmmmm is this that programmers rage thing I keep reading about?

**Comment by miljko1984** [comment]
This still doesn't works!

**Comment by joeparis** [comment]
ditto

Has this project been abandoned?

**Comment by cuteboi** [comment]
This is affecting a fresh install of nvm, with:

$ npm --version
4.0.5
$ node --version
v7.4.0

I fixed it for my system by changing the spawn to call to be the module "node-sass" vs having the absolute path being referenced.

**Comment by opperbolt** [comment]
same here on win10
also nodeschool links to https://github.com/claudiopro/learn-sass instead of https://github.com/workshopper/learn-sass/

**Comment by robert-gogolan** [comment]
For windows users, you can get bash on ubuntu on windows: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

Run the learn-sass from bash and it will work like a charm

**Comment by GregorBiswanger** [comment]
I found a workaround

Install global learn-sass and node-sass.

Go to the global path of learn-sass:
_C:\Users\Gregor\AppData\Roaming\npm\v10.14.1\node_modules\learn-sass_

and edit the line 115 in **execute.js**

`this.sassExec = path.resolve(__dirname, '../../node-sass.cmd');`

**Comment by mavidalma** [comment]
> I found a workaround
> 
> Install global learn-sass and node-sass.
> 
> Go to the global path of learn-sass:
> _C:\Users\Gregor\AppData\Roaming\npm\v10.14.1\node_modules\learn-sass_
> 
> and edit the line 115 in **execute.js**
> 
> `this.sassExec = path.resolve(__dirname, '../../node-sass.cmd');`

I´ve just tried it, but still same ENOENT :(
