### ISSUE TITLE
Grant Waffle.io to access nodeschool repositories

### ISSUE THREAD

**Issue by laurisvan** [nodeschool/discussions#1591]
We're using Waffle (waffle.io) for the kanban-like interface for juggling between our NodeSchool Helsinki issues. Waffle Kanban tickets are one-to-one with GitHub issues, e.g. it writes directly into nodeschool/helsinki issues. Hence Waffle needs access to NodeSchool organisation repositories in order to work.

AFAIK all the writes to the repositories are done with users' own credentials, so ordinary users cannot do any more harm with Waffle than they would do with the normal GitHub web ui.

For some magical reason, Waffle was working alright for our previous NodeSchool (long back in April) - we must have had different kind of team structure back then  Now that we're organising another NodeSchool in January, Waffle no longer works.

Would you think we can still use Waffle, or should our local chapter switch to something else like Trello?

**Comment by SomeoneWeird** [comment]
Everything is public, so it's fine. Approved it :)
