### ISSUE TITLE
if-statement.js problem JAVASCRIPT QUESTION

### ISSUE THREAD

**Issue by feteezuk** [nodeschool/discussions#1592]
## The challenge:  

  Create a file named if-statement.js.  

  In that file, declare a variable named fruit.  

  Make the fruit variable reference the value orange with the type of  
  String.  

  Then use console.log() to print "The fruit name has more than five  
  characters." if the length of the value of fruit is greater than five.  
  Otherwise, print "The fruit name has five characters or less."  

  Check to see if your program is correct by running this command:  

```
 javascripting verify if-statement.js  
```

MY SOLUNTION is wrong for some reason, and not sure why:

``` js
var fruit = 'orange';

if (fruit > 5) {
console.log("The fruit name has more than five  
  characters.");
} else{
    console.log("The fruit name has five characters or less.");
}
```

**Comment by SomeoneWeird** [comment]
Very very close - each string has a `.length` property that you need to use to get the length. Currently you're comparing the actual string `'orange'` to `5`, so that's always going to be false.

**Comment by feteezuk** [comment]
Got it, thank you.

**Comment by feteezuk** [comment]
So, i was able to finish the javascript module. What is the next tutorial i should try ?? I am a beginner

**Comment by SomeoneWeird** [comment]
probably `learnyounode` is the next step

**Comment by ola-show** [comment]
still dont get it

**Comment by feteezuk** [comment]
CORRECTED VERSION:

var fruit = 'orange'

if (fruit.length > 5) {
console.log("The fruit name has more than five  
  characters.");
} else{
    console.log("The fruit name has five characters or less.");
}

**Comment by feteezuk** [comment]
by adding fruit.length, it takes the variable string "orange" and uses it's ".length" property and compares it to being more than 5 letters.  If it is more than 5, the first message "The fruit name has more than five
characters." is displayed
