### ISSUE TITLE
Exercise #4 - MY FIRST ASYNC I/O

### ISSUE THREAD

**Issue by existenzial** [nodeschool/discussions#1593]
Possible error? Tutorial is returning a PASS for the right New Line(**'\n'**) count but FAIL for use of **fs.readFileSync**. I've tried rewriting the call to readFileSync without saving its result into a variable still no avail. Is this a bug or am I missing something? 

```javascript
var fs = require('fs');
var fileToRead = fs.readFileSync(process.argv[2], 'utf8', function(err, data){
	if(err){
		return console.error(err);
	}
	
}).split('\n');

var newLineCount = fileToRead.length - 1;
console.log(newLineCount);
```

**Comment by noffle** [comment]
Close! A couple of things:

1. This exercise calls for using asynchronous I/O. You'll want `fs.readFile` here, not `fs.readFileSync`. You already are using the correct arguments for `readFile`.

2. `fs.readFile` doesn't return the body of the file like `fs.readFileSync`. Check out [the docs](https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback). The file data will come in as the `data` argument in the callback you've written. You'll want to do your `split()` and line counting operations inside the callback.

**Comment by existenzial** [comment]
When the typos come back to haunt us. I thought I typed readFile, ha! Thanks!
