### ISSUE TITLE
Baby Steps! Excercise #2

### ISSUE THREAD

**Issue by camerondillard** [nodeschool/discussions#1596]
So I'm on exercise #2 of Learnyounode and I really don't understand what it's asking of me at all.  Are there supplemental materials I'm supposed to be using to familiarize myself with JS first?  It went from hello world to loops with close to 0 instruction on syntax.  It was my understanding that learnyounode didn't require previous JS experience.  Am I wrong?

**Comment by noffle** [comment]
You might have better luck with the `javascripting` workshopper: it goes through familiarization of JS much more than `learnyounode`:

> Learn the basics of JavaScript. No previous programming experience required.
> 
> `npm install -g javascripting`

**Comment by camerondillard** [comment]
Thank you very much.  I saw that package and that's what got me wondering once I hit the road block.  Will do.
