### ISSUE TITLE
BABY STEPS

### ISSUE THREAD

**Issue by HiOrange** [nodeschool/discussions#1597]
the codes I wrote can successfully pass the "learnyounode verify program.js 1 2 3 ". The codes as follows:
```js
var input = process.argv;
var total = 0;
for (var i = 2; i < input.length; i++) {
	total+=Number(input[i]);
};
console.log(total);
```
```
=====================
However, the results displayed on my terminal are:
                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "114"                               ==    "114"                              
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected  
   
  # PASS Your solution to BABY STEPS passed!  
```
1+2+3=6   I am confused!

**Comment by HiOrange** [comment]
Why the result of learnyounode verify program.js is 114 but not 6?

**Comment by HiOrange** [comment]
problem solved,
I missed some instruction in hint section:
"learnyounode will be supplying arguments to your program when you run  
  learnyounode verify program.js so you don't need to supply them yourself.  
  To test your program without verifying it, you can invoke it with  
  learnyounode run program.js. When you use run, you are invoking the test  
  environment that learnyounode sets up for each exercise.  "

This reminds me hint really help :-)

**Comment by GiannisGl** [comment]
close #1597

**Comment by finnp** [comment]
Yes that part is often missed :smiley:
