### ISSUE TITLE
JUGGLING ASYNC (Exercise 9 of 13)  

### ISSUE THREAD

**Issue by luisfmelo** [nodeschool/discussions#1598]
I wonder if you could help realize this thing: asynchronism.

```
var http = require('http');
var message = [];

for (var i = 2; i < 5; i++)
    http.get(process.argv[i], function (res) {
          res.setEncoding('utf8');

          res.on('data', function(line) {
                message[i] += line.toString();
          });
         res.on('end', function(line) {
                for (var i = 0; i < 3; i++)
                      console.log(message[i]);
         });
});
```

**Comment by finnp** [comment]
In your code the `i` variable within the callback functions will always be the last `i` value from the loop. Here
```js
res.on('data', function(line) {
                message[i] += line.toString();
          });
```
`message[i]` will be `message[4]` ever time. The reason for this is that the for loop will run through first and then when the data events are coming in the `i` value will be `4` every time. 

Over here's a hint on how to fix that: https://github.com/nodeschool/discussions/issues/1520

**Comment by carmof** [comment]
I tryed something different, I used the code from exercise 8 of 13 and I only had to put a counter and an array to control the flow. Array positions controls the right sequence to output the data and the counter controls the amount of returns I've received so far.

To add another variable to the 'callback' I used a function that returns the callback function.

`const http = require('http'),
	  bl = require('bl');

var queue = [];
var count = 0;
http.get(process.argv[2],aux(0));
http.get(process.argv[3],aux(1));
http.get(process.argv[4],aux(2));


function aux (i){
	return function callback(response){
				response.pipe(bl(function (err, data) { 
			 		queue[i] = data.toString();
			 		count++;
			 		if(count == 3){
			 			 queue.forEach(function(pos){
			 			 	console.log(pos);
			 			 });
			 		}
				}));
			};
};`

**Comment by deni86** [comment]
great solution...thank you

**Comment by mohouyizme** [comment]
This is my solution:

```js
const http = require('http');
const bl = require('bl');
const async = require('async');

const argv = process.argv.slice(2);

const result = [];

async.eachOf(argv, (arg, key, callback) => {
  http.get(arg, (response) => {
    response.pipe(bl((err, data) => {
      if (err) return callback(err);
      data = data.toString();
      result[Number(key)] = data;
      callback();
    }));
  });
}, (err) => {
  if (err) return console.log(err);
  if (result.length === argv.length) {
    result.forEach(item => console.log(item));
  }
});
```
