### ISSUE TITLE
learnyounode : Make it Modular

### ISSUE THREAD

**Issue by nickborti** [nodeschool/discussions#1601]
In this question I wrote this code:

program.js

``` js
var module = require('./module');

module(process.argv[2], process.argv[3], function(data){
    console.log(data);
});
```

module.js

``` js
var fs = require('fs');

module.exports = function(dir, ext, callback){
    fs.readdir(dir, function(err, data){
        if (err){
            return callback(err);
        }else{
            for(var i = 0; i < data.length; i++){
                var lastIndex = data[i].lastIndexOf('.');
                if(data[i].substr(lastIndex + 1) == process.argv[3]){
                    callback(null, data[i]);
                }
            }
        }
    });
};
```

It's saying "Your additional module file [module.js] did not call the callback  
  argument"

I don't get it really.

**Comment by noffle** [comment]
You're close! A couple of guiding questions:

1. What happens when `lastIndexOf` returns `-1`? (couldn't find the character in the string)
2. The callback function format is `callback(err, data)` -- are you using that consistently throughout `module.js` and `program.js`?
