### ISSUE TITLE
Hello World learnyounode Exercise giving me error?

### ISSUE THREAD

**Issue by Mashadim** [nodeschool/discussions#1602]
It's my first time running node and would appreciate some advice:

I got node installed and have started my first learnyounode exercise, Hello World, but I'm getting an error when I type in node program.js in my command line window. Why? I can't move on without getting this working first right? I am using Windows.

module.js:340
   throw err;
   ^

Here is a better view: http://postimg.org/image/68udarcn7/

**Comment by noffle** [comment]
Have you created a file named `program.js` in `C:\Users\Plenty`?

**Comment by Mashadim** [comment]
I thought I could just create it through the command line. Which I did, did you click the image link?

**Comment by SomeoneWeird** [comment]
```
The instructions say that I first need to create a new file by typing
```

The instructions say:

```
Execute your program by running it with the node
  command. e.g.:

     $ node program.js
```

You still need to create `program.js` with another text editor or IDE, before you can run it with `node` :)

**Comment by Mashadim** [comment]
Oooooomg ok. I misinterpreted what they meant. Thank you for clarifying!! :+1:

**Comment by SomeoneWeird** [comment]
No problem, open another issue if you need more help! :D
