### ISSUE TITLE
npm install bl doesn't work (HTTP COLLECT)

### ISSUE THREAD

**Issue by Doumao1999** [nodeschool/discussions#1603]
When I worked on  "HTTP COLLECT", using npm install bl, but came out " code E404,  missing : bl, 'bl' is not in the npm registry.",  Can someone help? Thank you

**Comment by noffle** [comment]
Is this still happening? [bl](https://www.npmjs.com/package/bl) is definitely in the npm registry.

What version of npm are you running? (use `npm version`)

**Comment by Doumao1999** [comment]
Thank you.
Yes it still happening.  npm version 3.5.2. 

But when I opened a new workspace, and tried to install bl, it works. When I list dependencies, it shows 'npm ERR! extraneous: bl@1.0.0 /home/ubuntu/workspace/node_modules/bl'. I can work on  HTTP COLLECT now.
Thank you.
Maria
