### ISSUE TITLE
help saving canvas image to disk in nodejs app

### ISSUE THREAD

**Issue by michalakis** [nodeschool/discussions#1605]
hello, I am a novice and im completely stuck, I created a web app and then packaged it with nw.js so I can run it on the desktop. I am doing this for a university coursework. I have a canvas which i manipulate and then I want to save the image on the canvas to the disk but not sure how to go about it, other instructions out there seem a bit too advanced

**Comment by finnp** [comment]
This is probably not really the right place to get help for this. Maybe have a look at the https://github.com/nwjs/nw.js project page and ask that question somewhere there. Generally to save files to disk you can use the [fs](https://nodejs.org/api/fs.html) module in node and to convert a get the canvas object as an image you can use [toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).
