### ISSUE TITLE
learnyounode object HAS NO METHOD error.

### ISSUE THREAD

**Issue by anandrew1995ifds** [nodeschool/discussions#1607]
Working on the 10th learnyounode module. 

```javascript
var net = require('net');
var server = net.createServer(function (socket){
	var date = new Date();
	var year = date.getFullYear();
	var month = date.getMonth();
	var date = date.getDate();
	var hour = date.getHours();
	var min = date.getMinutes();
	var data = year + "-" + month + "-" + date + " " + hour + ":" + min;
	socket.end(data);
});
server.listen(process.argv[2]);
```

and I am getting an error that says:

/home/learnyounode/program.js:105
	var hour = date.getHours();
	                ^
TypeError: Object 11 has no method 'getHours'
    at Server.<anonymous> (/home/learnyounode/program.js:105:18)
    at Server.EventEmitter.emit (events.js:95:17)
    at TCP.onconnection (net.js:1191:8)

I've only found a solution that said use new Date() instead of just Date() to create, but I was using new the whole time. Thanks in advance.

**Comment by mappum** [comment]
In the line `var date = date.getDate();`, you are replacing the `date` object with a number (today's date). This is why the error refers to `Object 11` (today is the 11th).

**Comment by dmcaodha** [comment]
Hi there, I think the problem is that you are declaring the variable `date` twice.
````
var date = new Date();
````
and
````
var date = date.getDate();
````
I haven't looked at the task, but you may not even need the second date statement at all. In fact you might be looking for:
````
var day = date.getDay();
````

**Comment by anandrew1995ifds** [comment]
DIdn't realize I was using the same var name and replaced it. Thank you for the replies!
