### ISSUE TITLE
[Juggling Async] Any improvement over this suggested over this

### ISSUE THREAD

**Issue by Akira-Avin** [nodeschool/discussions#1609]
I have finished the juggling async task without errors. I want to check whether the below solution is feasible or it can be improved further . 

It is similar to the accepted answers in most ways . Can anyone help ?
# Code : 

```
//HTTP Client - Juggling Async Exercise 9 of 13 
var http = require('http');
//Importing the http module 
var result = [];  //To keep data from server 
var urls = [];  //Push the urls into an array 
var callbackCount = 0;  //Keep track of callbackCount

var aCallBack = function(response) {
    callbackCount++;
    var finalData = "";
    response.on("data", function(data) {
        finalData = finalData + data;
    });
    response.on("error", function(data) {
        return console.error(data);
    });
    response.on('end', function(data) {
        result.push(finalData);
        http.get(urls[callbackCount], aCallBack);
        if (callbackCount === 3) {
            result.forEach(function(value) {
                console.log(value);
            });
        }
    });
};


for (var i = 2; len = process.argv.length, i < len; i++) {
    urls.push(process.argv[i]);
}

http.get(urls[0], aCallBack);

```
#

**Comment by finnp** [comment]
Hey!

Right now what this code is doing is fetching the first URL, then waiting for it to be downloaded and then starting the download the next one.

What you actually do want here, is that all of these URLs are fetched at the same time. You would not need that many changes to make that happen. See if you can figure it out :relaxed:

**Comment by Akira-Avin** [comment]
Dear @finnp : I have tried the following changes .

```
//HTTP Client - Juggling Async Exercise 9 of 13 
var http = require('http');
//Importing the http module 
var result = []; //To keep data from server 
var urls = []; //Push the urls into an array 
var callbackCount = 0; //Keep track of callbackCount

var aCallBack = function(response) {
    callbackCount++;
    var finalData = "";
    response.on("data", function(data) {
        finalData = finalData + data;
    });
    response.on("error", function(data) {
        return console.error(data);
    });
    response.on('end', function(data) {
        result.push(finalData);
        //http.get(urls[callbackCount], aCallBack);
        if (callbackCount === 3) {
            result.forEach(function(value) {console.log(value);});
            //console.log(result);
        }
    });
};


for (var i = 2; len = process.argv.length, i < len; i++) {
    urls.push(process.argv[i]);
    http.get(urls[i-2], aCallBack);
}

```

Output : 
Your submission results compared to the expected:

───────────────────────────────────────────────────────────────

1.  ACTUAL:    "Built like a slabs bloody stands out like a cranky. As busy as a going off when as dry as a struth. As stands out like wuss flamin he hasn't got a offsider. It'll be icy pole when we're going icy pole. Get a dog up ya stickybeak no worries flat out like a sanger. "
1.  EXPECTED:  "We're going boardies to as stands out like sickie. As cunning as a lizard drinking to as stands out like veg out. She'll be right two pot screamer where as cunning as a prezzy. Lets get some cream no dramas gutful of joey. We're going slabs with grab us a sickie. "

2.  ACTUAL:    "Shazza got us some whinge when as busy as a ridgy-didge. We're going chunder no worries we're going rollie. He hasn't got a ridgy-didge flamin as cross as a gobsmacked. "
2.  EXPECTED:  "Built like a slabs bloody stands out like a cranky. As busy as a going off when as dry as a struth. As stands out like wuss flamin he hasn't got a offsider. It'll be icy pole when we're going icy pole. Get a dog up ya stickybeak no worries flat out like a sanger. "

3.  ACTUAL:    "We're going boardies to as stands out like sickie. As cunning as a lizard drinking to as stands out like veg out. She'll be right two pot screamer where as cunning as a prezzy. Lets get some cream no dramas gutful of joey. We're going slabs with grab us a sickie. "
3.  EXPECTED:  "Shazza got us some whinge when as busy as a ridgy-didge. We're going chunder no worries we're going rollie. He hasn't got a ridgy-didge flamin as cross as a gobsmacked. "

4.  ACTUAL:    ""
4.  EXPECTED:  ""


───────────────────────────────────────────────────────────────

Some of the URLs are getting the data much before the URL called earlier .. The output is as above. Please guide me

**Comment by agauniyal** [comment]
@Akira-Avin the task is to get url contents as soon as possible, whether they are fetched in correct order or not, **but** display them in correct order.

**Comment by artivilla99** [comment]
@Akira-Avin when you make the http request, the callbacks get executed in any order, what you would want to do is pass in the index value as well and in the callback store the data in result[index] so the order is preserved. Also, the for loop is synchronous, so you want to wrap the get request in a function to pass the the i value.

In this case you're passing the index into your getAsync function that does the actual http.get and you can store the result in results[i]. You also don't have to pass in i, just start at 0 until length of urls.

```
const urls = process.argv.slice(2)

for (let i = 0; i < urls.length ; i++) {
  getAsync(urls[i], i)
}
```

Hope this helps. Give it another try.
