### ISSUE TITLE
learnyounode6: Make it modular

### ISSUE THREAD

**Issue by setagana** [nodeschool/discussions#1612]
Hi all,

If I'm honest, I don't really get this lesson :( I read through some of the other questions and tried to get my code to run with their help, but I have no idea where to go next. I have:

**mymodule.js:**

```javascript
var module = require('module');
var fs = require('fs');
var path = require('path');

module.exports = function(testDirectory, testExtension, callback)
{
	fs.readdir(testDirectory, function(error, folderContents)
		{
			if (error) return callback(error);
			for (i = 0; i < folderContents.length; i++)
			{
				var fileExtension = path.extname(folderContents[i]);
				if(fileExtension === "." + testExtension)
				{
					callback(null, folderContents[i]);
				}
			}
		});
};
```

**program.js:**

```javascript
var mymodule = require('./mymodule.js');

mymodule(process.argv[2], process.argv[3], function(error, data)
{
	console.log(data);
});
```

But when I try and test it I get *TypeError: mymodule is not a function*.

Can anyone help me along?

**Comment by titoesteves** [comment]
In mymodule.js you have `var module = require('module');`. This should not be in that file. Module is a global object provided in node so there is no need to 'require' it. I suspect this is why you are seeing this error.

**Comment by setagana** [comment]
Ahh, that's fixed it. Thank you Tito!

**Comment by titoesteves** [comment]
Awesome. Glad to hear
