### ISSUE TITLE
In which order should we tackle the modules?

### ISSUE THREAD

**Issue by irishetcher** [nodeschool/discussions#1613]
I have just started the modules and am wandering in which order should they be taken.

Starting with the javascript, should we move down the left column with git-it or, move over to learnyounode and then back down to git-it? 

Perhaps some numbering on the modules would help?

**Comment by finnp** [comment]
Probably doing `learnyounode` next is a good idea. But apart from that they are mostly independent from each other, so you are free to do what you want next.

**Comment by irishetcher** [comment]
Cheers.

**Comment by finnp** [comment]
:+1:
