### ISSUE TITLE
What is this syntax: (err) => {...} ?

### ISSUE THREAD

**Issue by pentool** [nodeschool/discussions#1614]
Hi, I was just reading the new node.js 5.4.1 documentation and saw the syntax that resembles a mix of PHP array and JS object-like style. I don't find any documentation anywhere on this (probably because I'm not even sure how exactly to specify what I'm searching for). See this example where they declare the 'createserver' method: https://nodejs.org/dist/latest-v5.x/docs/api/synopsis.html

    http.createServer((request, response) => {
    ...
    })

Is this some sort of new way of declaring a callback/function? Regardless what sample code I'm looking at on the net, I don't see this kind of syntax except on the Node.js docs pages.

Thanks.

**Comment by dominhhai** [comment]
This is ES6' syntax. Please see the detail [here](https://nodejs.org/en/docs/es6/)

**Comment by pentool** [comment]
Thank you!
