### ISSUE TITLE
open lesson plans after install

### ISSUE THREAD

**Issue by annaruth3030** [nodeschool/discussions#1616]
I want to do the javascripting module. I installed it, and did the intro, but a friend was helping me yesterday and I forget how to pull up the curriculum. whats the command to list all of the lessons?

**Comment by SomeoneWeird** [comment]
If you just run `javascripting` you should get a list.

**Comment by annaruth3030** [comment]
great, thanks !

**Comment by finnp** [comment]
:+1:
