### ISSUE TITLE
String Length 

### ISSUE THREAD

**Issue by Rauljfa** [nodeschool/discussions#1617]
I've been trying to get the string length exercise done, but I can't get it right. I've tried many different ways and have no idea what I'm doing wrong. Any help?

**Comment by luketlancaster** [comment]
Any examples of what you've tried doing? That way you can get pointed in the right direction.

**Comment by Rauljfa** [comment]
I managed to solve it now. It was a really dumb mistake I made. I had forgotten to save on my text editor. As soon as I hit save and ran the code again it worked.

**Comment by luketlancaster** [comment]
Gotcha. Been there, done that. Glad to hear you figured it out.

**Comment by SomeoneWeird** [comment]
:tada:
