### ISSUE TITLE
NPM Won't Start

### ISSUE THREAD

**Issue by ajseavers** [nodeschool/discussions#1618]
When I type npm start, this is what I get. I'm new to programming, but really need to figure this out by tomorrow.  Any help would be appreciated.  I'm hoping it's an easy fix.

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/Users/andyseavers/.node/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! path /Users/andyseavers/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/andyseavers/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/andyseavers/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andyseavers/npm-debug.log

From the nmp-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose config Skipping project config: /Users/andyseavers/.npmrc. (matches userconfig)
5 verbose readDependencies loading dependencies from /Users/andyseavers/package.json
6 error install Couldn't read dependencies
7 verbose stack Error: ENOENT: no such file or directory, open '/Users/andyseavers/package.json'
7 verbose stack     at Error (native)
8 verbose cwd /Users/andyseavers/Dropbox/Coding/Ramsey Project
9 error Darwin 15.2.0
10 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
11 error node v4.2.4
12 error npm  v2.14.12
13 error path /Users/andyseavers/package.json
14 error code ENOPACKAGEJSON
15 error errno -2
16 error syscall open
17 error package.json ENOENT: no such file or directory, open '/Users/andyseavers/package.json'
17 error package.json This is most likely not a problem with npm itself.
17 error package.json npm can't find a package.json file in your current directory.
18 verbose exit [ -2, true ]

**Comment by Kablex** [comment]
Did you try with sudo?

May this help u: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ajseavers** [comment]
Yes I did.  No luck.

**Comment by luketlancaster** [comment]
NPM is looking for a `package.json` file. Are you running the command in the correct directory? I get the same thing if I run `npm start` in my user directory (i.e. `~/User/Lancaster`) but it's fine once I cd into the project I'm working on.
