### ISSUE TITLE
learnyounode 6: Make It Modular

### ISSUE THREAD

**Issue by Elephly** [nodeschool/discussions#1619]
So, I'm not so sure this is a mistake in my code, but I'll past in my code anyway.

So I've got make-it-modular.js here...
```javascript
var myModule = require('./make-it-modular-module');

var pathName = process.argv[2];
var fileType = process.argv[3];

myModule(pathName, fileType, function(err, data) {
  if (err) {
    return err;
  }
  console.log(data);
});
```

Next, I have make-it-modular-module.js here...
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function(dirName, fileExt, callback) {
  fs.readdir(dirName, function(err, data) {
    if (err) {
      return callback(err, data);
    }

    for (var i = 0; i < data.length; i++) {
      if (path.extname(data[i]) === "." + fileExt) {
        callback(null, data[i]);
      }
    }
  });
};
```

And finally, here is the output of executing learnyounode verify make-it-modular.js
```
>learnyounode verify make-it-modular.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

C:\...\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:182
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (C:\...\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:182:18)
    at C:\...\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:189:7
    at callback (C:\...\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:26:15)
    at modFileError (C:\...\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:31:5)
    at C:\...\AppData\Roaming\npm\node_modules\learnyounode\exercises\make_it_modular\verify.js:119:18
    at C:\...\make-it-modular-module.js:11:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Apparently, my output looks correct, but something else is breaking, even though it traces back to the line where I call callback inside the module function.

**Comment by GiannisGl** [comment]
see #1606

**Comment by Elephly** [comment]
Thanks very much!

**Comment by nbappi** [comment]
output file :  output.js

var modules = require("./modules/files");
var dirname = process.argv[2] ;
var extname = process.argv[3] ;

modules( dirname ,extname , function (err , datas)
{
   datas.forEach(function(data){
       console.log(data);
   });
});

module file :  modules/files.js

var fs = require("fs"), path = require("path");
module.exports = function(dirname, extname, callback)
{
     fs.readdir(dirname , function( err , files)
    {
        if(err) return callback(err);

        files = files.filter(function (file){
              return path.extname(file) == '.'+extname;
        });
         callback(null, files);
     });    
}

**Comment by nbappi** [comment]
output file : output.js

var modules = require("./modules/files");
var dirname = process.argv[2] ;
var extname = process.argv[3] ;

modules( dirname ,extname , function (err , datas)
{
     datas.forEach(function(data){
           console.log(data);
      });
});

module file : modules/files.js

var fs = require("fs"), path = require("path");
module.exports = function(dirname, extname, callback)
{
fs.readdir(dirname , function( err , files)
{
    if(err) return callback(err);

    files = files.filter(function (file){
          return path.extname(file) == '.'+extname;
    });
     callback(null, files);
 });    
}
