### ISSUE TITLE
learnyounode make it modular bug

### ISSUE THREAD

**Issue by desdulianto** [nodeschool/discussions#1620]
i run verify to verify my answer for make it modular exercise of learnyounode module. the result is correct but i got runtime error like the picture i attached. is this a bug?
![learnyounode](https://cloud.githubusercontent.com/assets/3291789/12576114/06af53ca-c444-11e5-9abd-099070b0cd23.png)

**Comment by GiannisGl** [comment]
see #1606

**Comment by desdulianto** [comment]
work perfectly, thanks!
