### ISSUE TITLE
why -g global

### ISSUE THREAD

**Issue by cataquil** [nodeschool/discussions#1622]
can I install these packages locally so I don't put them into the global repo?

**Comment by dominhhai** [comment]
It is OK!
However, if you install these packages globally, you can open them easily.
In case of local, you have to mount to folder which contain your packages in order to run your workshops.

**Comment by noffle** [comment]
Yep, you can install and run locally:

```
cd /tmp
npm install planetproto
node /tmp/node_modules/planetproto/planetproto.js
```

**Comment by josersleal** [comment]
nope...
