### ISSUE TITLE
Branches Aren't For Birds issue

### ISSUE THREAD

**Issue by CodeMorrow** [nodeschool/discussions#1623]
`jmorrow3906:~/workspace/patchwork (add-CodeMorrow) $ git push origin add-CodeMorrow
Username for 'https://github.com': CodeMorrow
Password for 'https://CodeMorrow@github.com': 
remote: Permission to jlord/patchwork.git denied to CodeMorrow.
fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403`

`Verifying "BRANCHES AREN'T JUST FOR BIRDS"...

ACTUAL                             EXPECTED

---

"Found branch as expected!"        "Found branch as expected!"  
"{ [Error: Command failed: /bin/sh -c git reflog show origin/add-CodeMorrow" != "Changes have been pushed!"  
"fatal: ambiguous argument 'origin/add-CodeMorrow': unknown revision or path not in the working tree." != "File in contributors folder!" 
"Use '--' to separate paths from revisions, like this:" != ""  
"'git <command> [<revision>...] -- [<file>...]'" != null  
"]"                             != null  
"  killed: false,"              != null  
"  code: 128,"                  != null  
"  signal: null,"               != null  
"  cmd: '/bin/sh -c git reflog show origin/add-CodeMorrow' }" != null  
""                              != null                           
# FAIL

Your solution to BRANCHES AREN'T JUST FOR BIRDS didn't match the expected output.
Try again!
-----------------------------------------------------------------`

**Comment by noffle** [comment]
A dump of your console output with no explanation makes it difficult to help: you're asking others to exert more effort into solving your problem than you put into asking it.

Here are some questions to help you clarify your thinking process:

1. What are you trying to accomplish?
2. Walk us through your steps -- what do you think each of your commands are doing?
3. Do you understand the error messages? What do you think they're communicating?

**Comment by Baltimorejones** [comment]
I received the exact same error

**Comment by oky1** [comment]
Same problem.

**Comment by artitudinale1** [comment]
same error
