### ISSUE TITLE
My first ASYNC I/O issue

### ISSUE THREAD

**Issue by esthercuan** [nodeschool/discussions#1624]
Hello Node School, 
I am having trouble getting anything out of the fs.readFile() function. 

```
var fs = require('fs'); //node module included 
var string = fs.readFile(process.argv[2],'utf8',function(err, data){
	if (err) throw err;
	return data
});  
console.log(string) // => undefined :(
```

The Docs say _"If no encoding is specified, then the raw buffer is returned."_ But Im not getting it returned, even if I ask to return the data. 

Thank you for your help !

**Comment by noffle** [comment]
Unlike `fs.readFileSync`, `fs.readFile` does not return the file's contents synchronously ([see docs](https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback)). Instead, the file's data is provided within the callback function you provide as the 3rd method parameter (here it's `data`).

**Comment by esthercuan** [comment]
Thank you so much for your reply! Im trying to do this: 
`console.log(string.split('\n').length - 1);` 
with my `string` var. So Apparently I might only use the callback to check for errors.

**Comment by noffle** [comment]
Well done! :star2:
