### ISSUE TITLE
can't install any workshops past javascripting

### ISSUE THREAD

**Issue by Jarevalo92** [nodeschool/discussions#1625]
hey all, having a hell of a time trying to install workshops other than the javascripting lessons.

So I am on a dinosaur of a machine, a 2009 macbook with os x 10.7.5

I've attempted sudo installs, following this websites instructions https://docs.npmjs.com/getting-started/fixing-npm-permissions, and I'm just completely stuck.

![screen shot 2016-02-02 at 7 40 53 pm](https://cloud.githubusercontent.com/assets/15959096/12769362/44b9a55c-c9e5-11e5-9eac-8bdc6ce9f410.png)

please send help!

Thank you so much.

**Comment by noffle** [comment]
It looks like you have some existing files in `~/.npm-global` that have superuser permissions -- probably from running as superuser before. What do the logs look like when you run with `sudo`?

**Comment by Jarevalo92** [comment]
@noffle 

Johns-MacBook:~ jnikga$ sudo install -g learnyounode
Password:
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...


Johns-MacBook:~ jnikga$ learnyounode
-bash: learnyounode: command not found
Johns-MacBook:~ jnikga$

**Comment by noffle** [comment]
`sudo` is a prefix command that runs the command **after** it with superuser privileges. So you'd execute

```
sudo npm install -g learnyounode
```

**Comment by Jarevalo92** [comment]
![screen shot 2016-02-03 at 2 19 00 pm](https://cloud.githubusercontent.com/assets/15959096/12794041/3a3113a8-ca81-11e5-8c41-6149e908f389.png)

@noffle

**Comment by noffle** [comment]
You're getting closer. :)

`sudo npm install -g learnyounode` is a **shell** command. What you run inside of `node` is Javascript code. You'll want to execute the command in the shell, not in `node`.

**Comment by Jarevalo92** [comment]
![screen shot 2016-02-03 at 7 06 54 pm](https://cloud.githubusercontent.com/assets/15959096/12801285/7c7bf868-caa9-11e5-9140-2a3b688388cb.png)

okay so I ran sudo npm install -g learnyounode as a command, opened it as a shell and got the above. 

![screen shot 2016-02-03 at 7 11 20 pm](https://cloud.githubusercontent.com/assets/15959096/12801334/efb7cb72-caa9-11e5-8f2c-d6aa874f690c.png)

This is what I get when I try to run learnyounode outside of node

![screen shot 2016-02-03 at 7 12 10 pm](https://cloud.githubusercontent.com/assets/15959096/12801349/15c6c444-caaa-11e5-8516-73b90040006d.png)

and this is what I get when I try to run it in node. 

Thank you so much for your help and being patient with me!

**Comment by noffle** [comment]
You're really close!

Since you've changed your global install location to `/Users/jnikga/.npm-global`, you'll need to update an environment variable called `PATH`. This decides where to look for executable programs on your computer. Try it out by opening a terminal and typing

```
echo $PATH
```

You'll need to add the `.npm-global` directory to your path as well for you to be able to run npm-installed programs.

In the [article that you linked to](https://docs.npmjs.com/getting-started/fixing-npm-permissions), this corresponds to steps 3 and 4.

**Comment by Jarevalo92** [comment]
@noffle 

I hate that I'm having you hold my hand here, but I'm not sure how to add .npm-global to the result of echo $PATH.

**Comment by noffle** [comment]
You just need to do steps 3 and 4 from that article. :)
