### ISSUE TITLE
how-to-npm

### ISSUE THREAD

**Issue by bryont** [nodeschool/discussions#1626]
How can I get the second module for how-to-npm open?  01 Dev Enviroment?

I have tried:
how-to-npm select LEVEL 02  
how-to-npm select 02 etc.....
and many other variations.

Thanks,

**Comment by tgfjt** [comment]
- `how-to-npm list`: Show a menu to interactively select a workshop.
- `how-to-npm select NAME`: Show a newline-separated list of all the workshops.

and you can get help message: `how-to-npm help` :)

**Comment by derekharmon** [comment]
how-to-npm select "01 dev environment"
