### ISSUE TITLE
functional-javascript Async Loops

### ISSUE THREAD

**Issue by midN** [nodeschool/discussions#1629]
Hello,

Async loops task PASSes with initial Boilerplate.
Isn't there supposed to be some additional checks if you have used additional Done function etc?

`function loadUsers(userIds, load, done) {
  var users = [];
  for (var i = 0; i < userIds.length; i++) {
    users.push(load(userIds[i]));
  }
  return users;
}

module.exports = loadUsers;
`

Running `functional-javascript verify program.js` marks this task as PASSed.

**Comment by koddsson** [comment]
Hey @midN!

Yeah there should be! There's even a [open issue](https://github.com/timoxley/functional-javascript-workshop/issues/119) on the `functional-javascript-workshop` github page for it.

Hopefully someone will fix it soon but I recommend going through the exercise as intended to get the full educational benefit :mortar_board:!
