### ISSUE TITLE
HTTP CLIENT exercise

### ISSUE THREAD

**Issue by FilipMessa** [nodeschool/discussions#1630]
Hi all i have question, where is right place for handle error on response?

http.get(url, function(res) {
  res.setEncoding('utf8');
  res.on('data',function(data){
      console.log(data);
  });
  res.on('error',console.error); //Here?
}).on('error',console.error); // or here?

**Comment by noffle** [comment]
Check out the Node docs: https://nodejs.org/api/http.html#http_http_get_options_callback

**Comment by FilipMessa** [comment]
ok so i think in official solution is mistake. 
var http = require('http');

http.get(process.argv[2], function (response){
  response.setEncoding('utf8')
  response.on('data',console.log)
  response.on('error',console.error)
})

I think right solution is
var http = require('http');

http.get(process.argv[2], function (response){
  response.setEncoding('utf8')
  response.on('data',console.log)
}) .on('error',console.error)
