### ISSUE TITLE
get data from two databases to a string to be used outside of the function

### ISSUE THREAD

**Issue by izmeil** [nodeschool/discussions#1631]
i am trying to get data from two DBs to compare them 

so far here is what i have wrote 

````
var label = "";
var sql1 = "select * from to_do1 WHERE   name like 'XXX'";

((function () {
//first database
  db1.query(sql1).then(function (data1) {
          _.each(data1, function (one) {

        //get name from database 1  and add to string label
 label = label + one.name + "  \n ";

//second database
              var sql2 = "select * from to_do2 where id like '" + one.id + "'";
              db2.query(sql2).then(function (data2) {
                  _.each(data2, function (two) {
//get name from second database and add to the string label
                      label = label + "\t " + two.name + " \n ";
                  })
              })
          })
      })
      .catch(function (error) {
       
      })
  })());

//here i want to use the string (label) all added up to the string 
//something like 
console.log(label); //but this is not giving me any output 
````

need some help with some explanation so thank i will  know what i am doing

**Comment by ismnoiet** [comment]
Hi @izmeil  welcome to nodeschool, this kind of question is better to be asked at [stackoverflow](https://www.stackoverflow.com), go there and ask your question and you will probably find questions similar to yours, if you don't find then write a question and the community there will more than happy to answer your question or possibly me i'll be answering your question.
Hope you find a solution and thanks for visiting nodeschool page :).
