### ISSUE TITLE
If/Else Statement

### ISSUE THREAD

**Issue by Lindz27** [nodeschool/discussions#1633]
Hello,

I am going through Javascripting in Node School and I keep receiving an illegal token error when I am running this if/else statement. Is there anything wrong with how this is set up in sublime or is the error coming from the terminal?

var fruit = 'orange';
if (fruit.length > 5){
console.log('The fruit name has more than five  
  characters.');
} else {
    console.log('The fruit name has five characters or less.');
}

**Comment by noffle** [comment]
Single quoted strings cannot span multiple lines. You'll need to bring `characters.');` up to the same line as the rest of the first `console.log` statement.

**Comment by riyadhalnur** [comment]
```js
var fruit = 'orange';
if (fruit.length > 5) {
    console.log('The fruit name has more than five characters.');
} else {
    console.log('The fruit name has five characters or less.');
}
```

**Comment by mgwmp** [comment]
nice work guys!
