### ISSUE TITLE
process.argv behaving differently in count to 6

### ISSUE THREAD

**Issue by Ranjeetkaur** [nodeschool/discussions#1634]
In count to 6 exercises, there is need to access command line values. When accessing the command line value using process.argv[2] with the help of command:
 count-to-6 run program.js 'David'
I'm getting this as progress.argv
[ '/Users/myaccount/.nvm/v0.10.36/bin/node',
  '/var/folders/1x/wln51jy95wz_6cvsvj6swxw80000gp/T/_count-to-6_13183/0.9015634851530194.js',
  'CampJS' ]
where 'CampJS' randomly changes to anything else every-time.

If I use this command instead:
 node program.js 'David' 
I get the correct value as expected
[ 'node',
  '/Users/myaccount/Practice/nodeschool/counttosix/template-strings.js',
  'David' ]
(but this doesn't recognize es6 syntax..)

What could be the problem with fetching progress.argv correctly?

**Comment by koddsson** [comment]
Hey @Ranjeetkaur!

When you run the code using the workshop, in this case the `count-to-6` workshop. It will help you out by supplying a argument to the program so you can easily verify that it is working the way it's intended. 

When running using node, it however works normally and will take in the arguments like you'd expect.

Does that answer your question?

**Comment by Ranjeetkaur** [comment]
Thanks, got it working, there was problem on my part with missing $.
