### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by nitin466** [nodeschool/discussions#1636]
Hello !

I'm following the scope-chains-closures lessons (on http://nodeschool.io/) and I'm stucked at excercice 4 on closures.

Appreciate if someone help me out here. 

Here is the challenge:
Modify your solution from the previous lesson to set bar = true inside zip(),
then return the function zip as the result of foo()

This is how my solution looks like:

function foo () {
  quux = 10;
    var bar;
    var zip = function () {
        quux = 20;
        bar = true;
    }
    return zip;
};

Thanks.

**Comment by noffle** [comment]
Remember: Lesson #2 asked you to define `quux` as *lexically scoped within `zip`*.
