### ISSUE TITLE
Argument index issue

### ISSUE THREAD

**Issue by Sandybhai** [nodeschool/discussions#1640]
HTTp Client Problem --

Write a program that performs an HTTP GET request to a URL provided to you  
  as the **first command-line argument**. Write the String contents of each  
  "data" event from the response to a new line on the console (stdout).  

**Guys! I am really confused about the argument index to be used. When they say first argument is the url, shouldn't it be process.argv[0] ? how come it's process.argv[2] in this case?**

**Comment by maxrimue** [comment]
@Sandybhai `process.argv` doesn't hold arguments you passed to your app, but instead all arguments you passed to your shell. So if you write:
```
node index.js someOption
```
, that means that:
`process.argv[0]` = `node`,
`process.argv[1]` = `index.js`,
`process.argv[2]` = `someOption`
