### ISSUE TITLE
Nodeschool module menus are still not working with node version 5.6.0

### ISSUE THREAD

**Issue by anvis2000** [nodeschool/discussions#1641]
I see from previous threads that there was a problem with workshopper menus being non-functional in node version 4.0.0 and that the issue had been fixed in version 5.1.0.  I am currently running node version 5.6.0 and I still have the issue with non-functional menus.

**Comment by martinheidegger** [comment]
@anvis2000 Thank you for reporting it! It would be very helpful to know your system specification (windows? mac?) and the menu that you try to run. (`learnyounode` - I assume, which version?)

**Comment by anvis2000** [comment]
Actually its the git-it module.  I am running Windows 10.  Thank you.

**Comment by martinheidegger** [comment]
@anvis2000 Does learnyounode work?

**Comment by anvis2000** [comment]
learnyounode has the same issue with non-functional menus as well.  To be more accurate it seems it works sometimes but most of the time it does not.

**Comment by martinheidegger** [comment]
What is the windows terminal software that you use? (Preferably with version)

**Comment by anvis2000** [comment]
I've tried both the Windows commandline [version 10.0.10420] and Git Shell git version 2.5.3.windows.1.  Neither one works.

**Comment by martinheidegger** [comment]
@rvagg this seems to be a node-core regression?!

**Comment by rvagg** [comment]
Can we get anyone else to confirm on Windows 10? I don't recall seeing any concerns come up on nodejs/node about this so it's possible this is machine-specific somehow.

**Comment by SomeoneWeird** [comment]
Will try.

**Comment by rvagg** [comment]
From memory I think the previous bug had something to do with character widths didn't it @martinheidegger or am I getting them mixed up? What language is your computer set to @anvis2000?

**Comment by SomeoneWeird** [comment]
afaik, there was an issue with TTY not being configured properly on windows. See https://github.com/nodeschool/discussions/issues/1448

**Comment by SomeoneWeird** [comment]
And https://github.com/nodejs/node/pull/3490

**Comment by martinheidegger** [comment]
@rvagg The character width has been a separate issue.
@SomeoneWeird The tty issue does exist in some bash-for-windows versions - as far as I can remember.

**Comment by SomeoneWeird** [comment]
OK, both 5.1.0 and 5.6.0 on windows 10 are working alright for me.

**Comment by SomeoneWeird** [comment]
git-it works too. Rules out core regression.

**Comment by martinheidegger** [comment]
@anvis2000 Could you run `node -p -e "Boolean(process.stdout.isTTY)"`

**Comment by TylerMoeller** [comment]
Just to add to the thread, I'm also seeing the same issue with the git-it workshop + node 5.6.0 + x64Win10. I tried other workshops and also noticed the same problem with many of them: javascripting, promise-it-wont-hurt, regex-adventure, scope-chains-closures, stream-adventure, and test-anything. 

I'm not seeing it with the learnyounode or async-you workshops. Everything worked fine when I had Node 5.4.0. 

`node -p -e "Boolean(process.stdout.isTTY)"` = `true` when I run that command.

**Comment by anvis2000** [comment]
Same here.  I get a node -p -e "Boolean(process.stdout.isTTY)" = true on both the command line window as well as the Git Shell.

**Comment by anvis2000** [comment]
I think I've gotten to the bottom of this.  It seems that the problem with the non-responsive menus only occurs when I have an instance of the Microsoft Edge browser running.  When I kill all instances of Edge, the tutorial menus do work.

**Comment by TylerMoeller** [comment]
I don't use Edge, but tried it out to see if it affects the behavior and didn't see any difference on my Win10 machine.

The test code mentioned in https://github.com/nodejs/node/issues/5384 has an 80% failure rate on my machine (48/60 times tried) with and without Edge running.

**Comment by JohnyTech** [comment]
I've encountered with the same problem as you, guys, do.. The menu doesn't work even after restarting the shell. It seems pointless, but I've changed the language of the workshop to italiano and I cant't read it obviously. So does anyone know how to fix it? I've been trying only learnyounode so far. Thank you!

**Comment by TylerMoeller** [comment]
@JohnyTech do `learnyounode -l en` to get back to English.

To use the workshop without a functional menu, do `learnyounode select 1` where `1` is the exercise number. 

`learnyounode help` for more details.

**Comment by Slayther** [comment]
I can confirm that menu is not functional on Win 10, node v5.8.0 and v5.10.1, but it does work on node v4.4.5. Have only tried javascripting for now.

**Comment by benjamincarp** [comment]
this appears to also be an issue using the ubuntu for windows 10 bash and node v6.4.0

I also ran `node -p -e "Boolean(process.stdout.isTTY)"` and it returned true
