### ISSUE TITLE
git-it 7/11: Branches Aren't Just for Birds

### ISSUE THREAD

**Issue by blackbuddha88** [nodeschool/discussions#1643]
### Error output
```
remote: Permission to jlord/patchwork.git denied to blackbuddha88.
fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403
```

### My Code
```
$ git push origin add-blackbuddha88
```
So I followed the directions up to this point, and I successfully added a textfile with my username to the contributors folder. Then I entered this code to 'push my update to my GitHub fork', and this error message was returned to me.

The branchname is the same name as that which I created earlier in this module. I don't understand what is the cause of the error and would appreciate it if someone could assist me.

**Comment by koddsson** [comment]
Are you sure that you managed to add your username to the contributors folder?

It should be in [contributors/blackbuddha88](https://github.com/jlord/patchwork/blob/gh-pages/contributors/add-blackbuddha88.txt), right?

**Comment by blackbuddha88** [comment]
@koddsson 

> Are you sure that you managed to add your username to the contributors folder?
> 
> It should be in contributors/blackbuddha88, right?
![screenshot](https://cloud.githubusercontent.com/assets/16542247/13153709/6a3177aa-d643-11e5-854d-0a4eb5033c9e.png)

**Comment by koddsson** [comment]
Ah ok, I just ran through the `git-it` workshop and I understand a little bit better now. I think the problem is that when it says:

> remote: Permission to jlord/patchwork.git denied to blackbuddha88.

It's saying that the user `blackbuddha88` doesn't have access to push to the repo `jlord/patchwork.git`. Note that in this example the repo name consists of a username and the repo name seperated by a forward slash (`/`).

Could it be that your remotes have gotten mixed up and you are not in fact trying to push to your fork but some other remote?

**Comment by blackbuddha88** [comment]
@koddsson 

> Could it be that your remotes have gotten mixed up and you are not in fact trying to push to your fork but some other remote?

![screenshot](https://cloud.githubusercontent.com/assets/16542247/13160651/b1705a82-d666-11e5-9746-3a62c536dae2.png)

You, sir, have made my day.

Thank you very much for helping to identify the problem.

**Comment by koddsson** [comment]
:tada: Awesome! :tada: 

I'm glad I could help.
