### ISSUE TITLE
How to receive  email from contact form in  my website using node.js

### ISSUE THREAD

**Issue by sudanvellakovilkanakavel** [nodeschool/discussions#1646]
I have created a website using HTML5, and in contact page i have used java script to evaluate contact form. 
when client come to my website and fill their details in contact form ,of contact page and  entered submit button. I like to receive an email at info@mycomopany.com.

I know that only from server side scripting we can do it.
I like to do it with node.js 
i am new to node .js,can anyone kindly help.

### My Code
`<div class="container">
  <p style="font-size:24px;">SHOOT US AN EMAIL</p>
  <hr size="2%;"width="50%;">

  <form role="form" name="myForm" onsubmit="return(validate());">
  <div class="form-group">
      <label for="name">What is your name?</label>
      <input type="text" class="form-control" id="text" name="Name" placeholder="name">
    </div>
    <div class="form-group">
      <label for="cname">What is your company name?</label>
      <input type="text" class="form-control" id="text" name="Cname" placeholder="company name">
    </div>
    <div class="form-group">
      <label for="email">What is your email address?</label>
      <input type="email" class="form-control" id="email" name="EMail" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="phone">What is your phone number?</label>
      <input type="text" class="form-control" id="text" name="Phone" placeholder=" phone number with area code">
    </div>
    
    <div class="form-group">
      <label for="comment">What would you like to talk to us about?
</label>
      <textarea class="form-control" rows="5" id="comment"></textarea>
    </div>
    
    <button type="submit" class="btn btn-default">SUBMIT</button>
    
  </form>
  
</div>
```

**Comment by TheEvilDev** [comment]
You don't have to do this server side necessarily, the simplest solution is a mailto link in html.

You can do this with a basic a tag:

```
<a href="mailto:someone@somewhere.com">Contact us!</a>
```

The advantages of this approach, is simplicity, and it opens the user's configured email client, which may be more comfortable for them to use, and they get a copy of the feedback they submit automatically in their sent mail box.

If you want your send to address to remain annonomous, then you will need to do this server side. There are a number of tools in node to do this, including https://nodemailer.com/.

That said, any library supporting the protocol of your mailserver can do this  (i.e. pop, imap, exchange, etc). The main advantage of this approach is you protect your inbox from spam, and you can add additional verification on your site (like a captcha).

**Comment by sudanvellakovilkanakavel** [comment]
Hi,
Thank you for the replay.It was very useful.I have little doubts.

1)mailto option doesn't take content (form fields) client has filled in the form and send  it as e-mail to  someone@somewhere.com

2)I am looking for  noide.js function which is  equivalent to  mail() function  in php

3)Nodemailer is  used for  sending multiple mails from our website(newsletters,email marketing etc)

4) I am looking for client who visit my webpage,if he like to contact me ,he should fill a form and click submit,which i will receive in mail.

kindly correct me,if i am wrong.

**Comment by TheEvilDev** [comment]
Hey,

I'm not aware of any mail function in vanilla node, you're likely going to need a package for that. Nodemailer *can* be used for mass email, but there's really not much difference between sending 1 or 100 emails, you just need a straight forward abstraction layer over the smtp server.

Here's a blog post that show's the basic essentials:
http://javascript.tutorialhorizon.com/2015/07/02/send-email-node-js-express/

A quick google search aslo turns up node-sendmail:
https://www.npmjs.com/package/sendmail

Give the example a try and see if it works for you.

**Comment by sudanvellakovilkanakavel** [comment]
Hi 
nodemailer package worked successfully for my contact form. 
I used both sender and receiver mail id as same.
so when client fill his details in my contact form in contact page and click submit,mail containing details of the form filled by client is send from my mail id to same id.

Thus  i got the details of the clients who fill my contact form. Your guidance was very useful,thank you very much.

**Comment by deepakparamesh** [comment]
Hi @sudanvellakovilkanakavel ,
     I have been searching for this. can you send me the code of how to integrate the node function in HTML to send the mail. This would be very helpful for my website too.

Thanks in advance

**Comment by arezonasehi** [comment]
hey , would you please send me your code on nasehi.amir@gmail.com , cause i have the same issue , and you've already solved it,

**Comment by mizaelmorales** [comment]
please send me the code mizael754@gmail.com i need help with this one

**Comment by deepakparamesh** [comment]
Hi, I think this video would help for nodejs developers.
https://www.youtube.com/watch?v=nF9g1825mwk

**Comment by dark-dao** [comment]
Here is my simple implementation https://github.com/dark-dao/feedback-service. Run this service on your server. Then send a request from the web page. Then the data is sent by email using nodemailer. You can modify it to your needs))

**Comment by Kirti003Shukla** [comment]
Please share its code at kirti003shukla@gmail.com, I am facing the same issue. I have installed nodemailer but still, I am not able to get form details, it is showing reference error for node mailer.
Thanks in advance

**Comment by vishalisakar** [comment]
Hi @sudanvellakovilkanakavel, I am also facing the same issue, would You please share your code to vishalisakar27@gmail.com.
Thank you in advance.

**Comment by Kirti003Shukla** [comment]
Hi,
I solved the problem through php and jQuery, if you want that I can share.

**Comment by vishalisakar** [comment]
Thank you @Kirti003Shukla , but I am looking up in javascript node js.

**Comment by NJBOOT** [comment]
Look up the nodemailer package on npm and read the documentation
