### ISSUE TITLE
I was getting error

### ISSUE THREAD

**Issue by flik** [nodeschool/discussions#1656]
- node version: v5.7.0
- npm version:  3.6.0
### Error output

```
I installed {npm install -g bug-clinic}  and when I start bug-clinic.
 My system was hanged after a message I was unable to do anything.
```

**Comment by dominhhai** [comment]
> My system was hanged after a message I was unable to do anything.

your message is?

**Comment by flik** [comment]
I am unable to explore this bug-clinic ?

I have installed bug-clinic but not working properly. It is hanging up the system.
