### ISSUE TITLE
learnyounode Time Server problem

### ISSUE THREAD

**Issue by tzilih** [nodeschool/discussions#1657]
My code returns the date/time correctly but it's failing with this message:

Actual                                               Expected
"2016-03-07 19:30"      =               "2016-03-07 19:30" 
                                    !=               " "                                  <--- FAIL

I don't understand what that means and why my code failed.

This is what I wrote:
var net = require('net');
var myPort = process.argv[2];

var dateTime = new Date();
var month = dateTime.getMonth() + 1;
if (month < 10) month = '0' + month;
var date = dateTime.getDate();
if (date < 10) date = '0' + date;

dateTime = dateTime.getFullYear()+'-'+month+'-'+date+' '+dateTime.getHours()+':'+dateTime.getMinutes();

var server = net.createServer(function callback (socket) {
    socket.end(dateTime);
});

server.listen(myPort);

**Comment by noffle** [comment]
You're right: the test result output is odd.

Looking your code though, you've covered the cases where month or day is < 10. But what happens if the hour or minute is < 10 as well?

**Comment by bashmach** [comment]
Hi,

In your example error message tolds that actual result is null, but expected "".
So all you need is add a newline character after the date.

**Comment by josh08h** [comment]
@tzilih To fix it - append a '\n' to your data on line 10 like this:

    dateTime = dateTime.getFullYear()+'-'+month+'-'+date+' '+dateTime.getHours()+':'+dateTime.getMinutes() + '\n';

**Comment by HassanAlgoz** [comment]
Yep, same problem. Thanks guys! the new line character solved the problem!
