### ISSUE TITLE
Node.js on embedded linux

### ISSUE THREAD

**Issue by seletiur** [nodeschool/discussions#1660]
Hello everybody,

I'm quite new to Node.Js but I am involved in a project where we'll need to use Node.js in a embedded Linux systems. I was wondering if you guys could point me to some tutorials/books/documentations that might help me getting started.

Thanks in advance ;)

**Comment by riyadhalnur** [comment]
Hi, it's great you're working with NodeJS on embedded linux system.s Would love to know more about it and hopefully a working example soon. I've listed a few things that will help you get started. Hope they help and do follow up if you have more questions.

1. [http://embeddednodejs.com/chapters.html](http://embeddednodejs.com/chapters.html)
2. [https://events.linuxfoundation.org/sites/events/files/slides/nodejs-presentation_0.pdf](https://events.linuxfoundation.org/sites/events/files/slides/nodejs-presentation_0.pdf)

**Comment by seletiur** [comment]
Thanks riyadhalnur, I'll get started there. As soon as I have something to show, I'll post a working example. I will most likely need to use customized hardware, so any help on how to make Node.js communicate with device drivers will be helpful.

**Comment by riyadhalnur** [comment]
You are welcome @seletiur. You can look in to this package [node-serialport](https://github.com/voodootikigod/node-serialport) to communicate with serial ports using NodeJS.
