### ISSUE TITLE
Help with Recursion exercise of Functional Javascript is Good

### ISSUE THREAD

**Issue by ajw650** [nodeschool/discussions#1661]
I am getting confused at the initial step of this problem.

1module.exports = function getDependencies (tree) {
2	var arr = Object.keys(tree);
3	
4	//arr.forEach(function (curr) {
5	//	console.log(tree.curr);
6	//})
7}

This code doesn't produce errors.  But, as soon as I uncomment out the forEach part, I get a type error: cannot convert undefined or null to object for the second line of my code (var arr = Object.keys(tree);).  Thank you in advance.

Andrew

**Comment by noffle** [comment]
What is the value of `tree` when called?

Also, watch out: `tree.curr` is equivalent to `tree["curr"]`, which may not be your intention.

**Comment by riyadhalnur** [comment]
```js
var arr = Object.keys(tree);

arr.forEach(function (curr) {
  console.log(tree[curr]);
});
```

You have to use the bracket notation to reference the value for each key since the array returned by `Object.keys()` is an array of strings.

**Comment by ajw650** [comment]
Thank you very much.  I just tested all the permutations.  I think I understand now.
