### ISSUE TITLE
Install the javascripting locally

### ISSUE THREAD

**Issue by ericyuanyong** [nodeschool/discussions#1664]
Hi Guys, 
I'm trying to use Intel edison to learn the nodejs. For some reason i can't run the npm install --global javascripting, because of the GFW(I had installed nodejs and my npm version is 1.4.28 ). But i can download the file from github to my computer with the help of VPN, and i can move all of the file(javascripting-master.zip) to the onboard disk of edison. So that files can be in home folder of ediosn. The edison use Tocto OS.
I guess my question is based on that file,can i install javascripting locally?

**Comment by riyadhalnur** [comment]
@ericyuanyong, you can install locally but installing it locally means you won't be able to invoke the app from the terminal. You would have to navigate to the folder you installed the module in and invoke it from there always.
