### ISSUE TITLE
Unable to get rid of node and install it again

### ISSUE THREAD

**Issue by ARAtIntBitTech** [nodeschool/discussions#1666]
$ brew uninstall node
Error: No such keg: /usr/local/Cellar/node
$ brew link node;
Error: No such keg: /usr/local/Cellar/node

What do I do?

**Comment by Dalan-Miller** [comment]
Did you ever find a solution?

**Comment by malcolm-decuire** [comment]
I get the same issue and I'm so frustrated. I don't if its my lack of understanding about file systems or if this is extremely complex to do a simple thing

forgive my ignorance please

**Comment by roman17bb** [comment]
Maybe you installed node via a downloaded installer (and not brew) like I did?
