### ISSUE TITLE
What is my file supposed to be named and what do I type in the command line for meet_pipe?

### ISSUE THREAD

**Issue by energene** [nodeschool/discussions#1669]
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
### Error output

```
 // copy your error output here
```
### My Code

``` js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Hi @energene, can you please more details into the problem you're facing? Our issues now have a template. Filling it up gives us more context on the problems you might be having.
