### ISSUE TITLE
Make it Modular error

### ISSUE THREAD

**Issue by sandshoes** [nodeschool/discussions#1670]
After finishing filterls I have had trouble understanding make it modular. What I did is take what I had for filterls and fit it in module.exports. The file is called mymodule.js.

``` javascript
var fs = require('fs');
var path = require("path");

module.exports = function(dirname, filext, callback) {

  fs.readdir(process.argv[2],function (err,files){  
      files.forEach(function(file) {
          if (path.extname(file)==="."+process.argv[3]) {
              console.log(file);
          }
      });
  });
}
```

Then what I did is create the new file and declare the var mymodule. What I still don't understand is how to make the code in the middle work. I don't have a clear understanding of what it is asking. This is the code for my second file:

``` javascript
var mymodule = require('./mymodule.js') 
var callback= function(err,files) {
    if err{
        console.error(err);
    }
    files.forEach(function(file) {
        console.log(file);
    });
}

mymodule(process.arv[2], process.argv[3], callback);
```

**Comment by noffle** [comment]
Let's look at the module you've defined: what do you want it to do? What are its inputs, and what is the expected output? Should it write to standard out via `console.log`? Should it run the callback function `callback`? What information does it need to communicate back to your main JS code to achieve the desired result?

**Comment by sandshoes** [comment]
Thought about it and came up with this. Changed the second file:
```javascript 
var mymodule = require('./mymodule.js') 
function callback(err,files) {
    if (err){
        console.error(err);
    }
    console.log(files);
}

mymodule(process.argv[2], process.argv[3], callback);
```
Used callback function to print the files and if there's any error notify it. Everything looked OK but then I got this error.
![screen shot 2016-03-18 at 18 46 34](https://cloud.githubusercontent.com/assets/16758697/13887073/2859ec78-ed3a-11e5-8163-c5b94e98c85f.png)
Everything works but I can't understand this error

**Comment by Enriqe** [comment]
I'm also having trouble understanding this concept. How can we populate the "data" argument of the callback function created in the module?

`var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function callback(err, data){
		if(err != true){
			for(i=0; i<data.length; i++){
				if(path.extname(data[i]).substr(1)==ext)
			}
		}
	});
};
`

**Comment by Enriqe** [comment]
I'm also having trouble understanding this concept. How can we populate the "data" argument of the callback function created in the module?

This is what my module looks like

```
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
	fs.readdir(dir, function callback(err, data){
		if(err != true){
			for(i=0; i<data.length; i++){
				if(path.extname(data[i])=='.'+ext)
                    //should I populate the callback's data here?
			}
		}
	});
};
```

**Comment by alisneaky** [comment]
@sandshoes did you find a solution to that error?

**Comment by Enriqe** [comment]
@sandshoes did you remove the console.log()'s in your module? The instructions say you're not supposed to use print anything there. Also, you need to do early returns for errors. My solution ended up looking like this:

```
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
	var ext = '.' + ext;
	fs.readdir(dir, function (err, data){
		if(err)
			return callback(err);

		var list = data.filter(function( i ){
			return ( path.extname(i) == ext);
		});

		return callback(null, list)
	});
};
```

```
var mymodule = require('./ex6module');
var dir = process.argv[2];
var ext = process.argv[3];

function callback(err, files){
	if (err){
		console.log(err);
	}
	files.forEach(function(i){
		console.log(i);
	});

};

mymodule(dir, ext, callback);
```

**Comment by pjcevans** [comment]
I think the error above is is related to the correct output being logged by the module rather than the main file. When I ran through this I hit similar errors until I created an array in the module file that contained the right data, ran the callback function with that data as the second argument and then iterated through that array in the main file (callback) to output the data.

**Comment by LuisGVV** [comment]
I'm hitting the same error. My console.log method is called in the main (program.js) file, so I don't know if this is a weird error. I've got 2 files as following:

myModule.js:
`
// myModule.js

var fs = require('fs');
var path = require('path');

module.exports = function(dir, extension, callback){
    var extension = '.'+extension;
    fs.readdir(dir, function(err, data){
        if(err)
            throw callback(err);
        var list = data.filter(function(element){
            return(path.extname(element) === extension);
        });
        return callback(null, list);
    });
}
`
and then my main file program.js:
`
// program.js

var myModule = require('./myModule.js')

var directory = process.argv[2];
var extension = process.argv[3];


function myFiles(err, fileList){
    if(err){
        throw err;
    }
    for(var i = 0; i<fileList.length;i++){
        console.log(fileList[i]);
    }
};

myModule(directory, extension, myFiles);
`
I ran it first with node program.js ./ js as this should return the two files I'm running

**Comment by riyadhalnur** [comment]
@LuisGVV First, in your `myModule.js` file, you shouldn't throw a callback. You would return the callback with the error like so `return callback(err);`

Second, in `program.js`, you're only console logging the list of files in your array but but then you're not exiting the program after that's done.

**Comment by Philosophist** [comment]
Same error. Please help. 
node6b.js:
`var module = require('./node6a.js');

module(process.argv[2], process.argv[3], function(err, data) {
   if (err) {
       console.log(err);
   } 
   else {
       data.forEach(function(item) {
           console.log(item);
       });
   }
});`

node6a:
`var fs = require('fs');
var path = require('path');

function retrieve(callback) {
    fs.readdir(process.argv[2], function fin(err, list) {
        var arr = [];
        for(var i = 0; i < list.length; i++) {
            if(path.extname(list[i]) === '.' + process.argv[3]) {
                arr.push(path.basename(list[i]));
            }
        }
        callback(arr);
    });
}

function printList(arr) {
    for(var i = 0; i < arr.length; i++) {
        console.log(arr[i]);
    }
}

retrieve(printList);`

**Comment by GiannisGl** [comment]
see #1606
