### ISSUE TITLE
module

### ISSUE THREAD

**Issue by hrisp** [nodeschool/discussions#1672]
* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Hi @hrisp , can you please more details into the problem you're facing? Our issues now have a template. Filling it up gives us more context on the problems you might be having.

**Comment by hrisp** [comment]
Sorry, my bad. Please just close it.
