### ISSUE TITLE
help with Recursion exercise of Functional Javascript is Good

### ISSUE THREAD

**Issue by ajw650** [nodeschool/discussions#1674]
I need help with this problem, which takes a tree as an object and returns all the dependencies with its version number.  The dependencies are nested.  Therefore you need to recurse through the tree.  This is what I have so far.

module.exports = function getDependencies (tree) {
    var arr = [];

```
function findKeys(branch) {
    var branchHolder = [];
    branchHolder = branchHolder.concat(Object.keys(branch));
    //console.log(branchHolder);
    var filtered = branchHolder.filter(function (value) {
        return value !== 'name' && value !== 'version';
    })
    //console.log(filtered);
    filtered.forEach(function (twig) {
        if (twig !== 'dependencies') {
            arr.push(twig + '@' + twig.version)
            console.log(arr)
        } else {
            findKeys(branch[twig])
        }
    })
}

findKeys(tree);
return arr.sort();
```

}

The problems I am having are that my results look like value@undefined.  And, I don't seem to be recursing properly.  I can't figure out why.  Thank you for your help in advance!  :)

Andrew
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
### Error output

```
 // copy your error output here
```
### My Code

``` js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Please provide a set of reproducible steps.

**Comment by ajw650** [comment]
What is a 'set of reproducible steps'?  I'm sorry I don't know what this means.

**Comment by ajw650** [comment]
I figured out the value@undefined part.  I still don't know why my code isn't recursing properly.  It seems to not like 
				findKeys(branch[twig]);
for some reason.
