### ISSUE TITLE
Not able to return to previous course

### ISSUE THREAD

**Issue by KavyaBavikatti** [nodeschool/discussions#1676]
Hi,

I am trying start learnyounode from begining. But when I start learnyounode it is showing exercise for "Make it Modular". Kindly help.

PFA of screenshot.

Thanks
Kavya Rani B
![learnyounode](https://cloud.githubusercontent.com/assets/17717506/13838743/43e8c310-ec0e-11e5-8ef0-4f009e7a58bd.jpg)

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by ismnoiet** [comment]
@KavyaBavikatti  you can use <kbd>k</kbd> key to move up and <kbd>j</kbd> to move down, once you are in the right exercise hit <kbd>enter</kbd> and you should be ready to start that exercise whether its completed or the first time you open it.

**Comment by Hillsie** [comment]
@KavyaBavikatti , I can confirm that @ismnoiet is the way it works for me. You could probably try it out and if it work close of  this one.
