### ISSUE TITLE
Cannot install stream-adventure

### ISSUE THREAD

**Issue by ericviston** [nodeschool/discussions#1685]
* node version: v4.3.2
* npm version:  2.14.12

### Error output
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "stream-adventure"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: provinces@'>=1.8.0 <1.9.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","0.0.1-security"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'stream-adventure'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ericviston\npm-debug.log

I have problem with installing stream-adventure. Although i have google a lot,  i can figure out what to do

**Comment by substack** [comment]
The provinces package was unpublished recently. We're trying to figure out a fix. https://github.com/substack/provinces/issues/20

**Comment by madHamish42** [comment]
@ericviston : You could clone the stream-adventure git repo to your local machine and make a change to the package.json file. 
Under "dependencies" just replace 
"provinces": "~1.8.0" 
with 
"provinces": "~2.0.0".
Then install stream adventure globally from your local repo with: 
npm install -g.
I did that yesterday and it works fine.

**Comment by nikcorg** [comment]
@madHamish42 the provinces 2.0.0 package was not an equivalent replacement for the previous version. But, you can replace the version number with `substack/provinces` to install the correct dependenct.

**Comment by madHamish42** [comment]
Great, thanks for the clarification.

**Comment by ericviston** [comment]
Thank you every one for your great help.

**Comment by substack** [comment]
provinces 1.8.1 now exists on npm
