### ISSUE TITLE
cannot draw polygons on cat (elementary electron)

### ISSUE THREAD

**Issue by cromagi** [nodeschool/discussions#1692]
When i verify it, it passes but i cannot draw polygons on cat as described.

node version :5. 7. 0 

npm version:  3. 6. 0 

``` js
index.js
var picture = require('cat-picture')
var src = picture.src
var image = require('lightning-image-poly')
var src = picture.src
var viz = new image('#visualization', null, [src] ,{hullAlgorithm: 'convex'})
picture.remove()


app.js
var electron = require('electron')

electron.app.on('ready', function () {
    var mainWindow = new electron.BrowserWindow({width: 600, height: 800})
    mainWindow.loadURL('file://' + __dirname + '/index.html')

})
```

**Comment by fultonm** [comment]
Reproduced this error and received the following error:
G:\workspace\elementary-electron\hello-world\node_modules\lightning-client-utils\index.js:39
Uncaught TypeError: Cannot read property 'indexOf' of undefined

**Comment by Mycroft1891** [comment]
I assume your html file (index.html) doesn't have a div with an id of "visualization". 

`<div id='visualization'></div>`

Check if you have a typo. Both have to be the same. 
Could you show us what you have in the index.html file ?

**Comment by abhidd** [comment]
seems to be the same(visualization), here is my index.html file:

<!DOCTYPE html>  
<html>  
<head>  
</head>  
<body>  
<h1>Hello World</h1>
<div id='visualization'></div> 
<script type="text/javascript" src="index.js"></script>
</body>  
</html>  


i'm on ubuntu 16, npm and ubuntu installed recently, probably latest versions

thanks

**Comment by abhidd** [comment]
`<!DOCTYPE html>  
<html>  
<head>  
</head>  
<body>  
<h1>Hello World</h1>
<div id='visualization'></div> 
<script type="text/javascript" src="index.js"></script>
</body>  
</html>  `

**Comment by abhidd** [comment]
f***ing hell

> <!DOCTYPE html>  
<html>  
<head>  
</head>  
<body>  
<h1>Hello World</h1>
<div id='visualization'></div> 
<script type="text/javascript" src="index.js"></script>
</body>  
</html>

**Comment by abhidd** [comment]
>

**Comment by abhidd** [comment]
> <!DOCTYPE html>  
> <html>  
> <head>  
> </head>  
> <body>  
> <h1>Hello World</h1>
> <div id='visualization'></div> 
> <script type="text/javascript" src="index.js"></script>
> </body>  
> </html>

**Comment by abhidd** [comment]
well the div is there, and the id is id='visualization', its the same in var viz = new image...

**Comment by abhidd** [comment]
and its before the script tag as suggested in the tut

**Comment by Ertist** [comment]
You have one more **var src = picture.src**

just like this:

```javascript
var picture = require('cat-picture')
var image = require('lightning-image-poly')

var src = picture.src
 var viz = new image('#visualization', null, [src], {hullAlgorithm: 'convex'})
picture.remove()
```
