### ISSUE TITLE
course path

### ISSUE THREAD

**Issue by ghost** [nodeschool/discussions#1693]
I'm doing javascripting class and want to go to learnyounode next then npm, what do I take after that? and as far as electives go do you have any angular courses?
* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by geekmonster** [comment]
I think I posted in the wrong forum

**Comment by riyadhalnur** [comment]
Personally, I would suggest finishing these first few modules 
![screen shot 2016-05-11 at 10 46 59 am](https://cloud.githubusercontent.com/assets/3457571/15170273/439c002e-1766-11e6-8a69-3ffd34990936.png)

After you're done with those, you can move on to the electives and as the name implies, they are electable. So it's up to you to choose the specific topics you want to learn in depth.
