### ISSUE TITLE
Blank solution on javascripting

### ISSUE THREAD

**Issue by igloocube** [nodeschool/discussions#1694]
I get no example solution on the javascripting exercises. Nothing is displayed. I've done a few now and they've all done this.
- node version: v5.9.1
- npm version:  3.7.3

OS X 10.11, used brew to install npm.
### Example output:

```
$ javascripting verify string-length.js
  # PASS Your solution to STRING LENGTH passed!

  Here's the official solution in case you want to compare notes:

 ─────────────────────────────────────────────────────────────────────────────

 # WIN: 14 CHARACTERS

  You got it! The string example string has 14 characters.

  Run javascripting in the console to choose the next challenge.

 ─────────────────────────────────────────────────────────────────────────────
  You have 15 challenges left. Type 'javascripting' to show the menu
```

**Comment by koddsson** [comment]
[It seems it's a known bug in `javascripting`](https://github.com/sethvincent/javascripting/issues/145). I was gonna say that hopefully it's fixed soon but there hasn't been a lot of traction on that issue :disappointed:

**Comment by igloocube** [comment]
Thank you. I searched the issues here but forgot to check the javascripting repo. I've gone for just looking at the solutions folder of the source.

**Comment by jmpp** [comment]
https://github.com/workshopper/javascripting/issues/145#issuecomment-337540387
