### ISSUE TITLE
aync juuggling - can't explain behaiviour

### ISSUE THREAD

**Issue by swinston100** [nodeschool/discussions#1697]
This is about Juggling Async in Learnyounode  (Exercise 9 of 13)

I have the program working by changing the location of 

`if(count==3) printResults();`

If it's located in the bl function then it works but I move this code outside that function then the count never reaches 3.
Can someone please explain to a relative beginner why this is.

The code below contains a console.log() so that I could determine the count as the program ran. This is why I am getting output 0,1,2... :-)

Thanks!

* node version: v4.4.1
* npm version:  2.14.20

### Error output

1.  ACTUAL:    "a: 0"
1.  EXPECTED:  "As cross as a pint no dramas as cross as a dipstick. Flat out like a sleepout my it'
ll be slab. He hasn't got a cactus mate and as busy as a bush telly. "

2.  ACTUAL:    "a: 1"
2.  EXPECTED:  "As stands out like scratchy with she'll be right dob. Flat out like a ridgy-didge pi
ece of piss grab us a cobber. Lets throw a jillaroo bloody stands out like a aussie salute. "

3.  ACTUAL:    "a: 2"
3.  EXPECTED:  "As stands out like strides also flat out like a aussie rules footy. As cunning as a
billy also come a dog's balls. Come a ute heaps he hasn't got a blow in the bag. As stands out like
bathers also it'll be vinnie's. As cross as a bradman how gutful of piker. "

4.  ACTUAL:    ""
4.  EXPECTED:  ""

### My Code

```js
var http = require('http');
var bl = require('bl');
var results = [];
var count = 0;
for (var i = 0; i < 3; i++)
  httpGet(i)

function httpGet(index) {

  http.get(process.argv[index+2], function(response){
    response.pipe(bl(function(err,data){
      results[index] = data.toString();
      count++

      // works here - comment to get working
      //if(count==3){ printResults(); }

    }));

        console.log('count: ' + count);
        // doesn't work here
        if(count==3){ printResults(); }

  });

}

function printResults () {
  for (var i = 0; i < 3; i++)
    console.log(results[i]);
  }
```

**Comment by noffle** [comment]
Let's flatten out your `httpGet` function and its two callback functions into three distinct functions:

```js
function httpGet(index) {
  http.get(process.argv[index+2], handleResponse)
}

function handleResponse(response){
    response.pipe(bl(handleData))
}

function handleData(err,data){
      results[index] = data.toString();
      count++

      // (A)
      if(count==3){ printResults(); }
}

// (B)
if(count==3){ printResults(); }
```

Where control flows from `httpGet` -> `handleResponse` -> `handleData` each time`httpGet` is called.

This is a bit more intuitive to think about -- many nested callbacks can obfuscate the control flow. (B) is actually executed before the code in any of these functions is: `http.get()` triggers an asynchronous process that will result in `handleResponse` being called at some point in the future.

**Comment by swinston100** [comment]
Many thanks @noffle for making my code more understandable and for the great explanation :-) :+1:
