### ISSUE TITLE
Floating point Math

### ISSUE THREAD

**Issue by Hillsie** [nodeschool/discussions#1699]
node v4.4.0
npm 2.14.20

### Floating point 

//why does 
`0.1 + 0.2 //equate to  0.30000000000000004 ?`

// what other floating point math should we be aware of?

**Comment by koddsson** [comment]
I've never really been able to wrap my mind around it but here's a good reading resource that tries to explain it: http://floating-point-gui.de/

**Comment by koddsson** [comment]
From the "basic answers" section of that site:
>Because internally, computers use a format (binary floating-point) that cannot accurately represent a number like 0.1, 0.2 or 0.3 at all.

>When the code is compiled or interpreted, your “0.1” is already rounded to the nearest number in that format, which results in a small rounding error even before the calculation happens.

**Comment by SomeoneWeird** [comment]
Another good read is [this website](http://0.30000000000000004.com/)

**Comment by Hillsie** [comment]
Thanks for your answers. Then my follow up question is, how can I insure that my floating point math is predictable?

**Comment by Hillsie** [comment]
Thanks again guys, ...yip, I completely understand now.

**Comment by binarybaba** [comment]
I can't believe someone actually decided to go with 0.30000000000000004.com as a domain name. Brilliant.
