### ISSUE TITLE
stream-adventure HTML Stream validation fails

### ISSUE THREAD

**Issue by wileym** [nodeschool/discussions#17]
Running my version seemed to be producing valid results when using 'stream-adventure run'. When switching to 'stream-adventure verify' it reports an incorrect result, but all the expected result lines are null.

To check, I copied stream-adventure/problems/html_stream/solution.js, tried verify again, and had the same result.

I'm running Win7, node 0.10.18

**Comment by Sequoia** [comment]
@moriame @wileym please reopen if this issue exists! :+1:

**Comment by andrewmnelson** [comment]
I had this issue as well, running stream-adventure on Windows 7 x64, and discovered that by making the 'through' callback =
function(buf, _notUsed, next) {
  this.push(buf.toString().toUpperCase());
  next();
}
the .loud text got uppercased, and the following text was also streamed.  Why this is different on Windows, I have no idea, but this is *exactly* why I'm a believer in genetic diversity among devs :-)
