### ISSUE TITLE
Use of web servers?

### ISSUE THREAD

**Issue by Hillsie** [nodeschool/discussions#1701]
I'm puzzled where a in this model the need for a web server is? Could someone please explain. I sort of get the idea that, why would I want one.

**Comment by riyadhalnur** [comment]
@Hillsie I think you meant to say module instead of model. If so, then which module are you referring to?

**Comment by Hillsie** [comment]
@riyadhalnur with the use of cloud services, I really don't see the need to know about webservers. They are abstracted I assume. All of my code becomes a service. Maybe I am missing something and I will soon understand, but hence my question. I'm going to close this one until I have a clearer picture how everything is turning into a service.
