### ISSUE TITLE
Javascripting

### ISSUE THREAD

**Issue by DanielDwyer** [nodeschool/discussions#1702]
I am new to coding and went to the nodeschool in Denver this past week. I was able to run learnyounode in my terminal. Today I wanted to learn some javascript so I ran npm install -g javascripting in my terminal and it was successfully installed but now I don't know how to bring up the menu with all the lessons listed in it. What do I type in my terminal to bring up and start the javascript course?

Please & Thank you

**Comment by riyadhalnur** [comment]
Hi Daniel,

All you need to do to access the exercise is to go the terminal and type in `javascripting` and press enter. That should bring up the module. You can then use arrow keys to select the exercise you want to do.

Cheers.

**Comment by DanielDwyer** [comment]
Thank you very much!!!
