### ISSUE TITLE
In React.js How to pass values of form from one component to another component

### ISSUE THREAD

**Issue by sudanvellakovilkanakavel** [nodeschool/discussions#1708]
1)Trying to create an EMI  calculating app 
2)which allow user to enter details in a form (Home.js component) 
3)and results will be calculated and displayed by PromptContainer component
4)Main.js component contain header which will be displayed always(on both Home.js and PromptContainer component)irrespective of which one is rendered.
5)In my EMI calculator application using react.js , i have form in one component called Home.js when user enter the form values and click calculate emi,

I like to pass the form values to another component called PromptContainers where it will be evaluated and EMI will be calculated and displayed.

6)on running the server i get the following error

### Error output
```
 ERROR in ./app/containers/PromptContainer.js
Module build failed: SyntaxError: /Users/kanaks/Desktop/secondapp/app/containers/PromptContainer.js: Unexpected token (17:0)


if( document.myForm.age.value == "" )
         {
            alert( "Please provide your age!" );
            document.myForm.age.focus() ;
```

### My Code   

for easy reading full source code is in https://github.com/sudanvellakovilkanakavel/multicomponent-EMIapp

File name  :   app/containers/PromptContainer.js

var React = require('react');
var ReactDOM = require('react-dom');

var PromptContainer = React.createClass({

    render: function () {

      return (
            
       <div className= "jumbotron col-sm-6 col-sm-offset-3 text-center">       

calInterestandvalidation: function() {

if( document.myForm.age.value == "" )
         {
            alert( "Please provide your age!" );
            document.myForm.age.focus() ;
            return false;
         }
 if( document.myForm.income.value == "" )
         {
            alert( "Please provide your income!" );
            document.myForm.income.focus() ;
            return false;
         }
  if( document.myForm.loan.value == "" )
         {
            alert( "Please provide your loan!" );
            document.myForm.loan.focus() ;
            return false;
         }

  if( document.myForm.rate.value == "" )
         {
            alert( "Please provide your rate!" );
            document.myForm.rate.focus() ;
            return false;
         }
  if( document.myForm.months.value == "" )
         {
            alert( "Please provide your months!" );
            document.myForm.months.focus() ;
            return false;
         }

  if(

    document.myForm.age.value != "" && 
    document.myForm.income.value != "" && 
    document.myForm.loan.value != "" &&
    document.myForm.rate.value != "" &&
    document.myForm.months.value != ""

    )
         {

            var loanterm = document.myForm.months.value;
            var roicomb;  //rate of interest calculated on monthly basis
         
            var emi;
            var principle = document.myForm.loan.value;
            var rannualinterest = document.myForm.rate.value ;

           roicomb = rannualinterest/12/100;

           emi=principle*roicomb *(1+roicomb )^loanterm/((1+roicomb )^loanterm-1);
           alert(emi);
           return true;

          }

return( true );
},

		)

}

});  

        </div>
           
    

module.exports = PromptContainer;

File name: app/config/routes.js

var React = require('react');
var ReactRouter = require('react-router');
var Router = ReactRouter.Router;
var Route = ReactRouter.Route;
var IndexRoute = ReactRouter.IndexRoute;
var hasHistory = ReactRouter.hasHistory;
var  Main = require ('../components/Main');
var  Home = require ('../components/Home');
var  PromptContainer = require ('../containers/PromptContainer');

var routes = (

<Router history={hasHistory}>

<Route path='/'  component= {Main} >

   <IndexRoute component={Home}  />
   <Route path='PromptContainer' component={PromptContainer} />

</Route>
</Router>

);

module.exports = routes;

components/Home.js

var React = require('react');
 var ReactRouter = require('react-router');
var Link = ReactRouter.Link;

var divStyle = {
  background: "#D9EDF7"
  
  
}; 

var Home = React.createClass({
render: function()
{

return(

<div className= "jumbotron col-sm-6 col-sm-offset-3 text-center" style={divStyle} > 
             <form name="myForm" onSubmit= {'../containers/PromptContainer.js'} method="post">
             
           
            
           <div class="form-group">
            <label>Choose a bank  :</label>
              <div class="col-sm-6">
            <select>
  <option value="">Canadian Imperial Bank of Commerce</option>
  <option value="">Bank of Montreal</option>
  <option value="">Laurentian Bank of Canada</option>
  <option value="">National Bank of Canada</option>
</select>
</div>
</div>
           <br />
           <div class="form-group">
            <label>Choose a Gender :</label>
              <div class="col-sm-6">
              <select>
  <option value="">Male</option>
  <option value="">Female</option>
  <option value="">Other</option>

</select>
</div>
</div>
<br />
             <div class="form-group">
            <label>Choose a loan type  :</label>
             <div class="col-sm-6">
            <select>
  <option value="">Personal</option>
  <option value="">Housiing</option>
  <option value="">Vechile</option>
  <option value="">Business</option>
</select>
</div>
</div>
           <br />
           
               <div class="form-group">
            <label>Enter the current age :</label> 
            <div class="col-sm-6">  
            <input type="number" class="form-control" name="age" placeholder="eg. 25" />
         </div>
         </div>
           <br />
           <div class="form-group">
            <label>Enter monthly income in $:</label> 
            <div class="col-sm-6"> 
            <input type="number" class="form-control" name="income" placeholder="eg. 30000" />
            </div>
            </div>
              <br />
         <div class="form-group">
            <label>Enter loan amount in $:</label> 
            <div class="col-sm-6"> 
            <input type="number" class="form-control" name="loan" placeholder="eg. 1000000" />
            </div>
            </div>
              <br />
             <div class="form-group">
            <label>Enter  interest rate in % : </label>
             <div class="col-sm-6"> 
            <input type="text" class="form-control" name="rate" placeholder="eg. 10.5" />
            </div>
            </div>
             <br />
           <div class="form-group">
            <label>Enter duration in months : </label>
            <div class="col-sm-6"> 
            <input type="number" class="form-control" name="months" placeholder="eg. 48" />
           </div>
            </div>
            <br />
              <br />
              <br />
              <div className="form-group col-sm-4 col-sm-offset-4">
              <Link to='../containers/PromptContainer.js'>

            <button className="btn btn-block btn-success"type="submit">CALCULATE</button>

            </Link>
</div>
<br />
              <br />
              <br />
              
            </form>

            </div>

	)

}

});

module.exports = Home;

File Name: app/components/Main.js

var React = require('react');
var ReactRouter = require('react-router');

var divStyle = {
  background: "#F5F5DC"
  
}; 

var Main = React.createClass({

  render: function () {

     return (
              <div className= "jumbotron col-sm-6 col-sm-offset-3 text-center" style={divStyle} > 
            
            <h2><font color="orange">CHOOSE YOUR LOAN WISELY </font></h2>
           <h4>An React  App For Calculating Your Monthly Loan Interest in Different Canadian Banks</h4>
           <br /> <br />

           {this.props.children}
           </div>

            )
                     }

  });

module.exports = Main;

File Name : index.html

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> Welecome to My Second React App </title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>

	<div id="app"></div>
</body>
</html>

File Name: index.js

var React = require ('react');
var ReactDOM = require('react-dom');
var routes = require('./config/routes');

ReactDOM.render(

routes,

document.getElementById('app')

  );
 // copy your code here
```

**Comment by riyadhalnur** [comment]
In React.js, component to component communication is done through `props`. You can read about it in more details in the [documentation](https://facebook.github.io/react/tips/communicate-between-components.html).
