### ISSUE TITLE
Time Server failing without failing

### ISSUE THREAD

**Issue by jazmatician** [nodeschool/discussions#171]
So, I have the times matching, but the second line, null != '' is where it fails.
I noticed all the other challenges check for an empty string at the end of the application. What is that? Why does my time server not have it?

My code:
var net = require('net');
var moment = require('moment');

var server = net.createServer(function(socket) {
    socket.end(moment().format('YYYY-MM-DD HH:mm'));
    });
server.listen(process.argv[2]);

Result:
Verifying "TIME SERVER"...

ACTUAL                             EXPECTED

---

"2014-01-23 00:09"                 "2014-01-23 00:09"
null                            != ""
# FAIL

Your solution to TIME SERVER didn't match the expected output.
Try again!

**Comment by AdamAtri** [comment]
@rvagg 's answer is correct. see his anwer [here](https://github.com/nodeschool/discussions/issues/123#issuecomment-33098179)
