### ISSUE TITLE
These files can't be opened error

### ISSUE THREAD

**Issue by deedle42** [nodeschool/discussions#1713]
*node version: 4.4.3
- npm version:  2.15.1

I am getting a windows security error when trying to create files. I have tried a couple different editors to create the file with. The error is:

These files can't be opened.
Your internet security settings prevented one or more files from being opened.

I am running Windows 10. I'm not sure what internet security settings there are on here. I have tried turning most of it of already.

**Comment by BlackGuyCoding** [comment]
What browser are you using? And are you having any problems opening any other types of files?

It sounds like a browser changed your security settings somehow and they need to be reset.

**Comment by deedle42** [comment]
I use Google Chrome as my web browser. I have only ever had this problem when trying to start lessons in Node. This is my first attempt at doing any of this and I can't seem to get started. Everything seems to be installed correctly.
