### ISSUE TITLE
javascripting #12 array-filtering.js  problem

### ISSUE THREAD

**Issue by TimNR** [nodeschool/discussions#1715]
Hi, folks,

I have problem in #12javascripting array-flitering.
Please let me know what's wrong(_ _).

### My Code
array-filtering.js 

var numbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
filtered = numbers.filter(function evenNumbers(number) {
return(number % 2 === 0);
});
console.log(filtered);

**Comment by riyadhalnur** [comment]
`numbers` is supposed to be an array - `var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. You declared it as an object.

**Comment by TimNR** [comment]
Thank you, riyadhalnur.
It worked!
I spent more than one hour for it(^^;).
