### ISSUE TITLE
Stuck after: npm install -g javascripting

### ISSUE THREAD

**Issue by andy-young** [nodeschool/discussions#1716]
- node version: 4.4.3
- npm version:  2.15.1
### Error output

```
 npm ERR! tar.unpack untar error /Users/andyyoung/.npm/javascripting/2.6.0/package.tgz
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "javascripting"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path /usr/local/lib/node_modules/javascripting
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/javascripting'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/javascripting']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andyyoung/npm-debug.log
```
### My Code

``` js
 // copy your code here
```

**Comment by ismnoiet** [comment]
@andy-young you need to be an  administrator in order to install this workshop as you can read from the error message **Error: EACCES: permission denied,**

All you have to do is to prefix the previous install command with a leading ``sudo`` like this : 

`` sudo npm install -g javascripting``

Then you'll be asked to write you password, then the workshop is hopefully installed and ready to play with.

**Comment by 123survesh** [comment]
how to access the installed files after that?

**Comment by adamerobertson** [comment]
At the command prompt, type 'javascripting' and you will see:

                                                                              
   JAVASCRIPTING                                                              
   Select an exercise and hit Enter to begin                                  
   ─────────────────────────────────────────────────────────────────────────  
   » INTRODUCTION                                                             
   » VARIABLES                                                                
   » STRINGS                                                                  
   » STRING LENGTH                                                            
   » REVISING STRINGS                                                         
   » NUMBERS                                                                  
   » ROUNDING NUMBERS                                                         
   » NUMBER TO STRING                                                         
   » IF STATEMENT                                                             
   » FOR LOOP                                                                 
   » ARRAYS                                                                   
   » ARRAY FILTERING                                                          
   » ACCESSING ARRAY VALUES                                                   
   » LOOPING THROUGH ARRAYS                                                   
   » OBJECTS                                                                  
   » OBJECT PROPERTIES                                                        
   » FUNCTIONS                                                                
   » FUNCTION ARGUMENTS
