### ISSUE TITLE
Juggling Sync, not synced

### ISSUE THREAD

**Issue by shivamarora13** [nodeschool/discussions#1719]
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
### Error output

```

1.  ACTUAL:    "Grab us a chrissie mate as cunning as a rage on. As cunning as a fair dinkum no worries grab us a khe sanh. "
1.  EXPECTED:  "Grab us a fremantle doctor my as stands out like bazza. As cunning as a spag bol flamin lets throw a mongrel. As stands out like two pot screamer bloody she'll be right amber fluid. "

2.  ACTUAL:    "As cunning as a cactus mate also as cunning as a galah. He's got a massive barbie no worries shazza got us some bog standard. Shazza got us some pokies also as cross as a gyno. "
2.  EXPECTED:  "Grab us a chrissie mate as cunning as a rage on. As cunning as a fair dinkum no worries grab us a khe sanh. "

3.  ACTUAL:    "Grab us a fremantle doctor my as stands out like bazza. As cunning as a spag bol flamin lets throw a mongrel. As stands out like two pot screamer bloody she'll be right amber fluid. "
3.  EXPECTED:  "As cunning as a cactus mate also as cunning as a galah. He's got a massive barbie no worries shazza got us some bog standard. Shazza got us some pokies also as cross as a gyno. "

4.  ACTUAL:    ""
4.  EXPECTED:  ""
```
### My Code

``` js
var bl = require('bl'); 
var http = require('http');
var results = [];
var count = 0;


for(var index=0; index < 3 ; index++){

   http.get(process.argv[2+index],function callback(response){

   response.pipe(bl(function(err,data){
      if(err) return console.error(err);
      console.log(data.toString());
      results.push(data.toString());
      count++;

      if(count==3){
         for(var i =0; i<3;i++){
            console.log(results[i]);
         }
      }
   }));
   });
}
```

**Comment by noffle** [comment]
Do you have any suspicions as to why your results aren't appearing in the desired order?

In your code, what happens when the HTTP request for the 2nd URL returns **before** the 1st URL? Is there any way you might prevent the 2nd HTTP request from starting until *after* the 1st completes?

**Comment by pankaj805** [comment]
Noffle is right. But i will disagree with the approach. If we prevent the 2nd http request from starting until after 1st one completes, then we are not taking the benefit of asynchronous flow.

you are calling 3 urls, all the operations you are performing are happening in the callback. So, the loop probably completes before actually running the callback for any of the url, the webpages are heavy etc.

No, you don't have any control on whose callback will be executed first. 

So you have to work on that logic.

You can check my solutions for learnyounode in case you are stuck:
https://github.com/pankaj805/nodeschool_learnyounode

Let me know if this helped you
