### ISSUE TITLE
Functional-javascript-workshop Function Call - question with solution spoiler

### ISSUE THREAD

**Issue by rlau1115** [nodeschool/discussions#172]
The official answer to this question makes somewhat sense:

```
module.exports = Function.call.bind(Array.prototype.slice);
```

Correct me if I'm wrong here (or anywhere in this post), but I get that in binding Array.prototype.slice to call, it's the same as saying Array.prototype.slice.call( ).

My questions lie in the answers that I unsuccessfully tried to work out:

```
module.exports = Array.prototype.slice.bind(arguments[0]);
```

My thoughts with this approach were that I would be binding the array supplied in the first argument to invoke Array.prototype.slice.  I figured this would work, because the arguments supplied to our custom slice function require that we call Array.prototype.slice on the array passed in as the first argument.  

However, while my code did compile, the results ended up being an empty array.  This suggested to me that my code wasn't actually firing.  

Questions:
1) What was my code actually doing, if not the desired result?  Why didn't it produce the desired result?
2) How does the official solution deal with the array being passed in as the first argument?  In the actual implementation of Array.prototype.slice, don't you need to invoke this function with an array?  (As in someArray.slice(0, 1) )

I also tried these two options, to no avail.  

```
module.exports = Function.prototype.call.bind(Array.prototype.slice, arguments);
module.exports = Function.prototype.call.bind(Array.prototype.slice, arguments[0]);
```

Any insight on my confusion?

**Comment by invokercd** [comment]
@timoxley  thanks. Great explanation about bind()
