### ISSUE TITLE
learnyounode - can't complete challenge #10 TIME SERVER

### ISSUE THREAD

**Issue by eywenn** [nodeschool/discussions#1724]
* node version: 4.4.3
* npm version:  2.15.1

### Error output
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "2016-05-03 10:15"                  ==    "2016-05-03 10:15"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

  ✗ Submission results did not match expected!

```

### My Code

```
var strftime = require('strftime')
var net = require('net')

var time = strftime.timezone('+0200')
var server = net.createServer(function (socket){
	socket.end(time('%Y-%m-%d %H:%M'))
})
server.listen(process.argv[2])
```

To state the obvious, my program doesn't output an empty line where learnyounode expects one. for some reason I can't get it to just print one either. I tried `console.log('\n')` both in and outside the callback function of the server. Neither brought the expected  output.

is there a way to work around this? I just dislike the idea that it doesn't say 'completed'.. :D

**Comment by riyadhalnur** [comment]
@eywenn Almost there. You just need to add a new line after the `socket.end` function. It'll look something like this - 
```js
var server = net.createServer(function (socket){
    socket.end(time('%Y-%m-%d %H:%M') + '\n');
});
```

**Comment by eywenn** [comment]
@riyadhalnur thanks! fixed it.

**Comment by riyadhalnur** [comment]
Awesome. Is it working now?

**Comment by StevenYuysy** [comment]
@riyadhalnur  It work! Thx a lot.
