### ISSUE TITLE
#2 Baby Steps problem

### ISSUE THREAD

**Issue by TimNR** [nodeschool/discussions#1728]
Hello, Folks,

I have trouble in Baby Steps.
Please give me suggestions.

for (i=2; i++; i<process.argv.length) {
    var sum = Number(process.argv[i]) + sum
};
console.log(sum);

**Comment by noffle** [comment]
1. What output did you expect?
2. What output did you get? Were there errors?
3. Do you have an hypotheses of what might be wrong?

**Comment by TimNR** [comment]
Noffle,

Thank you for your comment.

What output did you expect?
->
I expect variable sum would sum up elements of process.argv during for loop.


What output did you get? Were there errors?
->
No errors.  Just stucked.


Do you have an hypotheses of what might be wrong?
->
I expect there might be infinite loop in for sentence because the program was stucked.


I am looking forward to you comments.

**Comment by noffle** [comment]
Excellent analysis! I think your hypothesis may be correct. Let's look at the syntax for a [`for` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for):

```
for ([initialization]; [condition]; [final-expression])
   statement
```

What values do you have for each piece of the `for` loop? Are the `condition` and `final-expression` in the right places?

**Comment by TimNR** [comment]
Thank you noffle,

I checked sequence of for loop numbers.
I could get the result although still it is error!

My new code is as follows.
->
var i;
var sum;
for (i=2;  i<process.argv.length; i++) {
	sum = Number(process.argv[i]) + sum
};
console.log(sum);


Error messages are as follows.
->
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "NaN"                               !=    "556"                              
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✗  Submission results did not match expected!  
   
       
     # FAIL  
     Your solution to BABY STEPS didn't pass. Try again! 


I checked for loop starting from i=2 to 3,4,,,.  But I could not get the reason for error message.
Please give me some advices.

**Comment by noffle** [comment]
Be careful about making sure variables are initialized. If you run

```js
var sum
console.log(sum + 1)
```
you'll get `NaN`. This is because `sum` was never initialized to e.g. `0`.

**Comment by hayk94** [comment]
Hello guys I am having some issues with this step as well.
Here is what I've written
console.log(process.argv);
var sum = 0;
for (var i = 2; i < process.argv.length; i++) {
  sum += Number(process.argv[i]);
}
console.log(sum);

It works great with node program.js and works great with learnyounode run program.js but for some unknown reason when I run learnyounode verify program.js it doesn't get verified

**Comment by ishtiaque23** [comment]
@hayk94 please remove the first **console.log** from your code. Your code should only **console.log** the sum at the end(which you are doing fine). Any extra output returned by your code will be considered error by the verifier script.

**Comment by hayk94** [comment]
@ishtiaque23  Thank you

**Comment by Catcheer** [comment]
@ishtiaque23   Thangk you      I am having some issues with this step as well.

**Comment by aksharp99** [comment]
var i;
var sum = 0;
for(i=process.argv[2],i<process.argv[2].length;i++) {
sum += Number(process.argv[i]);
}
console.log(sum);

^ above is my code. I get a
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/Users/aksharpatel/Desktop/nodetutorial/program.js:3:40)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

any ideas?

**Comment by lsta** [comment]
my solution works. but i don't think its 100% right.

I am trying to figure out how people know to start with i=2 in their for loop.

note: before I put the if condition in, i noticed that I would get "NaN" as a result. which appeared to be my script trying to add an invalid number to the loop. I don't understand why, 

**Solution that doesn't work and I don't understand why:**
```
var sum=0
for(i=0; i < process.argv.length; i++){
        sum+= Number(process.argv[i])
}
console.log(sum)
```
**Final solution:**
```
var sum=0
for(i=0; i < process.argv.length; i++){
    if(process.argv[i] > 0){
        sum+= Number(process.argv[i])
    }
  
}
console.log(sum)
```

**Textbook solution**
```
 var result = 0

    for (var i = 2; i < process.argv.length; i++) {
      result += Number(process.argv[i])
    }

    console.log(result)
```

**Comment by delaguilaluis** [comment]
Hi @lsta,
The solution starts the `for` loop at index `2`, because, as [the problem hints](https://github.com/workshopper/learnyounode/blob/master/exercises/baby_steps/problem.md) state,

> The `process` object has an `argv` property which is an array containing the complete command-line. i.e. `process.argv`.

So, if you run a script like:

```javascript
$ node program.js 1 2 3
```

Then, the `process.argv` array would contain:

```javascript
[ 'node', '/path/to/your/program.js', '1', '2', '3' ]
```

Now I'll try to explain each of the scenarios:
1. Returns `NaN` because creating a `Number` with a string as parameter that cannot be coerced to a number will result in `NaN`, and adding any number to `NaN` also results in `NaN`.

2. Your solution works because before creating a new `Number`, the `if`'s condintion is ignoring the cases where the value is not greater than 0, and `NaN` is not greater than 0.

3. The official solution starts the `for` loop at `2`, so the `process.execPath` value and the _path to the JavaScript file being executed_ are ignored.

More about `process.argv` [here](https://nodejs.org/docs/latest/api/process.html#process_process_argv).
