### ISSUE TITLE
In what order should I select and learn the tutorials and nodeschool.io

### ISSUE THREAD

**Issue by anuoluwapo** [nodeschool/discussions#1732]
In what order should I select and learn the tutorials and nodeschool.io
I just finished learning  javascripting

**Comment by riyadhalnur** [comment]
Personally, I would suggest finishing these first few modules 
![screen shot 2016-05-11 at 10 46 59 am](https://cloud.githubusercontent.com/assets/3457571/15170222/dc3ebca0-1765-11e6-8c0a-ef2a90867ed6.png)

After you're done with those, you can move on to the electives and as the name implies, they are electable. So it's up to you to choose the specific topics you want to learn in depth.

**Comment by anuoluwapo** [comment]
@ riyadhalnur, thanks alot i really appreciate. have even finish learning javascripting, but am still on scope chains and closures. almost done sha!
