### ISSUE TITLE
how-to-npm verify

### ISSUE THREAD

**Issue by adrianturcato** [nodeschool/discussions#1743]
- node version: v4.4.4
- npm version:  2.15.1
### Error output

```
killed":false,"code":1,"signal":null,"cmd":"C:\\Windows\\system32\\cmd.exe /s /c \"C:\\Program Files\\node.js\\npm.CMD --version\"
```
### My Code

``` js
how-to-npm verify
```

Just trying to do the npm workshop, but I got an error when trying to verify if npm is installed correctly. Any thouhgts on how to diagnose my issue with npm?

**Comment by dvirtz** [comment]
I managed to fix this locally be adding double quotes around `npm ` variable before calling `exec`:

`exec('"' + npm +'" --version'`
