### ISSUE TITLE
promise-it-wont-hurt: "Promise after promise" task not working

### ISSUE THREAD

**Issue by dasvineet** [nodeschool/discussions#1747]
- node version: v6.1.0
- npm version:  3.8.6
### Error output

```
 ✗ Expected execution time: 521±100ms. Submission execution time: 120ms.
```
### My Code

``` js
'use strict';

function first(){
    return Promise.resolve('SECRET VALUE');
}

function second(val){
    return Promise.resolve(val);
}

first().then(second).then(console.log);
```

**Comment by nicomf1982** [comment]
same problem
`✗ Expected execution time: 491±100ms. Submission execution time: 75ms.`

**Comment by MareikeTaeubner** [comment]
I have the same problem.
The task description is very confusing from the _"Return the promise..."_ part on. (At least for non native english speakers)

> Call first function in your program. first() will return a promise that
> will be fulfilled with a secret value.
> Call second with the fulfilled value of first. Return the promise returned
> by second in your onFulfilled callback.
> 
> Finally, print the fulfilled value of that new promise with console.log.

The error message I get from the verify tells me nothing about what I did wrong:

`? Expected execution time: 812±100ms. Submission execution time: 448ms.`

And there is no 'solved' example or even hints until I have finished this task - so I'm stuck completely.

**Comment by nicomf1982** [comment]
I found a solution , just add a setTimeout() , with 400 ms or more at the end. 

Bye

**Comment by MareikeTaeubner** [comment]
Thanks nicomf1982, that helped me to get a step further.

**Comment by adekbadek** [comment]
`first` and `second` and already defined - just use the functions and test with `promise-it-wont-hurt run <your-program>`

There is an [issue open on the workshopper repo](https://github.com/stevekane/promise-it-wont-hurt/issues/88) and a [corresponding PR](https://github.com/stevekane/promise-it-wont-hurt/pull/93), which clarifies it

**Comment by darylshy** [comment]
This worked for me. Instructions are very confusing btw..
**_`first().then(second).then(console.log);`_**

**Comment by JavierMendozaGomez** [comment]
thank you daryl

**Comment by shengnoyi** [comment]
This problem is really confusing.I got its offical solution by searching its sources file in node_modules folder.
─────────────────────────────
 'use strict';

 /* global first, second */

 var firstPromise = first();

 var secondPromise = firstPromise.then(function (val) {
   return second(val);
 });

 secondPromise.then(console.log);

 // As an alternative to the code above, ou could also do this:
 // first().then(second).then(console.log);


**So the problem is that the 'first' function and 'second' function are both not defined by user but as global funciton.**

**Comment by capozzic1** [comment]
Was very confused by this problem.
