### ISSUE TITLE
Fails on additional module file, despite aditional file with correct results

### ISSUE THREAD

**Issue by andymagill** [nodeschool/discussions#1752]
The test is failing on the 3rd criteria, use an additional module file. I definitely am using an additional file with module.exports and it seems to be processing the list properly. It seems like I am doing this according to the requirements. Any ideas why this is happening? 

* node version: 4.4.5
* npm version:  2.15.5

### output
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected

  ✓  Used asynchronous method: fs.readdir()

  ✗  Did not use an additional module file, you must require() a module to
  help solve this exercise
```

### original program
```
var filter_list = require('./6b.js');

var folder = process.argv[2];
var ext = process.argv[3];

filter_list(folder, ext, function(err, list) {

	if (err){
		return console.log(err);
	}
	else {
		return console.log(list);
	}
});
```

### module file
```
var fs = require('fs');
var path = require('path');

module.exports = function (folder, ext, callback) {

	fs.readdir(folder, function doneReading(err, list) {

		if (err){
			return callback(err);
		}
		else {
			var filtered_list = [];
			for(i=0; i<list.length; i++){

				if (path.extname(list[i]) == '.'+ext){
					filtered_list.push(list[i]);
				}
			}
			return callback(null, filtered_list);
		}
	});
}
```

**Comment by ishtiaque23** [comment]
It doesn't seem like the error message and the code you have shared are from the same attempt. May be its a modified version of the code.

Other than that, from the current state, I can say you have it almost right.

One change is required to make it work though and thats in the original program.

in the **else scope** of the **callback** method that you passed to **filter_list** you need to output the items individually:

```javascript
// you did:
return console.log(list);

//replace this with:
list.forEach(function (item) {
  console.log(item)
})
// or you can simply use the old school for loop and if that makes more sense to you
```

Let me know if that change solves your problem or not.

**Comment by andymagill** [comment]
You are right, ishtiaque23.  My sleep deprived mind was running the test on my code for the previous challenge. Running the challenge on the code I pasted above showed your suggested changes were indeed necessary. Thanks for the help!
