### ISSUE TITLE
javascripting - FOR LOOP - discrepancy between exercise and result

### ISSUE THREAD

**Issue by dloret** [nodeschool/discussions#1753]
Hello,

In the exercise description, we're asked to use a for loop by incrementing i to a limit of ten.
The variable total is also being incremented at each pass, so we get a result of 10.
When verifying the result, the code checker expects a result of 45... Why is that ?

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
  # PASS Your solution to FOR LOOP passed!  
   
  Here's the official solution in case you want to compare notes:  
   
 ─────────────────────────────────────────────────────────────────────────────  
   
 # THE TOTAL IS 45  

```

### My Code (I changed the limit to 45, to pass)
```js
  1 var total = 0;
  2 var limit = 45;  // when it's 10, the test is failed                                                                                                                                       
  3 
  4 for (var i = 0; i < limit; i++) {
  5     total++;
  6 }
  7 console.log(total);

```

**Comment by mappum** [comment]
The exercise is actually asking for something slightly different. Rather than incrementing `total` by 1 for each iteration, try incrementing by `i`. (0 + 1 + 2 + ... + 10)

**Comment by dloret** [comment]
Thanks, you're totally right. I read 1 instead of i... Several times!
Should have read once more.
Sorry, I close the issue.

**Comment by mappum** [comment]
Maybe we should open an issue or pull request on the javascripting repo about the text being easy to misinterpret. It could be reworded so others don't make this mistake in the future.

**Comment by dloret** [comment]
It is clear and I think reading carefully the specifications is part of
what's to be learned. What could be secured is to make sure nobody works
around the exercise the way I did :)
