### ISSUE TITLE
java 卡關求助幫忙

### ISSUE THREAD

**Issue by just123** [nodeschool/discussions#1754]
想請各位
如何利用使用者輸入一個3x3的陣列，並算出列的總和？
我一直卡關在如何讓使用者輸入3x3的陣列

範例：
input
1 2 3
4 5 6
7 8 9

output 
12 15 18

抱歉是新手剛上路認真研究學習，需要有人指導指引，麻煩各位高手幫幫忙，感謝🙏

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.
