### ISSUE TITLE
got connection error on http uppercase problem

### ISSUE THREAD

**Issue by VanishingDante** [nodeschool/discussions#1755]
below's my code
```
var http = require("http");

var server = http.createServer(null, (request, response) => {
    var text = "";
    request.on("data", (chunk) => {
        text += chunk;
    });
    request.on("end", () => {
        text = text.toUpperCase();
    });

    response.write(text);
});

server.listen(process.argv[2]);
```

can anyone tell me why i got this?
```
  ✗  Error connecting to [http://localhost:55497](http://localhost:55497):
  read ECONNRESET
```

**Comment by riyadhalnur** [comment]
Are you running the server? If you are, did it crash and exit?

**Comment by VanishingDante** [comment]
@riyadhalnur 
i don't know what u mean
i just run this command `learnyounode run ./program.js` and i got this error message

just now, i restarted my pc, and upgraded my node to version 6.2.
still got this.

os  is win10

**Comment by riyadhalnur** [comment]
Right, you need to provide the port the server will listen on when you run the program from the terminal - `learnyounode run ./program.js 3000`

**Comment by VanishingDante** [comment]
@riyadhalnur 
no use
and i think the `learnyounode run` will provide the port number.
the error message `✗  Error connecting to [http://localhost:55497](http://localhost:55497):` showed the port number used that time.
every time i run the command, the port number changes

**Comment by pankaj805** [comment]
Hi,

i checked your code. the client was not able hit the server with the port as there was issue with the way you created the server. I tried updating your code as follows and it worked.

Change this line 
var server = http.createServer(null, (request, response) => {
to
var server = http.createServer((request, response) => {

You shouldn't see the error which you were seeing earlier. But still there is another issue with the code for which it will fail the test.

As it is a asynchronous flow, the following line will get executed before the end event of the http request.

 response.write(text);

Do fix it. And let me know if this helped :+1:  Even i am new to node js. It will be a boost up :)

**Comment by VanishingDante** [comment]
@pankaj805 
i'm sorry that i didn't notice your comment.

i changed my code, and it got passed.
```
var http = require("http");

var server = http.createServer( (request, response) => {
    var text = "";
    request.on("data", (chunk) => {
        text += chunk;
    });
    request.on("end", () => {
        text = text.toUpperCase();
        response.write(text);
        response.end();
    });
});

server.listen(process.argv[2]);
```

You are right, it is a asynchronous flow, so the `response.write` function should be in the `request.on('end',() => {...})` block.
and the `response.end()` is necessary, or the request is not considered not complete .
So move the  `response.write`, and add `response.end()`

i'm not a native English speaker, not sure if there's something wrong with my grammer or some other things.

**Comment by pankaj805** [comment]
@VanishingDante 

No issues :) Your English is perfect to me at least. anyways javascript is the language here :) Glad my solution could help you :+1:  I guess you can close the issue now :)
