### ISSUE TITLE
Queenstown, New Zealand meetup

### ISSUE THREAD

**Issue by Sm00g15** [nodeschool/discussions#1759]
Hey,
I'm a Node.js noob and looking for some folks to meet up, talk code, and practice coding with. Anyone around here?

**Comment by SomeoneWeird** [comment]
You may want to go open an issue on @nodeschool/chapter-organizers too!

**Comment by rahmona-henry** [comment]
Hi @Sm00g15,

I am in Queenstown and fairly new to Node.js also Keen to meet up and talk code etc if you are still interested?

**Comment by Sm00g15** [comment]
yeah, totally down Rahmona. I'm a super noob, but super interested in learning a lot more about coding/programming/Node. When works best for you?

**Comment by Sm00g15** [comment]
Rahmona,

There's also a Queenstown Tech Group Meetup this Thursday that you should come to

**Comment by rahmona-henry** [comment]
Hi @Sm00g15,

If you are going to the Meetup - should I just meet you there?

**Comment by Sm00g15** [comment]
Rahmona,

Absolutely, that works for me. See you Thursday 

Best
Sean Magin

**Comment by rahmona-henry** [comment]
Super see you then:)

**Comment by rahmona-henry** [comment]
Hi Sean @Sm00g15 ,

How are you? How is the coding going?
Are you going to the Queenstown Tech Group Meetup this Thursday?

Rahmona

**Comment by Sm00g15** [comment]
Yooooo! I’m doing well, and I’ve coded a bit since then, i’ll tell you all about it at the meetup! How about you??! Any luck with finding work? Still been going hard?

Best,
Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by rahmona-henry** [comment]
@Sm00g15 Awesome - looking forward to hearing all about it at the Meetup!

Still no luck with finding work yet . I am having a casual job chat with a place on Thursday afternoon, not a formal interview - I will tell you how it goes on Thursday:) I have been doing some coding most days to keep my head in the game but it can be tough going by yourself!
