### ISSUE TITLE
Stream-Adventure HTTP-server, first line not printed out

### ISSUE THREAD

**Issue by micsandbricks** [nodeschool/discussions#1764]
Hi, I'm having some issues with the http-server assignment for stream-adventure. Most of the other issues I've seen on this board concern the problem with declaring a "through" variable outside the scope of the server callback function, resulting in "extra" text being printed out (see for example [https://github.com/nodeschool/discussions/issues/132](url)). My problem is that my program doesn't want to print out anything before the first newline. The same problem occurs when I use the solution [https://github.com/jeremy-w/node-stream-adventure-solutions/blob/master/http-server.js](url) code. I can tell that the method "queue" is used in the solution instead of "push" in my program, are they pretty much the same thing or am I missing something? Any help would be most appreciated.
- node version: 6.2.0
- npm version:  3.9.5
### Error output

```
TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
not ok 2 should be equal
  ---
    operator: equal
    expected: 'SLOUGHCHANGE\nIN\nTHE\nNIP\nOF\nA\nNAPPLE\nSOLONGAS\nWE\nCAN\n'
    actual:   'IN\nTHE\nNIP\nOF\nA\nNAPPLE\nSOLONGAS\nWE\nCAN\n'

```
### My Code

``` js
 var http = require('http')
var through = require('through2')

var port = process.argv[2];

var server = http.createServer( function (req, res) {
    if (req.method === 'POST') {
    req.pipe( through ( function (buffer, encoding, next) {
        this.push(buffer.toString().toUpperCase());
        next();
    })).pipe(res);
    }
});
server.listen(port);

```

**Comment by ishtiaque23** [comment]
You are extremely close!

To find the problem with yor code you need to have a look at the doc for **through2** module.

It takes 3 parameters. One is **options** which is not required for this challenge.  The other 2 are functions. One is for the **transformation** and the other one is for the **flush**. See details [here](https://github.com/rvagg/through2).

In your solution you already have the **transform function** in place.
```javascript
function (buffer, encoding, next) {
  this.push(buffer.toString().toUpperCase());
  next();
}
```

 All you need to do is provide the **flush function**. The **transform** actually help you to work on the current stream. The missing **flush** function is vital here as it will actually let the system know when the stream ends.

The description of this exercise has a pretty neat example of what you need to do. I am pasting it here for your convenience

```javascript
var through = require('through2');
process.stdin.pipe(through(write, end)).pipe(process.stdout);

function write (buf, _, next) {
  this.push(buf);
  next();
}
function end (done) {
  done();
}

//for you the 2nd line is actually:
req.pipe(through(write, end).pipe(res)
```

**Comment by ishtiaque23** [comment]
Just realized its a pretty old issue and probably the person posted already solved it. Still keeping my comment so it might help others who face similar issue.
