### ISSUE TITLE
Filtered LS

### ISSUE THREAD

**Issue by hayk94** [nodeschool/discussions#1768]
- node version: v6.2.0
- npm version:  3.8.9
### Error output

```
No error
```
### My Code

``` js
var fs = require('fs');
var path = require('path');
// var myPath = process.argv[2];
// var myExt = process.argv[3];
fs.readdir(process.argv[2], function callback(err,list) {
  for (var i = 0; i < list.length; i++) {
    if (process.argv[3]===path.extname(list[i])) {
      console.log(list[i]);
    }
  }
});

```

There are no errors. It just doesn't console log anything. But I don't understand why, please help me.

**Comment by ishtiaque23** [comment]
**path.extname** will return extension in this format: 
.txt
.md
.pdf etc.

Your argv[3] will receive values like 
txt
md
pdf etc.

Its a case of string mismatch.
