### ISSUE TITLE
how-to-npm adduser

### ISSUE THREAD

**Issue by 524119574** [nodeschool/discussions#1772]
- node version: v4.4.5
- npm version:  v3.10.2
### Error output

```
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "adduser"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.2
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:15443
npm ERR!     at Object.exports._errnoException (util.js:870:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:893:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:15443]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 15443 }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/newdirectory/npm-debug.log
```
### My Code

``` js
 npm adduser
```

**Comment by nexdrew** [comment]
@524119574 Does your `~/.npmrc` file point to `127.0.0.1:15443` by any chance? What if you try `npm config set registry https://registry.npmjs.org` and then `npm adduser`?

**Comment by 524119574** [comment]
@nexdrew Thank you for your help. But the question remains after `npm config set registry https://registry.npmjs.org`. I use "express vpn" to access cloud9, is that possible the problem is arised due to the VPN?

**Comment by Mycroft1891** [comment]
how-to-npm creates a local user not a real one. I had the same issue trying to adduser in the directory where I installed how-to-npm

If you take a look at the .npmrc file you will notice that it doesn't point to the official npm registry. It points to a local file in the how-to-npm module. This means that to create a user, you have to run:

how-to-npm
select exercise 2 Login (this lets you create a user locally) and go through the process.

This is the only way to login or adduser for this module. If you try it without the exercise, you will get an error. I tried to add it later when I had to publish it and it kept giving me your error too. I hope that helps.

**Comment by nl-x** [comment]
@Mycroft1891 Thanks! I understood that how-to-npm created a local webserver mimicing npmjs, but I wasn't able to figure out how to restart that server. Apparently you restart it by running exercise 2 again, like you stated.
