### ISSUE TITLE
Node.js User Geoup?  Southern Delaware / eastern Shore Maryland?

### ISSUE THREAD

**Issue by bethanybeachbum** [nodeschool/discussions#1774]
is there any interest out there in a User Group for Southern Delaware and Eastern Shore Maryland?

**Comment by wetherallCode** [comment]
What about South Jersey?

**Comment by bethanybeachbum** [comment]
Where in south jersey? 
It will probably be a two hour drive for me

Thank you,

Mark Brown
703-801-0055
