### ISSUE TITLE
"Ask Questions if Stuck" confusing to new users

### ISSUE THREAD

**Issue by dlindahl** [nodeschool/discussions#1775]
On the homepage, clicking "Ask Questions if Stuck" shows a GitHub login form if the user is not signed in. For new users that may not have heard of Git/GitHub, this is confusing, especially since they are already in need of help.

It may help by linking to a static page with some tips on how to self-solve common problems and, if still needed, list the GitHub account requirement and provide help on how to sign up _for free_ before linking to `/issues/new`.

**Comment by sathishakula** [comment]
[a1.txt](https://github.com/nodeschool/discussions/files/353732/a1.txt)
I tried to add a router to the first AS which i created when i addedd the router R1 there was no ping between the two routers R0 and R1 when i tried to ping between them and even a host which i added to the router R1 wasnt able to ping the oother hosts
