### ISSUE TITLE
http colllect: using Bacon.js

### ISSUE THREAD

**Issue by nogo10** [nodeschool/discussions#1778]
* node version: v4.1.1
* npm version:  2.14.4

### Error output

It might be somewhat overkill but Im trying to use Bacon.js FRP to act as buffer/ stream processor for the http req response.. It works.. being able to log sequentially the characters. Problem is when I use proven Bacon.js fold() function to concat the resulting stream it logs a empty string.. 

Is the problem linked to learnyoumode testing framework? Is the testing framework capable of handling other buffer libs other than bl and concat? 
```
 // copy your error output here
```

### My Code
```js
var http = require("http");
var bacon = require("baconjs").Bacon;
var count = 0;
var the_string = "";
var url = "http://baconjs.github.io/api.html" ;//process.argv[2];
var read = bacon.fromBinder(function(sink) {
 http.get(url, function(res) {
  res.setEncoding('utf8');
  res.on('data', function(chunk) {
   sink(chunk);
  });
 });
});

var concatenated = read.fold("", function(a,b) {a+b;
});

concatenated.log("concatenated");
```

**Comment by omahlama** [comment]
The problem you have is that the stream you create with `fromBinder` never ends. That means that the `concatenated` stream never gets a value. You should add:

```
res.on('end', function() {
  sink(new Bacon.End())
});
```

**Comment by nogo10** [comment]
The unit test returns  
`"concatenated undefined"`
Somehow the data is getting through..

 to check I ran the onValue()
The unit test returns:
`(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.`
Trace outputs sucessive lines each with new char until full line of data is logged:
`"ipsum bla...bla"`

**Comment by nogo10** [comment]
Bacon.js can be a great buffer: I was missing the `return` in the statement
var concatenated = read.fold("", function(a,b) { **return** a+b;
});
