### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by lkkk123** [nodeschool/discussions#1779]
[root@iZ94pts9yarZ electron-quick-start]# npm start

> electron-quick-start@1.0.0 start /usr/local/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/electron-quick-start
> electron

/usr/local/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/electron-quick-start/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

npm ERR! Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! argv "/usr/local/node-v6.2.2-linux-x64/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/electron-quick-start/npm-debug.log

**Comment by Mycroft1891** [comment]
Could you tell us what you tried to do ?
What are you trying to install ?
