### ISSUE TITLE
transferring progress

### ISSUE THREAD

**Issue by jrobinson0** [nodeschool/discussions#1781]
is there any way to transfer progress from the nodeschool modules from one PC to another?

Thanks!

**Comment by riyadhalnur** [comment]
Exercise progress is stored in `~/.config/<name-of-module>/`. You can copy this folder between machines to pick up where you left off. Let me know if that helps. Cheers.

**Comment by swedishpotato** [comment]
Is there a simple way of changing the location of this file? We want to store this on the users profile (windows), not on the local C drive, which gets wiped on every shutdown.
