### ISSUE TITLE
Parse Error - http File Server (exercise 11)

### ISSUE THREAD

**Issue by indusninja** [nodeschool/discussions#1787]
I have a weird problem. This code runs fine and gives the expected output if I run it through node. But when I try to verify or run through learnyounode, it shows a parse error.

Running: node p11b.js 20354 program1.js

and directing my browser to http://localhost:20354 gives me the output of that file.

* node version: v4.4.5
* npm version:  2.15.5
### Error output
```
learnyounode run p11b.js
  ✗  Error connecting to [http://localhost:46624](http://localhost:46624):
  Parse Error
```

### My Code
```js
var net = require('net');
var port = process.argv[2];
var filename = process.argv[3];

var server = net.createServer(function (socket) {
	var fs = require('fs');
	var readStream = fs.createReadStream(filename);
	readStream.pipe(socket);
});

server.listen(port);
```

**Comment by riyadhalnur** [comment]
From the description above, you are listening on port 20354 but the program is trying to connect to port 46624.

**Comment by indusninja** [comment]
_**Running: node p11b.js 20354 program1.js
and directing my browser to http://localhost:20354 gives me the output of that file.**_

That process works when I run my program directly via node, and test it.

This error happens
```
  ✗  Error connecting to [http://localhost:46624](http://localhost:46624):
  Parse Error
```

when I run via learnyounode
```
learnyounode run p11b.js
```

**Comment by riyadhalnur** [comment]
Yes, during verification of the program, it tries to connect over port 46624. Having said that, the reason for mis-match is that you're using the `net` module instead of the `http` module. Your code would become - 
```js
var http = require('http');
var port = process.argv[2];
var filename = process.argv[3];

var server = http.createServer(function (req, res) {
    var fs = require('fs');
    res.writeHead(200, { 'content-type': 'text/plain' });
    var readStream = fs.createReadStream(filename);
    readStream.pipe(res);
});

server.listen(port);
```

**Comment by indusninja** [comment]
Thanx, that sounds more plausible. I'll test it tonight.

**Comment by riyadhalnur** [comment]
Haha, no worries man. I'm glad the problem's solved. Cheers
