### ISSUE TITLE
Stream Adventure - HTTP CLIENT - Alternate Approach?

### ISSUE THREAD

**Issue by luiscvega** [nodeschool/discussions#179]
Hi everyone!

I've solved this already but I wanted try it without using the `request` module.

So my thinking is to use the `http.request(options)` built in to the `http` module.

Here's my attempt:

```
var http = require("http")

var request = http.request({
  hostname: "localhost",
  port: 8000,
  method: "POST"
})

process.stdin.pipe(request).pipe(process.stdout)
```
I did a `run` and it's just waiting, doing nothing. I did a `verify` and everything is `null`.

Just wanted to check if I'm missing something. Am I supposed to end the `res` once the `request` stream has been written to?

**Comment by Sequoia** [comment]
Hi @L2L2L! Still working on this or is the issue resolved?

**Comment by JonathanMH** [comment]
This seems to be an issue with Spotify, because they use port `8099`

```
% netstat -tulpn | grep :8099  
tcp        0      0 127.0.0.1:8099          0.0.0.0:*               LISTEN      20605/spotify   
```
