### ISSUE TITLE
make it modular question

### ISSUE THREAD

**Issue by svailla4** [nodeschool/discussions#1790]
Hi I have no idea on how to approach this question. I guess what confuses me is the callback function, and on how I'm suppose to program that on both the main file and modular one.

this is what I tried to do.

```

//Main file
`var modular = require('./modular.js')

console.log(printfile(process.argv[2], process.argv[3], function(err, data)));`

//side File (Modular.js)

`"use strict";

var fs = require('fs');
var path = require('path');

module.exports = function printFile(dirName, extension, callback){

    fs.readdir(dirName, 'utf8', callback(err, files){
        if(err) throw err;

var ar =[];

        files.forEach(function(value){
            if(path.extname(value) == extension)
                ar.push(value);

        });
return ar;

    });

}


`
```

**Comment by Mycroft1891** [comment]
In your main file you are not handling the output.
You are wrote: 

`console.log(printfile(process.argv[2], process.argv[3], function(err, data)));`

But your callback function is not doing anything with the data once it receives it.
Your callback should look something like this:

```
function callback (err, data) {
	if (err) return console.error(err)

	data.forEach(function(i){
		console.log(i)
	})
}

printFile(dirName, extension, callback)
```

In your module you have to take care of the missing '.' 
The request will look something like this:

`node main.js /foo/bar txt`

Notice that txt does not have a leading '.' which means that you have to add it. 

```
        files.forEach(function(value){
            if(path.extname(value) == '.' + extension)   // add dot to the extension
                ar.push(value);

        });
```

Also there is no need to create an array and return it. You can simply return the results using the filter function:

var item = files.filter(function(i) {                         // filter returns each file with extension name
      return ext.extname(i) === '.' + extension       // extname grabs that extension to compare
    })

return callback(null, item)


Remember that your module only takes data, processes it and returns it back to your main file. 
In your main file you have to receive it and do something with it. 

I hope this helps ^^

**Comment by jpuriol** [comment]
I am doing the same workshop and I don't understand what I have to do. 

So far what I have got is that are two files:

Here is my first file `main.js`
```
var module = require("./module.js");

function callback (err, data) 
{
    if (err) return console.error(err);

    data.forEach(function(i)
    {
        console.log(i)
    });
}

console.log(module.printList(process.argv[2], process.argv[3], callback));
```
And the other file `module.js`
```
const fs = require('fs');
const path = require('path');

module.exports = function imprimirLista (nombreDir, ext, callback)
{
    fs.readdir(folder, function (err, files)
    {
        if (err) return console.error(err);
        var filtered = files.filter(function(i) 
        {
            return path.extname(i) === '.' + ext;
        });
        
        return callback(null, filtered);
    }
}
```

This doesn't work but I not sure how to fix it, because I am not sure what it should do.

**Comment by ishtiaque23** [comment]
@jpuriol : You are on the right track. Some minor issues though.

## module.js
**One Syntax error** :

In your **module.js** you are missing a closing **)** in the 2nd last line. Thats the closing parenthesis for **fs.readdir**. So the last 3 lines should look like this:
```javascript
        return callback(null, filtered);
    }) // this is the missing part
}
```

Two more issues in the **module.js**

```javascript
module.exports = function imprimirLista (nombreDir, ext, callback)
```
You don't need to give a function name here. Let it be an anonymous function. Like this:
```javascript
module.exports = function (nombreDir, ext, callback)
```

Now, in this following line:
```javascript
fs.readdir(folder, function (err, files)
```
You are expecting a variable called **folder** but you are not passing any of that name. You are actually passing another variable **nombreDir**, which is actually the variable expected here.
```javascript
fs.readdir(nombreDir, function (err, files)
```

Now as your **module.js** is in a better state, lets focus on **main.js**

## main.js

Remember that we exported a nameless function from **module.js**?

So in the first line lets not call it module anymore, you can call it printList or imprimirLista(whichever you prefer)

```javascript
var module = require("./module.js");
//replace this line with the following:
var printList = require("./module.js");
```
The callback function you have defined is spot on. Nothing to change there. Just for your help, remember that this function already printing out(or **console.log**) the results.

Now the last problem to tackle:

```javascript
console.log(module.printList(process.argv[2], process.argv[3], callback));
```
1. You don't need to **console.log()** this. Just executing the function will do. **callback** function will take care of the **console.log()** part.
2. As you remember we returned an anonymous function and then stored it in a variable called **printList**. So this line should be replaced with the following:
```javascript
printList(process.argv[2], process.argv[3], callback)
```

This will solve your problem. Let me know whether it worked or not.

Also, if you need any more clarification about the solution I will be glad to help.

**Comment by geverl** [comment]
file.js:
'use strict';

module.exports = (dir, ext, callback) => {
	let fs = require('fs'), path = require('path');
	fs.readdir(dir, (err, files) => {
		if (err) return callback(err);
		let arr = files.filter((file) => {
			return path.extname(file) === '.' + process.argv[3];
		});
		callback(null, arr);
	});
}

ex6.js:
'use strict';

let file = require('./file');
file(process.argv[2], process.argv[3], (err, data) => {
	if (err) console.log(err);
	else {
		for (const FILE of data) console.log(FILE);
	}
})

learnyounode verify ex6.js gives:
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"

but does not confirm the exercise as completed.
Why is that?
