### ISSUE TITLE
New Chapter for Nodeschool Abuja

### ISSUE THREAD

**Issue by ldbraun** [nodeschool/discussions#1794]
Hi, I would like to start a nodeschool chapter for [Abuja Nigeria]. I am [@BraunBoniface] on twitter, [Braun Boniface [https://ng.linkedin.com/in/braun-boniface-81653189]] on LinkedIn and work at Okoi Studios as CTO/CTE on Javascript and Web Technology and development. I will be co-organizing this chapter with [Oluchi Braun, James Ugochukwu]. I have been using Node.js for 2 years since 2014 and would like to help others learn and get to use as well.

**Comment by riyadhalnur** [comment]
Hi @ldbraun, would you opening an issue here at https://github.com/nodeschool/organizers/issues and we can get your started on making an awesome new chapter for Abuja 😃
