### ISSUE TITLE
Abuja

### ISSUE THREAD

**Issue by ldbraun** [nodeschool/discussions#1795]
Hi, I would like to start a nodeschool chapter for [Abuja Nigeria]. I am [@BraunBoniface] on twitter, [Braun Boniface [https://ng.linkedin.com/in/braun-boniface-81653189]] on LinkedIn and work at Okoi Studios as CTO/CTE on Javascript and Web Technology and development. I will be co-organizing this chapter with [Oluchi Braun, James Ugochukwu]. I have been using Node.js for 2 years since 2014 and would like to help others learn and get to use as well.

**Comment by riyadhalnur** [comment]
Duplicate of #1794. Closing.

**Comment by ldbraun** [comment]
Hello @riyadhalnur, 
thank you for your response, but don't understand. does this mean I have to still wait for the chapter request to e approved?

kind regards.

**Comment by riyadhalnur** [comment]
Hi @ldbraun,

Yes, you still have to wait but since you've already opened an issue, I closed this one. You just need to open one issue to request a new chapter. Hope that explains things. 😃 

Cheers

**Comment by ldbraun** [comment]
Yes. Thanks @riyadhalnur.
