### ISSUE TITLE
Elementary-electron Hello World app.js

### ISSUE THREAD

**Issue by doylet** [nodeschool/discussions#1796]
* node version: 4.2.4
* npm version:  2.14.12

Following the Hello World exercise on Elementary-Electron, when run ` elementary-electron verify`, the app is verified but the exercise is incomplete as index.js is not available?

### Error output
```bash
  Checking Requirements:  
   
   » index.js [?]                                                                
   » app.js ✔                                                                    
   
  FAIL!  
```

### My Code
```js
// app.js

var electron = require('electron')

electron.app.on('ready', function() {
	var mainWindow = new electron.BrowserWindow({width: 600, height: 800})
	mainWindow.loadURL('file://' + __dirname + '/index.html')
});
```
```html
<!-- index.html -->

<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<h1>Hello World</h1>
</body>
</html>
```
Any ideas on the source of the problem? I cannot progress with the module. I notice on the Elementary-Electron repo there is an index.js, however this is not covered by the workshop.

**Comment by doylet** [comment]
Created a pseudo index.js

**Comment by JacobAMason** [comment]
Probably shouldn't close this if it's still a problem, even if there is a workaround.
