### ISSUE TITLE
Shasum check failed  - Javascripting 

### ISSUE THREAD

**Issue by anoopd** [nodeschool/discussions#1797]
* node version: <v6.2.2>
* npm version:  <3.9.6>

### Error output
```
 npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/Users/anoopd/.npm-packages/bin/npm" "install" "-g" "javascripting"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.6

npm ERR! shasum check failed for /var/folders/l8/wdgm3d_s1jg3kf3n5hpjn7180000gn/T/npm-1048-2d425788/registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
npm ERR! Expected: f31fb59ebb18e21e611ca16b243ea040c9bd57bc
npm ERR! Actual:   78a53b5719978aa0370d32beb2647aed4ab5432c
npm ERR! From:     http://registry.npmjs.org/javascripting/-/javascripting-2.6.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anoopd/npm-debug.log
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Looks like a network problem. The download is getting cut off and NPM is not able to download the package properly. Could you try trying again? Is this issue also present for other npm installs?

**Comment by anoopd** [comment]
@riyadhalnur  Thank you for the quick response . I tried it twice ( will try again ) and is getting the same error . This issue is not present for other packages

**Comment by riyadhalnur** [comment]
Let me check as well on my machine. Getting back to you in a bit.

**Comment by anoopd** [comment]
No need  ....... !!! it got installed  !!

**Comment by anoopd** [comment]
Sorry for wasting your time  ....... what should i do now to get this issue resolved ?

**Comment by riyadhalnur** [comment]
Awesome!

**Comment by riyadhalnur** [comment]
@anoopd Closed the issue. Issue resolved
