### ISSUE TITLE
BABY STEPS - Not working right

### ISSUE THREAD

**Issue by yedlahs** [nodeschool/discussions#18]
Here is  my code:

``` js
var result = 0;

for (var i = 2; i < process.argv.length; i++) {
    result = result + Number(process.argv[i]);
}

console.log(result);
```

This works fine with "node add.js". But if I use "learnyounode verify add.js 12 34", I get some weird errors. Is there a bug in the BABY STEPS challenge?

**Comment by koushik72** [comment]
If anyone has problem with this test, please remove the first two lines of codes which are
```
console.log('HELLOW WORLD);
console.log(process.argv);
```

and it will solve the problem.
