### ISSUE TITLE
learnyounode verify Time Server does not work

### ISSUE THREAD

**Issue by hainguyen86** [nodeschool/discussions#1800]
* node version: v4.4.7
* npm version:  2.15.8

### Error output
```
 Nothing happen
```

### My Code
```js
 var argv = process.argv.slice(2);
var port = argv[0].toString();

var net = require('net');
var strftime = require('strftime')

var server = net.createServer(function (socket) {
    socket.on('data', function (data) {
        socket.write(strftime('%F %H:%M') + '\n\n');
        socket.end();
    });
});

server.listen(port);
```

When I run this command: learnyounode verify learnsocket.js
I don't see any process :(

**Comment by ishtiaque23** [comment]
According to the Problem given in this exercise: you need to create a server that will listen to a port for a socket connection. When that socket connection become active, it should return the time in that format.

```javascript
var server = net.createServer(function (socket) {
    socket.on('data', function (data) {
        socket.write(strftime('%F %H:%M') + '\n\n');
        socket.end();
    });
});
```

Here you just need to do the **socket.write()** and **socket.end()** stuff. Get rid of the **socket.on** wrapper

You are not expecting any incoming data from the connected socket. So you need not to listen to it. 

The way you have written your code, the algorithm for it is like:
1. Create Server
2. Listen to specific port
3. Waiting for connection
4. On Connection, wait for incoming data
  1. On receiving data, write back that time string to socket
  2. End connection

So In your case the timeserver get stuck in a never ending waiting state on step 4.

But in reality the expected algorithm is:
1. Create Server
2. Listen to specific port
3. Waiting for connection
  1. On Connection write back that time string to socket
  2. End connection

Even after doing this change you might face another problem that resides in your code. The string you are writing back to socket should have a single end of line **\n**, you have **\n\n** right now.

Let me know if these changes solves your problem.

**Comment by hainguyen86** [comment]
thanks for your feedback @ishtiaque23,
but my problem is learnyounode does not have any process when I run the command:
`learnyounode verify learnsocket.js`

I tested my code, It create a server, listened port that I provide and print correctly datetime string on the browser.

I don't know why learnyounode cannot run it.

**Comment by ldbraun** [comment]
have you tried to run it with "node learnsocket.js"? @hainguyen86 
note that the surrounding enclosing quote is not part of the command.

**Comment by hainguyen86** [comment]
@ldbraun , sure
let's run `node learnsocket.js 12349`
then go to browser open this url: http://127.0.0.1: 12349

you will see something like this on your browser:
`2016-07-19 15:28`

**Comment by ishtiaque23** [comment]
@hainguyen86 : Please share your updated code(the changes I have suggested) here.

**Comment by ishtiaque23** [comment]
FYI, to simply run your code you can use 
```
learnyounde run learnsocket.js
```
The learnyounode itself will provide the command line arguments in its own(the one you are doing manually when running **node learnsocket.js**.

And to verify you can use the one you are already familiar with
```
learnyounode verify learnsocket.js
```

**Comment by ldbraun** [comment]
I just replicated your code above @hainguyen86 and made the corrections @riyadhalnur provided and ran it with "learnyounode run learnsocket.js" and it ran.

even if you should create and empty file and run it with learnyounode it will run. except, you are having a code error which you'll definitely be notified by the exception thrown.

go through your code again and implement the corrections above by @riyadhalnur  and make sure to check you system that you have the correct file permissions and run it again.

**Comment by hainguyen86** [comment]
thanks @ldbraun, @ishtiaque23 so much!
there are my latest codes :
`var argv = process.argv.slice(2);
var port = argv[0].toString();

var net = require('net');
var strftime = require('strftime')

var server = net.createServer();

server.on('connection', function (socket) {
    socket.write(strftime('%F %H:%M') + '\n');
    socket.end();
});

server.listen(port);
`

It passed learnyounode verification well.
Now I know learnyounode verify also on our algorithm not just the result.
