### ISSUE TITLE
[TIME SERVER]why do we need the '\n'

### ISSUE THREAD

**Issue by leo481** [nodeschool/discussions#1807]
###  Code
```js
var net = require('net')

function zeroFill(i) {
  return (i < 10 ? '0' : '') + i
}

function now () {
  var d = new Date()
  return d.getFullYear() + '-'
    + zeroFill(d.getMonth() + 1) + '-'
    + zeroFill(d.getDate()) + ' '
    + zeroFill(d.getHours()) + ':'
    + zeroFill(d.getMinutes())
}

var server = net.createServer(function (socket) {
  socket.end(now() + '\n')
})

server.listen(Number(process.argv[2]))
})
```

###Problem

If I remove the '\n',I can't get through the  #practise

**Comment by riyadhalnur** [comment]
The `\n` is a newline character. It tells the console to place a newline after printing the string so anything that comes after is printed on a new line and not on the same line as the string you printed. It's mostly a formatting thing and the exercise checks for that to pass. I hope that helps. 😃

**Comment by leo481** [comment]
@riyadhalnur 
It helps me a lot,thx.
