### ISSUE TITLE
How to deploy Node.js with mongo on ec2 instance

### ISSUE THREAD

**Issue by rishabh03** [nodeschool/discussions#1808]
please help me in deploying the node.js application with mongo db on ec2 instance. I am not able to find the way  how to upload the node.js project on server. i am new in node.

Pls Help me.

**Comment by xtuc** [comment]
Did you try deploying your application with EB (https://aws.amazon.com/fr/elasticbeanstalk) ?

There is no managed MongoDB in AWS. Instead, you can use EC2 container service to simply deploy a MongoDB server (https://hub.docker.com/r/tutum/mongodb).

**Comment by riyadhalnur** [comment]
The AWS Marketplace have ready-to-go images. [This](https://aws.amazon.com/marketplace/pp/B00NO1HJ56?qid=1469249205633&sr=0-1&ref_=srh_res_product_title) one comes with the MEAN stack installed. You can try that.
