### ISSUE TITLE
fifth problem. Learyounode

### ISSUE THREAD

**Issue by aurorekha** [nodeschool/discussions#1811]
- node version: <run "node -v" in you terminal and replace this>
- npm version:  <run "npm -v" in you terminal and replace this>
### Error output

```
 // copy your error output here
```

fs.js:803
  binding.readdir(pathModule._makeLong(path), req);
ypeError: path must be a string
    at TypeError (native)
    at Object.fs.readdir (fs.js:803:11)
    at Object.<anonymous> (/Users/rbhagavatula/Desktop/learnyounode/filtered.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
### My Code

``` js
 // copy your code here
const fs = require('fs');
const path = require('path');


var readDir = fs.readdir(process.argv,function callback(err, list) {
      for (var i = 2; i < list.length; i++);
});

console.log(readDir);

```

hello there

I just want to read first what's in my file. I can't even get that started.
Thank you for help in advance.

**Comment by ishtiaque23** [comment]
This code is incomplete and already contains few errors.

1. **fs.readdir()** is an asynchronous function which returns its result in the **callback**. So, trying to store value in the variable **readDir** will not work.
2. The **for loop** you have written does nothing.
3. You didn't even reach the extension based filtering of the file list.

The complete instruction of the exercise is given in the **learnyounode** program. Yet I will explain it here and provide you some guideline to attack this problem.

## The program:
* Write a Program that takes 2 command line arguments
* First argument will be a path to a directory
```javascript
process.argv[2]
```
* Second argument will be a file extension(like txt, doc, mp4).
```javascript
process.argv[3]
```
* You will have to first read the directory. Use **fs.readdir()** like you are using already.
* fs.readdir() is an asynchronous function, it will return the result in the parameter **list** of the callback function.
```javascript
// sample content of the list:
['readme.txt', 'changelog.md', 'notes.txt', 'resume.doc']
// as you can see it will be an array of filenames contained in that directory
```
* Note that all you are going to do will take place inside this **callback** function. 
```javascript
var fs = require('fs');
fs.readdir(pathToDirectory, function (err, list) {
// Everything goes here
})
// in our case pathToDirectory is process.argv[2]
```
* Inside the **callback**, write a **for loop** which will go through each of the filename in the array **list**
```javascript
for (var i = 0; i < list.length; i++) {
  // the code that you will apply to each of the list[i] will go here
}
```
* There should be an **if statement** inside the **for loop**. This **if statement** will check if the filename contains the specific extension provided in the 2nd argument(mentioned in step 3)
```javascript
if (condition) {
 // some statement. It will be executed only and only if the condition is met.
}
/* Here is an example
if (path.extname(list[i] === '.' + process.argv[3]) {
  console.log(list[i])
}
*/
```
* You need to use **path.extname()** method to do so. **path.extname()** takes a filename and return its extension
```javascript
var path = require('path');
var myDummyFileName = 'demo.txt';
var extension = path.extname(myDummyFileName);
console.log(extension);
// this will print: .txt
```
* So you will need to match this with the extension provided in **process.argv[3]**
* if the condition matches, then you will **console.log()** that filename.
* One bonus hint about the **if condition** extension will be provided like "txt" but path.extname() will return ".txt". You need to keep that in mind and compare it properly.

## Special Notes:
* Whenever you want to test your code, you should run the following command
```
learnyounode run yourfilename.js
```
* Notice that you don't need to pass the 2 arguments in this command. The **learnyounode** will take care of it. but you need to make sure your code does use these arguments.
```
//it will actually run the following command:
node yourfilename.js /path/to/directory txt 
```
* Expected result: (these are just example.It assumes that the extension passed was "txt")
```
file1.txt
file2.txt
file3.txt
```
* Once you are confident with your solution and getting similar output, you should submit your solution by running
```
learnyounode verify yourfilename.js
```
## Final Thought:
Follow the instruction and play around it. Try to understand each step. Let me know if its still unclear.

**Comment by KenpoJ** [comment]
I'm having the same issue. I tried to follow your instructions and have this code:

```
var fs = require('fs');
var path = require('path');
var name = process.argv[2];
var ext = process.argv[3];

fs.readdir(name, function(err, list) {
	for(i = 0; i < list; i++) {
		if(path.extname(list[i]) === '.' + ext) {
			console.log(list[i]);
		} else {
			console.log('Nothing');
		}
	}
});
```

The problem is that there is nothing returned. My guess is that the readdir() is not being initiated, but I'm not sure how to do that. In the previous exercise I was able to put the fs.readFile() into a variable and log that variable. That doesn't seem to work with this exercise.
