### ISSUE TITLE
-bash: learnyounode: command not found

### ISSUE THREAD

**Issue by Sonia-H** [nodeschool/discussions#1812]
- node version: v6.2.2
- npm version:  3.9.5

Hi,

I'm using mac. I typed this command to install learnyounode: _**sudo npm install -g learnyounode**_; it looks like the installation was a success that the result shown in the terminal.
**/Users/SONIA/.npm-global/bin/learnyounode -> /Users/SONIA/.npm-global/lib/node_modules/learnyounode/bin/learnyounode
/Users/SONIA/.npm-global/lib
└── learnyounode@3.5.3**

But, after I typed **_learnyounode_**, the terminal return me this. **-bash: learnyounode: command not found**

Please help and thanks for viewing this issue.

**Comment by nharrisanalyst** [comment]
I am getting the same error

**Comment by mariothiel** [comment]
I am having this issue on ubuntu for windows. Mine says: /usr/bin/env: node: File or Folder could not be found
