### ISSUE TITLE
How to move to next practise

### ISSUE THREAD

**Issue by leo481** [nodeschool/discussions#1814]
- operation system: windows 10

It seems like I can't move to next practise with cmd or any other bash in windows 10.I am now stuck in practise 1 which is completed

**Comment by riyadhalnur** [comment]
Discussed here #1641. You can use arrow keys to move between chapters.

**Comment by Mycroft1891** [comment]
which workshop are you working on ?
Did you type the workshops name to launch it (again)?
You have to launch it every time you complete a lesson.
