### ISSUE TITLE
Add instructions to install Node as a pre-req to workshoppers?

### ISSUE THREAD

**Issue by btamayo** [nodeschool/discussions#1816]
Sometimes the workshoppers presume you installed Node and won't add "Install Node" as a first step, and sometimes they do. Sometimes they prefix their instructions with `sudo`, and sometimes they don't (resulting in access errors for the learners).

Would it be better to have instructions on the site or the READMEs on how to install Node using `nvm` or `n`, so that the learners can start off using similar Node installs and envs? Also, it eliminates the need to use `sudo` in the workshoppers, which seems like a dangerous thing to do, especially for learners that are unfamiliar with that command.

**Comment by riyadhalnur** [comment]
Hi @btamayo, thanks for the suggestion. We already have a set of suggestions for that [here](https://github.com/nodeschool/discussions/wiki/Installation-suggestions). Maybe we could integrate it into the NodeSchool homepage to make it more visible?

**Comment by btamayo** [comment]
@riyadhalnur Yeah, I think that the instructions need to be on the NodeSchool homepage since most people go there instead of GitHub.

Also, the instructions as they're posted right now still require using `sudo`, which is why I suggested we should move to recommend installing via [`nvm`](https://github.com/creationix/nvm) or `n`, or `brew` by default.

If you need me to write up instructions I can do so. :)

**Comment by riyadhalnur** [comment]
@btamayo Yes, definitely. That would be great. You can add instructions to install node using `nvm` on this [wiki](https://github.com/nodeschool/discussions/wiki/Installation-suggestions) page. 😃
