### ISSUE TITLE
Make it Modular Exercise 6 - not processing err

### ISSUE THREAD

**Issue by Trevash** [nodeschool/discussions#1817]
So my problem is that it doesn't seem to process err when it is testing to see if it will pass back an error.

My module is:

``` js
var fs = require('fs');
var path = require('path');

module.exports = function(arg1,arg2,callback) {
    var array = [];
    fs.readdir(arg1,arg2, function(err,list) {
        if (err) 
        {
            return callback(err, null);
        }
        for (var i = 0; i < list.length; i++) 
        {
            if (path.extname(list[i]) === "." + arg2) 
            {
                array.push(list[i]);
            }
        }
        return callback(null,array);
    });
};  
```

And this is my program for reference:

``` js
var arg1 = process.argv[2];
var arg2 = process.argv[3];
var module = require('./myModule');

module(arg1,arg2,function(err,array)
{
    if(err) {
        console.log(err);
    }
    for (var i = 0; i < array.length; i++) {
        console.log(array[i]);
    }
});
```

This is the error that i've been experiencing, and I can't figure out what is different:

> Your additional module file [myModule.js] does not appear to pass back  
>  an error received from fs.readdir(). Use the following idiomatic Node.js  
>  pattern inside your callback to fs.readdir(): if (err) return  
>  callback(err)

**Comment by ishtiaque23** [comment]
I was unable to get the exact error this code was suppose to produce. Hence I assume the code you have shared here and the error code source are not the same.

There is one bug in your shared code though. You messed up one function signature:

```javascript
//myModule file

// the fs.readdir has 2 arguments: a directory name string and a callback function
fs.readdire(dirName, someCallbackFunction)

//But your code says:
fs.readdir(arg1,arg2, function(err,list) {
```
## Solution:
```javascript
//correct code based on your approach:
fs.readdir(arg1, function(err,list) {
```
This one change allowed the code to run correctly.

**Comment by Trevash** [comment]
Thanks!
