### ISSUE TITLE
Make it Modular meltdown

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#1820]
* node version: v0.12.7
* npm version:  2.11.3

### Error output
```
 // Haven't gotten that far.
```

### My Code
// mymodule.js
var fs = require('fs');
var path = require('path');

module.export = function listFiles (dirName, fileExt, callback) {
  fs.readdir(dirName, callback(err, files) {
    
  }

```I have no idea how to even start this problem. I'm not sure if this is even the right way to begin. I'm so lost. There was so much more direction (links to supporting web sites) in the previous challenges. And this one is like figure all this out with no help.

**Comment by wetherallCode** [comment]
I've updated my module.js:

var fs = require('fs');
var path = require('path');

module.export = function(dirName, fileExt, callback) {
  fs.readdir(dirName, function(err, files) {
    if (err) {
      return callback(err)
    }
    for (var i = 0; i < files.length; i += 1) {
      if (path.extname(files[i]) === "." + fileExt) {
        return files;
      }
  });

};

I'm sure this is wrong. Also I don't understand how to go about coding the original program. Please help me.

**Comment by marinintim** [comment]
Hi @wetherallCode!

First, minor one: it's `module.exports`, not `module.export`.

The main theme to learn here is that when you go callback, you can't go back. You can't `return` value directly, you have to provide it by calling back via callback.

**Comment by wetherallCode** [comment]
@marinintim I got it working. Thanks. I also used a you tube video and another discussion thread, but once I got a workable answer, I played around with node school's answer and the other various answers to make my answer a little better. Again, thanks for the help.
