### ISSUE TITLE
HTTP Client

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#1822]
Is there a reason that logging the data received from the response object is any better or worse (or it doesn't matter) than using the setEncoding('utf8') method? 

My Version:

var http = require('http');
var url = process.argv[2];

http.get(url, function (response) {
  response.on('data', function(data) {
    **console.log(data.toString());**
  });
});

Node School's version:

var http = require('http')

   http.get(process.argv[2], function (response) {
     **response.setEncoding('utf8')**
     response.on('data', console.log)
     response.on('error', console.error)
   })

**Comment by venkateshmurugan** [comment]
I am trying to run this exercise. I see the argument http://localhost:51108 is not running in my machine and it retunrs 404 error. Is there any setup that I missed?
