### ISSUE TITLE
My date.getMonth() is off???

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#1826]
For some reason, my month is off by one month. When I run the program, the month is July, but it's actually August. Whats up with this?
### My Code

``` js
var net = require('net');
var date = new Date();

var server = net.createServer(function (socket) {

  socket.write(
    date.getFullYear() + '-' + (date.getMonth()+1) + '-' + date.getDate() + ' ' +
    date.getHours() + ':' + date.getMinutes()
  );
  socket.end();
});

server.listen(process.argv[2]);
```

**Comment by atymchuk** [comment]
I ran the test - it seems to be Ok and there is no error. The month is `8`, which is August. 
Date.getMonth is known to return a zero-based result, i.e. January - 0, February - 1, etc. This is why you increased the return value by 1. Nothing is wrong.

**Comment by dominhhai** [comment]
> The getMonth() method returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year).

Check the reference [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)
