### ISSUE TITLE
http file server question

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#1829]
I wrote an acceptable answer to this challenge: 

var http = require('http');
var fs = require('fs');
var stream = fs.createReadStream(process.argv[3]);

var server = http.createServer(function(request, response) {
  stream.pipe(response);
});

server.listen(process.argv[2]);

The only thing that was functionally different in the Node School's answer was this line:

res.writeHead(200, { 'content-type': 'text/plain' })

I looked it up and I understand what its use is, I just don't understand why you need to do it?

**Comment by noffle** [comment]
The `Content-Type` header is hint to the requester about how to interpret the data it's being sent. If you were writing a "real" file server, you might set the Content-Type to e.g. `image/png` when sending image data, or `text/plain` for plaintext. I suspect most browsers will interpret a response consisting of only ASCII or UTF-8 data as `text/plain` anyways, which makes the header at least somewhat redundant in this case.

**Comment by Rud156** [comment]
Thanks I had the same problem
