### ISSUE TITLE
electron app requirement error

### ISSUE THREAD

**Issue by udoyen** [nodeschool/discussions#1833]
* node version: 5.12.0
* npm version:  3.8.6

### 
```
   Your app has some issues
```

### My Code
```js
   var electron = require('electron');

electron.app.on('ready', function () {
    var mainWindow = new electron.BrowserWindow(
        {
            width: 600,
            height: 800
        });
    mainWindow.loadURL('file://' + __dirname + '/index.html');
})
```

The `app` says I need `index.js` but instructions ask that I create `index.html`.

**Comment by TylerMoeller** [comment]
There's a workaround for this issue mentioned here: https://github.com/maxogden/elementary-electron/issues/16

On line 12 of: `<global npm path>\node_modules\elementary-electron\exercises\hello_world\exercise.js`

Change the code to:
```js
problem.verify = function (args, cb) {
  checkAll([
    fsCheck(path.join('.', 'index.html')),
    fsCheck(path.join('.', 'app.js'))
  ], '{{exercise.hello_world.success}}', '{{exercise.hello_world.fail}}', cb)
}
```

**Comment by udoyen** [comment]
@TylerMoeller should I be getting rid of the **return** statement at the bottom of the `exercise.js` file ?

**Comment by TylerMoeller** [comment]
@udoyen No need to remove the return. For reference, here's the full file with the fix: https://github.com/maxogden/elementary-electron/blob/master/exercises/hello_world/exercise.js

**Comment by udoyen** [comment]
it worked thanks @TylerMoeller
