### ISSUE TITLE
I need a bit explanation of HTTP FILE SERVER official solution.

### ISSUE THREAD

**Issue by edwinharly** [nodeschool/discussions#1839]
### This is the official solution code

```
var http = require('http')  
var fs = require('fs')  

var server = http.createServer(function (req, res) {  
    res.writeHead(200, { 'content-type': 'text/plain' })  

    fs.createReadStream(process.argv[3]).pipe(res)  
})  

server.listen(Number(process.argv[2])) 
```

So, what does this line mean ? 

```
res.writeHead(200, { 'content-type': 'text/plain' }
```

Thank you.

**Comment by marinintim** [comment]
Hi, @edwinharly 

`res.writeHead ` writes [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) to the response, this is kind of metadata of the response. In this case we're setting Content-Type to `text/plain`, so the browser would know it's a plaintext and not HTML or something else.
