### ISSUE TITLE
Issue in MAKE IT MODULAR :  returned an error on its  callback

### ISSUE THREAD

**Issue by arnabsarkarbabun** [nodeschool/discussions#1841]
While running with node command I am getting the exact output that is being shown by the learnyounode verify. But verify is giving me the following error.

* node version: v5.1.0
* npm version:  3.3.12

### Error output
  ✓  Submission results match expected  
   
  ✓  Additional module file exports a single function  
   
  ✓  Additional module file exports a function that takes 3 arguments  
   
  ✓  Additional module file handles errors properly  
   
  ✓  Additional module file handles callback argument  
   
  ✗  Your additional module file [fileModule.js] returned an error on its  
  callback: { [Error: ENOENT: no such file or directory, scandir 'verify']  
  errno: -2, code: 'ENOENT', syscall: 'scandir', path: 'verify' }

### My Code
**fileModule.js**
module.exports =  function(dirName,ext,callback){
    var fs = require('fs');
    var path = require('path');
    var size = fs.readdir(process.argv[2], function(err, list){
      if(err){
        return callback(err);
      }else {
        var data = new Array();
        list.forEach(function(file){
          if("."+process.argv[3] == path.extname(file)){
            data.push(file);
          }
        });
        return callback(null, data);
      }
    });
  };
**helloNode.js**
var nodeModule = require('./fileModule.js');
nodeModule(process.argv[2], process.argv[3], function(err, data){
  if(err){
    console.log(err);
  } else{
    data.forEach(function(name){
      console.log(name);
    })
  }
})

**Node Output**
$ node helloNode.js verify img
{ [Error: ENOENT: no such file or directory, scandir 'verify'] errno: -2, code: 'ENOENT', syscall: 'scandir', path: 'verify' }

**Comment by ishtiaque23** [comment]
In your module function you are already receiving 2 parameters which are **dirName** and **ext**. 
```javascript
module.exports = function(dirName,ext,callback){
```
These 2 actually holds the values of **process.argv[2]** and **process.argv[3]** respectively. 

But in your module function body, you are still accessing those command line argument directly
```javascript
//The first one at:
var size = fs.readdir(process.argv[2], function(err, list){

// And the 2nd one at:
if("."+process.argv[3] == path.extname(file)){
```
Replace them with the respective function variable. Make this 2 change and it will work.

Also one minor issue:

```javascript
var size = fs.readdir(process.argv[2], function(err, list){
//No need for this size variable. 
//You will only get undefined here. Just execute the readdir like:
fs.readdir(process.argv[2], function(err, list){
```

## Why the main problem occurred:
At first glance it feels like an innocent code and should work when run directly. But there are 2 major issue:

1. This practice is ethically wrong. When you have a specific data passed via function parameter, you don't need to reach out to another external source to get it again. Use what you already have.
2. For the nodeschool exercises when you run the following command
```bash
learnyounode verify yourfile.js
```
The arguments orders are different, and the **verify** function ensure the provided file get the correct argument in correct place. But then when you try to access the command line again from a separate file, that special step is missing and your 2nd file will end up receiving arguments in wrong order.

**Comment by arnabsarkarbabun** [comment]
thanks @ishtiaque23 .
