### ISSUE TITLE
Installation of javascripting module was stopped.

### ISSUE THREAD

**Issue by khanhoct** [nodeschool/discussions#1848]
- node version: v6.3.1
- npm version:  3.10.3
### Error output

`[               ...] | extract:javascripting: verb gentlyRm don't care about contents; nuking C:\Users\KhanhNGUYEN\AppData\Roaming\npm\node_modules\.staging\javascript`
### Description

I tried to install javascripting nodule but when I run `npm install -g javascripting` command, It just run for a short time and It was stopped at:
`[               ...] | extract:javascripting: verb gentlyRm don't care about contents; nuking C:\Users\KhanhNGUYEN\AppData\Roaming\npm\node_modules\.staging\javascript`

**Comment by martinheidegger** [comment]
Turns out it has been my fault. I published a new version. Would you mind trying to install it again?
