### ISSUE TITLE
learnyounode on windows 10 doesn't work,  Installation does not end

### ISSUE THREAD

**Issue by markokg102** [nodeschool/discussions#1850]
* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by martindiiorio** [comment]
I have the same problem. 
![untitled-1](https://cloud.githubusercontent.com/assets/14200226/17907792/ce96b928-6953-11e6-8857-1f2fa98c6e86.jpg)
