### ISSUE TITLE
Stuck with npm install --global javascripting 

### ISSUE THREAD

**Issue by venkateshmurugan** [nodeschool/discussions#1851]
I am trying to install javascripting in my windows 7 machine. I ran rhe command "npm install --global javascripting" I see nothing after running the command in cmd prompt. It stuck there forever. I tried as administrator but still the same problem. I reinstalled node; deleted all node_modules folders; restarted the machine but still not working. Any tips to resolve would help.
- node version: v4.5.0
- npm version:  2.15.9
### Error output

C:\WINDOWS\system32>npm install --global javascripting
\

**Comment by btkarthick** [comment]
Hello Venkatesh,

Are you behind a corporate firewall? If yes, then you need to tell it to npm via config settings.

Go through the below URLs for setting the proxy details,

https://jjasonclark.com/how-to-setup-node-behind-web-proxy

http://stackoverflow.com/questions/25660936/using-npm-behind-corporate-proxy-pac

**Comment by btkarthick** [comment]
Seems there is a problem with  javascripting workshop #1849.

**Comment by martinheidegger** [comment]
I created an issue on NPM: https://github.com/npm/npm/issues/13722

**Comment by abolajibisiriyu** [comment]
This issue is taking time to fix.. Can anyone one suggest an npm version that works well with these workshops..

**Comment by martinheidegger** [comment]
Some people are trying to triage the bug: https://github.com/nodeschool/discussions/issues/1849#issuecomment-241404380

**Comment by martinheidegger** [comment]
Turns out it has been my fault. I published a new version. Would you mind trying to install it again?

**Comment by venkateshmurugan** [comment]
![image](https://cloud.githubusercontent.com/assets/21027549/17930669/15215c1c-69cd-11e6-9b5b-327049673ed4.png)

still same problem. Should I try different npm version?

**Comment by venkateshmurugan** [comment]
![image](https://cloud.githubusercontent.com/assets/21027549/17930932/631ab9d0-69ce-11e6-9816-5715a81d52ad.png)

I see the files are copied but still javascripting install does not end. If I open another cmd window and try javascripting command, it does not recognize the command.

**Comment by stdrake95** [comment]
Try installing nodejs-legacy if you haven't already. It's a bug fix. http://askubuntu.com/questions/702157/install-node-js-in-ubuntu-14-04
