### ISSUE TITLE
Installation Error : extract:javascripting: verb gentlyRm don't care about contents

### ISSUE THREAD

**Issue by sourabhswain** [nodeschool/discussions#1852]
I am trying to install by running 'npm install -g javascripting' on my machine (Windows 7). The installation freezes and nothing happens. I tried it multiple times but it stops on the following state. Please help me ? Thanks

* node version: v4.4.7
* npm version:  3.10.5

### Error output
extract:javascripting: verb gentlyRm don't care about contents

**Comment by martinheidegger** [comment]
I opened an issue on NPM: https://github.com/npm/npm/issues/13722

**Comment by martinheidegger** [comment]
Turns out it was my fault. You should be able to install it now!

**Comment by sourabhswain** [comment]
Yes it got installed now ! Thanks :)

**Comment by martinheidegger** [comment]
@sourabhswain Thank you for confirming. I am sorry for the inconvenience. Thank you for the patience and input.
