### ISSUE TITLE
[JavaScripting] ## VARIABLES (Exercise 2 of 19)  

### ISSUE THREAD

**Issue by KyleFlemington** [nodeschool/discussions#1856]
## The challenge:
-   Create a file named variables.js.  
-   In that file declare a variable named example.  
-   Make the variable example equal to the value 'some string'.  
-   Then use console.log() to print the example variable to the console.  
-   Check to see if your program is correct by running this command:  
-   javascripting verify variables.js  

---

<img width="1105" alt="screen shot 2016-08-25 at 12 57 00 pm" src="https://cloud.githubusercontent.com/assets/20758659/17983847/7f4db8e6-6ac3-11e6-80f2-6b0292f205da.png">

---

Why have I failed this exercise? Can someone please tell me the flaws in my code. 
Thank You,

**Comment by riyadhalnur** [comment]
In the 3rd line of your code, you are not printing the value of the variable `example` you declared in line 1 but a separate string - putting quotes around text makes it a **string**. The objective of this exercise to print the value of the variable you have declared; so your code will be something like this - 
```js
var example;
example = 'some string';
console.log(example);
```
