### ISSUE TITLE
How to watch NodeSchool tutorials

### ISSUE THREAD

**Issue by EmadElSammad** [nodeschool/discussions#1859]
Guys, someone told me to go to Nodeschool and watch all the tutorials on JavaScript. but when I came to this site I got lost and I don't see any tutorials. It's very confusing. Are there any tutorials? and how to start watching them?

**Comment by riyadhalnur** [comment]
You can find available tutorials here [http://nodeschool.io/#workshoppers](http://nodeschool.io/#workshoppers)

**Comment by lvivier** [comment]
@EmadElSammad hi Emad, the NodeSchool tutorials are called "workshoppers" and they aren't videos that you watch, they are programs that present you with coding problems to solve using node.js. I recommend you to start with **javascripting** and **learnyounode**.

**Comment by abhiii5459** [comment]
@EmadElSammad  There is however the supplementary "codeschool", which does have videos, but isn't as hands-on as nodeschool. The videos are pretty good and clear though - [Code School - NodeJS videos](https://www.codeschool.com/courses/real-time-web-with-node-js)

**Comment by riyadhalnur** [comment]
Imo, if videos are more comfortable for you, I think you can do both side-by-side. Sounds like a good mix.

**Comment by martinheidegger** [comment]
_(I took the liberty to reduce the title because it was way too long)_
