### ISSUE TITLE
[JavaScripting]  ## ARRAY FILTERING (Exercise 12 of 19)  

### ISSUE THREAD

**Issue by KyleFlemington** [nodeschool/discussions#1861]
## The challenge:

  Create a file named array-filtering.js.  
  In that file, define a variable named numbers that references this array: 
     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];  
  Like above, define a variable named filtered that references the result of  
  numbers.filter().  
  The function that you pass to the .filter() method will look something  
  like this:  
     function evenNumbers (number) {  
       return number % 2 === 0;  
     }  
  Use console.log() to print the filtered array to the terminal.  
  Check to see if your program is correct by running this command: 
##      javascripting verify array-filtering.js  

var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
var filtered = numbers.filter(function(evenNumbers(numbers) {
  return number % 2 ==== 0;
};
console.log(filtered);

---

Why does this code fail?

Thank you,
Kyle

**Comment by ishtiaque23** [comment]
Your approach has some syntax error. The way it is written, it suppose to throw error.

You have the correct idea of using the **numbers.filter()**.
You have to pass it that **evenNumbers** function. 

The way you are doing it is wrong. There are two proper way to do this.

First you can do something similar to this(focus on how they are passing it to the filter function): 
![image](https://cloud.githubusercontent.com/assets/106562/18075832/7251c5f8-6e9a-11e6-8bbb-00b7e91fe4fd.png). 
Second, you can use an anonymous function like this

```javascript
var myNumbers = [1, 2, 3, 4, 5, 6, 7, 8]
var myVariable = myNumbers.filter(function (number) {
  return number % 2 === 0;
})
```

Read more about Array Filters [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

Also note that the compare operator you are using should be **===**, not **====**. There is nothing called **====** in javascript.

**Comment by hackemateninja** [comment]
var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
var filtered = numbers.filter(function EvenNumbers(number) {
  return number % 2 === 0;
});
console.log(filtered);
