### ISSUE TITLE
Module exercise

### ISSUE THREAD

**Issue by samd21313** [nodeschool/discussions#1862]
I cant figure out what im doing wrong 
- node version: <6.5.0>
- npm version:  <3.10.6> 
  ```  ✗  Your additional module file [filtered-module.js] returned an error on
  its callback: { Error: ENOENT: no such file or directory, scandir
  'C:\node\younode\verify' at Error (native) errno: -4058, code: 'ENOENT',
  syscall: 'scandir', path: 'C:\node\younode\verify' }

``````

Module File
```js 
 module.exports = function(directory,fileType,callback){

var fs = require('fs');
var path = require('path');

var directory = process.argv[2];
var fileType = '.'+ process.argv[3];

fs.readdir(directory, function (err, list){
  if (err) {return callback(err)}
    for(i=0;i<list.length;i++){
        if (path.extname(list[i]) === fileType){
            console.log(list[i]);}
        }
    });

}

``````

Program file

```
var filter = require('./filtered-module');

filter(process.argv[2],process.argv[3])

```

**Comment by ishtiaque23** [comment]
In your module function, you are doing this:
```javascript
module.exports = function(directory,fileType,callback){
```
Inside the function once again you are doing this:
```javsacript
var directory = process.argv[2];
var fileType = '.'+ process.argv[3];
```
Get rid of these 2 lines.
When you are inside the module file, the order of the **process.argv** will be different(which will be handled internally by the verifier scripts). So you can't rely on the **process.argv** stuffs from within that function.

Good News is, you already have those covered with that function signature I showed you in the first line. You can use the **directory** like you are doing now. You do need a change about **fileType** though:

```javascript
//change this line
if (path.extname(list[i]) === fileType){
//to this
if (path.extname(list[i]) === '.' + fileType){
```

Now comes the important part. We need to revisit the function signature. You have a 3rd parameter called **callback**. Means you are expecting a **callback function** here.

But when you are calling this method from program file, you are not passing the function:

```javascript
filter(process.argv[2],process.argv[3])
```
you have to pass a **callback function** here which will receive an **array**, loop through it and  **console.log** each item of it.

From within the module function, you will not **console.log** anything. You have to store the found values in an **array**. and then call the **callback** with that **array**.

Keep in mind the universal signature for any callback function in javascript is:
```javascript
function myCallback(error, result)
// it will always expect error in first parameter and the result in second one. 
// When passing result you need to pass null as the first parameter.
```
