### ISSUE TITLE
Do modules need to be installed globally?

### ISSUE THREAD

**Issue by dantesolis** [nodeschool/discussions#1869]
* node version: <run "node -v" in you terminal and replace this> `4.4.7`
* npm version:  <run "npm -v" in you terminal and replace this> `2.15.8`

So I would like to run the modules from within a folder I created. I did `npm install javascripting`  & `npm install learnyounode` the both installed, but I'm unable to run the modules within this folder. Globally I have no problems.

Is there a way around this?

Thanks

**Comment by noffle** [comment]
Is there an error? What happens when, after installing locally, you run

```sh
$ node_modules/javascripting/bin/javascripting
```

**Comment by dantesolis** [comment]
@noffle, thank you. I was still trying to run it by just calling `javascripting`
 Your solution worked. Thanks. 

Question to just run it with `javascripting`  instead of ` node_modules/javascripting/bin/javascripting` I would have to make that executable available in my path? Is this correct?


Thanks

**Comment by noffle** [comment]
Yes, that's correct. Something like `export PATH=$PATH:/somepath/node_modules/javascripting/bin`.

However, if your qualm with global installs is that it requires superuser privileges, you can tell npm to use e.g. your home directory for global installs:

```sh
$ npm set prefix $HOME/.npm-global
```

Now all `npm -g install`s you do will be placed here. This has the nice side effect of letting you set just one directory in your `PATH` to capture all globally installed executables:

```sh
export PATH=$PATH:$HOME/.npm-global/bin
```

**Comment by dantesolis** [comment]
@noffle right now I have a `.npm/` directory on my home. But I think that's the same thing?. Anyways thanks for the help and for the info. Should I close this issue?

**Comment by martinheidegger** [comment]
@dantesolis @noffle I feel like this should be noted somewhere on the [homepage](https://github.com/nodeschool/nodeschool.github.io). I am busy with other things, but perhaps one of you could help everyone out and add a paragraph at a good place?

**Comment by dantesolis** [comment]
@martinheidegger  & @noffle I could do it. I Just read the contribution section and about to clone the repo on my machine. Waiting for the greenlight

**Comment by SomeoneWeird** [comment]
Go ahead. Make a PR and somebody can review it 👍

**Comment by riyadhalnur** [comment]
@dantesolis Yes, please go ahead. Tag one of us once your open the PR. Thank you in advance 😃

**Comment by dantesolis** [comment]
No problems. Thanks guys.

**Comment by martinheidegger** [comment]
@dantesolis was so kind to add a section to the readme of nodeschool.github.io.

**Comment by martinheidegger** [comment]
@dantesolis can this issue be closed?

**Comment by dantesolis** [comment]
@martinheidegger, yes, I'll go ahead and close it. And thanks guys for letting me contribute. Now to start working on those modules.
