### ISSUE TITLE
Official solution not displayed on correct answer submission (Javascripting) 

### ISSUE THREAD

**Issue by shannonjanehogan** [nodeschool/discussions#1881]
- node version: v6.2.2
- npm version:  3.10.5

When working through the javascripting unit, upon submitting the correct answer, this is the output: 
### Error output

https://www.dropbox.com/s/ux2yhyfzpc3abbt/Screenshot%202016-09-23%2009.45.58.png?dl=0

No official solution is displayed, it is just an empty line.

**Comment by riyadhalnur** [comment]
Hi @sjhogan2. Thank you for reporting this. Could you open an issue in the [Javascripting](https://github.com/sethvincent/javascripting/issues) repo. Would help the authors figure out if others are having the same problem as well.
