### ISSUE TITLE
excercise 6 - fs.readDir is not a function

### ISSUE THREAD

**Issue by HopVuVan** [nodeschool/discussions#1883]
Hi guys. 
I'm a new noob when study node.js. When i do excercise 6th, i got this issue.
I searched in Google but got nothing.
* node version: 4.5.0
* npm version:  2.15.9

### Error output
```
d:\Study\nodeschool.io\excercise6.js:4
readDir(path, ext, function(err, data){
^

TypeError: readDir is not a function
    at Object.<anonymous> (d:\Study\nodeschool.io\excercise6.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

### My Code
```js
// file Module_Excercise_6.js
module.exports = {
    myReadDir: function (pathFile, ext, callback){
    var path = require('path');
    var fs = require('fs');
    
    fs.readDir(pathFile,'utf-8', function(err, listFile){
        if(err) return callback(err, null);
        listFile.array.forEach(function(element) {
            if (path.extname(element) === ext) {
                callback(null, element);
            }
        }, this);
    });
}
}

// file Excercise6.js
var readDir = require('./Module_Excercise_6.js');
var ext = '.' + process.argv[3];
var path = process.argv[2];
readDir(path, ext, function(err, data){
    if(err) throw console.error(err);
    console.log(data);
});

```

**Comment by raja-kosuru** [comment]
in exercise6.js - use  readDir.myReadDir(path...
in Module_Exercise_6 - noticed typo  it is fs.readdir and not fs.readDir

**Comment by HopVuVan** [comment]
@raja-kosuru thanks guy, i changed my code. But new issue is :

> D:\Study\nodeschool.io>learnyounode run excercise6.js
fs.js:78
    throw new TypeError('callback must be a function');
    ^
> TypeError: callback must be a function
    at makeCallback (fs.js:78:11)
    at Object.fs.readdir (fs.js:799:14)
    at Object.module.exports.myReadDir (D:\Study\nodeschool.io\Module_Excercise_6.js:7:12)
    at Object.<anonymous> (D:\Study\nodeschool.io\excercise6.js:4:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

//Module_Excercise_6.js
        module.exports = {
        myReadDir: function (pathFile, ext, callback) {
        var path = require('path');
        var fs = require('fs');

        fs.readdir(pathFile, 'utf-8', function (err, listFile) {
            if (err) return callback(err, null);
            listFile.array.forEach(function (element) {
                if (path.extname(element) === ext) {
                    callback(null, element);
                }
            }, this);
        });
       }
     }
//Excercise6.js
var readDir = require('./Module_Excercise_6.js');
var ext = '.' + process.argv[3];
var path = process.argv[2];
readDir.myReadDir(path, ext, function(err, data){
    if(err) throw console.error(err);
    console.log(data);
});

**Comment by alexpetroni** [comment]
try with:
module.exports = myReadDir;
where myReadDir is your function. Right nou you return an object {}.
Hope it helps.

**Comment by HopVuVan** [comment]
@alexpetroni Thanks guy. I fixed my code. 
First, i still let callback within loop array.forEach() function, It's have 1 error when verify my file.

> Your additional module file [filter.js] did not call the callback  argument.

Second, i let callback out of loop, push all data (which extension file = '.'+ process.argv[3]) to an array. Then callback(null, array).
In prior file, i loop forEach to console.log each element of my array.
It's work.

Link one guy have the same issue with me here: [#1836](https://github.com/nodeschool/discussions/issues/1836)
