### ISSUE TITLE
is this a good starting point to learn to code?

### ISSUE THREAD

**Issue by johnmdowds** [nodeschool/discussions#1884]
* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Hi, please provide more information if possible.

**Comment by riyadhalnur** [comment]
Closing this because of inadequate information.
