### ISSUE TITLE
I will like integrated nodeschool in morocco / Casablanca, can you give me information ?

### ISSUE THREAD

**Issue by saadaouad** [nodeschool/discussions#1886]
* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Hi @saadaouad, if you are looking to open a new chapter, would you mind opening an issue here on the [organizers](https://github.com/nodeschool/organizers) repo and we can get you on-board 😃

**Comment by saadaouad** [comment]
Thanks @riyadhalnur :+1:
