### ISSUE TITLE
Hosting NodeSchool Event?

### ISSUE THREAD

**Issue by eunsol715** [nodeschool/discussions#1887]
Is it possible to host the 1st NodeSchool event without creating a new chapter? 
Is it a MUST DO line item to create a new chapter or could we create a chapter after a successful event turnout?

**Comment by martinheidegger** [comment]
@eunsol715 You do not need to create a chapter at all. You can do it if and when you feel like you want to tell the world regularly: 

> *Chapter* … A NodeSchool chapter refers to a place where at least one (but preferably more) NodeSchool events happen. Chapters are based on their geolocation (!not on any other structure!) and are usually setup for an area that is easy to reach with public transport within approx. 40min. Usually that means one Chapter per city.

from: https://medium.com/@leichtgewicht/the-missing-hands-at-nodeschool-8999a90d33d1#.q2prh6j7t

Does that help you (answer your question)?

**Comment by eunsol715** [comment]
Yes, @martinheidegger Thank you very much :)

**Comment by martinheidegger** [comment]
@eunsol715 :+1:
