### ISSUE TITLE
Node.js giving less performance than Java EE on Tomcat Server

### ISSUE THREAD

**Issue by nischay13may** [nodeschool/discussions#1897]
I made a  single player game of Snakes and Ladders using AngularJS and Java(Spring and Hibernate). Then I read some blogs and forums about game development, and decided to switch to Node.JS. But after developing the backend on Node.JS, I decided to do some Performance Testing using JMeter.
I have used Threads(200), Ramp Up Time(1),, Loop Count(2)
I was amused after looking at the results.
The throughput of the Java based games was 27.1/sec and that of Node.JS was 8.1/sec.
This was after using compression package on Node.JS.

Is there any solution to increase Node.JS performance?

**Comment by martinheidegger** [comment]
Node.js Is having a JIT compiler that literally "JIT" creates compile steps and optimizations. Running a test on a simple data set might run in precompilation steps that do not resemble a real environment. That aside: There are tasks that are faster in Java, but there is a bunch of optimizations that you can do in Node. Without a look at your performance test I can not give you any recommendation on how to use it better.

_Sidenote: This might be a better thread for https://github.com/nodejs/help/issues_

**Comment by nischay13may** [comment]
What kind of information you require? 
Testplan or the Test results?

**Comment by martinheidegger** [comment]
The Testplan/Testcode would be helpful as well as information about the system you are running them on.

**Comment by martinheidegger** [comment]
Closing this issue in favor of https://github.com/nodejs/help/issues/317 (please post the information there)
