### ISSUE TITLE
verify option is ignored

### ISSUE THREAD

**Issue by orboan** [nodeschool/discussions#1898]
Hello,
is strange as when I type 'javascripting verify [whatever-valid]' from the correct directory, it immediately goes to the exercises menu, without checking anything, the same behavior as if I typed only 'javascripting' without any arguments. The same happens with learnyounode, the verify option does nothing, like it is ignored. On the other hand, git-it verify works perfectly well.

Can anyone help me to solve this issue?

Next, info about OS, and node and npm versions. Thanks.

[vagrant@localhost nodeschool]$ uname -a
Linux localhost.localdomain 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@localhost nodeschool]$
[vagrant@localhost nodeschool]$ node -v
v6.3.1
[vagrant@localhost nodeschool]$ npm -v
3.10.3
[vagrant@localhost nodeschool]$

**Comment by orboan** [comment]
Any clues? It's  javascripting@2.6.0. I've reinstalled everything from the source code, now:

[vagrant@localhost ~]$ node -v
v6.7.0
[vagrant@localhost ~]$ npm -v
3.10.3

And when I install javasripting using 'npm install -g javascripting' I get the next warning (I do not know if it is related or not):
npm WARN deprecated workshopper-adventure@4.7.1: Accidental major release published as patch. Please use 5.0.0

So before installing javascripting I installed first workshopper-adventure, and the installed version of it is 5.0.3. Still, when installing javascripting I get that warning. Don't know if it's related with argument verify not working, but just in case I let you know.

Anyway, after reinstalling everything, 'verify' parameter is still ignored and the javascripting exercise menu is launched too, as if the javascripting script was run without any argument.

Please, help

**Comment by martinheidegger** [comment]
Note: I have just installed the same version on a fresh centos and also wasn't able to reproduce that issue. are you sure that you don't have a typo?

**Comment by orboan** [comment]
Hello,
thanks for your answer.
Yes, it's not a typo.
What I will do, now not but when I find some time to do it, is to upload this vagrant box to atlas (online vagrant repo), then you'll be able to download it and test what I'm saying. I'll let you know when the box is available online.
Thanks

**Comment by orboan** [comment]
Ok, here you have it:

vagrant init orboan/nodeschool-el7-test
vagrant up --provider virtualbox

username: vagrant
password: vagrant
