### ISSUE TITLE
NodeSchool - Chapter Sao Paulo, Brazil

### ISSUE THREAD

**Issue by fcossini** [nodeschool/discussions#1899]
Hi!

I would like to know if the NodeSchool Chapter Sao Paulo, Brazil is up and running.

Although I do not see this chapter listed in NodeSchool website, I find it in Github and in another webpage specifically to present the chapter.

I opened an issue on October, 6th but have not receive a reply yet.

I would appreciate your help to put me in contact with the leader of this chapter, if it is active. Otherwise, myself and some colleagues here at IBM Sao Paulo would like to work on the construction of the chapter in our area.

Thanks for your help,

Fabio

**Comment by riyadhalnur** [comment]
Ping @thebergamo, @ErickWendel and @Leolosi

**Comment by thebergamo** [comment]
We're in touch! Thks @riyadhalnur for the mention!!
