### ISSUE TITLE
The command "learnyounode" doesn't appear to run anything

### ISSUE THREAD

**Issue by filostrato** [nodeschool/discussions#190]
The command "learnyounode" doesn't appear to be doing anything. By going into the folder where learnyounode.js is, I can get the tutorial to run by running "nodejs learnyounode.js", but it seems like it's supposed to run when typing in the command "learnyounode" from anywhere. Doesn't give me any error messages or warnings, it just doesn't do anything.

**Comment by vgonzalezr** [comment]
Hi guys, I've been looking everywhere to fix my problem and this was the right solution.

Thanks a lot.

**Comment by kapilgarg1996** [comment]
The solution you suggested worked for me but not the commands. To update to the latest version i followed this [askubuntu answer](http://askubuntu.com/a/83290)
