### ISSUE TITLE
learnyounode says no error returned on exercise Make it modular

### ISSUE THREAD

**Issue by klequis** [nodeschool/discussions#1908]
### Error output

```
 // copy your error output here
✗  Your additional module file [readdirectory.js] does not appear to pass  
  back an error received from fs.readdir(). Use the following idiomatic  
  Node.js pattern inside your callback to fs.readdir(): if (err) return  
  callback(err)  
```

node version: 6.9.1
npm version: 3.10.8
os: Ubuntu 16.10 GNOME 3.22 - VirtualBox VM

Problem
### My Code for readdirectory.js. If I change the path to something invalid it does return an error so not sure what to do.

``` js
let fs = require("fs");
const path = require("path");
let fileName;

module.exports = function(dirPath, ext, callback) {
  fs.readdir(dirPath, "utf8", (err, data) => {
    //if (err) return callback(err, data);
    if (err) return callback(err);

    // pack data
    ext = "." + ext;
    let arr = [];
    for (let i=0; i<data.length; i++) {
      fileName = data[i];
      if (path.extname(fileName) == ext) {
        arr.push(fileName);
      }
    }
    return callback(err, arr);
  });
};

```

**Comment by klequis** [comment]
## More Info
I modified my code to print the error message with err.message. Below is the update plus in the fs.readdir() call I mutate the path (dirPath + "a") to produce the error. it returns the below messages.
````
ENOENT: no such file or directory, scandir '/tmp/_learnyounode_1316a'
````
### Here is the complete code with the mutated path
#### program05.js
````js
let readDir = require("./readdirectory.js");
let dirPath = process.argv[2];
let extension = process.argv[3];

readDir(dirPath, extension, listData);

function listData(err, data) {
  if (err) {
    console.log(err.message);
  } else {
    for (let i=0; i<data.length; i++) {
      console.log(data[i]);
    }
  }
}
````
#### readdirectory.js
````js
let fs = require("fs");
const path = require("path");
let fileName;

module.exports = function(dirPath, ext, callback) {
  fs.readdir(dirPath + "a", "utf8", (err, data) => {
    if (err) return callback(err, null);
    // pack data
    ext = "." + ext;
    let arr = [];
    for (let i=0; i<data.length; i++) {
      fileName = data[i];
      if (path.extname(fileName) == ext) {
        arr.push(fileName);
      }
    }
    return callback(null, arr);
  });
};
````
#### complete verify output attached


![032 selection](https://cloud.githubusercontent.com/assets/18337376/19726523/330c2aaa-9b40-11e6-80b9-a453a7eed2f6.png)

**Comment by Mycroft1891** [comment]
You have to call the error:

```
var myModule = require('./module.js')

var path = process.argv[2]
var extention = process.argv[3]

function callback (err, data) {
	if (err) return console.error(err)

	data.forEach(function(i){
		console.log(i)
	})
}

myModule(path, extention, callback)
```

**Comment by ayhtrak** [comment]
let fs = require("fs");
const path = require("path");
let fileName;

module.exports = function(dirPath, ext, callback) {
  fs.readdir(dirPath + "a", "utf8", (err, data) => {
    if (err) return callback(err, null);
    // pack data
    ext = "." + ext;
    let arr = [];
    for (let i=0; i<data.length; i++) {
      fileName = data[i];
      if (path.extname(fileName) == ext) {
        arr.push(fileName);
      }
    }
    callback(null, arr);
  });
};

**Comment by obinnaeye** [comment]
Try replacing `fs.readdir(dirPath, "utf8", (err, data)` with `fs.readdir(dirPath, (err, data)`

Don't use let and const, use var instead.

Then follow @Mycroft1891 answer for your main program.js. 

If your problem has been resolved, it's good to indicate; so others may follow the answers that worked.
