### ISSUE TITLE
Javascripting for-loop (10 of 19) Why is answer 45??

### ISSUE THREAD

**Issue by arssonist** [nodeschool/discussions#1909]
I have written the correct code in Nano and had it verified but I don't get why the answer is 45?

```var total = 0;
      var limit = 10;
for (var i = 0;i < limit; ++i){
  total += i;
}
console.log(total);```

(Also not sure what the loop is all displaying on one line like that??)

If it loops through 1-10 adding 1 each time, where do all the extra values come from?
```
0
1
3
6
10
15
21
28
36
45
```

**Comment by riyadhalnur** [comment]
At the very beginning, you are starting with a variable `total` with an initial value of 0. When you start a `for` loop, you are telling the loop to iterate 10 times starting from 0. On each pass, the iterator, `i`, value is being passed to your function inside the loop. In this particular problem, you are adding the value of `i` to total on each pass of the loop. So, for a loop of 0 upto but not including 10, what is essentially happening is - *0 + 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 = 45*.

**Comment by arssonist** [comment]
Ahh, thanks riiyadhaiur. Makes sense now.
