### ISSUE TITLE
Trampoline - What is a trampoline?

### ISSUE THREAD

**Issue by turion** [nodeschool/discussions#191]
I find the hints in the trampoline question incomprehensible. Can someone explain what is being asked here? What does "the next step" mean? What is a trampoline? Wikipedia isn't helping here and via google I only find stuff related to generators - surely not what is being asked here?

**Comment by smartbeauty** [comment]
The <a href="http://www.domijump.com/products/trampoline/round-trampoline/">round trampolines</a> are available in different sizes such as 5ft, 6ft, 12ft and 14ft models and uniquely identified by their round shape. They are mainly considered as recreational trampolines that are ideal for outdoor and home use. The trampolines are fitted with additional safety equipment such as the safety net enclosures.

Others feature the “button hole” that connects the jump net and the safety enclosure system. This eliminates the gaps. The <a href="http://www.domijump.com/">Domijump</a> trampolines are padded with a soft foam that keeps jumpers away from the springs and frames. The safety nets are available for both external and internal styles.

**Comment by SomeoneWeird** [comment]
Lol.
