### ISSUE TITLE
Error calling a local function from post method

### ISSUE THREAD

**Issue by nischay13may** [nodeschool/discussions#1912]
### Error output

Error: Route.post() requires callback functions but got a [object Undefined]
### My Code

app.post('/getDetails',this.getDetails);
this.getDetails = function(req, res)
{
    console.log(req.body);
    db.getDetails(req.body);  // db is another js file in which getDetails function is written
};

**Comment by noffle** [comment]
You're so close! When the first line is run, `this.getDetail` is not yet defined. Try putting the `app.post(...` line *under* the definition of `getDetails` instead.

**Comment by nischay13may** [comment]
Worked!! Thanks!!
