### ISSUE TITLE
tutorial commands not found

### ISSUE THREAD

**Issue by mndr** [nodeschool/discussions#1914]
Hello, I received error message "command not found" when running "javascripting" and "learnyounode". I think something is wrong with my permissions. I'm running on Mac 10.11

$ node -v
v7.0.0

$ npm -v
3.10.8

$ npm config get prefix
/Users/amanda/npm

$ npm list -g --depth=0
/Users/amanda/npm/lib
├── javascripting@2.6.1
└──  learnyounode@3.5.7

$PATH
/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/

Help?

**Comment by noffle** [comment]
You're nearly there! You'll need to add `/Users/amanda/npm/bin` to your `$PATH`. On macOS you can do this by opening/creating a file named `.bashrc` in your home directory and add `export PATH=$PATH:${HOME}/npm/bin` to it.

**Comment by mndr** [comment]
Ok thank you! that did the trick once I added this path and restarted my terminal.
