### ISSUE TITLE
learnyounode command not found

### ISSUE THREAD

**Issue by johnny-steelhouse** [nodeschool/discussions#1918]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.

**Comment by rogerchocs** [comment]
Is there an answer for this? Cant get learnyournode to work for anything.

node -v
v6.9.1
npm -v
3.10.8

windows 10

Thank you

**Comment by Shivamnema05** [comment]
I'm also seeing this error message. Please help to start with this.

**Comment by Dawn11** [comment]
when I try to call learnyounode, nothing happens/

node -v
v6.9.1
npm -v
3.10.8

I'm using a mac pro, thanks

**Comment by Shivamnema05** [comment]
This problem can be fixed. @Dawn11 @rogerchocs @riyadhalnur 
Please fix the [npm permissions on you computer. ](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

Check this out and try to fix the problem.

**Comment by Shivamnema05** [comment]
- #1918 fixed
