### ISSUE TITLE
Redirect HTTP requests to HTTPS in node server hosted in Amazon EC2

### ISSUE THREAD

**Issue by sivivicky** [nodeschool/discussions#1919]
I have configured SSL for a node based website hosted in AWS EC2 Linux Instance. https://www.domain.com is working whereas http://www.domain.com is not redirecting to "https" nor loading the page.

I tried all possible stackoverflow solutions and none of them worked.

Code that I used in app.js file:

var app = express();
var options = {
    key: fs.readFileSync(config.sslKeyPath),
    cert: fs.readFileSync(config.sslCertPath),
	ca: fs.readFileSync(config.sslCaPath)
};

var server = https.createServer(options, app);
var redirectServer = http.createServer(app);

app.use(function requireHTTPS(req, res, next) {
  if (!req.secure) {
    return res.redirect('https://www.venuetiger.com'+ req.url);
  }
  next();
});

redirectServer.listen(3000);

**Comment by riyadhalnur** [comment]
Shameful endorsement but nonetheless, this is why I built it. You can use this [node-force-secure-redirect](https://github.com/riyadhalnur/node-force-secure-redirect) module to forcefully redirect all request over 80 -> 443. Let me know if it helps.

**Comment by Mycroft1891** [comment]
I have been reading the book express in action and it describes how you might want to do it. I didn't go through it myself because I use Heroku but maybe it works for you. 

```
var enforceSSL = require("express-enforces-ssl");

app.enable("trust proxy");
app.use(enforceSSL());
```

You can read more about express-eforce-ssl here: [https://github.com/aredo/express-enforces-ssl](url)
