### ISSUE TITLE
Iterando con FOR (Ejercicio 10 - 19)

### ISSUE THREAD

**Issue by IgnacioGans** [nodeschool/discussions#1925]
Hola a Todos!

Voy directo al grano, en el siguiente ejercicio (Ejercicio 10 - 19), he intentado usar el bucle FOR de la siguiente manera:

```
var total = 0;
var limit = 10;

for (var total += i; i < 10; i++) {
	
};
console.log(total);
```

Evidentemente no estoy iterando correctamente lo que me plantea la consola de javascripting, por lo que respecta en ese ejercicio soy muy noob con los bucle FOR.  
Agradecería cualquier material para entender y lograr pasar ese nivel del Bucle FOR.

Saludos
Remking

**Comment by noffle** [comment]
¡Hola! Estás muy cerca.

Para imprimir los números de 1 a 10, escribiría

```js
for (var i = 0; i < 10; i++) {
  console.log(i)
}
```

Las tres partes de FOR son 1) declaración de variables, 2) condición, 3) incremento. Usted tiene 2 y 3 correctos pero necesita fijar 1.

**Comment by IgnacioGans** [comment]
Happy New Years Noffle, 
Oh, cierto, debí declarar la variable dentro del "FOR" para poder imprimir la variable.
Gracias por la ayuda.

**Comment by noffle** [comment]
¡De nada!
