### ISSUE TITLE
My TimeServer is not passing the test 

### ISSUE THREAD

**Issue by ayhtrak** [nodeschool/discussions#1926]
var dateformat = require('strftime');
var net =require('net');

date= new Date();
date=dateformat('%F %H:%M',date);

var server = net.createServer(function(socket){

	socket.write(date)
	socket.end()

})

server.listen(process.argv[2]);

**Comment by ayhtrak** [comment]
The output of the test has and extra 
""
blank line as a second line output.

Can anyone please help? Thanks!

**Comment by nateweller** [comment]
You're missing one small part of the exercise, take another peek at the instructions: "For each connection you must write the current date & 24 hour time in the format: "YYYY-MM-DD hh:mm" **followed by a newline character**. Month, day, hour and minute must be zero-filled to 2 integers."

**Comment by ayhtrak** [comment]
Thanks for the response! I could have missed that forever ... that helped !!
