### ISSUE TITLE
I need help with Javascript Arithmetic operators

### ISSUE THREAD

**Issue by marsa926** [nodeschool/discussions#1929]
```js
var a = 1, b = 2, c = 3;
	(function secondFunction(){
		var b = 8;
		console.log("a: "+a+", b: "+b+", c: "+c);
})();
```

My out put is suppose to be a = 1, b = 8, c =6.

I'm getting confused with "a: "+a+", b: "+b+", c: "+c
I understand a++ means add one to the current a, but the arithmetic operators above are confusing me. Can anyone help me and explain them to me please?
(I would like to guess +a+ means equal to the variable?)

**Comment by noffle** [comment]
Addition of two numbers will add them together, while addition of a number and a string will concatenate them together. You can try this out for yourself on the node [repl](https://en.wikipedia.org/wiki/REPL) by typing `node` on the command line:

```
> 4 + 5
9

> 4 + "bob"
"4bob"

> 4 + "5"
"45"
```

The use of adding a number to a string in your posted code is to print those numbers on the screen, which is what `console.log` does.

**Comment by marsa926** [comment]
Oh my goodness, I was getting confused because I thought the quotation marks were between +a+ haha
instead of thinking "a:"    sorry my hunger was overpowering my brain. Noffle thank you so much!! XD

**Comment by noffle** [comment]
Haha, it can be tricky when they're all sandwiched together like that. :grinning:
