### ISSUE TITLE
Problems solving MAKE IT MODULAR (Exercise 6 of 13)

### ISSUE THREAD

**Issue by webgast** [nodeschool/discussions#1930]
### Notes

Hi, I am trying to solve exercise 6 (MAKE IT MODULAR (Exercise 6 of 13) and I am working in Cloud 9 (c9.io) on:

-node version v4.1.1.
-npm version 2.14.4

I kind of understood the prior exercises and thought I had a proper solution, although the learnyounode verify program thinks otherwise.

c9.io runs their virtualized servers on:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

### Error output

Hmm, no errors. Although learnyounode shouts:

 Your additional module file [my_module.js] returned an error* on its
 callback: []

(I cannot find the mentioned error)

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!

My Code (2 files and a "fake" directory with 3 empty .md files)

my_module.js:

### 

module.exports = function (dirname, extension, callback) {

    var fs = require('fs');
    var path = require('path');
    var dir =  dirname;
    var arr = [];
    
    function filter(data, ext) {
    	for(var x in data) {
            	if(path.extname(data[x]) == ext) {
    			    arr.push(data[x]);
            	}
    	}
        return arr;
    }
    
    var doSomething = function(err, data) {
    	if(err) throw err;
    	var mitt = filter(data, extension);
    	if (err) throw callback(err);
    	callback(mitt);
    };
    
    fs.readdir(dir, function(err, data){
        if(err) {
            return callback(err);
        };
        doSomething(err, data);
    });

};

####### next file:

modular.js

`var mm = require('./my_module');

var outcome = mm('/home/ubuntu/workspace/spoof', '.md', function(stuff) {
    for(var x in stuff) {
        console.log(stuff[x]);
    }
});`

###### finally, the directory spoof, in which the 3 empty .md files reside:

/spoof
.CHANGELOG.md
.LICENCE.md
.README.md

######

The program outputs the filenames nicely. I had to do the spoof because the learnyounode program is clearly not designed to run in c9.io environment, but eh, I liked the challenge.

Thanks for helping!

**Comment by noffle** [comment]
Perhaps it was a copy/paste error, but `modular.js` requires `my_module`, but your module is named `mymodule.js` (missing underscore).

Another possible point of error is the way that you're calling `callback` in `mymodule`. The Node convention is to call callbacks with `callback(error, result)`. So, to return data (without an error) you'd write `callback(null, result)`. This also applies to the arguments yo're expecting in your callback in `modular.js`: you want the signature `function (err, stuff)`, not `function (stuff)`.

**Comment by webgast** [comment]
Thanks Noffle, that "mymodule.js" was indeed a typo and should read "my_module.js". However, adding "null" to the call results in a syntax error:

/home/ubuntu/workspace/modular.js:3
var outcome = mm('/home/ubuntu/workspace/spoof', '.md', function(null, stuff) {
                                                                 ^^^^

SyntaxError: Unexpected token null
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

And adding an "err" var does work, but my node install complains about the throw statement:

/home/ubuntu/workspace/modular.js:4
    if(err) throw err;
            ^
CHANGELOG.md,LICENCE.md,README.md

And yet, the exercise is not complete according to learnyounode (not modular!) I'm stumped.

**Comment by noffle** [comment]
Hey @webgast. What does your code look like now?

**Comment by webgast** [comment]
Hi Stephen,

Thanks! I think you can take a look for yourself:

https://ide.c9.io/perk/geennood

It's the files modular.js and my_module.js

Kind regards,

Johan Perk
webgast.nl

info@webgast.nl

+31(0)654934880

twitter.com/webgast

**Comment by webgast** [comment]
Hi Stephen,

Sorry! I tried to get in but without c9 account that wouldn't fly.

Here are the files as is!

PS> I use a "spoofed" dir with 3 .md files as described in my ticket.

Thank you very much for helping, I am trying to learn node asap :)

Kind regards,

Johan Perk
webgast.nl

info@webgast.nl

+31(0)654934880

twitter.com/webgast

**Comment by noffle** [comment]
@webgast I don't have an account; it may be easier if you posted your code here.
