### ISSUE TITLE
Solution for Async Juggling from learnyounode not working 

### ISSUE THREAD

**Issue by dhaliman** [nodeschool/discussions#1931]
Hi,

Here's my solution to the Async Juggling:
```js
var http = require('http');
const url1 = process.argv[2];
const url2 = process.argv[3];
const url3 = process.argv[4];



function GetData ( url, callback ) {
  http.get(process.argv[2], function (response) {
      var str = '';
      response.on('data', function(data) {
        str += data.toString();
      })
      response.on('end', function() {
        callback(str);
      })
  });
}



GetData (url1, function(err, data) {
  if (err) {
    console.log(err);
  }
  else {
    console.log(data);
    GetData (url2, function(err, data) {
      if (err) {
        console.log(err);
      }
      else {
        console.log(data);
        GetData (url3, function(err, data) {
          if (err) {
            console.log(err);
          }
          else {
            console.log(data);
          }
        });
      }
    });
  }
});
```

I don't understand why it isn't working. Can anyone help me out.
Thanks 
Manmeet

**Comment by noffle** [comment]
You're close! Take a closer look at your `GetData` function: are you using the parameter `url` anywhere?

You also want to look at the way you're calling `callback` in `GetData`. The Node convention is to always pass errors in as the first parameter, and the result as the second parameter. For example: `callback(null, result)` if you want to provide a result but signal no error.

**Comment by dhaliman** [comment]
I fixed the `url` parameter in `GetData` but was still getting the same result.

Then I changed `callback(str)` in` GetData` to `callback(null, str)` and it passed all tests. I don't understand why though.

**Comment by noffle** [comment]
Here's your code the first time you call `GetData`:

```js
GetData (url1, function(err, data) {
  ...
})
```

As you've written, its callback takes two parameters: `err` and `data`. This function is what's passed in to the `GetData` function, so inside `GetData` when you call `callback(null, str)` you're setting `err` to `null` and `data` to `str`.

**Comment by dhaliman** [comment]
okay. Thanks. I still feel a little confused but I get it. 

If I change all the `GetData` to accept only a single `data` parameter and remove all the `if(err)` statements, it still works!

Just wondering if I should use `err` at all since, I'm giving it a null value in the callback.

Thanks...

**Comment by noffle** [comment]
You don't *need* to use `err` in this instance because a) no errors are being thrown, and b) `GetData` is your function and you can decide what parameters it passes to its callback.

However, the convention of callbacks having the form `function (err, result)` is extremely common in Node: most modules will send back results in that form.
