### ISSUE TITLE
How to install node js application in linux hosting server?

### ISSUE THREAD

**Issue by hashemirafsan** [nodeschool/discussions#1934]
I'm trying to make a script which fetches the data from http://codeforces.com API. When I try to execute on CMD it's properly run then I use express package for open a localhost server to run my script on the browser and it's also executed properly but now I wanna  upload on my hosting server but it doesn't work. how can I do that ? 
this is my repository : https://github.com/hashemirafsan/ACM_helper/blob/master/app.js

**Comment by riyadhalnur** [comment]
Hey @hashemirafsan. To run your app on a server, you need a `process manager` which will essentially run your app as a process just like any other app in an OS. There are tons of options to choose from but I like [pm2](https://github.com/Unitech/pm2) and [forever](https://github.com/foreverjs/forever). `forever` is simpler to get started while `pm2` is more powerful feature wise.
