### ISSUE TITLE
Debugging the node scripts

### ISSUE THREAD

**Issue by eswarreddyt** [nodeschool/discussions#194]
I am new to node.js and learning the node via the nodeschool programs.  While writting the solutions to the nodeschool assignments/exercises, I often find the need to debug the partially coded program and test. 

Please help me in identifying the tool/process to debug the code so that it would help me understand the code better and help in fast learning.

**Comment by martinheidegger** [comment]
Also there is a workshopper called [bug-clinic](https://github.com/othiym23/bug-clinic) now that may help.
