### ISSUE TITLE
-bash: javascripting: command not found

### ISSUE THREAD

**Issue by soggybag** [nodeschool/discussions#1941]
Just installed javascripting without error. When I try to run it I get: 

`-bash: javascripting: command not found`

**Comment by zhdzmn** [comment]
did you install the packege globally? with `-g` flag

**Comment by soggybag** [comment]
Yes. I can see the folder and run JavaScript from the folder with: 

/Users/username/.npm-global/lib/node_modules/javascripting/bin/javascripting

**Comment by MaxiDeMuro** [comment]
I can run Javascripting form that folder as well; Just wondering how to do it directly from my home user.
