### ISSUE TITLE
Need some help with the juggling async exercise

### ISSUE THREAD

**Issue by nnguyen01** [nodeschool/discussions#1947]
const http = require('http');
const bl = require('bl');
var urls = [process.argv[2], process.argv[3], process.argv[4]]
var results = []
count = 0;

for (var i = 0; i < 3; i++) {
    http.get(process.argv[2+i], function(response) {
	response.setEncoding('utf8');
	response.pipe(bl(function(err,data) {
	    if (err) {return console.error(err)}
	    results[i] = data.toString();
	    count++;
	    if (count === 3) {
		for (var i = 0; i < 3; i++) {
		    console.log(results[i])
		}
	    }
	}))
    })
}

This returns

1.  ACTUAL:    "undefined"
1.  EXPECTED:  "Grab us a roo to shazza got us some uluru. As cunning as a captain cook to as cunning as a blowie. As busy as a stubby holder my as stands out like cubby house. "

2.  ACTUAL:    "undefined"
2.  EXPECTED:  "Trent from punchy rollie with come a knock. Built like a gone walkabout mate watch out for the fisho. Shazza got us some stubby holder where as dry as a amber fluid. "

3.  ACTUAL:    "undefined"
3.  EXPECTED:  "Shazza got us some dipstick piece of piss as busy as a fairy floss. Watch out for the esky bloody gutful of dag. You little ripper freckle and as dry as a holden. Come a ace! flamin watch out for the dob. "

4.  ACTUAL:    ""
4.  EXPECTED:  "". 

I'm confused as to why it's printing undefined.

**Comment by davecocoa** [comment]
I recommend you add `console.log(i)` before `results[i] = data.toString();` to verify you're populating the correct element of the results array.
