### ISSUE TITLE
learnyounode - Exercise 5 - returns only 2 files 

### ISSUE THREAD

**Issue by x9t9** [nodeschool/discussions#1948]
It seems that my code somehow works, but it only outputs 2 files ( instead of expected 3 ) .

### Error output
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED

─────────────────────────────────────────────────────────────────

   "LICENCE.md"                        !=    "CHANGELOG.md"

   "README.md"                         !=    "LICENCE.md"

   ""                                  !=    "README.md"

                                       !=    ""


─────────────────────────────────────────────────────────────────
 ✗

 Submission results did not match expected!

 ✓

 Used asynchronous method: fs.readdir()

FAIL Your solution to FILTERED LS didn't pass. Try again!
```
### My Code
```js
var fs = require('fs');
var path = require('path');
var fileToRead = fs.readdir(process.argv[2], 'utf8', function(err, list){
    if(err){
        return console.error(err);
    }
	for (var i=2;i<list.length;++i){
		var noDot = process.argv[3];
		if (noDot===path.extname(list[i]).replace('.','')) {
		  console.log(list[i]);
		}
	}
});

```
So like above said, the program somewhat works ok, but it returns only 2 files ( "CHANGELOG.md" is missing from the list  ) 

What am I doing wrong ?

## Edit ##
Ok, so two minutes after opening the issue, I changed the line

`for (var i=2;i<list.length;++i){`
to
`for (var i=1;i<list.length;++i){`

and it works .
Seeing the solution I understand that I should have used `foreach` instead of for , but somehow I still do not understand why the i need to be `1` and not `2` if the first 2 arguments of `process.argv` are always fixed ( and I actually start from index `3`?

Surely I am missing something very primitive and fundamental here. .

**Comment by x9t9** [comment]
Ok, so two minutes after opening the issue, I changed the line 

`for (var i=2;i<list.length;++i){`
to 
`for (var i=1;i<list.length;++i){`

and it works .
Seeing the solution I understand that I should have used foreaach instead of for , but somehow I still do not understand why the `i` need to be `1` and not `2` if the first 2 arguments of `process.argv` are always fixed ( and I actually start from index `3`?

 Surely I am missing something very primitive and fundamental here. .

**Comment by davecocoa** [comment]
For JavaScript (and many other languages), indexing in arrays starts at zero instead of one. So the first two arguments are at index 0 and 1, that's why you need to start at 2.

**Comment by x9t9** [comment]
@davecocoa - that is exactly my point . if i start at `2` ( meaning skipping `0` && `1` ) - it is not working as expected, but if I start at `1` - it does . `1` should be the 2nd index - or am I wrong ?

**Comment by Pipmonm** [comment]
Starting at index = 2 applies to the 'process.argv[2]' portion of code while what you're talking about is the 'list' returned as an array and you should really have (var i=0;i<list.length;i++)  in standard style for enumerating that array.  I'm guessing that the only reason it works starting at 1 is because the first file name (index = 0) is simply not the right extension and so it doesn't matter that you missed it.

**Comment by x9t9** [comment]
@Pipmonm - Thanks . That is totally right. Somehow I did not even noticed that I am iterating a totally different array ( list ) .  Maybe should not do these exercises at 3 am ... :-) . so problem resolved for me .

However, it might still be some kind of an issue ( bug ? ) with the exercise, because , like you said , it should NOT work as expected with my code , but only with `for (var i=0..`
