### ISSUE TITLE
Javascripting Exercise 9 of 19 

### ISSUE THREAD

**Issue by trose7** [nodeschool/discussions#1953]
Hello I am just trying to complete the Compass(Lighthouse Labs) pre work for the full time bootcamp. 

In the "Javascripting Exercise 9 of 19 I can't determine the solution. Can anyone help me? I'm not sure if I need to post the question etc.?

Here is my attempt:

var fruit = 'orange';
fruit = fruit.toString(orange);
if (fruit > 5) {
  console.log('The fruit name has more that five charachters.');
} else {
  console.log('The fruit name has five charachters or less.');
}

Thank you!

**Comment by lvivier** [comment]
Hi @trose7, I think the challenge description is a bit overblown for this one :)

When the description says, "declare a variable named `fruit`. Make the `fruit` variable reference the value **orange** with the type of **String**.", all you need is the following:

```js
var fruit = 'orange'
```

You don't have to call the `toString()` method (it's already a string). Then in your if statement, compare [the length property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) of `fruit`:

```js
if (fruit.length > 5)
```

The length property of a string equals the number of characters, which is what you need to compare in this exercise.

Good luck with Lighthouse Labs—you're gonna love it!

**Comment by trose7** [comment]
Ah okay, that worked! Thank you very much for the help!

Yes, I'll be starting in January and am putting in the prep work now...
Thank you!

**Comment by trose7** [comment]
Hey sorry for the additional e-mail but while I was trying to do the next
exercise(10/19-creating a for loop)  I accidentally did something that
wouldn't allow me to enter commands in the bash line of my terminal
anymore.


I shut down Vagrant but now when I go to re-boot I get this error:

*An error occurred while downloading the remote file. The error*

*message, if any, is reproduced below. Please fix this error and try*

*again.*

*Couldn't open file /Users/trevorrose/base*

Do you know how I can fix Vagrant so that is running again?

**Comment by Sunslinger00** [comment]
I had a problem with this question too. Except I got an error. 

var fruit = 'orange';
if (fruit.length > 5)
{
console.log("The fruit name has more than five characters.");
} else {
console.log("The fruit name has five characters or less.");
}



 JAVASCRIPTING

## IF STATEMENT (Exercise 9 of 19)

Error: ERROR: /vagrant/javascripting/if-statement.js does not exist!
    at /home/vagrant/.nvm/versions/node/v6.3.1/lib/node_modules/javascripting/lib/run-solution.js:51:13
    at tryCallOne (/home/vagrant/.nvm/versions/node/v6.3.1/lib/node_modules/javascripting/node_modules/promise/lib/core.js:37:12)
    at /home/vagrant/.nvm/versions/node/v6.3.1/lib/node_modules/javascripting/node_modules/promise/lib/core.js:123:15
    at flush (/home/vagrant/.nvm/versions/node/v6.3.1/lib/node_modules/javascripting/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Sunslinger00** [comment]
@trose7 
try vagrant halt then vagrant up then vagrant ssh. Seemed to work for me when I had the problem. Took me awhile to figure it out (I even uninstalled everything and tried to start fresh, which didn't work)

Vagrant suspend didn't solve my problem.

**Comment by trose7** [comment]
1) Ok thank you for the help but when I run "vagrant halt" I get this
message:

*==> default: VM not created. Moving on...*

2) When I run "vagrant init" I get this message:


*`Vagrantfile` already exists in this directory. Remove it before*

*running `vagrant init`.*

*Trevors-MacBook-Pro:~ trevorrose$ *

3) Then when I run vagrant "ssh" I get this error:

*VM must be created before running this command. Run `vagrant up` first.*


All of this started when I edit the loop file(incorrectly) which I since
deleted.

**Comment by Sunslinger00** [comment]
@trose7 did you change your directory to lighthouse?

cd lighthouse then SSH into Vagrant.

Are you having a problem with accessing any of the modules? I can't get any of the module lists to drop down anymore. Just stuck at module 1. Tried on 2 laptops & different browsers.

**Comment by trose7** [comment]
Ah yes, that worked- thank you!

The modules are working for me so no problems there.

I want to attempt the loop problem again but don't want to crash the
machine.. Did you solve the loop problem by chance?

**Comment by Sunslinger00** [comment]
@trose7  That problem honestly took me 3 days to figure out. Vagrant and changing directories......... haha

For loop

var total = 0;
var limit = 10;
for (var i = 0; i < limit; i++){
  total +=i;}
console.log(total)

I had to search why { total +=i;} wasn't inside ()

**Comment by trose7** [comment]
Yeah, wow. I had no idea the {total +=i;] was outside the brackets.

Thank you for sending that though! Very much appreciated.

Happy New Year!

**Comment by trose7** [comment]
Hi sorry for the additional message but I am just now re-visiting this
problem:

Do you know why this code might not be working? thank you!

var total = 0;
var limit = 10;
for (var i = 0; i < limit; i++) {
  total += i; }
  console.log(total)

**Comment by noffle** [comment]
@trose7: what does "not working" mean? What happens when you try to run the program?

**Comment by trose7** [comment]
This is this the error I get! (see below) so I am not sure what that
means...

*{ Error: Command failed: node "/vagrant/for-loop.js"*

*/vagrant/for-loop.js:1*

*(function (exports, require, module, __filename, __dirname) { for (var
total = 0; var limit = 10; i++)
{
                                                            ^^^*

*SyntaxError: Unexpected token var*

*    at Object.exports.runInThisContext (vm.js:76:16)*

*    at Module._compile (module.js:513:28)*

*    at Object.Module._extensions..js (module.js:550:10)*

*    at Module.load (module.js:458:32)*

*    at tryModuleLoad (module.js:417:12)*

*    at Function.Module._load (module.js:409:3)*

*    at Module.runMain (module.js:575:10)*

*    at run (bootstrap_node.js:352:7)*

*    at startup (bootstrap_node.js:144:9)*

*    at bootstrap_node.js:467:3*

*    at ChildProcess.exithandler (child_process.js:202:12)*

*    at emitTwo (events.js:106:13)*

*    at ChildProcess.emit (events.js:191:7)*

*    at maybeClose (internal/child_process.js:852:16)*

*    at Process.ChildProcess._handle.onexit
(internal/child_process.js:215:5)*

*  killed: false,*

*  code: 1,*

*  signal: null,*

*  cmd: 'node "/vagrant/for-loop.js"' }*

**Comment by Sunslinger00** [comment]
Are you sure its exactly the same? It's the same as my code. I even checked it in Sublime and the grammar looks the same. Copy mine and use that. See if it changes.

**Comment by trose7** [comment]
Ok thanks for the response!

I'll run that and check.
