### ISSUE TITLE
Can't make it modular

### ISSUE THREAD

**Issue by PaulCezanneFMR** [nodeschool/discussions#1955]
### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

$ node -v
v6.9.2

$ npm -v
3.10.9

OS: OSX 10.11.6

### Error output

 Your additional module file [myModule.js] does not appear to pass back an
 error received from fs.readdir(). Use the following idiomatic Node.js
 pattern inside your callback to fs.readdir(): if (err) return
 callback(err)

### My Code
```js
var fs = require('fs');  
var pathModule = require('path');  

module.exports = function(pathName, suffix, callback) {
	//suffix = "." + suffix
    fs.readdir(pathName, 'utf8', function (err, content) {

    	if (err) return callback(err);
    	
		var matches = [];
		for (i = 0; i < content.length; i++) {
			if (pathModule.extname(content[i]) == suffix) {
				matches.push(content[i])
			}
		}
		callback(null, matches);
    })
}
```

Note the use of the 'utf8' parameter to readdir, that could be  what is messing this up. If I remove that, my code now fails with this error.

### Error Output

 Your additional module file [myModule.js] appears to be expecting a
 '.'-prefixed extension, it should receive the second command-line argument
 without the added '.'

 ### FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!

which isn't true since I'm not doing anything with "." in it.

And if I do prepend the "." to suffix my code doesn't give the correct output but at least it didn't complain about the readdir error checking!

I'll work on get the "." issue fixed.

**Comment by PaulCezanneFMR** [comment]
While debugging the "." issue I see that ".md" is passed in as the suffix so **that's why** prepending a "." doesn't work! LOL.

**Comment by PaulCezanneFMR** [comment]
Just an FYI, I've passed the lesson.

```js
var fs = require('fs');  
var pathModule = require('path');  

module.exports = function(pathName, suffix, callback) {

	suffix = suffix.replace(/(^\.+|\.+$)/mg, '');
        fs.readdir(pathName, function (err, content) {

    	if (err) return callback(err);
    	
		var matches = [];
		for (i = 0; i < content.length; i++) {
			// now remove the . from the pathname extension
			var sanitizedExt = pathModule.extname(content[i]);
			sanitizedExt = sanitizedExt.replace(/(^\.+|\.+$)/mg, '');
			if (sanitizedExt == suffix) {
				matches.push(content[i])
			}
		}
		callback(null, matches);
    })
}
```

But I'm leaving the issue open since the bug with 'utf8' should probably be addressed.

**Comment by misel6** [comment]
> But I'm leaving the issue open since the bug with 'utf8' should probably be addressed.

Thank you so much! I couldn't find the error in my code and felt like I was going mad. Removing 'utf-8' let my code pass.

**Comment by lacostenycoder** [comment]
using `replace(/\W/g, '');` to sanitize extension also passes.
