### ISSUE TITLE
Phoenix/Tempe, AZ Chapter?

### ISSUE THREAD

**Issue by parion** [nodeschool/discussions#1957]
I was looking through the NodeSchool chapters and was disappointed to not find one in the Phoenix/Tempe area in Arizona. Is there any interest for a chapter here? I'd love to start one up!

Thanks!

**Comment by monteslu** [comment]
Come to nodeaz, I could help you promote it.  https://www.meetup.com/nodeaz/

**Comment by nrn** [comment]
I'd be happy to show up and help mentor.

**Comment by parion** [comment]
Sweet, RVSP'd! Also, my apologies, I have no Idea there was a node.js group in the Tempe area!

**Comment by parion** [comment]
@nrn Really? That'd be awesome!
I'll leave this thread up since I'll need a couple more co-organizers to create a chapter. Hopefully I can find some excited people at NodeAZ! But if you could help mentor, I'd much appreciate it! 👍

**Comment by nrn** [comment]
Absolutely. Unfortunately, for me organizing drains some energy I just don't have right now. But mentoring the workshops is a pleasure. Feel free to hit me up for advice too!

**Comment by parion** [comment]
Update: Believe I found another co-organizer. Will be attending NodeAZ on February 20th to present my initial plans for a NodeSchool in the Phoenix/Tempe area as well look for another interested co-organizer or two and take feedback.  
Will get back to this thread afterwards.

**Comment by parion** [comment]
All discussion moved to this issue: https://github.com/nodeschool/organizers/issues/413
