### ISSUE TITLE
Mac: sudo npm start   error

### ISSUE THREAD

**Issue by xiaobeiying** [nodeschool/discussions#1964]
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.0.5
npm ERR! path /usr/local/bin/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

Details of npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.0.5
3 info using node@v6.9.4
4 verbose stack Error: ENOENT: no such file or directory, open '/usr/local/bin/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /usr/local/bin
6 error Darwin 16.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v6.9.4
9 error npm  v4.0.5
10 error path /usr/local/bin/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
15 error enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

Anyone have this problem? How to fix?

**Comment by mostlyerror** [comment]
@riyadhalnur do you have `package.json` file, as the error suggests?

**Comment by riyadhalnur** [comment]
@mostlyerror I think you meant to tag @xiaobeiying 😃

**Comment by mostlyerror** [comment]
Woops! sorry 🤓 @riyadhalnur
