### ISSUE TITLE
Juggling Async : solution passes sometimes but not always.

### ISSUE THREAD

**Issue by Hassanbhb** [nodeschool/discussions#1965]
Hello, i have figured a solution for the JUGGLING ASYNC challenge
but my code seems to pass sometimes and sometimes it doesn't.
can you help me to find why?

### My Code
```js
 // copy your code here
const http = require('http');
let results = [];
let count = 0;
let all = '';

function printResult(){
	for (var j = 0; j < 3; j++) {
		console.log(results[j]);
	}
}

function httpGet(index){
	http.get(process.argv[2 + index], function(res){
		res.setEncoding('utf8');
		res.on('data', function(data){
			all += data; 
			results[index] = all;
		})
		res.on('end', function(){
			count++;
			
			if (count === 3) {
				printResult();
			}
			all = '';
		})
		
	})
}

for (var i = 0; i < 3 ;i++) {
	httpGet(i);
}

```

**Comment by noffle** [comment]
Be careful: you're sharing the value of `all` across 3 asynchronous calls. What happens if two separate http requests run the `res.on('data', function (data) { ...})` code block one after the other before `res.on('end', ...)` is called?

**Comment by Hassanbhb** [comment]
aaha so that is why sometimes the text does not pass, i can't find a way to fix this right now maybe tomorrow. thank you for helping me understand.

**Comment by noffle** [comment]
If you search for "juggling async" on this repo's issues you'll find a wealth of others who have struggled with this problem in the past. You might find studying their problems and solutions helpful.
