### ISSUE TITLE
Juggling Async Question

### ISSUE THREAD

**Issue by ebertucc** [nodeschool/discussions#1968]
I just completed this exercise and reviewed the official solution, but there's still one aspect of the solution (both mine and the official one—mine is fairly similar) that I don't understand. (Official solution below for reference.)

Looking at the official solution, the callback functions determine whether to log to the console or not by checking `if (count === 3)`. Since the callbacks run asynchronously, but they all check the value of the global variable `count`, is it possible for this condition to never be met? The scenario I have in mind is one where the `http.get()` calls for the second and third URLs take a while to return responses, so that both callbacks are working with a value of `2` for `count`, and thus neither would print the results text.

Is that even possible? I guess what I'm really looking for is clarification on when asynchronous methods actually run, i.e. what the control flow looks like. Any help or reading recommendations on this would be appreciated.

```
var http = require('http')
var bl = require('bl')
var results = []
var count = 0

function printResults () {
  for (var i = 0; i < 3; i++) {
    console.log(results[i])
  }
}

function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(function (err, data) {
      if (err) {
        return console.error(err)
      }

      results[index] = data.toString()
      count++

      if (count === 3) {
        printResults()
      }
    }))
  })
}

for (var i = 0; i < 3; i++) {
  httpGet(i)
}
```

**Comment by noffle** [comment]
Great question, Ezra.

Yes, there are a few ways that `count === 3` may not be met:

1. One or more calls to `bl()` return an error. This will cause `return console.error(err)` to run and bail early before `count++` is run.
2. `req.pipe(bl(...))` encounters an error while streaming, such as a broken pipe (EPIPE). I'm not sure if `bl` captures stream errors or not, but if it doesn't neither `console.error(...)` nor `count++` will run. You'd need to listen for these on the HTTP `response` stream to capture these:

```js
response.on('error', function (err) { ... })
repsonse.on('unpipe', function () { ... })
```

(Loads more in the [NodeJS Streams documentation](https://nodejs.org/api/stream.html).)

You can, at least, rely on `http.get()` to always eventually call its callback with a `response`.

**Comment by ebertucc** [comment]
Thanks for the reply, Stephen.

I hadn't considered the cases you mention, but I see how they could lead to `count === 3` never being met. 

What I had in mind was a situation where there are no errors, but two of the callbacks were running at the same time on different threads, and neither one sees `count` as 3. After doing a bit more reading, I think I just had some misconceptions about the way asynchronous functions work in NodeJS—I thought they were executed simultaneously on multiple threads or something like that (which I now know is not the case).

**Comment by noffle** [comment]
Yep, you got it! All JS code runs from a single thread, which saves us a **lot** of mental energy in concurrency concerns.
