### ISSUE TITLE
Exercise 5 question 'FLTERED LS' learnyounode.

### ISSUE THREAD

**Issue by ghost** [nodeschool/discussions#1969]
Learnyounode in this exercise mentions that using Path module 

> would be helpful.

So I have this question about said exercise, do I _have_ to use 'path' module? I passed using it and it did not give me much headache. But... 

...first thing I tried, did actually give me one. I opted for not using 'path' module. I thought that, well, i can filter list with regexp, so why would I need to load whole module for that little task. Path module will return 'visible' extensions and that is what i need, already being fed nice strings.

Here is what I came up with the first time:
```javascript
var fs = require('fs');

var fileList, filteredFileList;
var regExExt = new RegExp('(^.*\\.('+process.argv[3]+'))', 'gi');

function checkExt (fileName){

	return regExExt.test(fileName);

}; 

fs.readdir(process.argv[2], function(err, list){

	if (err) throw err;

	fileList = list;
	filteredFileList = fileList.filter(checkExt);

	filteredFileList.forEach(function(e){
		console.log(e);
	})
	
});
```
So, here, every time 'LICENCE.md' is being thrown out by filter method. In controlled environment:

- regex101 matches that file name
- when i hardcode array of filename strings and try it all out, everything is fine

Does learnyounode purposely, somehow, make it that code fail to push me into using Path module or I am simply missing something?

**Comment by noffle** [comment]
`path` is a red herring: you want to remove the 'g' flag from your `RegExp`. This flag causes the test index in the string to be tracked, which is not what you want here. See [here](http://stackoverflow.com/a/1520853).
