### ISSUE TITLE
Stuck in 6 of 13 Make It Modular

### ISSUE THREAD

**Issue by webgast** [nodeschool/discussions#1970]
Howdy, I keep being stuck in exercise 6, Make it Modular. Learnyounode complains:

" Your additional module file [my_module.js] did not call the callback
 argument after an error from fs.readdir()"

running node version 4.1.1
running npm version 2.14.4

code is as follows:

`module.exports = function (dirname, extension, callback) {

    var fs = require('fs');
    var path = require('path');
    var dir =  dirname;
    var arr = [];
    
    function filter(data, ext) {
    	for(var x in data) {
            	if(path.extname(data[x]) == ext) {
    			    arr.push(data[x]);
            	}
    	}
        return arr;
    }
    
    callback = function(){} //this line seems not to make a big difference
    
    var doSomething = function(err, data) {
    	if(err) throw err;
    	var mitt = filter(data, extension);
    	if (err) throw callback(err); //so I call callback
    	callback(mitt); //and another for good measure
    };
    
    fs.readdir(dir, function(err, data){
        if(err) {
            return callback(err); //call!
        };

        doSomething(err, data);
    });
    
};`

### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by chasestarr** [comment]
Hey there, 
'callback' in the error message is referring to the argument being passed in on line 1.

Towards the middle of the code, callback is reassigned to a new function. 
Here: `callback = function(){} //this line seems not to make a big difference`
Have you tried removing that line?

**Comment by Rud156** [comment]
Remove the line:
 
callback = function(){} //this line seems not to make a big difference


You need to call your callback from the original file. my_module.js should not have the callback defined. my_module.js will only call the callback function in the original file if there is an error

**Comment by webgast** [comment]
I am not making any progress.. I use the modular.js file as container:

`var mm = require('./my_module');

var outcome = mm('/home/ubuntu/workspace/spoof', '.md', function(stuff) {
    for(var x in stuff) {
        console.log(stuff[x]);
    }
});`

and it includes my_module.js:

`module.exports = function (dirname, extension, callback) {

    var fs = require('fs');
    var path = require('path');
    var dir =  dirname;
    var arr = [];
    
    function filter(data, ext) {
    	for(var x in data) {
            	if(path.extname(data[x]) == ext) {
    			    arr.push(data[x]);
            	}
    	}
        return arr;
    }
    
    var doSomething = function(err, data) {
    	if(err) throw err;
    	var mitt = filter(data, extension);
    	if (err) throw callback(err);
    	callback(mitt);
    };
    
    fs.readdir(dir, function(err, data){
        if(err) {
            return callback(err);
        };
        doSomething(err, data);
    });
    

};

`

I use a folder with the dummy files:

CHANGELOG.md
LICENSE.md
README.md

Please help!

**Comment by Rud156** [comment]
Here's what I tried with your program:

my_module.js
```js
module.exports = function (dirname, extension, callback) {
    var fs = require('fs');
    var path = require('path');
    var dir = dirname;
    var arr = [];

    function filter(data, ext) {
        for (var x in data) {
            if (path.extname(data[x]) === '.' + ext) {
                arr.push(data[x]);
            }
        }
        return arr;
    }

    var doSomething = function (err, data) {
        if (err) throw err;
        var mitt = filter(data, extension);
        if (err) throw callback(err);
        callback(null, mitt);
    };

    fs.readdir(dir, function (err, data) {
        if (err) {
            return callback(err);
        };
        doSomething(err, data);
    });
};
```

modular.js
```js
var file = require('./my_module');
function callback(err, filteredList) {
    if (err)
        throw err;

    for (var i = 0; i < filteredList.length; i++)
        console.log(filteredList[i]);
}
file(process.argv[2], process.argv[3], callback);
```

Stuff I changed:
* Added ```'.'``` before ext in function filter in my_module.js. This is required as learnyounode expects you to handle the ```.``` before extensions in the modular file.
* Changed the callback in modular.js
