### ISSUE TITLE
how-to-npm #07 Package Niceties error

### ISSUE THREAD

**Issue by macogil** [nodeschool/discussions#1971]
Hello,

I'm stuck with how-to-npm excersise #7 "Package Niceties". I've followed all steps in guide but I get following error after doing how-to-npm verify:

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "i"
npm ERR! node v4.6.1
npm ERR! npm  v4.1.1
npm ERR! code E404

npm ERR! 404 missing : linclark
npm ERR! 404 
npm ERR! 404  'linclark' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@macogil/workspace'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

Uh oh!
It looks like something went wrong

Could you give some hint where the problem is?

Thank you!

**Comment by noffle** [comment]
Could you share the contents of your `package.json`?

**Comment by macogil** [comment]
{
  "name": "@macogil/workspace",
  "version": "1.0.0",
  "description": ",-----.,--.                  ,--. ,---.   ,--.,------.  ,------.     '  .--./|  | ,---. ,--.,--. ,-|  || o   \\  |  ||  .-.  \\ |  .---'     |  |    |  || .-. ||  ||  |' .-. |`..'  |  |  ||  |  \\  :|  `--,      '  '--'\\|  |' '-' ''  ''  '\\ `-' | .'  /   |  ||  '--'  /|  `---.      `-----'`--' `---'  `----'  `---'  `--'    `--'`-------' `------'     -----------------------------------------------------------------",
  "main": "server.js",
  "dependencies": {
    "@linclark/pkg": "^1.0.2",
    "async": "^0.2.10",
    "express": "^3.2.6",
    "linclark": "^1.0.2",
    "socket.io": "^0.9.17"
  },
  "devDependencies": {},
  "scripts": {
    "test": "node test.js",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/macogil/npm.git"
  },
  "bugs": {
    "url": "https://github.com/macogil/npm/issues"
  },
  "homepage": "https://github.com/macogil/npm#readme"
}

**Comment by macogil** [comment]
thank you!

**Comment by noffle** [comment]
Did you publish `@linclark/pkg` in an earlier step?

**Comment by macogil** [comment]
Sorry, I'm very new to node.js

What does "publish" @linckark/pkg mean?

In principle I've followed steps given by tutorial. Up to step 6 everything was Ok once checked with how-to-npm verify

**Comment by noffle** [comment]
> In principle I've followed steps given by tutorial.

In principle? Did you deviate? Therein may lie the answer to the issue. Does `@linclark/pkg` look familiar? Did you write anything like that in an earlier step? What happens if you remove that line from the `package.json`? You may discover the solution to your problem by repeating the first five steps without deviation, to see where you may have gone wrong.

**Comment by macogil** [comment]
Thanks for your help!. I've decided to start from scratch and everything went smooth!
