### ISSUE TITLE
Creating file in windows command line - access denied

### ISSUE THREAD

**Issue by DesDev** [nodeschool/discussions#1973]
* node version: 6.9.4
* npm version:  3.10.10
* os: windows 7

### Error output
```
 I started workshop named 'javascripting' and wanted to do introducion, when got to creating new .js file via my command line, windows security pops me window saying - 'these files can't be opened, windows security prevented one or more files from being opened'.
```

**Comment by Rud156** [comment]
Don't know about you but. In my case it shows ```Access is denied``` but the file is created. Are you using the command ```NUL> someFile.js``` ???

**Comment by DesDev** [comment]
Hahaha, you know what, I just solved it, the command was 'type NUL > something.js' buuuut.... i thought that 'type' wasn't a part of actual command lol. Nevermind then, it's solved :)

**Comment by Rud156** [comment]
Hahaha
