### ISSUE TITLE
Stuck in learnyounode #4

### ISSUE THREAD

**Issue by macogil** [nodeschool/discussions#1974]
I get a match of the result but verify won't pass because it says "Used synchronous method: fs.readFileSync()", but I'm using async callback readFile as you can see in my code:
```js
var path=process.argv[2];
var fs=require('fs');
fs.readFile(path, 'utf-8', function readone (data, err){
    if (err){
        console.log('Error');
    }else{
        var newLines=data.split('\n');
        console.log(newLines.length-1);        
    } 
});
```
Any hint on where the problem my be?

Thanks a lot!

**Comment by finnp** [comment]
Hey @macogil,

that seems like a weird error. However your arguments of the `readone` function are in the wrong order.
It should be `readone (err, data)`.

**Comment by macogil** [comment]
Hey @finnp,

Silly thing, I was using same code from previous excercise (got confused when renamed file). Also as you mentioned I confused function parameter's order.

Now I got it right. One step ahead!

Thanks!
