### ISSUE TITLE
Cannot verify Baby steps in Learnyounode labels: learnyounode labels: windows  

### ISSUE THREAD

**Issue by anthonyalvarez** [nodeschool/discussions#1976]
# Problem with an error message In Learnyounode, BABY STEPS (Exercise 2 of 13)
Following instructions but Node cannot verify program.js for BABY STEPS using command: 

* node version: v6.9.4
* npm version:  4.1.1
* os: Windows 10 Pro x64

## Error output
LEARN YOU THE NODE.JS FOR MUCH WIN!

BABY STEPS (Exercise 2 of 13)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────
```
   "[ 'J:\\\\Program Files\\\\nodejs\\\\node.exe'," !=    "16"                               
   "  'J:\\\\programming\\\\node.js\\\\program.js'," !=    ""                                 
   "  '13' ]"                          !=                                       
   ""                                  !=                                       
```
────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

FAIL

 Your solution to BABY STEPS didn't pass. Try again!

# My Code
program.js

`console.log(process.argv)`
```
c:\> learnyounode verify program.js
```

**Comment by dtung2008** [comment]
The question is asking one to sum up all the numbers put after command line programs. For examples, you can check with `node program.js 12 24`, the answer should be 36; with `node program.js 1 2 3`, the answer should be 6. (like a sum of all the numbers provided).

**Comment by kobiljonergashev** [comment]
so how sum them up?

**Comment by stephanoulaa** [comment]
hello, i am also wondering about this exercise....

at first i tried:
var num1 = +process.argv[2];
var num2 = +process.argv[3];
var result = num1 + num2;
console.log(result);

but this obviously only works for 2 inputs. How would i loop through any other numbers that could be inputted to get their sum?

**Comment by noffle** [comment]
Hey @stephanoulaa. `process.argv` is an *array*, so it can be stepped through using a `for` loop like any other array (you'll maybe also hear these called "lists"):

```js
var array = [1, 2, 3]
var sum = 0
for (var i = 0; i < array.length; i++) {
  sum += array[i]
}
console.log('sum is', sum)
```
