### ISSUE TITLE
Just started with Node.js

### ISSUE THREAD

**Issue by trojanhawrs** [nodeschool/discussions#1984]
Hi, just started looking at the first introduction for node.js, the javascripting module.

I downloaded the atom editor as instructed and it told me to write - console.log('hello'); - in an introduction file.

It congratulates me for verifying the file but I don't see any hello message in the prompt, guess I'm actually doing something wrong?

Thanks

**Comment by riyadhalnur** [comment]
Hi @trojanhawrs, kudos to you on your first steps to learning NodeJS. The `verify` command verifies if the program you wrote is correct and not in charge of running the program/script itself. If you want to run your script and see it action, you can do - 
```shell
> node introduction.js  
> Hello World!
```

**Comment by trojanhawrs** [comment]
Ah, thanks a lot - appreciate the quick reply!

I'm sure you'll see me back before the end of the tutorial

**Comment by riyadhalnur** [comment]
@trojanhawrs No problem at all and anytime.

**Comment by trojanhawrs** [comment]
Hi again, told you I'd be back!

Have inputed this code into atom for the second exercise and saved to variables.js

var example;
var example = 'some string';
console.log()

Says it's not right?

**Comment by riyadhalnur** [comment]
@trojanhawrs Haha, no problem. There's just one small mistake here. You're declaring the same variable twice. You need to delete line 1 or if you prefer to declare variables first and then assign it a value in the next line, then you need to delete the `var` keyword on the second line. Lastly, you need to pass the variable you declared into `console.log` so that it can print it out on the terminal screen.

So -
```js
var example;
example = 'some string';
console.log(example);
```

**or**

```js
var example = 'some string';
console.log(example);
```

**Comment by trojanhawrs** [comment]
That makes some kind of sense, thanks again

**Comment by trojanhawrs** [comment]
Any chance someone can give me a quick hand? Stuck on the for-loop tutorial, heres my code so far

var total = 0;
var limit = 10;
total += i;
for (var i = 0; i < 10; i++) {
  console.log(i)
}
console.log(total)

This is my result :

 Solution ===================

 45

 Your Attempt ===================

 0 1 2 3 4 5 6 7 8 9 NaN
