### ISSUE TITLE
learnyounode #9 Juggling Async not working

### ISSUE THREAD

**Issue by macogil** [nodeschool/discussions#1985]
Anyone can give a hint why this code is not working?. Thanks

var url1=process.argv[2];
var url2=process.argv[3];
var url3=process.argv[4];

var http=require('http');
var strData="";
var arrData=[];
var cont=0;

function displayData(){
   for (var i=0;i<3;i++){
      console.log(arrData[i]);
   }
   
}

function collectData(url){

var strData="";

http.get(url, function (response){
   response.setEncoding("utf8");
   response.on("data", function(data){
       strData+=data;
   });
   response.on("end",function(){
      arrData[cont]=strData;
      cont++;
      if (cont===3){
         displayData();
      }

   })
   response.on("error", function(error){
       console.log(error);
   });
});

}

collectData(url1);
collectData(url2);
collectData(url3);

**Comment by dtung2008** [comment]
There is one problem I spotted. The index of your arrData[] depends on the response order, and it is not necessary the same as the order of the calling URLs.

**Comment by macogil** [comment]
Thanks for the hint!!!

Allright!!!. Now I'm passing the array index to the function and it works just fine!!!

var http=require('http');
var strData="";
var arrData=[];
var cont=0;

function displayData(){
   for (var i=0;i<3;i++){
      console.log(arrData[i]);
   }
}

function collectData(url, index){

var strData="";

http.get(url, function (response){
   response.setEncoding("utf8");
   response.on("data", function(data){
       strData+=data;
   });
   response.on("end",function(){
      arrData[index]=strData;
      cont++;
      if (cont===3){
         displayData();
      }

   })
   response.on("error", function(error){
       console.log(error);
   });
});

}

for (var j=2;j<5;j++){
   collectData(process.argv[j], j-2);
