### ISSUE TITLE
Struggling with baby steps

### ISSUE THREAD

**Issue by trojanhawrs** [nodeschool/discussions#1986]
Just finished floundering my way through the javascripting tutorial and am now giving the node one a bash. It wants me to loop through a command line array but I can't work out how to make it add consecutive inputs. This is where I'm at just now

for (var i = [2]; i < [10]; i++) {
}
console.log(+process.argv[i])

It's still only giving me the first number i put in the command line :/

**Comment by DanFog** [comment]
@trojanhawrs if you store the object returned by process.argv into a variable you can then loop through that and store the sum. Something like below (with some changes) : 
`var argv = process.argv;
for( i = 2; i < argv.length; i++ {
     // code to add sum of inputs
}

//console log sums here
`
