### ISSUE TITLE
learnyounode HTTP UPPERCASERER

### ISSUE THREAD

**Issue by macogil** [nodeschool/discussions#1993]
Anyone knows why this code doesn't work?. Thanks!

I get following error message:

--------------------------  ERROR MESSAGE  ----------------------------

fs.js:540
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at ReadStream.open (fs.js:1673:6)
    at new ReadStream (fs.js:1660:10)
    at Object.fs.createReadStream (fs.js:1608:10)
    at Server.<anonymous> (/home/ubuntu/workspace/httpUpperCaserer.js:13:18)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:536:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
 ✗ 

 Error connecting to [http://localhost:44055](http://localhost:44055):
 socket hang up

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "DUNNY"                            
                                       !=    "FRECKLE"                          
                                       !=    "BUSH BASH"                        
                                       !=    "BUSH OYSTER"                      
                                       !=    "COBBER"                           
                                       !=    "SNAG"                             
                                       !=    "DRONGO"                           
                                       !=    "PASH"                             
                                       !=    "BITZER"                           
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✗ 

 Submission results did not match expected!

 # FAIL Your solution to HTTP UPPERCASERER didn't pass. Try again!

-------------------------   CODE  --------------------------------------------

var port = process.argv[2];

var file = process.argv[3];

var fs = require('fs');

var http = require('http');

var map = require('through2-map');

var server = http.createServer(function (req, res) {  

    var str = fs.createReadStream(file);

    str.pipe(map(function (chunk){
        return chunk.toString().toUpperCase();
        
    })).pipe(res);

});

server.listen(port)

**Comment by davecocoa** [comment]
Looking at your error stack trace, I can see the error was produced on line `13` of your program (`/home/ubuntu/workspace/httpUpperCaserer.js:13:18`). This line is `var str = fs.createReadStream(file);`. Reading your program, I can't see the variable `file` mentioned anywhere before that line, so I suspect it may not be defined. Maybe you could try `console.log(file)` before that line to make sure?

**Comment by macogil** [comment]
I is defined in line 2 "var file = process.argv[3];". But anyhow I already have this challenge solved!. Thanks for your help!
