### ISSUE TITLE
how can i send a json data from server to client without using express

### ISSUE THREAD

**Issue by linux08** [nodeschool/discussions#1994]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.

**Comment by linux08** [comment]
i am trying to build an API in node without using express,

https://github.com/linux08/appnoexpress,

i am having problem sending back  JSON data to the client

**Comment by linux08** [comment]
I want to build a rest API  with pure nodeJs  (no express),
I am having difficulty getiing the Json data

**Comment by riyadhalnur** [comment]
You can set the headers to the proper response type and stringify your data object to a JSON string before sending it over - 

```js
res.writeHead(200, {"Content-Type": "application/json"});
res.write(JSON.stringify(dataObj));
res.end();
```

**Comment by linux08** [comment]
I want a JSON object not a JSON string.

**Comment by riyadhalnur** [comment]
A JSON string is essentially a JSON object. You cannot send plain objects over HTTP as the response. On the client-side, once you have received the results from the server, you can parse the JSON response to a JS object and work on that.

**Comment by linux08** [comment]
Oooh tanks 
You just solved my problem.
