### ISSUE TITLE
I can't install packges with npm install {module name}

### ISSUE THREAD

**Issue by scvasquez19901024** [nodeschool/discussions#1998]
I am working in learnyounode tutorial.. In the excersice 12  http uppercaseer is neceseary to install the package (through2-map)  but when I carried on this process I got  errors. This only pass when I am working on learnyoumodule, in other folders I can to install packages..

this is the command that I use to iinstall the package: npm install through2-map 

the system throw the follow errors:

sergio@sergio-Dell-System-Inspiron-N411Z:~/Documents/freecodecamp$ npm install through2-map
npm ERR! Linux 3.13.0-107-generic
npm ERR! argv "/home/sergio/.nvm/versions/node/v5.0.0/bin/node" "/home/sergio/.nvm/versions/node/v5.0.0/b
in/npm" "install" "through2-map"
npm ERR! node v5.0.0
npm ERR! npm  v4.1.2
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:15443

npm ERR!     at Object.exports._errnoException (util.js:860:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:883:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:15443]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 15443 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sergio/Documents/freecodecamp/npm-debug.log

**Comment by hodorswit** [comment]
It sounds like your npm registry somehow got set to localhost and is no longer set to npmjs.org. Run this command and try again:

`npm set registry https://registry.npmjs.org`

**Comment by nl-x** [comment]
Is that as part of the how-to-npm course? Then check out this discussion https://github.com/nodeschool/discussions/issues/1772

(TL;DR: run exercise 2 again so the local webserver gets restarted.)
