### ISSUE TITLE
Learnyounode - Make It Modular

### ISSUE THREAD

**Issue by TC1987** [nodeschool/discussions#1999]
### Error output

 Your additional module file [mymodule.js] does not appear to pass back an
 error received from fs.readdir(). Use the following idiomatic Node.js
 pattern inside your callback to fs.readdir(): if (err) return
 callback(err)

### My Code
```js

program.js

var myModule = require('./mymodule');

myModule(process.argv[2], process.argv[3], function(err, files) {
    if (err) {
        return err;
    }

    files.forEach(function(file) {
        console.log(file);
    })
})

mymodule.js

var fs = require('fs'),
    path = require('path');

module.exports = function(filePath, ext, callback) {
    fs.readdir(filePath, 'utf8', function(err, files) {
        if (err) {
            return callback(err);
        }

        var filtered = files.filter(function(file) {
            return path.extname(file).slice(1) === ext;
        })

        callback(null, filtered);
    })
}

```

### Explanation

The wording of this problem is quite confusing. With the way I've written my solution, an error should be returned if a problem were to occur with readdir.

Any input is greatly appreciated. Thanks.

**Comment by hodorswit** [comment]
This is a false negative, the workshopper currently doesn't correctly handle the optional encoding parameter. If you remove the 'utf8' parameter it should pass:

```javascript
fs.readdir(filePath, function(err, files) {});
```
There is a PR submitted to fix this that is in limbo at the moment: https://github.com/workshopper/learnyounode/pull/437

**Comment by TC1987** [comment]
Thanks so much! The code has passed and I can stop pulling hair out now.

**Comment by hodorswit** [comment]
No problem! FYI, I've submitted a fix for this in the hopes that we can spare future generations from this angst 😀

**Comment by liamcloss** [comment]
Thanks for the tip Hodorswit, I've spent hours reading up on callbacks and modules... to them stumble across this.
