### ISSUE TITLE
Stream-adventure Transform lesson

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#2001]
Why does the through2 directions in the lesson seem to have no resemblance to the documentation on npm or anything else I've seen?

**Comment by m-onz** [comment]
I disagree...

through2: https://www.npmjs.com/package/through2 has more options... but its usage within stream adventure is the same as the README:

In binary mode:
`.pipe(through(function (chunk, enc, callback) {`

In Object mode:
`.pipe(through.obj(function (chunk, enc, callback) `
