### ISSUE TITLE
Where to begin?

### ISSUE THREAD

**Issue by AlchemicFate** [nodeschool/discussions#2007]
I am new here and trying to learn to code, and have finished the javascripting module, and was wondering where to go after that? I have done a few of the learn younode exercises but it feels like there is a gap of information that I am missing. I was wondering where to go next and if I am on the right path.

**Comment by ameenshake** [comment]
Really depends on the amount of javascript knowledge you have. Where exactly did you feel like there was a gap in your information during learnyounode? 

If I were to start from scratch, I would do: javascripting => Scope Chains & Closures => learnyounode 

If you want a stronger guide for javascript, try this book called [Eloquent Javascript](http://eloquentjavascript.net/).

**Comment by AlchemicFate** [comment]
I am starting from scratch.  When doing the learnyounode module, they were referencing things I wasn't familiar or had not done.  I kept looking back at the exersizes I had done with javascripting and it I hit a wall and didn't know if I was doing these in the wrong order.
Thank you for the book suggestion, I will look into it!

**Comment by ameenshake** [comment]
Could please be more specific, what exactly are some the things they referenced that you were not familiar with?  If I know that, I could probably give you more specific pointers.

**Comment by AlchemicFate** [comment]
When doing the second exercise, Baby-steps, they were telling about process.argv which I had a hard time grasping. I looked up the answer and spent some time trying to understand why the code would consistently give me different numbers but was somehow correct.

`var result = 0

for (var i = 2; i < process.argv.length; i++) {
  result += Number(process.argv[i])
}

console.log(result)`

When moving onto the 3rd module, about synchronous filesystem operations, it asked if I recalled if strings could be .split() which I had never been taught or come across.  I began to get really lost and I didn't want to keep continuing on and try to brute force my way through the exercises only learning how to copy instead of really knowing how to manipulate javascript.

At the moment, I am just working off the nodeschool list and don't have any more materials. Is there anything you would recomend or to look into?

**Comment by ameenshake** [comment]
What level of programming knowledge do you have? Is Javascript your first? It seems like you need to dive deeper into javascript before attempting to learn node. I would again recommend the book I mentioned above: [Eloquent Javascript](http://eloquentjavascript.net/), especially if you are new to programming. Another resource that I liked is [FreeCodeCamp](https://www.freecodecamp.com). I would do their Basic Javascript challenges, then Object Oriented and Functional Programming and maybe even the algorithm challenges. If you are short on time, then go for FreeCodeCamp, it should give you a good enough foundation to start learning node.js. However, there would be gaps in your knowledge so I would still go back and read through the book. 

As for your `process.argv`, do you know how command lines work? If not, try this [tutorial](https://www.learnenough.com/command-line-tutorial). Also, `process.argv` is a node.js thing. It creates an array containing the command-line. If sure you know that you can run your node.js programs from the command-line, right? To run your program, you type `$ node yourprogram.js` if `yourprogram.js` is in the current folder. `process.argv` captures the commands used to run the node.js program and put them in an array for you to use. Therefore, `process.argv[0]` will always say `node` or give a path to node. `process.argv[1]` will always give the path to your node.js program. `process.argv[2]`....`process.argv[n]` will be the command-line arguments used when running the code. Therefore, for `$ node yourprogram.js 1 2 3 `,  `process.argv[2]` will equal to `1`, `process.argv[3]` will equal `2` and `process.argv[4]` will equal `3`.

**Comment by AlchemicFate** [comment]
I have a very minimal knowledge, I took a C++ class in college a couple of years ago, but I only remember some of it. Thank you for the books and website! I will be sure to use them. I don't need to rush at so I'll go through the material. As for the nodeschool exercises, I am a bit confused as to the order in which do them. 
I will probably end up coming back to node.js after I learn a bit more.
Thank you for the explanation, I am sure I will understand it more fully as I delve deeper into the book and Javascript.

**Comment by ameenshake** [comment]
I would lay off nodeschool for now if I were you. Learn your fundamentals more and then come back and do the learnyounode lesson. Once you complete learnyounode, order doesn't really matter imo as they are all supplementary.

**Comment by AlchemicFate** [comment]
Thank you for your advice! I'll probably come back here once I am more prepared! I really appreciate it!
