### ISSUE TITLE
Stuck on learnyounode exercise 5

### ISSUE THREAD

**Issue by AJTMCCANN** [nodeschool/discussions#2015]
My problem is I can't even seem to log the files at all, much less filter them.  The only clue I have is the DeprecationWarning.  Could that have something to do with it?  Can anyone help?

### My setup

* node version: 7.4.0
* npm version:  4.0.5
* os: windows 10

### Error output
```
(node:1376) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

### My Code
```js
var fs = require('fs')
var path = require('path')

var dir_to_list = process.argv[2]
var filter = process.argv[3]

function list_files() {
	fs.readdir(dir_to_list, (err, files) => {
		if (err) { return console.error(err) }
		console.log(files)
	})
}	
```

**Comment by noffle** [comment]
It looks like you've defined `list_files` but aren't calling it: add `list_files()` at the bottom of the file to run the (lovely) function you've written.

**Comment by ahmedzaky030** [comment]
as @noffle  said  that you need to call the function that you created or  you can remove the function declaration and start directly with fs.readdir()......
