### ISSUE TITLE
Make It Modular and throwing "err", where to do it?

### ISSUE THREAD

**Issue by wheelsofsteel** [nodeschool/discussions#2024]
Hey guys, 

So I'm a bit of a noob to this whole server-side business and everything seems to be a bit topsy-turvey!.

I am currently failing the verify because I have not included the code to throw an error if (err). The trouble is, I have no idea where to put the code (I've tried everywhere but have left it out of the code below for clarity purposes).

I have a very slight grasp of callbacks which is more than likely my downfall.

Here is what I currently have:

**task5.js**

```
var mymodule = require('./task5module.js');
var path = process.argv[2];
var format = process.argv[3]; 
mymodule(path, format);
```

**task5module.js**

```
var fs = require('fs');

module.exports = function(path, format, formatFilter) {
  format = "." + format;
  fs.readdir(path, function formatFilter(err, myData) {
  	for(var i = 0; i < myData.length; i++) {
  		var element = myData[i];
  		if(element.indexOf(format) !== -1) {
  			console.log(myData.splice(i, 1).toString());
  			i--;
  		}
  	};
  });
}
```

Interestingly, I also thought I wasn't supposed to console.log the data from the module file. So I wanted to have the module file return an array and use console.log(mymodule(path, format)) in my main file but it didn't work at all. For example: 

```
var fs = require('fs');

module.exports = function(path, format, formatFilter) {
  format = "." + format;
  var list = [];
  fs.readdir(path, function formatFilter(err, myData) {
  	for(var i = 0; i < myData.length; i++) {
  		var element = myData[i];
  		if(element.indexOf(format) !== -1) {
  			list.push(myData.splice(i, 1).toString());
  			i--;
  		}
  	};
  });
 return list;
}
```

Followed by console.log(mymodule(path,format)) in the task5.js file.
But, It didn't work, ha.

Thanks again guys.
Steve

**Comment by noffle** [comment]
Hi Steve. Yes, I think you're correct that your understanding of callbacks and the flow of asynchronous code is what's hindering you.

---

Consider `setTimeout`: a very simple asynchronous function. It takes two parameters: a callback and a delay:

```js
setTimeout(fn, delay)
```

In use, it might look something like this:

```js
setTimeout(onDone, 1000)

function onDone () {
  console.log('done')
}
```

You can try running this by saving it into a file named e.g. `timeout.js` and then running `node timeout.js`. Remember that the following is equivalent to what's above, with the function inlined as a parameter:

```js
setTimeout(function () {
  console.log('done')
}, 1000)
```

---

I could create a module called `wait_and_announce.js` that wraps this functionality:

```js
module.exports = function (delay) {
  setTimeout(function () {
    console.log('done')
  }, delay)
}
```

It could be used in another file like this:

```js
var waitAndAnnounce = require('./wait_and_announce')

waitAndAnnounce(2000)
```

This would wait for 2 seconds and then write `done`.

What if I wanted to write another message once it completes? Like `huzzah!`? Maybe I could just do..

```js
var waitAndAnnounce = require('./wait_and_announce')

waitAndAnnounce(2000)

console.log('huzzah!')
```

If you run this, you'll see

```
huzzah!
done
```

Why did `huzzah!` come first?

When you run an asynchronous function (like `setTimeout`), generally its code will run at some point "in the future", and regular code execution continues. You can see this here: `setTimeout` gets called in `wait_and_announce.js` and then `console.log('huzzah!')` runs. Then, at some point later, the timeout finishes and the function inside `setTimeout` runs.

To run code AFTER an asynchronous function runs, we can give it a "callback". This is a function object that the function you're giving it to can run once it's finished. In fact, the function I handed to `setTimeout` is a callback.

Here's `wait_and_announce` again, but with a callback as a parameter that's called once the function is finished:

```js
module.exports = function (delay, callback) {
  setTimeout(function () {
    console.log('done')
    callback()
  }, delay)
}
```

Now I can modfy my original main program like so, to write `huzzah!` after `done`:

```js
var waitAndAnnounce = require('./wait_and_announce')

waitAndAnnounce(2000, onDone)

function onDone () {
  console.log('huzzah!')
}
```

Run it; you'll see `done` followed by `huzzah!`. Like before, this is equivalent to inlining the callback:

```js
var waitAndAnnounce = require('./wait_and_announce')

waitAndAnnounce(2000, function () {
  console.log('huzzah!')
})
```

**Comment by wheelsofsteel** [comment]
@noffle Fantastic answer and very appreciated.

I finally passed the module. It's just a very difficult concept for the try to pass the data from one function to the other using callbacks etc. But, I'll persist. If people could tell me if this is the simplest way of doing it, I would be very pleased:

```
var mymodule = require('./task5module.js');
var path = process.argv[2];
var format = process.argv[3];

mymodule(path, format, function(err, myData) {
  for(var i = 0; i < myData.length; i++) {
    console.log(myData[i]);
  }
});
```

```
var fs = require('fs');
module.exports = function(path, format, callback) {
  fs.readdir(path, function(err, myData) {
    if(err) return callback(err);
    format = "." + format;
    var list = [];
    for(var i = 0; i < myData.length; i++) {
  		var element = myData[i];
  		if(element.indexOf(format) !== -1) {
  			list.push(myData.splice(i, 1).toString());
  			i--;
  		}
    };
    callback(err, list);
  });
}
```

**Comment by noffle** [comment]
If I understand you correctly: the names aren't being copied; you just happened to use the same variable name. You could have wrote:

```js
var mymodule = require('./task5module.js');
var path = process.argv[2];
var format = process.argv[3];

mymodule(path, format, function(err, names) {
  for(var i = 0; i < names.length; i++) {
    console.log(names[i]);
  }
});
```

and kept the other file the same. Consider this example, which is has the same control flow as your code, but without much of the other logic that's going on:

```js
var mymodule = require('./task5module.js');

mymodule(function(err, data) {
  for(var i = 0; i < data.length; i++) {
    console.log(data[i]);
  }
});
```

```js
module.exports = function(callback) {
  var list = [1, 2, 3, 4];
  callback(err, list);
}
```

It takes some time to wrap your head around. Keep at it! :)

**Comment by wheelsofsteel** [comment]
@noffle Thanks again for replying. It's hard to explain my logic, so I'll demonstrate it in code ;).

I thought this is how it worked:

```
module.exports = function(x, y, callback) {
    console.log(foo + bar);
}
```

````
var mymodule = require('module');

mymodule(200,200, function(foo, bar) {
    foo = "Hello ";
    bar = "World";
});
```

But in reality it is this:

``` 
module.exports = function(x, y, callback) {
  return callback("hello ", "world");
}
```

```
var mymodule = require('./testmodule.js');

mymodule(200,200, function(foo, bar) {
  console.log(foo + bar);
});
```

I thought that you could pass the predefined parameters to the module function as opposed to the module's function returning a definition. I... guess that's why it's called a callback? Haha...

Anyway, a good learning experience.

**Comment by noffle** [comment]
Yep, you've got it!
