### ISSUE TITLE
Juggling Async Question

### ISSUE THREAD

**Issue by wheelsofsteel** [nodeschool/discussions#2025]
Hey again!

If I understand this task correctly: We want the HTTP Requests to return the information in the same order that the URLs were passed in. However, the server will naturally return whichever request is finished with first, so therefore the order is not guaranteed to be the same as the order of the URLs passed in.

Therefore, we can wait until a HTTP request has finished and push it into an array (in my example: "buffer") at the index that matches the same index in the url array? (So buffer[0] would be the correct data for url[0]). Right?

I 'think' my code will work below except there is an issue that I am getting 'undefined' values creeping into the buffer array. I assume that this is because i am pushing the data into the buffer array before the HTTP request has returned anything? I tried to remedy this by adding the if(chunk !== undefined) but it hasn't worked.

What's the flaw in my logic here?

```
var http = require('http');
var url = process.argv.splice(2);
var buffer = [];

function printResults() {
  for(var i = 0; i < buffer.length; i++) {
    console.log(buffer[i]);
  }
}

url.forEach(function(element, i) {
  http.request(element, function(response) {
    response.setEncoding('utf8');
    var str = '';
    response.on('data', function(chunk) {
        if(chunk !== undefined) {
          str += chunk;
        }
    });

    response.on('end', function() {
      buffer[i] = str;

      if(buffer.length === url.length) {
        printResults();
      }

    })

    response.on('error', console.error);
  }).end();
})
```

**Comment by noffle** [comment]
You're on the right track. I think you're being tripped up by how arrays work in Javascript. Try this example:

```js
var buffer = []
console.log(buffer.length)
buffer[2] = 7
console.log(buffer.length)
```

This might shed some light on why your condition around `printResults()` might be firing early.
