### ISSUE TITLE
'Juggling Async' tutorial - incomplete answer accepted as correct issue

### ISSUE THREAD

**Issue by adisonjames** [nodeschool/discussions#2026]
Hi,

Thank you for providing the 
learnyounode tutorial. 

Just getting past the 'Juggling Async' and I have coded an incomplete answer shown below: 

```
var http = require('http');
var concatStream = require('concat-stream');

var url1 = process.argv[2];
var url2 = process.argv[3];
var url3 = process.argv[4];

var urlCount=0;


function getUrl(urlNum, concatData){
	http.get(urlNum, function getResponse(response){
		response.pipe(concatStream(function getData(data){
			concatData(data);
		}));
	});

}
function concatData(concatData){
	urlCount++;
	console.log(concatData.toString());
}

getUrl(url1, concatData);
getUrl(url2, concatData);
getUrl(url3, concatData);
```

where get requests are completely concatenated for the 3 urls, but it does not display them in the console in the correct order (just displays them to the console in the order of completely concatenated strings that have been returned).

there should be additional logic for retaining which url was returned and displaying them in the correct order (which I am about to add) but the tutorial still verified me as having the correct answer.

just a quick heads up!

attaching screenshots of two consecutive verify runs with the same code:

1. correct verification
![image](https://cloud.githubusercontent.com/assets/6829451/23570538/ea63968a-00a7-11e7-9827-28d1869817d6.png)

2. incorrect verification
![image](https://cloud.githubusercontent.com/assets/6829451/23570548/fac6aec2-00a7-11e7-8a6a-aee28dd5da6d.png)

**Comment by itsjtwright** [comment]
A fix might be running the test 3 or 4 times, making sure it passes every time? There still might be an incomplete answer that gets through, but it would be less.

**Comment by adisonjames** [comment]
​I had left the post so that the verification code might be edited.

I chugged through to the next tutorial - thanks for your reply! =)
