### ISSUE TITLE
Problem connecting to the localhost

### ISSUE THREAD

**Issue by deven810** [nodeschool/discussions#2027]
Hey guys

So I got this same problem with every time I create the server. I'm not sure if the code is correct, but it seems to part of the problem, however, I commented it out and it still didn't connect, giving the same problem. The localhost port keeps changing everytime I run this because a different URL is sent so that's nothing to worry bout. I got a problem with the previous exercise too, but somehow changing the connects of the createserver(function callback) callback fixed it. Idk what is happening. Please help! Thank you! 
### If you have a problem with an error message:

* node version: v6.9.1
* npm version:  4.3.0
* os: windows 10

### Error output

  ```✗  Error connecting to (http://localhost:53907): read ECONNRESET```

### My Code
```var http = require('http')
var map = require('through2-map')

var server = http.createServer(function getPOST(req, res) {
  if(req.method=='POST') {
    req.on('data', function (data) {
      data.pipe(map(function (chunk){
        return chunk.tostring().toUpperCase()
      })).pipe(res)
    })
  }
})
server.listen(Number(process.argv[2]))

**Comment by hodorswit** [comment]
ECONNRESET implies that the connection was abruptly closed by the server. I've seen this happen when the server emits an error event that does not have an associated listener. Try adding a listener for the 'error' event on the server and see if it gives you a more meaningful error:

```js
server.on('error', function(err){
  console.error(err)
})
```
