### ISSUE TITLE
goingnative "Am I ready?" the very first challenge

### ISSUE THREAD

**Issue by PabloVent** [nodeschool/discussions#2036]
### Notes
I am trying to get the environment ready for the goingnative challenges but all I get is some errors which I have copied and pasted below.  They are all related to gyp.  The goingnative version I am using is goingnative@2.0.7.  Perhaps I need a more stable node version looking at the errors

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Pablo\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pablo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Pablo\~test-addon.7270
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
✗ Could not compile test addon
```

### My Code
```js
 // copy your code here
```

**Comment by giovannigiordano** [comment]
Try updating node-gyp.
```
npm install -g node-gyp@latest
```

**Comment by PabloVent** [comment]
Thx
