### ISSUE TITLE
Need help: Javascripting Lesson #2 (Variables)

### ISSUE THREAD

**Issue by makye** [nodeschool/discussions#2037]
Could someone help me why my code isn't generating the output "some string"? Just started to learn, thanks so much.

### My Code: 

var example = 'some string';
console.log('example');

### Error output:
Solution ===================

 some string

 Your Attempt ===================

 Difference ===================

 some string

**Comment by jinsyaoommen** [comment]
No single quotes needed around `example` when you console.log out the variable. 
`console.log(example)`
