### ISSUE TITLE
Array doesn't obtain values.

### ISSUE THREAD

**Issue by shivamarora13** [nodeschool/discussions#2040]
What is the problem with my code, why array doesn't obtain the result, but when I console data directly, results are just fine?

* node version: v7.3.0
* npm version:  3.10.10
* os: mac

### Error output
$ learnyounode run jugglingAsync.js
undefined
undefined
undefined

### My Code

var http = require('http');
var urls = [process.argv[2],process.argv[3],process.argv[4]];
var bl = require('bl');
var op = [];

for(var i=2;i<5;i++){
	http.get(process.argv[i],function(response){
		response.setEncoding('utf-8');
		response.pipe(bl(function(err,data){
			if(err){
				console.error(err);
			}else{
				op[i-2] = data.toString();
			}
		}))
	})
	console.log(op[i-2]);
}

**Comment by milesibastos** [comment]
That's in portuguese but I hope to help you
![https://asciinema.org/a/108788](https://cdn-images-1.medium.com/max/800/1*F2qcuKGC33077aTFhYjfNg.gif)
https://asciinema.org/a/108788
