### ISSUE TITLE
exercise 4 of 19

### ISSUE THREAD

**Issue by firebase007** [nodeschool/discussions#2042]
hi guys, please i'm having issues with the 4th exercise. please help... thanks
 // copy your error output here
## Check your solution:

 Solution ===================

 14

 Your Attempt ===================

 example string

 Difference ===================

 14example string

### My Code
```js
 // copy your code here
var example= 'example string';
example.length
console.log(example.length)

**Comment by milesibastos** [comment]
That's in portuguese but I hope to help you
![https://asciinema.org/a/107512](https://cdn-images-1.medium.com/max/800/1*3UaiGld_0gA3EiF52DAfEg.gif)
https://asciinema.org/a/107512

**Comment by firebase007** [comment]
thank you. it was helpful.
