### ISSUE TITLE
Exercise 03 My First I/O, readFileSync Does Not Work

### ISSUE THREAD

**Issue by imacomputanerd** [nodeschool/discussions#2045]
I know we are instructed not to create a test file, but I did and want to know why I can't read it. Any help is appreciated.

See in the screenshot. On the right is a text file called ```03.txt```
On the bottom-left is my code in ```03.js``` that reads the text file.
On the top-left is the error thrown when I try to run ```03.js```
The error says that there is no such file, but the path ```C:\Users\bmahler\Tutorials\Node.js\HelloWorld``` is correct.

![activity 03 trouble](https://cloud.githubusercontent.com/assets/3085781/24310023/d2d3587e-1093-11e7-9dcd-bb7dcc4f6cea.PNG)

How do I read the text file?

**Comment by imacomputanerd** [comment]
I'd like to apply the learnyounode label to this issue, please let me know how to do that. It says in the guidelines that only owners can do that though.

**Comment by milesibastos** [comment]
That's in portuguese but I hope to help you

![https://asciinema.org/a/107351](https://cdn-images-1.medium.com/max/800/1*C1YWVQhFAGHP_7Cbyjl3dQ.gif)
https://asciinema.org/a/107351

**Comment by davecocoa** [comment]
This is a wild guess, but maybe your text file is actually named `03.txt.txt`. Notice how the windows file explorer omits the `.js` suffix on your JS files, perhaps it is also hiding an additional `.txt` suffix on your text file.

To diagnose, could you list the files in that folder from the terminal / command prompt? You can list files by running the command `dir`, then we will get a definite idea of the file name.
