### ISSUE TITLE
Chain Mail - Why value()

### ISSUE THREAD

**Issue by haraldkubota** [nodeschool/discussions#2047]
For the Chain Mail exercise, I don't understand why I got away without .value() at the end?

My code (which passes):
```
var worker = function(coll) {
	return _.chain(coll)
		.map(function(x){return x+"CHAINED"})
		.map(function(x){return x.toUpperCase()})
		.sort();
};
```
Official solution:
```
var wordsmodify = function (arr) {
    return _.chain(arr)
      .map(function (item) {
        return item + 'Chained';
      })
      .map(function (item) {
        return item.toUpperCase();
      })
      .sortBy()
      .value();
};

```
Reading LoDash docs https://lodash.com/docs/4.17.4#prototype-value seems to make a value() call necessary chen using _.chain(). Or is .value() optional in some cases?

**Comment by riyadhalnur** [comment]
Hi @haraldkubota, good question. `.value()` is not optional if you intend to chain methods in lodash but there's a helper method - `_(value)`  - which creates and object to implicitly wrap chained methods and unwraps the value. The verifier in *lololodash* does that when verifying so even if you don't type `.value()` in your code, it will still unwrap for you. This begs the question whether we should be doing that in the first place.

**Comment by haraldkubota** [comment]
Thanks for the explanation!
