### ISSUE TITLE
15 Rm solution

### ISSUE THREAD

**Issue by ionakathryn** [nodeschool/discussions#2048]
Hi I can't seem to solve exercise 15 of how to remove all dependencies. I've used npm rm and npm rm --all and there are no dependencies listed in my json package file - is this a bug? I can't get rid of the message:

"Looks like there are some deps still hanging around"

Appreciate if someone can help, thanks!

**Comment by m-onz** [comment]
try running
`npm cache clean`

**Comment by MrJkmullen** [comment]
What did that command do?

**Comment by ionakathryn** [comment]
I think the bug is still there. Will have a look later and see if this is still the case.

**Comment by ShyamVKansagra** [comment]
I am facing the same issue. I tried [these](https://stackoverflow.com/questions/13066532/how-to-uninstall-npm-modules-in-node-js) solutions, but still getting the same message saying: Looks like there are some deps still hanging around.

**Comment by jjprevite** [comment]
I'm also facing this issue and still getting the message "Looks like there are some deps still hanging around." The only way to make it pass was to manually delete the dependencies from my package.json file.

**Comment by NuclearBlast** [comment]
I faced similar issue and solved it after some struggles.
You have to type `npm rm @linclark/pkg ` instead of`npm rm`
