### ISSUE TITLE
"My First Async IO" - issue

### ISSUE THREAD

**Issue by manny-k** [nodeschool/discussions#2057]
Hi everyone, could you please help me understand what's wrong here? The problem - I think - lies in here:

```js
var myString = fs.readFile(process.argv[2], "utf8", callback);
```

The variable myString isn't actually a string but undefined. I don't know though how to resolve the issue. Do you have any pointers?

I'm grateful for any help!

### My Code:
```js
var fs = require("fs");

var myString = fs.readFile(process.argv[2], "utf8", callback);

function callback (err, data) {
     if (err === false) {
        return data;
    } 
}


var num = myString.split("\n").length;
        
num -= 1;
        
console.log(num)
```

**Comment by davecocoa** [comment]
You're right, `fs.readFile` does not return anything. If you want to see the contents of the file, you'll have to look in the `data` parameter passed to your `callback` function. I recommend using `console.log` to see the value of both `data` and `err` at the start of that function.

At the risk of ruining the suspense, let me explain that `err` will not be `false` if there are no errors, it will simply be `undefined`. It is a common pattern to put `if(err) { return console.log(err); }` at the start of callback functions - this is a check for "truthiness" as opposed to a direct comparison to `false`.

**Comment by manny-k** [comment]
@davecocoa thanks a lot, that helped. I've made the necessary changes but I still run into the same issue:

```javascript
var fs = require("fs");

var myString = fs.readFile(process.argv[2], "utf8", callback);

function callback (err, data) {
     if (err) {
        return console.log(err);
    } 
    return data;
}

var num = myString.split("\n").length;
        
num -= 1;
        
console.log(num)
```

What else am I missing?

**Comment by davecocoa** [comment]
You're getting closer!

I'm afraid the structure you have won't work though. Your `callback` function is indeed returning `data`, but this is altogether a different thing from `fs.readFile` returning anything - `fs.readFile` will never return anything.

Hopefully it's helpful to imagine the definition of `fs.readFile` like this:
```js
function readFile(filePath, encoding, callback) {
  var fileContents = "123\n456"; // this is of course, an imaginary definition!
  callback(undefined, fileContents);
  return undefined;
}
```
This imaginary definition matches the behaviour of `fs.readFile` fairly well but there is one important difference - `fs.readFile` will not call your `callback` function immediately. Instead, your `callback` function is called at some later stage.

**Comment by manny-k** [comment]
Why will fs.readFile never return anything? Shouldn't it return a string type variable?

I've went back and forth now and tried a view things and came up with this - but still there's something wrong.

```javascript
var fs = require("fs");

var myString = ""

fs.readFile(process.argv[2], function (err, data) {
     if (err) {
        return console.log(err);
    }
    
        return myString = data.toString();
    
});

var num = myString.split("\n").length;
        
num -= 1;
        
console.log(num)


```

**Comment by davecocoa** [comment]
`fs.readFile` will never return something because it is asynchronous. This means it has some work it must continue doing after the function returns. The file contents is not ready at the time the function returns, so instead of returning something, it calls the function `callback` with the result of its work.

This is the confusing but important thing to grasp about asynchronous functions in JavaScript - you will only be able to access the result of the operations *inside* the callback function.

**Comment by manny-k** [comment]
Thank you very much, this was pretty much exactly what I was missing. The fact that I'm only able to access the result **inside** the callback function wasn't clear to me. Thanks again; I really appreciate the way you made me think and didn't just tell me the answer 👍
