### ISSUE TITLE
Why i can't install javascript

### ISSUE THREAD

**Issue by Jackdaw93** [nodeschool/discussions#2061]
C:\>npm install -g javascriptng
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascriptng"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.8.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

i have this error when im going install npm -g javascripting

please help

**Comment by Jackdaw93** [comment]
#Error Intalling

**Comment by Duplicated** [comment]
First off, you made a typo. You forgot the second "i" in javascripting. This is what you typed it (based on what you wrote): `C:>npm install -g javascriptng`

If that's not the problem, check that you're actually connected to the internet.
