### ISSUE TITLE
Update to learnyounode version (3.5.8 to 3.5.10) fails

### ISSUE THREAD

**Issue by gyoungdahl** [nodeschool/discussions#2070]
So as part of my efforts in chasing another problem I was having with the "Make It Modular" exercise, I noticed the "Check For Update" option in the lower section of the main learnyounode menu and gave that a try in case it might have some impact on the problem I was encountering.  Apparently it failed to update (the error messages seem to indicate that, of course, but if I try to check for updates again it still reports it is at 3.5.8 and tries to update to 3.5.10).

Although it looks like my difficulty with the "Make It Modular" exercise is not likely related to this, it might be nice to understand (and presumably resolve) the problem with getting the latest version of the learnyounode package on my system.

Thanks,
--
AETLM

### If you have a problem with an error message:

* node version: v6.9.4
* npm version:  3.10.10
* os: windows 7

#### Here is what is left on my screen after the attempt to update:  ####

 # LEARN YOU THE NODE.JS FOR MUCH WIN!

  learnyounode@3.5.8 is out-of-date, updating to 3.5.10 with

     npm install learnyounode@latest -g

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

C:\Greg\WebDev\JavaScript\NodeSchool\learnyounode>

### My Code
I have no code associated with this issue.

**Comment by giovannigiordano** [comment]
Have you tried to run command as Administrator?

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
Hi giovannigiordano,

    My user account is reflected as an Administrative account, according to the control panel's "User Accounts" application.  Is that sufficient, or is there something specific to do to run the update as Administrator?  I assume I'd have to run the whole "learnyounode" application as administrator, if that is the issue, since the update is just a menu selection from that app.

Thanks
--
AETLM
