### ISSUE TITLE
After installing a learnyou tutorial via npm, how do you start thte tutorial? 

### ISSUE THREAD

**Issue by restycena** [nodeschool/discussions#2073]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by vikmn** [comment]
assuming you have installed the package with the -g option
``` npm install learnyounode -g
```
you can then navigate into the folder where you wish to create your exercises and type in
```learnyounode```
that should offer you the steps to the first module you will need to complete and as you complete each module they will be marked as completed everytime you run the learnyounode command
