### ISSUE TITLE
Java Developer Trying to learn Node 

### ISSUE THREAD

**Issue by victyvinay9** [nodeschool/discussions#2074]
Hi  I just started learning node. I have cloned the first project 'javascripting'. I see the node project structure index.js, package.json etc. How should I run this project. I am using WebStorm IDE now. 

Sorry its a very beginner level question.

**Comment by ismnoiet** [comment]
Hi @victyvinay9, 
Cloning  the 'javascripting' project repository is generally to improve it(add new features etc)
or to read through the source code.
Instead if you want to install it and play around with it, you need to :    

1. Make sure you have Node.js and NPM installed on your machine.
2. Open up your terminal(CMD in Windows) and type in ``npm install -g javascripting``.
3. Once the installation is completed, type in your terminal ``javascripting``.
4. Now you will see a blue screen, that is it.

I Hope you find this useful.
