### ISSUE TITLE
timeserver module

### ISSUE THREAD

**Issue by vikmn** [nodeschool/discussions#2077]
Hi,
Working through learnyounode module  and slightly stuck on the timeserver. i do get the part about creating the server etc and without trying to look ahead at the solution i am not sure how i can get my actual value to be populated for the purpose of verification. The actual value still appears blank. There is not much pointer on the print instructions on how to populate that value?

────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "2017-04-18 18:27"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

**Comment by davecocoa** [comment]
Here's the relevant text from the instruction hints:

> Use socket.write(data) to write data to the socket and socket.end() to close the socket. Alternatively, the .end() method also takes a data object so you can simplify to just: socket.end(data).

Does that help? If not, could you show your current code? I can give better hints if I know what you've tried =)

**Comment by vikmn** [comment]
```JS
let net = require("net");
net.createServer(function (socket) {
    console.log("test")
    socket.end(new Date().toLocaleDateString());
}).listen(8000);

let client = new net.Socket();
client.connect(8000, "127.0.0.1", function () {
    console.log("connected");

});

client.on("data", function (data) {
    console.log("received :" + data);
});
```
Would have helped if i had attached the code as well. So have attached it her now. Awaiting the hint :)

**Comment by davecocoa** [comment]
It looks like you're connecting to the socket yourself, that should not be
necessary, I would remove that and allow `learnyounode` you handle it.

Also, are you sure you're listening to the correct port?

**Comment by vikmn** [comment]
Ahh!! the last sentence in your response triggered the fact that i wasnt actually capturing the port from the input which is one of the thingsmentioned in the instructions. So changing that alongside removing the clientside code worked. I was slightly confused by the need to add a additional newline charachter "\n" . Is there a need for this or is it just a limitation of the "verify" subcommand  that it needs that?

**Comment by davecocoa** [comment]
Well done! I'm afraid I'm not sure of the reason for the additional "\n" requirement. I believe some systems add it automatically when the socket is closed, so perhaps it's a good practice to add it explicitly for consistency... That is a total guess though!
