### ISSUE TITLE
Help "Make it Modular"

### ISSUE THREAD

**Issue by Cal-culator** [nodeschool/discussions#2078]
I'm currently working on NodeSchool's learnyounode and am stuck at "Make it Modular".

Here's my code for the module
```
var dir;
var ext;
var files=[];
var fs=require('fs');

module.exports=function(dir, ext, callback){
	fs.readdir(dir, function(err, list){
		if (err){
			return callback(err);
		}
		else{
			for (var i=0; i<list.length; i++){
					var extension=list[i].split(".");
					if (extension[1]===ext){
						files.push(list[i]);
				}
			}
			return callback(null, files);
		}
		
	});
};
```

Here's the code for the program:

```
var mod=require("./module1.js");
var fs=require('fs');


console.log(mod(process.argv[2], process.argv[3], function(err, list){
	if (err){
		throw err;
	}
	else{
		for (var i=0; i<list.length; i++){
			console.log(list[i]);
		}
	}
}));

```

Here is the result when I tried verifying:

                 ACTUAL                                 EXPECTED                
─────────────────────────────────

   "undefined"                         !=    "CHANGELOG.md"                     
   "CHANGELOG.md"             !=    "LICENCE.md"                       
   "LICENCE.md"                     !=    "README.md"                        
   "README.md"                     !=    ""                                 
   ""                                          !=                                       

─────────────────────────────────

I don't understand why the "undefined" is there. Can anyone explain the issue?

Thanks!

**Comment by vikmn** [comment]
I think it might be this extra logging causing the issue 
console.log(mod(

**Comment by Cal-culator** [comment]
@vikmn Hey. Thanks! But I still don't understand why the console.log was causing this issue. Could you elaborate on this or refer me to an article?

Thanks!

**Comment by vikmn** [comment]
your function mod does not return a value so as far as console.log is concerned there is no value in the return type which it treats as an undefined. hence the undefined in your console.log. hope this helps
