### ISSUE TITLE
How to access and run javascripting in terminal

### ISSUE THREAD

**Issue by greatbyte** [nodeschool/discussions#2083]
Hi folks. I attended a Nodeschool meetup in my city yesterday and npm install -g javascripting was installed in my MAC . Today, i am trying to access the javascript through the terminal, but i get an error message that -bash: npm: command not found. Who can help me ?

**Comment by jeetendra-choudhary** [comment]
Typically this happens in windows os when the npm global module path is not added into environment path veriables, not sure about the MAC or UNIX environment. Just a pointer for the RCA.
