### ISSUE TITLE
Learnyounode - Make it modular: asynchronous issue

### ISSUE THREAD

**Issue by chunzhu** [nodeschool/discussions#2084]
Can anyone share with me why is inside my codes that is causing it to be synchronous method?

 FAILED - Used asynchronous method from the fs module.

### My Code
var fs = require('fs')

module.exports = function (directory_name, ext, callback) { 
	fs.readdir(directory_name, 
		function s(err,data) {
			if (err) {
				callback(err)
			}
			
			data = data.filter(function(string) {
					if (string.split('.')[1] == ext)
						return string
					});
			callback(null,data)
	})
} 

var getFile = require('./test6a.js')
var path = require('path')

var callback = function(err,data) {
	if (err) {
		console.log( err)
	}
	else {
		console.log( data.join('\r\n') )
	}
}

var dir = process.argv[2]
var ext = process.argv[3]
getFile(dir,ext,callback)
```

**Comment by noffle** [comment]
Double check that you're running `learnyounode verify` on the correct
file. What you've written here is definitely using the async version of
`fs.readdir`.
