### ISSUE TITLE
Lesson 6: Make it modular (Error from readdir)

### ISSUE THREAD

**Issue by abyabrkal** [nodeschool/discussions#2086]
* node version: v7.9.0 
* npm version:  4.5.0 
* os: Windows 10 

Please check this code below and let me know why readdir returns error
### Error output
```
 Returns Error from readdir function. 
-- --
 "C:\\Users\\ABCD\\AppData\\Local\\Temp\\_learnyounode_XYZA**md**" !=    "CHANGELOG.md"

 "Error"                             !=    "LICENCE.md"
 ""                                  !=    "README.md"
───────────────────────────────────────────────────

Message from console log before readdir call

PathFile: C:\Users\ABCD\AppData\Local\Temp\_learnyounode_XYZA
Extension: md

```

### My Code
```module6.js
//module6.js

var fs = require('fs');

module.exports = function(path, filter, callback) {

    console.log(path + '**' + filter + '**');
    fs.readdir(path, function doneReading(err, list) {

        if (err) {
            return callback(err);
        } else {

            var ext = '.' + filter;
            var newList = list.filter(function(fname){
                    return (fname.endsWith(ext) === true);
            });
            callback(null, newList);
        }
    })
}
```

```program6.js 
//program6.js

var mod6 = require('./module6.js');

function log(err, data) {
    if (err === null){
        console.log("Error");
    } else {
        for (item in data){
            console.log(data[item]);
        }
    }
}

mod6(process.argv[2], process.argv[3], log);
```

**Comment by davecocoa** [comment]
Looking at your code and output, it seems the output is produced by `console.log(path + '**' + filter + '**');` and `console.log("Error");`. I assume you added `console.log(path + '**' + filter + '**');` simply for debugging purposes and understand you'll need to remove that in order for the solution to pass.

For `console.log("Error");`, can you guess why this piece of code is being executed? Are you sure the condition `err === null` is correct?

**Comment by abyabrkal** [comment]
@davecocoa Thanks dave. I ran the program initially without the debug console code. Here, as you mentioned at the end, readdir is returning error.

So, I included the debug line to show the arguments getting passed to readdir. The path passed here (a temp folder) is non-existent and cant be accessed from file explorer (hidden files are made visible too). 
Is the path passed during test is some folder from a temp directory?

**Comment by davecocoa** [comment]
The way the exercise works, it creates a folder, passes that path to your
program, and then deletes the folder again after your program is finished
running. You won't be able to examine the folder using the file explorer.

Are you sure readdir is returning an error? If so, perhaps you could log it
to get more information.

**Comment by abyabrkal** [comment]
@davecocoa I found my **stupid** mistake. 
         The error check `if (err === null)` was totally wrong. 

_Thanks for your time._
