### ISSUE TITLE
 Promise followed by promises challenge

### ISSUE THREAD

**Issue by vikmn** [nodeschool/discussions#2087]
### Notes
Reading through the print notes in regards with chaining promises,  Can someone help understand what is the expected output supposed to be in relation to the task?
## Task

This task will allow you to demonstrate an understanding how to chain promises
together using then.

Call first function in your program. first() will return a promise that
will be fulfilled with a secret value.

Call second with the fulfilled value of first. Return the promise returned
by second in your onFulfilled callback.

Finally, print the fulfilled value of that new promise with console.log.

### Error output
```
✗ Expected execution time: 663±100ms. Submission execution time: 261ms.
```

### My Code
```js
let first = function () {
    return Promise.resolve("SECRET");
};

let second = function (value) {
    return Promise.resolve("SECOND " + value);
};

first().then(function (data) {
        return second(data);
    })
    .then(console.log);
```

**Comment by davecocoa** [comment]
I believe [this update to the exercise wording](https://github.com/stevekane/promise-it-wont-hurt/pull/93) should help.

**Comment by vikmn** [comment]
That surely helped.
