### ISSUE TITLE
values and promises verification failure

### ISSUE THREAD

**Issue by vikmn** [nodeschool/discussions#2093]
### Notes

On the promises and values task i get the following error inspite of using the attachTitle function specified in the task. Can anyone explain what is wrong with this code?

### Error output
```
✓ Submission results match expected
✗ You didn’t create or didn’t use attachTitle method

```

### My Code
```js
let attachTitle = function (firstArgument) {
    return "DR. " + firstArgument;
}

let test = new Promise(function (fulfill, reject) {
    return fulfill("MANHATTAN");
});

test.then(function (data) {
    var p = attachTitle(data);
    console.log(p);
});
```

**Comment by jordanSu** [comment]
Hi, 
In the instruction it mentioned that 
> Build a promise chain off the promise we just constructed that first calls`attachTitle` then calls `console.log`

So I think you should build a **promise chain**, it would be like this:
`test.then(attachTitle).then(console.log)`

Hope this helps ^_^

**Comment by vikmn** [comment]
ahh.. i see the attachtitle is actually a value (albeit a function)
