### ISSUE TITLE
where do i begin?

### ISSUE THREAD

**Issue by alexander2005rj** [nodeschool/discussions#2094]
Hi, everyone!

So, i'm stook in the doubt about where i begin.

The section 'Fundamentals' don't suggests a sequence from study.

Someone could help me about this question?

**Comment by mostlyerror** [comment]
Hi @alexander2005rj 
Have you tried installing the javascript basics package and going through that?
From your computer terminal, enter these commands:
```
npm install -g javascripting
javascripting
```

if you don't have `npm` installed, you can check out the screencast here: https://docs.npmjs.com/getting-started/installing-node

Hope this helps!

**Comment by xujie-phper** [comment]
'javascripting' is not internal or external command.Execute is failed.
