### ISSUE TITLE
confusion about duplexer

### ISSUE THREAD

**Issue by franklingu** [nodeschool/discussions#210]
```javascript
var spawn = require('child_process').spawn;

module.exports = function (cmd, args) {
    var duplexer = require('duplexer');
    var exec = spawn(cmd, args);

    return duplexer(exec.stdin, exec.stdout);
}
``` 

this is my solution to duplexer--but is not stdin readable?
why this works when duplexer requires `duplexer("writeStream", "readStream")`?

**Comment by Sequoia** [comment]
@franklingu [process.stdin](http://nodejs.org/api/process.html#process_process_stdin) is readable but [child.stdin](http://nodejs.org/api/child_process.html#child_process_child_stdin) is **`writable`**.

This confused me too :smile_cat:
