### ISSUE TITLE
Can't reset registry.(completed exercises) how-to-npm workshop

### ISSUE THREAD

**Issue by shokry-suleiman** [nodeschool/discussions#2101]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.

**Comment by shokry-suleiman** [comment]
oky

**Comment by shokry-suleiman** [comment]
![capture](https://cloud.githubusercontent.com/assets/17477187/26316485/b2c075da-3f14-11e7-8aee-b5acea36a7d6.PNG)
