### ISSUE TITLE
HELP! - Problem with Exercise 2/19 "variables.js"

### ISSUE THREAD

**Issue by DorianKwan** [nodeschool/discussions#2103]
I'm stuck on this exercise for what seems no apparent reason. I believe what I have coded is correct although the output is [object Object].

Here is the code inside my variables.js file I edited with sublime text 3:

var example = 'some string';
console.log(example);

What have I done wrong?

**Comment by DorianKwan** [comment]
I figured it out. I'm not sure what I did wrong in the process. Although what I found was that in javascripting there was two separate files names variables.js. One had the proper code inside and the other did not.

**Comment by stefanmirck** [comment]
Closing as the issue is solved.
