### ISSUE TITLE
npm outdated command throws error

### ISSUE THREAD

**Issue by parasKumarSahu** [nodeschool/discussions#2107]
### If you have a problem with an error message:

* node version: v4.7.3
* npm version:  4.6.1
* os: linux(ubuntu on cloud9 server)

### Error output

npm ERR! code E404
npm ERR! 404 missing : async
npm ERR! 404 
npm ERR! 404  'async' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-05-26T19_10_15_370Z-debug.log

### My Code
npm outdated

**Comment by iigmir** [comment]
Got same problem at c9 here.

# If you have a problem with an error message:
    node version: v4.7.3
    npm version: 5.3.0
    os: linux(ubuntu on cloud9 server)

# Error output
npm ERR! code E404
npm ERR! 404 missing : async
npm ERR! 404 
npm ERR! 404  'async' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-07-16T17_39_02_192Z-debug.log

# My Code
npm outdated
