### ISSUE TITLE
Issue with learnyounode Make It Modular

### ISSUE THREAD

**Issue by Justin-Stevenson** [nodeschool/discussions#2110]
I am not able to make it past the Make It Modular step. If I run the verify against the original file (make-it-modular.js), it fails the additional module checks. If I run it against the module (filtering.js), it fails the submission results. Can someone look to see if it is something with the code? Is it something with how I am running verify command?

### If you have a problem with an error message:

* node version: 6.10.3
* npm version:  3.10.10
* os: windows 10

### Error output
If I run learnyounode verify filtering.js, I fail the submission results but pass all additional module checks.
```
 Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "CHANGELOG.md"
                                       !=    "LICENCE.md"
                                       !=    "README.md"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

 ✓

 Additional module file exports a single function

 ✓

 Additional module file exports a function that takes 3 arguments

 ✓

 Additional module file handles errors properly

 ✓

 Additional module file handles callback argument

 ✓

 Additional module file returned two arguments on the callback function

 ✓

 Additional module file returned an Array as the second argument of the
 callback

 ✓

 Additional module file correctly handles '.'-prefixed extension

 ✓

 Additional module file returned correct number of elements as the second
 argument of the callback

 ✓

 Additional module file returned correct list of files as the second
 argument of the callback

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!
```
If I run learnyounode verify make-it-modular.js, I pass the submission results but fail all additional module checks.
```
 Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✓

 Submission results match expected

 ✗

 Your additional module file [

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!

Error occurred when reading verify
```
Am I not running the verify command correctly? It doesn't seem like there are errors in my code since I can get submission results and additional module checks passing if change which scripts to verify. 

### My Code
make-it-modular.js
```js
var filtering = require('./filtering');

var directory = process.argv[2];
var extension = process.argv[3];

filtering(directory, extension, function(error, files) {
    if (error) {
        console.log('Error occurred when reading ' + directory);
        return error;
    } 
    
    files.forEach(function(file) {
        console.log(file);
    });
});
```

filtering.js
```js
 var fs = require('fs');
var path = require('path');

module.exports = function (directory, extension, callback) {
    fs.readdir(directory, function (error, files) {
        if (error) {
            return callback(error);
        }

        var filtered = [];

        files.forEach(function (file) {
            if (path.extname(file) === '.' + extension) {
                filtered.push(file);
            }
        });

        callback(null, filtered);
    });
};
```

**Comment by sphanley** [comment]
I had a very similar issue - it just seems weirdly picky about the order of the logic within your module. Here's the "official" solution, for comparison: 



    var fs = require('fs')
    var path = require('path')
    
    module.exports = function (dir, filterStr, callback) {
      fs.readdir(dir, function (err, list) {
        if (err) {
          return callback(err)
        }
    
        list = list.filter(function (file) {
          return path.extname(file) === '.' + filterStr
        })
    
        callback(null, list)
      })
    }

**Comment by Justin-Stevenson** [comment]
I pasted in the solution code but I am still getting the following error:

There was an error: { Error: ENOENT: no such file or directory, scandir 'C:\Users\Justin\My Documents\projects\node-workspace\learnyounode\verify'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Justin\\My Documents\\projects\\node-workspace\\learnyounode\\verify' }
