### ISSUE TITLE
Nodeschool chapter request from kolkata, india.

### ISSUE THREAD

**Issue by codetanmoy** [nodeschool/discussions#2111]
India's one of the oldest city is Kolkata. There are lots of tech enthusiastic folks here. Already we are associated with few open source communities like OWSAP,  CSA and Sillycon. We have noticed that there is already a Nodeschool Kolkata chapter open ("https://nodeschool.io/kolkata/") but it's almost inactive since last year. Please let us know if it's possible to open a new chapter in Kolkata.

**Comment by riyadhalnur** [comment]
Hi @codetanmoy, I think it's better if you can try to get in touch with the current maintainers of the Kolkata chapter and possibly talk about letting you take over.

**Comment by koustuvsinha** [comment]
Hi @codetanmoy , current maintainer here. Please follow our [discussion from this issue](https://github.com/nodeschool/kolkata/issues/5). Thanks!
