### ISSUE TITLE
[learnyoureact]PROPS_FROM_SERVER challenge description has mistake

### ISSUE THREAD

**Issue by YuanLuo1** [nodeschool/discussions#2115]
## Just to correct a mistake in the description

"Make the value of detail for the first object equal to the fourth command line
argument, and detail for the second object equal to the fifth command line
argument."

The fourth command line argument should be third,  and the fifth should be fourth.

**Comment by riyadhalnur** [comment]
Hi @YuanLuo1, if there's a mistake in the lesson, would you mind opening an issue on the repo for the tutorial? Here's the link to the [repo](https://github.com/workshopper/learnyoureact). Cheers.
