### ISSUE TITLE
Problem with learnyounode install npm

### ISSUE THREAD

**Issue by samwikiwiki** [nodeschool/discussions#2118]
### Data version:

* node version: v6.11.0
* npm version:  5.0.3
* os: ubuntu 17.04

I have this error when I put this in my console: "sudo npm install -g learnyounode"
### Error output
```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /home/myuser/.npm/_cacache/tmp/git-clone-750fff68
npm ERR! /home/myuser/.npm/_cacache/tmp/git-clone-750fff68/.git: Permiso denegado
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2017-06-15T15_27_17_565Z-debug.log

```

What can I do? I tried "sudo chown -R $USER /usr/local" but I get the same error.

**Comment by samwikiwiki** [comment]
EDIT: I did it finally with "sudo chmod 777 -R /usr/lib/node_modules/"

**Comment by lucaquaglia** [comment]
Node 8.2.1
NPM 5.0.3
Ubuntu 16.04

@samwikiwiki your solution does not work for me, as I still get:

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /home/luca/.npm/_cacache/tmp/git-clone-af3824d0
npm ERR! /home/luca/.npm/_cacache/tmp/git-clone-af3824d0/.git: Permission denied
npm ERR! 

and in the verbose log file I have

210 error Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /home/luca/.npm/_cacache/tmp/git-clone-af3824d0
210 error /home/luca/.npm/_cacache/tmp/git-clone-af3824d0/.git: Permission denied

I did set chmod -R 777 to  /home/luca/.npm/

what else can I do?
thank you in advance for your help!
