### ISSUE TITLE
Code not entering a callback function on exercise 6 of 13

### ISSUE THREAD

**Issue by halfnhalf0527** [nodeschool/discussions#2119]
Hi, I'm trying to learn node right now and I've been doing the exercises that are on nodeshcool.io.

I've come across an issue that I'm a bit confused about.  my code is this -
`var fs = require('fs');
var arrayToReturn = [];

module.exports = {

    filterDirectoryFiles: function (dir, ext, callback) {
        arrayToReturn = fs.readdir(dir, function returnValidDirectoryFiles(err, files) {
            files = files.filter(function filterDirectory(file) {
                return (file.includes("." + ext));
            });
            callback(null, arrayToReturn);
        });

    }
};`

for my module and for the program that runs the module my code is this

`var mymodule = require('./mymodule.js');

var dir = "C:\\Users\\aUser\\TestProjects\\learnyounode";
var ext = "js";

mymodule.filterDirectoryFiles(dir, ext, function returnedFilteredList(err, data) {
    if (err) {
        throw err;
    } else {
        for (var i = 0; i < data.length; i++) {
            console.log(data[i]);
        }
    }
});`

I know I can use .forEach on the data for simplify the code, but I have an issue with the line that contains

`arrayToReturn = fs.readdir(dir, function returnValidDirectoryFiles(err, files) `

this code.  It seems to jump straight to the end of the module and leave it rather than entering the function.  Is there something wrong with my syntax or organization of the code I might be missing that is causing this issue?

**Comment by davecocoa** [comment]
I have a few questions I hope might send you in the right direction.

- What do you expect is the value of `arrayToReturn`?
- Have you checked the documentation for [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) to see what it returns?
- OK, the docs for `fs.readdir` are not actually that helpful or clear. But you can always add a `console.log` to check what the value is. Hint: that function does not return anything
- What do you expect to happen if the `err` parameter passed to your `returnValidDirectoryFiles` is defined?
- Hint: for this exercise, you shouldn't be defining your own `ext` and `dir` properties, but getting those from `process.argv`. Perhaps that was only a debugging technique, I just want to make it's clear
- When you say the code seems to jump straight to the end of the module, could you explain more about what leads you to that conclusion? What output do you see? Have you tried adding `console.log` to see which pieces of code are running?

Hopefully that helps, good luck!
