### ISSUE TITLE
need explanation on stream-adventure secretz

### ISSUE THREAD

**Issue by franklingu** [nodeschool/discussions#212]
1 var crypto = require('crypto');
  2 var decipher = crypto.createDecipher(process.argv[2], process.argv[3]);
  3 var gunzip = require('zlib').createGunzip();
  4 var parser = require('tar').Parse();
  5 var through = require('through');
  6 
  7 parser.on('entry', function (e) {
  8             if (e.type !== 'File') {
  9                 return ;
 10             }
 11             var hasher = crypto.createHash('md5', {encoding : 'hex'});
 12             e.pipe(hasher).pipe(through(function (buf) {
 13                         this.queue(buf + ' ' + e.path + '\n');
 14                     }));
 15         });
 16 
 17 process.stdin.pipe(decipher).pipe(gunzip).pipe(parser).pipe(process.stdout);
 18 

for this I receive msg like this:
"
AUTHORIZED TARGETS THE JUSTICE DEPARTMENT DEEMS LEGAL TO SPY ON:

* NON-AMERICANS
* AMERICANS
* CLOWN COLLEGES
* MIME SCHOOLS
* RENAISSANCE FAIRS
* RENAISSANCE FAIRES
* RENAISSANCE FARES
* REN-FAERES
* HACKERS (ANYONE WHO HAS EVER "HACKED")
* END-USERS
* JOURNALISTS

SIGNATURE OF THE SECRETARY OF IMPORTANT GOVERNMENT THINGS WHICH ARE ALL SECRET
AND WHATEVER:
"
and a string of a large amount of numbers preceding it.

but when I looked at one online solution and changed the file to:
  1 var crypto = require('crypto');
  2 var decipher = crypto.createDecipher(process.argv[2], process.argv[3]);
  3 var gunzip = require('zlib').createGunzip();
  4 var parser = require('tar').Parse();
  5 var through = require('through');
  6 
  7 parser.on('entry', function (e) {
  8             if (e.type !== 'File') {
  9                 return ;
 10             }
 11             var hasher = crypto.createHash('md5', {encoding : 'hex'});
 12             e.pipe(hasher).pipe(through(null, function () {
 13                         this.queue(' ' + e.path + '\n');
 14                     })).pipe(process.stdout);
 15         });
 16 
 17 process.stdin.pipe(decipher).pipe(gunzip).pipe(parser);
 18

then I can pass the verification.

however, if I changed line 17 to  process.stdin.pipe(decipher).pipe(gunzip).pipe(parser).pipe(process.stdout);
again--i can see the long warning again.

can somebody explain this to me?

**Comment by Sequoia** [comment]
Can't easily parse question-- @franklingu can you please reformat per @timoxley's suggestion & attempt to clarify the question?
