### ISSUE TITLE
Every NodeSchool CLI are displaying incorrectly in Windows 10

### ISSUE THREAD

**Issue by softmantk** [nodeschool/discussions#2120]
Hi, I cant use any of the nodeschool Tutorials ( those CLI). Every CLI is displaying incorrectly.Adjusting the windows size cant 
![capture](https://user-images.githubusercontent.com/12989335/27223441-0dc2a4a6-52ae-11e7-84d0-33b5f54a1124.PNG)
![capture](https://user-images.githubusercontent.com/12989335/27223446-153c6226-52ae-11e7-8ddd-f2c104293192.PNG)

solve the issue. Do you have any solution ? I cant follow any tutorials.

**Comment by jpryne** [comment]
Hm... I'm not using Windows 10, but if the terminal works at all like Windows 7, try this:

Right-click on the terminal title-bar (the top part that you use to move the window) and click "Properties".
From there, click "Layout" and try setting the "Width" to 80. Let me know if that helps.

**Comment by softmantk** [comment]
No, it didn't help me. Text are displaying incorrectly. I had no issue with my personal laptop that runs windows 10, 
Is there any other way ?

**Comment by xuchunyangex** [comment]
I have exactly the same issue in my cmd and powershell... however you can still follow the tutorial if you can bare the ugly UI, just press enter to direct to correspond chapter. The specific chapter is working good.

Or you can try with gitbash:
![2017-07-03_16-33-31](https://user-images.githubusercontent.com/13094085/27784677-7d08c7ca-600d-11e7-8196-4f03cef7df3f.jpg)
