### ISSUE TITLE
Help with learnyounode: MAKE IT MODULAR

### ISSUE THREAD

**Issue by jules1020** [nodeschool/discussions#2122]
I can't seem to figure out how to run an error in the callback function through fs.readdir()?  I think I'm confused on specifically what that means, but I've completed the other parts of the exercise except that part.

**Comment by jpryne** [comment]
In the module, you should check for errors. If one occurs, simply return the callback function with the error, like this:

`        if (err) {
            return callback(err)
        }`

**Comment by jules1020** [comment]
I've done that but then it says: "Your additional module file [myModule.js] returned an error on its
 callback: { Error: ENOENT: no such file or directory, scandir 'verify' at
 Error (native) errno: -2, code: 'ENOENT', syscall: 'scandir', path:
 'verify' }"

**Comment by jules1020** [comment]
my module looks likes this: 

<img width="578" alt="screen shot 2017-06-18 at 6 59 12 pm" src="https://user-images.githubusercontent.com/24559680/27264912-40db049a-5458-11e7-8a63-207f0647f18b.png">

**Comment by jpryne** [comment]
Ah, then my guess is you need to check for that error *again* in the main.js code:
`    if (err) {
        console.log("There was an error")
    }`

**Comment by jules1020** [comment]
by main.js code you mean the original program?

**Comment by jules1020** [comment]
to help out here's my main program and myModule:
<img width="576" alt="screen shot 2017-06-19 at 8 51 26 am" src="https://user-images.githubusercontent.com/24559680/27285976-8369313c-54cc-11e7-8ca0-e8c911bc8770.png">
<img width="302" alt="screen shot 2017-06-19 at 8 51 18 am" src="https://user-images.githubusercontent.com/24559680/27285975-83673e72-54cc-11e7-855d-d233760a3293.png">

**Comment by mattinteractive** [comment]
FYI, @jules1020, it looks like you are returning callback(error) when it should be callback(err).

**Comment by jules1020** [comment]
ahh ok thanks!
