### ISSUE TITLE
learnyounode: HTTP JSON API SERVER

### ISSUE THREAD

**Issue by juliansd** [nodeschool/discussions#2124]
Having trouble with this exercise.  The hint says something about parsing a URL but i'm not sure how to get a URL from the url module.  The instructions give me a path but I'm not sure if I should be using the path to retrieve a url?

**Comment by chiaberry** [comment]
The url can be found in the request to the http server, aka `req.url`. Then you can use `parse` in the `url` module to parse the url from the request. 

Does that help?
