### ISSUE TITLE
a weird problem with expressworks/hello-world

### ISSUE THREAD

**Issue by franklingu** [nodeschool/discussions#213]
personally I think for hello-world it should not refer "/home" as root--should not root be '/'?

**Comment by Sequoia** [comment]
Hey @franklingu! Good news: all the lessons are on github so you can fix 'em up & file a pull request! :smile_cat:. Here's the relevant files: https://github.com/azat-co/expressworks/tree/master/problems/hello_world fork & PR as you will! Good luck! :+1:
