### ISSUE TITLE
BabySteps solution confusion

### ISSUE THREAD

**Issue by ashhath** [nodeschool/discussions#2136]
I just solved the BabySteps problem. However the output isn't what I was expecting and I don't know why. I was expecting 6 (the sum of 1,2,3). Why is it 420? Is it something to do with the next number (4) and then index 2? Perhaps I'm over thinking this.

**Comment by noffle** [comment]
Could you share your solution?

**Comment by ashhath** [comment]
var result = 0

for (var i = 2; i < process.argv.length; i++)
	result += Number(process.argv[i])

console.log(result)

**Comment by noffle** [comment]
What are you running to see 420? I put this code into `foo.js` and run `node foo.js 1 2 3` and get 6.

**Comment by ashhath** [comment]
ah you're right. i was getting confused w/ the submission results when i don't pass any arguments. thank you! 
<img width="562" alt="screen shot 2017-07-18 at 14 03 56" src="https://user-images.githubusercontent.com/3227045/28332225-068fd212-6bc2-11e7-97d2-275b89087767.png">

**Comment by noffle** [comment]
Awesome. Remember to close the issue if all is well!
