### ISSUE TITLE
proposing glitch as a tool for workshops, or simply resources for access to workshop participation

### ISSUE THREAD

**Issue by jennschiffer** [nodeschool/discussions#2137]
hi, i'm the community engineer for [glitch.com](https://glitch.com) and we've been running workshops (and some folks even running nodeschool workshops) where a web IDE like glitch has provided much value to folks who are unable to get their dev environment set up in the classroom (ie. installing node or xcode - or anything for that matter if using a chromebook or ios device or android tablet). 

i was wondering if a section on resources for handling access to taking part in workshops exists and, if not, would it be of value for someone like me to publish something like a glitch tutorial on how to set up a nodeschool workshop. glitch related or not, i think a set of resources to help teachers best set up their students should exist.

**Comment by garann** [comment]
I've been thinking about trying to host a nodeschool event and would love if glitch was part of it. At js workshops I've been part of before people always seem to have more fun and less frustration with tools like that that let them focus on their code without having to learn unix/git/etc at the same time. 👍

**Comment by finnp** [comment]
Yes, that sounds really helpful for beginner workshops. There is a wiki with information about how to run a workshop https://github.com/nodeschool/organizers/wiki. I am not sure though how many people are using it though.

**Comment by banzor** [comment]
+1 great idea!
