### ISSUE TITLE
fcall and An Important Rule

### ISSUE THREAD

**Issue by chiaberry** [nodeschool/discussions#2141]
Exercise 10 "An Important Rule" from Promise It Won't Hurt, the task says to `wraps your iterate method using Q's 'fcall'` but the official solution makes no use of `q` or `fcall`  

How would one solve it using `fcall`? 

Thank you!

**Comment by delaguilaluis** [comment]
Hi @chiaberry,
It seems like the official solution stopped using the `fcall` at some point in time.
[Here](https://github.com/stevekane/promise-it-wont-hurt/commit/5434e14a8e0f83ee769bebbf5ebac6b3b44e372a) is the commit that removed it. Maybe it helps you figuring out the desired approach.

Basically it starts the promise chain with:
```javascript
q.fcall(iterate, 1)
````
