### ISSUE TITLE
learnyounode Make It Modular: is it possible without using closure?

### ISSUE THREAD

**Issue by ndc** [nodeschool/discussions#2143]
About learnyounode the Make It Modular exercise, I have successfully solved it, but as a challenge I tried to not depend on closure to get extension name and module callback inside the readdir callback, but haven't found a way:

```js
var fs = require("fs");
var path = require("path");

module.exports = function (folderName, extensionName, callback) {
    fs.readdir(folderName, processFileList);
}

function processFileList(err, list) {
    // ???
}
```

Is it possible to not depend on closure to solve this? Any hints?

**Comment by ndc** [comment]
I think I got it:

```js
var fs = require("fs");
var path = require("path");

module.exports = function (folderName, extensionName, callback) {
    fs.readdir(folderName, function (err, list) {
        return processFileList(err, list, extensionName, callback);
    });
}

function processFileList(err, list, extensionName, callback) {
    // ...
}
```

Looks like my original intent was to avoid giant indentation wedge of function definition inside function definition, not to avoid using closure.

**Comment by delaguilaluis** [comment]
You could check the official solution in the learnyounode repo: https://github.com/workshopper/learnyounode/tree/master/exercises/make_it_modular/solution
