### ISSUE TITLE
javascripting in node

### ISSUE THREAD

**Issue by doakheggeness** [nodeschool/discussions#2145]
I installed 'javascripting' in node and ran the 'Introduction'.  It states 'Open the file in your favorite text editor..... 
I am new at this, so what file do I open in my text editor? Then is states to save and verify it is working by running 'javascripting verify introduction.js'.

Thanks

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by ndc** [comment]
I haven't tried javascripting but I think you need to create a file called `introduction.js` and edit it with your text editor.

**Comment by stefanmirck** [comment]
In the instructions it says:
```
Create a file named introduction.js:

     touch introduction.js 

Or if you're on Windows:

     type NUL > introduction.js
```
Using these commands you create a new file called `introduction.js`, which you can then open with the text editor of your choice.

Alternatively you can open your text editor, create a new file, write some code and then save it as `introduction.js` (or give it any other name if you like.)
