### ISSUE TITLE
function-arguments ex.18 javascripting

### ISSUE THREAD

**Issue by nasteho28** [nodeschool/discussions#2146]
**Directions**
define a function named math that takes three arguments.  
  It's important for you to understand that arguments names are only used to  
  reference them.  
  Name each argument as you like.  
  Within the math function, return the value obtained from multiplying the  
  second and third arguments and adding that result to the first argument.     
  After that, inside the parentheses of console.log(), call the math()  
  function with the number 53 as first argument, the number 61 as second and  
  the number 67 as third argument.  
   **my code**
`function math (firstNumber, secondNumber, thirdNumber) {
    return math * 
    
}`
Question- How do I format the return part?
Thank you for your time

**Comment by stefanmirck** [comment]
The exercise wants you to call `math()` from within `console.log()`. You don’t need to call `math()` from within itself.

Does that help you solving the problem?
