### ISSUE TITLE
new chapter in Tabriz

### ISSUE THREAD

**Issue by mrfarhadir** [nodeschool/discussions#2149]
**Hello** ,
I want to start chapter in Tabriz , would you please guide me  how to start .
also there is an old chapter for Tabriz city which is inactive and their website is not working !

**Comment by stefanmirck** [comment]
Hi @mrfarhadir, please read up on how to start a chapter (here)[https://github.com/nodeschool/organizers] and (here)[https://github.com/nodeschool/organizers/wiki).

If you want to take over an existing chapter, it’s best to contact the current organizers and ask how you could get involved or if they are willing to transfer the ownership of the repository for the Tabriz chapter over to you.

For any other questions you might have about organizing (local) NodeSchool events you best can open an issue in the organizers repo: https://github.com/nodeschool/organizers/issues.
