### ISSUE TITLE
Trouble with 'Manage Packages with npm'

### ISSUE THREAD

**Issue by Zikt** [nodeschool/discussions#2152]
### Notes
1. I just started learning on FreeCodeCamp's website and now I am stuck. How to I solve some of the issues I have?
-NPM Test
-How to edit `package.json`

2. Publish Again

3. Dist-Tag
-This command `npm dist-tag add <pkg>@<version> [<tag>]`

4. Dist Tag Removal
-
 
5. Outdated

6. Update

7. Rm
I have not been able to find any solutions yet.

**Comment by noffle** [comment]
It would help immensely if you could summarize the problem you're having and your questions. I'm not familiar with FreeCodeCamp -- did they direct you to https://nodeschool.io? What workshopper and exercise are you on?

**Comment by Tourzie** [comment]
Hi ZKT....Watch the video it's  going you help you but am also struggling with  "**-NPM Test
-How to edit package.json**" https://www.youtube.com/watch?v=xwQYLSkwjsU
