### ISSUE TITLE
cannot install learnyounode, got git already installed but they can't find it

### ISSUE THREAD

**Issue by Pumpkinworks** [nodeschool/discussions#2159]
Can't install Learnyounode, but I had already installed git for windows (2.14.0), and tried installing git via npm (0.1.5)

### If you have a problem with an error message:

* node version: 8.2.1
* npm version:  5.3.0
* os: windows 10

### Error output
C:\Users\chant>npm install learnyounode
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chant\AppData\Roaming\npm-cache\_logs\2017-08-08T00_21_29_632Z-debug.log

C:\Users\chant>npm install git
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\chant\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\chant\package.json'
npm WARN chant No description
npm WARN chant No repository field.
npm WARN chant No README data
npm WARN chant No license field.

+ git@0.1.5
added 2 packages in 1.287s

C:\Users\chant>npm install learnyounode -g
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chant\AppData\Roaming\npm-cache\_logs\2017-08-08T00_22_33_614Z-debug.log

C:\Users\chant>npm install learnyounode
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chant\AppData\Roaming\npm-cache\_logs\2017-08-08T00_22_46_624Z-debug.log

**Comment by delaguilaluis** [comment]
You are trying to install git by running `npm install git`, but that would install a package for managing git in a node application.
Instead, install git for Windows: https://git-scm.com/downloads
