### ISSUE TITLE
Error installing Javascripting

### ISSUE THREAD

**Issue by JoeDelux** [nodeschool/discussions#2161]
### Error output

 // C:\Windows\system32>npm install learnyounode -g
npm ERR! git clone --template=C:\Users\Admin\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:codeclimate/javascript-test-reporter.git
C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate
-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-09390dad:
 undefined
npm ERR! git clone --template=C:\Users\Admin\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:codeclimate/javascript-test-reporter.git
C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate
-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-09390dad:
 undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "learnyounode" "-g"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

/*

I've already installed the desktop version of Github. Seems like a problem to recognize it?
*/

**Comment by JoeDelux** [comment]
I've already installed the desktop version of Github. Seems like a problem to recognize it?

**Comment by delaguilaluis** [comment]
The GitHub desktop application is a user interface to use git.
Instead install git: https://git-scm.com/downloads and try again.
