### ISSUE TITLE
Function Arguments - exercise 18

### ISSUE THREAD

**Issue by microsushi** [nodeschool/discussions#2163]
Im having a problem with this exercise, dont understand it. I have created 3 arguments : multiply arguments 2 and 3, adding the first. My code doesnt work. Im a newbie. Can someone please help me to successfully do this. I thank you in advance.

### My Code
function math (secondArg [61] * thirdArg[67] + firstArg[53]){
console.log(math());
};

**Comment by delaguilaluis** [comment]
Hi microsushi, and welcome!

To solve this exercise you are expected to do two things:

1.) **Declare** a function called `math`that take three arguments.

An example of a valid _function declaration_ is:

```javascript
function sum(firstArg, secondArg) {
  return firstArg + secondArg;
}
```

2.) **Call** that function

To call a function, you state the function name, followed by a set of parenthesis. Inside these, you state the values you want to pass as arguments, separated by a comma.
The statement result then becomes the _returned value_.

An example of how you should _call_ our previously declared `sum` function:

```javascript
var result = sum(1, 2);

// The expected value of `result` here is 3.
```

So if you would like to log out to console the `result`, the resulting code would look something like:

```javascript
function sum(firstArg, secondArg) {
  return firstArg + secondArg;
}

var result = sum(1, 2);

console.log(result);
```

Check out more on functions here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions

**Comment by microsushi** [comment]
And I thank you for your help, I get it now. 
Im really enjoying this.
___________
James FISH  
DESIGNER
06 78 98 59 75
hello@fishlab.com
www.fishlab.com
