### ISSUE TITLE
Order fortutorials

### ISSUE THREAD

**Issue by yovasx2** [nodeschool/discussions#2165]
Which is the suggested order to take tutorials?

**Comment by delaguilaluis** [comment]
You could pick based on what you already know and what you want to learn, but I'll try to make a path here:

* javascripting*
* Scope Chains & Closures
* JavaScript Best Practices
* Count to six
* learnyounode*
* Expressworks / Make me Hapi*
* Test Anything*
* Then start picking on what seems interesting to you

\*: don't skip this

**Comment by yovasx2** [comment]
Awesome, thanks a lot
