### ISSUE TITLE
Learnyonode 7- Http client

### ISSUE THREAD

**Issue by abeldjesusp** [nodeschool/discussions#2166]
### Notes

Hi i have a problem, the firts line this output "<Buffer 4d 75 6c 6c 65 74>" .
I don't understand why firts line has this error and other lines not

### If you have a problem with an error message:

* node version: 6.11.2
* npm version: 3.10.10
* os: linux

### Error output
 "<Buffer 4d 75 6c 6c 65 74>"        !=    "Mullet"                           
   "Ankle biter"                                 ==    "Ankle biter"                      
   "Cactus mate"                              ==    "Cactus mate"                      
   "Throw-down"                              ==    "Throw-down"                       
   "Bundy"                                        ==    "Bundy"                            
   "Your Shout"                                ==    "Your Shout"                       
   "Divvy van"                                   ==    "Divvy van"                        
   "Bail out"                                       ==    "Bail out"                         
   "Bingle"                                         ==    "Bingle"                           
   "Parma"                                        ==    "Parma"                            
   ""                                                   ==    ""    

### My Code
```js

 let http = require('http');
let dir = process.argv[2];

http.get(dir, function(response){
	response.on('data', function(data,err){
		response.setEncoding("utf8")
		if(err){
			console.log(err);
		}
		else{
			console.log(data);
		}
	})
})

**Comment by stefanmirck** [comment]
Hi @abeldjesusp, this issue is that you’re setting the encoding of the response too late. Try setting the response encoding outside the data event callback.
