### ISSUE TITLE
Problem with "Make it Modular'

### ISSUE THREAD

**Issue by cewfowler** [nodeschool/discussions#2170]
don't quite understand what my problem is, its a logic error because its not printing out the right input. It's printing an empty array, so just "". It should be printing the files that match the input file extension.

Module code: 

const fs = require('fs');
const path = require('path');

function filterFiles(dir, fileExt, callback) {
  var fileNames = {};

  fs.readdir(dir, (err, files) => {

    if (err) return callback(err);
    
    //loops through files returned and adds those that match fileExt to fileNames
    for (var i = 0; i < files.length; i++){
      if (path.extname(files[i]) === ("." + fileExt)){
        fileNames.push(files[i]);
      }
    }
    
  })

  return callback(null, fileNames);
  
}

module.exports = filterFiles;

Program code:

const fs = require('fs');
const path = require('path');
var mymodule = require('./mymodule.js');

function printFiles(err, files){
  if (err){
    console.log("There was an error");
  }

  //prints the names of all the files
  for (var i = 0; i < files.length; i++){
    console.log(files[i]);
  }
}

mymodule(process.argv[2], process.argv[3], printFiles);

**Comment by delaguilaluis** [comment]
Hi, @cewfowler!

I was able to identify two problems in your _module code_:

1.) You are initializing the `fileNames` variable with an empty object, but I think you meant to use an array.

2.) You should call the callback with the results inside the asynchronous code (inside the callback for `fs.readdir`).

After fixing this two problems the solution passed. :party:
