### ISSUE TITLE
Console Logging Objects From json file.

### ISSUE THREAD

**Issue by nightfuryninja** [nodeschool/discussions#2172]
Hello, I was wondering how I could read objects I think it is called from a Json file. I have made an attempted using the knowledge I know but I couldn't seem to get it working as it would just display "Undefined" in the console which is annoying.

### My Code
```js
const config = require("./config.json");
console.log(config.Test.Test); //I dont know if that is correct but I don't know how else to do it.
```
```json
{
    "Test":["Random Text"],
    "Personal Info": [
            {
                "ID":"104",
                "Name": "Harry"
            }
        ]
    }
```
//// EDIT - I entered the wrong code.

```js
const config = require("./config.json");
console.log(config.Personal Info.Name); //I dont know if that is correct but I don't know how else to do it.
```

**Comment by delaguilaluis** [comment]
Hi @nightfuryninja, you were almost there.
The thing is that you are accessing `a.Test.Test`, but that property doesn't exist in the JSON file that you defined.

Your JSON has the following properties:
* `Test`: an array of strings
* `Personal Info`: an array of objects. The object defined inside has the properties `ID` and `Name` which are both strings.

If you want to access the text "Random Text", then you could do it like: `config.Test[0]`. This will retrieve the first string of the `Test` array.

If you want to access the Name for the ID "104", then you could do it like: `config['Personal Info'][0].Name`.

Here's a more detailed resource about [Working with objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects).
