### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by Sjahriyar** [nodeschool/discussions#2182]
In Scope-chains-closures, assignment 5, there should be an update, because they updated the interface in chrome, there is no more 'Time-Line' tab. it is in performance now.

**Comment by riyadhalnur** [comment]
Hi @Sjahriyar, thank you for bringing this up. An issue is already open in the repo for the lesson [https://github.com/workshopper/scope-chains-closures/issues/34](https://github.com/workshopper/scope-chains-closures/issues/34) . I also noticed that a PR has been opened in the regard. Hopefully, it will be merged in soon.
