### ISSUE TITLE
Learning Node for backend development?

### ISSUE THREAD

**Issue by michae1ho11ey** [nodeschool/discussions#2183]
I am a Systems Administrator. The devs I work with write primarily in Node. I have need to learn a language to do some server side scripting to help automate our build pipeline. I figured I'd get the best support for actual issues if I use the same language our devs use, hence why I'm looking into learning Node.

So my question is, what courses should I go through to learn how to use Node as a backend scripting language, not a front-end web language? Or is that out of the focus of this site and I'll need to go else where to figure out that piece?

Thanks for your guidance!

**Comment by noffle** [comment]
Yes, do check out the https://nodeschool.io workshoppers. Almost all of
the them (sans the explicitly web ones) may be helpful. I've also heard
positive things about https://www.freecodecamp.org but haven't used it
myself.
