### ISSUE TITLE
 # LEARN YOU THE NODE.JS FOR MUCH WIN!        ## MY FIRST I/O! (Exercise 3 of 13)

### ISSUE THREAD

**Issue by DoiChris** [nodeschool/discussions#2184]
Please give me sample for 
# LEARN YOU THE NODE.JS FOR MUCH WIN!     
 ## MY FIRST I/O! (Exercise 3 of 13) 

I really do not have any idea.

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.
