### ISSUE TITLE
younode ex02 - hints!?

### ISSUE THREAD

**Issue by slowreader87** [nodeschool/discussions#2186]
firstly - is learnyounode the second batch of exercises in the set? I worry I've gone from 1 to 4 or something

second - I am trying to run the below solution but it fails

```
for (i = 2, sum = 0; i <= process.argv.length; i++) {
    num = Number(process.argv[i]);
    sum += num;
}
console.log(sum);
```

third - is there a way to view the correct answer so I don't have to come online to ask - giving me much shame

Fourth - thanks to everyone who put this site and exercises together! I always wonder what motivates such generosity! Some day maybe I will be in a position to pay it forward... till then I'm kind of a confused newbie. Enthusiastic and persistent but not particularly talented!

**Comment by noffle** [comment]
Great questions @charlieafif.

> firstly - is learnyounode the second batch of exercises in the set? I worry I've gone from 1 to 4 or something

If you're totally new to the language, [javascripting](https://www.github.com/sethvincent/javascripting) is a much easier place to begin.

> second - I am trying to run the below solution but it fails
```js
for (i = 2, sum = 0; i <= process.argv.length; i++) {
    num = Number(process.argv[i]);
    sum += num;
}
console.log(sum);
```

How are you running it? How do you know it's failed?

> third - is there a way to view the correct answer so I don't have to come online to ask - giving me much shame

Yes! Run `learnyounode verify solution.js`, where `solution.js` is whatever your source code file is named.

> Fourth - thanks to everyone who put this site and exercises together! I always wonder what motivates such generosity! Some day maybe I will be in a position to pay it forward... till then I'm kind of a confused newbie. Enthusiastic and persistent but not particularly talented!

Keep at it! You're doing great.

**Comment by moitorrijos** [comment]
@slowreader87 simply use less than process.argv.length instead of less than or equal to ... like this:

`for (i = 2, sum = 0; i < process.argv.length; i++) {
    num = Number(process.argv[i]);
    sum += num;
}
console.log(sum);`

To see the results before trying out simply run `node program.js` in the command line from the same directory as the file.
