### ISSUE TITLE
learnyounode exercise Filtered ls

### ISSUE THREAD

**Issue by terena12** [nodeschool/discussions#2189]
### Notes

-
### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```✗ 

 Submission results did not match expected!

 ✓ 

 Used asynchronous method: fs.readdir()

 # FAIL Your solution to FILTERED LS didn't pass. Try again!

### My Code
```js
 // copy your code here
```
var fs = require("fs");
var path = require("path");
var ext = '.' + process.argv[3];
var dir = process.argv[2];
 
fs.readdir(dir, function callback (err, data)  {
    if(err){return err}
    
    var l =data.length;
    
    for(var i = 0; i < l; i++){
        var x = data[i];
        var e = path.extname(x);
        if(e == "."+ext){
            console.log(x);
        }
    }
})

**Comment by terena12** [comment]
I don't  know what I have done wrong

**Comment by Hychhayrith** [comment]
Because you add "." + ext 
you already add dot when you declare ext so it becomes duplicate
should be like this  if(e == ext){ .........}
