### ISSUE TITLE
verifying 'variables' exercise

### ISSUE THREAD

**Issue by brandonsamuel1** [nodeschool/discussions#2192]
### Notes
Hey, so im stuck on verifying my 'variables' exercise. Ive created the file called "variables" then when i write the code in sublime and go to verify, it says im doing something wrong. I have spelled everything correctly and I dont know what else I could be doing wrong, please help!

**Comment by brandonsamuel1** [comment]
I have also typed 'ls variables.js' to check, and it returns 'variables.js' in my terminal.

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.

**Comment by brandonsamuel1** [comment]
VARIABLES (Exercise 2 of 19)  
   
  A variable is a name that can reference a specific value. Variables are  
  declared using var followed by the variable's name.  
   
  Here's an example:  
   
     var example;  
   
  The above variable is declared, but it isn't defined (it does not yet  
  reference a specific value).  
   
  Here's an example of defining a variable, making it reference a specific  
  value:  
   
     var example = 'some string';  
   
 # NOTE  
   
  A variable is declared using var and uses the equals sign to define the  
  value that it references. This is colloquially known as "Making a variable  
  equal a value".  
   
 ## The challenge:  
   
  Create a file named variables.js.  
   
  In that file declare a variable named example.  
   
  Make the variable example equal to the value 'some string'.  
   
  Then use console.log() to print the example variable to the console.  
   
  Check to see if your program is correct by running this command:  
   
  javascripting verify variables.js  
   
 ─────────────────────────────────────────────────────────────────────────────  
  Need help? View the README for this workshop:  
  (http://github.com/sethvincent/javascripting)  
   
 ─────────────────────────────────────────────────────────────────────────────  
   
   » To print these instructions again, run: javascripting print                 
   » To execute your program in a test environment, run: javascripting run                                                                            
     program.js                                                                  
   » To verify your program, run: javascripting verify program.js                
   » For help run: javascripting help                                            
   
vagrant [javascripting]> touch variables.js
vagrant [javascripting]> javascripting verify variables.js

**Comment by brandonsamuel1** [comment]
Did you type the name of the file correctly? You can check by running                                                                          
    'ls variables.js'. If you see 'ls: cannot access variables.js: No such                                                                          
    file or directory,' then perhaps the file doesn't exist, or has a                                                                          
    different name, or is in a different directory.                           
  » Make sure you didn't omit any parens, or the compiler will not be able                                                                          
    to parse it.                                                              
  » Make sure you don't have any typos in the string itself.                  

─────────────────────────────────────────────────────────────────────────────
 Need help? View the README for this workshop:
 (http://github.com/sethvincent/javascripting)

─────────────────────────────────────────────────────────────────────────────

  » To print these instructions again, run: javascripting print               
  » To execute your program in a test environment, run: javascripting run                                                                          
    program.js                                                                
  » To verify your program, run: javascripting verify program.js              
  » For help run: javascripting help                                          

─────────────────────────────────────────────────────────────────────────────
 Need help? View the README for this workshop:
 (http://github.com/sethvincent/javascripting)

─────────────────────────────────────────────────────────────────────────────

  » To print these instructions again, run: javascripting print               
  » To execute your program in a test environment, run: javascripting run                                                                          
    program.js                                                                
  » To verify your program, run: javascripting verify program.js              
  » For help run: javascripting help                                          

vagrant [javascripting]> ls variables.js
variables.js
vagrant [javascripting]> javascripting help

**Comment by ecobabush** [comment]
Did you save your variables.js in your sublime before typing javascripting verify variable.js?
And try this 1)ls variables.js
                   2)sublime variables.js and take a look inside you variables.js to check is all your stuff there?

**Comment by brandonsamuel1** [comment]
Thank you it worked! My problem was i didn't save it, please excuse my stupidity....
