### ISSUE TITLE
issue: cannot find module

### ISSUE THREAD

**Issue by Tasnym** [nodeschool/discussions#2200]
Hi guys, this is the issue that I'm facing currently,
I've just ran one of the work shopper module on git bash, the package is npm install -g learnyounode and the module name is learnyounode, the exercise was to print out a hello world to the console stdout, I used visual studio code to write the js code and ran it on git bash terminal, here's the problem it say's cannot find module 
![image](https://user-images.githubusercontent.com/30748126/31707155-f983b7ba-b41d-11e7-881b-2b51ff4484a2.png)
I appreciate if someone would help me out here.
Thank You to those who help.

**Comment by Xxbur** [comment]
make sure when you 'node *.js' ,your git bash direction is same as your 'js' file direction
