### ISSUE TITLE
Change Bangalore, IN to Bengaluru, IN

### ISSUE THREAD

**Issue by TheShashank** [nodeschool/discussions#2201]
Hey everyone

I love nodeschool, learnyounode has helped me a lot. Just a quick note, it has been a while since the city of Bangalore was renamed to Bengaluru - it would be great if the name could be updated in the website to minimize confusion.

Thanks a ton

**Comment by riyadhalnur** [comment]
Fixed in https://github.com/nodeschool/nodeschool.github.io/pull/584
