### ISSUE TITLE
My first async i/o! Exercise 4 of 13

### ISSUE THREAD

**Issue by elizabethfranklin** [nodeschool/discussions#2206]
I am new to node.js and was hoping to get some feedback on my code. 
My error code is SyntaxError: missing > after argument list

### My Code
```js
 // copy your code here
```var fs=require('fs');
var fileToRead=fs.readFile(process argv[2], 'utf8', function(err, contents){
  var lines=contents.toString().split('\n').length-1
  console.log(lines)
})

**Comment by noffle** [comment]
You're close. `progress.argv` is an object containing the arguments given to the program. The period `.` between `process` and `argv` is necessary for node to understand that you're accessing the key `argv` of the object `process`.

**Comment by elizabethfranklin** [comment]
Thank you! Little things are tripping me up here, and I appreciate the quick response.
