### ISSUE TITLE
Juggling Async help please

### ISSUE THREAD

**Issue by StephenDRoberts** [nodeschool/discussions#2210]
Hello

Apologies for writing this issue however I'm really struggling to get my Async project completed. Having read and watched many sites & youtube videos respectively about async & callbacks, and having read the other issues on this site I've gotten a lot further however I cant seem to get this last bit sorted.

I think I've now solved the issue about timing my responses.  However when I print my output, each sentence beigis with "undefined". E.g:

"undefinedShazza got us some oldies bloody lets throw a nipper. As dry as a bull bar also as cunning as a freo. "

I'm really unsure why the initial undefined is coming through and so any help would be greatly appreciated.  The undefined comes through on each array that I enter

### My Code
```js
var http = require('http');
var i = 2;

var final = 0;
var array = [ ];
    
function getIt (url, i){
http.get(url, function(res){
    res.setEncoding('utf8');
    
  res.on('data', function(data){
     
     array[i] += data.toString();
  });
  res.on('end', function(){
    final ++;
    if (final == 3){
        printMe();
    }
  });
}).on('error', function(e){
    console.log("Error: " + e);
});
};


for (i==i; i<5;i++){
    var url = process.argv[i];
    getIt(url, i-2);
    
    
}


function printMe(){
    console.log(array[0]);
        console.log(array[1]);
            console.log(array[2]);
}
```

**Comment by noffle** [comment]
Nice work so far @StephenDRoberts! Here's some code to try and run that might shed some light on your bug for you:

```js
var array = []
array[0] += 'hi'
console.log(array[0])

var foo
console.log(foo)
foo += 'hi'
console.log(foo)

var bar = ''
bar += 'hi'
console.log(bar)
```

**Comment by noffle** [comment]
Maybe also

```js
var a = []
console.log(a[5])
```

**Comment by StephenDRoberts** [comment]
you hero.  Thank you very much.  Managed to get it sorted with by specifying empty entries in the array. Not sure if it's the right way to do it but it works.  Thank you very much noffle!

**Comment by noffle** [comment]
Awesome! A common trick I'll use when I don't know when an array element already exists or not:

```js
array[5] = (array[5] || '') +  'hi'
```

This uses the array element if it 's already present, and creates a new string as a base if not.
