### ISSUE TITLE
Want to join the organization

### ISSUE THREAD

**Issue by amitsin6h** [nodeschool/discussions#2214]

**Comment by riyadhalnur** [comment]
Please provide more information.

**Comment by amitsin6h** [comment]
@riyadhalnur I want to join nodeschool org. Am from Ranchi, Jharkhand

**Comment by riyadhalnur** [comment]
You would need to create a new chapter and be one of its co-organisers or join an existing chapter in your area and become one of the organisers. Either way, anyone who uses our tutorials is a part of the Nodeschool family anyways 😃
