### ISSUE TITLE
Error while deploying the node project. 

### ISSUE THREAD

**Issue by Ankur008** [nodeschool/discussions#2219]
* node version: v8.9.1
* npm version:  5.5.1
* os: linux

Actually, I am tried to deploy the node js project on Linux (Ubuntu 16.04) server using the Apache2 server. 
But when I am trying to hit API, getting error 404. 
Probable reason:  Not able to set up the right address and port.

**Comment by riyadhalnur** [comment]
Please provide more information by providing the full error output and steps to reproduce the error.

**Comment by Ankur008** [comment]
hey sorry, I forget to add the link.. (https://stackoverflow.com/questions/47362712/getting-404-while-accessing-the-api)
