### ISSUE TITLE
nodeschool chapter request

### ISSUE THREAD

**Issue by amitsin6h** [nodeschool/discussions#2220]
Want to start nodeschool chapter for my region.
nodeschool Jharkhand chapter.
Please let me Know how can I.

**Comment by riyadhalnur** [comment]
Hi @amitsin6h, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by riyadhalnur** [comment]
Hi @amitsin6h, that's awesome. Do you have other co-organisers? We usually recommend at least 2 or 3 people to co-organise a given chapter.

**Comment by amitsin6h** [comment]
Yes got the co-organiser Prateek Kumar(@sam1730) and Sumit Kumar Singh

**Comment by amitsin6h** [comment]
Please also let me know how to start. @riyadhalnur

**Comment by riyadhalnur** [comment]
Tracking in https://github.com/nodeschool/organizers/issues/497.
