### ISSUE TITLE
what is child_processes (Duplexer Stream-adventure)

### ISSUE THREAD

**Issue by agilephoenix** [nodeschool/discussions#2222]
the question asks us to spawn a process from a cmd strings and an args array.But I dont understand what they are? #

**Comment by noffle** [comment]
`child_process` is a built-in node module for creating and managing [processes](http://www.theunixschool.com/2012/09/what-is-process-in-unix-linux.html). You can find the node documentation for that [here](https://nodejs.org/api/child_process.html).

**Comment by agilephoenix** [comment]
Thanks for the help!
