### ISSUE TITLE
starting with JavaScript

### ISSUE THREAD

**Issue by ramramchander** [nodeschool/discussions#2224]
### Notes

hello i want to start javascripting exercise and i have Windows 10 laptop can any body tell plz how i can install package to start it. I have download  nodejs into my PC
thanks 

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by delaguilaluis** [comment]
Hi, @ramramchander,

Since you already installed Node.js, you could follow the instructions found on the [javascripting's README](https://github.com/workshopper/javascripting):

### Install `javascripting` with `npm`

Open your terminal and run this command:

```
npm install --global javascripting
```

The `--global` option installs this module globally so that you can run it as a command in your terminal.

**Comment by noffle** [comment]
Hey @rogerrc122. On unix systems like macOS there's an environment
variable[1] called $PATH. Try typing `echo $PATH` in the terminal:
you'll see a list of directories separated by colons. Whenever you type
in a command, all of those directories will be searched, in order, for a
command by that name.

For example, if you type `which npm` you'll see where in $PATH the npm
command was found. If your system says that `javascripting` can't be
found, it means that that command isn't in the $PATH variable.

You can get npm to tell you where it puts modules it downloads by
running `npm config get prefix`. For me it's `/home/sww/.npm-global` --
it'll be different for you. The commands are put in the /bin
subdirectory, so for me `/home/sww/.npm-global/bin`. If you run `ls
THAT_DIRECTORY` you'll see all of the npm commands you've installed. You
should see `javascripting` in there!

Now we can add that directory to the $PATH variable. It gets set up in a
script called .bashrc in your home directory. You can add a line to that
to expand $PATH to include your npm bin directory like this:

cat >> ~/.bashrc
export PATH=$PATH:/home/sww/.npm-global/bin
^D

Where ^D means press CTRL+D. You can also just use a text editor to open
the .bashrc file in your home directory and add that line. This tells
$PATH to also search your npm directory for commands.

Finally, type `source ~/.bashrc` to make your changes live. You can also
just open a new terminal window to do this. You should be able to run
the `javascripting` command now!

**Comment by delaguilaluis** [comment]
Can you spot any error on the npm install output? Could you share it here?
