### ISSUE TITLE
Exercise 11 : http server

### ISSUE THREAD

**Issue by Etilawin** [nodeschool/discussions#2228]
* node version: v8.9.1
* npm version:  5.5.1
* os: windows 10

Hello,
I can't get rid of a weird output from exercice 11 of learnyounode
Has anyone a solution ? Is my code wrong ?
Thanks in advance

### Error output
```
 _stream_readable.js:595
    dest.end();
         ^

TypeError: dest.end is not a function
    at IncomingMessage.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  ✗  Error connecting to (http://localhost:61583): read ECONNRESET
```

### My Code
```js
const fs = require('fs');
const http = require('http');

const port = process.argv[2];
const filePath = process.argv[3];

let server = http.createServer(function callback(req, resp){
  req.pipe(fs.createReadStream(filePath)).pipe(resp);
});

server.listen(port);
```

**Comment by noffle** [comment]
What is your intention behind this line of code:

```js
  req.pipe(fs.createReadStream(filePath)).pipe(resp);
```

Note that `req` and `fs.createReadStream()` are both [readable](https://nodejs.org/api/stream.html#stream_readable_streams) streams. `resp` is a [writable](https://nodejs.org/api/stream.html#stream_writable_streams) stream. For `pipe` to work, a readable stream needs to be piped into a writable stream.

**Comment by Etilawin** [comment]
Thanks, indeed I misunderstood the goal of the pipe method !

This now closed because correcting my code made it work.

Thanks
