### ISSUE TITLE
learnyounode - exercise 3

### ISSUE THREAD

**Issue by mattstub** [nodeschool/discussions#2229]
I'm sure I'm overlooking something very simple here, but it seems to pass my tests setup as well, so just wondering if this has been answered somewhere else before or if someone knows why i'm showing a fail even though the tests are passing? Thanks in advance for the help! Here is a link to the [repo](https://github.com/mattstub/learnyounode)

![learnyounode](https://user-images.githubusercontent.com/26757091/33529677-c21cb7fa-d839-11e7-8bcb-9069db7b51e8.png)

**app.js**
```js
const fs = require('fs')

module.exports = {
  ...
  readString: (filepath) => {
    let count = fs.readFileSync(filepath).toString().split('\n').length - 1
    return count
  }
}
```

**program.js**
```js
const app = require('./app')
...
// MY FIRST I/O! - Exercise 3
console.log(app.readString(process.argv[2]))
```

**Comment by mattstub** [comment]
Disregard, resolved at this time

**Comment by hytonylee** [comment]
May I ask how did you resolve it, coz I have ran into the same issue.
