### ISSUE TITLE
Make it modular

### ISSUE THREAD

**Issue by IbragimY** [nodeschool/discussions#223]
MacOS X 10.9.2

learnyounode --version
learnyounode@0.2.16-mimbug

node --version
v0.10.13

Verifying "MAKE IT MODULAR"...

ACTUAL                             EXPECTED
------                             --------
"CHANGELOG.md"                     "CHANGELOG.md"                 
"LICENCE.md"                       "LICENCE.md"                   
"README.md"                        "README.md"                    
""                                 ""                             
3 ["README.md","CHANGELOG.md","LICENCE.md"]
0 [""]

Your additional module file:
	/Users/ib/dev/nodejs/filtered-ls-module.js
did not return an Array with the correct number of elements as the second argument of the callback

# FAIL

make-it-modular.js 
-------------------------
var filter = require('./filtered-ls-module.js')
filter(process.argv[2], '.' + process.argv[3], function(err, data) {
	if(err) {
		console.log("error")
		return
	}
	data.forEach(function(item) {
		console.log(item)
	})
})

filtered-ls-module.js 
--------------------------
module.exports = function(dir, ext, callback) {

	var result = []
	var fs = require('fs')
	var path = require('path')

	fs.readdir(dir, function(err, files) {
		if(err)
			return callback(err)
		for(var i = 0; i < files.length; ++i) {
			var file = files[i]
			if(path.extname(file) === ext)
				result.push(file)
		}
		callback(null, result)
	})
}

**Comment by KanTian** [comment]
@pirfalt  thany you very much, ^_^，   I also have meet this question...
