### ISSUE TITLE
Javascripting #3: Strings

### ISSUE THREAD

**Issue by philawesomer** [nodeschool/discussions#2232]
Hey, not really an issue but a question. It asks you to write:
 
var someString = this is a string;
console.log ('someString');

But, instead of outputting 'this is a string', I got 'someString' instead.

## Check your solution:

 Solution ===================

 this is a string

 Your Attempt ===================

 someString

 Difference ===================

 this is a someString

What have I done wrong? Have I done anything wrong? Please let me know.

**Comment by huberv** [comment]
Well, you asked console.log to output the string 'someString', but what you probably wanted to do was to ask console.log to output the value of someString.

**Comment by philawesomer** [comment]
Exactly. I figured it out just as you commented. Thank you for your help.
