### ISSUE TITLE
javascripting Unable to make a new directory via the command prompt

### ISSUE THREAD

**Issue by kangjushang** [nodeschool/discussions#2238]
When I try to make a directory via the command prompt by typing 
"mkdir javascripting". The command prompt responds with the message "Access Denied".
What have I done wrong? Please help.

**Comment by akinhwan** [comment]
i assume you are on windows because you are using mkdir...in which case you may need to run as admin? see this link for more info   [https://superuser.com/questions/26393/access-is-denied-when-i-try-to-create-a-directory-in-windows-vista]

**Comment by kangjushang** [comment]
The issue is resolved, thank you for the assistance.
