### ISSUE TITLE
Stream Adventure "websockets" problem

### ISSUE THREAD

**Issue by jlmitch5** [nodeschool/discussions#224]
Hey,
I'm trying to figure out why I can't see "hello" in my browser from this problem.  My solution matches the proposed solution and was "accepted" as correct, but like I said, Chrome gives me the error:
"Oops! Google Chrome could not connect to localhost:8000"

I ran this nmap scan, and was told that this port was closed...do I need to open it?  Will that cause any security vulnerabilities on my system if I do (not sure if there's any attacks possible through an open alternate-http port).  Thank you, these tutorials are great, by the way!

$ nmap localhost -p 8000

Starting Nmap 6.40-2 ( http://nmap.org ) at 2014-03-10 13:36 EDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000078s latency).
PORT     STATE  SERVICE
8000/tcp closed http-alt

**Comment by Sequoia** [comment]
Does this ticket cover the same issue? https://github.com/substack/stream-adventure/issues/53

**Comment by substack** [comment]
fixed in 4.0.0
