### ISSUE TITLE
(node:47348) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by akinhwan** [nodeschool/discussions#2240]
I am getting the error in the title of this issue for 

**stream-adventure**, as well as for **scope-chains-closures**

**Comment by delaguilaluis** [comment]
Hi, akinhwan,

It seems like you are using a method of the `fs` module without specifying a callback as parameter.
Although, at the moment, this is just a warning, in future versions of Node.js the code might throw an error instead, so I'd recommend you to check [the `fs` methods documentation](https://nodejs.org/api/fs.html) for the right way to call a desired method.

More info on the deprecation is found [here](https://nodejs.org/api/deprecations.html#deprecations_dep0013_fs_asynchronous_function_without_callback).

**Comment by finnp** [comment]
This is not your fault, it's a bug in the workshopper (see https://github.com/workshopper/stream-adventure/issues/200)
