### ISSUE TITLE
Why the learnyounode's filter LS's answer have the fouth element?Is it only should be the first three?

### ISSUE THREAD

**Issue by JackieLJM** [nodeschool/discussions#2247]
"CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

**Comment by finnp** [comment]
Hey, there should be a newline printed after `README.md`. Then when your code is checked the output is splitted by newlines (`\n`). Since there is a newline at the end, it will have an empty string in the end.

Does that make sense?
