### ISSUE TITLE
starting up my new baby chapter

### ISSUE THREAD

**Issue by codeekage** [nodeschool/discussions#2251]
Hello guys, please i need help starting up the new chatper in my region.
Like:

1. Getting swags.
2. Getting @nodeschool.io email.
3. Having a first event to remember.

Thank. email: agiriabrahamjunior@gmail.com
twitter: @codeekage

Or 
Just contribute here. Thank You!

**Comment by finnp** [comment]
Hey @codeekage,

that sounds great! Could you please have a look at https://github.com/nodeschool/organizers/#how-to-start-a-new-nodeschool-chapter and create an issue over there?

When you start a chapter we can take care of the nodeschool email. 👍
