### ISSUE TITLE
What's the difference between learnyoureact and thinking-in-react

### ISSUE THREAD

**Issue by nick722** [nodeschool/discussions#2256]
Hi,

can you please elaborate what's the difference between this 2 workshops:

- learnyoureact - https://github.com/workshopper/learnyoureact
- Thinking in React - https://github.com/asbjornenge/thinking-in-react

Is one of them more advanced than the other or what?

Thanks,
Nikolai

**Comment by noffle** [comment]
Maybe someone will come along and do the work of summarizing the differences for you, but you should also feel empowered to check out the each of them (try the `exercises/` directory) and try to answer your question for yourself!

**Comment by finnp** [comment]
As far as I can tell `learnyoureact` is more focused on beginners, teaching you the different parts of React. While `thinking-in-react` might be a bit more advanced and also more based on an example application.
