### ISSUE TITLE
NodeSchool Port Harcourt, Nigeria!!! Tagged : NodeSchool Africa Together... Mentorship Request 

### ISSUE THREAD

**Issue by codeekage** [nodeschool/discussions#2264]
Calling out on all the NodeSchools in Africa for a Collaboration! To Storm Africa with NodeJS.
Tweet me @codeekage or email @agiriabrahamjunior@gmail.com.. Let's Make Africa the largest Contributors to NodeJS!!

**Comment by inidaname** [comment]
@codeekage I sent you a mail on this

**Comment by ldbraun** [comment]
Am in. My username @ldbraun

Warm regards.

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: codekage
Sent: Wednesday, 14 February 2018 18:40
To: nodeschool/discussions
Reply To: nodeschool/discussions
Cc: Subscribed
Subject: [nodeschool/discussions] NodeSchool Port Harcourt, Nigeria!!! Tagged : NodeSchool Africa Together... Mentorship Request (#2264)



Calling out on all the NodeSchools in Africa for a Collaboration! To Storm Africa with NodeJS.
Tweet me @codeekage<https://github.com/codeekage> or email @agiriabrahamjunior@gmail.com<mailto:agiriabrahamjunior@gmail.com>.. Let's Make Africa the largest Contributors to NodeJS!!

**Comment by codeekage** [comment]
Please show further interest here https://github.com/NodeJSAfrica/nodeschool-organizers/issues
