### ISSUE TITLE
learnyounode blank text in areas of the tutorial description

### ISSUE THREAD

**Issue by freddyrayes** [nodeschool/discussions#2266]
While running through the "learnyounode" tutorials, some of the text is blank and does not appear appear. For example in the last area "To print these instructions again, run: <Blank>". See bottom section of the attached screenshots.

* node version: v9.50
* npm version:  5.6
* os: mac 10.13.3 (High Sierra) - I'm running the mac terminal with default profile.

![screenshot 2018-02-17 17 00 31](https://user-images.githubusercontent.com/19268333/36346062-0a55db30-1405-11e8-9b52-152b4ee44297.png)
![screenshot 2018-02-17 17 04 25](https://user-images.githubusercontent.com/19268333/36346063-0a629cd0-1405-11e8-94f9-74eb177ac2e6.png)

**Comment by darkstylazz** [comment]
I have the same problem

**Comment by eduucaldas** [comment]
Same

**Comment by taleymirza** [comment]
same issue

**Comment by anygard** [comment]
I have the same issue on challenge 2 on the javascripting tutorial

**Comment by mimen** [comment]
Yep, also having this problem. Is this a new issue?

**Comment by noffle** [comment]
Yes this seems to be a new issue across at least learnyounode and javascripting.

**Comment by SMTaha** [comment]
Same issue in learnyounode and scope-chains-closures.

**Comment by mimen** [comment]
I noticed the issue in every module that I tried. Any word on if this is being worked on? I had some people in the process of going through these tutorials and want to get them going again asap.

**Comment by WaleedAshraf** [comment]
It seems this has been fixed as mentioned here: https://github.com/workshopper/learnyounode/issues/607
But if you are still facing this, please log here [learnyounode](https://github.com/workshopper/learnyounode). Someone might be able to address.
