### ISSUE TITLE
learnyounode - exercise 6

### ISSUE THREAD

**Issue by ghost** [nodeschool/discussions#2268]
this is the learnyounode Exercise 6. All tests pass, and the result is right when compared. but this error is displayed at the end of the test.

### Error output
```
 
your additional module file is: [filter.js] ?exercises.MAKE IT
 MODULAR.fail.mod.dont_use_dot || common.exercise.fail.mod.dont_use_dot ||
 fail.mod.dont_use_dot?

```

### My Code
```js
//####index.js

const filter = require('./filter')

let folder = process.argv[2]
let ext = '.' + process.argv[3]

function callback(err, data) {
	if (err) return 'error'
	for (let i = 0; i < data.length; i++) {
		console.log(data[i])
	}

}

filter(folder,ext, callback)

 //####filter.js
const fs = require('fs')
const path = require('path')

let filesArray = []

function readDir(folder, ext, callback) {
  fs.readdir(folder, function (err, files) {
    if (err) return callback(err, null)

    files.forEach(function (file) {
      if (path.extname(file) === ext) {
        filesArray.push(file)
      }
    })
    callback(null, filesArray)
  })
}

module.exports = readDir 
```

**Comment by FrankleyJones** [comment]
I think you should not do this ( let ext = '.' + process.argv[3] ) in the index.js

The instruction says:
The filename extension argument must be the same as what was passed to your program. Don't turn it into a RegExp or prefix with "." or do anything except pass it to your module where you can do what you need to make your filter work.

**Comment by nboaldin** [comment]
I would like to bump this issue. I am having a similar problem. All my actual and expected are the same but the last error breaks it. I'm not quite sure how to deal with it.

" Your additional module file [mod.js] may be matching "ext" instead of
 '.ext' "

**Comment by noffle** [comment]
@nboaldin could you share your code?

**Comment by nboaldin** [comment]
Sure thing:

```js
// mod.js
const fs = require("fs");

let arr = [];

function filterData(ext2, data2) {
  return data2.filter(function(files) {
    return files.includes(ext2);
  });
}


module.exports = function(dirName, ext, callback) {
  fs.readdir(dirName, function (err, data) {
    if (err) {
      return callback(err, null);
    }
    arr = filterData(ext, data);
    return callback(null, arr);

  });
};


// mod2.js
const mod = require('./mod');


const dir1 = process.argv[2];
const fileType = process.argv[3];
const whenDone = function(err, arr) {
  if(err) {
    console.log(err);
  } else {
  for(i = 0; i < arr.length - 1; i++) {
    console.log(arr[i]);
  }
  }
}




mod(dir1, fileType, whenDone);

```

**Comment by yongqiangyue** [comment]
// index.js
let listext= require('./lsmodule.js');

let folder = process.argv[2];
let ext = process.argv[3];

listext(folder, ext, (err, files) =>{
     if(err) return console.error(err);
     files.forEach(file =>{
          console.log(file);
     });
});

// lsmodule.js
const fs = require('fs');
const path = require('path');

function listext(folder, ext, callback){
   fs.readdir(folder, (err, files) =>{
     if(err){
         return callback(err, null);
     }    
    callback(null, files.filter(file =>{
         return path.extname(file) === '.' + ext; // 
        }));
    });
}

module.exports= listext;

**Comment by yongqiangyue** [comment]
`// index.js
let listext= require('./lsmodule.js');

let folder = process.argv[2];
let ext = process.argv[3];

listext(folder, ext, (err, files) =>{
if(err) return console.error(err);
files.forEach(file =>{
console.log(file);
});
});

// lsmodule.js
const fs = require('fs');
const path = require('path');

function listext(folder, ext, callback){
fs.readdir(folder, (err, files) =>{
if(err){
return callback(err, null);
}
callback(null, files.filter(file =>{
return path.extname(file) === '.' + ext; //
}));
});
}

module.exports= listext;`

**Comment by yongqiangyue** [comment]
// mod.js
const fs = require("fs");

let arr = [];

function filterData(ext2, data2) {
  return data2.filter(function(files) {
    //return files.includes(ext2);
     path.extname(files) === '.' + ext2;
  });
}


module.exports = function(dirName, ext, callback) {
  fs.readdir(dirName, function (err, data) {
    if (err) {
      return callback(err, null);
    }
    arr = filterData(ext, data);
    return callback(null, arr);

  });
};


// mod2.js
const mod = require('./mod');


const dir1 = process.argv[2];
const fileType = process.argv[3];
const whenDone = function(err, arr) {
  if(err) {
    console.log(err);
  } else {
  for(i = 0; i < arr.length - 1; i++) {
    console.log(arr[i]);
  }
  }
}




mod(dir1, fileType, whenDone); 
@nboaldin
