### ISSUE TITLE
Error in Exercise 7 learnyounode

### ISSUE THREAD

**Issue by Jayant-Isswani** [nodeschool/discussions#2271]
The question is as follows:
```
Write a program that performs an HTTP GET request to a URL provided to you  
as the first command-line argument. Write the String contents of each  
"data" event from the response to a new line on the console (stdout).  
```

Here is my code for learnyounode exercise 7:
```
var http=require('http');
http.get(process.argv[3],function(response){
	resonse.on("data",function(err,data){
		if(err)
			throw err;
		console.log(data.toString());
	})
})
```

Here is the error I am getting:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

How do I solve this?

**Comment by lvoneduval** [comment]
I don't know why you get that error but i see two problème in your code.

first : (line 3) resonse.on => response.on
seconde: (line 2) process.argv[3] => process.argv[2]

i have nearly the same code. Except the error handling. It works.

sorry for my bad english.
Lionel.

**Comment by Jayant-Isswani** [comment]
Thankyou for pointing out the mistake, Lionel :)
Both your observations needed to be sorted out to get correct result.
