### ISSUE TITLE
promise-it-wont-hurt: "You used reject method with non-Error"

### ISSUE THREAD

**Issue by wowdacom** [nodeschool/discussions#2274]
I am learning Promise way with promise-it-wont-hurt and getting stock on problem2  "Reject a promise". I don't know what happen in it.

After verifying program, it showed that belong: 

✓ Submission results match expected
✓ Used the Promise constructor
✗ You used reject method with non-Error
✓ Used then method

Here is my code :
```JavaScritp
'use strict';

var promise = new Promise((fulfill, reject)=>{
  function Error(message){ this.message = message}
  setTimeout(reject, 300,new Error('REJECTED!'))
})

function onReject (error) {
  console.log(error.message)
}

promise.then((fulfill)=>{
   console.log('SUCCESS!')
}, (reject)=>{
   onReject(reject)
})
```

**Comment by Dynom** [comment]
I just stubled upon here through a meetup link, I have no affiliation with Nodeschool, but thought to chip in :-)

I'm not sure why your code doesn't validate, perhaps a reject(42); is needed somewhere, although the exercise doesn't mention the exact rule. Hopefully one of the Node School mentors can elaborate on that.

However to give other tips: You don't need to create the Error function with `this.message = message`. The error constructor already has this property (See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message).

So I suppose you could shorten your code to:
```js
const promise = new Promise(function (_, reject) {
  setTimeout(() => reject(new Error('REJECTED!')), 300);
});

function onReject(error) {
  console.log(error.message);
}

promise.then(null, onReject);
```
