### ISSUE TITLE
Exercise 6 of learnyounode

### ISSUE THREAD

**Issue by Julias0** [nodeschool/discussions#2276]
Module file - 
var fs = require('fs');

module.exports = function filteredLs(dir, ext, lsHandler) {
    
    fs.readdir(dir, function callback(err, list) {
        if (err)
            return lsHandler(err);
        
        list.forEach(v => {
            extension = v.split('.')[1];

            if (extension == ext) {
                lsHandler(null,v);
            }
        });

    });
}

File I am running in verify
var fileReaderMod = require('./handlerMod');

fileReaderMod(process.argv[2],process.argv[3],function lsHandler(err,data){
    if(err){
        console.log(err);
        return;
    }
    console.log(data);
});

I am getting the error - cannot read property call of undefined

**Comment by Gevie** [comment]
Take note of the following line in your module:

`module.exports = function filteredLs(dir, ext, lsHandler) {`

This should be changed to the following in order to make it a single function module.

`module.exports = function(dir, ext, lsHandler) {`
