### ISSUE TITLE
Challenge 10 in Javascripting

### ISSUE THREAD

**Issue by A-Sm1th** [nodeschool/discussions#2279]
### If you have a problem with an error message:

* node version: 8.9.4
* npm version:  5.7.1
* os: mac

### Error output
```
 # JAVASCRIPTING

## FOR LOOP (Exercise 10 of 19)

─────────────────────────────────────────────────────────────────────────────

# O-oh, something isn't working.

# But don't panic!

─────────────────────────────────────────────────────────────────────────────

## Check your solution:

 Solution ===================

 45

 Your Attempt ===================

 Difference ===================

 45 
```

### My Code
```js
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++){
    total += i;
}
```

**Comment by A-Sm1th** [comment]
Thanks @ericcgu for your answer.

When I add console.log() as follows:
```
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++){
    console.log(total += i);
}
```

I get this:
0
VM88:4 1
VM88:4 3
VM88:4 6
VM88:4 10
VM88:4 15
VM88:4 21
VM88:4 28
VM88:4 36
VM88:4 45
undefined

Could you please tell me where I did wrong?

Thanks in advance!

**Comment by RamenNoodlez** [comment]
## The Challenge:
After the for loop, use console.log() to print the total variable to the terminal.

The console.log needs to reside after the close curly brace "}"
having it before (inside the braces) makes it log during each loop.

**Comment by A-Sm1th** [comment]
![screen shot 2018-04-02 at 20 14 36](https://user-images.githubusercontent.com/24876060/38208783-80db6e62-36b2-11e8-99dc-e2c6e8680667.png)

I followed your instructions but still keep getting an error...

`
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++){
    total += i;
}
console.log();
`

**Comment by RamenNoodlez** [comment]
I'm sorry, I was unclear. console.log() takes an argument in its parentheses.
In this case you are trying to print the value of the total variable. 
You would need to use:

 console.log(total)

**Comment by RamenNoodlez** [comment]
You missed the total in console.log()

`var total = 0; 
var limit = 10; 
for (var i = total; i < limit; i++){
    total += i; 
} 

console.log(total);`

**Comment by A-Sm1th** [comment]
Thanks!
