### ISSUE TITLE
Lesson 2 Baby Steps. Yup. Baby Steps. It's not going well.

### ISSUE THREAD

**Issue by jamonjamon** [nodeschool/discussions#2283]
OK, so my code works when I run it, but it returns NaN when it's verified..??? What am I missing?

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "NaN"                               !=    "154"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

 # FAIL Your solution to BABY STEPS didn't pass. Try again!
```
HOWEVER: I got this when testing:

C:\Users\jaimi\babysteps>learnyounode run program-two.js
205

### My Code
var a = Number(process.argv[2]);
var b = Number(process.argv[3]);
var c = Number(process.argv[4]);

var sum = a+b+c

console.log(sum);
```

**Comment by miguelceja77** [comment]
You are missing ";" in the sum variable. It has to look like this:

`var a = Number(process.argv[2]);
var b = Number(process.argv[3]);
var c = Number(process.argv[4]);

var sum = a+b+c;

console.log(sum);`


that works for me.
