### ISSUE TITLE
Implement Map with Reduce question on solution

### ISSUE THREAD

**Issue by moseskarunia** [nodeschool/discussions#2297]
Hi guys, so, I solved this with below solution

```
function arrayMap(arr, fn) {
    return arr.reduce(function (accumulator, currentValue) {
        accumulator.push(fn(currentValue))
        return accumulator
    }, [])
}

module.exports = arrayMap;
```

but the solution is:

```
module.exports = function arrayMap(arr, fn, thisArg) {
      return arr.reduce(function(acc, item, index, arr) {
        acc.push(fn.call(thisArg, item, index, arr))
        return acc
      }, [])
    }
```

My question is, what's the benefit of using `fn.call(thisArg, item, index, arr)` in the official solution compared to using `fn(currentValue)` my solution (which I think shorter)?

Thank you!

**Comment by noffle** [comment]
I think it's just trying to work the same as the built-in JS `map` function[1], which:

1. ensures that `this` is bound
2. calls the user map `fn` with not only the current value, but also the index that it's at and the entire array

I guess whoever wrote the tests for the exercise wasn't worried about checking that your implementation did those things.

  [1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by moseskarunia** [comment]
idk man, it's doesn't like the test can check what's our real code are.
