### ISSUE TITLE
Não consigo instalar o learnyounode

### ISSUE THREAD

**Issue by lejs200** [nodeschool/discussions#2299]
Ja instalei o javascripting mas quando vou instalar o learnyounode acontece esse erro

C:\Users\leandro>npm install -g learnyounode
npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leandro\AppData\Roaming\npm-cache\_logs\2018-05-06T00_22_0
2_502Z-debug.log

C:\Users\leandro>
```
 
alguém sabe como resolver?

**Comment by airjulio** [comment]
Parece que vc não tem `git` instalado.
Tenta instalar esse aqui: https://git-scm.com/download/win
