### ISSUE TITLE
scope-chains-closures doesn't work

### ISSUE THREAD

**Issue by saint-yellow** [nodeschool/discussions#2300]
Hi, all. The module scope-chains-closures doesn't work when I select a exercise to explore.
The pictures below show the error.

![scope-chains-closures_1](https://user-images.githubusercontent.com/20455640/39828947-6c35ea46-53ef-11e8-8287-6433e8dd6428.png)
![scope-chains-closures_2](https://user-images.githubusercontent.com/20455640/39828948-6c690a8e-53ef-11e8-9557-55a549aeda7e.png)

Hope a solution. Danke.

**Comment by designtech44** [comment]
It works now.  but my solution dose not work. 
I can't tell what I'm doing wrong.... I am new to javascript anyway;  scope is the most confusing to me. 

function foo() {
    var foo;
}
// not sure if I am to be putting this in too? 

if (true) {
    let bar;
}

Please advise.

**Comment by saint-yellow** [comment]
Fine. I reinstalled Node 8.11.2 LTS and scope-chains-closures module. Now cope-chains-closures works well. 

I was using Node 10.3.0 when I opened current issue. Anyway, I can learn JavaSript and Node with nodeschool. 

So if somebody have trouble familiar with this issue, reinstalling Node LTS may be a solution.
