### ISSUE TITLE
learnyounode problem 3

### ISSUE THREAD

**Issue by lchalabi** [nodeschool/discussions#2303]
For the third one, I've tested my code on my own test files and it finds the number of newlines but when I run it through the given tester file it fails. 

```js
var fs = require('fs');
var file = process.argv[2];

var buffer = fs.readFileSync(file);
var stringfile = buffer.toString();
var split = stringfile.split('\n');

var newlines = 0;

for (i = 0; i < split.length; i++) {
	if (split[i] === '') {
		newlines++;
	}
}

console.log(newlines);
```

**Comment by finnp** [comment]
If I get this right you define newlines as empty lines. But it actually wants to know the number of line breaks.

For example, this would be 3 newlines:
```
hello

bye
```

**Comment by theangellmethod** [comment]
You should look at the contents of split[i] to see what you're looking for.  When I run your code on this lesson, I get newlines as 0 and if I look at the contents of split[i] by putting console.log(split[i] after the if statement but inside the for loop, I can see what is going wrong.  The last line of the HINT would help you with this code.  "Note that the test file does not have a newline character ('\n') at the end of the last line, so using this method you'll end up with an array that has one more element than the number of newlines."
