### ISSUE TITLE
sanmiguel team-mate proposal

### ISSUE THREAD

**Issue by D3Portillo** [nodeschool/discussions#2320]
how can I use @nodeschoolbot ?

**Comment by D3Portillo** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
add-team-user sanmiguel arnoldou

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel arnoldou

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @arnoldou to the `sanmiguel` team.

**Comment by arnoldou** [comment]
I am here

**Comment by D3Portillo** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
