### ISSUE TITLE
console is undefined

### ISSUE THREAD

**Issue by catkim** [nodeschool/discussions#2325]
![error](https://user-images.githubusercontent.com/6711552/42121214-c40d514c-7bdf-11e8-9555-c7c0b94c5ded.png)

Error after running verify command
### If you have a problem with an error message:

* node version: 8.9.3
* npm version:  6.1.0
* os: windows 10

### Error output
```
see screen shot, console is undefined
### My Code
```js
console.log('test')
```

**Comment by catkim** [comment]
run node [filename] which was fine but then when I ran node verify [filename] I get that error and can't do anything else

**Comment by noffle** [comment]
@catkim use `learnyounode verify [filename]` to verify your code.

**Comment by noffle** [comment]
`node foo.js` runs a file using node. `learnyounode` is the node workshop program: use this to verify your exercises' correctness.

**Comment by catkim** [comment]
learnyounode verify [filename] produced the error

**Comment by catkim** [comment]
If I restart the cmd and start over then I can move onto the next lesson, just looks like I won't be able to verify my work which is a bummer.

**Comment by catkim** [comment]
I tried using  Gitbash instead of cmd and it's working!!!

**Comment by catkim** [comment]
Thanks for you help Stephen!
