### ISSUE TITLE
HELP I NEED HELP

### ISSUE THREAD

**Issue by benleib** [nodeschool/discussions#2329]
I thought that node would allow me to run java script. But I can't seem to work anything. when I copy and past stuff from this node "school" it says i need to open a shell in order to run the command. I don't know what a shell is. I don't know anything please help. this "school doesn't make sense. It gives me no info, or not the info I need. What even is this node.

**Comment by heaslis3-dcu** [comment]
Hi benleib,

I'm just learning nodeschool myself but I try help you.

First make sure you have installed node.js. Then install git.  I think you either use git or command-line to install the lessons by copying the line of code under each lesson example: npm....learnyounode.

To access the lesson, you can type "learnyounode" in either command-line or git...i think i use command-line.

Here is a video which may help you get started:

https://youtu.be/3rQB5fr_5D4

Sean
