### ISSUE TITLE
Understanding "Juggling Async" challenge

### ISSUE THREAD

**Issue by Leoat12** [nodeschool/discussions#2335]
I'm doing the challenge from "learnyounode" module and on the "Juggling Async" challenge I came up with this solution, which passed the tests.
### My Code
```js
 var http = require('http');
var bl = require('bl');
var url = process.argv[2];
var url2 = process.argv[3];
var url3 = process.argv[4];
http.get(url, (res) => {
        res.pipe(bl((err, data) => {
            if(err){
                return console.log(err);
            }
            console.log(data.toString());

            http.get(url2, (res) => {
                res.pipe(bl((err, data) => {
                    if(err){
                        return console.log(err);
                    }
                    console.log(data.toString());

                    http.get(url3, (res) => {
                        res.pipe(bl((err, data) => {
                            if(err){
                                return console.log(err);
                            }
                            console.log(data.toString());
                        }))
                    })
            }));
        });
    })
)});
```
I assumed that after http.get() the program would not wait for the result and would go to the next command right away, that's why, to make that it would come in the right order, I chained the calls, calling them in the callback of the previous http.get() and it passed. However the solution, as you probably know already, is as follows:
```js
var http = require('http')
var bl = require('bl')
var results = []
var count = 0

function printResults () {
  for (var i = 0; i < 3; i++) {
    console.log(results[i])
  }
}

function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(function (err, data) {
      if (err) {
        return console.error(err)
      }

      results[index] = data.toString()
      count++

      if (count === 3) {
        printResults()
      }
    }))
  })
}

for (var i = 0; i < 3; i++) {
  httpGet(i)
}
```
Based on my understanding of async and callback, the program would not wait for the http.get() result and would go immediately to the next interaction of the loop and so on. How this code guarantee that the first call will certainly be the first to finish and be added to the results array? My understanding of async call is wrong anywhere?

If it is the wrong place to ask this kind of question, please let me know. 
Thanks in advance for the answers!

**Comment by davecocoa** [comment]
Your understanding of async is spot on, I think you've just missed a subtlety of adding to the array...

>> How this code guarantee that the first call will certainly be the first to finish and be added to the results array?

This code does *not* guarantee that the first call will be the first to finish, the calls can finish in any order and that's fine because:
```
results[index] = data.toString()
```
It's not using `push` to add to the end of the array, but assigning directly to an index, based on which call has just finished. This, combined with the `count` variable to figure out when every request has finished, allows making all 3 requests immediately, and logging as soon as all 3 results have arrived.

**Comment by Leoat12** [comment]
I didn't notice that, very smart indeed! Thank you for the explanation, it is indeed a much more elegant way to do this.

**Comment by dbiehle** [comment]
Yes, thank you for that explanation @davecocoa! I was trying to push those little dudes into the array and wondering what was up. Indexing for the win!
