### ISSUE TITLE
want: intro to JS workshopper

### ISSUE THREAD

**Issue by maxogden** [nodeschool/discussions#234]
(continued from https://github.com/baltimorenodeschool/baltimorenodeschool.github.io/issues/2)

We need to make an interactive workshopper (just like everything else on http://nodeschool.io/) that introduces JavaScript for absolute beginners!

I think the workshop should start assuming no JS knowledge and build up through intermediate skills like callbacks, bind, prototype, etc.

Here are existing curriculum/resources that can be combined to make this happen:
- https://gist.github.com/chrisdickinson/821359fb8d95570ab22a
- http://afeld.github.io/advanced_js/
- http://www.girldevelopit.com/materials
- http://jsforcats.com/ (video https://www.youtube.com/watch?v=GeCWaTML3D0)

All of the workshoppers so far have been CLI + node based, and we have a robust module for creating the workshops (http://npmjs.org/workshopper), so this one should probably follow suit, unless the person writing it feels strongly that it needs to be implemented in some other way.

**Comment by Sequoia** [comment]
huzzah! :tada: https://github.com/sethvincent/javascripting
