### ISSUE TITLE
Arrays bug?

### ISSUE THREAD

**Issue by slimferg** [nodeschool/discussions#2343]
Hello everyone 
I am on 
# JAVASCRIPTING  
 ## ARRAYS (Exercise 11 of 19)  

however when i run javascripting verify arrays.js  after following instructions it looks like it is reading from the program.js exercise

## Check your solution:

 Solution ===================

 [ 'tomato sauce', 'cheese', 'pepperoni' ]

 Your Attempt ===================

 hello

 Difference ===================

 [ 'tomato sauce', 'cheese', 'pepperlloni' ]

## Additional troubleshooting:

  » Did you type the name of the file correctly? You can check by running                                                                          
    'ls program.js'. If you see 'ls: cannot access program.js: No such file                                                                          
    or directory,' then perhaps the file doesn't exist, or has a different                                                                          
    name, or is in a different directory.                                     
  » Make sure you didn't omit any parens, or the compiler will not be able                                                                          
    to parse it.                                                              
  » Make sure you don't have any typos in the string itself.    

Thanks in advance for your help

Luke

**Comment by kwaping** [comment]
Are you sure the contents of arrays.js are correct?
