### ISSUE TITLE
I can't figure out the error

### ISSUE THREAD

**Issue by aditya2000** [nodeschool/discussions#2347]
### Error output
```
 Your additional module file [modularFunc.js] returned an error on its
 callback: { [Error: ENOENT: no such file or directory, scandir 'verify']
 errno: -2, code: 'ENOENT', syscall: 'scandir', path: 'verify' }
```

### My Code
modular.js
```js
const fs = require('fs');
const path = require('path');
const myFunc = require('./modularFunc.js');

/*fs.readdir(process.argv[2], (err, data) => {
  if(err) console.log("Error:" + err);
  else{
    let filteredList = data.filter(file => path.extname(file)== `.${process.argv[3]}`);
    filteredList.forEach(file => console.log(file));
  }
})*/

const callback = (err, data) => {
  if(err) console.log('ERROR:' + err);
  else data.forEach(file => console.log(file));
}

myFunc(process.argv[2], process.argv[3], callback);
})
  

```

modularFunc.js

```js
const path = require('path');
const fs = require('fs');


module.exports = (pathname, filename, callback) => {
  fs.readdir(pathname, (err, list) => {
    if(err) return callback(err);

      
      let filteredList = list.filter(file => path.extname(file)== `.${filename}`);
      callback(null, filteredList)



  })
}

```

**Comment by noffle** [comment]
In `modular.js` you call `myFunc` with parameters `__dirname` and `process.argv`.

- Is [__dirname](https://nodejs.org/api/modules.html#modules_dirname) what you meant to use?
- What kind of object is `process.argv`? You're treating it like a filename. Add a line above `myFunc` like `console.log(process.argv)` and see what it outputs. How about `process.argv[2]`?

**Comment by aditya2000** [comment]
It was specified in the instructions that you have to pass the name of directory. 
process.argv is the data entered by command line arguments

**Comment by noffle** [comment]
@aditya2000 You're right, the program needs the name of a directory. The instructions say

>  The first argument is the directory name and the second argument is the extension filter.

**Comment by aditya2000** [comment]
Yea but it's not working.Earlier only one test was failing so, I made some changes, but now its passing only one test.

**Comment by noffle** [comment]
What command are you running to verify your code?

**Comment by noffle** [comment]
Your latest code (minus the leftover `})` on the last line of `modular.js` passes all tests on my machine.

**Comment by aditya2000** [comment]
I'm using learnyounode verify module.js

**Comment by aditya2000** [comment]
I think I forgot to delete that ```}) ``` here but in my system i'm not using it and it's running but cannot pass the verification
learnyounode run module.js --> for executing  
learnyounode verify module.js --> to verify
