### ISSUE TITLE
I'm stuck trying to find the basic tutorial

### ISSUE THREAD

**Issue by David263** [nodeschool/discussions#2348]
I'd like a basic tutorial in node.js and npm. But https://nodeschool.io just confuses me. I click on Tutorials, but can't find a way to run a basic tutorial. What basic step am I missing, if any?

**Comment by noffle** [comment]
On the left there is a terminal-window-like graphic with two commands inside of it:

```bash
npm install -g learnyounode
learnyounode
```
If you have Node.JS installed, you ought to be able to run these commands. The first installs the `learnyounode` workshopper, and the second runs it. It should boot up a list of exercises that you can select from with the arrow keys and Enter.

**Comment by sedmo** [comment]
Thanks a lot! I had the same question

**Comment by scollar71** [comment]
npm install -g learnyounode fails to install for me 

`npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
Unhandled rejection Error: Command failed: /bin/git submodule update -q --init --recursiveode_modules/.staging/core-js-b2946a5a (6653
fatal: failed to stat '/root/.npm/_cacache/tmp/git-clone-dca3cce1': Permission denied`

**Comment by noffle** [comment]
@scollar71 You can use `sudo npm install -g learnyounode`.
