### ISSUE TITLE
Javascripting challenge #2 and #3

### ISSUE THREAD

**Issue by Anarchonist7** [nodeschool/discussions#2357]
What is wrong with my code here? These are simple exercises and idk what I could possibly be doing wrong. I know this code works and logs the string to the console...

variables.js:

var example = 'some string'

console.log(example)

strings.js:

var someString = 'this is a string';

console.log(someString);

**Comment by Anarchonist7** [comment]
okay nvm I figured it out, wasn't saving the file, lol, don't make fun of me

**Comment by AnshuPrince** [comment]
close the issue.XD

**Comment by canadiankay** [comment]
> okay nvm I figured it out, wasn't saving the file, lol, don't make fun of me

LOOOOOL this was my mistake too!! I thought I was the only one xD
