### ISSUE TITLE
stuck on 6/13 from learnyounode

### ISSUE THREAD

**Issue by SweeToxin** [nodeschool/discussions#2358]
Hello,

I'm still having a problem on how to use callbacks, I'm actually on 6/13 from learnyounode and have no idea how to fix the following : 
```js
var fs = require("fs");
var path = require("path");

function lines(directoryName, extention, "WHATTODOHERE") {
  fs.readdir(directoryName, "utf8", function filtering(err, data) {
    var filter = "." + extention;
    var lookedForExtentions = data.filter(
      element => (filter == path.extname(element) ? true : false)
    );
    return lookedForExtentions.join("\n");
  });
}

module.exports = lines;
```
help ?! 

best regards;

**Comment by dbiehle** [comment]
I'm with you on the fuzziness. I kinda get the callback, but also feel like I'm stabbing in the dark to get my answer. Even though you solved your problem, I think this issue should remain open until someone is able to provide a good explanation of how, when, and why to use callbacks, particularly in situations like creating modules.
