### ISSUE TITLE
Stuck on  LOOPING THROUGH ARRAYS (Exercise 14 of 19)

### ISSUE THREAD

**Issue by banet** [nodeschool/discussions#2359]
### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
``` Difference ===================

 [ 'cats', 'dogs', 'rats' ]

### My Code
```js
 // copy your code here
var pets = ['cat', 'dog', 'rat'];

// Creating a for loop

for (var i = 0; i < pets.length; i++) {
    pets[i] = pets[i] + "s";
    
}
console.log("[" + pets[0] + pets[1] + pets[2] + "]");
```

**Comment by kevinsimper** [comment]
@banet Hi Bane, what problem do you experience? 😄

**Comment by kevinsimper** [comment]
You should just say `console.log(pets)`, then it will come out as expected :)

**Comment by kevinsimper** [comment]
@banet Great, that is really good to hear! 👍You should close this issue 😄
