### ISSUE TITLE
Markdown Challenge #4 Lists

### ISSUE THREAD

**Issue by kippo1234** [nodeschool/discussions#2364]
# Lists

- One
        - 1.1
        - 1.2
- Two
        - 2.1
        - 2.2
- Three
- Four
- Five
--------------------------------------------------------
this should be the solution to the problem, but its  not working and ive tried making my own list as wanted and that also didnt work. Please help.

**Comment by itzsaga** [comment]
Hello @kippo1234, the answer should look like this:
```markdown
# Lists

- One
  - 1.1
  - 1.2
- Two
  - 2.1
  - 2.2
- Three
- Four
- Five
```
Which turns into this:
# Lists

- One
  - 1.1
  - 1.2
- Two
  - 2.1
  - 2.2
- Three
- Four
- Five

You'll notice that if you use that there will be bullets for `1.1`, `1.2`, `2.1`, and `2.2`. There needs to be at least two spaces before nested items.
