### ISSUE TITLE
Error installing a javascripting in OSX

### ISSUE THREAD

**Issue by jorgelu54** [nodeschool/discussions#2365]
`npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm ERR! path ../lib/node_modules/javascripting/bin/javascripting
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/javascripting/bin/javascripting' -> '/usr/local/bin/javascripting'
npm ERR!  { [Error: EACCES: permission denied, symlink '../lib/node_modules/javascripting/bin/javascripting' -> '/usr/local/bin/javascripting']
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, symlink '../lib/node_modules/javascripting/bin/javascripting' -> '/usr/local/bin/javascripting'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../lib/node_modules/javascripting/bin/javascripting',
npm ERR!      dest: '/usr/local/bin/javascripting' },
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, symlink \'../lib/node_modules/javascripting/bin/javascripting\' -> \'/usr/local/bin/javascripting\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/javascripting/bin/javascripting',
npm ERR!   dest: '/usr/local/bin/javascripting' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jorgelu54/.npm/_logs/2018-10-18T05_08_50_893Z-debug.log`

**Comment by paolovalladolid** [comment]
I had to run sudo chmod 777 on the node_modules directory to get the installer to run, but even then there were some minor errors:

npm install -g learnyounode
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated boganipsum@0.1.0: no longer maintained
/usr/local/bin/learnyounode -> /usr/local/lib/node_modules/learnyounode/bin/learnyounode
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: codeclimate-test-reporter@github:codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa (node_modules/learnyounode/node_modules/i18n-core/node_modules/codeclimate-test-reporter):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: /usr/bin/git ls-remote -h -t ssh://git@github.com/codeclimate/javascript-test-reporter.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: exited with error code: 1
