### ISSUE TITLE
exercise 7 of learnyounode (http.client)

### ISSUE THREAD

**Issue by Ba-ran** [nodeschool/discussions#2371]
Dear  Nodeschoolers,

npm version 6.4.1
node version v8.12.0

I am stuck at exercise 7 of learnyounode.

The code that I have thus far:
----------------------------------------------------------------------------
const http = require('http');

console.log(http.get(process.argv[2], function callback (res){

    res.setEncoding("UTF-8");

    res.on("data", function (data){console.log(data)} )
}));
----------------------------------------------------------------------------

The output is no where near the expected result.

Can someone explain me what I am doing wrong?

Thank you in advance

Kind regards,

Baran Demir

**Comment by MGenteluci** [comment]
@Ba-ran, as I can see you are logging the results twice. You should only use console.log() in res.on(), not in http.get().

Hope it helps!

**Comment by Ba-ran** [comment]
OMFG, at a certain point I just didnt keep track of changing the code and just wanted it to work... But your suggestion helped. Thank you :-)
