### ISSUE TITLE
stuck in learyounode #6 cannot find the problem

### ISSUE THREAD

**Issue by lorenalugo** [nodeschool/discussions#2373]
this is my code:
```
var fs = require('fs');
var path = require('path');

module.exports = function (folder, extension, callback){
	fs.readdir(folder, "utf8", (err, data) => {
		if(err) {return callback(err)};
		return callback(null, data.forEach((file) => {
				if(path.extname(file) == extension){
					console.log(file);
				}
			})
		);
	});
}
```

so, I get the list with an undefined at the end. Please help I don't get it.

**Comment by MGenteluci** [comment]
Hi @lorenalugo . As i can see the problem happens in `path.extname(file) == extension`.
If you `console.log(path.extname(file))` it will give you only the extension without the `.`, and the string in the `extension` parameter is `.md`.

So a fast solution would be `if(path.extname(file) == '.' + extension)`.

Still i'm pretty sure you are gonna go through a feel more problems in this challenge, but I'm not gonna give you answers to problems you haven't even faced yet.

**Comment by lorenalugo** [comment]
@MGenteluci That's not the problem, in fact, the '.' was already in the code, the problem is when I run the module, it results in the list of files with a 'undefined' at the end, like the last item in the list.
Like this: 
doc.txt
doc1.txt
doc2.txt
undefined

**Comment by MGenteluci** [comment]
Can you post here the other part of your code?

**Comment by lorenalugo** [comment]
Hi, @MGenteluci This is the rest of the code: 
```
var dir = process.argv[2];
var ext = "."+process.argv[3];
var mymodule = require('./argsmodule.js');

function show(e,dat){
	if(e){
		console.log(e);
	}
	console.log(dat);
}


mymodule(dir,ext,show);
```

**Comment by MGenteluci** [comment]
Oh ok, @lorenalugo when you do `console.log(dat);` you are just logging undefined because the parameter `dat` has no value since you didn't return anything from your module.
This line of code: `data.forEach((file) => {
				if(path.extname(file) == extension){
					console.log(file);
				}
			}` simply logs the files to the console, it doesn't return anything to the function `show()`.

**Comment by lorenalugo** [comment]
you're right! Thank you @MGenteluci 
I already solved it.
