### ISSUE TITLE
stuck on execution/verify excerzise 10

### ISSUE THREAD

**Issue by crypt0nate** [nodeschool/discussions#2387]
### If you have a problem with an error message:

when running "javascripting verify" or the program itself, the terminal gets stuck - meaning i get no error and the cursor is blinking on new line.. the output of verify is below, what's wrong?

* node version: 10.13.0 
* npm version:  6.4.1
* os: windows 10

### Error output
```
N/A
```
just cursor blinking on new line after execution, can't input

#JAVASCRIPTING 

## FOR LOOP (Excersize 10 of 19) 

_

### My Code
var total = 0;
var limit = 10;
for (var i=0; i < limit; total += i);
console.log(total);

**Comment by marlondlc** [comment]
var total = 0
var limit = 10


for (var limit = 0; limit < 10; limit++) {
       total += limit;
     }

console.log (total)

**Comment by KateDay** [comment]
Can someone explain why this is correct? I'm stuck on 14 and I was stuck on the original looping challenge. I just don't understand how this part of the questions equates this answer:

Create a for loop with a variable i starting at 0 and increasing by 1 each  time through the loop. The loop should run as long as i is less than  limit.  
   
On each iteration of the loop, add the number i to the total variable. To  do this, you can use this statement:  
   
     total += i;
