### ISSUE TITLE
How to console.log only last value after FOR LOOP?

### ISSUE THREAD

**Issue by JulieAman** [nodeschool/discussions#2388]
Hi,
I am currently undergoing a practice and challenge in JS and I am stuck at the FOR loop. 
I need to get rid of the numbers from 0 to 36, as after console.log it should show only number "45". 
How do I console.log it properly??

### My code
```js
// 
var total = 0;
var limit = 10;

for (var i = 0; i < limit; i++, total += i) {
  console.log(total);
}
```

When I check it, it shows this:

Solution ===================
45
Your Attempt ================== 
0 1 3 6 10 15 21 28 36 45
Difference ===================
0 1 3 6 10 15 21 28 36 45

**Comment by tharun208** [comment]
@JulieAman , why cant you check for a condition inside the loop like if index is equal to limit-1 and print the total value

**Comment by JulieAman** [comment]
@tharun208 , thanks a lot! it really helped.

**Comment by JulieAman** [comment]
@tharun208 , no it did not work..

**Comment by JulieAman** [comment]
This is the solution that I have found! :)

```js
// 
var total = 0;
var limit = 10;

for (var i = 0; i < limit; i++) {
  total += i;
}

console.log(total)
```
