### ISSUE TITLE
 npm install -g @angular/cli not working

### ISSUE THREAD

**Issue by ekinmehmet** [nodeschool/discussions#2389]
PS C:\> npm -v
6.4.1
PS C:\> node -v
v10.15.0

after this

PS C:\> npm install -g @angular/cli
[..................] / rollbackFailedOptional: verb npm-session 1fd8069db31329b0

and it has stopped.

**Comment by LordJohn42** [comment]
What does it have to do with Angular and nodeschool?

**Comment by ekinmehmet** [comment]
The problem was about connection problem.
