### ISSUE TITLE
learnyounode - Exercise 3

### ISSUE THREAD

**Issue by SieghartCL** [nodeschool/discussions#2390]
### If you have a problem with an error message:

* node version: v10.15.0
* npm version:  6.4.1
* os: windows 10

### Error output
```
## MI PRIMER I/O! (Ejercicio 3 de 13)


Su resultado propuesto comparado con lo esperado:

                 ACTUAL                                 ESPERADO
────────────────────────────────────────────────────────────────────────────────

   "2"                                 !=    "39"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 El resultado no concuerda con lo esperado!

 ✓

 Método síncrono utilizado: fs.readFileSync()

 # FALLO Su solución a MI PRIMER I/O! no pasó. Intentalo de nuevo!
```

### My Code
```js
var fs = require('fs')

var buf = fs.readFileSync('program.js')
var str = buf.toString()

var lines = str.split('\n')
console.log(lines.length)
```

I don't know what's failing here, because there is 2 lines in the file I'm checking on (it's the one from the exercise 1, with a comment and the console.log("HELLO WORLD") in there); however, it says it's wrong.

Hope that this can get resolved :)

**Comment by wphony** [comment]
The parameter of "readFileSync" should be the argument of command-line, not specified by yourself, you can use process.argv[2] to do it.
