### ISSUE TITLE
Javascripting Functions.js

### ISSUE THREAD

**Issue by MikeTheFyke** [nodeschool/discussions#2400]
Cant seem to figure this one out any suggestions ...

My Code ...

function eat (food) {
       return 'food' + ' tasted really good.';
  }

console.log (eat('food'));

My Error ...

 Solution ===================

 bananas tasted really good.

 Your Attempt ===================

 food tasted really good.

 Difference ===================

 bananasfood tasted really good.

## Additional troubleshooting:

  » Did you type the name of the file correctly? You can check by running                                                                          
    'ls functions.js'. If you see 'ls: cannot access functions.js: No such                                                                          
    file or directory,' then perhaps the file doesn't exist, or has a                                                                          
    different name, or is in a different directory.                           
  » Make sure you didn't omit any parens, or the compiler will not be able                                                                          
    to parse it.                                                              
  » Make sure you don't have any typos in the string itself.                  

It seems the console log is causing the error, which Id love to remove which actually provides the correct output, barring the console.log part of the assignment.

Any help yous can dos would be appreciated.

**Comment by nov314k** [comment]
Remove quotes around food, and it will work.
The function should be:

function eat (food) {
    return food + ' tasted really good.';
}

food (without single quotes) is the value of the function argument (whatever you pass to the function). 'food' (with single quotes) is always the same four-letter string.

Cheers
