### ISSUE TITLE
Disappearing Act

### ISSUE THREAD

**Issue by KateDay** [nodeschool/discussions#2408]
So I easily made it through the variables challenge and when I moved on to the next one, I keep getting "-bash var command not found"

what's up with that? I did not enter any bash editing or anything, I went straight into the next challenge and got this. 

### Error output
```
-bash: var: command not found
```

### My Code
```js
var someString = 'this is a string'
```

**Comment by hackergrrl** [comment]
Hi Kate. How are you running your code?

**Comment by KateDay** [comment]
> Hi Kate. How are you running your code?

so I'm running it on linnux in terminal and I'm in my javascripting folder with vagrant up... here's exactly what I'm doing:
vagrant [javascripting]> var someString = 'this is a string';
-bash: var: command not found
vagrant [javascripting]> node -v
v8.9.4
vagrant [javascripting]> npm -v
5.6.0

**Comment by hackergrrl** [comment]
Did you run code from previous exercises in the same way? It looks like `vagrant [javascripting]>` is a bash prompt, which won't be able to interpret node code. (If this sounds super obvious then I probably misunderstood your problem!)  Have you tried writing your code into a file (e.g. `exercise.js`) and typing `node exercise.js` into that prompt?

**Comment by KateDay** [comment]
I could have sworn I did. Sorry I'm a total noob. I did the first exercise then moved right into the second. I did not change anything in between so  i'm not sure how this got changed. can you help me change it back into interpreting node please?

**Comment by hackergrrl** [comment]
Maybe you're thinking of the node [REPL](https://en.wikipedia.org/wiki/REPL)? You can run that by running `node` as a command by itself. That will let you run nodejs code line by line. CTRL+D to exit that.

To verify your exercises though, you'll have to write your code to a file, so you can then run `javascripting verify program.js` (where `program.js` is whatever you named your source code fle).

**Comment by KateDay** [comment]
so I typed in node ... here's what happened:

vagrant [javascripting]> node
> var example = 'some string';
undefined
> javascripting verify variables.js
javascripting verify variables.js
              ^^^^^^

SyntaxError: Unexpected identifier

**Comment by KateDay** [comment]
So even in the node REPL, the command var is still not working. Anything?? 

I've googled and found that **var** could be replaced with "**let**" or "**const**"?

**Comment by hackergrrl** [comment]
When you run `node` you can only type in javascript. However, `javascripting verify` is a bash command.

I recommend the route of writing your code to a file, and then running `javascripting verify` on that, instead of trying to use the REPL.

**Comment by KateDay** [comment]
Thanks noffle!

I figured it out last night. I was doing all the work in the terminal instead of the text editor (sublime) and was confused. I now know my error and am a touch embarassed to make such a simple error. so basically doing exactly what you said to do. sorry.

**Comment by hackergrrl** [comment]
aw, no worries. I still make the most ridiculous mistakes :D
