### ISSUE TITLE
javascripting scope - exercise 19

### ISSUE THREAD

**Issue by KateDay** [nodeschool/discussions#2409]
This probably is a silly and simple question, but I'm not sure what I'm doing wrong. My answer is the same as the solution but it wont mark it complete. Clearly there is something wrong with the code??

vagrant [javascripting]> node -v
v8.9.4
vagrant [javascripting]> npm -v
5.6.0

linux

### Error output
```
## Check your solution:

 Solution ===================

 a: 1, b: 8, c: 6

 Your Attempt ===================

 Difference ===================

 a: 1, b: 8, c: 6 

### My Code
```js
var a = 1, b = 2, c = 3;

(function firstFunction(){
  var b = 5, c = 6;

    (function secondFunction(){
      var b = 8;

      (function thirdFunction(){
        var a = 7, c = 9;

        (function fourthFunction(){
          var a = 1, c = 8;

console.log('a: '+a+', b: '+b+' , c: '+c);
        });
      });
    });
});
```

soooo What? I got the answer right but it won't take it??

**Comment by hackergrrl** [comment]
I think what it's saying is that the "My Attempt" section is blank, and then the "Difference" between their solution and yours is that theirs prints out that value, and yours prints nothing. What do you see when you run your code yourself?

**Comment by hackergrrl** [comment]
Hint: `function name () { /* some code */ }` **defines** a function, but doesn't run it.

**Comment by KateDay** [comment]
Yup. I see that I got it wrong and nothing showed... I'm still not getting the right answer...

I just don't understand how I'm able to access a local scope, globally. 

the question clearly states :
Use your knowledge of the variables' scope and place the following code  
  inside one of the functions in scope.js so the output is a: 1, b: 8, c: 6  
   
     console.log("a: "+a+", b: "+b+", c: "+c);  

... however putting the console.log inside a local just outputs nothing, as discovered yesterday evening. Yes, I've been reading and trying different things all day and have had zero luck. please send help!!

**Comment by hackergrrl** [comment]
The problem isn't that you're accessing local scope wrong, it's that you aren't running the functions you're defining. :)

Here's an example of defining and running a function:
```js
function add (a, b) {
  return a + b
}
add(1, 2)
```

This can also be expressed by wrapping a nameless function in parentheses and calling *that*:

```js
(function (a, b) {
  return a + b
})(1, 2)
```

The two perform an equivalent computation.

Compare this to simply defining (and *not* calling) a nameless (anonymous) function:

```js
(function (a, b) {
  return a + b
})
```

which defines a function, but doesn't call it.

**Comment by KateDay** [comment]
OMG I finally got it!!! Thank you so much for your explanations!! my issue was  not being sure how to call it properly! YES!!

**Comment by hackergrrl** [comment]
yaay :cake:
