### ISSUE TITLE
Console NODE

### ISSUE THREAD

**Issue by mandycuba** [nodeschool/discussions#2411]
Hi, Iam new in nodeJS, i have a cuestion. 
I have a new project, whit a function Hola Mundo, for example
fuction hi(){
print "Hola Mundo"
}
Is it possible to arbitrarily call the console from windows?

**Comment by huanghe2015** [comment]
You have to invoke this function in the source file or paste it in REPL to test whether it works out.

**Comment by huanghe2015** [comment]
@stale It can be closed.
