### ISSUE TITLE
...

### ISSUE THREAD

**Issue by LukeAnton** [nodeschool/discussions#2413]
~ npm install -g learnyounode
npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
/Users/luke/.npm-packages/bin/learnyounode -> /Users/luke/.npm-packages/lib/node_modules/learnyounode/bin/learnyounode
+ learnyounode@3.5.10
updated 1 package in 2.522s

**Comment by huanghe2015** [comment]
It works fine without error, post this to related repository belongs to.

**Comment by huanghe2015** [comment]
https://github.com/workshopper/learnyounode

**Comment by Ruheee** [comment]
hello! was there ever any solution to this? I am currently getting the same error
