### ISSUE TITLE
文件内容是console.log('Hello, World!');

### ISSUE THREAD

**Issue by fancx** [nodeschool/discussions#2414]
你提交的结果与预期结果的比较如下:

                实际结果                                预期结果
────────────────────────────────────────────────────────────────────────────────

   "Hello, World!"                     !=    "HELLO WORLD"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

 ✗

 提交的结果不符合预期！

 # 失败 你对 你好，世界 所作的答案未通过验证， 请再试一次！

**Comment by huanghe2015** [comment]
把右边的复制一下就好啦！
