### ISSUE TITLE
how do I make a discord.js/node.js command with multiple responses?

### ISSUE THREAD

**Issue by NaeggyH0pe17** [nodeschool/discussions#2430]
I'm having trouble making a discord bot with multiple responses, similar to an 8-ball.
for example, if you were to ask it, 'Hey (bot), should I do ___?', then it would respond with one of many answers, like 'yes', 'no', or 'maybe'.

I've looked up multiple tutorials/guides, and tried them out, yet it still doesn't seem to work. Then again, I'm pretty new at this, so I may just not be understanding it correctly.

**Comment by ghost** [comment]
Hey @NaeggyH0pe17,

You can easily do that by:
```javascript
// an array of strings consisting of the possible messages
const messages = ['Yes', 'No', 'Couldn\'t quite catch that', 'Maybe', 'Never'];
// gets a random string from the array of strings (possible messages)
const random = messages[Math.floor(Math.random() * messages.length)];
// send the message containing the random result in the channel
message..channel.send(`Your anwser is: ${random}`);
```

**Comment by NaeggyH0pe17** [comment]
Ah,, so sorry for not getting back to you, @chroventer !! I've been somewhat busy recently.

How exactly do you connect it so it will respond to a certain message? That is mainly what i'm struggling with at the moment.
(Plus, the editor I used might have deleted my progress, so a simple message ping-pong[?] command would be useful as well ^^)

**Comment by ghost** [comment]
@NaeggyH0pe17,

Check out [Discord.js Guide](https://discordjs.guide) if you want to start from a scratch.
Furthermore, [Discord.js Documentation](https://discord.js.org) contains an example of the ping command.

**Comment by ghost** [comment]
@martinheidegger @NaeggyH0pe17, please close the issue if your issue has been resolve.
