### ISSUE TITLE
TIME SERVER EXERCISE ISSUE

### ISSUE THREAD

**Issue by arora94surbhi** [nodeschool/discussions#2445]
var net = require('net');
var server = net.createServer(socket => {
  var today = new Date();
  var date = today.getFullYear()+'-'+(today.getMonth()+1).toString().padStart(2, '0')+'-'+today.getDate().toString().padStart(2, '0');
  var time = today.getHours().toString().padStart(2, '0') + ":" + today.getMinutes().toString().padStart(2, '0');
  var dateTime = date+' '+time;
  socket.write(dateTime);
  socket.end("");
});
server.listen(process.argv[2]);

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "2019-08-28 20:55"                  ==    "2019-08-28 20:55"                 
                                                          !=    "" 

Second output is wrong. I am not able to figure out why the expected output is ""

**Comment by jtoik** [comment]
Hint: Read the specification carefully:

"For each connection you must write the  
  current date & 24 hour time in the format:  
   
     "YYYY-MM-DD hh:mm"  
   
  **followed by a newline character.**"

(emphasis mine)
