### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by SUNderingPanda** [nodeschool/discussions#2449]
i opened the terminal and tried running the command npm -g javascripting and it says i don't have access and errors out?

### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
```

**Comment by clockelliptic** [comment]
What operating system are you using?

If you happen to be using linux (which can include WSL on win10) try this: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory

**Comment by SUNderingPanda** [comment]
thank you! i just went brute force and installed the package as a root user with "sudo", really appreciate the response!
