### ISSUE TITLE
npm: No such file or directory

### ISSUE THREAD

**Issue by laserblue** [nodeschool/discussions#2460]
# If you have a problem with an error message:

Dory d/node.js on Android 4.4.2

* node version: v6.11.4
* npm version:  npm: No such file or directory ( after I did an npm install npm trying to fix an issue with npm)
* os: Android 4.4.2 (NOTE: I don't know if I can re-install Node because Dory d/node.js is no longer supporting Android 4)

### Error output
npm: No such file or directory

**Comment by victorperin** [comment]
Based on issues you had on #2462 and #2461, it seems to be a problem installing nodejs (and npm) on android).

I never experienced running those on an android environment, but we can try :)
If you have the possibility, try learning on an Windows or Linux system. They tend to work generaly.

My experience running nodejs on android I aways got those type of errors and I think learning while those errors apears tend to be annoying. :/

**Comment by laserblue** [comment]
I ran how-to-npm, learnyoureact, javascripting and other workshops with no problem a few years ago. The main problem I had was to set a path variable for npm and not do global installs.
