### ISSUE TITLE
Setting N_PREFIX to downgrade node

### ISSUE THREAD

**Issue by laserblue** [nodeschool/discussions#2462]
If you have a problem with an error message:
App: Termux
* node version: v13.0.0
* npm version:  6.12.0
* os: Android 6.0

### Error output

npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
-----------------------------'
home  usr
$ cd home
$ ls
bin      lib      myFile.txt  share
include  main.js  n           test-node
$ n 12.13.1
  installing : node-v12.13.1
       mkdir : /usr/local/n/versions/node/12.13.1
mkdir: cannot create directory ‘/usr’: Read-only file system

  Error: sudo required (or change ownership, or define N_PREFIX)

$
```

### My Code
```js
 // copy your code here
```

**Comment by victorperin** [comment]
Hey @laserblue. It seems to be related with the [N project](https://github.com/tj/n) on Android.

Can you also open an issue there? I think people there could have a better experience with it.

Also, there's an alternative to it called [nvm](https://github.com/nvm-sh/nvm) that I use.
To install I recomend:
- uninstall nodejs
- install nvm using this script `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash`
- run `nvm install 12.3.1`
- run `nvm use 12.13.1`

(i never tested it on android. i think it will work.)

**Comment by laserblue** [comment]
Thank you for the information and help.
I know about NVM and will give that script a try.
