### ISSUE TITLE
filtered-ls exercise bug

### ISSUE THREAD

**Issue by meatnordrink** [nodeschool/discussions#2464]
On the filtered-list.js exercise, I got a "could not find directory" error when I tried to verify it using `learnyounode verify filtered-ls.js` : 
`[Error: ENOTDIR: not a directory, scandir '/tmp/_learnyounode_15800.txt']`

Though I had verified the solution myself several times. When I tried pasting in the official solution, I got another error (below). 

It doesn't seem to be recognizing the directory that learnyounode is storing the test directory in. 

I'm running this on Linux. 

```
/home/meatnordrink/Nextcloud/node/filtered-ls.js:5
  list.forEach(function (file) {
       ^

TypeError: Cannot read property 'forEach' of undefined
    at /home/meatnordrink/Nextcloud/node/filtered-ls.js:5:8
    at FSReqCallback.oncomplete (fs.js:152:23)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "15"                               
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✗ 

 Submission results did not match expected!

 ✗ 

 Used asynchronous method: fs.readdir()

 # FAIL Your solution to MY FIRST I/O! didn't pass. Try again!
```

For reference, my solution: 
```js
const fs = require('fs')
const path = require('path')

fs.readdir(process.argv[2], function(err, files){
    if (err) console.error(err)
    for (i = 0; i < files.length; i++) {
        if (path.extname(files[i]) === "." + process.argv[3]){
            console.log(files[i])
        }
    }
})
```

And the "official" one I pasted in: 
```js
var fs = require('fs')
var path = require('path')

fs.readdir(process.argv[2], function (err, list) {
  list.forEach(function (file) {
    if (path.extname(file) === '.' + process.argv[3])
      console.log(file)
  })    
})
```

**Comment by victorperin** [comment]
@meatnordrink I see learnyounode is trying to verify the response of `MY FIRST I/O!` but your solution is about `FILTERED LS`.

To fix it, you can do:
- execute `learnyounode`
- select `FILTERED LS` and press enter (this will output the exercise)
- now you can run `learyounode verify filtered-ls.js`

**Comment by meatnordrink** [comment]
Thank you so much, @victorperin ! That worked perfectly.
