### ISSUE TITLE
Code of conduct for nodeschool events?

### ISSUE THREAD

**Issue by jasonrhodes** [nodeschool/discussions#247]
I see that @hackygolucky mentioned they had a code of conduct for the Portland event, but I'm wondering if people are adopting anything for these events? 

I'm going to use one at the Baltimore event and I'm considering ones that already exist here: baltimorenodeschool/baltimorenodeschool.github.io#3 but if other people have been using one at other nodeschool events, I'd love to hear about it.

Whatever happens, I'll post what we use and how it fared in my write-up after the fact.

**Comment by Sequoia** [comment]
merge & close this ticket when ready: https://github.com/nodeschool/nodeschool.github.io/pull/239

**Comment by Sequoia** [comment]
merged on +1 from oxmageddon
