### ISSUE TITLE
Javascripting Exercise 4 of 20  STRING LENGTH "some thing isn't working"

### ISSUE THREAD

**Issue by YamadaKY** [nodeschool/discussions#2471]
### If you have a problem with an error message:

* node version: v12.14.0
* npm version:  6.13.4
* os: linux  Ubuntu 18.04.3 LTS

### Error output
```
  ## Check your solution:

   Solution ===================

   14

    Your Attempt ===================

   Difference ===================

   14 
  ```

### My Code
```string-length.js

let example = 'example string'  
     example.length  

```

**Comment by danjmaster** [comment]
Maybe you forgot to log it to the console?
`console.log(example.length);`

**Comment by YamadaKY** [comment]
Thank you for answering.

2020年2月9日(日) 18:48 danjmaster <notifications@github.com>:
