### ISSUE TITLE
Error when verifying exercise #10 (for loop)

### ISSUE THREAD

**Issue by jdhal056** [nodeschool/discussions#2473]
Getting this error when i try to verify exercise 10.

* node version: <v8.9.4>
* npm version:  <5.6.0>
* os: linux

### Error output
```
 { Error: Command failed: node "/vagrant/javascripting/for-loop.js"
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x121a2cc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x379fa398463d
Aborted

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 134,
  signal: null,
  cmd: 'node "/vagrant/javascripting/for-loop.js"' }

```

### My Code
```js
 javascripting verify for-loop.js
```

**Comment by danjmaster** [comment]
Post the code that you've written in 'for-loop.js'
The error says you're running out of memory, which suggests you have an infinite loop.
Check the loop condition, and whether you increase the value for 'i'.

**Comment by jdhal056** [comment]
//still have not been able to resolve the issue. 

let total = 0
let limit = 10
for (let i = 0; i < limit; i++) {
return total += i;
}
console.log(total);

**Comment by danjmaster** [comment]
Delete return so that it's just `total += i;`

The moment it hits return the script will finish as it sends back the value of `total += i` to whatever called it.

**Comment by nathan-judge** [comment]
having same issue this is my code

const total = 0
const limit = 10
for (let i = 0; i < limit; i++) {
    total += i;
}
console.log(total)
