### ISSUE TITLE
como usar ?

### ISSUE THREAD

**Issue by DiogoMalfatti** [nodeschool/discussions#2477]
<eu>por favor estive no meetup da nodeschool hj na caelum e conheci a plataforma : https://nodeschool.io/pt-br/

<eu>fiz a instalação para ver como é, deste modulo : 
javascripting
Aprenda o básico de Javascript. Não exige experiencia prévia em programação.

npm install -g javascripting 

<eu>recebi esta mensagem e acredito que instalou corretamente: 
PS C:\Users\dimal\Desktop\exercicios\moderno\modelo> npm install -g javascripting
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
C:\Users\dimal\AppData\Roaming\npm\javascripting -> C:\Users\dimal\AppData\Roaming\npm\node_modules\javascripting\bin\javascripting
+ javascripting@2.7.3
added 729 packages from 336 contributors in 357.578s

<eu> E agora ? como eu faço para usar ? pra onde devo ir ? {obrigado}
<eu> minhas versions de node e npm: 
PS C:\Users\dimal\Desktop\exercicios\moderno\modelo> node -v
v12.13.1
PS C:\Users\dimal\Desktop\exercicios\moderno\modelo> npm -v
6.12.1

**Comment by victorperin** [comment]
Oi @DiogoMalfatti :)

Cara, você instalou o modulo do Javascripting no seu computador. Agora, voce pode rodar o comando `javascripting` no terminal e isso vai aparecer:

![image](https://user-images.githubusercontent.com/5847145/74095928-974bb780-4ad6-11ea-8b33-dff4986d2803.png)

Cada item dessa lista é um exercício diferente. Ao selecionar um exercicio (por exemplo o primeiro), voce vai receber a seguinte informação: (ps: da pra mudar para português no `choose language`):

![image](https://user-images.githubusercontent.com/5847145/74095946-e98cd880-4ad6-11ea-8bd5-fd9cbc786c86.png)

Aqui existe uma descrição do que deve ser feito e algumas dicas.

Nesse caso, ele pede para criar um arquivo com o conteudo `console.log('hello')`. Quando salva-lo, voce pode rodar o comando: `javascripting verify SEU_ARQUIVO.js`.

Se tudo tiver certinho, você vai receber o seguinte output:
![image](https://user-images.githubusercontent.com/5847145/74095976-70da4c00-4ad7-11ea-957d-eb95765dd820.png)

caso alguma coisa esteja errada, o programa vai te avisar exatamente o que aconteceu de errado. (Tudo é testado automaticamente, você só passa de exercícios se seu programa estiver correto.)

Depois, é só continuar rodando o comando `javascripting` novamente. E você verá que o exercício estará marcado como `[completed]`:

![image](https://user-images.githubusercontent.com/5847145/74096005-cadb1180-4ad7-11ea-9844-4a8a9e7e0fed.png)


Assim, é só continuar fazendo a mesma coisa para os próximos exercícios até conseguir completa-los. :)


Espero ter ajudado e se precisar, fique a vontade para conversar comigo por aqui, pelo [twitter](https://twitter.com/victor_perin), [telegram](https://t.me/victorperin) ou pessoalmente em um próximo meetup. :)

**Comment by danjmaster** [comment]
If typing `javascripting` into your normal terminal doesn't work, try this:
Click on 'Start' and type: "node" and look for "Node.js command prompt".
Click on that to open it, then type `javascripting`

-----
Alternatively, type this into your terminal. Or copy/paste. (Ctrl+c, then right-click once in the terminal)
You may have to change the `nodevars.bat` path to where node was installed on your computer
```
C:\Windows\System32\cmd.exe /k "C:\Program Files\nodejs\nodevars.bat"
```
This sets up the environment for using node and npm, the Node.js command prompt is the same as copy pasting the above.

**Comment by luisangelorjr** [comment]
@DiogoMalfatti conseguiu amigo?

Tive um problema agora pra rodar o tuto e vi que não estava encontrando a pasta do npm pois não tinha configurado o caminho dele nas variaveis de ambiente (acredito que o script nodevars.bat do [comentário acima](https://github.com/nodeschool/discussions/issues/2477#issuecomment-586659908) configura no terminal que vc está aberto

Se não conseguiu, nos fale que subimos um tuto de como configurar isso no Windows

Obs.: Oi @victorperin  rsrs
