### ISSUE TITLE
learnyournode - Not found

### ISSUE THREAD

**Issue by beattier-hpinc** [nodeschool/discussions#2481]
* node version: v12.16.1
* npm version:  6.13.4
* os: windows 10 1903

### Error output
```
>npm install -g learnyournode
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/learnyournode - Not found
npm ERR! 404
npm ERR! 404  'learnyournode@latest' is not in the npm registry.
```

**Comment by beattier-hpinc** [comment]
My apologies.  I looked multiple times and could have sworn it said learn**your**node every time.

**Comment by victorperin** [comment]
No problem @beattier-hpinc this is a commom problem. 
Glad you find a way to fix the problem by yourself. :)
