### ISSUE TITLE
exsercise 10 of 20 loop for. Javascripting. (italian)

### ISSUE THREAD

**Issue by yuliya92** [nodeschool/discussions#2488]
Buon giorno a tutti,
scusate se non sono ancora molto pratica con l'inglese ma ci sto lavorando. Sto affrontando la challenge di "loop for" ma non riesco a capirne bene il comando. Ho capito che è un dichiarazione di ciclo (numerato), ma non riesco a entrare nella sintassi. Ho gia provato a leggerla su mozilla ma non riesco a riconvertirlo con l'esercizio. Qualcuno potrebbe aiutarmi.
thanks.
  ### Notes

### Error output
```
## Check your solution:

 Solution ===================

 45

 Your Attempt ===================

 0

 Difference ===================

 45-0


```

### My Code
```js
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++) {

}
console.log(i);
```

**Comment by yuliya92** [comment]
var total = 0;
var limit = 10;
for (var i=0; i<limit; i++){
  total += i;
  console.log(total);
}

this is my new solution but it is wrong. why?

**Comment by andrewjcarter** [comment]
It looks like you're printing out your total every time you're going through your "for" loop. Try moving your console.log statement outside of your for loop and see if that works. :)

**Comment by yuliya92** [comment]
yeahhhhhhh. thank you soooooo much!!!!!!:)))))
