### ISSUE TITLE
problem while building and running a sever using node.js

### ISSUE THREAD

**Issue by rtofficials** [nodeschool/discussions#2491]
i was building a server using node.js.  when i ran it, my browser did not display the response it should (html page or not even plain text). Moreover, if i run the server for any port number, it runs once once,If ai stop it and run again, it throws the following error :
events.js:292
    throw er; // Unhandled 'error' event
Error: listen EADDRINUSE: address already in use 127.0.0.1:5555
  at Server.setupListenHandle [as _listen2] (net.js:1313:16)
     at listenInCluster (net.js:1361:12)
     at doListen (net.js:1498:7)
     at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
     at emitErrorNT (net.js:1340:8)
     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  yscall: 'listen',
  address: '127.0.0.1',
  port: 5555
}

what should i do?

**Comment by danjmaster** [comment]
Post your code please!
In the error it says `throw er;` Is this a typo? Should it be `throw err;` or `throw error;`?

Try comparing your code to a basic node.js tutorial and see if you're missing anything basic.
