### ISSUE TITLE
I need help on if_statement 

### ISSUE THREAD

**Issue by andyjava6** [nodeschool/discussions#2495]
Hi I'm andy and I'm new here I need help on a JS code , this is about the conditional [ if-statement];
if someone could find me the mistake on this exercise , because is important 
the  JS code is below :
.............................................................................................................................................................................................
 var string= ("fruit") orange;

if (n >1) {
    console.log('the variable n is greater than 1.' );
} else {
    console.log('the variable n is less than or equal to 1.');
  {
      console.log("the fruit name has greater than five.");
      
  }  
}
....................................................................................................................................................................................................
thank you 
andy

**Comment by danjmaster** [comment]
Hi Andy :)
If this is your entire code, then you have a few mistakes.
In future, post your code in between back ticks:
\`code here\` will give `code here`
or

\`\`\`javascript
let x = 6;
\`\`\`
gives
```javascript
let x = 6;
```
or use the insert code button.
The second version gives you syntax highlighting for Javascript. (Can use other language names for appropriate highlighting.)
It's also helpful to post any errors you are getting, and also state what you think the code should be doing. Spacing out your code properly also helps you spot errors!
```javascript
var string = ("fruit") orange;
if (n > 1)
{
    console.log('the variable n is greater than 1.' );
}
else
{
    console.log('the variable n is less than or equal to 1.');
    {
        console.log("the fruit name has greater than five.");
    }
}
```
So it looks like your trying to get the length of the string 'orange' and print it to console. Javascript is dynamic, so you don't need to specify types.  I'm going to assume you wanted a variable called fruit, of type string, with value 'orange'.
Also the variable n isn't declared in this code section. You've just started using it. Also assuming it represents the length of the string.
And the if else statement needs some work! The log statements don't really match up with the logic.

```javascript
// Declare a variable called fruit, with the value "orange"
let fruit = "orange"
// Declare n to be the length of our fruit variable, (orange has 6 letters, so n is 6)
let n = fruit.length

//Just log n to the console..
console.log(fruit +  " has " + n + " letters");
//Or use the if else statement
if(n > 1 && n <= 5)
{
    console.log("The length of fruit is greater than 1, but less than or equal to 5"); 
}
else if(n > 5)
{
    console.log("The length of fruit is greater than 5");
}
else
{
    console.log("The variable n is less than or equal to 1");
}
```
Hope that was what you were after. Good luck!

**Comment by andyjava6** [comment]
how can I find others If- statement  training exercises ?

**Comment by danjmaster** [comment]
Try searching.
"if statement tutorial JavaScript"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else

https://www.w3schools.com/js/js_if_else.asp
