### ISSUE TITLE
filtered-ls.js

### ISSUE THREAD

**Issue by beytur** [nodeschool/discussions#2500]
Hello,
I try the challenges of learnyounode (FILTERED LS) and i'm fighting with this program since 2 days but I can't find the mistake. It runs correctly with the hard-coded input (commented out) but .. learnyounode verify filtered-ls.js .. can't find the files correctly..
I'll be very happy if you can help me.
Thanks a lot 
Beytur  

## FILTERED LS (Exercise 5 of 13)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "CHANGELOG.md"                     
                                       !=    "LICENCE.md"                       
                                       !=    "README.md"                        
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

 ✓

 Used asynchronous method: fs.readdir()

 # FAIL Your solution to FILTERED LS didn't pass. Try again!

### My Code
const fs = require('fs');
const path = require('path');

// you can ignore it, only for local testing
//let thePath = 'C:\\Users\\Borovali\\Documents\\priv\\studium\\2020S\\WebEng\\learnyounode';
//    thePath = '/Users/Borovali/Documents/priv/studium/2020S/WebEng/learnyounode/';
//let extend = 'js';

thePath = process.argv[2];
extend = process.argv[3];

var arrOut = [];

function readTheDirectory(callout) {
  fs.readdir('.', function callback(err, files) {
    if (err) console.log('error occurs');

    for (var i = 0; i < files.length; i++) {
      if (path.extname(files[i]) == '.'.concat(extend))
         arrOut.push(files[i]);
    }
    callout();
  })
}

function logFiles() {
  for (var i = 0; i < arrOut.length; i++) {
    console.log(arrOut[i])
  }
}

readTheDirectory(logFiles);

**Comment by danjmaster** [comment]
Hi beytur,
You've made a small mistake in the fs.readdir() function.
The first parameter should be the 'path' variable. Looks like you might have changed it to `'.'` when testing locally, and forgot to change it back?
If you change it to your `thePath` variable (the process.argv[2] one), your code passes.

Cheers
