### ISSUE TITLE
Error finding module

### ISSUE THREAD

**Issue by OlaoyeVic** [nodeschool/discussions#2504]
### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```Error: Cannot find module 'C:\Users\Victor Olaoye\The-JavaScript-Workshop-master\http_server.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

### My Code
```js
 // copy your code here
```var http = require('http');
var port = 3000;

// Spin-up a server instance
let server = http.createServer(function (req, res) {
  res.write('Hello World!'); // Response body
  res.end(); // End the response
});

server.listen(port); //the server object listens on port 3000

**Comment by danjmaster** [comment]
Have you installed NodeJS? And run the correct command to install the node module it looks like you are working on?
Did they install properly or did you get install errors?
You can run `node -v` and `npm -v` in a terminal to make sure they're installed, and what version you are running.

**Comment by OlaoyeVic** [comment]
I have tried that and I'm still getting the same error

**Comment by OlaoyeVic** [comment]
I'm running version v13.12,0 and I never get install errors. This is the
error it keeps giving me👇
Error: Cannot find module 'C:\Users\Victor
Olaoye\The-JavaScript-Workshop-master\http_server.js'

**Comment by danjmaster** [comment]
So http_server.js is the file you're trying to run? It seems like it's having trouble running your file, rather than the code being incorrect. I'll try run your code in a sec and see if it works. It looks like it should.

How are you trying to run the file?
`learnyounode run http_server.js`?
(Either `run` or `verify`)
And are you running the command through command prompt, PowerShell, or NodeJS terminal?

**Comment by danjmaster** [comment]
What is the workshop you are currently doing?

Your code works fine. In a command/powershell window you should be able to navigate to your `the-javascript-workshop-master/` directory, and then run `node http_server.js` then while that shell is open, point your browser to `http://localhost:3000/` and you should see `Hello world!`
In the shell, press `Ctrl+C` to kill the server.

If the above works for you, then it sounds like it has something to do with the way you are trying to run the code.

**Comment by OlaoyeVic** [comment]
It's still not working

**Comment by OlaoyeVic** [comment]
I'm running the command through powershell with: node http_server.js

**Comment by OlaoyeVic** [comment]
Please how do I navigate to the  the-javascript-workshop-master/   directory

**Comment by danjmaster** [comment]
`cd directory-name`
`cd ..` to go back a directory
cd is for change directory
And to see what is in a directory `ls` or `dir`
So
`cd "C:\Users\Victor
Olaoye\The-JavaScript-Workshop-master"`
Should take you to the correct directory.

You'll also need node added to your path. Google "add node to windows path" if you need to do that. But if you can run `node -v` then it sounds like it's already in your path.

**Comment by OlaoyeVic** [comment]
It's already in my path already. It's returning the same error
I'm fed up right now and I've been trying this for more than three weeks
now maybe node.js is not for me

**Comment by danjmaster** [comment]
Do you have a file named http-server.js in that directory?

Make a new folder on your Desktop called 'js'. Inside that folder, make a new file called 'test.js'
Then copy paste or re-type your http-server.js code into test.js
Open a PowerShell window.
Type or copy paste `cd "C:\Users\Victor Olaoye\Desktop\js"`
Type `ls` and check that you have a file called `test.js`, and not `test.js.txt` or anything else in that directory.
Then in the window run `node test.js`
If you still get an error, then I would suggest re installing node, or try googling for another tutorial and following as close as possible, as without seeing your screen/set up I can't tell what is wrong with the info in this thread.
Good luck!

**Comment by OlaoyeVic** [comment]
Thank you so much. It worked like a charm, I'm so happy

**Comment by danjmaster** [comment]
You're welcome, glad you got it working!
