### ISSUE TITLE
make-it-modular 

### ISSUE THREAD

**Issue by Dmancuso1** [nodeschool/discussions#2508]
I can't seem to make the callback work! This is fairly new to me, so any assistance here would be greatly appreciated ! :) 

Error output:

 Your additional module file [mymodule.js] did not return an Array with
 the correct number of elements as the second argument of the callback

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!

My Code:

(mymodule.js')

const fs = require('fs')
const path = require('path')

module.exports = function (folder, ext, callback) {
  fs.readdir(folder, function (err, file) {
    if (err) return callback(err); 
    file.forEach(function (file) {
      if (path.extname(file) === ext) {
        console.log(file)
      }
    })
    callback(null, file)  
  })
}

//---------------------------------

('make-it-modular.js')

const myModule = require('./mymodule.js')

const folder = process.argv[2]
const ext = '.' + process.argv[3]

function callback(err) {
  if (err) return console.error(err);  
}

myModule(folder, ext, callback);

**Comment by danjmaster** [comment]
Hi Dmancuso1,
Your callback is probably being called, but it doesn't output anything.
If there is no error, callback does nothing.
Try calling it from a terminal and pass in values for folder, and ext.
```
node make-it-modular.js C:\folder\that\isnt\real .txt
```
This should throw an error and you can see that your callback is happening.
To view your callback when there is no error.. (also change your callback so it can actually print files that were returned, if any)
```javascript
//in  make-it-modular.js
function callback(err, data){
    if(err) console.error("error from callback: " + err);
    else {
        console.log("callback with no error");
        //do something with data
    }
}
```
Which will allow it to use the data variable when you call it as `callback(null,file)` from mymodule.js
