### ISSUE TITLE
EEXIST error

### ISSUE THREAD

**Issue by ACooper5259** [nodeschool/discussions#2512]
HI I first did javascripting exercises a couple of weeks ago. I tried to continue, but everytime I type javascripting in my terminal it comes back with the error below. Can you help please?

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'
```

**Comment by ACooper5259** [comment]
Hello, it turns out it was an access error, and I was able to resolve it with the recommended sudo method.
Thank you

**Comment by johncabang** [comment]
Hello, I'm having the exact issue. Are you able to show me how you resolved it? Please. Thank you.

**Comment by ACooper5259** [comment]
Hi,
well here is what worked for me. I was trying to download and open the Javascripting on my virtual machine. So it worked once I downloaded it only on my local computer, and I used the command:
"sudo npm install --global javascripting" as recommended for access problems. I should also add that I work on a Mac. Once I had done that, javascripting worked. I hope this helps. Good luck!

**Comment by johncabang** [comment]
Hello,
Thank you for replying. Your instructions are perfect! It works! Thank you again.
