### ISSUE TITLE
javascripting #javascripting #vagrant #Mac

### ISSUE THREAD

**Issue by jesssubin** [nodeschool/discussions#2514]
I am currently following Run the workshop section of the following page: 
https://github.com/workshopper/javascripting#run-the-workshop

First thing to do is to type 'javascripting' as a command. 
Then a blue screen should pop up as describe in the webpage. 
Instead, I get a message saying "EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'"
What should I do to fix this issue? 
Please help 😭😭😭

**Comment by fabiovalho** [comment]
I've got the same problem. Someone could help us, please?

**Comment by johncabang** [comment]
I've got the exact same issue.  I'm not sure what to do next.

**Comment by jesssubin** [comment]
Anybody figured a solution to this problem?

**Comment by johncabang** [comment]
#2512

**Comment by adachuchu12** [comment]
I am having the same issue.  I went into #2512, used the same sudo method to get it running my host machine and it worked fine. However, the issue persists when I tried to run the workshop on my vagrant VM. Can anyone please help? :)

**Comment by etlecoent** [comment]
Hello
Someone found a workaround here : 
[https://stackoverflow.com/questions/63165707/vagrant-node-version-not-updating-in-vm](url)
