### ISSUE TITLE
Array: Como puedo saber la Cantidad de caracteres de un elemento dentro del Array

### ISSUE THREAD

**Issue by wilcasgil** [nodeschool/discussions#2520]
### Notes
Ayudenme por favor con estas dos funciones:
1) La función llamada 'mayorMenor' recibe como argumento un arreglo de números llamado 'numeros' y debe devolver un arreglo que contenga el mayor número del arreglo 'numeros' en la posición cero y el menor número del arreglo 'numeros' en la posición 1.
Ej:
  mayorMenor([9, 17, 6, 2, 4]) debe retornar [17, 2] ya que 17 es el número más grande (mayor) dentro del arreglo [9, 17, 6, 2, 4]
  y 2 es el número más chico (menor) dentro del arreglo [9, 17, 6, 2, 4]

2) Tengo esta fucnio, cantidadCaracteresIgual(['javascript', 'pedro', 'amigo', 'parque'], 5) debe retornar ['pedro', 'amigo']
La funcion recibe como argumento un arreglo de strings llamado 'strings' y un numero entero. Debe devolver en un array los strings que tengan el numero de caracteres coincidentes con el numero entero

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 // copy your error output here
```

### My Code
```js
 // copy your code here
function mayorMenor(numeros) {  
  /*
  var mayor = Math.max(...numeros);
  var menor = Math.min(...numeros);
  */
 
  let mayor = numeros[0];
  let menor = numeros[0];
  
  for (let i = 1; i < numeros.length; i++) {
    
    if (numeros[i] > mayor) {
      mayor = numeros[i];
    }
        
    if (numeros[i] < menor) {
      menor = numeros[i];
    }    
  } 

  numeros[0] = mayor;
  numeros[1] = menor;

  return numeros;

}


function cantidadCaracteresIgual(strings, caracteres) {
  for (let i = 0; i < strings.length; i++) {    
    if (strings[i].value.length === caracteres) {
      return strings;
    }    
  }
}
```

**Comment by Berllliin** [comment]
prueva con Math.max,apply(null,numbers) y de igual forma .min para el menor y .push para agregarlos al nuevo array es mucho mas corto yreturna el nuevo array 3 lineas de codigo
