### ISSUE TITLE
In vagrant while trying to open javascripting I get: EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'

### ISSUE THREAD

**Issue by DSykes28** [nodeschool/discussions#2523]
While in my VM typing javascripting opens the program without a problem.

However, when I'm in Vagrant I instead get the error: **EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'**

Does anyone know the issue? I'm using Ubuntu 20.04.

**Comment by cplpearce** [comment]
If this is lighthouse related - things I've tried:  

- running a sudo apt-get update/upgrade in the vagrant vm, and skipping past the GRUB loader selection.
- removing and reinstalling npm and node.
- installing it locally, not with the global tag; and
- Chmod setting the entire module to 777.   And it didn't work.

I ended up  running it on my local machine, and I'm thinking I'll try it on a basic ubuntu docker container.  As I can tell something in the Lighthouse vagrant vm is causing the issue but I can't be sure.

**Comment by DSykes28** [comment]
> If this is lighthouse related - things I've tried:
> 
>     * running a sudo apt-get update/upgrade in the vagrant vm, and skipping past the GRUB loader selection.
> 
>     * removing and reinstalling npm and node.
> 
>     * installing it locally, not with the global tag; and
> 
>     * Chmod setting the entire module to 777.   And it didn't work.
> 
> 
> I ended up running it on my local machine, and I'm thinking I'll try it on a basic ubuntu docker container. As I can tell something in the Lighthouse vagrant vm is causing the issue but I can't be sure.

Thanks for sharing your experiences. I tried a couple of those as well. I ended up doing it locally as well, but I was able to move the exercise files to the Vagrant VM, so I could share them with Lighthouse there.

**Comment by SociaJL** [comment]
Lighthouse related. same EEXIST on both the Vagrant VM and my local machine. Any other suggestions other than what's listed here?

**Comment by cplpearce** [comment]
Out of curiosity, did you install Javascripting with the global keyword?  Try doing an install on a folder in your home directory and chmod the folder to 777 - if that doesn't work try removing the package with `npm uninstall <package-name>` and reinstall the package.

If that doesn't work maybe download [ubuntu minima](https://help.ubuntu.com/community/Installation/MinimalCD)l and create a VM and try it there?  That way you'll have a totally clean install and we can work on a neutral platform :)

**Comment by achille66** [comment]
macos catalina, virtualbox, vagrant...

While in my VM typing javascripting opens the program without a problem.

However, when I'm in Vagrant I instead get the error: EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'

**Comment by Andriy-Lyt** [comment]
same problem

**Comment by Housam-j** [comment]
same problem

**Comment by mohammed-alialhassan** [comment]
Was anyone able to resolve it? Having the same issue

**Comment by ugurnur** [comment]
I got the same problem, I will install locally, I downsized my version of node with vagrant version of node. I will run them and keep the files inside vagrant javascripting folder. I tried so many things but nothing is working.

**Comment by Diogenesoftoronto** [comment]
I installed it locally in the same folder. It worked like a charm.
