### ISSUE TITLE
for-loop.js is validating wrong number for solution.

### ISSUE THREAD

**Issue by Aztek1337** [nodeschool/discussions#2525]
Hey Team,

looks like the exersize for-loop is validating incorrectly. The solution should be 10, but when you verify, it's checking for 45. I had to make the var 45 to pass it, 

Just an FYI

### Error output
```
 ↳ javascripting verify for-loop.js                                                                      ✔  21:30:55

# JAVASCRIPTING

## FOR LOOP (Exercise 10 of 20)

─────────────────────────────────────────────────────────────────────────────

# O-oh, something isn't working.

# But don't panic!

─────────────────────────────────────────────────────────────────────────────

## Check your solution:

 Solution ===================

 45

 Your Attempt ===================

 10

 Difference ===================

 4510

```

### My Code
```js
let total = 0
const limit  = 45

for (let i = 0; i < limit; i++)
{
total += 1
}

console.log(total)
```

**Comment by hackdefendr** [comment]
I see two issues with your code.  
Your variable `limit` should be `10`.  
The other is what you are doing to `total`.

**Comment by MiSteven** [comment]
Nevertheless, the solution shouldn't be 45, as mentioned.

Should be (print) the numbers from 0 to 9.

**Comment by aztecalex** [comment]
hi, i have the same issue but my code is this:
`let total = 0
let limit = 10

for (total; total < limit; total++){
	console.log(total)
}`
error output
`## Check your solution:

 Solution ===================

 45

 Your Attempt ===================

 0 1 2 3 4 5 6 7 8 9

 Difference ===================

 0 1 2 3 4 5 6 7 8 9 
`

**Comment by Paskineitor** [comment]
var total = 0;
var limit = 10;
for (var i = 0; i < limit; i++){
    total+=i
}
console.log(total)

// this is the correct code

**Comment by Paskineitor** [comment]
// or

let total = 0
    const limit = 10
    
    for (let i = 0; i < limit; i++) {
      total += i
    }
    
    console.log(total)
