### ISSUE TITLE
javascripting 'if statement'

### ISSUE THREAD

**Issue by Paskineitor** [nodeschool/discussions#2536]
can you say to me how resolve this exercise?

**Comment by yinsang** [comment]
```
// define variable
var fruit = 'orange'
// if statement
if(fruit.length <= 5){
  console.log("The fruit name has five characters or less.");
}else{
  console.log("The fruit name has more than five characters.");
}
```

**Comment by Sabatino1977** [comment]
var fruit = 'orange'

if(fruit.length >5){
 console.log("The fruit name has five characters or less.");
}else{
 console.log("The fruit name has more than five characters.");
}
why is wrong ?

**Comment by yinsang** [comment]
console.log("The fruit name has five characters or less."); is less than 5
