### ISSUE TITLE
javascripting in vagrant throws file already exists error

### ISSUE THREAD

**Issue by rahulshial** [nodeschool/discussions#2538]
Issue: javascripting throws error EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'. Unable to run javascripting after the initial run. Also not able to verity any code that is being written.

### If you have a problem with an error message:

* node version: 8.9.4
* npm version:  6.14.8
* os: linux - Ubuntu 20.04.01

### Error output
```
EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper'

```

### My Code
javascripting
javascripting -verify
```

**Comment by Stephan-Pauld** [comment]
I am also having this issue
" EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper' "

**Comment by shepherdlewis000** [comment]
Same here trying to first run learnyounode after having it installed a while back. So upgrade/install-over.

I've tried renaming the .config/workshopper directory. It allows learnyounode to run once, but on next run same EEXIST error. 
I then logged in as another user. Ran just fine but have to be conscious of file permissions now.

**Comment by NColusso** [comment]
Found a fix that worked for me - it was based on what node version was on my computer vs which one was in vagrant. check which one you installed on your computer you can compare and see which one is in the VM with input -  "nvm ls" . For me it was 8.9.4 where my computer had 12.19.0. You can update the version you had by inputting  "nvm install 12.19.0" (or whichever program your computer has) then reinstall and run javascripting. Worked for me

**Comment by Polarnik-ryaz** [comment]
> Found a fix that worked for me - it was based on what node version was on my computer vs which one was in vagrant. check which one you installed on your computer you can compare and see which one is in the VM with input - "nvm ls" . For me it was 8.9.4 where my computer had 12.19.0. You can update the version you had by inputting "nvm install 12.19.0" (or whichever program your computer has) then reinstall and run javascripting. Worked for me

I confirm this solution worked for me too!

**Comment by arms1997** [comment]
> Found a fix that worked for me - it was based on what node version was on my computer vs which one was in vagrant. check which one you installed on your computer you can compare and see which one is in the VM with input - "nvm ls" . For me it was 8.9.4 where my computer had 12.19.0. You can update the version you had by inputting "nvm install 12.19.0" (or whichever program your computer has) then reinstall and run javascripting. Worked for me

WORKED FOR ME TOO :)

**Comment by Colerk** [comment]
Fixed it for me as well.

**Comment by matymcleod** [comment]
Hi sorry noob here. i'm getting " EEXIST: file already exists, mkdir '/home/vagrant/.config/workshopper' " as well when i try to run 'javascripting'. 

Above, Does this mean your are updating the version of node on your VM to 12.19.0?
I am a mac user and downloaded node.js 15.12.0 on my actual mac and when I 'nvm ls' on the VM it comes back with:
->       v8.9.4
default -> v8.9.4
node -> stable (-> v8.9.4) (default)
stable -> 8.9 (-> v8.9.4)
iojs -> N/A

Not sure how to get them to line up properly.  I'm not the best debugger of things quite yet.

**Comment by anacko** [comment]
> Found a fix that worked for me - it was based on what node version was on my computer vs which one was in vagrant. check which one you installed on your computer you can compare and see which one is in the VM with input - "nvm ls" . For me it was 8.9.4 where my computer had 12.19.0. You can update the version you had by inputting "nvm install 12.19.0" (or whichever program your computer has) then reinstall and run javascripting. Worked for me

I could not make it work with version 12, but with the 14: "nvm install 14.17.5".
This problem seems to happen because the original version is not active anymore.(Aug/2021)

Source 1: Documentation for the [EEXIT error](https://github.com/workshopper/javascripting/blob/master/TROUBLESHOOTING.md)
Source 2: Node [Releases](https://nodejs.org/en/about/releases/), where the v14 link at this page leads to the [14.17.5](https://nodejs.org/download/release/latest-v14.x/) version.

EDIT: Just to add, for a next time running the workshop: "nvm use 14.17.5"

**Comment by lateefazeez** [comment]
> > Found a fix that worked for me - it was based on what node version was on my computer vs which one was in vagrant. check which one you installed on your computer you can compare and see which one is in the VM with input - "nvm ls" . For me it was 8.9.4 where my computer had 12.19.0. You can update the version you had by inputting "nvm install 12.19.0" (or whichever program your computer has) then reinstall and run javascripting. Worked for me
> 
> I could not make it work with version 12, but with the 14: "nvm install 14.17.5".
> This problem seems to happen because the original version is not active anymore.(Aug/2021)
> 
> Source 1: Documentation for the [EEXIT error](https://github.com/workshopper/javascripting/blob/master/TROUBLESHOOTING.md)
> Source 2: Node [Releases](https://nodejs.org/en/about/releases/), where the v14 link at this page leads to the [14.17.5](https://nodejs.org/download/release/latest-v14.x/) version.
> 
> EDIT: Just to add, for a next time running the workshop: "nvm use 14.17.5"

Worked for me. Thanks so much for this

**Comment by mohammed-alialhassan** [comment]
Hi! So after using nvm 14.17.5 what should I do next? Sorry I'm brand new to all this

**Comment by anacko** [comment]
> Hi! So after using nvm 14.17.5 what should I do next? Sorry I'm brand new to all this

After the `nvm install 14.17.5` or the `nvm use 14.17.5`, the `javascripting` command should make the tutorial run as intended.

**Comment by mohammed-alialhassan** [comment]
When I did that, I received -bash: javascripting: command not found

**Comment by anacko** [comment]
> When I did that, I received -bash: javascripting: command not found
Did you install the javascripting globally? That could be it... (`npm install -g javascripting`)

**Comment by mohammed-alialhassan** [comment]
I did

**Comment by anacko** [comment]
Maybe it could be some problem related to the path. In case it is Linux, suggest checking [here](https://linuxhint.com/bash_command_not_found/), hope that helps.

**Comment by mohammed-alialhassan** [comment]
I was able to get it resolved by completely removing and reinstalling node again

**Comment by canadiankay** [comment]
> > Hi! So after using nvm 14.17.5 what should I do next? Sorry I'm brand new to all this
> 
> After the `nvm install 14.17.5` or the `nvm use 14.17.5`, the `javascripting` command should make the tutorial run as intended.

This helped me thanks so much!
