### ISSUE TITLE
Noob friendly website design

### ISSUE THREAD

**Issue by mikeal** [nodeschool/discussions#254]
This really pains me.

I love the website, it makes me happy. But, as more and more newbie's are finding it the design is a little inaccessible for them. I've been pointing a lot of people from academia at it lately as well and they seem pretty put off by it.

No matter what, *I* should not be allowed to design such a site (I write the worst front-end code ever), but I'm hoping someone else can step up. I'd like to grow more events at universities and high schools and a site design a little closer to @jlord's recent logo would help a lot.

**Comment by martinheidegger** [comment]
@mikeal This issue is not relevant anymore, right?
