### ISSUE TITLE
Baby Steps - Node works, verify fails

### ISSUE THREAD

**Issue by JasonTheAdams** [nodeschool/discussions#26]
Here's my code:

```
var sum = 0;

for (index = 2; index < process.argv.length; index++) {
    sum += Number(process.argv[index]);
}

console.log(sum);
```

Here's a node test:

```
node baby-steps.js 1 2 3
6
```

Here's the verify:

```
learnyounode verify baby-steps.js
Verifying "BABY STEPS"...
 
ACTUAL                             EXPECTED
------                             --------
""                              != "130"                          
null                            != ""                             
# FAIL
 
Your solution to BABY STEPS didn't match the expected output.
Try again!
```

Am I missing something? :(

**Comment by beastmike** [comment]
> var sum = 0;
> 
> for (index = 2; index < process.argv.length; index++) {
>     sum += Number(process.argv[index]);
> }
> 
> console.log(sum);

**Comment by beastmike** [comment]
learnyounode verify baby-steps.js 1 2 3

**Comment by jkbits1** [comment]
@beastmike Just a couple of thoughts about your code. `index` in the for loop is a variable so it needs a `var` before it, just like `sum`. Also, the verify and run methods provide your code with arguments, so `1 2 3` is not needed.

Hope you are enjoying the tutorial :smile:

**Comment by egoodnoe** [comment]
Why does this fail?

var array = process.argv[2],
	arrayLen = array.split(','),
	sum = 0,
	x;
for (x=0;x<arrayLen.length;x++){
	sum += Number(arrayLen[x]);
}
console.log(sum);

**Comment by noffle** [comment]
@egoodnoe: how are you expecting the numbers to be formatted? Consider this line from the **HINTS** section of the exercise:

```
  Run it with node program.js and some numbers as arguments. e.g:  
   
     $ node program.js 1 2 3
```

**Comment by theednaffattack** [comment]
Hi I can't get this to verify but I'd like to move on in my learning.  Is this valid?
console.log(process.argv);
var newNum = 0;

for (var i = 2; i < process.argv.length; i++) {
	newNum = Number(newNum) + process.argv[i];
}
console.log(newNum);

**Comment by milesibastos** [comment]
The first `console.log(process.argv)` is only for sample aproach!
Remove that and every thing is gonna be ok!
