### ISSUE TITLE
How can I setup multiple levels of options from the Menus

### ISSUE THREAD

**Issue by dinooz** [nodeschool/discussions#268]
I like to create a CLI that can choose and configure multiple nested options.

Section I
   Option a
   Option b
   Option c

Section II
   Option d
   Option e
   Option f

Section III
  Option g
  Option h
  Option i

This way at the end when user select the nested options will be able to record the settings almost like a bios and save the config to a text file.

THX Dino.

**Comment by martinheidegger** [comment]
@dinooz Did you find a way?
