### ISSUE TITLE
ECONNREFUSED in fetch json lesson

### ISSUE THREAD

**Issue by victorbetran** [nodeschool/discussions#273]
Hi there,

I'm getting an error when trying to run/verify my code in the fetch_json lesson for the course promise-it-wont-hurt. I added a console.log for the response to see this error:

```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```
Here is my code:
```
var http = require("q-io/http");

http.read("http://localhost:1337").then(function(json) {
    console.log(JSON.parse(json));
}).then(null, console.log);
```
I know that you don't have to print the response, but I made that to see the problem.

Anyone had this problem too?

Thanks,
Viko

**Comment by Sequoia** [comment]
Hi @victorbetran! Are you sure you have a server running on that port?

Does this work in your shell: `curl localhost:1337`? Alternately punch `http://localhost:1337` into your browser & see what comes back.

Let us know how that works & good luck!

**Comment by victorbetran** [comment]
Hi @Sequoia,

I tried reproduce this problem now but I couldn't do it, it was a long time ago and I don't have the same enviroment than at that time, but I guess it should has been something wrong with that.

Thanks!
Viko
