### ISSUE TITLE
learnyounode module 1.5, filtered ls, needs callback err handling

### ISSUE THREAD

**Issue by faddah** [nodeschool/discussions#276]
hi,

regarding the 'learnyounode' module 1.5, filtered ls, your proposed 'official solution' is -

```
var fs = require('fs')
var path = require('path')
    
fs.readdir(process.argv[2], function (err, list) {
   list.forEach(function (file) {
     if (path.extname(file) === '.' + process.argv[3])
       console.log(file)
   })
})
```

^^^^ however, in this 'official solution' above, you fail to handle the 'err' in the callback function, like so -

```
...
if (err) {
  throw err;
}
...
```

i recommend adding this to the 'official solution' code to this 1.5, filtered ls module.

best,

—  faddah wolf
     portland, oregon

**Comment by martinheidegger** [comment]
@faddah Yes! PRs are always welcome. Particularly since I opened an issue now at learnyounode: https://github.com/rvagg/learnyounode/issues/180
