### ISSUE TITLE
git-it  -  issue  with  Branches  aren't just for birds

### ISSUE THREAD

**Issue by bsussman** [nodeschool/discussions#278]
Um - my github repository shows that I indeed do   have a branch with the proper name.  What am I missing?

Error output from verify:
ACTUAL                             EXPECTED

---

"branch name was not:"          != "Found the branch as expected!"
"'add-bsussman'"                != "Changes have been pushed!"  
"Changes not pushed"            != ""  
""                                            != null  
FAIL

**Comment by benjaminsuch** [comment]
Hello, sorry to reopen this issue but I have this problem too.

`git reflog show origin/add-benjaminsuch`
returns:
```
fatal: ambiguous argument 'origin/add-benjaminsuch': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

But when I change the name to "origin/benjaminsuch" it says `81d90f4 refs/remotes/origin/benjaminsuch@{0}: update by push`

I definately followed the instructions step by step. But maybe I should mention: After I forked the repo and created a new branch, `git status` says there is a modified file "contributors/add-AaronCallahan.txt". But this shouldn't make the verification fail I guess?
