### ISSUE TITLE
my first async i/o

### ISSUE THREAD

**Issue by bennage** [nodeschool/discussions#28]
My solution is 

``` js
var fs = require('fs');
var path = process.argv[2];

fs.readFile(path, 'utf8', function(err,data) {
  var lines = data.split('\n');
  console.log(lines.length-1);
});
```

However, the `verify` reports that actual is merely "".
When I run it though, I do see numeric output. Using 0.2.13. 
Am I making a dumb mistake?

**Comment by chiadt** [comment]
var fs = require('fs')
    var file = process.argv[2]
    
    fs.readFile(file, function (err, contents) {
      // fs.readFile(file, 'utf8', callback) can also be used
      var lines = contents.toString().split('\n').length - 1
      console.log(lines)
    })
