### ISSUE TITLE
git-it advises forcing branch delete in last problem

### ISSUE THREAD

**Issue by bsussman** [nodeschool/discussions#280]
capital D forces delete even if the conditions (for instance, changes not fully merged) might not be right to delete a branch.  Using l/c d ( git branch -d ...) produces message if  such conditions exist.

Why is lesson written to use 
```
git branch -D <BRANCHNAME>
```
instead of
```
git branch -d <BRANCHNAME>
```

**Comment by jlord** [comment]
:+1: Will change it to `-d`

**Comment by Sequoia** [comment]
pr in https://github.com/jlord/git-it/pull/145
