### ISSUE TITLE
CD Desktop command not taking me to the desktop directory

### ISSUE THREAD

**Issue by diptarupm** [nodeschool/discussions#281]
In node command prompt ,I am trying to type in CD Desktop/start/,where start is the folder that is residing on my desktop having some .js files in it.
Later on when I am tying in 'ls' in the command line,its not showing me the files in it.Could you please let me know what might be the issue?

**Comment by ghost** [comment]
Hello sir for me cd desktop command not working and showing the system cannot find the path specified please help me.
