### ISSUE TITLE
I'm stuck on Duplexer Redux of stream-adventure

### ISSUE THREAD

**Issue by stefanocoding** [nodeschool/discussions#283]
Hi,
I don't understand what I have to do in the lesson "Duplexer Redux".
I get confused in the line "call `counter.setCounts()` with your country counts", because `counter` is a Stream.
I tried to figure out it by myself but the error I get is:

```
net.js:612
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at ReadStream.Socket.write (net.js:612:11)
    at Stream.method [as write] (/Users/user/Downloads/node/node_modules/duplexer/index.js:47:39)
    at null.<anonymous> (/usr/local/lib/node_modules/stream-adventure/problems/duplexer_redux/setup.js:37:25)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

so I can't understand where is the problem.

Thank you for the lessons. I'm learning Node this way.

**Comment by nelson777** [comment]
I'm having trouble with this one. I've succefully created the object with the correct country count. But when I set the counter object with it I get the "write after end" error. I'm doing it this way:

    duplex.on("end", function() {
        counter.setCounts(countries);
    });

what's the problem with this code ? haven't the stream ended ?

**Comment by MarcosRZ** [comment]
Same problem for me. I am using a though2.obj stream (See https://github.com/rvagg/through2). According to my tests, the *on.( "end", function {...} )* event is not being called. Every help would be apreciated.

**Comment by MarcosRZ** [comment]
Same problem for me. I am using a though2.obj stream (See https://github.com/rvagg/through2). According to my tests, the *on.( "end", function {...} )* event is not being called. Every help would be apreciated.

EDIT: I found the problem for me! Just removed the stream push line from the write function and it worked!

```javascript
function write (chunk, encoding, next) {
doThingsWithChunk();
// this.push(chunk);
next();
}
```
