### ISSUE TITLE
Stream-adventure: concat works randomly.

### ISSUE THREAD

**Issue by mikeubell** [nodeschool/discussions#288]
My solution:
var concat = require('concat-stream');
process.stdin.pipe(concat(function (buf) {
                process.stdout.write(buf.toString().split('').reverse().join(''));
        }));

Seems to work randomly.  Here are 3 runs in a row with no changes to the program file:
MacBook-Pro-2:foo ubell$ stream-adventure verify program.js 
ACTUAL                             EXPECTED
------                             --------
"Every toaster oven in the"        "Every toaster oven in the"   
"village heard the radiometric"     "village heard the radiometric"
"clamor from the town square."     "clamor from the town square."
"Looking unparadoxically into"     "Looking unparadoxically into"
"the distance, Constable"          "the distance, Constable"     
"Franklin twiddled his"            "Franklin twiddled his"       
"piercing periscope to locate"     "piercing periscope to locate"
"the apt source. Unwittingly,"     "the apt source. Unwittingly,"
"a nearby conifer verily"          "a nearby conifer verily"     
"emitted high-velocity"            "emitted high-velocity"       
"confusing particles."             "confusing particles."        
""                                 ""                            
null                           !== ""                            
# FAIL

Your solution didn't match the expected output.
Try again, or run `stream-adventure run program.js` to see your solution's output.
MacBook-Pro-2:foo ubell$ stream-adventure verify program.js 
ACTUAL                             EXPECTED
------                             --------
"Every conifer in the village"     "Every conifer in the village"
"heard the apt clamor from the"     "heard the apt clamor from the"
"town square. Looking"             "town square. Looking"        
"unparadoxically into the"         "unparadoxically into the"    
"distance, Constable Franklin"     "distance, Constable Franklin"
"twiddled his untrustworthy"       "twiddled his untrustworthy"  
"periscope to locate the"          "periscope to locate the"     
"digital source. Unwittingly,"     "digital source. Unwittingly,"
"a nearby x-ray yawnily"           "a nearby x-ray yawnily"      
"flipped high-velocity"            "flipped high-velocity"       
"unhelpful particles."             "unhelpful particles."        
""                                 ""                            
# PASS

Your solution to CONCAT passed!

Here's what the official solution is if you want to compare notes:

    var concat = require('concat-stream');
    
    process.stdin.pipe(concat(function (src) {
        var s = src.toString().split('').reverse().join('');
        console.log(s);
    }));
    
You have 9 challenges left.
Type `stream-adventure` to show the menu.

MacBook-Pro-2:foo ubell$ stream-adventure verify program.js 
ACTUAL                             EXPECTED
------                             --------
"Every pebble in the village"      "Every pebble in the village" 
"heard the ionizing clamor"        "heard the ionizing clamor"   
"from the town square. Looking"     "from the town square. Looking"
"yawnily into the distance,"       "yawnily into the distance,"  
"Constable Franklin steered"       "Constable Franklin steered"  
"his unhelpful periscope to"       "his unhelpful periscope to"  
"locate the radiometric"           "locate the radiometric"      
"source. Unwittingly, a nearby"     "source. Unwittingly, a nearby"
"toaster oven zestily twiddled"     "toaster oven zestily twiddled"
"high-velocity confusing"          "high-velocity confusing"     
"particles."                       "particles."                  
""                                 ""                            
null                           !== ""                            
# FAIL

Your solution didn't match the expected output.
Try again, or run `stream-adventure run program.js` to see your solution's output.
MacBook-Pro-2:foo ubell$

**Comment by Sequoia** [comment]
This *should* be fixed: https://github.com/rvagg/workshopper-exercise/blob/master/comparestdout.js#L65-L66

Lemme know if you can still reproduce.
