### ISSUE TITLE
Stream-adventure: Websockets passes without really working.

### ISSUE THREAD

**Issue by mikeubell** [nodeschool/discussions#289]
Verifying the official solution code I just get the output below without ever starting the browser.  If I "run" the code it hangs, I can start a browser on localhost:8000 and get a blank page.  If I change "hello\n" to any other string it still passes.

stream-adventure verify program.js
################################################
#                                              #
# Open http://localhost:8000 to run your code! #
#                                              #
################################################

ACTUAL                             EXPECTED
------                             --------
""                                 ""                            
# PASS
Your solution to WEBSOCKETS passed!

**Comment by substack** [comment]
fixed in 4.0.0
