### ISSUE TITLE
London Nodeschool's dream...

### ISSUE THREAD

**Issue by orliesaurus** [nodeschool/discussions#292]
We all agree nodeschool is amazeballs, so we've been running nodeschool with the help of a few sponsors and mentors in London. Very good feedback, people from the crowd wanted to donate money to make it better etc etc.
We've also sent out a newsletter, so I was wondering if there was any chance we could make the London experience a **liiiiittle** bit better by having an official email address ?

When we send out our pre-nodeschool newsletter it would be nice to see it coming from a nodeschool domain rather than a random gmail address, what do you think?

I'd really like to hear your feedback on this, there might be pros and cons 
i.e.
* SPF/DKIM authentication on the DNS might be a pain in the ass to set up?
...

**Comment by Sequoia** [comment]
contacted a couple email providers to find out if they have offerings for FOS projects.

**Comment by iancrowther** [comment]
@Sequoia whats FOS?

**Comment by iancrowther** [comment]
@orliesaurus http://frontapp.com

**Comment by martinheidegger** [comment]
@iancrowther I assume @Sequoia means [FOSS](http://en.wikipedia.org/wiki/Free_and_open-source_software)

By the way: Isn't this an issue for https://github.com/nodeschool/newsletter

**Comment by iancrowther** [comment]
ah.. i see..

**Comment by iancrowther** [comment]
yes, this conv should move over to the newsletter repo.. not too sure how tho!

**Comment by martinheidegger** [comment]
I would close this issue reopen the issue over there with a link to this issue and an excerpt of the current state of the discussion.

**Comment by martinheidegger** [comment]
Ah! you are not an owner! let me change that :smile:

**Comment by iancrowther** [comment]
will do..
