### ISSUE TITLE
International NodeSchool Day

### ISSUE THREAD

**Issue by rvagg** [nodeschool/discussions#296]
Moving this discussion out of #294, that's too soon.

For the sake of simply starting something rolling I'm putting up two dates to choose from for an Inernational NodeSchool day, where we encourage organisers around the globe to set up events on the same day. The collective marketing efforts should make it much easier to bring new people in than the normal isolated events.

* **23rd of August 2014**; *or*
* **11th of October 2014** 

September has a couple of major conferences in it, I don't know of anything in August or October although I'm sure there are things.

There's going to be a bunch more content in NodeSchool by July so either way there's going to be plenty of options for event organisers!

Any objections to either of those dates? Is anyone aware of major conflicts?

/cc @olizilla

**Comment by martinheidegger** [comment]
11th has come and gone. New year new luck, new issue?

**Comment by iancrowther** [comment]
@olizilla @alanshaw thoughts?

**Comment by iancrowther** [comment]
@olizilla @rvagg @maxogden

I have had a chat with @alanshaw and we have agreed to take ownership on this.

We will set up a microsite for the day and manage chapter enrollment.

I'm proposing we go for Sat 2nd May to give us time to prep.

We discussed having a global object that passes from event to event (something like a roll call) so that there is a list of participants on the site at the end.

We also discussed a global map showing workshopper completions via a "high Five" module.

Anyhow.. leave it with us

**Comment by a0viedo** [comment]
so the oficial date 11th of October?

**Comment by iancrowther** [comment]
@a0viedo - "I'm proposing we go for Sat 2nd May to give us time to prep."

My understanding is that this never happened, so there is no official date as such

**Comment by iancrowther** [comment]
Ironically @alanshaw will be out of the country during this "international" event ;-p

so... Sat 9th May

**Comment by rvagg** [comment]
Never happened so the first one to set a date and make it happen wins! Good work.

**Comment by iancrowther** [comment]
Yep, figured this just needed some ownership.. done

**Comment by martinheidegger** [comment]
Looking forward for May 9th (or whatever day you announce)

**Comment by martinheidegger** [comment]
(Sorry, hit the wrong button ...)

**Comment by martinheidegger** [comment]
Now that https://github.com/nodeschool/international-day exists I close this. *cheers*!

**Comment by iancrowther** [comment]
+1
