### ISSUE TITLE
EACCES Error on install: run again as root/Administrator

### ISSUE THREAD

**Issue by meetmagdalene** [nodeschool/discussions#305]
I get this error when trying to install. I don't have the permissions?

"npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/learnyounode',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/learnyounode',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "learnyounode"
npm ERR! cwd /Users/maggie.benson
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /usr/local/lib/node_modules/learnyounode
npm ERR! fstream_path /usr/local/lib/node_modules/learnyounode
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/maggie.benson/npm-debug.log
npm ERR! not ok code 0"

**Comment by idhamperdameian** [comment]
This work for me:
`sudo chown -R $(whoami) ~/.npm`
`sudo chown -R $(whoami) /usr/local/lib/node_modules`

**Comment by zhe** [comment]
Thanks @idhamperdameian !

**Comment by andrefjpinto** [comment]
thanks @bneiluj and @idhamperdameian ;)

**Comment by bneiluj** [comment]
You are welcome @andrefjpinto

**Comment by fahmyfarahat** [comment]
Thanks @bneiluj  
This work for me:
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules

**Comment by igravity** [comment]
I just deleted the entire ~/.npm directory altogether using `rm -rf ~/.npm`, ran the install again and **it works!!!**

**Comment by RyanZhu1024** [comment]
These work like a charm. Thanks!!
`sudo chown -R $(whoami) ~/.npm`
`sudo chown -R $(whoami) /usr/local/lib/node_modules`

**Comment by milliezhou** [comment]
THANK YOU @bneiluj !! Same here, this worked wonders for me:

`sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules`

**Comment by Vishal403** [comment]
THANK YOU @bneiluj !! 
This worked wonders for me:

sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules

**Comment by maciao** [comment]
@idhamperdameian thanks it works!

**Comment by erturkedip** [comment]
Thank you @bneiluj and @idhamperdameian 
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules

it worked!

**Comment by vaibhavadm** [comment]
Thanks @bneiluj, your solution perfectly worked on mac 
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules

**Comment by gzavala-truelogic** [comment]
@bneiluj Well done sir!

**Comment by minhchuduc** [comment]
Thanks @bneiluj, your solution work for me (ubuntu 16.04). But could someone explain for me why `npm install -g ...` can install to "/usr/local/bin/" without root permission? I curious about the mechanism npm used. Thank a lot!

**Comment by noffle** [comment]
@minhchuduc It's only able to because `chown username -R` grants ownership of those directories to your local user.

**Comment by minhchuduc** [comment]
@noffle no, i checked owner of /usr/local/bin, still root.

**Comment by grettygoose** [comment]
Thanks @bneiluj, your solution worked for me!
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules

**Comment by jonatawilliam** [comment]
Thanks at @bneiluj this solved a problem which

**Comment by TC-rGangal** [comment]
thanks @bneiluj

**Comment by ihsanalgul** [comment]
writing sudo begin of the statement worked for me...thanks everyone
