### ISSUE TITLE
Every Some

### ISSUE THREAD

**Issue by Exegetech** [nodeschool/discussions#308]
Hi, 

I don't understand the challenge of Every Some.  The challenge says that we have to use both every and some method for this to work.

Below is my code so far

```
function checkUsersValid(goodUsers) {
    return function(submittedUsers) {
        if (submittedUsers.every(function(element) {
        }))
    }
}

module.exports = checkUsersValid;
```

Anybody can help or give hints?

**Comment by wordyallen** [comment]
@eddieajau stated:  " use some to check if 'a' user id is in the good users array"

What is 'a' referring to?
