### ISSUE TITLE
Learnyounode - Http Collect

### ISSUE THREAD

**Issue by christiansakai** [nodeschool/discussions#311]
Hi,

Is there anyone can tell me the difference between the exercise http client and http collect
Http Client
```
var http = require('http')

http.get(process.argv[2], function (response) {
  response.setEncoding('utf8')
  response.on('data', console.log)
  response.on('error', console.error)
})
```

Http Collect
```
var http = require('http');
var url = process.argv[2];
var bl = require('bl');


http.get(url, function(response) {
	response.pipe(bl(function(err, data) {
		if (err) throw err;
		console.log(data.toString().length);
		console.log(data.toString());
	}))
})
```

My question probably are:
1. What is the difference between the response object in http client and collect?
2. Also in light of question one, why can't we use response.setEncoding('utf8') in http collect?
3. What exactly is response.pipe doing? What does it do?
4. What exactly is bl do?

Sorry, I've been trying to read the documentation, but still don't understand.

I got pass http collect by pure luck.

**Comment by martinheidegger** [comment]
@christiansakai Just asking back: Did you have an eureka moment inbetween?

**Comment by hello2parth** [comment]
I am new a learner to node.js and following is passing the test, I am also not getting why to use bl module.

```
const http =  require('http');

http.get(process.argv[2], 'utf-8', (response) => {
  let rawData = '';
  response.on('data',(data) => {rawData += data;});
  response.on('end',() => {
    console.log(rawData.toString().length);
    console.log(rawData.toString());
  });
  response.on('error',(e) => {console.error(e)});
}).on('error',console.error);
```
