### ISSUE TITLE
Learnyounode - Juggling Async

### ISSUE THREAD

**Issue by christiansakai** [nodeschool/discussions#312]
Hello,
I can't make the code below works.  The resultArray is still blank no matter what.
```
var http = require('http');
var bl = require('bl');
var resultArray = []
function httpGet(index) {
	http.get(process.argv[2 + index], function(response) {
		response.pipe(bl(function(err, data) {
			if (err) {
				console.error(err);
			}
			resultArray[index] = data.toString();
		}));
	});
}

httpGet(0);
httpGet(1);
httpGet(2);
console.log(resultArray);
```

Anybody know why?

**Comment by martinheidegger** [comment]
@einarc  After the http requests are sent out (I/O), the single thread is able to process any other request because no other code in this file will be executed until the `callback` is will be called after data is received.

Does that answer your question?
