### ISSUE TITLE
NodeSchool Germany

### ISSUE THREAD

**Issue by balupton** [nodeschool/discussions#318]
[NodeSchool for Germany Wiki Page](https://github.com/nodeschool/discussions/wiki/NodeSchool-Germany)

Use the discussion below to organise and coordinate your own NodeSchool events in Germany.

[Possible Germany people to cc](https://github.com/search?q=location%3Agermany+language%3Anode.js+language%3Ajavascript&type=Users&ref=searchresults), _if you know one of them, and know they would appreciate it_, politely request their assistance by cc'ing them in this thread.

**Comment by martinheidegger** [comment]
@balupton @finnp Is this issue still relevant?
