### ISSUE TITLE
Ti.to invites

### ISSUE THREAD

**Issue by balupton** [nodeschool/discussions#319]
Post your email here to get an invite to create your ti.to events under the NodeSchool org.

**Comment by a0viedo** [comment]
alejandro.oviedo.g@gmail.com

**Comment by martinheidegger** [comment]
This should be in a markdown file or the wiki ...

**Comment by Fauntleroy** [comment]
the.kaempfer@gmail.com

**Comment by edwinallenz** [comment]
Please invite me to tito 
edwin.allen@gmail.com

**Comment by carlodicelico** [comment]
carlo@nodeschoolpwm.org

**Comment by meaku** [comment]
michael.jaser@peerigon.com

**Comment by adobley** [comment]
aidan@obley.net

**Comment by joshterrill** [comment]
joshterrill.dev@gmail.com

**Comment by robbennet** [comment]
rwbennet@gmail.com

**Comment by thorsteinsson** [comment]
aegir@thorsteinsson.is

**Comment by levint** [comment]
levin.tacandong@gmail.com

**Comment by tmlaughlinjr** [comment]
tmlaughlinjr@gmail.com

**Comment by Yesica-Villamil** [comment]
yesicavillamil@gmail.com

**Comment by ldbraun** [comment]
ldbraun@live.com

**Comment by joshterrill** [comment]
I still haven't gotten an invite, could you please send one to joshterrill.dev@gmail.com

**Comment by itopa** [comment]
itopa@live.ca

**Comment by mparigi** [comment]
mparigi99@gmail.com

**Comment by diarmaidm** [comment]
foylenodeschool@gmail.com (for http://nodeschool.io/foyle-valley/)

**Comment by quindai** [comment]
randy.quindai@gmail.com

**Comment by suchov** [comment]
artem.suchov@gmail.com

**Comment by ProfNandaa** [comment]
prof@nandaa.com

**Comment by inidaname** [comment]
saniyhassan@gmail.com

**Comment by tekindermisel** [comment]
misel.tekinder@gmail.com

**Comment by quibusus** [comment]
karol@oaks-lab.com

**Comment by attaradev** [comment]
mpyebattara@gmail.com

**Comment by ldbraun** [comment]
ldbraun@live.com
