### ISSUE TITLE
Creating an Event Discussion

### ISSUE THREAD

**Issue by balupton** [nodeschool/discussions#320]
[Guide here](https://github.com/nodeschool/discussions/wiki/Creating-an-Event)

Discussion below.

**Comment by martinheidegger** [comment]
Seems a little outdated, maybe better to delete the wiki page since it does contain misleading information?

**Comment by balupton** [comment]
Then update it?

**Comment by martinheidegger** [comment]
@balupton Thats why I added the "needs-some-love" label. I am trying to clean up the issues and this was an open one.

**Comment by Sequoia** [comment]
Reopen if there's a specific/actionable issue.
