### ISSUE TITLE
Wiki vs. Readme vs. Website vs. Issues

### ISSUE THREAD

**Issue by mikeal** [nodeschool/discussions#322]
Hey, I just noticed that we're now adding some pretty useful information to the project wiki.

I'm worried about these resources being discoverable enough, they aren't link to from the website or the README.

We should have a quick discussion about the best place to put stuff. Here's my suggestion:

* Focus the website on *users*. Point them at all the resource they need to complete a NodeSchool, get support from issues in this repo, and *attend* local events.
* Focus the wiki on resources for helping people run in-person NodeSchools and author new courses.
* Link to the wiki resources for authoring and creating events in the relevant website pages.

BTW, isn't someone building a new website? It looked almost done last time i saw something about it.

**Comment by martinheidegger** [comment]
We have a new website *yeah* The separation between wiki, issues and website could still use some love imho.

**Comment by martinheidegger** [comment]
Moved issue to https://github.com/nodeschool/discussions/issues/891 Seems that a task would be to move the wiki to markdown files
