### ISSUE TITLE
CampJS III Workshoppers

### ISSUE THREAD

**Issue by timoxley** [nodeschool/discussions#323]
Count to Six by @domenic 
https://github.com/domenic/count-to-6

Planet Proto by @sporto
https://github.com/sporto/planetproto

ThreeJS Intro by @alexmackey
https://github.com/alexmackey/IntroToWebGLWithThreeJS

**Comment by martinheidegger** [comment]
@sporto Probably done, right?

**Comment by sporto** [comment]
@martinheidegger yes I added these are issues to my repo (and done most of them)

**Comment by martinheidegger** [comment]
@sporto thanks! closing this issue then.
