### ISSUE TITLE
learnyounode - http client - it should be response instead of request on http.get ?

### ISSUE THREAD

**Issue by hanksudo** [nodeschool/discussions#33]
When I finish learn you node "http client" challenge, it show a official solution like this:

```
var http = require('http')

  http.get(process.argv[2], function (request) {
    request.setEncoding('utf8')
    request.on('data', console.log)
    request.on('error', console.error)
  })
```

I think `function(requst)` should be `function(response)` ?

http://nodejs.org/api/http.html#http_http_get_options_callback

**Comment by moshebeeri** [comment]
I think there is a grater issue with learnyounode process
when I iterate and test my solution I am getting reasonable results, that I might believe to be true.
then when I am verifying my solution I get only the results without the test case (the command line that was used to test) and therefor can't refine my results.
for example the http client 
```javascript
var options = {
  hostname: process.argv[2],
  port: 80,
  path: '/',
  method: 'GET'
};

var req = http.request(options, function(res) {
  // console.log('STATUS: ' + res.statusCode);
  // console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', console.log);
});

req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});

req.end();
```
when running it via 'node httpclient.js google.com' I get the html from goole.com, believing I have solved the challenge.
but running it via 'learnyounode verify httpclient.js' I get:
   "problem with request: getaddrinfo ENOTFOUND" !=    "Boil-over"                        
   ""                                  !=    "Oldies"                           
                                       !=    "Ugg"                              
                                       !=    "Cut lunch commando"               
                                       !=    "Bludger"                          
                                       !=    "Bushranger"                       
                                       !=    "Barrack"                          
                                       !=    "Lizard drinking"                  
                                       !=    "Cooee"                            
                                       !=    ""                                 

without any option to understands whats went wrong :-(

**Comment by joelsaxton** [comment]
I have the exact same problem, @moshebeeri. I think the problem is with their app.

**Comment by Sandybhai** [comment]
Guys! I am really confused about the argument index to be used. When they say first argument is the url, shouldn't it be process.argv[0] ? how come it's process.argv[2] in this case?

**Comment by austincunningham** [comment]
from baby steps
You'll need to think about how to loop through the number arguments so
  you can output just their sum. The first element of the process.argv array
  is always 'node', and the second element is always the path to your
  program.js file, so you need to start at the 3rd element (index 2), adding
  each item to the total until you reach the end of the array.
