### ISSUE TITLE
Currying should introduce the concept of currying

### ISSUE THREAD

**Issue by CamiloMM** [nodeschool/discussions#333]
This is the intro text to the currying lesson in `functional-javascript`:

    This is an example implementation of curry3, which curries up to 3 arguments:

```js
    function curry3(fun){
      return function(three){
        return function(two){
          return function (one){
            return fun(one, two, three)
          }
        }
      }
    }
```

I guess the usage of the term "`curry3`" comes from reading [an O'Reilly book](http://books.google.com.br/books?id=OIhuxqUO2TcC&pg=PT170).

But keep in mind that this sounds like saying "`bind4`" or "`apply7`", and the *Pyramid of Doom* syntax doesn't help in making it look appealing.

I say this as someone who was already familiar with currying, but keep in mind that many people may be coming to these lessons not as refresher/practice but as first-time experience with functional javascript. Up to this excercise it felt like it was written for first-timers (which is for the best, I think).

**Comment by timoxley** [comment]
You should PR. :+1:
