### ISSUE TITLE
Run NodeSchool classes in the browser

### ISSUE THREAD

**Issue by balupton** [nodeschool/discussions#340]
Here is the first one:

- http://runnable.com/U5_khE1yoWUQX_5P/nodeschool-learnyounode-for-node-js (click the run button)

Note: For authors, we need to run `npm install` in the terminal we have when creating the runnable script, just to do the initial once-off install of the modules.

Would be cool to have these on the website.

**Comment by martinheidegger** [comment]
@balupton This still works right? Should we put it in the wiki?

**Comment by martinheidegger** [comment]
Will close it, due to missing permission. Please reopen if need-be.

**Comment by balupton** [comment]
Happy to give whoever needs it permissions they need.

**Comment by martinheidegger** [comment]
@balupton Can you create a PR with a markdown file explaining how it works?
