### ISSUE TITLE
stream-adventure: web-sockets issue

### ISSUE THREAD

**Issue by Bondifrench** [nodeschool/discussions#352]
My solution to the websocket problem was the following:
````
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8000');

stream.pipe('hello\n');
````
It passed the test, which I guess it shouldn't because i forgot to end the stream.

I have another issue with the verification process, it finishes before I have time to open/refresh my browser on localhost:8000 and see whatever there is to see.
Am I not supposed to see 'hello' printed on the client side/browser side, or am I missing something? Thx

**Comment by Sequoia** [comment]
See: https://github.com/substack/stream-adventure/issues/53
