### ISSUE TITLE
NodeSchool Field Trip 2015™ / nodeschool at CCC Camp 2015 

### ISSUE THREAD

**Issue by yangwao** [nodeschool/discussions#353]
Summer 2015 will be The Chaos Communication Camp of the Chaos Computer Club in Germany
(The place is not Finowfurt, but <a href="http://de.wikipedia.org/wiki/Ziegeleipark_Mildenberg"> Ziegeleipark Mildenberg</a>)
Would be awesome to bring there tent for nodeschool and bring more hackers on board!
This community is pretty aware of Arduino, quadcopters and other electronics. 
Talked about it with @diasdavid and @olizilla 

Date <h3><strong>13th - 17th August 2015</strong></h3>

Some history of this event http://en.wikipedia.org/wiki/Chaos_Communication_Camp
http://events.ccc.de/2010/08/10/chaos-communication-camp-2011/

[1] http://wiki.milliways.info/wiki/Chaos_Communication_Camp_2015

# [#CCC15](https://twitter.com/search?q=ccc15)

**Comment by diasdavid** [comment]
We've dates!  https://twitter.com/c3infodesk/status/532434894077825024
#### 13th - 17th August 2015

**Comment by ralphtheninja** [comment]
@diasdavid :+1:

**Comment by ralphtheninja** [comment]
I think we should make a list of stuff that we need for the event. What do we need? What would we like to do? I'm voting for a couple of different things, e.g. some Arduino stuff and some NodeCopters of course :)

**Comment by cianomaidin** [comment]
Ok I'm up for helping

**Comment by gorhgorh** [comment]
I don't even need to say i'm in :-)

**Comment by ralphtheninja** [comment]
ping @mcollina

**Comment by elf-pavlik** [comment]
ping @nodeschool/berlin

**Comment by mcollina** [comment]
I will try my best, but it's too far ahead for me to make plans now: I'll
try to come, but we usually had family vacantions at that point of the
year! I'll know more in one or two months :/.


Il giorno ven 2 gen 2015 alle 14:54 ralphtheninja
notifications@github.com> ha scritto:

ping @mcollina <https://github.com/mcollina>

**Comment by orkoden** [comment]
The place is not Finowfurt, but [Ziegeleipark Mildenberg](http://de.wikipedia.org/wiki/Ziegeleipark_Mildenberg)

**Comment by ralphtheninja** [comment]
@mcollina It's cool. Just wanted to put the information in your head :)

**Comment by yangwao** [comment]
❤ 2 ✈ NodeSchool Field Trip 2015™ ✔
As it's mostly hardware geeks (lockpicking sessions, arduino, 3d printers from CCC11), we should focus how to node on simple hardware, so nodebots would be a thing!

**Comment by finnp** [comment]
So here's where we would have to add our village: https://events.ccc.de/camp/2015/wiki/Static:Villages

I'm currently in contact with the Ruby community in Berlin, maybe we can have a village together :)

**Comment by finnp** [comment]
We're going to have a meeting on Monday in Berlin together with Rusties and Rubies: https://github.com/rubytown/Chaos-Communication-Camp-2015/issues/2#issuecomment-97023309

If anyone in Berlin wants to join, just let me know :)

**Comment by ralphtheninja** [comment]
@finnp I might be renting one of these tents https://events.ccc.de/camp/2015/wiki/Rent_a_Tent .. we could use that for nodeschool/nodebots/whatever related things

**Comment by ralphtheninja** [comment]
@cianomaidin Can we borrow the node land flag? :)

**Comment by finnp** [comment]
@ralphtheninja We are currently starting to fundraise money for our tent. The campaign isn't online yet though. There's an issue open over here https://github.com/rubytown/Chaos-Communication-Camp-2015/issues/11 Maybe you could comment over there, if you're interested in sponsoring a tent.

Since we want to have a tent together with the Ruby and Rust community, we want to go for a big tent.

**Comment by maxogden** [comment]
I will be there!!!! also @mafintosh and @karissa

**Comment by ralphtheninja** [comment]
@maxogden Cool! This will be epic :)

@finnp Aaah ok. Getting a really big tent is a good idea. I'd be happy to pitch in. You have to get this done before the 20th, just fyi.

**Comment by finnp** [comment]
@ralphtheninja Cool, yeah we're aware of that. The next meeting is mainly for doing that. Btw, don't be confused about the name `rubytown`, we're going to change that name to a more inclusive one soon.

**Comment by karissa** [comment]
@finnp good because I don't know ruby. And I'd be happy to pitch in monetarily, just ping this thread when something goes live.

**Comment by ralphtheninja** [comment]
@karissa https://www.betterplace.org/en/projects/30076-an-assembly-on-chaos-communication-camp-providing-free-teaching

**Comment by ralphtheninja** [comment]
Also see https://github.com/rubytown/Chaos-Communication-Camp-2015/issues/11

**Comment by karissa** [comment]
great! donated.

On Sat, Jun 6, 2015 at 2:21 PM, Lars-Magnus Skog <notifications@github.com>
wrote:

> Also see rubytown/Chaos-Communication-Camp-2015#11
> <https://github.com/rubytown/Chaos-Communication-Camp-2015/issues/11>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/353#issuecomment-109651344>
> .
>



-- 
Karissa McKelvey
karissamck.com

Dat dat-data.com
U.S Open Data usopendata.org
Debt Collective debtcollective.org
Taskforce taskforce.is
Brass Liberation Orchestra brassliberation.org

**Comment by ralphtheninja** [comment]
Already at 50% funding!

**Comment by cjdelisle** [comment]
Can we come? :D   @larsg @ansuz @jbenet @krl @cryptix @dangowrt @wfleurant @kpcyrd

**Comment by jbenet** [comment]
cc @whyrusleeping

**Comment by ralphtheninja** [comment]
@cjdelisle Who's going to stop you? :)

**Comment by cjdelisle** [comment]
well not my bank, only 306€ to go :)

**Comment by SomeoneWeird** [comment]
a wild cjd appears.

**Comment by ralphtheninja** [comment]
@gorhgorh Donated as well. 200 to go!

**Comment by ralphtheninja** [comment]
Funded! Stretch goal was added for an even bigger tent.

**Comment by diasdavid** [comment]
Let's organize these troops! :D 

**People that going (say "I'm in" in this thread, if I missed to add you to the list):** 

- [X] @ralphtheninja 
- [X] @gorhgorh 
- [X] @diasdavid
- [X] @jbenet 
- [X] @larsg
- [X] @karissa 
- [X] @mafintosh 
- [X] @maxogden 
- [X] @finnp 
- [X] @yangwao 
- [ ] @rvagg ??
- [ ] @mikeal  ??
- [ ] @cianomaidin ??
- [ ] @mcollina ??
- [X] @ansuz 
- [X] @krl 
- [X] @cryptix 
- [X] @dangowrt 
- [X] @wfleurant 
- [X] @kpcyrd

**Plans:**

- [ ] Organize the CCC nodeschool 
  - Q: What do we need to make this happen?
- Q: Anyone that has CCC experience can let us know what we should be planning/thinking too?

**Important links (because finding stuff about CCC can be hard**

- main page - http://events.ccc.de/camp/2015/wiki/Main_Page
- tickets - http://events.ccc.de/2015/06/29/camp-tickets/

**Comment by rvagg** [comment]
Embarrassing that my name is not ticked there. CCC sounds like a blast and this would be a lot of fun but currently I'm a -0 because ... Germany is close to the opposite side of the planet to me (actually @diasdavid, I'm pretty sure you're _very_ close to my antipode) and :airplane:s are hard work when you're a big fella like me.

**Comment by diasdavid** [comment]
It is perfectly understandable :) however, I'm definitely going to miss your company @rvagg :)

**Comment by ralphtheninja** [comment]
@diasdavid Good that you're stepping up David! Not sure we really need anything but access to electricity and wifi. There's a list of things for the village here: https://events.ccc.de/camp/2015/wiki/Village:OpenCodeTown

**Comment by diasdavid** [comment]
Just updated the comment https://github.com/nodeschool/discussions/issues/353#issuecomment-117156920 to get things more tidy :)

@feross , not sure if this info has reached you, but I'm sure you would enjoy coming

**Comment by jbenet** [comment]
Yep, @feross come to CCC! \o/

**Comment by diasdavid** [comment]
Ticket sales were extended untill the 31st of July, make sure to get yours :):)
http://events.ccc.de/camp/2015/wiki/Static:Tickets

**Comment by feross** [comment]
Just saw this!

I got tickets to Copenhagen for Aug 4, and getting a ticket to Berlin around Aug 12 will be easy from there. But the website says that CCC Camp tickets are sold out. I emailed them to see if they can hook me up... If they can't, I'll just show up, sneak in, and donate a ticket price to CCC online :)

So... count me in!

**Comment by yangwao** [comment]
I think some tickets are maybe just reserved and some folks can change
opinion or will forget to pay. Keep eye on tickets :)

**Comment by ralphtheninja** [comment]
@diasdavid Who made the logo? It's the most badass logo ever!

**Comment by myf** [comment]
people at the camp wants to do some hack session the next few days?

**Comment by finnp** [comment]
@myf The camp is one big hack session. There's a NodeSchool tomorrow at 2pm btw.

**Comment by myf** [comment]
@finnp i think i completely missed the nodeschool. was swimming in the lake. im trying to hack a bit on the rad1o thing. will say hello if i bump into you!

**Comment by finnp** [comment]
Anyone who attended CCCamp in Berlin now? There's still on free speaker slot open for the Berlin.js meetup tomorrow: http://berlinjs.org/

**Comment by diasdavid** [comment]
@jbenet , @krl and @mappum are there :)

**Comment by maxogden** [comment]
do a hackrf talk!

**Comment by finnp** [comment]
A hackrf demo would have been sweet. Talks slots are taken now (by @karissa and @jbenet \o/), but maybe @mappum could squeeze something in.

**Comment by jbenet** [comment]
Yeah! the hackrf stuff is pretty cool. @mappum made a sweet waterfall graph:

![](http://puu.sh/jH1O6/8c94940b90.png)

I'm happy to split my slot with @mappum (or we could even do 4 talks! :O)

**Comment by yangwao** [comment]
See you at CCC Camp 2019 ;)
