### ISSUE TITLE
stream-adventure: new installation

### ISSUE THREAD

**Issue by Bondifrench** [nodeschool/discussions#355]
Hi,

due to past problems with this adventure, I uninstalled stream-adventure with 
````npm uninstall -g stream-adventure````
and then reinstalled it with:
````npm install -g stream-adventure```` it installs version 2.5.0

When running it, the menu has changed to the following with a lot of empty adventures at the end (all the STREAM2 ones):
![image](https://cloud.githubusercontent.com/assets/4905917/3405781/73b8bbe4-fd82-11e3-9f1d-07f8efa6654b.png)
Are these draft new exercises or problems arising from uninstall/install of different versions of stream-adventure?

**Comment by martinheidegger** [comment]
The latest stream-adventure doesn't seem to have those entries. Closing this issue.
