### ISSUE TITLE
Expressworks Hello World! connection error

### ISSUE THREAD

**Issue by jalane76** [nodeschool/discussions#385]
Hello,

I am trying to run the Hello World! exercise and am getting the following error:

Running "HELLO WORLD!"...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

I'm running it on a Windows 7 machine with the firewall turned on, however, when I first ran the script I was prompted to unblock Node and did so.  Does anyone have a suggestion as to what could be going wrong?

Thank you.

**Comment by Sequoia** [comment]
@jalane76 if you can repro this on a non-work-administered machine please comment for reopen.
