### ISSUE TITLE
nodeschool interactive

### ISSUE THREAD

**Issue by generalhenry** [nodeschool/discussions#390]
I made a prototype of in browser nodeschool

currently @ generalhenry.com

the code for it is between:
https://github.com/generalhenry/nodeschool-interactive
https://github.com/generalhenry/expose-bash-over-websockets
https://github.com/generalhenry/nodeschool-dockerfiles

**Comment by martinheidegger** [comment]
Closing this issue because the outcome is awesome :smile:
