### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by hughsk** [nodeschool/discussions#397]
It would be super useful for workshop authors to have some simple form of anonymous analytics: the most obvious metrics being to see which exercises are being attempted, and which ones are being completed. That alone could provide insight into where people are getting stuck, and ensuring the difficulty curve isn't all over the place too.

We could potentially pull this out into a simple module that handles the setup, using Google Analytics, @segmentio's [analytics.js](https://github.com/segmentio/analytics.js), or something similar.

Though of course I think a lot of us are pretty wary about analytics too. Would this be worthwhile? If so, any ideas on a best way to approach this?

**Comment by Sequoia** [comment]
migrated to https://github.com/rvagg/workshopper/issues/9
