### ISSUE TITLE
NodeSchool Meta Meeting

### ISSUE THREAD

**Issue by mikeal** [nodeschool/discussions#407]
A few things are starting to stir up in issues like #402 about NodeSchool in a wider sort of meta sense.

It would be great if we could get as many of the NodeSchool people as possible on a Skype for a chat. We're all sort of relying on a loose understanding of the goals here that are shared among a bunch of us culturally and with the growth we're experiencing it's important to write it down in to something like a mission statement for new people.

Please give me your Skype names and the time zone you'll be in on July 24th so we can schedule a time that works for everyone :)

@brianloveswords 
@christensenep
@dominictarr 
@iancrowther
@jlord 
@linclark
@maxogden
@muan 
@orliesaurus
@rvagg 
@simonmcmanus
@substack 
@timoxley  
@toolness 
@olizilla

**Comment by martinheidegger** [comment]
@iancrowther @mikeal What was the outcome of this? Is this issue still relevant?

**Comment by iancrowther** [comment]
close IMO

**Comment by martinheidegger** [comment]
@iancrowther so i did :)
