### ISSUE TITLE
Open Badges for Nodeschool

### ISSUE THREAD

**Issue by finnp** [nodeschool/discussions#410]
Hello there,

I was recently thinking about how Nodeschool could embody Open Badges and gladfully saw that there were already a few discussions about it.

While it would be nice if there would be a mechanism to automatically issue badges for the cli courses, I thought maybe first there could be something added for the offline events.

I think it would be a cool if participants of a Nodeschool event would get a badge afterwards (maybe even the current logo as it already looks like a badge). For hosting of the badges and assertions I would suggest using GitHub Pages. The organizers of a local event could then be granted access to that repo or be added to the organisation and simply add the new badges to the repo.

I made a test for this in [this repo here](https://github.com/finnp/openbadges-host). I also tested a small script for sharing the badges easily: http://www.finnpauls.de/openbadges-host/share/#badge-example/1 . This just takes the location of the badge in the hash part of the url, loads the proper image and allows people to simply add it to their backpack. 

Also I wrote a CLI for managing the badges and simply add new ones without writing the JSON files all by yourself: https://github.com/finnp/openbadges-issuer

Another cool think would be to design something like a GitHub Fork Badge and create a tutorial for making a pull request for adding yourself to the repo (similiar to the git-it workshop, could be a small challenge after completing that). That badge would show that people are able to do a pull request and the learner would be more confident going through the GitHub Flow (= win).

Would love to hear your opinion. 

Best, Finn

**Comment by martinheidegger** [comment]
The badge system has been discussed in https://github.com/nodeschool/organizers/issues/126#issuecomment-71232680 and I think we can safely say that the voices are very complex. How about putting a recommendation somewhere that: If some company/organisation starts a badge program and we like it that we will feature it on the homepage?

**Comment by martinheidegger** [comment]
Closing issue (other issues with similar topic are open).
