### ISSUE TITLE
stream-adventure http-server - hanging server

### ISSUE THREAD

**Issue by kevinansfield** [nodeschool/discussions#44]
I'm using the following code for the HTTP Server challenge of stream-adventure but the test is still failing.

```
var http = require('http');
var through = require('through');

var server = http.createServer(function (req, res) {
    if (req.method === 'POST') {
        req.pipe(through(function (buf) {
            this.queue(buf.toString().toUpperCase());
        })).pipe(res);
    }
    else res.end('send me a POST\n');
});
server.listen(8000);
```

I'm getting this response and I'm left with a node process that I have to kill manually:

```
➜  stream-adventure  stream-adventure verify 07-http-server.js
ACTUAL                             EXPECTED
------                             --------

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

If I kill any running node processes and then run the script manually with `node 07-http-server.js`, I am able to post to the server with curl and get a correct response but only once, any further attempts to post to the server just hang until they timeout and I have to kill the process again.

I believe the code I'm using is the same as the official solution. Is there a bug somewhere?

I'm running node v0.10.9 and the stream-adventure package was installed yesterday.

**Comment by claudiopro** [comment]
@substack Awesome! Thank you
