### ISSUE TITLE
LearnYouNode - Juggling Async

### ISSUE THREAD

**Issue by cflanagan** [nodeschool/discussions#440]
Why does my solution not work? In my solution, the response is all out of sync. It's like the process.argv[2 + i] doesn't understand that I'm asking for the 2, 3, 4 indices and starts with zero.

My Solution

```
var http = require('http');
var bl = require('bl');
var result = [];
var count = 0;

for(var i=0;i<3;i++) {
    http.get(process.argv[2 + i], function(res){
        res.pipe(bl(function(err,data){
            if(err) return console.log(err.message);
            result[i]  = data.toString();
            count++;
            if(count == 3) {
                for(var j=0;j<result.length;j++) {
                    console.log(result[j]);
                }
            }
        }));
    });
}
```

NodeSchool Solution

```
var http = require('http')
var bl = require('bl')
var results = []
var count = 0

function printResults () {
  for (var i = 0; i < 3; i++)
    console.log(results[i])
}

function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error(err)

      results[index] = data.toString()
      count++

      if (count == 3) // yay! we are the last one!
        printResults()
    }))
  })
}

for (var i = 0; i < 3; i++)
  httpGet(i)
```

**Comment by ketus** [comment]
Hi guys,
and I'm getting proper (I think!) responses, but at beginning of every response there's undefined.
Here's code:
```javascript
var http = require("http");

var data = [];

function getHttp(index){
    http.get(process.argv[index + 2], function(res) {
        res.on('data', function(chunk) {
          data[index] += chunk.toString();
        });
        
        res.on('end', function() {
           console.log(data[index].toString());
           console.log('\n');
        });
    });
}

for (var i = 0; i < 3; i++){
    getHttp(i);
}
```
What you guys think might be the reason?

**Comment by sunlee-newyork** [comment]
Here's another passing version with a recursive approach:

```javascript
var http = require('http')
var bl = require('bl')

var responseList = []
var args = process.argv

function storeResponse(i, end) {
	http.get(args[i], (response) => {
		response.pipe(bl((err, data) => {
			if (err)
				return console.error(err)
			
			console.log(data.toString())
			responseList.push(data.toString())
		}))

		i++

		if (i < end)
			storeResponse(i, end)
	})
}

storeResponse(2, args.length)

responseList.forEach((response) => {
	console.log(response)
})
```

**Comment by sunlee-newyork** [comment]
Here's another passing version with a recursive approach:

```javascript
var http = require('http')
var bl = require('bl')

var responseList = []
var args = process.argv

function storeResponse(i, end) {
	http.get(args[i], (response) => {
		response.pipe(bl((err, data) => {
			if (err)
				return console.error(err)
			
			console.log(data.toString())
			responseList.push(data.toString())
		}))

		i++

		if (i < end)
			storeResponse(i, end)
	})
}

storeResponse(2, args.length)
```

**Comment by vulbecula** [comment]
Old and closed but here is my answer without any third party modules:
`const http = require('http')

var result = []
var urlcnt = process.argv.length-2

//print results in order
function print(){
	for(x in result){
		console.log(result[x])
	}
}

function done(index){
  //console.log("done with " + index.toString())
  if(urlcnt == 0)
    print()
}

function getUrls(index){
	req = http.get(process.argv[2 + index], (res) => {
		var str = ""
		res.setEncoding('utf8')
		res.on('data', (dat) => {str += dat}) //gather data respones
		res.on('error', console.error)
		res.on('end', () => {
      result[index] = str //save full response
      urlcnt-- //counting down the params
      done(index) //check if all fetch's are done
    })
	}) 
}

for(i = 0; i<process.argv.length-2; i++){  
	getUrls(i)
}`

**Comment by briancbarrow** [comment]
I'm not sure why my code isn't passing:

```var files = process.argv.slice(2);
var count = 0;
var results = [];
var http = require('http');
function printOut() {
    for (var t = 0; t < results.length; t++) {
        console.log(results[t]);
    }
}

function run(id){
    http.get(files[id], function(response) {
        var output = '';
        count++;
        response.setEncoding('utf8');
        response.on("data", function(data) {
            output += data;
        });
        response.on("end", function() {
            count--;
            //console.log(count);
            results[id] = output;
            if (count === 0) {
                printOut();
            }
        });
        }).on('error', function(e){
                console.log("error:" + e.message);
            });

}

for(var j = 0; j < files.length; j++){
    //console.log('Running ' + (j+1) + 'st get');
    run(j);
}```

**Comment by briancbarrow** [comment]
I'm not sure why my code isn't passing. Any thoughts?

```javascript
var files = process.argv.slice(2);
var count = 0;
var results = [];
var http = require('http');
function printOut() {
    for (var t = 0; t < results.length; t++) {
        console.log(results[t]);
    }
}

function run(id){
    http.get(files[id], function(response) {
        var output = '';
        count++;
        response.setEncoding('utf8');
        response.on("data", function(data) {
            output += data;
        });
        response.on("end", function() {
            count--;
            //console.log(count);
            results[id] = output;
            if (count === 0) {
                printOut();
            }
        });
        }).on('error', function(e){
                console.log("error:" + e.message);
            });

}

for(var j = 0; j < files.length; j++){
    //console.log('Running ' + (j+1) + 'st get');
    run(j);
}
```

**Comment by midnightriot** [comment]
@briancbarrow here is a modified version of your solution that works. Your issue was cause by incrementing count inside the async code, causing the printOut function to be called multiple times. I simply moved the increment statement just above the async code. Le me know if you have any questions.

```javascript
var files = process.argv.slice(2);
var count = 0;
var results = [];
var http = require('http');
function printOut() {
    for (var t = 0; t < results.length; t++) {
        console.log(results[t]);
    }
}

function run(id){
    count++;
    http.get(files[id], function(response) {
        var output = '';

        response.setEncoding('utf8');
        response.on("data", function(data) {
            output += data;
        });
        response.on("end", function() {
            count--;
            //console.log(count);
            results[id] = output;
            if (count === 0) {
                printOut();
            }
        });
        }).on('error', function(e){
                console.log("error:" + e.message);
            });

}

for(var j = 0; j < files.length; j++){
    //console.log('Running ' + (j+1) + 'st get');
    run(j);
}
```

**Comment by merapi** [comment]
Hello, can someone explain why this solution "sometimes" work?

`
var http = require('http');
var done = [];

process.argv.splice(2).map((url, index) => {
    http.get(url, response => {
        var str = '';
        response.setEncoding('utf8');
        response.on('data', data => str += data);
        response.on('error', console.log);
        response.on('end', () => {
            done[index] = str;
            if(done.length == 3) {
                done.forEach( data => console.log(data) );
            }
        });
    }).on('error', console.error);
});
`

**Comment by Bnic3** [comment]
Does any one have a solution with the recommended libraries  "Async" and "after" modules.

**Comment by robeferre** [comment]
It works for me...

var http = require('http');
var urls = process.argv.slice(2,process.argv.length);
var pages = [];
var waiting = 0;

urls.map(function(url,idx){
    waiting++;
    http.get(url,function(res){
        var alldata = "";
        res.setEncoding('utf8');
        res.on('data',function(data){alldata += data});
        res.on('end', function(){
            pages[idx] = alldata;
            waiting--;
            if (!waiting) {
                pages.map(function(page){console.log(page)});
            }
        });
    });
});

**Comment by robeferre** [comment]
```
var http = require('http');
var urls = process.argv.slice(2,process.argv.length);
var pages = [];
var waiting = 0;

urls.map(function(url,idx){
    waiting++;
    http.get(url,function(res){
        var alldata = "";
        res.setEncoding('utf8');
        res.on('data',function(data){alldata += data});
        res.on('end', function(){
            pages[idx] = alldata;
            waiting--;
            if (!waiting) {
                pages.map(function(page){console.log(page)});
            }
        });
    });
});
```

**Comment by charazn** [comment]
Can someone explain why there must be a counter in order for the code to work? 
```
const http = require('http');
const concat = require('concat-stream');
var urls = process.argv.slice(2);
var lines = [];
// var count = 0;

function httpGet(idx) { 
  http.get(urls[idx], function(response) {
    response.setEncoding('utf8');
    response.on('error', console.error);

    response.pipe(concat(function(data) {
      lines[idx] = data.toString();
      // count++
      // console.log(idx); // returns 0, then 1, then 2
      // console.log(urls.length-1); // always returns 2

      if (idx === urls.length-1) { // instead of (count === 3)
        for (i = 0; i < lines.length; i++) {
          console.log(lines[i]);
        }
      }
    }));
  });
}

for (i = 0; i < urls.length; i++) {
  httpGet(i);
}
```
I wanted my code not to be hard-coded, therefore leaving out the count global variable on purpose. If we know the length of the urls array, therefore we also know the last index i passed into the httpGet(i) function, why doesn't  `if (idx === urls.length-1) ` work, knowing that idx === 2, and urls.length-1 also === 2? Could someone explain the reason / difference please? Appreciate it.

**Comment by lvivier** [comment]
@charazn from the hints section of "Juggling Async" in learnyounode:

> You will need to queue the results and keep track of how many of the URLs have returned their entire contents. Only once you have them all, you can print the data to the console.  
> 
> Counting callbacks is one of the fundamental ways of managing async in Node.

In your code, the `count` variable isn't intended to keep track of the last index passed into `httpGet()`, it's to *count how many times the callback to `concat()` has been called*. The key lesson the "Juggling Async" exercise is trying to impart is that you can't know ahead of time in which order the http requests will complete. The reason your solution doesn't work as you expect is, most of the time the requests won't complete in the order they were dispatched, so the `lines` array isn't populated yet.

I see no reason why, in your solution, you couldn't substitute `urls.length` for `3`.

**Comment by YangShuting** [comment]
My answer is quite different from the above. Though it works, I still want to know if it is the regular answer.
`var http = require('http');
var url1 = process.argv[2];
var url2 = process.argv[3];
var url3 = process.argv[4];

http.get( url1, function (response){
	var result = '';
  response.on('data', function (data){
    result += data;
  });
  response.on('end', function (data) {
  	console.log(result);
    http.get( url2, function (response) {
    	var result1 = '';
    	response.on('data' , function (data) {
         result1 += data;
    	});
    	response.on('end', function (data) {
         console.log(result1);
         http.get( url3, function (response) {
         	result2 = '';
         	response.on( 'data', function (data) {
         		result2 += data;
         	});
         	response.on('end', function (data) {
         		console.log(result2);
         	});
         });
    	});
    });
  });
});`

**Comment by charazn** [comment]
@YangShuting, as posted in the solutions or comments above and hinted from the lesson instructions, http.get() is asynchronous, hence the suggestion to queue the results.

What you did was to http.get() each url manually, in sequence, and printing that out to the console. The results work because the checker checks for what is output to stdout. 

You might like to refer to the comments above to implement it with a list of urls, instead of one per time.

**Comment by charazn** [comment]
@Bnic3 I implemented using async.

```
var http = require('http');
var concat = require('concat-stream');
var async = require('async');
var urls = process.argv.slice(2);

var q = async.queue(function(task, callback) {
  http.get(task, function(response) {
    response.setEncoding('utf8');
    response.on('error', console.error);
    response.pipe(concat(function(data) {
      callback(data);
    }));
  });
});

q.push(urls, console.log); 
```

Here are some useful references:
http://caolan.github.io/async/docs.html#.queue
https://github.com/nodeschool/discussions/issues/203

The general syntax: queue(worker, concurrency(opt))

**Comment by jim-hm** [comment]
It's my approach, also you can log result inside pipe method and remove the callback on completion.

```javascript
var http = require('http');
var bl = require('bl');
var async = require('async');

var httpget = function(url, callback){
    http.get(url, function(res){
        res.pipe(bl(function(err, data){
            if(err) {
               return callback(err);
            }
           callback(null, data.toString());
        })); 
    });
};

var printResult = function (results) {
    results.forEach(function(result){
        console.log(result);
    })
}

async.series([
    function(callback) {
        httpget(process.argv[2], callback);
    }, 
    function(callback) {
        httpget(process.argv[3], callback);
    },
    function(callback) {
        httpget(process.argv[4], callback);
    }
], function(err, results){
    if (err) {
        console.error(err)
    } else {
        printResult(results)
    }
})

```

**Comment by tapasweni-pathak** [comment]
👋 What are URLs that this chapter uses as command line arguments? I need to debug my solution with node and want to use same get calls that this exercise uses.
