### ISSUE TITLE
learnyounode - Make it Modular - solution works but fails

### ISSUE THREAD

**Issue by jstjoe** [nodeschool/discussions#441]
The reported error is:

Your additional module file [module.js] does not appear to pass back an error received from 
`fs.readdir()`
Use the following idiomatic Node.js pattern inside your callback to `fs.readdir()`:
    if (err)
      return callback(err)

My program.js:

```
var module = require('./module.js');
var filter = process.argv[3];
var dir = process.argv[2];

module(dir, filter, function(err, data) {
  data.forEach(function(element, index, list) {
    console.log(element);
  });
});
```

My module.js:

```
var fs = require('fs'),
    path = require('path');
module.exports = function(dir, filter, callback) {
  var matches = [];
  fs.readdir(dir, function (err, data) {
    if (err) {
      callback(err);
    }
    data.forEach(function (element, index, list) {
      if(path.extname(element) == '.' + filter) {
        matches.push(element);
      }
    });
    callback(null, matches);
  });
};
```

Note that, at least as far as I can tell, I am following their recommended pattern by putting the following in my callback to fs.readdir():

```
if (err) {
   callback(err);
}
```

Thanks for any suggestions.

**Comment by avanish24** [comment]
Just a note to whoever reaches here, 
Read the second and third line carefully, first argument is directory name and second argument is the extension filter.
You will save hours of debugging🙂 
```
Create a program that prints a list of files in a given directory,  
  filtered by the extension of the files. The first argument is the  
  directory name and the second argument is the extension filter. Print the  
  list of files (one file per line) to the console. You must use  
  asynchronous I/O.  
```
