### ISSUE TITLE
Modular Help

### ISSUE THREAD

**Issue by colincannon-acp** [nodeschool/discussions#471]
Here is my modular file

````
module.exports = function (mydir,myext,callback)
  {
      fs=require('fs');
      path=require('path');
      var myres=new Array();
      fs.readdir(mydir,function(err,list){
      if (err) 
             return callback(err);
          for (var i=0;i<list.length;i++)
          {
              if (path.extname(list[i]) == '.'+myext)
              {
                 myres.push(list[i]);
             }   
         }   
     }); 
     callback(null,myres);
}  
````

Here is my main file

````
var mymodule=require('./mymodule.js');
 var files=mymodule(process.argv[2],process.argv[3],cbak);
 
 function cbak(err,data)
 {
     console.log(data);
 }
````

I am stuck because my `cbak` function is not getting any data to print to the screen and I am getting this error:

Your additional module file [mymodule.js] does not appear to pass back an error received from `fs.readdir()`Use the following idiomatic Node.js pattern inside your callback to `fs.readdir()`:
	if (err)
	  return callback(err)

Can anyone one help me to progress past this point?

**Comment by avanish24** [comment]
Just a note to whoever reaches here, 
Read the second and third line carefully, first argument is directory name and second argument is the extension filter.
You will save hours of debugging🙂 
```
Create a program that prints a list of files in a given directory,  
  filtered by the extension of the files. The first argument is the  
  directory name and the second argument is the extension filter. Print the  
  list of files (one file per line) to the console. You must use  
  asynchronous I/O.  
```
