### ISSUE TITLE
Unable to do levelDb

### ISSUE THREAD

**Issue by zwhitchcox** [nodeschool/discussions#487]
I don't know about you guys, but when I'm coding, I make a LOT of mistakes. So many. So many mistakes.

And my main way of debugging my programs is to use console.log(). However, in the levelDb game, I noticed that it will not allow me to console.log(). I'm flying blind out there.

I was just wondering if there was any way ya'll could enable this feature or maybe suggest a new method of debugging. In the mean time, I suppose I'll check out the bug clinic game.

Thanks a million!

**Comment by martinheidegger** [comment]
@zwhitchcox Did you manage to get it working in the meanwhile?

**Comment by zwhitchcox** [comment]
Yes, I'm pretty sure console.error worked.

**Comment by martinheidegger** [comment]
Cool! Closing this issue :)
