### ISSUE TITLE
stream-adventure websockets

### ISSUE THREAD

**Issue by L2L2L** [nodeschool/discussions#501]
```
"use strict";

var http;
http = require("http");
var option;
option = {
    hostname:"localhost",
    port: 8000,
    method: "GET"
};
var req;
req = http.request(option,function(res){
    res.sned("hello\n");
});
//req.send("hello\n");

```

Any consideration of what I should do? What core module would I look at to pass the websockets lesson/test?

**Comment by mdavidjohnson** [comment]
I'm also having prety much the same difficulty here. I note open issues 501, 352, 289, 265, and 224 going back to March of last year.

Here's my code:

```
/*
*****
*
* WebSockets.js
* Nodeschool stream-adventure
* Challenge 9/15 
* MDJ 2015/01/09
*
*****
*/

var ws = require('websocket-stream');

var stream = ws('ws://localhost:8000');

stream.write('hello\n');
stream.end();
```

On "stream-adventure verify WebSockets.js" the system responds with:

```
################################################
#                                              #
# Open http://localhost:8000 to run your code! #
#                                              #
################################################

ACTUAL                             EXPECTED
------                             --------
""                                 ""                            
# PASS

Your solution to WEBSOCKETS passed!

Here's what the official solution is if you want to compare notes:

    var ws = require('websocket-stream');
    var stream = ws('ws://localhost:8000');
    stream.end('hello\n');
    
You have 7 challenges left.
Type `stream-adventure` to show the menu.
```

and then returns to the prompt.

On then going to another terminal and entering "http://localhost:8000" into elinks, the browser returns, "Unable to retrieve http://localhost:8000/: Connection refused".

And then, On "stream-adventure run WebSockets.js" the system responds with:

```
################################################
#                                              #
# Open http://localhost:8000 to run your code! #
#                                              #
################################################
```

and then blocks without returning to the prompt.

On then going to another terminal and entering "http://localhost:8000" into elinks, the browser returns a blank page.

I noted in issue #289 that this is a "known issue" - that was on August 16th of last year. 

What is the current status?

**Comment by Sequoia** [comment]
Does this ticket cover the same issue? https://github.com/substack/stream-adventure/issues/53?
