### ISSUE TITLE
Cleanup the issues

### ISSUE THREAD

**Issue by balupton** [nodeschool/discussions#504]
Now that there is a repo for everything, perhaps we should rename this repo to "support", and have a new repo called "meta" for meta discussions around nodeschool.

We should also close (or migrate) all issues relating to upcoming workshop modules, as they should now be on the workshopers repo.

We should also close (or migrate) all issues relating to node school events, as they should be on their own repos.

Who needs to give the go ahead for this?

**Comment by martinheidegger** [comment]
Started to clean up following: https://github.com/nodeschool/organizers/issues/90

**Comment by finnp** [comment]
We're at a quite good level right now thanks to the amazing work of @martinheidegger :)

Everyone who wants to help to keep it that way, should follow these steps here: https://github.com/nodeschool/discussions#apply-priorities
