### ISSUE TITLE
learnyounode HTTP FILE SERVER

### ISSUE THREAD

**Issue by gdrooid** [nodeschool/discussions#515]
I just finished the 11th exercise for 'learnyounode', and although it passed, I got this:
![2014-08-28--1409184599_726x42_scrot](https://cloud.githubusercontent.com/assets/712829/4069493/6ab98bd6-2e47-11e4-87ed-57bcba34ca0e.png)

While the exercise says this:
![2014-08-28--1409184614_480x41_scrot](https://cloud.githubusercontent.com/assets/712829/4069499/81b0e668-2e47-11e4-9289-6eae0fe14918.png)

It's confusing...

**Comment by yarthur** [comment]
If you look at the OP, you'll notice that the lesson passes, but one of the unit tests fails. I still think that's an issue, regardless of how the lesson is presented. I expect that my code passes all unit tests (and gets all the little green check-marks) before passing as a whole, and this runs counter to that expectation.

I think the lesson could also stand to explain a little more why you need to do it this way, so people don't have to come here and read @greelgorke's explanation, but at the very least, don't pass me until I've actually passed.

**Comment by martinheidegger** [comment]
@yarthur gotcha!

**Comment by Sequoia** [comment]
https://github.com/rvagg/learnyounode/issues/239 migrated
