### ISSUE TITLE
Section for videos

### ISSUE THREAD

**Issue by faiq** [nodeschool/discussions#519]
Hi y'all! First issue I'm submitting on nodeschool. So this is kind of similar to #345, but not really. 

I was hoping that we could have a portion of the website where we curate relevant videos for each workshopper, along with videos from talks and stuff that might help someone understand the issue better. 

For example, when I was learning about streams this video 
https://www.youtube.com/watch?v=UHZpk4LwCLE
came in super handy.  

Some times its nice to have an actual person explain a concept, rather than just reading it on your own. Let me know what y'all think!

**Comment by martinheidegger** [comment]
@faiq I think its a good idea to have links & video materials collected with the hints & in the help of the workshopper materials. If you could add PR's for those it would be awesome. @faiq is it okay if I close this issue in the meantime?

**Comment by faiq** [comment]
would you mind bikeshedding this issue for a little longer? I'm more than happy to submit a PR, but I don't know what everyone wants

**Comment by martinheidegger** [comment]
@faiq Sorry for not answering. Lost in the flood of issues. I think the data of helping videos should be stored/maintained in the github repository for each workshopper. If its in a parseable format (json, markdown), then we can automatically add links to the homepage.

**Comment by Sequoia** [comment]
@faiq Don't worry about what "everyone" wants-- if you wait around for everyone to agree you'll be waiting for a long time! :smile_cat:.  I can't see why someone would object to a video page, the content of the videos might be more contentious... Anyway, submit a PR & go from there!
