### ISSUE TITLE
crypto combine seems to meet requirements...

### ISSUE THREAD

**Issue by dcostinett** [nodeschool/discussions#521]
I thought the crypt instructions indicate a good use for stream-combiner, but my implementation using it throws an unexpected error. My code (I have the libraries npm installed):

```JavaScript
var crypto = require('crypto');
var stream = crypto.createDecipher('aes256', process.argv[2]);
var combine = require("stream-combiner");

combine(process.stdin, stream, process.stdout);
```

but running the code reports an error:

```
_stream_readable.js:763
    while (!paused && (null !== (c = stream.read())))
                                            ^
TypeError: Property 'read' of object #<Socket> is not a function
```

I banged my head a little against this trying things like using process.openStream() for the first stream to no avail. I looked at the docs for stream-combiner and it seems to indicate that it's returning what the problem asks for -- from the docs:
Turn a pipeline into a single stream. Combine returns a stream that writes to the first stream and reads from the last stream. 

I'm a bit baffled -- can someone help?
Thanks.

**Comment by martinheidegger** [comment]
@dcostinett Have you figured it out in the meanwhile?

**Comment by dcostinett** [comment]
@martinheidegger I ended up viewing the solution to get past the issue... can't remember now exactly where I was getting hung up. :-( Sorry.

**Comment by martinheidegger** [comment]
No problem.
