### ISSUE TITLE
Bytewiser - Type Array

### ISSUE THREAD

**Issue by kyeung2** [nodeschool/discussions#523]
Hi I'm working on this exercise and I got it to work with the following

process.stdin.once('readable', function () {

	var firstChunk = process.stdin.read();
	var arrayBuff = new ArrayBuffer(firstChunk.length);
	var dataView = new DataView(arrayBuff);
		for (var i = 0; i < firstChunk.length; i++) {
			dataView.setUint8(i,firstChunk[i] );
		}
	var typedArray = new Uint8Array(arrayBuff);
	var jsonString = JSON.stringify(typedArray);
	console.log(jsonString);
});

And the official solution is much simpler;

   process.stdin.once('data', function(buff) {
     var ui8 = new Uint8Array(buff)
     console.log(JSON.stringify(ui8))
   })

Reading the documentation of Uint8Array (https://developer.mozilla.org/en-US/docs/Web/API/Uint8Array) I don't understand why it is possible to construct it with;

new Uint8Array(buff), with buff being a NodeJs Buffer.

If any one knows that would be great

Regards,

Kye

**Comment by martinheidegger** [comment]
@kyeung2 Did the explanation help you?
