### ISSUE TITLE
No link or explination of callbacks.

### ISSUE THREAD

**Issue by cgkades** [nodeschool/discussions#587]
Got to excercise 4 and it's asking to do callbacks. I have no idea how to do this in node (which is why I'm doing 'basics'). And in reality, the only reason I even know what they are is becasue of Twisted. If you're not going to include an explination on what they are or on how to use them, can you at least link some where that I can read about it?

**Comment by martinheidegger** [comment]
Latest version has been published, closing the issue for now. Please reopen if the error should still occur.
