### ISSUE TITLE
I think there is something wrong of "HTTP CLIENT"'s offical solution.

### ISSUE THREAD

**Issue by jiwoobong** [nodeschool/discussions#588]
------------------------------ in the tutorial
    var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)  // <-- this line will be ignored?
    })
------------------------------------------------------------------

Have to be like

    var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
     }).on('error', function(e) { console.log( 'error : ' + e.message); } );

is there anything that i am missing here?

**Comment by martinheidegger** [comment]
@pirfalt Assuming that you mean that request is correct but a duplicate.
