### ISSUE TITLE
Unable to make http request

### ISSUE THREAD

**Issue by appleofoureye** [nodeschool/discussions#598]
Hi,
I recently completed exercise 7 of learnyounode where you make an http request. However this worked at the nodeschool workshop using their wifi.
However when I try to run the same sample from home it does not work. Not sure why.
The error I get is 
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```
And the code is straight forward
```JavaScript
    var http = require('http')

    http.get(process.argv[2], function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)
    })
```

**Comment by Sequoia** [comment]
@appleofoureye is this resolved?
