### ISSUE TITLE
nodeJS built on chrome Javascript means and non blocking?

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [nodeschool/discussions#600]
i am just starting to learn NODEJS. but the definition of the nodejs is quite confusing for me as nodejs.org said

Node.js® is a platform built on Chrome's JavaScript(Q1) runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model(Q2) that makes it lightweight and efficient, perfect for data-intensive real-time applications(Q3) that run across distributed devices.
remember(Q#) are my questions
 
(Q1) it built on on chromes Javascript: what does it really means?? DO it means that it cannot run on other machine?? or the chorme's javascript is a seperate javascript.
 
(Q2) what does exactly meaning of non-blocking?
 
(Q3) real time application we can also make using asp.net but why NODEJS highlight this feature? do this is different than others?

**Comment by martinheidegger** [comment]
@MuhammadFaizanKhan Is your question answered?
