### ISSUE TITLE
hi there (chapter request: Romania)

### ISSUE THREAD

**Issue by iamcaps** [nodeschool/discussions#611]
maybe not a bad ideea as im from here ... school in Romania ?! thanks

**Comment by martinheidegger** [comment]
@iamcaps Are you considering opening the chapter in romania? Are you still searching for people do it with you?

**Comment by martinheidegger** [comment]
Assuming no.

**Comment by iamcaps** [comment]
yes 

     On Thursday, February 5, 2015 6:03 AM, Martin Heidegger <notifications@github.com> wrote:
   

 @iamcaps Are you considering opening the chapter in romania? Are you still searching for people do it with you?—

**Comment by martinheidegger** [comment]
Tweeted about it: https://twitter.com/leichtgewicht/status/568323690972078081

**Comment by finnp** [comment]
Which city in Romania do you want to have a NodeSchool?

**Comment by martinheidegger** [comment]
With 1/10th of the population living in Bucharest - I would assume there.

**Comment by iamcaps** [comment]
Bucharest or Iasi beeing the 2nd capacity in RO 


     On Tuesday, April 21, 2015 10:05 AM, Martin Heidegger <notifications@github.com> wrote:
   

 With 1/10th of the population living in Bucharest - I would assume there.—

**Comment by finnp** [comment]
@iamcaps Maybe you could go to a BucharestJS meetup and look for people who would be up for it: http://www.meetup.com/BucharestJS/

**Comment by IonicaBizau** [comment]
Hey there! Maybe I could help too!
Bucharest is on the other side of the country, but who knows, maybe I can help in my area. :octocat:
