### ISSUE TITLE
Sync I/O strange problem

### ISSUE THREAD

**Issue by RuneBarrett** [nodeschool/discussions#612]
Hi there. 
I am having a strange problem. 
Here is the array i get out when logging process.argv:
[ '/usr/local/bin/node',
'/Users/troels/WebstormProjects/helloWorld/HelloNode.js',
'/var/folders/f8/f5fxxrv11191fb4qhd50phv40000gn/T/_learnyounode_25945.txt' ]

Judging from the above a correct solution could be like this right? 
var strArr = fs.readFileSync(process.argv[2]).toString().split("/n");
console.log(strArr.length-1);

I mean it is obviously not the first entry in the process.argv array. it must be the third right? 
When i try to verify it returns 0 for my solution. If i choose the first argument it returns 2168, if i chose the second argument it returns 1.

**Comment by martinheidegger** [comment]
@RuneBarrett Are you still having problems? Can we help you?
