### ISSUE TITLE
Need a chapter in my state (Delaware, Pennsylvania)

### ISSUE THREAD

**Issue by vanazzz** [nodeschool/discussions#618]
Hi, I would like to start a nodeschool chapter - Delaware Valley chapter in PA. I work in IT division of a financial firm. I work as an IT Architect and my team determines our company's future technology. I will be organizing this chapter, myself in the beginning and later add more team members. I have created a github account - DVNodeJs. I have just started to use Node.js and would like to learn it with others.

**Comment by martinheidegger** [comment]
@vanazzz Are you still interested?

**Comment by vanazzz** [comment]
Sure,  I am.
Regards, 

Vana Khurana

**Comment by martinheidegger** [comment]
Tweeted about it: https://twitter.com/leichtgewicht/status/563605212099661825

**Comment by Sequoia** [comment]
@vanazzz Get up & rolling and if you hit any snags come ask here-- we love to help!! :smile_cat:
