### ISSUE TITLE
Frontend tutorials?

### ISSUE THREAD

**Issue by mikeal** [nodeschool/discussions#62]
I know that @maxogden mentioned that someone, possibly him, was working on a workshopper for frontend. Anyone know the status of this?

**Comment by Sequoia** [comment]
If someone wants to take this on they totally should! :smile_cat:

Personally I think actual in-browser tutorials is sorta beyond the scope of what nodeschool (based on workshopper, running in node), but a forking the project & porting it to the browser with a nice GUI & a built in code editor would be totally cool. **The power is yours!** :earth_africa:
