### ISSUE TITLE
looping-through-arrays task

### ISSUE THREAD

**Issue by simon-p-r** [nodeschool/discussions#637]
Hi

This is my code

```
var pets = ['cat', 'dog', 'rat'];

for (var i = 0 ; i < pets.length; i++) {
    console.log(pets[i] = pets[i] + 's');
}
```

However it won't pass this challenge, am I missing something?

**Comment by PabloVent** [comment]
The code that works for me which was offered in their solutions is:

var pets = ['cat', 'dog', 'rat'], i;
for (i = 0; i < pets.length; i++) {
  pets[i] += 's';
}
console.log(pets);

However, I don't understand why I'd add ",i" in the pets declaration, when the link between var pets and "i" is established within the for loop.

**Comment by a0viedo** [comment]
@PabloVent it's just one way of doing it.

You could either have:

```js
var pets = [];
var i;
```

or 
```js
var pets = [], i;
```

**Comment by peterson5** [comment]
I did it like this and it works for me 

var pets = ['cat', 'dog', 'rat'];

for (var i=0;i < pets.length; i++){
pets[i] = pets[i] + 's';
}
console.log(pets)
