### ISSUE TITLE
functions.js - javascripting.

### ISSUE THREAD

**Issue by nagaflokhu** [nodeschool/discussions#647]
I was trying to finish javascripting just now and got stuck on the penultimate exercise.

The instructions are to define a function named eat that takes an argument named food
that is expected to be a string and to return the food argument plus ' tasted really good.'. Then, inside of the parentheses of console.log(), call the eat() function with the string bananas as the argument.

This is my code:

``` js
function eat (food) {
        return food + ' tasted really good.';
}
```

console.log(eat(bananas));

The verify function tells me that I'm doing something wrong, but I don't know what that might be. The name of my file is functions.js so that's not the problem.

All help appreciated!

**Comment by peterson5** [comment]
I solve it is like this
function eat(food){
return food + ' tasted really good.';
}
 console.log( eat('bananas'))
