### ISSUE TITLE
javascripting if-statement.js

### ISSUE THREAD

**Issue by johnnieb63** [nodeschool/discussions#648]
My solution doesn't pass the verify step. Please help…

var fruit = 'orange';
if(fruit.length > 5) {
  console.log('The fruit name has more than five characters.');
} else {
  console.log('The fruit name has less or equal than five characters.');

**Comment by davenelson** [comment]
Also note that there must be a line following the last closing curly bracket.

**Comment by SomeoneWeird** [comment]
oops. my bad.

**Comment by jwithington** [comment]
I'm getting something weird, too: it's saying that the solution should be "14". 

![screenshot 2015-02-06 15 35 22](https://cloud.githubusercontent.com/assets/4213550/6089324/dcc09faa-ae15-11e4-8c91-2fac3aa6bbae.png)

**Comment by SomeoneWeird** [comment]
@jwithington Are you sure you've selected the correct repository?

**Comment by jwithington** [comment]
@SomeoneWeird Weeeeird...didn't realize that I couldn't just try to verify wherever I was in the directory. Thanks!

**Comment by SomeoneWeird** [comment]
Awesome!
