### ISSUE TITLE
arrays.js not working

### ISSUE THREAD

**Issue by a-ayyash** [nodeschool/discussions#652]
Hey all, 

It's driving me nuts here is my code

``` javascript
var pizzaToppings = ['tomato sauce', 'cheese', 'pepperoni'];
consle.log(pizzaToppings);
```

I also tried 

``` javascript
consle.log(pizzaToppings.toString());
```

to no avail. 

I know that I should move on, but I can't.

**Comment by TwinTailsMusic** [comment]
Hi all, having the same issue.
Code: 
```
var pizzaToppings = ['tomato sauce', 'cheese', 'pepperoni'];
console.log(pizzaToppings);
```

**Comment by SomeoneWeird** [comment]
@TwinTailsMusic hi! Are you sure you've selected the correct problem? Your code works for me.

**Comment by TwinTailsMusic** [comment]
@SomeoneWeird Hi, sorry - for some reason my text editor saved the file in a different folder so it wasn't being read. I moved the js file and it's working now, thanks :)

**Comment by SomeoneWeird** [comment]
Awesome!
