### ISSUE TITLE
Houston Chapter?

### ISSUE THREAD

**Issue by butchewing** [nodeschool/discussions#665]
Is anyone interested in starting a NodeSchool Chapter in Houston, Texas?

**Comment by martinheidegger** [comment]
@butchewing Are you still interested?

**Comment by butchewing** [comment]
Yes, I'm still interested.

**Comment by martinheidegger** [comment]
Tweeted about it: https://twitter.com/leichtgewicht/status/563605212099661825

**Comment by Sequoia** [comment]
@butchewing wanna get the ball rolling and start a chapter? The power is yours! :earth_americas:

**Comment by Sequoia** [comment]
@butchewing How did it shake out? Did you start a chapter?

**Comment by butchewing** [comment]
No, since we didn't bites in the community, I figured that there is not enough interest in my area yet. I'll try again later, perhaps.

**Comment by Sequoia** [comment]
Darn! Well if you still want to do it, consider:

1. Work thru learnyounode (and maybe javascripting & stream-adventure)
2. get a space (e.g. free library conf. room) w/projector for 3-4hrs
3. announce a free nodejs workshop on your local dev channels!

Optionally: get a sponsor to buy coffee (I did this out of pocket it was like $12).

This might get people out of the woodwork. Here's a simple slide-deck for a short intro, feel free to bite slice dice whatever: https://docs.google.com/presentation/d/1gglPKTFksL71B5hsh6-LtQp9lE4qBGedOfnzZMjxaV0/edit#slide=id.p

gl;hf! :smile_cat:
