### ISSUE TITLE
Learnyounode Exercie #6 Make it Modular - Error: does not export a single function

### ISSUE THREAD

**Issue by mattroyer** [nodeschool/discussions#666]
I've looked through other issues here and haven't been able to resolve this exercise. It runs great if I use "node program.js". And it matches the output they want. Just get the weird single function error. Any help would be greatly appreciated.

**OS**: Windows 8.1
**learnyounode**: 1.0.6

# My Code and Results

### mymodule.js

    module.exports = function(dir, filter, callback) {
      var fs = require('fs');
      var path = require('path');
      var files = [];

      fs.readdir(dir, function(err, list) {
        if(err) {
          return callback(err);
        }
        list.forEach(function(file) {
          if(path.extname(file) === "." + filter) {
            files.push(file);
          }
        });
        return callback(null, files);
      });
    }

### program.js

    var mymodule = require('./mymodule.js');

    mymodule(process.argv[2], process.argv[3], function(err, data) {
      if(err) {
        console.log("Got an error: " + err);
      }
      data.forEach(function(file) {
        console.log(file);
      });
    });

## Results

√ Submission results match expected
? Your additional module file [program.js] does not export a single function.You
 must use the `module.exports = function () {}` pattern.

FAIL

Your solution to MAKE IT MODULAR didn't pass. Try again!

**Comment by m-ruggeri** [comment]
I got this error as well, really no solution?

**Comment by Dheerajkumar01** [comment]
Same Problem 
![nodejsoutput](https://cloud.githubusercontent.com/assets/16423553/26357415/d04e28ee-3fec-11e7-8772-85eea95d0cd5.PNG)

[Node.zip](https://github.com/nodeschool/discussions/files/1022344/Node.zip)

**Comment by a0viedo** [comment]
If you have similar problems please open a new issue with the full description.
