### ISSUE TITLE
My First I/O

### ISSUE THREAD

**Issue by hoboneighbor** [nodeschool/discussions#696]
I'm trying the "My first I/O" exercise. So far I haven't been able to get the program to pass the default arguments at all. For the I/O exercise, I'm expecting a file path to be passed automatically, but when I print out the arguments with `console.log(process.argv)` I only get the first two, regardless of if I supply arguments or not:

    [ '/usr/local/Cellar/node/0.10.13/bin/node',
        '/my/path/to/nodeschool/learnyounode/program.js' ]

If I run either of the following, I get the same result.

    learnyounode run program.js
    learnyounode run program.js 1 2 "Hi"

If I run `node program.js 1 2 "Hi"` I can see all of the arguments.

I'm on a Mac, and confirmed that I'm in the correct exercise. Tried installing/running as su, uninstalling, reinstalling, installing the latest. I can see in the `exercise.js` file that the `testFile` is being set to `path.join(os.tmpDir(), '_learnyounode_' + process.pid + '.txt')` and I confirmed that this file exists.

**Comment by mdouglasbrett** [comment]
When you call console.log on process.argv, remember it will return an array - the third item in the array is where the arguments start.

If your program.js just contains
     
    console.log(process.argv);

and you run

    $ node program.js

you will get back:

    [ '/usr/path/to/node', '/Users/path/to/program.js' ]

Any arguments you supply, i.e. 

    $ node program.js 1 2 "Hi!"

you will get back:

     [ '/usr/path/to/node', '/Users/path/to/program.js', '1', '2', 'Hi!' ]

Arrays are indexed from 0, so arguments will start at process.argv[2]. When you are running the MY FIRST I/O exercise through the verifier, the learnyounode program will supply a test path as an argument. This means that when you are using process.argv in your solution, you will need to reference process.argv[2] to get that path.

I hope this makes sense!

Mike
