### ISSUE TITLE
Run learnyounode from command line (Windows)

### ISSUE THREAD

**Issue by shane-reaume** [nodeschool/discussions#7]
I was able to install using npm install -g learnyounode

What would be the easiest way to fire up?

**Comment by alexandrtovmach** [comment]
I had a similar problem. (Windows x64 and x86)
I decided this way:
1) npm install -g learnyouunode
2) created a shortcut for the nodejs.exe to the Desktop
3) in the properties of the shortcut>object>we add the path to where the learnyounode is installed, namely to the folder **bin**
3.1) if you installed so - **npm install -g learnyouunode**, then the path will be:

 **C:\Users\\** _your_name_ **\AppData\Roaming\npm\node_modules\learnyounode\bin**

3.2) if you installed to local directory - **npm install learnyouunode**, then the path will be:

_[path_to_local_directory]_**\node_modules\learnyounode\bin**

4) Finally in "object" property of shortcut must be:

[path_to nodejs]\node.exe [path_from_3.1or3.2]\node_modules\learnyounode\bin\learnyounode

Example:
D:\Server\nodejs\node.exe D:\Server\nodejs\node_modules\npm\node_modules\learnyounode\bin\learnyounode
![image](https://user-images.githubusercontent.com/28801003/27518942-7320a478-59f3-11e7-9cdb-2bc46360a940.png)

**Comment by ShuklaVijayKumar** [comment]
In my case it opens a window popup to "Run With". But not launching any node application.
