### ISSUE TITLE
Exercise 6 - Make It Modular (Your additional module file did not return an array with the correct number of elements)

### ISSUE THREAD

**Issue by sgoodgrove** [nodeschool/discussions#707]
I've read through a couple of responses here and I've actually solved my own issue, but I thought it was worth repeating as the error message makes no sense whatsoever.

Here is the output I was getting

Your submission results compared to the expected:

                 ACTUAL                                  EXPECTED

    "CHANGELOG.md"                      ==    "CHANGELOG.md"

    "LICENCE.md"                        ==    "LICENCE.md"

    "README.md"                         ==    "README.md"

    ""                                  ==    ""

===

    ✓ Submission results match expected
    ✓ Additional module file exports a single function
    ✓ Additional module file exports a function that takes 3 arguments
    ✓ Additional module file handles errors properly
    ✓ Additional module file handles callback argument
    ✓ Additional module file returned two arguments on the callback function
    ✓ Additional module file returned Array as second argument of the callback
    ✗ Your additional module file [Exercise6-module1.js] did not return an Array with the correct number of elements as the second argument of the callback

    # FAIL

    Your solution to MAKE IT MODULAR didn't pass. Try again!

My first file `Exercise6.js` looked like this:

```javascript
var ex6 = require('./Exercise6-module1.js');

ex6(process.argv[2], '.' + process.argv[3], function(err, data) {
    for(var i in data) {
	console.log(data[i]);
	}
    }
);
```
My module file `Exercise6-module1js` looked like this:

```javascript
module.exports = function(dirName, extension, callback) {
    var fs = require('fs');
    var path = require('path');

    var results = [];

    fs.readdir(dirName, function(err, data) {
	if (err) {
	    return callback(err);
	    }
	else {
	    for(var i in data) {
		var fileExtension = path.extname(data[i]);

		if (fileExtension == extension)
		    results.push(data[i]);
	    }
	    callback(null, results);
	}
    });
}
```

My problem with the error message `Your additional module file [filename] did not return an Array with the correct number of elements as the second argument of the callback` is that it does not describe the issue at all. As far as I'm concerned the code produced the correct results and works against the criteria (namely that it is the same as exercise 5, but "modular").

The actual issue in my case is that prefixing the extension with a full stop (`.`) should have happened in the module file to make the exercise pass... strange. For completeness here are the amended files:

`Exercise6.js`

```javascript
var ex6 = require('./Exercise6-module1.js');

ex6(process.argv[2], process.argv[3], function(err, data) {
    for(var i in data) {
	console.log(data[i]);
	}
    }
);
```

`Exercise6-module1.js`

```javascript
module.exports = function(dirName, extension, callback) {
    var fs = require('fs');
    var path = require('path');

    var results = [];

    fs.readdir(dirName, function(err, data) {
	if (err) {
	    return callback(err);
	    }
	else {
	    for(var i in data) {
		var fileExtension = path.extname(data[i]);

		if (fileExtension == '.' + extension)
		    results.push(data[i]);
	    }
	    callback(null, results);
	}
    });
}
````

**Comment by cmalcom** [comment]
+1 same thing here.  Thanks for the comment, I would struggled with this for much longer.

**Comment by martinheidegger** [comment]
@cmalcom @xasos @supermajic @sgoodgrove It would be great if one of you could offer a pull request at [learnyounode](https://github.com/rvagg/learnyounode/pulls) to improve the experience for others. In any case, I will close this issue because it seems answered. I hope thats okay.

**Comment by sgoodgrove** [comment]
@martinheidegger I'd love to contribute, I'll try to find the time.

**Comment by arauchfuss** [comment]
Still experiencing this problem on windows. Had to move the extension concat into the module.

Also the test breaks if you do any async file stat testing.

**Comment by Assisting** [comment]
@arauchfuss I have no idea why, but that worked. I was having this issue in Linux, so apparently it's a cross-platform problem.

**Comment by Boberoo** [comment]
I got the same strange error message, but this post helped me find my problem. I had cut and paste the code from the main program into the module but forgotten to change the process.argv[3] to the new function's parameter name.

**Comment by peterfiorito** [comment]
Hi, this 'issue' is still persistent; I had all the values and checks with the ok sign, but when running the 'verify' command it kept telling me that my module was not returning an array as the second value. Luckily I found this, just moved the prefixing of '.' in argv[3] to the module and passed all the checks.
The checks do look for correct prefix handling, but I was prefixing it in my main.js and the check was still passing (and finally throwing the aforementioned error in the last check).
