### ISSUE TITLE
Issues to run the tutorial

### ISSUE THREAD

**Issue by pk16** [nodeschool/discussions#730]
npm install works fine, but i cant run using "learnyounode"
the output is

learnyounode: command not found

**Comment by mikeyferg** [comment]
I am having the same issue on a mac.  I executed npm install learnyounode -g.

My output for npm config get prefix is "/Users/mikey/.node".

Node -v is "v0.10.35"

NPM -v is "1.4.28"

**Comment by martinheidegger** [comment]
@mikeyferg @pk16 Just out of curiosity: Did you install nodejs using the installer or homebrew? Also: Did you update Node.js recently?

**Comment by mikeyferg** [comment]
I used NVM.  I have figured out the issue.  My original installation didn't have the appropriate permissions.  Thanks!
