### ISSUE TITLE
Learn Your Node - Filtered LS - help

### ISSUE THREAD

**Issue by gcmicah** [nodeschool/discussions#731]
Hi, I'm doing Learn Your Node - Filtered LS exercise. I started with just listing all the files of a directory. Below is my code. The outcome was it printed nothing. Can anyone please tell me where I got wrong? Thank you. 

> var fs = require('fs');

> function listFiles(callback) {
	fs.readdir("C:\\javascripting\\", function doneListing(err, files) {
		for( i=0; i<=files.length(); i++) {
			allFileNames = files[i] + "\n";
		}
		callback();	
	});
}

> function logFiles() {
  console.log(allFileNames)
}

![capture](https://cloud.githubusercontent.com/assets/9957527/5294449/527dfc50-7bd1-11e4-8b79-daf02f7bfe1a.JPG)

**Comment by martinheidegger** [comment]
@gcmicah Did you have any progress? Do you need more help?

**Comment by 11cs103** [comment]
![1](https://cloud.githubusercontent.com/assets/5787039/8306984/af905432-19d9-11e5-9b7b-29a04cc916cc.png)
![2](https://cloud.githubusercontent.com/assets/5787039/8306986/afbb4a84-19d9-11e5-9536-4aef6168b87b.png)

the original solution by learnyounode tells us to use process.extname and also foreach is used. I wrote the code without using those two and the i got a pass.
