### ISSUE TITLE
NPM install command not working

### ISSUE THREAD

**Issue by endergonic** [nodeschool/discussions#752]
When I enter $ npm install -g git-it  nothing happens. I'm running this on Windows using the 64bit MSI installer.

**Comment by martinheidegger** [comment]
@endergonic The regular cmd.exe usually doesn't have the node Path setup properly. See: https://github.com/nodeschool/organizers/issues/115#issuecomment-70531745

**Comment by dufagundes** [comment]
@finnp you got it wat I was doing wrong, I just dont understand why there is a Nodejs cmd.

**Comment by SomeoneWeird** [comment]
Please open another issue. This one is nearly a year old.
