### ISSUE TITLE
All exercises are false where the where first true

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#767]
Hello, 

I do the exercises in the nitrious.io site,
After I accedently left the page all the exercises are failing except the exercise where I was working on that moment. 

Anyone a idea how to solve this ?

Roelof

**Comment by martinheidegger** [comment]
@roelof1967 This seems to have been an issue with how you used the command line, right?

**Comment by roelof1967** [comment]
Yes, now I know more about how the workshops work,
