### ISSUE TITLE
Looping through arrays

### ISSUE THREAD

**Issue by jhbrewer264** [nodeschool/discussions#773]
Hi, 

I am trying to figure out the looping-through-arrays lesson and would appreciate some help.  Here is what I have so far:

var pets = ['cat', 'dog', 'rat']
for (var i = 0; i < 1; i++) {
    pets[i] = pets[i] + 's'
}
console.log(pets)

I assume the issue is with how I set up the initial for loop -- for (var i = 0; i < 1; i++) -- but I am not sure what the correct setup would look like.  Thank you in advance for any help!

**Comment by Jordantcarlisle** [comment]
@martinheidegger, this helped me as well. However, I'm having trouble understanding why pets.length works, because I don't know what it's value is as it's passing through. Does it represent the number of strings in the array? Or the length of all the strings for the pets array?

**Comment by jkbits1** [comment]
@Jordantcarlisle It's your first option :+1:  pets.length is the number of strings in the array
