### ISSUE TITLE
Recommended reading material for make it modular?

### ISSUE THREAD

**Issue by bobonthenet** [nodeschool/discussions#782]
I had a lot of trouble completing the Make it Modular lesson and feel like I still don't quite understand it all.  Would anyone recommend some reading material for better understanding the concepts in this lesson?

**Comment by martinheidegger** [comment]
@bobonthenet Do you feel comfortable is [callback hell](http://callbackhell.com) enough or do you need more help?

**Comment by khalifenizar** [comment]
@martinheidegger Maybe a callbacks/asynchronous workshopper might be in order.

**Comment by martinheidegger** [comment]
@khalifenizar `javascripter++`
