### ISSUE TITLE
How to Run Workshops

### ISSUE THREAD

**Issue by CruzinToVictory** [nodeschool/discussions#787]
I've installed a workshop from this site: http://nodeschool.io/#workshopper-list 

For example, I ran this command:

npm install -g javascripting

The output I got was essentially just a folder path to an AppData folder. I'm now trying to run the workshop using this command:

npm javascripting

And I just get what looks like a help documentation with command options. Any ideas?

**Comment by ChaosTherum** [comment]
Having this same issues on windows would be great to find out why. Thanks.

**Comment by ghutchinson** [comment]
Also having the same issue, any help here appreciated.

**Comment by martinheidegger** [comment]
Hmm. Reading over the issue again. I am not quite sure but could there be an understanding issue? `npm i javascripting -g` installs javascripting. You need to run `javascripting` afterwards in the command line to actually start it.

**Comment by ghutchinson** [comment]
Thanks Martin, indeed, after some head scratching i looked in the C:\Users\<youraccount>\AppData\Roaming\npm\ directory and found the javascript.cmd file which i then executed from the the command line.

I guess i was expecting a little more guidance post install that I needed to go there and execute it myself, not the most common install directory location i have seen!

Cheers

**Comment by martinheidegger** [comment]
@ghutchinson the installation process is very familiar for people using a linux/unix terminal but indeed for windows users it is less than optimal: https://github.com/nodeschool/organizers/issues/115

**Comment by chrisziegler** [comment]
Just to clarify for windows powershell users, one apparently needs to cd to \AppData\Roaming\npm\ and then type functional-javascript-workshop.cmd <enter> in the command line; 'javascripting does not work for me.
