### ISSUE TITLE
javascripting array-filtering.js

### ISSUE THREAD

**Issue by david-wayne-walker** [nodeschool/discussions#790]
I can't seem to get my code to work.  I am just learning javascript and need help.
here is my code for the array-filtering.js

```JavaScript
var numbers = [1,2,3,4,5,6,7,8,9,10];
var filtered = numbers.filter(evenNumbers(number)

function evenNumbers (number) {
	return number % 2 = = 0;
}
console.log(filtered);
```

**Comment by mykhael** [comment]
@BrotherBenson close this issue

**Comment by BrotherBenson** [comment]
@mykhael I didn't open it.

**Comment by mykhael** [comment]
@BrotherBenson wrong mention, sorry about that

**Comment by BrotherBenson** [comment]
@mykhael No problem. Have a good day!

**Comment by ManfredNeustifter** [comment]
var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
var filtered = numbers.filter(function(evens){
  return(evens % 2 === 0);
});
console.log(filtered);

**Comment by SomeoneWeird** [comment]
@ManfredNeustifter thanks, but please don't post solutions in other peoples issues :)
