### ISSUE TITLE
problem with expressworks' hello world. Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by RYOHOI** [nodeschool/discussions#798]
- express installed(v4.9)
- run with sudo 
- only console.log line in the code

Still:
![screen shot 2015-01-02 at 6 24 38 pm](https://cloud.githubusercontent.com/assets/5955526/5595405/a39e8b94-92ac-11e4-83f4-192414092111.png)

**Comment by roelof1967** [comment]
May we also see the code ?

**Comment by RYOHOI** [comment]
don't think it's necessary. It's more like environment setting issue.

Well, as I said, the code is as simple as "console.log ("hello world ")"

**Comment by roelof1967** [comment]
Then you are on the wrong way. 
On the expressworks lesson you need to make a webserver which displays hello world.
Read carefully the hints for that.

**Comment by RYOHOI** [comment]
I finally figured it out by following expressjs' official guide: http://expressjs.com/starter/installing.html

**Comment by martinheidegger** [comment]
@RYOHOI Gratulations! It would be awesome to share your biggest understanding problem here so we can improve the workshopper.

**Comment by RYOHOI** [comment]
The hints just said nothing about including express module & creating package.json file thing, right?

And before I stumbled upon this issue, I missed out installing express-generator or I should restart so that I can run `express --version`

These distressed me for 2 days. Again, I'm back and figuring things out : )

**Comment by RYOHOI** [comment]
One more irrelevant question, how can I add label to a issue. Didn't find this utility since then.

**Comment by SomeoneWeird** [comment]
Only people with write access to the repository can add labels.

**Comment by RYOHOI** [comment]
@SomeoneWeird Thanks the note ; )
