### ISSUE TITLE
how do i open two command prompts?

### ISSUE THREAD

**Issue by grwqk6** [nodeschool/discussions#799]
help?

**Comment by martinheidegger** [comment]
Depending on the operating system there are various ways:

Mac (Terminal / or [iTerm](http://iterm2.com/)):
- Command + N (Terminal in new window)
- Command + T (Terminal in new tab)

Windows:
Start the `cmd.exe` again should start a new command prompt. 
[Look here](http://www.tomshardware.com/forum/67418-63-short-command-prompt) if you want to know shortcuts.

**Comment by martinheidegger** [comment]
@grwqk6 Did this help you?
