### ISSUE TITLE
makemehapi : hello hapi problem 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#801]
Hello, 

I work on Nitrious.io and Im only allowed to use port 3000 for http and port 9500 for https.
So at this moment I never can solve the hello hapi problem where the url and the port are random.

How can I solve this ? Maybe changed the exercise ? 

Roelof

**Comment by martinheidegger** [comment]
@roelof1967 How about starting to work locally :stuck_out_tongue: ? In all seriousness: Workshoppers at the moment assume a random port which should work at 90% (my estimate) of the time, but there are surely cases where [it picks a random port](https://github.com/rvagg/learnyounode/blob/master/lib/rndport.js) that is already used (8080, 8000 are hot candiates) and then you would need to restart the test and hope it chooses another port next time. (Sort of random behaviour). We should probably change the system to use something like [get-port](https://github.com/sindresorhus/get-port)

**Comment by roelof1967** [comment]
Oke, Is windows 7 or a Linux distro a good choice ? 

Wierd, I tried get-port and I see this output :  

action@intense-motor-47-180577:~/workspace$ node port.js                                                                                                                               
32968                                                                                                                                                                                  
action@intense-motor-47-180577:~/workspace$ node port.js                                                                                                                               
59728                                                                                                                                                                                  
action@intense-motor-47-180577:~/workspace$ node 

port.js                                                                                                                               
49766      

action@intense-motor-47-180577:~/workspace$ node port.js                                                                                                                               
32968                                                                                                                                                                                  
action@intense-motor-47-180577:~/workspace$ node port.js                                                                                                                               
59728                                                                                                                                                                                  
action@intense-motor-47-180577:~/workspace$ node port.js                                                                                                                               
49766                

Can it be that localhost is somewhere hard-coded somewhere ?

Roelof

**Comment by martinheidegger** [comment]
With node-js I would prefer `Linux`. 

It seems like the ports are only "blocked from outside" but it seems Nitrious does allow to connect to them internally (so: they are not prohibited)

**Comment by roelof1967** [comment]
oke, and what does that mean for the exercises ? 
And use the workshopper uses localhost by default or does it look for the server name. 

I will look for a good Linux distro to use ?

Roelof

**Comment by roelof1967** [comment]
Another question.  If I use Linux and sublime text. Which plugin can I use the best to make it fun to programm in node.js

**Comment by roelof1967** [comment]
I found the answer to the timeserver problem . I hardcoded the port to 3000. When I changed it to the right one everything worked.
