### ISSUE TITLE
learnyounode : timeserver

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#802]
Hello, 

When I try to solve this one I Always see this error message : 

✗ Error connecting to localhost:28561: connect ECONNREFUSED

Now this can be two things : 

1) Because im working on nitrious.io localhost must be the url of my nitrious box 
2) Because im on nitrious.io as far as I know I can only use 3000 for http and 9500 for https 

What can I do to make this work ?

Roelof

**Comment by martinheidegger** [comment]
See my answer in https://github.com/nodeschool/discussions/issues/801#issuecomment-68638202
