### ISSUE TITLE
stream-adventure HTML STREAM problem to solution mismatch

### ISSUE THREAD

**Issue by Firexion** [nodeschool/discussions#804]
The problem text says to do this:
Your program will get some html written to stdin. Convert <b>all</b> the inner html to upper-case for elements with a class name of "loud".

Specifying this should happen for all instances of the loud class, however the solution provided (and the example provided) only work with the first instance of the class.

I propose either changing the problem text to indicate this should be solved for only the first instance of the loud class or to update the example and solution to use selectAll instead of select.
Thank you

**Comment by martinheidegger** [comment]
@Firexion Thank you for your response. Maybe you could work on a pull request [in the stream-adventure repository](https://github.com/substack/stream-adventure/tree/master/problems/html_stream) that shows how you think it best to be?

**Comment by Firexion** [comment]
Sure thing! I made a new pull request for this.
https://github.com/substack/stream-adventure/pull/103

**Comment by martinheidegger** [comment]
:+1: Awesome
