### ISSUE TITLE
node doesn't know about ES6 features

### ISSUE THREAD

**Issue by dKab** [nodeschool/discussions#806]
I tried to run this line in my terminal: 
node -e 'function test(...args) { console.log(args.join(' ')) } test('this' 'is' 'a' 'test');'
and I got SyntaxError: Unexpected token .
My node version is 0.10.35 , but apparently it doesn't recognize REST feature syntax (the "...args" part) and I'm curious why is that? Given the fact that when I use this syntax to solve count-to-6 workshop tasks it works alright and it runs in the same environment, right? I mean when I run 'count-to-6 verify file.js' it uses nodejs installed on my machine to evaluate the script. Am i missing something here?

**Comment by sudodoki** [comment]
The stable version of node has ES6 under `--harmony` feature flag - you can see all the supported features in it in [compat table](http://kangax.github.io/compat-table/es6/#node). But workshop itself [uses](https://github.com/domenic/count-to-6/blob/master/package.json#L25) transpiler called [traceur](https://github.com/google/traceur-compiler). This enables transpiling es6 code to be able to run on current es5 environments. There're other tools - see [es6-tools](https://github.com/addyosmani/es6-tools) for more info.
