### ISSUE TITLE
Socket.io in Vagrant VirtualBox hosted on Win8 

### ISSUE THREAD

**Issue by virologicbridge** [nodeschool/discussions#808]
I've tried multiple vagrant boxes, and tried putting the following in the vagrant files
------------
config.vm.provider "virtualbox" do |v|
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
end
------------
I cannot get the socket.io package to completely work. I'm going through socket.io's chat example and the socket.on event doesn't seem to fire off?  

Is there anyone out there with Win8 using Vagrant that has stream.io working 100% and did you have to do anything special?  Below is my code, I get notified that a user connected, but i dont get their message. 

Many Thanks for any help!

index.js ----------------------------------------------------------------------------------------------------
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket){
  console.log('a user connected');
  //console.log(socket);
  socket.on('chat message', function(msg){
    console.log('message: ' + msg);
  });
});

http.listen(8000, function(){
  console.log('listening on *:8000');
});
```
index.html ---------------------------------------------------------------------------------------------------
```html
<!doctype html>
<html>
  <head>
    <title>Socket.IO chat</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font: 13px Helvetica, Arial; }
      form { background: #000; padding: 3px; position: fixed; bottom: 0; width: 100%; }
      form input { border: 0; padding: 10px; width: 90%; margin-right: .5%; }
      form button { width: 9%; background: rgb(130, 224, 255); border: none; padding: 10px; }
      #messages { list-style-type: none; margin: 0; padding: 0; }
      #messages li { padding: 5px 10px; }
      #messages li:nth-child(odd) { background: #eee; }
    </style>
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.js"></script>
<script>
  var socket = io();
  $('form').submit(function(){
    socket.emit('chat message', $('#m').val());
    $('#m').val('');
    alert($('#m').val(''));
    return false;
  });
</script>
  </head>
  <body>
    <ul id="messages"></ul>
    <form action="">
      <input id="m" autocomplete="off" /><button>Send</button>
    </form>
  </body>
</html>
```

**Comment by virologicbridge** [comment]
<!doctype html>
<html>
  <head>
    <title>Socket.IO chat</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font: 13px Helvetica, Arial; }
      form { background: #000; padding: 3px; position: fixed; bottom: 0; width: 100%; }
      form input { border: 0; padding: 10px; width: 90%; margin-right: .5%; }
      form button { width: 9%; background: rgb(130, 224, 255); border: none; padding: 10px; }
      #messages { list-style-type: none; margin: 0; padding: 0; }
      #messages li { padding: 5px 10px; }
      #messages li:nth-child(odd) { background: #eee; }
    </style>
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.js"></script>
<script>
  var socket = io();
  $('form').submit(function(){
    socket.emit('chat message', $('#m').val());
    $('#m').val('');
    alert($('#m').val(''));
    return false;
  });
</script>
  </head>
  <body>
    <ul id="messages"></ul>
    <form action="">
      <input id="m" autocomplete="off" /><button>Send</button>
    </form>
  </body>
</html>

**Comment by swreeser** [comment]
Could you post the results of `node -v` and `npm -v`?

**Comment by finnp** [comment]
The problem is that your client side code tries to access the form element, which is not loaded yet, when the script is running. Simply move the script behind the form element to make it work. Alternatively wrap your code into 
```js
$(function() {
 ... your code here
})
```
Then it will only be run, when the page is loaded.

By the way you seem to have followed the help-page on socket.io. Please post an issue on https://github.com/Automattic/socket.io-website/issues to let them know that there is an error (or a confusion) in their getting started guide.

**Comment by finnp** [comment]
Please let us know if this helped you :smile: By the way your npm version is a bit old, you can install a new one with `npm install npm -g`
