### ISSUE TITLE
issue with learnyounode process

### ISSUE THREAD

**Issue by moshebeeri** [nodeschool/discussions#809]
when I iterate and test my solution I am getting reasonable results, that I might believe to be true.
then when I am verifying my solution I get only the results without the test case (the command line that was used to test) and therefor can't refine my results.
for example the http client 
```javascript
var options = {
  hostname: process.argv[2],
  port: 80,
  path: '/',
  method: 'GET'
};

var req = http.request(options, function(res) {
  // console.log('STATUS: ' + res.statusCode);
  // console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', console.log);
});

req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});

req.end();
```
when running it via 'node httpclient.js google.com' I get the html from goole.com, believing I have solved the challenge.
but running it via 'learnyounode verify httpclient.js' I get:
   "problem with request: getaddrinfo ENOTFOUND" !=    "Boil-over" 
 !=    "Oldies"                           .....
                                 

without any option to understands whats went wrong :-(
I really complain about the process

**Comment by davecocoa** [comment]
In general, workshops will give you more output if you use `run` instead of `verify`, for instance your `console.log`s would not be suppressed as they are when using `verify`. In this particular case - those logs still won't be shown because the error happens before those lines are reached. I would recommend using `learnyounode run httpclient.js` and adding a `console.log` of either `options` or `process.argv[2]`.

**Comment by moshebeeri** [comment]
Thanks for the tips, it seems that using run is better for testings then using "node script.js"
but it is not intuitive for us as developers not to run programs directly.
I think that in case of failure, in the verify process, learnyounode should call run or a least suggests that on screen while printing the command line arguments been used.
