### ISSUE TITLE
makemehapi : handler ( 404 error) 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#814]
Hello, 

Im now trying to make the handling exercise 

I have this : 

```JavaScript
var Hapi = require('hapi');

var server = new Hapi.Server();

server.connection({
    host: 'localhost',
    port: Number(process.argv[2] || 8080)
});

server.route({
    method: 'GET',
    path: '/',
    handler: {
        file: 'index.html'
    }
});

server.start();
```

but as soon as I do makemehapi run I see a 404 error 

Roelof

**Comment by roelof1967** [comment]
Solved it by talking to the maker of this tutorial .
I misread some things

**Comment by martinheidegger** [comment]
@roelof1967 Maybe other people will read your entry because they have the same problem. What was your misreading/understanding?

**Comment by roelof1967** [comment]
The biggest one that I not have read good enough to see that I had to change the path and the other was not understanding that I need to make the html file of my own.
