### ISSUE TITLE
Help on juggling http

### ISSUE THREAD

**Issue by chrisranderson** [nodeschool/discussions#815]
This code will get everything needed, but it is out of order. How do I run the asynchronous functions in series?
```javascript
var http = require('http');

var urls = [];
urls.push(process.argv[2]);
urls.push(process.argv[3]);
urls.push(process.argv[4]);

// http.get(urls[0], handleResponse)

blah(http.get, urls[0], 
blah(http.get, urls[1], 
blah(http.get, urls[2])));

function blah(fn, url, callback){
	callback = callback || function(){};
	fn(url, handleResponse);
	callback();
}

function handleResponse(response){
	var body = '';
	response.on('data', function moreData(data) {
		body += data;
	})
	response.on('end', function(){
		console.log(body.length);
		console.log(body)
	})
}
```

I know this is the wrong way to do it. What I would like to do is write a function that takes an array of functions, and runs them in order.

**Comment by chrisranderson** [comment]
I guess this is what I'm going for:

```javascript
function Queue(){
	this.fns = [];
}

Queue.prototype.add = function(fn) {
	this.fns.push(fn);
}

// Runs every function in order.
Queue.prototype.runAll = function() {

}

var queue = new Queue();

urls.forEach(function(url, index){
	queue.add(function(){http.get(url, handleResponse)})
});

queue.runAll();
```

What would I fill in for the runAll function?

**Comment by roelof1967** [comment]
You do not need to run it in series. they all get run in the same time.
Look at how the makeitmodular exercise. I could do it almost the same way.

**Comment by chrisranderson** [comment]
Never mind - I got it figured out. Rather than trying to make it synchronous, I just made checks every time a response was finished. Thanks @roelof1967 for the response.
