### ISSUE TITLE
stream-adventure - lines problem 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#817]
Hello, 

I try to solve this problem but I do not have a clue how I can count  how many lines and which line im working now. 

I tried with a line count_lines++ but it counts the chunks not the lines 

Roelof

**Comment by martinheidegger** [comment]
How about counting the lines of a chunk and adding that number to the total amount of lines :wink:

**Comment by roelof1967** [comment]
That can be a solution as soon as I figured out how to do that. 
data,length does not do the trick . Then I see the total amount of characters. 

Roelof

**Comment by martinheidegger** [comment]
I think you solved that one when you worked on: https://github.com/rvagg/learnyounode/blob/master/exercises/my_first_io/problem.md

**Comment by roelof1967** [comment]
Thanks, then i have to figure out how to count the output lines.
I have now this : 

~ ~ ~ 

var through = require('through');
var split = require('split');

var lines_count = 0 ;

var tr = through(function write(data) {
        split(data);
        },
    function end () {
        this.queue(null)
    });

process.stdin
    .pipe(split())
    .pipe(through(function (line) {
        console.dir(line.toString());
    }))
;

process.stdin.pipe(tr).pipe(process.stdout);

~ ~ ~ 

I have found out that I can also count the lines by adding count_lines++ in the split function

**Comment by roelof1967** [comment]
Solved it by looking at the answer
