### ISSUE TITLE
stream-adventure  concat  : complete confusing 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#819]
Hello, 

I have read the hint several times but still have no clue how to solve this .
The example is one who do something to a json stream and I have also no idea what the example exactly does.

Someone who can point me in the right direction or with more info how concat - stream works

**Comment by martinheidegger** [comment]
hello @roelof1967 
the [documentation of `contact-stream`](https://github.com/maxogden/concat-stream#var-writable--concatopts-cb) is fairly clear to me if I read it. I understand it like:

`concat-stream` is a module that collects all data and then gives you a buffer that contains all that data in a callback. 

So:

```
var concat = require('concat-stream')
var myGreatConcatinator = concat(function (allData) {
   // do something with it...
})

readableStream.pipe(myGreatConcatinator)
```

Is what I understand from the docs of `concat-steam`. Also I understand that the task is to reverse it so `console.log(reverse(allData))`. I am not quite sure what you are struggling with tbh.

**Comment by roelof1967** [comment]
Then the hints of this exercise are very confusing.
