### ISSUE TITLE
Beginner

### ISSUE THREAD

**Issue by 0syntrax0** [nodeschool/discussions#821]
I just installed Node.Js, I have windows, how do I know that it works? Is this an apple only thing?

**Comment by martinheidegger** [comment]
Open the command prompt and enter 'node' or 'npm'. Some windows/node combinations seem to have problems setting the path variables properly. What have you installed?

**Comment by 0syntrax0** [comment]
I downloaded the installer from the nodejs website.
 I have a WAMP server installed in my PC, where or how would I make it, so that when I create something as in the video tutorials where ppl save files and it runs in their local machine, I want that too.

I'm just following tutorials, but nobody talks about those sorts of setups, everybody jumps right in or will Node.JS will create files for me? I know what it's for, but i'm still unsure on to how it does all of that.

**Comment by martinheidegger** [comment]
@0syntrax0 Node.js (and all of the workshoppers at NodeSchool) work completely without WAMP. After you installed Node.js you should have two new commands in the [Command Prompt](http://en.wikipedia.org/wiki/Cmd.exe). One is `node` the other `npm`. With `node` you can run node scripts, with `npm` you can download/install other packages that you might need for your work. The list of [workshoppers](http://nodeschool.io/#workshopper-list) all specify something like `npm install learnyounode --global`. Entering this in your command like will make new commands available in your command prompt! (In the example: `learnyounode`). 

On mac this workflow doesn't have any problems except that you might need to add `sudo` in front. But some versions/combinations of Windows have issues in the setup process. Please look at the open & closed windows issues to see if they can help you: [here](https://github.com/nodeschool/discussions/issues?q=label%3Awindows+).
