### ISSUE TITLE
javascripting functions script is failing verification...not sure why 

### ISSUE THREAD

**Issue by infomaven** [nodeschool/discussions#822]
I've created a file named "functions.js". Content looks like this>
function eat(food) {
  return food + ' tasted really good';
}

console.log( eat("bananas") );

When I run $javascripting verify functions.js, it gives the classic  failure message 
 O-oh, something isn't working.
 
However when I run my code in Chrome Developer tools from the javascript console, it prints out the expected string. 

What is keeping my code from passing in the workshop's verify function?

**Comment by roelof1967** [comment]
I see one difference with my own working one. 

What if you changed "bananas"  to 'bananas' 

Roelof

**Comment by a0viedo** [comment]
hey @infomaven, what does does print if you run `node functions.js` in the terminal?

**Comment by infomaven** [comment]
@a0viedo Hi, I seem to have lost all my Node and tutorial files from this computer. 
I never got to try running functions.js in the regular terminal. It looks like I'm going to have to start over from scratch.

**Comment by martinheidegger** [comment]
@infomaven Please let us know if you need any help. For the meanwhile I hope you don't mind if I close this issue.

**Comment by infomaven** [comment]
Thanks much!
