### ISSUE TITLE
learnyounode - httpfileserver  :  No output 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#823]
I have this solution : 

~~~

var http = require ('http');
var fs = require('fs')

var server = http.createServer (function callback(request, respons) {
  fs.createReadStream (process.argv[3], function callback(error, data) {
    if (err) {
      return console.error('Er is een fout opgetreden')
      }
    data.pipe(respons)
   })
});
                   
server.listen(process.argv[2])

~~~

but when I do learnyounode run  I see a cursor and nothing else.

**Comment by martinheidegger** [comment]
'learnyounode run' starts your code without extra output. Your code is a webserver so to see what it's doing you need to either log something or connect to it with a web browser or curl.

**Comment by roelof1967** [comment]
oke, so I must do learnyounode run 3000 test.txt   ?

**Comment by martinheidegger** [comment]
That is because you mistook the api use of ['fs.createReadStream'](http://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options)

**Comment by roelof1967** [comment]
oke, i misunderstood it then. Is this a good example : https://docs.nodejitsu.com/articles/advanced/streams/how-to-use-fs-create-read-stream

**Comment by roelof1967** [comment]
I have now this : 

~~ ~

var http = require ('http');
var fs = require('fs')

http.createServer(function(req, res) {
  
  var filename = __dirname+ process.argv[3]
  var readStream = fs.createReadStream(filename);

  readStream.on('open', function () {
     readStream.pipe(res);
  });

  readStream.on('error', function(err) {
    res.end(err);
  });
}).listen(process.argv[2]);

~ ~ ~ 

then I see this error 

~ ~ ~ 

http.js:851
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (http.js:851:11)
    at ServerResponse.OutgoingMessage.end (http.js:985:16)
    at ReadStream.<anonymous> (/home/roelof/node_exercises/learnyounode/httpfileserver.js:16:9)
    at ReadStream.emit (events.js:95:17)
    at fs.js:1513:12
    at Object.oncomplete (fs.js:107:15)
✗ Error connecting to http://localhost:40856: socket hang up

~ ~ ~

when I swap the process.argv then I see this message ; 

~ ~ ~

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1132:5)
    at Object.<anonymous> (/home/roelof/node_exercises/learnyounode/httpfileserver.js:16:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
✗ Error connecting to http://localhost:5727: connect ECONNREFUSED

~ ~ ~

**Comment by roelof1967** [comment]
solved this one. There was a error in this line :  var filename = __dirname+ process.argv[3]
