### ISSUE TITLE
Why doesnt this PASS??!!  

### ISSUE THREAD

**Issue by joshmalouf** [nodeschool/discussions#833]
I get positive test results on the the "Making it Modular" workshop on every test except the final results..

what am i doing wrong?

***program file: "asyncFilter2.js"****
```JavaScript
var aSync = require('./asyncModule');

aSync.asyncRead;
```

***module containing file: "asyncModule.js"****
```JavaScript
module.exports = asyncRead

var fs = require('fs');
var pth = require('path');



function asyncRead (dirName, fileExt, listToConsole){
		fs.readdir(dirName, function (err, list){
			var filteredList = [];
			if (err) {
			 return listToConsole(err);
			}else{
				for(var i = 0; i < list.length; i++){

					if(pth.extname(list[i]) == '.' + fileExt){
						filteredList.push(list[i]);
					}
				}
			  return listToConsole(null, filteredList);
			}
		});
}

function listToConsole (err, list){
	if(err){
		console.log("Fuck Up!!");
	}else{
		for(i = 0; i < list.length; i++){
		console.log(list[i]+"\n");
		}
	}
}
```

**Comment by martinheidegger** [comment]
Hello @joshmalouf

There are two things that are common mistakes when working with javascript that happened here: You defined an argument `listToConsole` and a method with the same name. In this constellation the argument takes precedence! So you need to pass a method pointer to `asyncRead`.

The second is that the module that you created does only [exports](http://nodejs.org/api/modules.html#modules_modules) one method but the method is not used and you tried to access the property of your module `aSync.asyncRead;` which doesn't exist.  

To fix both problems you have to take care of two rather simple steps:

1. call your module's method: `aSync.asyncRead` -> `aSync(..)` and
2. make sure that listConsole is passed to `aSync` like this `aSync(..., listToConsole)`

**Comment by joshmalouf** [comment]
I appreciate the help... obvious newbie here so looking for all the help i can get..

**Comment by martinheidegger** [comment]
The point about NodeSchool is so you can learn. We have all been newbies here once. Have patience with yourself and the volunteers that try to help here and I am sure you progress swiftly!

**Comment by martinheidegger** [comment]
@joshmalouf By the way: Did the explanation help? Do you need more information?

**Comment by moadqassem** [comment]
hey @joshmalouf  yeah sometimes it's a little bit tricky specially if someone didn't follow the instructions in a every single detail because node school has a very strict scenario that you need to apply successfully and step by step, however it appears from your code that you are logging in the Module file which is wrong based on the workshop the function in the module needs only to provide the data and in the second file(the main program) you have to log them, if you need the solution I can give it to you, however it would be better to work it out a little bit more ;)

**Comment by joshmalouf** [comment]
@martinheidegger  yes the explanation did help and i have a much better grasp of how to use modules and node in general.

@moadqassem thanks for the offer but i ultimately worked through to the solution on my own.

In reality after finding the solution to this exercise i proceeded through the rest of the exercises very quickly and seemingly easily.  Now i am working on some of my own ideas with node.

Thanks again for the help.

**Comment by martinheidegger** [comment]
@joshmalouf Awesome! Closing this issue :)
