### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by abisivam2304** [nodeschool/discussions#834]
how to create a node module of my own and install it using npm

**Comment by martinheidegger** [comment]
Hello @abisivam2304!

There is a page that teaches you that [here](https://docs.npmjs.com/getting-started/creating-node-modules)

**Comment by martinheidegger** [comment]
@abisivam2304 Does that answer your question?

**Comment by abisivam2304** [comment]
hi,

Yes yes absolutely! Thank yu!

On Tue, Jan 20, 2015 at 12:52 AM, Martin Heidegger <notifications@github.com

**Comment by martinheidegger** [comment]
Awesome!
