### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by Ij888** [nodeschool/discussions#835]
Installing learnyounode does not place the app in the file I created. How do I make the app reside in the specific file I made for learnyounode?

**Comment by StewartLevine** [comment]
installing learnyounode installs the files in your appdata directory and I wouldn't mess with that. I believe you should be able to make a directory in another location (pretty much anywhere) and place your files there. Just run learnyounode from the directory where you placed your files.

**Comment by martinheidegger** [comment]
@Ij888 Does this answer your question?

**Comment by Ij888** [comment]
yes it does, thanks.
