### ISSUE TITLE
javascripting menu error

### ISSUE THREAD

**Issue by StewartLevine** [nodeschool/discussions#836]
I am able to select individual chapters at the command line - ex. javascripting select STRINGS but when I run javascripting and use the menu, it crashes everytime I select a chapter. 

C:\Users\slevine\AppData\Roaming\npm\node_modules\javascripting\node_modules\adv
enture\node_modules\terminal-menu\node_modules\charm\index.js:54
          input.destroy();
                ^
TypeError: Object #<Transform> has no method 'destroy'
    at Stream.<anonymous> (C:\Users\slevine\AppData\Roaming\npm\node_modules\jav
ascripting\node_modules\adventure\node_modules\terminal-menu\node_modules\charm\
index.js:54:17)
    at Stream.g (events.js:175:14)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Stream.Charm.end (C:\Users\slevine\AppData\Roaming\npm\node_modules\javas
cripting\node_modules\adventure\node_modules\terminal-menu\node_modules\charm\in
dex.js:107:10)
    at Menu.close (C:\Users\slevine\AppData\Roaming\npm\node_modules\javascripti
ng\node_modules\adventure\node_modules\terminal-menu\index.js:126:16)
    at Menu.<anonymous> (C:\Users\slevine\AppData\Roaming\npm\node_modules\javas
cripting\node_modules\adventure\lib\menu.js:41:14)
    at Menu.EventEmitter.emit (events.js:98:17)
    at Menu.ondata [as _ondata] (C:\Users\slevine\AppData\Roaming\npm\node_modul
es\javascripting\node_modules\adventure\node_modules\terminal-menu\index.js:215:
18)
    at Transform._transform (C:\Users\slevine\AppData\Roaming\npm\node_modules\j
avascripting\node_modules\adventure\node_modules\terminal-menu\index.js:50:18)
    at Transform._read (C:\Users\slevine\AppData\Roaming\npm\node_modules\javasc
ripting\node_modules\adventure\node_modules\through2\node_modules\readable-strea
m\lib\_stream_transform.js:184:10)

**Comment by a0viedo** [comment]
Hi @StewartLevine, what version of node are you using (run `node -v` in your terminal? You're using Windows, Linux or OSX?

**Comment by StewartLevine** [comment]
I'm using 3.4.8 in Win7

**Comment by martinheidegger** [comment]
@StewartLevine Can you update node and see if the error still persists?

**Comment by Stewart3L** [comment]
The error persisted after updating to 0.10.35. I've completed the tutorial in the meantime.

**Comment by martinheidegger** [comment]
@Stewart3L How could you complete the tutorial?

**Comment by StewartLevine** [comment]
@martinheidegger, I was able to access each exercise by the command line:
ex: javascripting select "FUNCTION ARGUMENTS"
The verify feature worked, but the menu crashes. 

fyi: Currently I'm having the opposite experience with learnyounode. In learnyounode the menu works ok, but the verify feature doesn't work past the first two lessons.

**Comment by SomeoneWeird** [comment]
Can you guys please update to the latest javascripting and see if it fixes your problem? There have been a few changes (although nothing directly related to this)

**Comment by StewartLevine** [comment]
@martinheidegger, @SomeoneWeird, I just updated to the latest version of javascripting and the menu feature works great. And for the record, I updated learnyounode and the verify feature works too.

Thanks to the team for their efforts in making and maintaining these nifty learning tools!

**Comment by SomeoneWeird** [comment]
Awesome! Open another issue if you run into more problems :)
