### ISSUE TITLE
Compilation errors.

### ISSUE THREAD

**Issue by justinbmeyer** [nodeschool/discussions#837]
I'm having a problem verifying myaddon.  I get the following output:

```
✓ package.json contains `"gypfile": true`
✓ binding.gyp includes a "myaddon" target
✓ binding.gyp includes "myaddon.cc" as a source file
✓ binding.gyp includes a correct NAN include statement
make: *** No rule to make target `Release/obj.target/myaddon/myaddon.o', needed by `Release/myaddon.node'.  Stop.
✗ node-gyp build: `make` failed with exit code: 2
```

All other prior verification steps have passed.  Any idea why this might be breaking?  I'm using:

- node v0.10.26
- python 2.7.5
- GNU Make 3.81
- gcc:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```

Thanks!

**Comment by wblankenship** [comment]
Could you paste your `binding.gyp` and `package.json` file?

**Comment by justinbmeyer** [comment]
```
{
  "name": "myaddon",
  "version": "1.0.0",
  "description": "My Awesome Addon",
  "main": "index.js",
  "scripts": {
    "install": "node-gyp rebuild"
  },
  "license": "MIT",
  "dependencies": {
    "bindings": "^1.2.1",
    "nan": "^1.2.0"
  },
  "gypfile": true
}
```


```
{
  "targets": [
    {
      "target_name": "myaddon",
      "sources": [ "myaddon.cc" ],
      "include_dirs": ["<!(node -e \"require('nan')\")" ]
    }
  ]
}
```

**Comment by wblankenship** [comment]
Hmm all things equal I can't replicate. (disclaimer, I'm on debian)

Which version of goingnative are you running? `goingnative -v`

The issue appears to be internal to goingnative: https://www.gnu.org/software/make/manual/html_node/Error-Messages.html

**Comment by justinbmeyer** [comment]
> goingnative@1.4.12

**Comment by wblankenship** [comment]
Also equal.

Perhaps its an issue with OSX and `gcc`'s configuration? Will defer to @rvagg if he has encountered this.

**Comment by rvagg** [comment]
hm, can you confirm myaddon.cc is in the same directory as binding.gyp?

**Comment by martinheidegger** [comment]
Bikeshedding this because its a nasty one.

**Comment by SomeoneWeird** [comment]
@justinbmeyer ping

**Comment by finnp** [comment]
Closing this because it's inactive.
