### ISSUE TITLE
exercise 3 of learnyounode  fs.readFileSync('/path/to/file')

### ISSUE THREAD

**Issue by arehfuss** [nodeschool/discussions#839]
I don't know what do I put in for 'path/to/file'?

**Comment by martinheidegger** [comment]
@arehfuss Welcome! The file path of a file you created! I agree that the naming is not well. Just out of curiosity: is the problematic concept that of a "path" or that you need to create a file?

**Comment by arehfuss** [comment]
I just don't know what to put in as a file.  To test it myself I put in my
own test.txt file and I get my own correct answer.  I am confused about how
the command "learnyounode verify program.js" works.  I'm guessing it won't
like my own private file.  "The full path to the file to read will be
provided as the first command-line argument".  I don't understand this
sentence.

Thanks for the reply

**Comment by sianglim** [comment]
Hi @arehfuss,

the hint lies in the Baby Steps excercise.

Instead of coding your actual file name (which is why it works when you test locally), you should use process.argv. This way, any filename you include on the command line is read as the first argument after "node program.js".

When verifying, you do not need to put in a filepath because learnyounode automatically adds its own file as the first argument after "learnyounode verify program.js".

Hope that helps.

**Comment by arehfuss** [comment]
Thank you.  I had a feeling it had something to do with baby steps and tried the process.argv, but I guess I'm not getting something right as it will not pass, yet.

**Comment by martinheidegger** [comment]
Very general: You can execute node scripts using `node x` where `x` stands for any file on your hard drive. The notation for `x` is a `file path`. On Linux/Mac the file paths look like this `/usr/local/martin/myfolder` on Windows they look like this `C:\Users\martin\myfolder\myfile.js`.

However, this `node x` will run the file without any of the pretext that `learnyounode` requires. `learnyounode run x` will add the pretext of the selected exercise (like the process.argv arguments). `learnyounode verify x` will also verify that the file that you ran actually does everything correctly.

**Comment by arehfuss** [comment]
After trying this:


C:\Users\Ant\Desktop\nodejs\nodeschool>learnyounode verify program.js
'C:\Users\
Ant\Desktop\nodejs\nodeschool\program.js'


I get this plus the regular fail message which I omit:

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags),
mode);
                 ^
TypeError: path must be a string
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.(anonymous function) [as openSync]
(C:\Users\Ant\AppData\Roamin
g\npm\node_modules\learnyounode\exercises\my_first_io\wrap.js:30:19)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.fs.(anonymous function) [as readFileSync]
(C:\Users\Ant\AppData\Ro
aming\npm\node_modules\learnyounode\exercises\my_first_io\wrap.js:30:19)
    at Object.<anonymous>
(C:\Users\Ant\Desktop\nodejs\nodeschool\program.js:25:
12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by martinheidegger** [comment]
@arehfuss I just re-read the issue and :pensive: it seems I should have read your request more carefully. I am sorry for that. @sianglim was spot on with his answer!

You need to use the path that is given to you through the `process.argv`. To debug your work it helps to use:

`learnyounode run problem.js`

And do something like

`console.log(process.argv)`

**Comment by arehfuss** [comment]
Thank you both for all of your help and for those hints that helped me
figure it out.  On to the next problem:)

**Comment by vicontin** [comment]
If I may, do not use any other console.log() other than the result. I had console.logs for the filename and stuff. It wasn't until I took those off, that my solution passed. Just FYI.

**Comment by prsheth** [comment]
@vicontin that worked for me as well !
