### ISSUE TITLE
Stream-adventure http server not working

### ISSUE THREAD

**Issue by krikara** [nodeschool/discussions#84]
When I try verifying my code in http server, I keep getting this error at the end. First, the entire Actual and Expected match perfectly, but at the very end, I see this -

```
ACTUAL SERVER Error : read ECONNRESET 
    at errnoException (...)
    at TCP.onread (...)
```
My following code looks like this. I have also tried using the official answer here https://github.com/substack/stream-adventure/blob/master/problems/http_server/solution.js, but I still get the same error everytime, no matter how I modify my code. What exactly is this error and how do I fix it?

```JavaScript
var http = require('http');
var map = require('through2-map');
var server = http.createServer(function (req, res) {
	if (req.method !== 'POST')
	{
		res.end();
	}
	else
	{
		req.pipe(map(function (chunk) {
			return chunk.toString().toUpperCase()
		})).pipe(res);
	}
});
server.listen(process.argv[2]);
```

**Comment by khalifenizar** [comment]
@krikara Your solution works for me so it has to be an installation problem. Does this problem still persist for you? Have you tried to update `stream-adventure`?
