### ISSUE TITLE
Error: unrecognized flag -v,

### ISSUE THREAD

**Issue by taconazo** [nodeschool/discussions#840]
hello 

I'm trying the run this code: 

```JavaScript
var example = prompt('some string');
console.log(example)
```

Is working on Scratchpad, I have issues running on the terminal following the javascripting documentation, and get this error

```
Error: unrecognized flag -v,
Try --help for options

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/mnlks/nom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by Sequoia** [comment]
Yo @taconazo! I'm not fully clear on what you're doing-- are you saying `node -v` doesn't work?  Because that's a problem that would have nothing to do with your script.  Looks like an install issue.  Have you been able to get node to do anything?  If not, try removing & reinstalling node.

https://github.com/joyent/node/wiki/installation Good luck!

**Comment by martinheidegger** [comment]
@Sequoia Seems like its a [Scratchpad](http://scratchpad.io/open-brain-8555) specific issue

**Comment by martinheidegger** [comment]
Or maybe this [Scratchpad](https://developer.mozilla.org/en-US/docs/Tools/Scratchpad). @taconazo Could you enlighten us?

**Comment by taconazo** [comment]
Hey, everything else is working, it was just that particular exercise. I
compiled on terminal and scratchpad. I guess is an installation issue.
Thanks a lot


On Tue, Jan 20, 2015 at 9:43 PM, Martin Heidegger <notifications@github.com>
wrote:

> Or maybe this Scratchpad
> <https://developer.mozilla.org/en-US/docs/Tools/Scratchpad>. @taconazo
> <https://github.com/taconazo> Could you enlighten us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/840#issuecomment-70775413>
> .
>



-- 
Manuel Alejandro Gutierrez
http://cargocollective.com/mnlks

**Comment by martinheidegger** [comment]
What is "scratchpad"? I have never heard of it. Would you mind to enlighten me)
