### ISSUE TITLE
If statements

### ISSUE THREAD

**Issue by VisValentina** [nodeschool/discussions#841]
Hi! My solution for the if-statement exercise doesn't seem to be passing and I don't know why, here is my code:

var fruit = 'orange';
if (fruit.length > 5) {
console.log('The fruit name has more than five characters');
}
else {
console.log('The fruit name has five characters or less');
}

**Comment by StewartLevine** [comment]
Hi @VisValentina,

This seems to be one of those silly little programming problems that one (hopefully) looks back and gets a chuckle. The text string you are sending to console is missing the period at the end. Looking closely at the challenge, you can see that the period at the end of the sentence is highlighted too.
