### ISSUE TITLE
learnyounode timeserver : why no output in the "helper" function 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#842]
Due to a git problem I have to do  several exercises another time.

At this moment I have this : 

~~~

var net = require('net'); 

function parsedate() { 
    date = new Date(); 
    year = date.getFullyear();
    month - date.getMonth(); 
    day = date.getDat(); 
    hour = date.getHour(); 
    minute = date.getMinute(); 
    second = date.getSecond();
    date2 = day + "-" + "month" + "-" + year ; 
    console.log(date2); 
    return  date2
}

var server = net.createServer (function (socket) { 
  date = parsetime ;
});

server.listen(3000); 

~~~

Now I wonder why date2 in the function parsetime is not seen on the screen ? 
And how I can display it. 

Roelof

**Comment by martinheidegger** [comment]
@roelof1967 It seems like you havn't given it your proper attention :wink: If I ask myself: "Which methods are called?" you might find that the only two methods called are the `.listen` and `function (socket){` method and both of them do not log or process anything.

**Comment by roelof1967** [comment]
oke, I just awake now and I hope i can give it the proper attentention.
