### ISSUE TITLE
learnyounode / http-collect : empty output

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#844]
Hello, 

I try to make this exercise workable with bl and concat-stream. bl is already working.
With concat-stream I have this : 

~~~

var http = require('http'); 
var concat = require('concat-stream'); 

var str = '' ; 

function d(dataBuffer) {
    console.log(dataBuffer.length); 
    console.log(dataBuffer.toString());
}


http.get(process.argv[2] , function callback(response) {
  
  response.setEncoding('utf8');
  
  response.on('error', function(e) { 
      console.log("Got error: " + e.message);
  });
  
  
  response.on('data', function() {
      var concatStream = concat(d);
      response.pipe(concatStream);
   });
   
   response.on('end', function () {
        
  }); 
 
})


~~~

but still I do not this output : 0 and a empty string

**Comment by roelof1967** [comment]
Wierd. With the same script I now see this output : 

~~~

warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at IncomingMessage.EventEmitter.addListener (events.js:160:15)
    at IncomingMessage.Stream.pipe (stream.js:70:12)
    at IncomingMessage.<anonymous> (/home/roelof1967/Documents/node_exercises/learnyounode/http_collect_concat_stream..js:23:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (_stream_readable.js:746:14)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)

~~~

**Comment by martinheidegger** [comment]
Hello @roelof1967 

In your code you are piping the response to concatStream when the "data" event already happended. 
you need to pipe it before the events happend (outside of the `.on`)

**Comment by roelof1967** [comment]
oke, then I have to look how to do that.
I thought that it was wise to do it on a .on because otherwise when there is a error the error is also sended to  d. 

Roelof

**Comment by martinheidegger** [comment]
Your thinking is actually quite good. Being aware of errors is important but piping works outside of that.

**Comment by roelof1967** [comment]
oke, so if I understood you well I can use the  .on data for example to display the data, 
and the .end means everything has ended

**Comment by martinheidegger** [comment]
Imagine there was no `.pipe` command. You would need to do piping like this:

```JavaScript
function pipe(in, out) {
  in.on("error", function(error) {
    out.emit("error", error);
  });
  in.on("data", function(data) {
   out.write(data);
  });
  in.on("end", function() {
     out.emit("end");
  });
}
```

This is an example code but what pipe does is essentially this: Instead of you needing to write event listeners on the input and passing the data to the output you can use the method `pipe` for your convenience.

All the events that are sent out can have more than one listener (so you should be theoretically able to pipe one source to many outputs. (never tried this)

**Comment by roelof1967** [comment]
oke, I think I understand it.
