### ISSUE TITLE
Learnyounode excerise 6 make it modular

### ISSUE THREAD

**Issue by coen-b** [nodeschool/discussions#845]
Hi All,

I have this code in one module:

```JavaScript
var path = require("path");
var handleFolder = require("./folderAction");

if (process.argv.length !== 4) {
  console.log("Missing path param and/or file extension");
  process.exit(1);
}

function filterFileName(fileName, fileExt) {
  return (path.extname(fileName) === fileExt);
}

handleFolder(process.argv[2], filterFileName, "." + process.argv[3],function callback(err, resultArr){
  if (err) {
    console.log("Dit ging fout: " + err);
  }else{
    resultArr.forEach(function(p){
      console.log("Filename: " + p);
    });
  }
});
```

And this code in the other module:

```JavaScript
var fs = require('fs');

function readFolder(folder, filterAction, fileExtension, cbFunc) {
  fs.readdir(folder, function(err, folderContent) {
    if (err) {
      cbFunc(err);
      return;
    }
    var res = [];
    folderContent.forEach(function(fileName) {
      if (filterAction(fileName, fileExtension)) {
        res.push(fileName);
      }
    });
    cbFunc(null, res);
  });
}

module.exports = readFolder;
```

But somehow learnyounode doesn't want to verify this code. The error message is:
does not appear to pass back an error received from `fs.readdir()`
This suprises me because it actually does.

Any help would be highly appreciated!

Best regards,
Coen

**Comment by martinheidegger** [comment]
Hello @coen-b!

Your solution is not broken but it is not following the specification to the letter:

> The module must export a single function that takes three arguments: the directory name, the filename extension string and a callback function, in that order.

Your module takes four arguments.

**Comment by coen-b** [comment]
Hi Martin,

Thank you so much!

I didn't expect this to be a problem.. ;-)

Best regards,

Coen
