### ISSUE TITLE
learnyounode  transform : can this also be done with the transform class

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#846]
Hello, 

When googeling I found out that the transform exercise can also be solved by using the transform class. 

Is there somewhere a example or explanation how I can use that class to solve the transform exercise ?

Roelof

**Comment by martinheidegger** [comment]
Hello @roelof1967 

I do not know what you mean by "the transform class" can you add a link to the document that you were writing about.

**Comment by roelof1967** [comment]
here it is : http://strongloop.com/strongblog/practical-examples-of-the-new-node-js-streams-api/

**Comment by roelof1967** [comment]
Found the answer with some help on irc

**Comment by martinheidegger** [comment]
@roelof1967 Awesome to go the extra-mile! Would you mind sharing the answer? In case someone else asks?

**Comment by roelof1967** [comment]
of course .

Here you have : 

~~~

var fs= require("fs"); 
var stream= require("stream"); 
var util= require("util"); 

var UpperTransform = function(options) { 
     if (!(this instanceof UpperTransform)) { 
       return new UpperTransform(options); 
     } 
     stream.Transform.call(this, options); 
}; 
util.inherits(UpperTransform, stream.Transform); 

UpperTransform.prototype._transform = function(line, enc, done) { 
     this.push(line.toString().toUpperCase()); 
     done(); 
}; 

var upper = new UpperTransform({ objectMode: true }); 

upper.on("error", function(err) { 
   console.log(err) 
}); 

process.stdin.pipe(upper).pipe(process.stdout); 

~~~

**Comment by martinheidegger** [comment]
:+1:
