### ISSUE TITLE
Node js question

### ISSUE THREAD

**Issue by demonus521** [nodeschool/discussions#847]
Somebody can tell me how to execute a js file with nodejs. when i execute the nodejs program only appear  an console window, but i dont kow how to do

**Comment by roelof1967** [comment]
where do you want to see the output then instead of the console window. The console window is the normal place for the output.

**Comment by greelgorke** [comment]
@demonus521 
```
node yourFile.js
```

you can use `node -h` for getting usage help

**Comment by martinheidegger** [comment]
@demonus521 I assume you are using windows: Starting node from the Sidebar will just start the Node REPL. To use node better use the node prompt (in the same application folder) or just drag & drop a file on the Node Icon.
