### ISSUE TITLE
Stuck in learnyounode HTTP UPPERCASER problem

### ISSUE THREAD

**Issue by crapbox** [nodeschool/discussions#848]
Im stuck in the HTTP UPPERCASER problem.

below is my code, and I've googled a lot and other answers seems similar to my code. 

Can't figure out why mine does not work.

I get "SyntaxError: Unexpected end of input"

```javascript
var http=require('http');
var map=require('through2-map');

var server = http.createServer(function (req,res){
        if (req.method === 'POST'){
                req.pipe(map(function (chunk){
                        console.log(chunk.toString());
                        return chunk.toString().toUpperCase();
                })).pipe(res);
        }
        else{
                console.log("not post");
                res.end();
        }
});
server.listen(process.argv[2]);
```

Any help is appreciated!

Thanks.

**Comment by davecocoa** [comment]
I tried your solution on my computer and it passed. Try to make sure you have the latest `node` and `learnyounode` installed.

**Comment by martinheidegger** [comment]
@crapbox Do you still have that problem?

**Comment by crapbox** [comment]
Thanks!! My learnyounode version was the problem. Now it works.

Sorry for the late comment. I was unable to use my computer..
