### ISSUE TITLE
Issue checking "Time server" task

### ISSUE THREAD

**Issue by Qo-Ops** [nodeschool/discussions#851]
So I have a problem checking my solution for "Time server" task in learnyounode. Here's my code:
```javascript
var net = require('net');
var server = net.createServer(function (socket) {
	var date = new Date();
	socket.end(date.getFullYear() + "-" + date.getMonth()+1 + "-" + date.getDate() + " " + date.getHours() + ":" + date.getMinutes());
});
server.listen(process.argv[2]);
```
I have also uploaded a screenshot of verify command outcome. It totally doesn't make any sense to me. I use ubuntu 14.10. node -v is v0.10.35
![screenshot from 2015-01-19 10 24 20](https://cloud.githubusercontent.com/assets/10588791/5794561/f343fc0c-9fc6-11e4-8f5b-2b03158fac53.png)

**Comment by martinheidegger** [comment]
Can you update to the latest version of `learnyounode`? A lot has changed since you installed it.

**Comment by Qo-Ops** [comment]
It hasn't helped. That's what I get now:
    "2015-01-20 9:33"                   !=    "2015-01-20 09:33"
Is the code correct?

**Comment by davecocoa** [comment]
In the picture with your original description it looks like you're missing a new line character after your output, that's what it means when it shows nothing ` != ""`. I acknowledge this is totally non-obvious and the exercise instructions don't mention a newline anywhere. Your solution is absolutely correct, I'm sorry the verification system tripped up on this.

**Comment by Qo-Ops** [comment]
Added the newline. Now it works! Thank you
