### ISSUE TITLE
looping-through-arrays

### ISSUE THREAD

**Issue by amy-chiu** [nodeschool/discussions#852]
Not sure what I'm doing wrong here. Any advice? 

var pets = ['cat', 'dog', 'rat'];
for (var i=0, i<pets.length+1, i++) {
	pets[i] = pets[i] + 's';
}
console.log(pets[i]);

**Comment by SomeoneWeird** [comment]
the variable `i` only exists within the `for` loop you have, so everything between the `{` and `}`. Try removing the `[i]` and just printing `pets` to log the entire array :)
