### ISSUE TITLE
Where can I find documentation for stream methods for websockets exercise?

### ISSUE THREAD

**Issue by josiahsprague** [nodeschool/discussions#853]
I'm working through the websockets exercise. I got a working solution just by intuitively trying;

```
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8000');
stream.write('hello\n');
stream.end();
```

But I don't really know what's going on. The official solution skips the `.write()` method and goes straight to `.end()`, which I didn't know was possible. I guessed at the method names `.write()` and `.end()`, but I wanted to find some docs about what methods are really available on the object returned by `ws`. The [`websocket-stream` docs](https://github.com/maxogden/websocket-stream) are very sparse. 

Where can I find detailed docs about what methods are available on the stream object here?

**Comment by a0viedo** [comment]
Hey @josiahsprague, it's great that you found the solution but still want to learn about the exercise. Check the docs for Streams [here](http://nodejs.org/api/stream.html). If you think you could use some other resources about streams, let me know.

**Comment by josiahsprague** [comment]
Awesome. That's very helpful. Thanks!
