### ISSUE TITLE
stream-adventure / combiner : again no output 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#854]
Hello, 

Till now I have this : 

~~~

var combine = require('stream-combiner'); 
var through = require('through'); 

module.exports = function() {
    
    var group = through (write,end)
    
    function write(line) {
        
        row = JSON.parse(line); 
        this.queue(row);
        
    }
        
     function end() {
         this.queue(null);
     }
} 

~~~

When I do node combiner.js {"type":"genre","name":"cyberpunk"} I expected to see the json string again. But I do not see anything at all. 

Where did my thinking took the wrong lane ?

Roelof

**Comment by martinheidegger** [comment]
I am not sure what the problem is but: What is `this.queue` supposed to do?

**Comment by roelof1967** [comment]
I thought it was for displaying data on the console but I think I mistaken.

**Comment by roelof1967** [comment]
Solved it. I did again console.log and I saw output
