### ISSUE TITLE
introduction javascripting - fail to pass - newline?

### ISSUE THREAD

**Issue by astemborskim** [nodeschool/discussions#855]
I can't get this very simple output to the console to pass the verify. It seems there is a newline after the hello. I'm assuming this is why it fails.

![intro](https://cloud.githubusercontent.com/assets/4976923/5808476/674ae846-9ff3-11e4-95e7-7a5aae50ca84.JPG)

![code](https://cloud.githubusercontent.com/assets/4976923/5808491/993bf07a-9ff3-11e4-92bd-223ed2949341.JPG)

Any ideas. I'm going to move on, but would like to fix this in case its an issue for other lessons.

**Comment by martinheidegger** [comment]
@astemborskim Everything looks to be right. Are you running the latest javascripting? `npm ls javascripting -g --depth=0` should show you which version you have installed. Maybe @SomeoneWeird can help?

**Comment by a0viedo** [comment]
@astemborskim what gives you if you run `node -v` and `npm -v`?

**Comment by astemborskim** [comment]
![versions](https://cloud.githubusercontent.com/assets/4976923/5878059/b5624a94-a2e9-11e4-9c94-4050fb973eab.JPG)
![javascripting](https://cloud.githubusercontent.com/assets/4976923/5878093/04eb0556-a2ea-11e4-89f5-fc613c1b04be.JPG)

**Comment by astemborskim** [comment]
Also.. this is an issue in all other lessons. None would pass the verify. Very odd.

**Comment by a0viedo** [comment]
@astemborskim have you tried using just the cmd without Cygwin? how do you installed node? also, can you try updating the workshop? `npm install javascripting -g`

**Comment by SomeoneWeird** [comment]
Yeah, if you update javascripting it should give you a difference output so you can see what is wrong.

**Comment by martinheidegger** [comment]
Can you zip the folder and put it somewhere for us to download? It could be that other issues are the problem.

**Comment by astemborskim** [comment]
Sorry for the delayed response. For some reason github messages were going to a junk folder. Still not resolved. I tried to run it through Microsoft Powershell as well adn still seeing the same error. I have placed my javascripting folder where i installed (npm install javascripting). 

http://1drv.ms/1z0ZDUI

**Comment by martinheidegger** [comment]
> Can you zip the folder and put it somewhere for us to download? It could be that other issues are the problem.
