### ISSUE TITLE
functional js / basic filter :  undefined as answer. Why ?

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#856]
Hello, 

If I understand everything right, I could solve this problem with : 

~~~

module.exports = function getShortMessages(messages) {
    
    function small_message(item) {
        return item.length < 50 ; 
    }
    
    messages.map(function(message) {
        return small_message(message)                 
    })
}
~~~

but when I do functional-js run basic_filter.js I see as output undefined.  

Can someone explain where my thinking took the wrong path ?

Roelof

**Comment by Sequoia** [comment]
> getShortMessages takes an array of objects with '.message' properties and **returns an array of messages** that are less than < 50 characters long.

A few issues:
1. Your `getShortMessages` doesn't return anything (it should return an array)
2. The array should contain *messages* (strings), you are replacing the array value with bools
3. [`Array.map`](http://devdocs.io/javascript/global_objects/array/map) will return an array that is **equal in length** to the original array, your final array should be shorter.

You need to use a different `Array` method.  Hint: see lesson title. :smile_cat: good luck!

**Comment by roelof1967** [comment]
you are right. I have now this 
~~~
module.exports = function getShortMessages(messages) {
    
    function smallerfifty(element) {
        return element.message.length < 50;
     }
    
    return messages.filter(smallerfifty);
 
               
}

~~~

which output looks like this : 

~~~

[ { message: 'Cupidatat reprehenderit qui dolor ex labore amet.' },      

~~~

so I have to find a way to get only the messages as output 

Roelof


 
~~~

so I have to find a way to

**Comment by roelof1967** [comment]
Sorry but this one is not solved. I still need help on how to make the output right. Could this be re-opened.

**Comment by martinheidegger** [comment]
> so I have to find a way to get only the messages as output

This is a task for you :smile:.
What is your current question in this issue?

**Comment by roelof1967** [comment]
How to do that. 
This is a very difficult workshop for a beginner in node. I did the javascripting, learnyounode and stream-adventure and I think I have not enough knowlegde to do this one.

Maybe search for a good book about this subject.

**Comment by martinheidegger** [comment]
Hint: [Array.map](http://devdocs.io/javascript/global_objects/array/map) does allow you to create a array of same sized where each entry is the result of a computation on one element. For example: you can turn strings into numbers:

```JavaScript
[1, 2, 3].map(String)
```
Accessing a property of an object is also a sort of computation.

Does that help you?

**Comment by roelof1967** [comment]
Thanks, I have solved that one but the following one is also very difficult. 
Maybe first get more experience in node and look for more info about this functional thing.

It looks very interressted but very difficult to see how you can come to the solution.

**Comment by martinheidegger** [comment]
I don't want to encourage you. My problem was just that I didn't see a question in this issue (which is why i closed it).

Functional JS is all about becoming familiar with new concepts of how javascript works. JavaScripting is super-basic and does very few but teach you the mechanics of the syntax so it will not help you with functional js much.

I think it could help if JavaScripting had more advanced usages like (`arguments`, `passing functions to functions`, `nested scopes`, `toString`, etc.). Maybe we need a new workshopper `javascripting++` for the tricky parts of the language.

**Comment by roelof1967** [comment]
maybe , for someone who has no experience in javascript the difference between the javascripting workshop and the functional javascript is very high. This is very not encourage newcomers to learn more about node.  I doubt now very much . This is not to blame you. You were the person who help me so muck with the beginners workshop I continue.

**Comment by martinheidegger** [comment]
Weeee: Just found a important typo: I meant to write "I don't mean to discourage you." Its great that you put so much energy in learning the things here and providing everyone with good feedback!

**Comment by Sequoia** [comment]
@roelof1967 one tip: When you get stuck, go back and re-read the exercise. I just went to edit the text to make clear that an array of Strings should be returned, but upon reading I saw that it already highlights this (albeit in a very odd location, under the `Examples` heading):
```markdown
## Example

The function should return an array containing the messages themselves, *without their containing object.*
```
Emphasis original.

Some of the exercises are challenging but each should be workable with a few tries & maybe a few readings of the instructions :sun_with_face:
