### ISSUE TITLE
javascripting introduction

### ISSUE THREAD

**Issue by Fortibus** [nodeschool/discussions#857]
My problem can be about the confusion around node or nodejs in ubuntu.
ubuntu: 14.04 LTS
npm -v: 1.3.10
nodejs -v: 0.10.25
node -v: " ... try sudo apt-get install node"
bash -version: 4.3.11(1)-release (x86_64-PC-linux-gnu)
Before the test i changed from node to nodejs in the "shebang" of index.js.
Test: see screenshot!
regards Fortibus

![node1](https://cloud.githubusercontent.com/assets/10583497/5819767/88a816c6-a0c0-11e4-9968-732bcb41f85b.png)

**Comment by Sequoia** [comment]
How/when did you install node? Check out https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

Alternately,
    sudo apt-get remove nodejs
    sudo apt-get install nodejs -y

Try that & reopen if the issue persists! good luck :+1:
