### ISSUE TITLE
newbie, why this outputs 0 ? (lesson 2)

### ISSUE THREAD

**Issue by 594727294** [nodeschool/discussions#859]
i cant seem to find out why this doesn't work.. should i try with parseInt() ?

i start the loop in the second index as the hint says. Tried as well with Number() instead of prefixing "+".

```JavaScript
var total = 0;
var c = 1;
process.argv.forEach(function() {
	c++;
	var numero = +process.argv[c];
	// console.log(numero);
	total = total + numero;
});
console.log(total);
```

it just outputs 0

**Comment by khalifenizar** [comment]
You are very close to the solution! Why don't you try to run this to see what's going on:

```js
var total = 0;
var c = 1;
process.argv.forEach(function() {
    c++;
    var numero = +process.argv[c];
    // print c and process.argv[c]
    console.log(c, process.argv[c]);
    total = total + numero;
});
console.log(total);
```

**Comment by sudodoki** [comment]
You're starting your index from second item, that's correct, but you're looping exactly so many times as the length of `process.argv` vector, which is getting you 2 extra runs

**Comment by 594727294** [comment]
I tried what @khalifenizar suggested (the print line returned a syntax error) and it returned the values as strings, i can see clearly that i get two more rounds which return "undefined" each. What i dont understand is why, i've looked into ``process.argv`` documentation but it doesn't really explain whats happening.

**Comment by khalifenizar** [comment]
@594727294 Remember that the first two values of `process.argv` are always "node" and the name of your program. Those aren't numbers to add! Try to `console.log(process.argv)` at the end of the program to see that it has those two extra values.

`.forEach` goes through every item in the array. Do you really need to add *everything* in `process.argv`?

**Comment by 594727294** [comment]
Good morning! thank you guys for your hints i passed!

    var total = 0;
    for (i = 2; i < process.argv.length; i++) { 
        var numero = +process.argv[i];
        total = total + numero;
    }
    console.log(total);

**Comment by martinheidegger** [comment]
@594727294 Awesome, congratulations!
