### ISSUE TITLE
Javascripting doesn't run

### ISSUE THREAD

**Issue by landan240** [nodeschool/discussions#860]
I'm very new to this, and I decided to do the Javascripting workshop. I installed the program, using 
npm install --global javascripting and it worked. But then when I type in javascripting, nothing happens. I don't know if I'm just too noob or it's a legitimate problem. Please help!
![cmd prompt javascripting](https://cloud.githubusercontent.com/assets/10608530/5829523/3d5a7256-a0c8-11e4-91b0-332de01bfde3.PNG)

**Comment by SomeoneWeird** [comment]
What version of node and npm do you have installed?

**Comment by landan240** [comment]
I have node v0.10.35 and npm v1.4.28. 
But now instead of not doing anything, it says it is not recognized.
![not recognized](https://cloud.githubusercontent.com/assets/10608530/5830749/ec38c438-a0d9-11e4-93f9-929c78edfd03.JPG)

**Comment by martinheidegger** [comment]
Maybe your PATH's are not setup correctly, could you try to use the [Node.js command prompt](https://github.com/nodeschool/organizers/issues/115#issuecomment-70531745)?

**Comment by landan240** [comment]
Opened Node.js command prompt and it worked fine. Thank you!
