### ISSUE TITLE
'console' is undefined?

### ISSUE THREAD

**Issue by landan240** [nodeschool/discussions#862]
I am doing the workshop Javascripting, and just finished the first objective thingy. But when i went to run the file, it gives me this:
![console is undefined](https://cloud.githubusercontent.com/assets/10608530/5832044/55a5df14-a0f3-11e4-969a-213179c7a5f3.JPG)
I have node v0.10.35 and npm v1.4.28.
Please help a newbie out!

**Comment by SomeoneWeird** [comment]
Yep! This is because windows is running your script with the `Windows Script` program, instead of node, try executing your file with `node introduction.js` instead of `introduction.js`

**Comment by landan240** [comment]
Thanks! Still learning this world of programming.

**Comment by SomeoneWeird** [comment]
I think 4 minutes might be the record for fastest resolved issue ;)
