### ISSUE TITLE
level me up scotty / basic-get : why is key here 100 for every entry 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#863]
Hello, 

This is my solution : 

~~~

var level = require('level')
var db = level(process.argv[2])

for (var i = 0 ; i < 101; i++ ) {
    
    var key = "key" + i ;
    
    db.get(key, function (err, value) {
        
        if (err) {
            if (err.type != "NotFoundError") { 
               return 
            }
            return
        }
        
        console.log(key + ' = ' + value)
        
    })
}

~~~

but when I run it I see all the time key100 = 

Can someone explain to me why this happens 

Roelof

**Comment by khalifenizar** [comment]
The problem is with the nature of callbacks and the current state of the `key` variable. Try to add some extra `console.log` calls to get some visibility of the order of events:

```js
var level = require('level')
var db = level(process.argv[2])

for (var i = 0 ; i < 101; i++ ) {

    var key = "key" + i ;

    console.log("I AM ABOUT TO FETCH KEY #" + i);

    db.get(key, function (err, value) {
        console.log("URGH... it took me a while to fetch a key...");

        if (err) {
            if (err.type != "NotFoundError") {
               return
            }
            return
        }

        console.log(key + ' = ' + value)

    })
}

console.log("I've sent out all requests to fetch keys. What now?\n...");
```

**Comment by roelof1967** [comment]
Thanks, the loop runs quicker as the callbacks so if the callback is ready the loop is at the end.
But if I place the loop in the callback like this : 

~~~

var level = require('level')
var db = level(process.argv[2])

var i = 0 ;
var key = "key" + i ;

db.get(key, function (err, value) {
    
    if (err) {
        if (err.type != "NotFoundError") {
            return
            }
            return
        }

   console.log(key + ' = ' + value)
   
    if (i < 10) {
        i++
    }  
})

~~~

Then the key is only fetched one time.

**Comment by roelof1967** [comment]
Solved it by doing this : 

~~~

var level = require('level')
var db = level(process.argv[2])

function read_key(key){ 
    (db.get(key, function (err, value) {
    
    if (err) {
        if (err.type != "NotFoundError") {
            return
            }
            return
        }

   console.log(key + '=' + value)
}))} 
    
for (var i = 0 ; i < 10; i++) { 
     key = "key" + i; 
     read_key(key); 
}

~~~

but I think there is a error in the official solution which looks like this : 

~~~

var level = require('level')
var db = level(process.argv[2])

function fetchNext (i) {
  var key = 'gibberish' + i
  db.get(key, function (err, data) {
    if (err) {
      if (!err.notFound)
        throw err
    } else
      console.log(key + '=' + data)

    if (i < 100)
      fetchNext(i + 1)
  })
}

fetchNext(0)

~~~

it gives blank errors. I think the if then is not right. 
As far as I can see it test if there is a error. If so , if the error is a no found if not then a console print of the key. But it never comes there because the if err is not closed. 

Am I right or wrong. If im right I will make a PR to the maintainer 

Roelof

**Comment by martinheidegger** [comment]
I am not sure what you mean with `blank errors`. The solution does this:

`if (err) { ... } else { console.log(...) }`

if an error occurs do something, else log something.

`if(!err.notFound) throw err` 

if an error occurs that it not a notFound error, break the application, else do nothing.

In other words: Errors may occur but if errors occur they should only break the system when they are not `notFound` errors.

**Comment by roelof1967** [comment]
Still if I verify the official solution I see this output: 

~~~

ACTUAL:   ""                                                                                             
EXPECTED: "key4=much of primary source materials but for AM collections are accompanied by LESK, for what
 can we afford, yet first Pausing a while, but she could for verifying the content of the confused march 
forlorn, th."                                                                                            
                

~~~

**Comment by martinheidegger** [comment]
Have you tried changing your solution to load 100 elements instead of 10?

**Comment by roelof1967** [comment]
yes . but what I said my solution works fine. 
The official solution not. That one gives the wierd output.

**Comment by martinheidegger** [comment]
hmm.. i tried the official solution and it works fine here...

**Comment by roelof1967** [comment]
very wierd, here not.
But case closed then
