### ISSUE TITLE
Workshopper concept for a websocket workshopper

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/discussions#864]
The most requested workshopper at NodeSchool Osaka is a workshopper to learn about websockets. 

Last time @Atuyl offered a very nice idea for the implementation:

- All exercises are build around the idea to interact with a websocket server.
- The websocket server is started by default locally but can also be set to connect to a server via setting the IP.
- The websocket server has a webinterface that shows a track record of all the exercises that you completed.
- Multiple people can connect to the same websocket server.

As a result: During NodeSchool we could start a local websocket server and all the members in the NodeSchool could compete trying the exercises. Everyone that finishes first will be shown big on the screen.

What do you think of this?

**Comment by Sequoia** [comment]
Go for it! :+1: :tada:

**Comment by Sequoia** [comment]
migrated to international-day
