### ISSUE TITLE
levelmeup / basis post - again no output 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#865]
Hello, 

I try to see the json string like this : 

```js
var level = require('level')

var db = level(process.argv[2]);
var data = JSON.parse(process.argv[3]);

console.log(data); 
```

but when I do levelmeup run solution.js I see no output

**Comment by khalifenizar** [comment]
I don't see output either. I think this particular run doesn't expose it's output. I have to check the code to be certain.

**Comment by roelof1967** [comment]
I think it has to do with the JSON.parse command. It seems to make a object which I did not found a answer how to print the contents

**Comment by khalifenizar** [comment]
I think it's something particular to the exercise because I did `levelmeup run program.js` with this code and it didn't show anything:

```js
console.log('SHOW ME SOMETHING');
```

**Comment by roelof1967** [comment]
hmm, 

then Iit is very difficult to post data which I cannot see 

roelof

**Comment by roelof1967** [comment]
oke, found the answer. 

this part does the trick : 

~~~

var level = require('level')
var db = level(process.argv[3]); 
var data = JSON.parse(process.argv[3]); 

var jsonPretty = JSON.stringify(data,null,2)

~~~

but I still do not understand why I have to parse the string because on the exercise is stated : 

The second command-line argument is a string containing a complete 
7 JSON-encoded object 

So why do I have to convert it to a json object where it is already a json string 

Roelof

**Comment by roelof1967** [comment]
Found the answer on the github page : https://github.com/rvagg/levelmeup/issues/20
