### ISSUE TITLE
learnyounode won't load

### ISSUE THREAD

**Issue by mikeyferg** [nodeschool/discussions#869]
After successfully installing learnyounode on a mac using the following command-

"npm install -g learnyounode"

I receive the this error-

"-bash: learnyounode: command not found"

Any suggestions??

**Comment by khalifenizar** [comment]
Hey there!

I suspect that npm executables are not properly set up in your terminal's path. Could you please post the output of these two commands?

1. `npm -g bin`
2. `echo $PATH`

**Comment by mikeyferg** [comment]
The outputs are as follows-
npm -g bin-
/Users/<username>/.node/bin
(not in PATH env variable)

echo $PATH-
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Thanks,

Michael

**Comment by khalifenizar** [comment]
I think that if you add `/Users/.node/bin` to your path it should work. In your `~/.bash_profile` file try to add this:

```bash
# Add npm executables
export PATH="/Users/.node/bin:$PATH";
```

That file is just the `.bash_profile` file in your user's home directory. If you don't have a `~/.bash_profile`, you can just create it with that content.

**Comment by mikeyferg** [comment]
I did that. Now it seems the path is changed, per below.

-echo $PATH
/Users/.node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

But I still receive the same message when I try to run learnyounode.
-bash: learnyounode: command not found

**Comment by khalifenizar** [comment]
Oh no! Could you please post the output of `ls -l /Users/.node/bin` now?

**Comment by mikeyferg** [comment]
ls: /Users/.node/bin: No such file or directory

**Comment by khalifenizar** [comment]
Ah! Now we are getting somewhere. Try these:

- `ls -la /Users//.node/bin`
- `ls -la /Users`

**Comment by mikeyferg** [comment]
-ls -la /Users//.node/bin
ls: /Users//.node/bin: No such file or directory

-ls -la /Users
drwxr-xr-x   6 root   admin   204 Jan 16 14:16 .
drwxr-xr-x  34 root   wheel  1224 Jan 21 18:53 ..
-rw-r--r--   1 root   wheel     0 Sep  9 18:16 .localized
drwxrwxrwt   5 root   wheel   170 Jan  6 01:28 Shared
drwxr-xr-x   3 root   admin   102 Jan 16 14:16 data
drwxr-xr-x+ 43 mikey  staff  1462 Jan 22 09:44 mikey

**Comment by khalifenizar** [comment]
Clearly `npm` is trolling us! I think it's got the wrong executable path set up. Try `ls -la /Users/mikey`.

**Comment by mikeyferg** [comment]
total 184
drwxr-xr-x+  45 mikey  staff   1530 Jan 22 10:43 .
drwxr-xr-x    6 root   admin    204 Jan 16 14:16 ..
-r--------    1 mikey  staff      7 Jan  6 01:39 .CFUserTextEncoding
-rw-r--r--@   1 mikey  staff  20484 Jan 13 14:53 .DS_Store
drwx------   74 mikey  staff   2516 Jan 21 17:08 .Trash
drwxr-xr-x   13 mikey  staff    442 Mar  4  2014 .android
-rw-------    1 mikey  staff   6675 Jan 22 09:44 .bash_history
-rw-r--r--@   1 mikey  staff     37 Jan 22 09:44 .bash_profile
-rw-r--r--    1 mikey  staff  12288 Jan 12 18:27 .bash_profile.swp
drwxr-xr-x    3 mikey  staff    102 Mar  3  2014 .cache
drwxr-xr-x    3 mikey  staff    102 Mar  3  2014 .config
drwx------    3 mikey  staff    102 Dec 24  2013 .cups
-rw-r--r--    1 mikey  staff      0 Jan 16 13:58 .dbshell
drwx------   12 mikey  staff    408 Jan 21 18:53 .dropbox
drwxr-xr-x    5 mikey  staff    170 Nov 25 17:54 .dvdcss
drwxr-xr-x   10 root   staff    340 Nov 17 13:28 .git
-rw-r--r--    1 mikey  staff    180 Sep 24 19:11 .gitconfig
drwxr-xr-x    5 mikey  staff    170 Mar  4  2014 .gradle
-rw-------    1 mikey  staff      6 May 11  2014 .jbapps-mikey
drwxr-xr-x    3 mikey  staff    102 Mar  3  2014 .local
-rw-------    1 mikey  staff      0 Jan 12 19:29 .mongorc.js
-rw-------    1 mikey  staff    280 Jan 22 10:43 .mysql_history
drwxr-xr-x    5 mikey  staff    170 Jan  6 14:26 .node
drwxr-xr-x    3 mikey  staff    102 Jan 16 14:19 .node-gyp
drwxr-xr-x  270 mikey  staff   9180 Jan 22 10:44 .npm
-rw-r--r--    1 mikey  staff     52 Dec  3 16:11 .npmrc
drwx------    5 mikey  staff    170 Aug 11 14:14 .ssh
drwx------    4 mikey  staff    136 Apr 24  2014 .tor
-rw-------    1 mikey  staff   7719 Jan 12 18:27 .viminfo
drwxr-xr-x    2 mikey  staff     68 Sep 23 23:59 Applications
drwx------+  29 mikey  staff    986 Jan 21 16:39 Desktop
drwx------+  33 mikey  staff   1122 Jan  6 13:55 Documents
drwx------+  97 mikey  staff   3298 Jan 22 10:37 Downloads
lrwxr-xr-x@   1 mikey  staff     31 May 27  2014 Dropbox -> /Users/mikey/Dropbox (Personal)
drwx------@  20 mikey  staff    680 Jan 21 18:53 Dropbox (ApptheGame, Inc)
drwx------@  12 mikey  staff    408 Jan 21 18:53 Dropbox (Personal)
drwx------@   4 mikey  staff    136 Jan 21 18:53 Google Drive
drwx------@  57 mikey  staff   1938 Jan 21 10:03 Library
drwx------+   3 mikey  staff    102 Dec  4  2013 Movies
drwx------+   7 mikey  staff    238 Oct  6 20:12 Music
drwx------+   6 mikey  staff    204 Sep 23 03:11 Pictures
drwxr-xr-x+   5 mikey  staff    170 Dec  4  2013 Public
drwxr-xr-x    3 mikey  staff    102 Jan 22 10:38 Workspace
-rw-r--r--    1 mikey  staff  11376 Jan 21 17:32 npm-debug.log
drwxr-xr-x    3 root   staff    102 Dec  3 15:39 tmp

**Comment by a0viedo** [comment]
@mikeyferg could you please run `npm install npm -g` and then try to reinstall javascripting?

**Comment by mikeyferg** [comment]
Just did.  Still not working.

**Comment by a0viedo** [comment]
and what does it says when you execute `npm config get prefix`?

**Comment by mikeyferg** [comment]
/Users/mikey/.node

**Comment by martinheidegger** [comment]
@mikeyferg Does that folder exist? Shouldn't that be `/Users/mikey/.npm`?

**Comment by mikeyferg** [comment]
Both of those folders exist.  Not sure how it should be setup...

**Comment by martinheidegger** [comment]
Do both folders contain a folder and/or file `javascripting` ?

**Comment by mikeyferg** [comment]
learn you node is in- 
in - /Users/mikey/.node, it is in the bin folder
and in - /Users/mikey/.npm

**Comment by martinheidegger** [comment]
Can you try to change your config to `npm config set prefix ~/.npm`?

**Comment by mikeyferg** [comment]
I have it figured out.  There was some wrong permissions on npm.

Thanks for helping to walk me through this!

**Comment by a0viedo** [comment]
That's awesome. Just for the record, how did you installed node?

**Comment by mikeyferg** [comment]
I used nvm.  I think I used "sudo" originally which caused the permission issues.
