### ISSUE TITLE
Looping through array

### ISSUE THREAD

**Issue by landan240** [nodeschool/discussions#870]
I have this:

![looping through array atom](https://cloud.githubusercontent.com/assets/10608530/5848832/e9333de6-a191-11e4-99cc-0315da3491be.JPG)

and it gives me this:

![command](https://cloud.githubusercontent.com/assets/10608530/5848847/16c9b460-a192-11e4-9bb1-da14ade48bfc.JPG)

any advice?

**Comment by khalifenizar** [comment]
Hey there!

You have a *very* small syntax error in your `for` statement. You need to use semicolons `;` instead of commas `,` to separate the sections of the `for`. Your line 2 should look something like this:

```js
for (var i = 0; i < pets.length + 1; i++) {
``` 

That said, once it works your `for` loop is infinite! That isn't good! Can you figure out why? Try to add this `console.log` to the loop to see what's going on:

```js
var pets = ['cat', 'dog', 'rat'];

for (var i = 0; i < pets.length + 1; i++) {
    pets[i] = pets[i] + 's'

    console.log(pets);
}

console.log(pets)
```

(contributors/owners, this is `javascripting`, exercise 13)

**Comment by landan240** [comment]
Applied your changes @khalifenizar , and now this shows up:
![i get this](https://cloud.githubusercontent.com/assets/10608530/5850884/34b46054-a1b2-11e4-833d-e0baeba27faf.JPG)

**Comment by khalifenizar** [comment]
The problem is `i < pets.length + 1`. You only want to loop until `i < pets.length`, otherwise your `pets[i] = pets[i] + 's'` actually adds new items to the array, making it infinitely longer! Infinity is no good in a program!

Try to apply that final change to see if your solution works.

**Comment by landan240** [comment]
Made the changes and saved it. Still get this
![still this](https://cloud.githubusercontent.com/assets/10608530/5851017/ab969d0c-a1b4-11e4-81ef-31c335ec5923.JPG)
.

**Comment by khalifenizar** [comment]
Double infinite loop combo! The problem lies in `i`. Can you figure it out? Try this `console.log`:

```js
var pets = ['cat', 'dog', 'rat'];

for (var i = 0; i < pets.length; i + 1) {
    console.log(i);
    pets[i] = pets[i] + 's'
}
```

**Comment by landan240** [comment]
Infinite 0's...

**Comment by khalifenizar** [comment]
Yes... but why? :)

Hint: it wasn't happening in the first version you sent.

**Comment by landan240** [comment]
Does it have to do with not stopping at the right time?

**Comment by khalifenizar** [comment]
A `for` loop has 3 sections in the parentheses. One of the sections is supposed to be updating `i` but it's not doing it's job.

**Comment by landan240** [comment]
![capture](https://cloud.githubusercontent.com/assets/10608530/5851356/dd856414-a1ba-11e4-89f7-826a7d2c7884.JPG)
It's adding an s olnly to cats, every time and nevers stops.

**Comment by khalifenizar** [comment]
The problem lies in `i + 1`. If you notice, the first code screenshot you sent had `i++` in the 3rd `for` section. `i + 1` doesn't actually change the value of `i`, that's why it's staying at `i = 0` forever.

**Comment by landan240** [comment]
![now i get this](https://cloud.githubusercontent.com/assets/10608530/5851439/31f26208-a1bc-11e4-9934-2b8533a9dcc5.JPG)
I'm closer...another hint?

And a semi-unrelated question, what is the difference between 'i + 1' and 'i++'?

**Comment by landan240** [comment]
Never mind, put the console.log outside of the squiggly brackets, and it worked great!
Thanks for all the help!

**Comment by khalifenizar** [comment]
The best way to see the difference is to try it!

```js
var i;

i = 0;
i + 1;
console.log('0 after i + 1:', i);

i = 0;
i++;
console.log('0 after i++:', i);

i = 0;
i = i + 1;
console.log('0 after i = i + 1:', i);

i = 0;
i += 1;
console.log('0 after i += 1:', i);
```

**Comment by landan240** [comment]
That makes a lot of sense, 
Thanks again for helping out this programming newbie!

**Comment by gosha50** [comment]
for an unknown reason it refuses to take this. 
pets=['cat','dog','rat'];
for(i=0;i<pets.length+1; i++)
{pets[i]=pets[i]+'s';
console.log(pets);
}
console.log(pets);

**Comment by khalifenizar** [comment]
@gosha50 That code results in an infinite loop! See my [previous comment](https://github.com/nodeschool/discussions/issues/870#issuecomment-70973089).

**Comment by gosha50** [comment]
that's like a magic method, where length on an array is the index of the last item plus one. that's the built in method.  twisted little key note that was missing.

**Comment by gosha50** [comment]
this works! 
pets=['cat','dog','rat'];
for(i=0;i<pets.length; i++)
{pets[i]=pets[i]+'s';
}
console.log(pets);
