### ISSUE TITLE
bytewiser / hex decoding : how to make this work 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#871]
Hello, 

Im this far : 

~~~
for (var i = 2; i < process.argv.length; i++) { 
    var buffer = new Buffer(process.argv[i]); 
    console.log(buffer.toString('hex'))
}

~~~

but now I see more then 1 output where the exercise expect only 1 output. 
Must I convert the buffers.toString to one string maybe to solve this ?

Roelof

**Comment by martinheidegger** [comment]
Well, the description says:

> should be **a** string of two-character pairs

Running `console.log` within a loop will be usually run more than once.

**Comment by roelof1967** [comment]
I could if I know how I can combine it. I think I have to convert it to a string and combine it with outcome = outcome + buffer.toString()

**Comment by martinheidegger** [comment]
You could put them in an array, write more than once to a buffer or concat (`a+a`) a string?!

**Comment by roelof1967** [comment]
I tried it with strings like this : 

`~~~

var buffer = new Buffer(1000);
var length2 = process.argv.length
var solution = '' ;

for (var i = 2; i < length2; i++) {
    solution = solution + process.argv[i];
    buffer.write(solution, 'hex');
}

console.log(buffer.toString('hex'))

~~~ 

but now I see a invalid hex string error message.

**Comment by martinheidegger** [comment]
@roelof1967 

First you should think about the use of your `solution` variable (there is an obvious mistake that can be found by thinking how the variable is used).

Aside from that: in `buffer.write(..., 'hex')` you assume that whatever you write is a hex string but the description for bytewiser says:

> Given an unknown number of bytes

Maybe you need another way of filling the buffer.

Sidenote: `new Buffer(1000)` is probably not a good idea...

**Comment by roelof1967** [comment]
Pfff. very frustrating

**Comment by martinheidegger** [comment]
Thats part of the learning process. If it were easy it wouldn't be fun :smiley: 
If you can identify a pain-point that makes sense to fix: PR's are welcome.
