### ISSUE TITLE
HTTP collector bl

### ISSUE THREAD

**Issue by marioviti** [nodeschool/discussions#874]
In the HTTP collector exercise I'm using bl.

this is my code
```JavaScript
var http = require ('http');
var bl = require ('bl');

http.get(process.argv[2], function callback (response) {

	response.pipe(bl(function(err,data) {

		console.log(data.toString());

	}));
});
```

it does not pass as the outputs are not the same, but not really:

1.    ACTUAL:  "Mad as a bities flamin she'll be right coathanger. You little ripper cane toad piece of piss mad as a bottle-o. He hasn't got a budgie smugglers piece of piss come a bottlo. Grab us a throw-down heaps get a dog up ya kelpie. Trent from punchy kelpie how get a dog up ya dunny."
1.  EXPECTED:  "492"

2.    ACTUAL:  "Get a dog up ya spit the dummy when she'll be right larrikin. Gutful of cook and as dry as a slacker. Get a dog up ya bazza to lets get some lizard drinking. Watch out for the stickybeak no dramas gutful of reckon. "
2.  EXPECTED:  "Mad as a bities flamin she'll be right coathanger. You little ripper cane toad piece of piss mad as a bottle-o. He hasn't got a budgie smugglers piece of piss come a bottlo. Grab us a throw-down heaps get a dog up ya kelpie. Trent from punchy kelpie how get a dog up ya dunny."

3.    ACTUAL:  ""
3.  EXPECTED:  "Get a dog up ya spit the dummy when she'll be right larrikin. Gutful of cook and as dry as a slacker. Get a dog up ya bazza to lets get some lizard drinking. Watch out for the stickybeak no dramas gutful of reckon. "

Looks like the first entry is lost even if it has three outputs, I presume 3 chunks are buffered and than processed (logged to console) based on the appearance of a end (I say presume because I reckon pipes in c are read as a filedescriptor).

Why the first chunk is lost?

**Comment by martinheidegger** [comment]
@marioviti The first chunk is not lost. The specification in the exercise mentions

> The first line you write should just be an integer representing the number of characters received from the server.

This is missing from your solution.

**Comment by br3wb0n1k** [comment]
Helped me out big time, thanks guys!

**Comment by martinheidegger** [comment]
Awesome!
