### ISSUE TITLE
Javascripting...always error

### ISSUE THREAD

**Issue by Matsuken** [nodeschool/discussions#877]
I did the first two years, but always returns error. Apparently not show my attempt.
The file was created and the code is correct.

///////////////////////////////// Terminal: ////////////////////////////

## Check your solution:

Solution
===================

some string

Your Attempt
===================

Difference
===================

some string

/////////////////////////////////////Thank's !/////////////////////////////

**Comment by khalifenizar** [comment]
Hey there! Could you please post your code and the output of the `npm -g ls --depth=0` command? I'd like to see which version of `javascripting` you are using because mine seems to be expecting the string *'this is a string'*.

**Comment by SomeoneWeird** [comment]
@khalifenizar The solution for *variables* is `some string` :)

**Comment by Matsuken** [comment]
Hi khalifenizar, thanks for your reply... this is the output:

npm -g ls --depth=0
/usr/local/lib
├── javascripting@1.10.1
└── npm@1.4.28

All exercises I realized having the same problem. This is the code of one of them, is a very simple example:
////
var example;
var example = 'some string';
console.log(example);

**Comment by SomeoneWeird** [comment]
@Matsuken are you sure you've selected the correct problem?

**Comment by khalifenizar** [comment]
@Matsuken to @SomeoneWeird's point (thanks for the clarification), could you please run `javascripting print`? Which exercise instructions do you get?

What operating system are you running this on?

**Comment by Matsuken** [comment]
@khalifenizar , @SomeoneWeird , thanks for your help:

1) These are the instructions for the exercise (the same happend with the first one, which is even simpler).
/*
Create a file named variables.js.
In that file declare a variable named example.
Make the variable example equal to the value 'some string'.
Then use console.log() to print the example variable to the console.
Check to see if your program is correct by running this command:
## javascripting verify variables.js
*/
2) OSX Maverics.

3) variables.js

I follow every step of the workshop, the only difference was in the beginning, first I had to install it without the -g because I got many error messages and could'nt load. Then i do it again using sudo , as shown in some discussion.
Maybe is an installation problem.
