### ISSUE TITLE
how to make webservice(http/soap) api calls with the oauth2 token

### ISSUE THREAD

**Issue by g3hk** [nodeschool/discussions#878]
how to make webservice(http/soap) api calls with the oauth2 token

where to set the token and gain access for webservice calls...soap npm also i checked the example is not so clear

**Comment by martinheidegger** [comment]
@g3hk It is not quite clear what you are talking about :sweat_smile: but thank you for submitting your question here. Do you try to do an API call as part of working through a tutorial? (I have not yet read all tutorials but I don't remember any exercise about that)

If you don't then probably all you need to do is add the oauth token to the headers. Can you elaborate a little more on your problem?

**Comment by g3hk** [comment]
Yes i want to know how to add the oauth token to headers and make a api call

**Comment by g3hk** [comment]
ie how to make a webservice call adding tokens to de headers. Can u give me any sample code???

**Comment by martinheidegger** [comment]
@g3hk Node.js's [`http].request`](http://nodejs.org/api/http.html#http_http_request_options_callback) Offers to define headers in a request:
```JavaScript
var http = require("http")
http.request({
  host: "google.com",
  method: "GET",
  headers: {
     "Authorization": "Bearer <token>"
  }
}, function (response) {
  //...
})
```

This assumes that the token is already properly formatted. There are [other packages](https://www.npmjs.com/search?q=oauth) in npm that help with oauth. [request](https://www.npmjs.com/package/request) has been very helpful to me, and has an [oauth example](https://github.com/request/request/tree/master/examples).

Does that answer your question? :smile:

**Comment by g3hk** [comment]
http://127.0.0.1:9090/server/tutorial/customerws

customersws - is a webservice written in .net which returns a list of customers. Now how to call this api url using the token like this "12dsgfdgdghdf#$545wrwerwet12232@"  generated by the oauth2...

Will this example work for the above code. If i give the url in "http://127.0.0.1:9090/server/tutorial/customerws" in host attribute will it work...I'm really new to node. Please help me in this.

Many Thanks,

**Comment by g3hk** [comment]
And also i'm unable to browse the URL http://127.0.0.1:9090/server/tutorial/customerws and get the wsdl url ...I want to know whether to assign this url "http://127.0.0.1:9090/server/tutorial/customerws" in host or i have to browse this url and get the WSDL url and assign it to the host.

**Comment by martinheidegger** [comment]
The `host` is the domain so in your example `127.0.0.1` (this is not node-specific). You will also need to add `port: 9090` to have it set using the right port. It should also have `path: "/server/tutorial/customerws"`. The nodejs core library is written to be used with some other systems. I strongly recommend that you use [request](https://www.npmjs.com/package/request) since it makes your task a lot easier.

If you have a project make sure that it has a `package.json`. Then install request with `npm i request -save` and then use it like:

```JavaScript
var request = require('request');

var options = {
    url: 'http://127.0.0.1:9090/repos/request/request',
    headers: {
        'Authorization': 'Bearer <token>'
    }
};

function callback(error, response, body) {
    if (!error && response.statusCode == 200) {
       console.log(body);
    } else {
       console.log(error || response.statusCode);
    }
}

request(options, callback);
```

Are you able to do your request with this?
