### ISSUE TITLE
ES6 generators workshooper

### ISSUE THREAD

**Issue by isRuslan** [nodeschool/discussions#879]
Hi everyone.
I've made [learn-generators](https://github.com/isRuslan/learn-generators) workshopper.
Any issues, feedback or promotions would be welcome. Thanks!

**Comment by sudodoki** [comment]
Related discussion in workshopper repo. https://github.com/nodeschool/workshoppers/issues/29

**Comment by sudodoki** [comment]
Maybe, do a PR with link to workshopper?

**Comment by martinheidegger** [comment]
Hey @isRuslan Thank you! This is awesome and should be put to [the homepage](https://github.com/nodeschool/nodeschool.github.io)! PR anyone?

**Comment by isRuslan** [comment]
PR: nodeschool/nodeschool.github.io#217
@martinheidegger @sudodoki Thanks!

**Comment by martinheidegger** [comment]
Closing this issue if you don't mind :smile:
