### ISSUE TITLE
juggling async problem! Closure doesn't work.

### ISSUE THREAD

**Issue by dkure** [nodeschool/discussions#880]
Learnyounode is great! I have been having fun with it so far.

 I have been having problems with juggling async. 
As you can see, I have tried using closures, after reading up on the problem. 
But it is still not working. I don't know what is wrong. 

    for (var i = 2; i < process.argv.length; i++) {
      (function(index) {
        http.get(process.argv[index], function (response) {
          response.pipe(bl(function (err, data) {
            console.log(data.toString());
          }));
        });
      })(i);
    }

Thanks you in advance!

**Comment by davecocoa** [comment]
I'm glad you'd been having fun!

Your solution is successfully fetching the correct urls, but it is logging them out of order - in the order in which the responses arrive.

Right now, although you are using a closure to save the `index` variable, you aren't actually using it apart from starting your http requests - so your code would run the same without it. Each of your http requests start in the loop, and each of the requests has a callback which immediately logs the response.

In order to log the responses in the correct order, you need to save them somewhere, and then log them once *all* the requests have completed. Does that help you move in the right direction?

**Comment by dkure** [comment]
var dataArray = new Array();

    for (var i = 2; i < process.argv.length; i++) {
      (function(index) {
        return (function(index){
          http.get(process.argv[index], function (response) {
            response.pipe(bl(function (err, data) {
              dataArray.push(data);
            }));
          });
        })(index);
     })(i);
    }

    console.log(dataArray);

Only prints out an empty array unfortunately!
I assume it is because the log is being called before the response have actually been pushed to the data?

**Comment by davecocoa** [comment]
Yes, you are absolutely correct and you are on the right track!

However, you don't need the closure around `response`. Also, if you simply push items onto the array as soon as responses arrive, you'll end up with the same ordering problems.

You'll want some kind of test, in the scope where you currently have `dataArray.push(data);`, so that you can tell when all the requests have completed. For example, if you incremented a `counter`, then you could check `if(counter === 3) { console.log(dataArray); }`. (You actually still need to log each response separately but hopefully this gives you the right idea)

**Comment by dkure** [comment]
for (var i = 2; i < process.argv.length; i++) {
      (function(index) {
        return (function(index){
          http.get(process.argv[index], function (response) {
            (function(response){
              response.pipe(bl(function (err, data) {
                counter++;
                dataArray.push(data.toString());
                if(counter === 3){
                   dataArray.forEach(function(currentValue, index, array){
                     console.log(currentValue);
                  });
                }
              }));
            })(response);
          });
        })(index);
      })(i);
    }

Not gotten there yet it seems.
Is my counter off? It seems to print the exact opposite from how they were added into the array... when I run learnyounode verify.

**Comment by davecocoa** [comment]
You're so close!

Your last problem is `dataArray.push`, this is adding responses to the end of the array *as they arrive* but we want to maintain the original order using `index`.

It's possible to assign an element to a certain position in an array using square brackets like this:
```js
arr[2] = 'some string';
arr[1] = 'some other string';
console.log(arr); // [undefined, 'some other string', 'some string']
```

**Comment by dkure** [comment]
Oh I see.
I was thinking that the isolated index made sure somehow that the requests would be carried out in order(this doesn't seem possible now).

The way it works from my understanding is as follows:

The for loop iterator ensures that the urls are given to the program in the order they were typed it. The http.get method then GET's the data for each request, the callbacks for each request still happen at random (when the get method is ready with data),  but this time, we're keeping track of each   response as we add it to the new array through our counter.  The callbacks are still called in whatever order is appropriate(whichever one responds fastest) , but we're using the isolated index to ensure each response data is added to the array in the right order!

..I hope that makes sense. Sorry if it's a bit daft! 

  var dataArray = new Array();
     var counter = 0;

    for (var i = 2; i < process.argv.length; i++) {
      (function(index) {
        return (function(index){
          http.get(process.argv[index], function (response) {
            (function(response){
              response.pipe(bl(function (err, data) {
                counter++;
                dataArray[index] = data.toString();
                if(counter === 3){
                   for (var i = 2; i < dataArray.length; i++) {
                     console.log(dataArray[i]);
                   }
                }
              }));
            })(response);
          });
        })(index);
      })(i);
    }

**Comment by davecocoa** [comment]
Yes, that's it exactly, well done!

When I ran that code on my machine, it passed the exercise, is it passing for you? If you're happy that you've solved your problem, you can go ahead and close this issue.

**Comment by dkure** [comment]
Yes it passed. 

Thank you very much!

**Comment by davecocoa** [comment]
As regards other ways of doing this, the solution provided by `learnyounode` is a good place to start. If I was solving it with promises, it would look like this:

```js
var Q = require('q'); // this is just one promise library, they all provide similar functions
var httpGet = Q.denodeify(http.get); // takes a callback based functio and returns a promise based function
var urls = process.argv.slice(2); // this gives an array of just the urls
var requests = urls.map(function(url) { return httpGet(url); });
Q.all(requests)
  .then(function(responses){ responses.forEach(console.log); })
```

So I'm skipping the `bl` step, but that's roughly the structure I would use. If you have any other questions feel free to ask.
