### ISSUE TITLE
My first i/o 

### ISSUE THREAD

**Issue by landan240** [nodeschool/discussions#886]
So I have this:

```JavaScript
var fs = require('fs') ;

var file = process.argv[2]
var buf = fs.readFileSync(file)
var str = buf.toString();

var lines = str.split('n')

console.log(lines)

```

And I get "path must be a string". I thought the buf.toString part would do that for me, 
What am i doing wrong?

**Comment by SomeoneWeird** [comment]
Are you running this file with `learnyounode run <file.js>`? If not, `process.argv[2]` will be `undefined` and cause an error.

**Comment by landan240** [comment]
I was running it with node, but when i ran it with learnyounode, I got the whole story that my code is supposed to process.

**Comment by SomeoneWeird** [comment]
Great. Let me know if you need any more help, if not, you can close this issue :)

**Comment by landan240** [comment]
When i verify, it still says I'm incorrect.
![firstio](https://cloud.githubusercontent.com/assets/10608530/5911478/db08acaa-a57a-11e4-9d40-188b2600e788.JPG)

**Comment by SomeoneWeird** [comment]
Can you paste your current code?

**Comment by landan240** [comment]
Here you go:

var fs = require('fs') ;

var file = process.argv[2];
var buf = fs.readFileSync(file);
var str = buf.toString();

var lines = str.split('\n');

console.log(lines);

**Comment by SomeoneWeird** [comment]
This problem is asking you for the *number* of lines in the file, not the actual lines :)

**Comment by landan240** [comment]
So how would I get it as a number? I'm still kinda confused as to what the " str.split('\n') " part does.

**Comment by Trott** [comment]
`\n` is a newline character. It indicates that one line is finished and a new line follows.

`split()` returns an array.

So, `split('\n')` returns an array where each line in the string is an element in the array.

So, to solve the problem, you need to know how to find the number of elements in an array.

**Comment by landan240** [comment]
Thanks for that. 
I used the .length property, and now i get an answer of 28 when the correct answer is 29
Here's my code:

var fs = require('fs') ;

var file = process.argv[2];
var buf = fs.readFileSync(file);
var str = buf.toString();

var lines = str.split('\n');
var number = lines.length

console.log(number);

and I get this screen:
![first io answer](https://cloud.githubusercontent.com/assets/10608530/5911799/566406e8-a57f-11e4-84cf-a67367bdc7e8.JPG)

**Comment by SomeoneWeird** [comment]
@landan240 Have you been through `javascripting`? It may be worth going through that to explain how arrays work etc.

**Comment by landan240** [comment]
Yes, I did complete javascripting very recently.
Figured out my problem. Thanks Guys!

**Comment by SomeoneWeird** [comment]
Awesome! Open another issue if you need more help :)
