### ISSUE TITLE
Documentation does not describe how to run the tutorials without -g installation

### ISSUE THREAD

**Issue by mobiletesteryandex** [nodeschool/discussions#887]
I am not able to run the nodejs tutorials.  Not everyone always has sudo access. I installed under my local user without -g option due to permissions.  Many people will chose to install in user directory.  Now I am not able to run any tutorials like javascripting.  It simply does not find javascripting.  I added everything to $PATH including /user/MAC1/node_modules/javascripting:node/user/MAC1/node_modules 
etc
but it does not find or run anything.

**Comment by martinheidegger** [comment]
@mobiletesteryandex "without -g" is is the keyword for your problem. The javascripting command will be globally only available using "-g"! On mac - if you use the regular installer - you will need to add `sudo`.

If you install it locally (opposite of -g) then the binary will be installed in the subfolder `node_modules/.bin`. You can run javascripting by either running it in always prefixed `./node_modules/bin/javascripting` or by navigating into that folder.

**Comment by mobiletesteryandex** [comment]
Yes,     
 node_modules/.bin.

That's what I was looking for.
