### ISSUE TITLE
Filtered LS - Help Please

### ISSUE THREAD

**Issue by genericlady** [nodeschool/discussions#888]
Ok so i'm having a rough time with this exercise.  I think my problem is I'm not understanding what they are asking for.  when I use the run command it returns "filename.txt" != "16".  Why is it listing a number?  Should I be listing all the directory contents but filter the results by extension first?
```javascript
var fs = require('fs');
var path = require('path');
var fullPath = path.dirname(process.argv[2]);

function txtPrint(file) {
	if (path.extname(file) == '.txt') {console.log(file)};
}

fs.readdir(fullPath, function(err, list) {
	if (err) throw err;
	list.forEach(txtPrint);
})
```
// Create a program that prints a list of files in a given directory, filtered 
// by the extension of the files. You will be provided a directory name as the 
// first argument to your program (e.g. '/path/to/dir/') and a file extension 
// to filter by as the second argument.
// 
// For example, if you get 'txt' as the second argument then you will need to 
// filter the list to only files that end with .txt. Note that the second 
// argument will not come prefixed with a '.'.
// 
// The list of files should be printed to the console, one file per line. 
// Use asynchronous I/O.

**Comment by martinheidegger** [comment]
@genericlady Could it be that you selected the wrong exercise? Can you try to select filtered-ls again and then verify once more?

**Comment by genericlady** [comment]
ahh ok!  that worked.  I didn't get the answer right but I can work from here.  Thanks!

**Comment by martinheidegger** [comment]
Awesome! Just open an issue if you have future problems. Cheers!
