### ISSUE TITLE
Filtered LS - Correct DIR?

### ISSUE THREAD

**Issue by genericlady** [nodeschool/discussions#889]
Am I in the right directory?  Maybe I'm mis-understanding how many arguments learnyounode passes?  Some hints would be great!  I know my truthy statement is off.  Should I be comparing to a value stored into a variable from the argument I'm possibly missing?

I don't fully understand how learnyounode is passing in arguments.

```javascript
var fs = require('fs');
var path = require('path');
var fullPath = path.dirname(process.argv[2]);

console.log(fullPath);

function txtPrint(file) {
	if (path.extname(file) == 'txt') {};
}

fs.readdir(fullPath, function(err, list) {
	if (err) throw err;
	list.forEach(txtPrint);
})
```
This is the full path that gets printed from console.log
/var/folders/wx/q7njx98d3_z5f_b602d4rmmr0000gn/T

**Comment by martinheidegger** [comment]
@genericlady The folder should be fine. For the tests `learnyounode` generates a temporary folder for you to work on afaik. Does it work with this folder? :wink:

**Comment by genericlady** [comment]
don't close this thread right away let me think about it, lol

**Comment by genericlady** [comment]
@martinheidegger don't close this thread right away let me think about it, lol

**Comment by genericlady** [comment]
@martinheidegger I don't want the folder to be fine for tests :P  which is the right folder?  I'm doing it wrong!  argh!  lol

**Comment by martinheidegger** [comment]
`/var/folders/wx/q7njx98d3_z5f_b602d4rmmr0000gn/T` should be the right folder to run `fs.readdir`!

If you run `ls -l /var/folders/wx/q7njx98d3_z5f_b602d4rmmr0000gn/T` you should get a list of files. (if not we have a problem)

This is a temporary folder created by `learnyounode` that gives you test data. Did you ever try and output the files that `fs.readdir` is returning. Like:

```JavaScript
var fs = require('fs');
var path = require('path');
var fullPath = path.dirname(process.argv[2]);

function txtPrint(file) {
    if (path.extname(file) == 'txt') {
        console.log(file);
    };
}

fs.readdir(fullPath, function(err, list) {
    if (err) throw err;
    list.forEach(txtPrint);
})
```

**Comment by genericlady** [comment]
@martinheidegger yeah and prints nothing because something is wrong with the truthy.  i've tried 'txt', '.txt', 'md, '.md' etc...  There's something I'm not grasping.  It's right in front of me...

**Comment by genericlady** [comment]
Also @martinheidegger there's a lot of files in /var/folders/wx/q7njx98d3_z5f_b602d4rmmr0000gn/T that are not from learnyounode.  maybe i shouldn't use the path.dirname method?

**Comment by martinheidegger** [comment]
Oh! Yes! I completely missed that 'path.dirname' is wrong here. Sorry for overlooking that.

**Comment by genericlady** [comment]
@martinheidegger PASS!  Thank you!
