### ISSUE TITLE
Can't pass MAKE IT MODULAR

### ISSUE THREAD

**Issue by clipclapclop** [nodeschool/discussions#89]
I get the following failure message with the below code. I've tried lots of different things but don't know how to make it pass. I'd appreciate any insight that you can give. Thanks.

<pre><code>Verifying "MAKE IT MODULAR"...
ACTUAL                             EXPECTED

---

"CHANGELOG.md"                     "CHANGELOG.md"  
"LICENCE.md"                       "LICENCE.md"  
"README.md"                        "README.md"  
""                                 ""  
Your additional module file:
    /home/chad/mymodule.js
did not return an Array with the correct number of elements as the second argument of the callback
# FAIL

Your solution to MAKE IT MODULAR didn't pass. Try again!</pre></code>

project.js
<pre><code>
var mymodule = require('./mymodule.js');
var dir = process.argv[2];
var filter = new RegExp('\.' + process.argv[3] + '$');
mymodule(dir, filter, function(err, value){
    value.forEach(function (file) {
        console.log(file);
    })
});
</pre></code>

mymodule.js
<pre><code>
var fs = require('fs');
var result = [];
module.exports = function DirFilt(dir, spec, callback) {
    var spec = new RegExp('\.' + process.argv[3] + '$');
    fs.readdir(dir, function (err, list) {
        if(err) 
            return callback(err, result);
        result = list.filter(function (file) {  
            return spec.test(file);
        })  
        return callback(null, result);
    })
}
</pre></code>

**Comment by m009arroyo** [comment]
I have a solution. Has worked for me. 
PROGRAM
```javascript
var myModule = require('./module');
var dir = "./file/";
var ext = "md";

myModule(dir, ext, function (err, data) 
         {
             if (err) return console.log('ERROR');
             
             data.forEach(function (d)
             {
                 console.log(d.toString());
             });
         });
```
MODULE
```javascript
var fs = require('fs'),
path = require('path');

module.exports = function (directory, filter, callback)
{
    fs.readdir(directory, function (err, list) {
      if (err) return callback(err); // early return
      var elements = [];
      list.forEach(function(element)
                  {
                      if(path.extname(element) === "." + filter ) 
                      {
                          elements.push(element);
                      }
                  });
      callback(null, elements);
    });
}
```

**Comment by MatejMatula** [comment]
I have same problem , here is my code 

Module[code]
module.exports = function (one, two, callback) {
    var fs = require("fs");
    var path = require("path");
    var konc = "." + two;
    fs.readdir(one, function (err, list) {
        if (err) return callback(err);
        var list = list.filter(function (x) {
            return path.extname(x) == konc;
        });
        callback(null, list)
    })
}
[/code]
program
[code]

var module=require("./module.js");
module(process.argv[2],process.argv[3],function(err,list){
if(err) return console.log("error",err);
list.forEach(function(v){
	console.log(v)
})
})
[/code]
It says but it results in erro = 
? Submission results did not match expected!
? Did not use an additional module file, you must require() a module to help sol
ve this exercise

FAIL
any help?

**Comment by skycutecat** [comment]
@MatejMatula 

Because you are wrong in variable scope declaration.

look forward your module code. 

```
fs.readdir(one, function (err, list) {
if (err) return callback(err);
var list = list.filter(function (x) {
return path.extname(x) == konc;
});
```

var list  is different  function (err, 'list')

when you declare list again, the outside list will be covered. Therefor you must modify 'var list' name to other name

**Comment by chkry** [comment]
NAME : CHAKRI REDDY
WEBSITE : www.chakrireddy.com

**MODULE CODE :**
```
var fs = require('fs');
var path = require('path');

module.exports = function (dir, ext, callback) {
  fs.readdir(dir, function (err, files) {
    if (err) return callback(err);
    var filteredFiles =  files.filter(function (file) {
    	var fext = "."+ ext;
      return path.extname(file) === fext;
    });
    return callback(null, filteredFiles);
  });
};
```



**FILE :**
```
var filteredls = require('./moduleRequest');
var argv = process.argv;
var dir = argv[2];
var ext = argv[3];

filteredls(dir, ext, function(err, files) {
  if (err) return err;
  files.forEach(function (file) {
    console.log(file);
  });
});

```

Works perfect and is successfully executed

**Comment by multimatex** [comment]
I have a problem: your aditional module file may be matching "ext" instead of ".ext"

Please Help
### **Main:**

`var Mym = require('./mimodulo');

var direccion_directorio = process.argv[2];
var extension_a_filtrar= process.argv[3];

function imprimir_listado(error,objeto)
{
	if (error) {
		return console.error('',error);
	} else {
		
		for (var i = 0; i < objeto.length; i++) {
			console.log(objeto[i]);
		}
		
	}

	
}

Mym(direccion_directorio,extension_a_filtrar,imprimir_listado);`

**### Module:**

`module.exports = function (path_del_directorio,nombre_de_la_extension,cb_imprimir_listado)
{
	var fs = require('fs');
	var path = require('path');

	//var nombre_extension = '.'+ nombre_de_la_extension; //previous code

fs.readdir(path_del_directorio,cb_listado);

function cb_listado(error,lista)
{
	if (error) {
		return cb_imprimir_listado(error);
	} 

		else {

			var acumulador = '';	
	for (var i = 0; i < lista.length; i++) {
		if(path.extname(lista[i]) === '.'+nombre_de_la_extension)//before: if (path.extname(lista[i]) === '.'+nombre_extension)
		{
			//console.log('.'+nombre_de_la_extension); some test here
			acumulador = acumulador + lista[i]+'\n';
		}
	}
		//console.log(nombre_extension); some test here
		return cb_imprimir_listado(null,acumulador.split('\n'));
		}
}

}`

**Comment by samuelzapote** [comment]
I will be leaving a comment, for those having the same problem as I was having. I had the right solution and proper output, but `learnyounode verify program.js` would keep giving me an error, breaking towards the end, or would tell me an array was not returned as the second argument. 

Solution: 

>Module File I named "readftext", it stands for Read Filter Extensions, In your example if can be whatever you want it to be.

>**readftext.js** 

```
var fs = require('fs');
var path = require('path');

module.exports =
    function (dirpath, extin, callback){
        fs.readdir(dirpath, (err, list)=>{
            if(err){
                return callback(err);
            }else {
                var retlist = [];
                list.forEach((file)=>{
                    var ext = '.' + extin; 
                    if(path.extname(file) == ext) {
                        retlist.push(file);
                    }
                });
                callback(null, retlist);
            }
        });
    };

```
 
>**program.js**

```
var fs = require('fs');
var extfil = require('./readfext');
var pathdir = process.argv[2];
var ext = process.argv[3];

extfil(pathdir, ext, (err, data)=>{
    if(err){
        console.log(err);
    }else {
        for(var i=0;i<data.length;i++){
            console.log(data[i]);
        }
    }
});

```

See how: 

- Empty array variable was made
- Files that matched the criteria were added to the array using **.push()**
- The array was included as the second argument in the callback
- A For loop was used in the **program.js** file to log all the separate files onto the console

This is a solution for those who's thought process was going this general direction. Both this solution and the next are functional solutions. It all comes down to how you choose to code, or how your employer wants you to code. In my opinion, the second solution is a lot faster to read, seeing as how its using predefined functions that help you **filter** and run through an array with **forEach** and how it was made with less lines of code, making your code cleaner. Not all languages use the same predetermined functions and maybe you consider the next solution a more professional solution, It depends on what you want to do. But as a beginner, it is nature to solve problems with the tools given to you, maybe now that you see the solution, you can be more informed on faster ways to write certain solutions with NodeJS. 

Both my problems were fixed and was given the solution they used as well, thus completing the verification. If you want that example too here it is.

```
var filterFn = require('./solution_filter.js')
    var dir = process.argv[2]
    var filterStr = process.argv[3]

    filterFn(dir, filterStr, function (err, list) {
      if (err) {
        return console.error('There was an error:', err)
      }

      list.forEach(function (file) {
        console.log(file)
      })
    })

```

```

var fs = require('fs')
    var path = require('path')

    module.exports = function (dir, filterStr, callback) {
      fs.readdir(dir, function (err, list) {
        if (err) {
          return callback(err)
        }

        list = list.filter(function (file) {
          return path.extname(file) === '.' + filterStr
        })

        callback(null, list)
      })
    }

```
