### ISSUE TITLE
"javascripting verify introduction.js" - NOT WORKING

### ISSUE THREAD

**Issue by z82n** [nodeschool/discussions#890]
The first exercise doesn't work for me

> javascripting verify introduction.js
>

I tried uninstalling and reinstalling node, to no avail

**Comment by martinheidegger** [comment]
Hello @z82n! Thanks for posting your issue.

Let me ask some basic questions: 
1. What happens when you enter `pwd` in the command line?
2. What happens when you enter `node -v` in the command line?
3. What happens when you enter `npm -v` in the command line?

**Comment by rahleak** [comment]
Found this discussion and there isn't a solution posted! I'm having the same issue.
pwd: home/vagrant/javascripting
node -v: v12.19.0
npm -v: 6.14.8

I know this is a super old thread but help would be appreciated!
