### ISSUE TITLE
Wiki or markdown files?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/discussions#891]
Which do you think we should use for general documentation?

**Comment by martinheidegger** [comment]
My opinion is to drop the wiki. It is hard to make PR's against it and generally has a lower visibility than markdown files.

ping @a0viedo: do you want to chime in?

**Comment by a0viedo** [comment]
I was just thinking the same thing, the visibility of the wiki it's not the same as a markdown file in the repo, so I'm +1ing markdown files.

**Comment by paul-byford** [comment]
Markdowm

**Comment by martinheidegger** [comment]
I guess that are about the response I can expect. Thank you for your opinion @a0viedo and @paul-byford will move the wiki at some point to markdown files. cheers!

**Comment by Sequoia** [comment]
Oh dang I'm sorry I missed this :(

The wiki is just:
1. A repo of markdown files (clone ours here: https://github.com/nodeschool/discussions.wiki.git )
2. Auto-building menu/navigation

### Other thoughts
* Making the wiki visible is as simple as linking to it at the top of `readme.md` and/or in project description.
* The disadvantage of using the main repo is that **menus & navigation has to be managed manually** whereas with wiki you get this for free.
* Lack of PR workflow is a :star: feature :star: not a bug. PR is too heavy-weight for wiki docs here, no server is going to crash if someone changes a wiki file. Consequences of change are low & ATM our problem is too *few* contributions, not too 
* Waiting for PR acceptance (especially absent a formal review process) can lead to bothersome conflicts-- see https://github.com/nodeschool/discussions/pull/861 https://github.com/nodeschool/discussions/pull/935 <-- this was a needless pain in the butt
* Beginners **may not understand how to navigate a repo of markdown files**. On the wiki this implementation detail is hidden & they just see a nice, familiar looking menu.

+1 **Wiki**

**Comment by Sequoia** [comment]
w/e I guess whoever wants to write the stuff can pick where to put it :smile_cat:
