### ISSUE TITLE
javascripting verify 'silent'

### ISSUE THREAD

**Issue by paul-byford** [nodeschool/discussions#892]
i've managed to install javascripting and run it. after i create the introduction.js file and run the command javascripting verify introduction.js i get a 'silent' response. the machine seems to process for a while and then just load a new command prompt line with no response from the last command

i'm running windows 7, node -v is v0.10.32

**Comment by SomeoneWeird** [comment]
That's strange! Can you upgrade node and see if it fixes the problem?

**Comment by paul-byford** [comment]
unfortunately this did not work node -v is now v0.10.36 . 

same 'silent response'

**Comment by paul-byford** [comment]
i just installed learnyounode and ran it. learnyounode verify introduction.js worked and produced an output.

**Comment by sethvincent** [comment]
this came up for another user recently.

@paul-byford take a look at this: https://github.com/nodeschool/discussions/wiki/Installation-suggestions#windows

is that how you installed `javascripting`?

**Comment by SomeoneWeird** [comment]
I just installed win8 in a vm, installed node and then installed javascripting. Afraid I can't replicate this issue :\

**Comment by martinheidegger** [comment]
@paulford in which folder are you running javascripting?

**Comment by paul-byford** [comment]
i installed node as described. i've already got git installed. i also just tried uninstalling javascripting with npm and then reinstalled javascrpting with npm. this did not fix the issue

i'm running from a folder on my c drive that i created to hold my introduction.js file

what is bizarre is the learnyounode verify command works. it looks at the file and gives me the result. javascripting is still silent.

any other ideas?
thanks

**Comment by martinheidegger** [comment]
@paul-byford It seems to be a problem with Javascripting. I submitted [a PR](https://github.com/sethvincent/javascripting/pull/53). The silent response is there because one error-case has not been handled correctly. Before a new version of javascripting with a fix is published try to run `node introduction.js` because this will likely show what error you had.

**Comment by paul-byford** [comment]
thanks martin. running node introduction.js prints hello to the terminal, which is what I would expect. it is the first lesson which just contains console.log('hello')

**Comment by martinheidegger** [comment]
It should `just work`(tm) seems like the problem would not be fixed by this bugfix. 
@paul-byford Could you update javascripting? `npm update javascripting -g` What version are you running?

**Comment by paul-byford** [comment]
great, some progress. after running npm update i'm on javascripting@1.10.2 . after running javascripting verify introduction.js i get at output of

Error: Command failed:
module.js:340
    throw err;
          ^
Error: Cannot find module Error: Cannot find module 'C:\Users\pbyf\Google'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

the introduction.js file is there. when i run node introduction.js i get hello output to the console. any ideas

**Comment by martinheidegger** [comment]
Sounds like `javascripting` was not installed properly (how can that happen at first place?). Can you try to remove the last trace of javascripting from your computer (usually `npm r javascripting -g`) and install it again?

**Comment by paul-byford** [comment]
i ran '''npm r javascripting -g''' and it seemed to work, the console responded with '''unbuild javascripting@1.10.2
''' and the files had been removed from my npm folders at ....AppData\Roaming\npm 

I then reinstalled with '''npm install javascripting -g''' and got the response at the console of 

'''C:\Users\pbyf\AppData\Roaming\npm\javascripting -> C:\Users\pbyf\AppData\Roaming\npm\node_modules\javascripting\index.js

javascripting@1.10.2 C:\Users\pbyf\AppData\Roaming\npm\node_modules\javascripting
├── diff@1.2.2
├── colors@1.0.3
├── adventure@2.9.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, split@0.3.2, mkdirp@0.5.0, through2@0.5.1, terminal-menu@2.1.1)
└── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.7, cardinal@0.4.4)
'''
which looked good too.

on running '''javascripting verify introduction.js''' i get the same error message

''' Error: Command failed:
module.js:340
    throw err;
          ^
Error: Cannot find module Error: Cannot find module 'C:\Users\pbyf\Google'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3'''

**Comment by paul-byford** [comment]
i ran `npm r javascripting -g` and it seemed to work, the console responded with a response of
`unbuild javascripting@1.10.2` 
and the files had been removed from my npm folders at ....AppData\Roaming\npm

I then reinstalled with `npm install javascripting -g` and got the response at the console of

```
C:\Users\pbyf\AppData\Roaming\npm\javascripting -> C:\Users\pbyf\AppData\Roaming\npm\node_modules\javascripting\index.js

javascripting@1.10.2 C:\Users\pbyf\AppData\Roaming\npm\node_modules\javascripting
├── diff@1.2.2
├── colors@1.0.3
├── adventure@2.9.0 (inherits@2.0.1, x256@0.0.2, minimist@0.2.0, split@0.3.2, mkdirp@0.5.0, through2@0.5.1, terminal-menu@2.1.1)
└── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.7, cardinal@0.4.4)
```
on running `javascripting verify introduction.js` i get the same error message

```
Error: Command failed:
module.js:340
throw err;
^
Error: Cannot find module Error: Cannot find module 'C:\Users\pbyf\Google'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:929:3 
```

**Comment by sethvincent** [comment]
This part: `Error: Cannot find module Error: Cannot find module 'C:\Users\pbyf\Google'` is saying that something is requiring a module that can't be found. A module at that path named `Google`.

That's super weird! I'm confused about why that would happen. There shouldn't be anything in the internal javascripting code that would do that.

A couple questions:

Does the `learnyounode` command still work? 

Are you running this from windows's built-in cmd prompt or another prompt?

**Comment by paul-byford** [comment]
I see, its good to know what the error means.  

I'm running the commands from the terminal within webstorm.  Learnyounode is still working when I run it from the terminal in webstorm too.

**Comment by scottwngo** [comment]
I'm also getting the same issue.  All I did was install node.js and the javascripting module.  This issue happens when I try to run a learnyounode script as well.

**Comment by sethvincent** [comment]
@paul-byford that's good to know it's not just webstorm i guess.

@scottwngo dang! are you also on windows? what node and npm versions do you have installed?

**Comment by scottwngo** [comment]
npm v. 1.4.28
node v. 0.10.36

**Comment by sethvincent** [comment]
Hey @paul-byford & @scottwngo I'm curious if javascripting v1.10.3 fixes this issue.

Can you try updating javascripting with `npm install -g javascripting`, then trying the verify command again?

**Comment by paul-byford** [comment]
@sethvincent the fix worked. i successfully updated and verified all the the challenges

I'm intrigued, what was the fix?

**Comment by SomeoneWeird** [comment]
@paul-byford There was a problem with error reporting when a file could not be accessed, and another bug that didn't allow solutions with a space in their path to be verified correctly.
