### ISSUE TITLE
Why javascripting excerise output return not correct?

### ISSUE THREAD

**Issue by kamatchipannerselvam** [nodeschool/discussions#895]
Hi am new to nodejs

am trying with node school workshop.

am trying to complete java scripting array filtering exercise 
my code is

```JavaScript
var numbers=['1','2','3','4','5','6','7','8','9']
var filteres=numbers.filter(function(numbers){
  return (numbers % 2 === 0 );
});
console.log(filters);
```

while am testing by node array-filtering.js
it's return [2,4,6,8]

if am check with javascripting verify command it's return it's not correct
let me know why it's happening like that?
I hope some help me. 
Thank you for advance.

**Comment by SomeoneWeird** [comment]
What is the output of javascripting?

**Comment by kamatchipannerselvam** [comment]
This my javascripting out put

# O-oh, something isn't working.

But don't panic!
Check next things:
  1) did you type the name of the file correctly? You can check by running ls in
troduction.js, if you see ls: cannot access introduction.js: No such file or dir
ectory then you should create new file / rename existing or change directories t
o the one with file
  2) make sure you didn't omit parens, since otherwise compiler would not be abl
e to parse it
  3) make sure you didn't do any typos in the string itself

-------------------
Need help? Ask a question at: github.com/nodeschool/discussions/issues

**Comment by SomeoneWeird** [comment]
Can you update javascripting and try again? `npm install javascripting -g`

**Comment by kamatchipannerselvam** [comment]
Wow! thanks 
now I can identify the mistake.
