### ISSUE TITLE
Need help! Which order I need to follow for learn node js using nodeschool workshop?

### ISSUE THREAD

**Issue by kamatchipannerselvam** [nodeschool/discussions#897]
Hi
Am new to learn nodejs
am already started to learn using nodeschool workshop 
I just want to know about the workshop structure
What's the meaning of highlighted yellow/gray color in workshop?
Which order I want to follow?
1. javascripting
2. git-it
3. ?
I hope some one help me to clarify this small doubt.
Thanks for advance

**Comment by martinheidegger** [comment]
@kamatchipannerselvam If you don't know JavaScript then javascripting is at the very beginning for you. http://jsforcats.com/ is another resource to learn it. git-it is basic knowledge for working on any computer-science these days but you can skip it if you just want to learn node (its not an requirement for many other workshopper). There are follow-ups to javascripting like "count to 6" and "functional javascripting" that will not touch `node.js` very much. However for all others `learnyounode` is a very important basic. 

My recommendation is thusly:

0. (git-it if you still need to learn git)
1. javascripting
2. jsforcats.com
3. learnyounode
4. async-you
5. stream-adventure
....
