### ISSUE TITLE
HTTP Client - Run executes successfully.  Verify fails spectacularly.

### ISSUE THREAD

**Issue by elbankster** [nodeschool/discussions#898]
For starters, I'm doing this in Powershell in Windows.

My HTTP Client code:
```javascript
var http = require('http')

http.get(process.argv[2], function (response) {
  response.setEncoding('utf8')
  
  response.on("data", function(data) {
    console.log(data)
  })
  response.on("error", function(error) {
    console.log(error)
  })
})
```
When I run `learnyounode run program.js` I get the following output:

    Barbie
    Beauty
    Fair go
    Aerial pingpong
    Ironman
    Bushranger
    Yabber
    Give it a burl
    Knock
    Offsider

However, when I run `learnyounode verify program.js` it fails amazingly and I get something like the following (only showing a snippet for the sake of space):

    "Holy dooley!"                      !=    "{ _readableState: "
    "Fruit loop"                        !=    "   { highWaterMark: 16384,"
    "Cactus mate"                       !=    "     buffer: [],"
    "Bazza"                             !=    "     length: 0,"
    "Digger"                            !=    "     pipes: null,"
    "Outback"                           !=    "     pipesCount: 0,"
    "Brekkie"                           !=    "     flowing: false,"
    "Dole bludger"                      !=    "     ended: false,"
    "Ten Clicks away"                   !=    "     endEmitted: false,"
    "Two up"                            !=    "     reading: false,"
    ""                                  !=    "     calledRead: false,"
                                        !=    "     needReadable: false,"
                                        !=    "     emittedReadable: false,"
                                        !=    "     readableListening: false,"
                                        !=    "     objectMode: false,"
                                        !=    "     defaultEncoding: 'utf8',"
                                        !=    "     ranOut: false,"
                                        !=    "     awaitDrain: 0,"
                                        !=    "     readingMore: false,"
 
                                            ...cont'd

Any idea what's going on here?

**Comment by cmalcom** [comment]
Just a guess... I am on a later exercise and cannot verify my idea:
My code passed and is almost identical.  The only difference is that, around the on("data" and on.("error"  I have single quotes.  .on('data'  etc.

Maybe that'll help

**Comment by elbankster** [comment]
Thanks.  Tried changing that.  Still no love.

**Comment by martinheidegger** [comment]
@elbankster This should work. The code doesn't contain any identifiable error. Most likely its a problem with your setup (bug in node, windows combinations, something weird...). What version of node are you running? `node -v` What version of Windows is that on?

**Comment by elbankster** [comment]
Running v0.10.36 here.

**Comment by martinheidegger** [comment]
Just to remind you: the version of windows would be important.

**Comment by elbankster** [comment]
Version of Windows is 7 Enterprise, 64-bit.

**Comment by martinheidegger** [comment]
@elbankster Can you try with node 0.12?

**Comment by gelogenic** [comment]
@elbankster It's unclear from your original post whether you are using Powershell to run the node code or just as your text editor. In case you are running from Powershell, it might be worth invoking the learnyounode exercises using CMD instead. See http://www.appveyor.com/docs/lang/nodejs-iojs#wrong-output-encoding 

Or, per the entry immediate below the previous-provided URL (http://www.appveyor.com/docs/lang/nodejs-iojs#garbled-or-missing-output ), try using node 0.12.x

FWIW, I'm working throught nodeschool.io on Windows 7 Enterprise, running io.js as my node environment, invoking scripts via either the CMD or else the 'git bash' shell that came along with installing the Git for Windows client.

Hope this is helpful.
