### ISSUE TITLE
Juggling Async : It's killing me.

### ISSUE THREAD

**Issue by cmalcom** [nodeschool/discussions#899]
I understand what's happening here, I am just not sure how to solve it.
Can anyone help?

Below is my js code.  I am running it using this command:
c:\> node 9_CountAndPrintMany.js "http://www.amazon.com" "http://www.bn.com" "http://www.google.com"

It obviously calls GetEndpoint on each passed in, and then calls the callback which prints "Finished."
But, i need it to wait in between the items in the series.
I am looking more for a conceptual answer on how this should be done.

Thanks!

```js
var http = require('http');
const bufferList = require('bl');
var async = require('async');

var endpoint1 = process.argv[2];
var endpoint2 = process.argv[3];
var endpoint3 = process.argv[4];

var printStuff = function(error, data){
	console.log("printStuff called");
	if(!error){
		console.log(data.toString());
	}
}

async.series(
[ 
	function(printStuff){
		var data = GetEndpoint(endpoint1);
		printStuff(null, data);
	},
	function(printStuff){
		var data = GetEndpoint(endpoint2);
		printStuff(null, data);
	},
	function(printStuff){
		var data = GetEndpoint(endpoint3);
		printStuff(null, data);
	},
],function(response){ 
	console.log("Finished: " + response);
	
	});

function GetEndpoint(location){
	var bl = new bufferList();
	console.log("Calling GET on : " + location);
	http.get(location, function(response){
		response.on('data',  function(data)	{ 
			console.log("Data of : " + location);
			bl.append(data);
		});
		response.on('error', function(error){ 
			console.log("Error of : " + location);
			console.log(error); 
		});
		response.on('end', function(){
			console.log("End of : " + location);
			//console.log(bl.toString());
		});
	});
}
```

**Comment by a0viedo** [comment]
There's something your `GetEndpoint` function it's not contemplating: http requests are asynchronous. How do you know when it's finished retrieving data?

**Comment by cmalcom** [comment]
When the "end" response come in, but how do I capture that and not return until I do?

**Comment by a0viedo** [comment]
Excellent response. That's the tricky part, return will be useless in your function if you want to wait for async processes. So if you don't use return, do you think what could work?

Step out of this particular exercise for a minute and think, how does the module `fs` notifies you that's done reading/writing a file?

**Comment by cmalcom** [comment]
I think what you are getting at is to add a callback to my GetEndpoint function.  I am still unsuccessful getting the desired results.  The async.series completes almost immediately.
I'm at a loss here... what am I doing wrong?

Here is my latest attempt:
var http = require('http');
const bufferList = require('bl');
var async = require('async');
var operations = [];

var endpoint1 = process.argv[2];
var endpoint2 = process.argv[3];
var endpoint3 = process.argv[4];

var returnData = [];

function saveData(error, data){
	console.log("In saveData");
	if(!error){
		console.log("In saveData - non error state");
		returnData.push(data);
		console.log("Return data now has length of " + returnData.length);
	}
}
function GetEndpoint(location, ondone){
	var bl = new bufferList();
	console.log("Starting GET on : " + location); 
	var counter = 0;
	
	http.get(location, function(response){
		response.on('data',  function(data)	{ 
			if(counter < 0) { 
				console.log("Data started of : " + location);	
				counter++
			}
			bl.append(data);
		});
		response.on('error', function(error){ 
			console.log("Error of : " + location);
			console.log(error); 
		});
		response.on('end', function(){
			console.log("End of : " + location );
			ondone(null, {"location":location, "data":bl.toString()} );
		});
	});
}

operations.push(function(callback){ GetEndpoint(endpoint1, saveData); callback();} );
operations.push(function(callback){ GetEndpoint(endpoint2, saveData); callback();} );
operations.push(function(callback){ GetEndpoint(endpoint3, saveData); callback();} );

async.series(
	operations,
	function(err){ 
		if(!err){
			console.log("Ending async.series");
			console.log(returnData[endpoint1]);
			console.log(returnData[endpoint2]);
			console.log(returnData[endpoint3]);
			}
	});

**Comment by a0viedo** [comment]
You're not applying the same criteria that you use to call `fs.readFile`, for example:

```js
var fs = require('fs');
// note that this call is asynchronous
// it may not take the same time if you run it several times
fs.readFile('temp.txt', function (err, res) {
  // in order to execute code when the function has finished, I provide a callback
  // and the code executed here will certainly be executed after the file has been read
}

// as it's opposite, this will be executed synchronously
// meaning that it will output 'hey' every time before the file is read
console.log('hey');
```


Reformatting some of your code:
```js
var http = require('http');
const bufferList = require('bl');
var async = require('async');
var operations = [];

var endpoint1 = process.argv[2];
var endpoint2 = process.argv[3];
var endpoint3 = process.argv[4];

var returnData = [];

function saveData(error, data){
    console.log("In saveData");
    if(!error){
        console.log("In saveData - non error state");
        returnData.push(data);
        console.log("Return data now has length of " + returnData.length);
    }
}

function GetEndpoint(location, callback){
    var bl = new bufferList();
    console.log("Starting GET on : " + location); 
    var counter = 0;

    http.get(location, function(response){
        response.on('data',  function(data) { 
            if(counter < 0) { 
                console.log("Data started of : " + location);   
                counter++
            }
            bl.append(data);
        });
        response.on('error', function(error){ 
            console.log("Error of : " + location);
            console.log(error);

            // this is very important too
            // you should always call your callbacks even if an error was encountered
            callback(error);
        });
        response.on('end', function(){
            console.log("End of : " + location );
            callback(null, {"location":location, "data":bl.toString()} );
        });
    });
}

operations.push( function(callback){ 
    GetEndpoint(endpoint1, function () {
        saveData();
        callback();
    });
});
operations.push( function (callback) { 
    GetEndpoint(endpoint1, function () {
        saveData();
        callback();
    });
});
operations.push( function (callback) {
    GetEndpoint(endpoint1, function () {
        saveData();
        callback();
    });
});

async.series( operations, function (err) { 
    if(!err){
        console.log("Ending async.series");
        console.log(returnData[endpoint1]);
        console.log(returnData[endpoint2]);
        console.log(returnData[endpoint3]);
    }
});
```

Well now I have a question for you. The function `saveData`, is executed synchronously or asynchronously?

**Comment by cmalcom** [comment]
I had to give up on this one.  I found the answer and have been looking it over, trying to make sense of it.  Thanks for your help, but I am going to have to experiment for a while to get this to sink in.

**Comment by a0viedo** [comment]
@cmalcom hang in there! Don't give up without a fight.

**Comment by gholtsla** [comment]
I just (finally) figured this one out, thanks to this and the other juggling question here.

What really helped me? Simplicity. Forget about the async library, as that just confused me when trying to read your code. The answer is pretty simple once you kind of "get it" and the other unresolved question was pretty helpful too in this regard. #312 is what it was.

It seems a _little_ unfair, looking back now, that the previous HTTP question didn't suggest the BufferList a bit more strongly. But you live and learn.

(if this comment makes the answer too obvious, please edit or delete it (or let me know and I'll do that))

**Comment by martinheidegger** [comment]
@gholtsla Congratulations.
