### ISSUE TITLE
Piping to stdout with Concat - Stream Adventure

### ISSUE THREAD

**Issue by magwitch** [nodeschool/discussions#90]
I wonder if someone could just clarify my understanding of streams and piping.
In Stream- Adventure `Transform` we used the npm  `Through` to create a read/write stream through which we could pipe data that we then transformed and  piped on to the standard output.

In Stream-Adventure `Concat` we're piping in a number of data streams which are concatenated together with the resultant stream being passed to a callback function. Having then transformed the data in the callback, if the result is logged directly to the console the transformation is applied but, if the result is piped on to the standard output with `.pipe(process.stdout),` just as we did in `Transform,` then the output shows no transformation. What is the purpose of using a callback function if we can't pipe on the results?

**Comment by dkoleary88** [comment]
Keyword here is "write" ;)

**Comment by kmckee** [comment]
This thread really helped my understanding of streams.  Thanks!

**Comment by squishleheimer** [comment]
Thanks guys.

**Comment by lodalo** [comment]
This was helpful :+1:

**Comment by hschoenburg** [comment]
yeah just jumping on to say thanks again. very helpful thread

**Comment by geekydatamonkey** [comment]
This is a great question and helped me understand streams better. It took me awhile to figure out that `concat` returns a **writable** stream, not a **readable** stream. Writeable streams cannot be piped to another stream. Only readable streams have a `pipe()` method. Makes sense.

This got me wondering how to do the reverse problem where I could pipe the reversed text to stdout, similar to previous problems in the streams adventure. 

I didn't use `concat()` and just used `through()` to create a transform stream. This was my solution (with comments), in case it helps someone else:

```js
const through = require('through2');

// this buffer will hold our chunks of data
// once we have everything, then we can reverse it
// and push it onto the next pipe
let buffer = '';

// reverses the data
function reverseChars(data) {
  return data.toString()
    .split('')
    .reverse()
    .join('');
};

// fires with each chunk. we save each chunk in the buffer.
// Note that we don't push any data onto the next pipe
// with this.push(...). We need to gather all the data first.
function onEachChunk(chunk, _, done) {
  buffer += chunk.toString();
  done();
}

// fires once we all the chunks. we reverse the buffer
// and push the result onto the next pipe
function onEnd(done) {
  this.push(reverseChars(buffer));
  done();
}

// here's the stream magic:
// use `through` to create a transform stream (a transform stream can be piped)
// the first function will fire on each chunk,
// the second will fire on end
// see: https://github.com/rvagg/through2
const reverseCharsStream = through(onEachChunk, onEnd);

// run it
process.stdin
 .pipe(reverseCharsStream)
 .pipe(process.stdout);

```

**Comment by maxwell-oroark** [comment]
Awesome thread guys, this was exactly what I was confused by and I've already learned a lot.  Would there be a solution aiming at piping to process.stdout like @jxjj but that uses some stream utility function wrapper around the `concat` function? I tried `fs.createReadStream( concat ( cb... ) ) ) ` but with no success.

**Comment by luk82** [comment]
As _concat-stream_ is writable it's possible to get the concat result into readable stream and then use pipe.

```
const concat = require('concat-stream');
const { Readable } = require('stream');

process.stdin.pipe(concat(function (data) {
  var str = data.toString().split('').reverse().join('');
  const readable = new Readable;
  readable.push(str);
  readable.push(null);
  readable.pipe(process.stdout);
}));
```
