### ISSUE TITLE
lololodash workshop - ex. 9 (To Do Template) - stumped!

### ISSUE THREAD

**Issue by srperetz** [nodeschool/discussions#900]
I'm completely stymied, and I'm hoping someone can help me out.  My solution to this problem looks to be essentially identical to the one posted by @mdunisch [here](https://github.com/mdunisch/lololodash/blob/master/exercises/9_todo_template/solution/solution.js), and the one posted above by @dylants [here](https://github.com/nodeschool/austin/issues/5#issuecomment-68921122).  Yet my solution fails when I run it, returning only `undefined`.

Any suggestions would be immensely appreciated.

Here's my code:

```JavaScript
"use strict";

var _ = require("lodash");

var worker = function(toDoData) {
   if (!(toDoData)) return "";

   var isUrgentDate = function(dateStr) {
      return (new Date(dateStr).getTime() -  new Date().getTime()) < (2 * 24 * 60 * 60 * 1000);
   }

   _.forEach(toDoData,
         function(toDoList, person) {
            toDoData[person] = _.sortBy(toDoList, 'date');
         });

   var toDoHtml = "<ul>\n" +
      "<% _.forEach(toDoCollection, %>" +
         "<% function(toDoList, personName) { %>" +
            "<li><%= personName %>\n" +
            "<ul>" +
            "<% _.forEach(toDoList, %>" +
               "<% function(toDo) { %>" +
                  "<li>" +
                  "<% if (isUrgentDate(toDo.date)) { %><b>URGENT</b> <% } %>" +
                  "<%= toDo.todo %>" +
                  "</li>\n" +
               "<% }); %>" +
            "</ul>\n" +
            "</li>\n" +
         "<% }); %>" +
      "</ul>\n";

   return _.template(toDoHtml, { toDoCollection: toDoData }, { 'imports': { 'isUrgentDate': isUrgentDate } });
}

module.exports = worker;
```

**Comment by martinheidegger** [comment]
Seems like template system changed in the recent version of `lodash`. Downgrade to `2.4.1` and it should work.

**Comment by srperetz** [comment]
Thanks @martinheidegger.  I just tried downgrading from 3.0.0 to 2.4.1, but it gives me the same error.  When I copy and paste my code into the REPL and call it with the same input that's used in `verify`, I get this error:

```
SyntaxError: Unexpected token ;
    at Function (native)
    at Function.template (....\node_modules\lodash\dist\lodash.js:6305:22)
    at worker (repl:29:10)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
```

and here are lines 6304-6309 from lodash.js:

```
      try {
        var result = Function(importsKeys, 'return ' + source + sourceURL).apply(undefined, importsValues);
      } catch(e) {
        e.source = source;
        throw e;
      }
```

so I added some logging to print out the args to the offending line (`Function(...).apply(...)`), and it turns out that lodash is doing something rather unexpected -- it's adding semicolons at the end of every `<% *some javascript code %>` ("evaluate") line.  That seems like a bug, no?

Below is the output when I print out the source argument that's passed in the offending line of code -- note the semicolons after lines such as `l.forEach(toDoCollection,` and `function(toDoList, personName) {`.  Could I be doing something wrong to cause that, or is that a bug in the template implementation.

Any ideas?

```
function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape, __j = Array.prototype.join;
function print() { __p += __j.call(arguments, '') }
with (obj) {
__p += '<ul>\n';
 l.forEach(toDoCollection, ;

 function(toDoList, personName) { ;
__p += '<li>' +
((__t = ( personName )) == null ? '' : __t) +
'\n<ul>';
 l.forEach(toDoList, ;

 function(toDo) { ;
__p += '<li>';
 if (isUrgentDate(toDo.date)) { ;
__p += '<b>URGENT</b> ';
 } ;
__p +=
((__t = ( toDo.todo )) == null ? '' : __t) +
'</li>\n';
 }); ;
__p += '</ul>\n</li>\n';
 }); ;
__p += '</ul>\n';

}
return __p
}
```

**Comment by martinheidegger** [comment]
If you write "%><%" in `lodash` templates it will replace it with something like `render("")` so if you do something like `function (a, %><% function()` then `lodash` will replace it with `function (a, render("") function () {` which is not valid javascript code and thus showing the error.

**Comment by srperetz** [comment]
@martinheidegger, thanks!!  I did that purely for formatting -- I'm used to JSP templates, which don't suffer from that limitation, to the best of my recollection.  Once I combined the offending lines, it worked (almost -- still some whitespace issue that's preventing it from passing, but no biggie there).  Thank you for taking the time to help me out!

**Comment by martinheidegger** [comment]
@srperetz Sure, no problem!
