### ISSUE TITLE
Filtered LS: Can someone explain what I'm doing wrong?

### ISSUE THREAD

**Issue by jclayton0004** [nodeschool/discussions#901]
Here's the code I have so far. I'd really appreciate if someone can tell me why it's wrong.

```JavaScript
var fs = require('fs')
var path = require('path')
var filterMe = process.argv[3]
var filePath = process.argv[2]
var printArr = undefined
fs.readdir(filePath, function printOut(err, list){
	printArr = list.filter(function filterArr (fileExt){
		return (path.extname(fileExt) === filterMe)
	})
	console.log(printArr)
})
```

**Comment by martinheidegger** [comment]
Hello @jclayton0004, 

as far as I can tell you are doing two things wrong here. 
1) You are filtering against fileExt but the fileExt does not arrive as you expect it.
2) Logging the array is not the same thing as logging each file in one line.

Are those hints enough?
