### ISSUE TITLE
I have installed the modules, but dont find any related tutorials

### ISSUE THREAD

**Issue by hbkevin** [nodeschool/discussions#902]
I have ubuntu 12 and installed javascripting,learnyounode and stream-adventure. But i don't find any related documentation or tutorials.

Please inform where can i find all the related tutorials

**Comment by martinheidegger** [comment]
@hbkevin javascripting, learnyounode and stream-adventure should show you information to each exercise (including links to documentation) after you chose an exercise. Is that not sufficient?

**Comment by hbkevin** [comment]
@martinheidegger : i have executed this command

npm install -g learnyounode

but i didn't found any documentation or any folder in my system in node_modules folder. Am doing anything wrong?

**Comment by martinheidegger** [comment]
@hbkevin Sounds like a installation problem: Did you try look at the wiki?https://github.com/nodeschool/discussions/wiki/Installation-suggestions
