### ISSUE TITLE
webgl exercise

### ISSUE THREAD

**Issue by rk08** [nodeschool/discussions#903]
Hi,

Whenever I run this piece of code in my files it shows i have completed my exercise.
Can you guys tell me why its happening

var exercise = require('workshopper-exercise')()

module.exports = exercise

**Comment by martinheidegger** [comment]
Ping @hughsk

**Comment by hughsk** [comment]
@rk08, I'm sorry I'm not sure what you mean. Are you referring to [WebGL Workshop](https://github.com/stackgl/webgl-workshop)? Or are you trying to use [`workshopper-exercise`](https://github.com/rvagg/workshopper-exercise) to write your own exercises?

If you're attempting WebGL Workshop, there shouldn't be any need to use `workshopper-exercise`. WebGL Workshop has been built from scratch so doesn't use it :) If you're writing your own exercises, I'm not familiar with how `workshopper-exercise` works unfortunately, but you might want to open an issue over there.
