### ISSUE TITLE
fs.readFile

### ISSUE THREAD

**Issue by code807** [nodeschool/discussions#904]
I'm having trouble understanding exactly what to do in the "My First Async I/O" part of the learnyounode module. I'm not sure if I missed any prerequisite tutorials, or even what they're asking me to do. Please help as soon as possible.

**Comment by martinheidegger** [comment]
@code807 Hmm, i am not sure what to tell you better than referencing the text in the hints:

> **HINTS** The solution to this problem is *almost* the same as the previous problem except you must now do it the Node.js way: asynchronous.

Most methods of [`fs`](http://nodejs.org/api/fs.html) have both a `*Sync` and a regular method. For example `fs.readFile` and `fs.readFileSync`. The former exercise asked for a solution using the sync api. `fs.readdirSync` So this method asks for a very similar task but this time it should use the `fs.readdir` method. Does that help you?
