### ISSUE TITLE
learnyounode HttpUpperCaserer

### ISSUE THREAD

**Issue by codydaig** [nodeschool/discussions#905]
In the learnyounode tutorial, more specifically the HttpUpperCaserer tutorial, the directions require that the application only accept 'POST' requests. However, when you verify that you've done it correctly, it does not check to see if it allows the standard GET requests. 

Ex. I did not put the logic in my code to check for POST or not, and yet I still passed.

**Comment by martinheidegger** [comment]
@codydaig Sounds like a good improvement for `learnyounode` to check that as well. Can you submit a Pull Request?

**Comment by finnp** [comment]
This is already mentioned here, not resolved yet though: https://github.com/rvagg/learnyounode/blob/master/exercises/http_uppercaserer/exercise.js#L65
