### ISSUE TITLE
`Filtered LS` in learnyounode

### ISSUE THREAD

**Issue by muan** [nodeschool/discussions#91]
Hi! I tried learnyounode the other day and it was super :cool:!

:raising_hand: 

During the challenges, I ended up getting stuck at `Filtered LS` for a good while because I couldn't figure out why `filename.match(/\.dat/)` works but `r = new RegExp("\.dat")` doesn't, which is totally my problem for not understanding RegExp well enough, but I feel like testing people regexp in the step created some unnecessary frustration in one's path to node.

What do y'all think?

**Comment by 11cs103** [comment]
![1](https://cloud.githubusercontent.com/assets/5787039/8307088/52dbaa24-19da-11e5-95a6-e9921478c233.png)
![2](https://cloud.githubusercontent.com/assets/5787039/8307097/601f2602-19da-11e5-9b90-b399606a7907.png)

I completed this task without using the path.extname() but i got a pass.

**Comment by SomeoneWeird** [comment]
That's fine, you don't have to follow the instructions exactly to the letter.

**Comment by takobaba** [comment]
I didnt want to use regex, instead i used split which was introduced previously:

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected  
   
  ✓  Used asynchronous method: fs.readdir()  
   
  # PASS Your solution to FILTERED LS passed!  
```

`Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected  
   
  ✓  Used asynchronous method: fs.readdir()  
   
  # PASS Your solution to FILTERED LS passed!  `

**Comment by b9sk** [comment]
It is not  feature it is a bug!

The `verify` in `learnyounode` for lesson `Filter LS` defenetly does not work properly. The only requirement is to use async `require('fs').readdir` method but the verify cannot be finished while the script works properly.

Properly means:
* we have to use callback into `fs.readdir` method
* nothing returns if the second argument is empty (or a file extension does not exist in given directory)

So this is the one of several possible scripts:
```
var fs = require('fs');

fs.readdir(process.argv[2], function(err, list) {
  if (err) throw err;

  list.map( function(filename, i) {

    // get extension from current file and compare it to given extension argument
    if (filename.split('.')[filename.split('.').length - 1] === process.argv[3])
      // if compared, make output of file name to console
      console.log(filename);

  });

});
```
And it's not pass verify, because `verify` does not comleted:
```
user@pc:~/nodeschool/learnyounode$ learnyounode verify program.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
user@pc:~/nodeschool/learnyounode$
```
See? Seems like it's stuck.

Version of  `learnyounode` is 3.5.3
`node` version is v4.4.5

**Comment by ishtiaque23** [comment]
@b9sk : Your first example will work. Just do this:
```javascript
//replace this line:
if (filename.split('.')[filename.split('.').length - 1] === process.argv[3])

//with this one:
if (path.extname(filename) === '.' + process.argv[3])
//note that you will require the "path" module for this.
```
2 problems with your approach:
First:
```javascript
filename.split('.')[filename.split('.').length - 1]
// Here you are doing the same filename.split operation twice. unnecessary
```
Second: The verify script will try it out with the extension "md". And to trick you, the test directory will contain file that has no extensions. In that case this approach will backfire as there will be no split at all.



Your second example will definitely not work.
1. You have that same problem I just mentioned above.
2. Also as you are using the **fs.readdirSync**, it won't pass. It clearly says in the description that this need to be async. So using a synchronous function is not expected here.

I am not sure whether you got confused by the 2nd test result or not. That is an automated test. And I agree, for this particular situation that test verbiage("Used synchronous method") is totally misleading.

**Comment by b9sk** [comment]
@ishtiaque23 Thank you for explanation and sorry my bad English. I forgot to mention: i try your solution above also. And your solution completely correct. It fixes case when extension and filename are the same. Unfortunately doesn't work too. `verify` has stuck. See result:
![image](https://cloud.githubusercontent.com/assets/8406003/16563035/8719c24c-4208-11e6-8cd6-a2f758b1bc99.png)


My point is:
* The verification has stuck if a script is correct.
* The verification ends "correct" if we ignore necessary requirements like using async `fs.readdir` and use `fs.readdirSync` instead ([image](https://cloud.githubusercontent.com/assets/8406003/16546262/645dc430-414d-11e6-8acd-263d5b43da2d.png)). In this case the verification is completed, it writes about errors.

So seems like it is a bug.

Thank you for paying attention.
I'm sorry if i caused misunderstanding in this explanation again.

If you want to reproduce it:
1. Environment: 
    - Ubuntu 14.04.4 LTS
    - node v4.4.5
    - npm 3.10.3
    - learnyounode 3.5.3
2. the script:
```
var fs = require('fs');
var path = require('path');

fs.readdir(process.argv[2], function(err, list) {
  if (err) throw err;

  list.forEach( function(filename, i) {
    if (path.extname(filename) === '.' + process.argv[3])
      console.log(filename);
  });

});

```
