### ISSUE TITLE
HTTP File Server: ECONNREFUSED, Invalid ".listen" argument

### ISSUE THREAD

**Issue by TheDemx27** [nodeschool/discussions#910]
This code works well if I don't run it with `learnyounode`, and instead use `node`, manually putting in arguments and pointing my browser to `localhost:<port>`. Here is the program:
```JavaScript
var http = require('http')
var fs = require('fs')

var server = http.createServer(function (req, res){
  var src = fs.createReadStream(process.argv[2])
  src.pipe(res)
})

server.on('listening',function(){
  console.log('server listening on ' + process.argv[3])
})

server.listen(process.argv[3])
```
And here is the output:
```
~/$ learnyounode verify lyn11.js 
server listening on /tmp/_learnyounode_23998.txt

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1133:5)
    at Object.<anonymous> (<path>/lyn11.js:9:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
✗ Error connecting to http://localhost:20743: connect ECONNREFUSED

```

I'm aware this error usually means there is a connection already using the specified port, but I am unsure of how to fix it. Somthing interesting is that the program would give an output such as: `server listening on /tmp/_learnyounode_23998.txt` before returning the error, indicating that learnyounode isn't providing a number and instead providing a file. Upon reading the files they don't even contain a number, but rather it seems that the files are from past tutorials, for example:
```
It'll be gyno to he's got a massive greenie. Gutful of bodgy mate as cross as a ratbag. She'll be right cleanskin mate flat out like a bottle-o.
```
And of course if I read the file and passed it to `.listen` I would get an invalid argument.

**Comment by davecocoa** [comment]
I would take another look at the instructions for the exercise and check that you are using the program arguments (`process.argv[2]` and `process.argv[3]`) in the correct order.

**Comment by TheDemx27** [comment]
Well that was an easy fix. Thanks!
