### ISSUE TITLE
Can't select an exercise after starting learnyounode

### ISSUE THREAD

**Issue by Mustiimams** [nodeschool/discussions#912]
I'm just unable to select anything, it's still the same after reinstalling.

Installed it by using: npm install -g learnyounode
Started the app with the following command in node.js cmd: learnyounode

**Comment by martinheidegger** [comment]
@Mustiimams What is the output? Can you do a little screencast? Also: Which operating system?

**Comment by Mustiimams** [comment]
@martinheidegger Hi, sorry for the late response, Learnyounode is working now.
I had to reinstall node.js instead learnyounode

**Comment by SomeoneWeird** [comment]
Awesome! :)
