### ISSUE TITLE
I want to send an object data to the worker fork call. the env allows only strings

### ISSUE THREAD

**Issue by nraghu99** [nodeschool/discussions#913]
How do I send json objects to the worker from the master during the worker creation using fork. Env only allows strings. Is there some other way to do it

**Comment by SomeoneWeird** [comment]
One way you could acomplish this is to call `JSON.stringify` on your object, which converts it to a json string, and then in your worker, call `JSON.parse` to convert it back to an object.

**Comment by nraghu99** [comment]
Thanks!
