### ISSUE TITLE
streams understanding stream adventure

### ISSUE THREAD

**Issue by paul-byford** [nodeschool/discussions#915]
i've been working on the streams-adventure workshopper and hoping you guys can help me get my head around streams. i thought i had the basics understood, but as i've moved through to some of the more complex adventures I've found this is not the case.

i've two specific questions, plus would appreciate any wider tips on how to approach getting my head around streams

first immediate question i have is understanding the difference between readable and writeable streams, and how i use them.

so my current understanding is that
- readable streams represent sources of data
- writeable streams represent where i would write data to 
- i can use `src.pipe(dest)` to get data from a readable stream and send it to a writeable stream

the duplexer module is one source of confusion, the help page on npm states the usage is. `duplex (writeStream, readStream)` and gives an example of 

```
var grep = cp.exec('grep Stream')
duplex(grep.stdin, grep.stdout)
```

when i read `stdin` i think it is a source of data that i would read from and if i read `stdout` i think it is something i would write to. the duplexer example seems to have them the other way around. What am i missing? how can i understand it better.

the second question i have is how do i best create streams in memory that i can use. for example if i do some work in my script to create some data from scratch and want to pipe it to a writable stream.

the third area is any more general advice on specific concepts i should understand with streams?

thanks in advance

**Comment by alanshaw** [comment]
Point of reference is important. Within your process, `process.stdin` is stream you read from and `process.stdout` is a stream you write to. From outside of your process, other programs write to it's stdin and read from it's stdout.

**Comment by Skunkw0rks** [comment]
I have the EXACT same queries as paul, if anyone could care to elaborate on any of his points it would be very much appreciated.

**Comment by jrjuang** [comment]
child_process.exec() creates a ChildProcess object, and ChildProcess.stdin is a Writable; ChildProcess.stdout is a Readable. They are designed to share the stdio to other Processes, so they are defined differently from Process.stdin and Process.stdout.
Document: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
