### ISSUE TITLE
For loop.js

### ISSUE THREAD

**Issue by Olen123** [nodeschool/discussions#916]
Hi sethvincent 
Thanks so much for your advice. It is working now my for-loop.js.
var total = 0;
var limit = 10;
for (var i = 0; i < limit; i++)
total += i;
console.log(total);

**Comment by sethvincent** [comment]
Cool! Feel free to open another issue if you have problems with another part of javascripting or other workshops.

**Comment by abinchalyan** [comment]
@Olen123 Olen:
var total = 0;
var limit = 10;
for (var i = total; i < limit; i++) {
total += i;
}
console.log(total);
I had same issue. I copy pasted the codes from other forum but didn't work. Problem was with location not the code. It seems like windows command terminal switch user back to parent FOLDER every time the user goes to next task. 

SOLUTION: check your file location. It should be C:\user\name\javascripting> javascripting verify for-loop.js
NOTE : don't forget to do 'cd javascripting'. Took me hours to figure out. :D
