### ISSUE TITLE
Decimal to binary conversion accurately

### ISSUE THREAD

**Issue by SrikanthNode** [nodeschool/discussions#917]
var dec = this.get(number)
 ,   bin = ParseInt(dec,10).toString(2)
here in the above example i tried to convert the 'number' (decimal) into binary but the value i got is slightly not matching with the decimal value after converting the converted binary value into decimal
decimal value:72057598599935719
binary value after converting:100000000000000000000000100001111111010101011011011100000
decimal value after converting from binary: 72057598599935710
the mismatch between 72057598599935719 and 72057598599935710
please help me to overcome this issue 

Thank you and regards,
Srikanth K
Web developer

**Comment by davecocoa** [comment]
That number is too large, integers represented as JavaScript numbers are only reliable up to 15 digits. Further info: http://www.hunlock.com/blogs/The_Complete_Javascript_Number_Reference

**Comment by martinheidegger** [comment]
@SrikanthNode Does it help you?

**Comment by SrikanthNode** [comment]
@martinheidegger  have to check if it work i will let you know 
Thank you @davecocoa and @martinheidegger

**Comment by SrikanthNode** [comment]
but can u give a better idea to solve this issue please.Because i need a code to convert the decimal to binary in accurate with the 64 bit values in javascript @davecocoa and @martinheidegger

**Comment by martinheidegger** [comment]
Does this library work? https://github.com/broofa/node-int64

**Comment by SrikanthNode** [comment]
thanks @martinheidegger let me check and is it possible to give the bower library

**Comment by SrikanthNode** [comment]
please can u tell me how i need to give the path in the node-modules, i gave but its not working properly so please guide me @davecocoa and @martinheidegger

**Comment by SrikanthNode** [comment]
And what the require function will do and how it will get the Int64 values please help me to understand this https://github.com/broofa/node-int64 @davecocoa and @martinheidegger

**Comment by martinheidegger** [comment]
It uses `Buffer` to store two regular integers and operates on them using standard operations. All in all probably a very slow approach but it will work. The source code is very short and fairly self explanatory: https://github.com/broofa/node-int64/blob/master/Int64.js

Do you need more info?
