### ISSUE TITLE
Trying to install a workshop, getting error in the terminal

### ISSUE THREAD

**Issue by lrose07** [nodeschool/discussions#918]
Trying to learn node.js. I installed it and then tried to run "npm install -g learnyounode". I got several lines of error:

    Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode'
    npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode']
    npm ERR!   errno: 3,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/local/lib/node_modules/learnyounode',
    npm ERR!   fstream_type: 'Directory',
    npm ERR!   fstream_path: '/usr/local/lib/node_modules/learnyounode',
    npm ERR!   fstream_class: 'DirWriter',
    npm ERR!   fstream_stack: 
    npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
    npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
    npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.
    
    npm ERR! System Darwin 14.1.0
    npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "learnyounode"
    npm ERR! cwd /Users/Lauren
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! path /usr/local/lib/node_modules/learnyounode
    npm ERR! fstream_path /usr/local/lib/node_modules/learnyounode
    npm ERR! fstream_type Directory
    npm ERR! fstream_class DirWriter
    npm ERR! code EACCES
    npm ERR! errno 3
    npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/learnyounode'
    npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
    npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
    npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Users/Lauren/npm-debug.log
    npm ERR! not ok code 0

I'm not familiar with using terminal or command lines for pretty much anything useful, so I have no idea what any of this means, and I have no idea what to do now. Any insight is greatly appreciated.

Thanks.

**Comment by martinheidegger** [comment]
Hello @lrose07 Thanks for posting here. We have some installation explanation here:
https://github.com/nodeschool/discussions/wiki/Installation-suggestions#mac
