### ISSUE TITLE
Unable to navigate the lessions

### ISSUE THREAD

**Issue by Kalpb** [nodeschool/discussions#920]
Hi have successfully installed the learnyounode.
I can open the learnyounode in my terminal but after opening i cant navigate between the lessons in mac(Yosemite).

It works perfectly fine in my windows machine.

Thanks in advance

**Comment by martinheidegger** [comment]
Hello @Kalpb!

Are you using a english keyboard layout? (Just in case)

**Comment by Kalpb** [comment]
Yes

**Comment by Kalpb** [comment]
uninstalling node and reinstalling it with brew solved it.

**Comment by martinheidegger** [comment]
Okay, great. Maybe wrong node.js version. Closing the issue.
