### ISSUE TITLE
stream-adventure #8 - HTTP Client - Error in official solution

### ISSUE THREAD

**Issue by arielschon12** [nodeschool/discussions#921]
The official solution states that the post request should be made to:

`var r = request.post('http://localhost:8000');`

This apparently doesn't work on my machine, and changing it to the solution below solved it:

`var r = request.post('http://localhost:8000/');`

**Comment by martinheidegger** [comment]
Can you open a Pull Request at https://github.com/substack/stream-adventure ?

**Comment by arielschon12** [comment]
@martinheidegger Just created a Pull Request!

**Comment by finnp** [comment]
Merged: https://github.com/substack/stream-adventure/pull/108 :blue_heart:
