### ISSUE TITLE
If/else statement in lines exercise  label:stream-adventure 

### ISSUE THREAD

**Issue by IGRACH** [nodeschool/discussions#922]
I'm not getting it, in the official solution they are using ternary operator, and it works. But when I use simple if/else statement I get null and errors. How to use if/else statement inside `this.queue()`. Here is the code:

    var split   = require('split')
    , through = require('through');

    var lines = 0;

    tr = through(
     function(line) {
       this.queue(
         if(lines % 2 === 0) {
           line.toString().toLowerCase() + '\n';
      } else {
        line.toString().toUpperCase() + '\n';
         }
         );
       lines++;
     }
     )
    process.stdin.pipe( split() ).pipe( tr ).pipe(process.stdout);

**Comment by sudodoki** [comment]
And what does your function return? ;)

**Comment by sudodoki** [comment]
You cannot nest `if` into function call as an argument. 
```
function n (a) {console.log(a)} 
n(if(true){ 1} else { 2 })
```
Will raise `SyntaxError: Unexpected token if`
Unlike 
```
function n (a) {console.log(a)} 
n(true ? 2 : 1)
```

**Comment by IGRACH** [comment]
Yes I know that, but how then to use logic inside this.queue(), is it possible? Except ternary operator?

**Comment by sudodoki** [comment]
Use [IIFE]()
```
function n (a) {console.log(a)} 
n((function(){ 
    if (true) { 
      return 1 
    } else { 
      return 2
    }
  })())
```
Or use an assignment
```
function n (a) {console.log(a)} 
var arg;
if (true) { 
  arg = 1 
} else { 
  arg = 2
}
n(arg)
```
So, in your case it would be 
```
var lines = 0;
tr = through(
 function(line) {
  var lineResult;
  if(lines % 2 === 0) {
    lineResult = line.toString().toLowerCase() + '\n';
  } else {
    lineResult = line.toString().toUpperCase() + '\n';
  }
   this.queue(lineResult);
   lines++;
 }
)
```
So this is exactly the illustration why sometimes ternary might be your friend instead of `if-else`

**Comment by IGRACH** [comment]
Oh thank you. I was thinking you can't access stream out of this.queue(). I'm new to this xD. So this.queue() is just passing on stream?

**Comment by sudodoki** [comment]
From https://github.com/dominictarr/through 
>through takes care of pause/resume logic if you use this.queue(data) instead of this.emit('data', data).

Maybe, you might want to take a look at [stream-handbook](https://github.com/substack/stream-handbook).
