### ISSUE TITLE
Juggling Asyc Problems

### ISSUE THREAD

**Issue by SoundtrkSamurai** [nodeschool/discussions#923]
Below is the code I'm trying to get to work. Testing of the code is showing that the index I'm looking for is permanently stuck at 3 instead of using the index value provided by i like I want. I'm aware of the pitfall of having the value of i increased during the time that the asynchronous callback is still running. I can figure out how to keep the current index value in scope log enough to use it when the callback function returns.

```JavaScript
var http = require('http');
var bl = require('bl');
var http = require('http');

var callbackStore = [];
var callbackCount = 0;
var urlsArr = [process.argv[2],process.argv[3],process.argv[4]];

for(var i = 0; i < 3; i++)
{
	juggleGet(i);
}

function juggleGet(index)
{
	http.get(urlsArr[index],function(response)
		{		
			response.pipe(bl(function(err,data)
			{	
				if(err) { console.error(err)};
				callbackCount++;				
				callbackStore[i] = data.toString();	
				
				if(callbackCount == 3)
					printResults();
			}));			
		});
}

function printResults()
{
	for(var x = 0; i < 3; i++)
	{
		console.log(callbackStore[x]);
	}
}
```

**Comment by martinheidegger** [comment]
```JavaScript
callbackStore[i] = data.toString(); 
```
This seems to be using the wrong variable, shouldn't that be callbackCount?

**Comment by SoundtrkSamurai** [comment]
No, callbackCount can be incremented by any of the three calls to https.get() in any order, so I don't use it for keeping track of which index I'm on. I just use it to know when all three callbacks have returned. After stepping away from the code for a few hours and coming back I immediately saw what the problem was. I was switching my variables from one section to the other after editing it so many times without making sure the same variable was changed everywhere. 

For example:

for(var x = 0; i < 3; i++), using x and then switching to I.

Or as in below:

function juggleGet(index)
{
    http.get(urlsArr[index],function(response)
        {       
            response.pipe(bl(function(err,data)
            {   
                if(err) { console.error(err)};
                callbackCount++;                
                callbackStore[i] = data.toString(); 
...
}

Using index at first in the function parameter and then using using I in the callbackStore[] array. The code was correct other than the variable names. Everything works now.

Thanks any for the help.

**Comment by martinheidegger** [comment]
Sorry, my bad, I meant it should be `index` instead of `i`

**Comment by martinheidegger** [comment]
@SoundtrkSamurai Did `index` work?
