### ISSUE TITLE
Understanding Stream/Pipe and Readable and writable stream events.

### ISSUE THREAD

**Issue by eswarreddyt** [nodeschool/discussions#924]
Hi,

I am trying to learn how the stream and pipe work in Node.js. 

Tried to mix and match few code . 
1. Created readable stream from a file (test.txt)
2. Streaming from a file to the compressed file (test.txt.gz) using pipe
3. Create a writer stream from a  file  (testwrite.txt)  and perform write
4. Apart from the write in step3,  Pipe the contents from readable (test.txt) to writable (testwrite.txt)

I have added few events as well.  and there seems to be conflict in the code and the events. and seeing an error.

Provided below is the code.

``` js
//streaming from file to compressed zip using pipe.
var fs = require('fs');
var zlib = require('zlib');
var readable = fs.createReadStream('test.txt');
var z = zlib.createGzip();
readable.pipe(z).pipe(fs.createWriteStream('test.txt.gz', {
    end : false
}));

readable.on('end', function() {
    console.log("Completed the streaming!");

});

//Writer
var writer =fs.createWriteStream('testwrite.txt');
for (var i = 0; i < 10; i++) {
    writer.write('hello, #' + i + '!\n');
}


//Writer pipe event
var assert = require('assert');
writer.on('pipe', function(src){    
    assert.equal(src, readable, 'Correct');
    console.log("successful");
});
readable.pipe(writer);


//Call end on writer
writer.end('this is the end\n');
writer.on('finish', function() {
    console.error('all writes are now complete.');
});
```

Can someone help me understand the code flow and whats the problem is. I can just remove an event and make the code working, but would like to know the reason why it isn't working.

**Comment by eswarreddyt** [comment]
Adding the error handling on writer resolved the error
*****************************
writer.on('error',function(err){
	console.log('Error mesage'+err);
});
********************
but the contents of the " Pipe the contents from readable (test.txt) to writable (testwrite.txt)" isn't working. 

Can't we do the pipe before the end function ?.

**Comment by finnp** [comment]
You are calling `writer.end('this is the end\n');` on the writer directly after piping to it. This means the pipe is interrupted by this end. So there is no chance that the readable will have time to write to the `writer`. And writes after end are not possible.
