### ISSUE TITLE
learnyounode lesson #3 seems to return wrong answer

### ISSUE THREAD

**Issue by mkiuchi** [nodeschool/discussions#925]
My answer rejected by learnyounode, but I believe that my answer is correct...

[program3.js]
var fs = require('fs');
var buf = fs.readFileSync('/mnt/storage/home/kiuchi/test');
var num = buf.toString().split(/\r\n|\r|\n/).length - 1;
console.log(num);
[/mnt/storage/home/kiuchi/test]
aaa
bbb
ccc

here is my trial.

$ node program3.js 
3
$ cat test|wc -l
3
$ learnyounode verify program3.js 
Your submission results compared to the expected:
                 ACTUAL                                 EXPECTED                
───────────────────────────────────────────────────────────────
   "3"                                 !=    "19"                               
   ""                                  ==    ""                                 
───────────────────────────────────────────────────────────────
✗ Submission results did not match expected!
✓ Used synchronous method: fs.readFileSync()
# FAIL
Your solution to MY FIRST I/O! didn't pass. Try again!

any comment is welcome...

Regards,

**Comment by davecocoa** [comment]
I think you need to reread the exercise instructions, specifically this one: 
```
The full path to the file to read will be provided as the first command-line argument.
```

**Comment by mkiuchi** [comment]
Oh... I've missed. Thanks.
