### ISSUE TITLE
Make it Modular Lesson Question about errors

### ISSUE THREAD

**Issue by emilabraham** [nodeschool/discussions#927]
I finished Lesson 6 about making things modular. I was curious about why we ```return``` the callback function when we get an error? Instead of just calling the callback function with error as a non-null value?

In the same vein, why do we ```return``` the console.error when we find an error? Instead of just calling console.error?

**Comment by notmatt** [comment]
Hi @emilabraham,

If I follow you correctly, you're wondering about this kind of convention in node code (from the hints section of 'Make it Modular'):
```javascript
    function bar (callback) {
      foo(function (err, data) {
        if (err)
          return callback(err) // early return
```
I'll try and  explain two things here: what that early-return line is actually doing, and why it's a useful convention in node.

So first, `return callback(err)` operates by first calling the function (`callback(err)`), and then it returns the result of the function. This code has exactly the same effect, but is hopefully makes what's going on more explicit:
```javascript
    function bar (callback) {
      foo(function (err, data) {
        if (err) {
          var result = callback(err)
          return result // early return
        }
```
So to answer part of your question, we are calling the callback function in the early return. This works the same way with `console.error` in the solution.

To answer the other part, this 'early return' is a convention in node as a result of server/client (especially web server) code being so common in node. A server can only respond once to a request, and that response (whether it's an error or the data you requested) will typically come via a callback or a series of callbacks in your application. As a result, it's a very strong convention in node that callbacks should only be called once, and the 'early return' convention helps avoid this type of error. As a quick example, here's similar code above, but without the early return:
```javascript
    var calledMe = 0
    function callMeOnce (err, data) {
      calledMe += 1
      console.log("Called " + calledMe + " times");
    }

    // creates an "error"
    function foo(callback) {
      callback("error", null);
    }

    function bar (callback) {
      foo(function (err, data) {
        if (err) 
          callback(err) // no return

        // do non-error things
        callback(null, data)
      })
    }

   // call bar to see what happens
   bar(callMeOnce)
```
I hope that helps! Thanks for trying out the workshops.

**Comment by eswarreddyt** [comment]
@notmatt 

Thanks I was also curious about the callback and the function call from foo.  The example you provided  clears my question.

**Comment by emilabraham** [comment]
:+1: Thank you for the explanation. I understand now. What is the protocol after I received a satisfactory answer? Close the issue? Or leave it open for future reference?

**Comment by martinheidegger** [comment]
@emilabraham Say thanks and close issue :+1:
