### ISSUE TITLE
learnyounode results in warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by kalpitad** [nodeschool/discussions#928]
Hi there, I've noticed the following warning when I run 'learnyounode'. I'm not sure if it's always been there, or if it just started because it prints to the terminal before the tutorial comes up. I noticed when I scrolled up once. Based on what I've read online about this issue, it seems like a problem with 'learnyounode' directly, rather than anything that I'm doing. Is that correct? Also, some folks online have said that running setMaxListeners isn't necessarily the right approach because something weird is going on. Please let me know if something is actually wrong with my setup. It hasn't prevented me from using the tutorial, which is great by the way!

The full warning...

    ♥ learnyounode
    (node) warning: possible EventEmitter memory leak detected. 11 select listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
    at Menu.addListener (events.js:179:15)
    at Menu.add (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/terminal-menu/index.js:74:14)
    at addEntry (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:33:10)
    at addVariableEntry (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:46:5)
    at Array.forEach (native)
    at addVariableEntry (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:41:28)
    at Array.forEach (native)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:58:16)
    at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/exerciseMenu.js:29:10)
    at Workshopper.printMenu (/usr/local/lib/node_modules/learnyounode/node_modu

**Comment by Sequoia** [comment]
@kalpitad nice catch! Can you please post some info about your environment?
* OS/version
* `node --version`
* `npm list -g learnyounode` (for lesson version)

**Comment by kalpitad** [comment]
Sure, here you go...
- Mac OS X Yosemite 10.10.2
- Node v0.12.0
- learnyounode@2.3.4

**Comment by Sequoia** [comment]
hrm that's the *exact* same stack as me.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109

$ node -v
v0.12.0

$ npm list -g learnyounode
/Users/sequoia/.npm-packages/lib
└── learnyounode@2.3.4
```

I'll try running it with `node-inspector` or something... Is this a totally clean, unmodified install, and did you install from the web or from brew or elsewise?

**Comment by kalpitad** [comment]
I originally installed node.js from the website. Then, I read that it was better to install it via homebrew, so I unstalled and reinstalled via homebrew. The uninstall process had a few hiccups but I believe that I was eventually able to get a clean homebrew install. Is there a way that I can check if something is actually wrong with my setup?

**Comment by martinheidegger** [comment]
The question is inverted: Why is this not a problem anywhere else? [For every item in a `workshopper`](https://github.com/rvagg/workshopper/blob/master/menu.js#L33) one event listener [will be added to the `terminal-menu`'s `select` event](https://github.com/substack/terminal-menu/blob/master/index.js#L83). By my last count that would be `17` listeners. However: [the default value for `maxlisteners`](http://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n) should have been `10` for a long time (certainly [before the changes](https://github.com/joyent/node/commit/cf0fa96db84caf9c1e6e5d0cb6f303cf6a8025c9)  of 0.12). Why it doesn't show as an error before 0.12 is a little mystery to me.

So... How can it be fixed? In my understanding it should be fixed in `terminal-menu`. Does @substack (cc) agree?

**Comment by Sequoia** [comment]
@kalpitad can you reproduce this in another environment? If so please escalate this to `rvagg/workshopper` or `rvagg/learnyounode`, this is an issue with one of these libs most likely. Sorry couldn't resolve this! Can't repro on my machine (with identical specs).

**Comment by martinheidegger** [comment]
I can reproduce it

**Comment by spyder1472** [comment]
I reproduced today, same warning as above.

Ubuntu 14.04.1 LTS in VirtualBox
Node v0.12.0, fresh install from source
learnyounode: v2.5.1

**Comment by Sequoia** [comment]
migrated to `learnyounode` as bug :point_up_2:
