### ISSUE TITLE
json time server

### ISSUE THREAD

**Issue by wordsforthewise** [nodeschool/discussions#929]
I'm confused by this line
  if (/^\/api\/parsetime/.test(req.url))
in the solution for the json time server.  Can someone explain to me what's going on with the /^\api\/parsetime/.test thing?

**Comment by martinheidegger** [comment]
In JavaScript you can use [regular expressions](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions). The solution uses a regular expression in this case to test if the `req.url` starts with "/api/parsetime". 

Does that help?

btw.: Regular expressions are awesome and you should definitely learn how to use them.

**Comment by wordsforthewise** [comment]
Ah ok, thanks! I know regex from python but didn't recognize the formatting
in js.

**Comment by martinheidegger** [comment]
In javascript regex are first-class citizens. Cool isn't it?
