### ISSUE TITLE
Juggling Async Scope

### ISSUE THREAD

**Issue by emilabraham** [nodeschool/discussions#932]
This is my attempt at a solution for problem 9:
```JavaScript
var http = require('http');
var bl = require('bl');
queue = {
  first: 'first',
  second: 'second',
  third: 'third'
}

var array = ['first', 'second', 'third'];

// First GET
http.get(process.argv[2], function (response) {
  response.pipe(bl(function (err, data) {
    if (err) {
      return console.error(err);
    }
    array[0] = data.toString();
  }));
});

// Second GET
http.get(process.argv[3], function (response) {
  response.pipe(bl(function (err, data) {
    if (err) {
     return console.error(err);
    }
    array[1] = data.toString();
  }));
});

// Third GET
http.get(process.argv[4], function (response) {
  response.pipe(bl(function (err, data) {
    if (err) {
      return console.error(err);
    }
    array[2] = data.toString();
  }));
});

for (var i = 0; i < array.length; i++) {
  console.log(array[i]);
}
```

I thought this would work. But it does not. When I mutate the elements of the array within the callback function, it does not seem to change. I can think of 2 possible reasons for this:

1. Scope. Somehow that array is not being mutated, but it retains the values that it was initialized to. Maybe it is out of the scope of the function?
2. Asynchrony. I am getting to printing the array before I am finished getting the http response because it is asynchronous. The flow of the program is allowed to continue while the get request is being processed. When the get request is done, it will simply call the callback function.

I am thinking it is most likely Asynchrony. Could I have an explanation? And maybe a hint towards the correct direction?

**Comment by martinheidegger** [comment]
Hello @emilabraham 

You were guessing right. Its about asynchrony. The `function (response) {` will be called as soon as the response is finished but `for (var i = ...` will be called when the last request was started.

**Comment by emilabraham** [comment]
Yup. Thanks. I added a counter that keeps track of which responses have finished. When that counter hits a certain number, print the result. :+1:
