### ISSUE TITLE
Problem on Objects Lesson

### ISSUE THREAD

**Issue by ldg** [nodeschool/discussions#933]
Hi, I'm doing the lesson on Objects and for some reason I'm getting the error:
`# O-oh, something isn't working.`
My code does work when I check it in the firefox console, so I'm confused as to what I'm doing wrong. This is what the lesson asks for:
## The challenge:

Create a file named objects.js.

In that file, define a variable named pizza like this:

```JavaScript
var pizza = {
  toppings: ['cheese', 'sauce', 'pepperoni'],
  crust: 'deep dish',
  serves: 2
}
```

Use console.log() to print the pizza object to the terminal.

## My solution:
```JavaScript
var pizza = {
	toppings: ['cheese', 'sauce', 'peperoni'],
	crust: 'deep dish',
	serves: 2
}

console.log(pizza);
```
...which returns:
```JavaScript
Object { toppings: Array[3], crust: "deep dish", serves: 2 }
```
Am I not understanding what the challenge question is asking? Why is javascripting telling me something is wrong?

**Comment by martinheidegger** [comment]
@ldg Peperoni?

**Comment by ldg** [comment]
Well I feel pretty stupid, lol. Thanks martinheidegger for clearing that up :+1:

**Comment by martinheidegger** [comment]
No problem. I am closing this issue, okay?

https://github.com/nodeschool/discussions#close-your-issue
