### ISSUE TITLE
Forks and Clones not verifying. 

### ISSUE THREAD

**Issue by Th3JourneyMan** [nodeschool/discussions#936]
![screen shot 2015-02-13 at 1 28 50 pm](https://cloud.githubusercontent.com/assets/2679050/6192909/887dd164-b384-11e4-80f9-4c819f59aced.png)

So, I've done all the steps described in the tutorial, and it's not verifying. I've had to add my username and email because by default it's got my work credentials, which aren't on github. However, after that's fixed, I can't think of anything else that might be getting in the way.

How can I turn on logging, to see exactly what git-it is doing to verify so that I can pinpoint the problem?

**Comment by Sequoia** [comment]
Hi @Th3JourneyMan! What exercise are you on? You write [forks and clones](https://github.com/jlord/git-it/blob/de7380e9660fb40b4963aa0a908230481d80ca4d/problems/forks_and_clones/verify.js) but from the output it looks like you're on [remote control](https://github.com/jlord/git-it/blob/de7380e9660fb40b4963aa0a908230481d80ca4d/problems/remote_control/verify.js#L10)

Try running `git reflog show origin/master` as in the latter exercise and see if `git reflog show origin/master` is output.

**Comment by Th3JourneyMan** [comment]
Hey @Sequoia,

Yeah, I meant remote control. Thanks for clarifying that.

I'm actually confused now, because when I check git-it, it says that I've completed that exercise. I'll get back to you.

**Comment by Th3JourneyMan** [comment]
So, actually, I might have been trying to verify forks and clones while git-it was pointed at remote control. 

Regardless, it verifies now. Sorry for taking your time, and thanks for the help!
