### ISSUE TITLE
JUGGLING ASYNC passed & fail! Why?

### ISSUE THREAD

**Issue by LxPvlv** [nodeschool/discussions#938]
```js
var bl = require('bl');
var http = require('http');

var dataArr = [];
var counter = 0;

function printToConsole () {
    for (var i = 0; i < 3; i++) {
        console.log(dataArr[i]);
    }
}

function get (i) {
    http.get( process.argv[i+2], function(response) {

    response.pipe(bl(function(err, data){
        if (err) {return console.error(err);}

        dataArr.push(data.toString());   //<<<< not work   why?
        // dataArr[i] = data.toString();//     this work   why?
        counter++;
        if (counter == 3) {printToConsole();}
    }));
});
}

for (var i = 0; i < 3; i++) {
    get(i);    
}
```

**Comment by finnp** [comment]
The `http.get` is asynchronous, that means that the callbacks can be called in a different order depending on which http request returns first. 
With this line:
```
 dataArr[i] = data.toString();
```
the variable i is set to the value in the array where it belongs. While 
```
 dataArr.push(data.toString());
```
will add to the end of the array each time the request ends. So the order depends on the timing of the requests.

Did this explanation help?

**Comment by LxPvlv** [comment]
Yes, thanks!
I confused the order of the index. I did so:
```js
dataArr.push( data.toString() + i );
```
and output was every time:
........  1
........  2
........  0

**Comment by martinheidegger** [comment]
@LxPvlv I assume you accidentally reopened :wink:
