### ISSUE TITLE
Http Server problem

### ISSUE THREAD

**Issue by SeeThruHead** [nodeschool/discussions#941]
sorry to clarify this is the stream-adventure course

I think that I've coded this properly but I can't seem to find why it's giving me the wrong output.

```javascript
var http = require('http'),
  ts = require('through');

var upperCaserer = ts(function write(data) {
  this.queue(data.toString().toUpperCase());
});

var server = http.createServer(function(req, res) {
  if (req.method === 'POST') {
    req.pipe(upperCaserer)
      .pipe(res);
  }
});
server.listen(process.argv[2]);
```

**Comment by SeeThruHead** [comment]
ACTUAL                             EXPECTED
------                             --------
"MISLAID"                          "MISLAID"
"ON"                               "ON"
"THEM"                             "THEM"
"BUT,"                             "BUT,"
"MASTER"                           "MASTER"
"OF"                               "OF"
"SNAKES,"                          "SNAKES,"
"WE"                               "WE"
"CAN"                              "CAN"
"MISLAID"                      !== "SLOUGHCHANGE"
"ON"                           !== "SLOUGHCHANGE"
"THEM"                         !== "IN"
"BUT,"                         !== "IN"
"MASTER"                       !== "THE"
"OF"                           !== "THE"
"SNAKES,"                      !== "NIP"
"WE"                           !== "NIP"
"CAN"                          !== "OF"
"SLOUGHCHANGE"                 !== "OF"
"SLOUGHCHANGE"                 !== "A"
"IN"                           !== "A"
"IN"                           !== "NAPPLE"
"THE"                          !== "NAPPLE"
"THE"                          !== "SOLONGAS"
"NIP"                          !== "SOLONGAS"
"NIP"                          !== "WE"
"OF"                           !== "WE"
"OF"                           !== "CAN"
"A"                            !== "CAN"
"A"                            !== "ALLSEE"
"NAPPLE"                       !== "ALLSEE"
"NAPPLE"                       !== ""
"SOLONGAS"                     !== null
"WE"                           !== null
"WE"                           !== null
"CAN"                          !== null
"CAN"                          !== null
"ALLSEE"                       !== null
"ALLSEE"                       !== null
""                             !== null
# FAIL

is the output

**Comment by martinheidegger** [comment]
Hello @SeeThruHead Just some basic questions: jave you selected the correct exercise? Are you operating in the correct folder?

**Comment by SeeThruHead** [comment]
yes all that is correct. it seems the problem lies in me assigning the return of the through module to a variable. if i put it like this

this works:
```javascript
var http = require('http'),
  ts = require('through');

var server = http.createServer(function(req, res) {
  if (req.method === 'POST') {
    req.pipe(ts(function(data) {
      this.queue(data.toString().toUpperCase());
    })).pipe(res);
  }
});
server.listen(process.argv[2]);
```
but this doesn't:
```javascript
var http = require('http'),
  ts = require('through');

var upperCaserer = ts(function(data) {
  this.queue(data.toString().toUpperCase());
});

var server = http.createServer(function(req, res) {
  if (req.method === 'POST') {
    req.pipe(upperCaserer).pipe(res);
  }
});
server.listen(process.argv[2]);
```

The only difference being that i put the through stream into a variable. which worked for me in previous exercises.

**Comment by deltab** [comment]
That's not the only difference. In the working version, you create a through stream for each request; in the other, you create one at the top and then use it for all requests.

Because [a through stream has a buffer](https://github.com/dominictarr/through/blob/6f814a601b37db1f44113e56a1eaa0c32a33b0a2/index.js#L17), and one request can start before a previous one has finished, if you have a shared through stream you'll sometimes have two requests accessing the same buffer and seeing data they shouldn't. Calling `through` each time means a separate buffer for each request.

You could instead name the _function_, and use `req.pipe(through(upperCaser)).pipe(res);`.

**Comment by SeeThruHead** [comment]
Thank you, that makes so much sense now.
