### ISSUE TITLE
Feedback request for learnyounode MAKE IT MODULAR '.'-prefix problem

### ISSUE THREAD

**Issue by rvagg** [nodeschool/discussions#942]
One of the most frequently encountered problems with learnyounode (it seems) is that people carry over their FILTERED LS code into MAKE IT MODULAR and leave the `'.'`-prefixing _outside_ of the module and therefore pass in a modified extension string and it fails. The standard failure says something like:

> Your additional module file [whatever.js] did not return an Array with the correct number of elements as the second argument of the callback

Which doesn't help in figuring out what the problem is, so they either end up here or on the learnyounode repo asking for help.

I would appreciate if helpers in here could review a proposed change that would address this directly and perhaps comment on wording if you have better ideas.

See rvagg/learnyounode#227

**Comment by Sequoia** [comment]
I don't fully understand the issue (I haven't done learnyounode in a minute) but "make it modular", if the purpose of the lesson is to teach about building modules, my O would be "don't add any other requirements that could confuse the communication of this concept."  I.e., if the exercise is "take the last exercise and put it in a module," make the exercise do that and not anything else.

It *seems* like people are getting confused because the exercise is "Make in modular and change the behavior in a couple subtle ways" rather than just "make it modular." Proposal would be to make the exercise strictly limit its requirements to introducing modules & not allow extraneous/extra requirements.  Thoughts?

**Comment by davecocoa** [comment]
I think it might be useful to split the exercise in two. Part 1 would involve writing a module, which learnyounode would exercise. The module would not access `process.argv` at all, and this would be an easy requirement to communicate. Part 2 would involve using the module written in Part 1.

**Comment by rvagg** [comment]
@davecocoa so, longer term I'd like to introduce a new "hello world" style exercise between these two exercises to make spin-up to modules more practical.

@Sequoia there is no changing of behaviour at all, it's the same exercise but you're given an API contract to abide by when splitting it out in to modules, I think this is a reasonable thing to ask--even if we reversed it so that you had to prefix the `.` before passing it in then I'd still want to be checking that you're abiding by the API contract you've been asked to use. API contracts are part of programming in every language and in Node it's usually at the module level.

As I've said elsewhere, I'm strongly opposed to dumbing exercises down much further, part of the enjoyment for the kinds of personalities who are drawn to programming is the problem-solving nature of what we do. The simpler we make the exercises the less enjoyment likely to be derived from solving the problems set. This isn't just about teaching the semantics of Node but an introduction to the joy of programming with Node.

**Comment by Sequoia** [comment]
@rvagg resolved?

**Comment by LanguidSquid** [comment]
@rvagg I recently started learnyounode. I had precisely the problem you mentioned. I left the prefixing of the extension in the original program.js and did not migrate it into the module. having read your first post I was quickly able to resolve this. Your mentioning this is the only thing that has helped me solve this awkward problem.

@davecocoa @Sequoia To contribute to the discussion; I think that the problem isn't necessarily the complexity of the problem (it's pretty simple as is) but maybe some more informative issue logging would help, like 'be sure to migrate all logic to the module' or  'do not modify the process.argv paramaters before passing them to the module function'
