### ISSUE TITLE
Start a nodeschool chapter for Bangkok, Thailand

### ISSUE THREAD

**Issue by athivvat** [nodeschool/discussions#943]
Hi, I would like to start a nodeschool chapter for Bangkok, Thailand. I am @athivvat on twitter and work on Code Friday Co.,Ltd. I have been using Node.js for 6 months and would like to help others learn as well.

**Comment by martinheidegger** [comment]
Hello @athivvat 

Following https://github.com/nodeschool/organizers/issues/28 I invited you to the owners list
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

**Comment by SmallRoomLabs** [comment]
I'm willing to help running the first nodeschool in Bangkok.  I spend about half my time working at the office in Bangkok and the dest of the time working from home in Kuala Lumpur. I've been thinking for a while to do a nodeschool event in either place, so maybe we could do one in bkk sometime in the next few months. I'm @matseng on twitter.

**Comment by athivvat** [comment]
Hi Michael,

I'm very glad to hear from you so interested to help running the first
nodeschool in Bangkok. this is my email athivvaat@gmail.com we can discuss
about how we are contribute community.


Cheers,
Ohm

Twitter @athivvat

**Comment by martinheidegger** [comment]
@athivvat please add @SmallRoomLabs to the bangkok group
