### ISSUE TITLE
[JUGGLING ASYNC] What is the difference between looping inside a function or outside of it?

### ISSUE THREAD

**Issue by faurehu** [nodeschool/discussions#944]
Have a look at the following code

```js

var http = require('http');
var bl = require('bl');
var res = [];
var count = 0;
var get = function(index) {
    http.get(process.argv[2+i], function(response) {
      response.setEncoding('utf8');
      response.pipe(bl(function (err, data) {
        if(err) {console.error(err);};
        count++;
        res[index] = data.toString();
        if(count==3) {print()};
      }))
    })
}

var print = function() {
  for(var j = 0; j < res.length; j++) {
    console.log(res[j]);
  }
}

for(var i = 0; i < 3; i++) {
get(i);
}

// I was first trying to have my function get as in the following code:

var get = function() {
    for(var i = 0; i < 3; i++) {
     ... // do whatever get does.
    }
}

```

Why is the latter method not valid? It adds 3 undefined elements and a string. I have trouble visualizing how this matters.

**Comment by rigers** [comment]
I have a very similar question.

When I use the code below it only returns the first value, the other ones are empty strings.
```javascript
for (var i = 2; i < process.argv.length; i++) {
    http.get( process.argv[i], function(response) {

        response.pipe(bl(function(err, data){
            if (err) {
                return console.error(err)
            }

            array[i-2] = data.toString()
            counter++
            if (counter == 3) {
                array.forEach(function(item){
                    console.log(item)
                })
            }
        }))
    })
}
```
But the following works.
```javascript
function read (i) {

    http.get( process.argv[i], function(response) {

        response.pipe(bl(function(err, data){
            if (err) {
                return console.error(err)
            }

            array[i-2] = data.toString()
            counter++
            if (counter == 3) {
                array.forEach(function(item){
                    console.log(item)
                })
            }
        }))
    })
}

for (var i = 2; i < process.argv.length; i++) {
    read(i)
}
```

**Comment by martinheidegger** [comment]
@faurehu 
You are dealing with difficulties of understanding "scope" in javascript. There many articles that try to explain scopes in the web. [this](http://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope/) for example. Perhaps its better to read them in case you are having problems with it.

Basically your problem is that variables are accessible at different execution points, consider this very simplified example:

```JavaScript
var a = "w";
var b = "x";
var c = function (a) {
   console.log(a + b);
}

a = "y";
b = "z";
c("v"); // output: vz
```

@rigers It really does seem like you are having a similar problem. I hope you get an answer with my former response as well. If not, please open a different issue here so we don't get all mixed up.

**Comment by faurehu** [comment]
@martinheidegger: in the first example, is the loop's variable 'i' passed to my htttp.get(argv[2+i])? I just realized it should be index, but it passed anyway. Just to be clear, it's the first one that worked and the second get function didn't.

**Comment by martinheidegger** [comment]
@faurehu You need to consider execution order.

```JavaScript
for(var i = 0; i < 3; i++) {
    console.log("Before request: " + i);
    http.get(process.argv[i], function () {
        console.log("Before processing the response" + i);
    });
    console.log("After request: " + i);        
}
console.log("All requested: " + i);
```

In this example `After request` and `All requested` will be called **before** `Before processing the response`. This means at the time when the callback comes the number stored in `i` is `4` and all response will write into the array position `4`.

Does that explain things?

**Comment by faurehu** [comment]
I get it now! We can mark this as closed.

One more question though: coming from Java, I thought the variables declared in the for-loop parameters can only be reached from the scope of the block. Is it true then that in Javascript these global?
