### ISSUE TITLE
Your solution to MY FIRST I/O! didn't pass. Try again!MY FIRST I/O!

### ISSUE THREAD

**Issue by taltal115** [nodeschool/discussions#948]
i wrote this program:
```javascript
function count(){
        var fs = require('fs');
        var buffer = fs.readFileSync('/var/www/nodejs-app/README.md').toString().split('\n');
        return buffer.length;
}
console.log(count());
```
but the numbers on the expected result is changing and by what i did it looks true.

can i ask what is the problem?

**Comment by Sequoia** [comment]
Hi @taltal115!  Note in [the exercise](https://github.com/rvagg/learnyounode/blob/master/exercises/my_first_io/problem.md) where it says
> The full path to the file to read will be provided as the first command-line argument. You do not need to make your own test file.

Review the solution to [baby steps](https://github.com/rvagg/learnyounode/blob/master/exercises/baby_steps/problem.md) for a refresher on reading command line arguments.

If you're still stuck comment & we can keep working on it! :smile_cat: Good luck!

**Comment by martinheidegger** [comment]
The problem is that the file you have to load will be given using process.argv:

> The full path to the file to read will be provided as the first command-line argument. You do not need to make your own test file.

so `fs.readFileSync('/var/www/nodejs-app/README.md')` becomes `fs.readFileSync(process.argv[2])`.

Does that help you?
