### ISSUE TITLE
learnyounode

### ISSUE THREAD

**Issue by bvcxtds** [nodeschool/discussions#949]
i followed the steps on installation but it is still not running on my vm running ubuntu

**Comment by maxogden** [comment]
@bvcxtds hi can you [check out our suggestions](https://github.com/nodeschool/discussions/blob/master/CONTRIBUTING.md#suggestions) and let us know exactly what is not working? please provide full error output (if you get an error) or a screenshot.

You can also check previous threads about installation problems at this link: https://github.com/nodeschool/discussions/issues?q=install

**Comment by bvcxtds** [comment]
hey @maxogden thank you for responding. 
So when i go an enter the npm command i get the follow
/usr/local/bin/learnyounode -> /usr/local/lib/node_modules/learnyounode/learnyounode.js
learnyounode@2.5.0 /usr/local/lib/node_modules/learnyounode
├── duplexer@0.1.1
├── after@0.8.1
├── rimraf@2.2.8
├── boganipsum@0.1.0
├── through@2.3.6
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── workshopper-wrappedexec@0.1.2 (xtend@2.1.2)
├── colors-tmpl@1.0.0 (colors@1.0.3)
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── concat-stream@1.4.7 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── bl@0.9.4 (readable-stream@1.0.33)
├── hyperquest@1.0.1 (duplexer2@0.0.2)
├── workshopper-exercise@2.3.0 (tuple-stream@0.0.2, split@0.3.3, visualwidth@0.0.1, chalk@0.4.0, xtend@2.1.2, i18n-core@1.3.2, through2@0.4.2)
├── through2-map@1.4.0 (xtend@3.0.0, through2@0.5.1, terminus@1.0.11)
└── workshopper@2.3.1 (map-async@0.1.1, xtend@3.0.0, chalk@0.4.0, mkdirp@0.3.5, visualwidth@0.0.1, colors-tmpl@0.1.1, terminal-menu@1.0.2, i18n-core@1.3.2, optimist@0.6.1, msee@0.1.1)

I'm assuming this is good, nothing went wrong. Now when i go and try to run it i get this
user@server:~$ learnyounode
user@server:~$ 

am i suppose to be running the command in a certain directory? Because i thought the installation was installed globally. Or maybe I'm just a complete noob...

**Comment by SomeoneWeird** [comment]
Yep! The problem is you probably have the `node` package installed. This is not `node.js`, try running `sudo apt-get remove node` and then follow the installation instructions on http://nodejs.org again :)

**Comment by bvcxtds** [comment]
@SomeoneWeird !!! you're boss!!! how did you know what was my issue??? Thank you very much!!

**Comment by SomeoneWeird** [comment]
\o/ the `node` package installs a binary which acts like the output you pasted (immediately returning and doing nothing). It's common enough that it happens quite often, unfortunately.
