### ISSUE TITLE
stream datatypes - general big picture understanding 

### ISSUE THREAD

**Issue by beckastar** [nodeschool/discussions#951]
Hi,

I'm going through the streams section, and I'm just confused about what it is that is being received.  What's the datatype?  If you're getting a stream of data, how is it chunked? Is it by size?  

Thanks,

Becka

**Comment by martinheidegger** [comment]
The data is chunked depending on the implementation of the stream. There is afaik. no "standard size" of a chunk. Regarding types: http://nodejs.org/api/stream.html#stream_object_mode

Does that clear up things?
