### ISSUE TITLE
Spark.io nodeschool workshop

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/discussions#952]
*from @emilyrose, migrated from https://github.com/nodeschool/discussions/issues/93#issuecomment-75096081*:
> I'm interested in working on a nodeschool course around hardware hacking with Spark hardware. Is there an existing nodeschool like this in the bay area?

Hi Emily! Apologies if you know this already, but here's some information that might be helpful:

"Nodeschool" can refer to:
1. This entire project/educational initiative
2. An event with a location/date & someone to facilitate it
3. A local chapter that puts on these events

There are also workshops or "workhoppers" (a bit confusing because it refers to workshops *built on* the [workshopper](https://github.com/rvagg/workshopper) framework, also named workshopper :stuck_out_tongue:).  These are listed [here](http://nodeschool.io/#workshopper-list) & workshoppers in progress can be found [here](https://github.com/nodeschool/workshoppers/issues?q=label%3A%22status%3Ain+progress%22)

**So**, are you asking
1. 'Is there a nodeschool in the bay area?'
:point_right:  *yes there are a couple: https://github.com/nodeschool/oakland http://nodeschool.io/sanfrancisco/ prsnly I'd recommend joining up with one of these chapters to organize your event*
2. 'Is there an upcoming nodeschool event in the bay?'
:point_right:  *none listed currently http://nodeschool.io/events.html*
3. 'Is there a `workshopper` on the subject of spark.io?'
:point_right: *[Doesn't look like it](http://nodeschool.io/index.html#workshopper-list) but you should totally make one! There is one on [robotics programming with johnny 5](https://github.com/tableflip/nodebot-workshop)*

Check out https://github.com/nodeschool/workshoppers for info on building your own workshopper.

So, does that make sense? If you have more questions, post away! :smile_cat:

**Comment by Sequoia** [comment]
lol nm @maxogden answered your request much more concisely :cat:

**Comment by grabbou** [comment]
@Sequoia any updates on Spark.io workshop? Got some sparks in the office and I can definitely help you with the preparations.

**Comment by Sequoia** [comment]
@grabbou It [doesn't look like](https://github.com/nodeschool/workshoppers/issues?q=label%3A%22status%3Ain+progress%22) anyone's doing a spark.io workshopper right now, you should do it! :+1:

**Comment by grabbou** [comment]
Yeah, interesting idea. My only worry is that not everybody is going to have spark.io with him... Not sure if we can get a company on board that will provide few of them. Shall I continue further discussion in newly created issue in repo you've linked or here?

**Comment by Sequoia** [comment]
Yes. Create with status:inprogress if you're actually starting the effort,
create with status:requested if you are not. The workshopper can be picked
up/used by anyone at any time so you don't need to worry about e.g. "does
each person have a spark.io" unless you're planning to put on an in-person
workshop.

**Comment by notmatt** [comment]
@grabbou 
> My only worry is that not everybody is going to have spark.io

The nodebots workshop is set up so that hardware isn't required, but you're still writing programs you could use on the hardware. I have no idea about the feasibility or difficulty of that with the Spark library, but I thought it worth mentioning since it might help get people to try it out.
