### ISSUE TITLE
learnyounode problem #3 - I am confused about how to get this to pass

### ISSUE THREAD

**Issue by chrisdavidmills** [nodeschool/discussions#953]
Hi there,

I have written the following solution for problem [#3](https://github.com/rvagg/learnyounode/blob/master/exercises/my_first_io/problem.md), which looks like it is working ok when I run it with a test file:

```JavaScript
var fs = require('fs');
var data = fs.readFileSync('test.txt');
var str = data.toString();
var array = str.split('\n');
console.log(array.length-1);
```

But I can't get it to pass when I try verifying it. the part of the instructions that is confusing, in my mind, is "The full path to the file to read will be provided as the first command-line argument. You do not need to make your own test file. " — nowhere does it seem to state what test file you need to use. Where is the test file to point to?

**Comment by Sequoia** [comment]
Hi @chrisdavidmills!

So you're right on the right track-- you highlighted the very part of the instructions I was going to point you to! Revisit your solution from [baby steps](https://github.com/rvagg/learnyounode/blob/master/exercises/baby_steps/problem.md#hints). In that exercise you learned to read args from the command line.  In this exercise, the **path to the file** will be passed in as a command line argument.  The file itself is [created **dynamically**](https://github.com/rvagg/learnyounode/blob/master/exercises/my_first_io/exercise.js#L47-L48) when you run `verify` or `run`, so you won't be able to find it before then.

Let us know how it shakes out!

**Comment by chrisdavidmills** [comment]
Hi there! I checked out the values available in process.argv, and passed the relevant array index in as my filepath inside readFileSync(). So my code now passes the test. Thank you so much for the help!
