### ISSUE TITLE
Node Error in For Loop

### ISSUE THREAD

**Issue by ArcanaMagus** [nodeschool/discussions#957]
Solution
===================

45

Your Attempt
===================

0
1
3
6
10
15
21
28
36
45

Difference
===================

0
1
3
6
10
15
21
28
36
45
(Solved)

**Comment by martinheidegger** [comment]
I am not quite sure what this issue means. Could you add an explanation or question?

**Comment by ArcanaMagus** [comment]
A for loop is used to iterate over items in a sequence rather than having to individually define each value or variable. This is what a for-loop looks like:


var total = 0;

var limit = 10;


for( var I = 0; I < 10; I++) {


//log in the console the number 45

total += I;




}

console.log(total);

‘var’ is used to define each variable we intend to modify

 Define a variable ‘total’ that is equivalent to 0

Define a second variable ‘limit’ that is equivalent to 10


Write a for loop that uses the ‘i’ to iterate over the items in the loop until the ‘limit’ is reached. On each iteration ‘i’ to the sequence of ‘total’ using a statement like this one:



total += 1;



The first statement introduces the variable ‘i’ that is its only function in this example

‘i’ is used to track how many times the loop will run

 The loop runs as long as ‘i’ is less than the ‘limit’

‘I++’ increases the variable by one for each iteration of the loop


Sent from Windows Mail





From: Martin Heidegger
Sent: ‎Saturday‎, ‎February‎ ‎21‎, ‎2015 ‎6‎:‎53‎ ‎PM
To: nodeschool/discussions
Cc: Ron Thomas





I am not quite sure what this issue means. Could you add an explanation or question?

**Comment by Sequoia** [comment]
Yo @ArcanaMagus! Can you please add the following to your ticket:
1. The name of the workshopper and the lesson number of the lesson you're having trouble with
2. **Your** solution code
3. The expected outcome (i.e. "I thought it would do X...")
4. The actual outcome ("...but in fact it did Y!")
5. Any error output.

We want to help but can't figure out what problem you're running into. :smile_cat:

**Comment by notmatt** [comment]
@ArcanaMagus If I understand correctly, you're doing the javascripting 'for loop' exercise, and your solution is being rejected.

I think the difficulty here is that you're logging at each point during the loop, but the exercise is expecting only a single line of output at the end of the loop.

Let us know if that helps.

**Comment by jaskillo** [comment]
From what I saw, it is requiring you to add a for loop that goes to 10 and expecting an answer that goes through 45. the question will never get the answer expected.
