### ISSUE TITLE
Problems installing my first workshoppers

### ISSUE THREAD

**Issue by jrox10** [nodeschool/discussions#958]
After intalling node.js in my macbook, i'm trying to unstall javascripting training course...
i've used
npm install -g javascripting
I'm using my  own user that has adminitrator rights (normally...)
i copy the error messages i've got
----
MacBook-Pro-de-Jesus:~ jrox$ npm install -g javascripting
npm ERR! tar.unpack untar error /Users/jrox/.npm/javascripting/1.11.0/package.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "javascripting"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/javascripting
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/javascripting']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/javascripting',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jrox/npm-debug.log
---
any help

thanks a lot

**Comment by martinheidegger** [comment]
In unix systems an root/Administrator is something slightly different than in mac os. You are usually running nodejs as your user that has `sudo` rights but is not a `su` by itself (which is good!). Please look at the [installation suggestions](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#mac) and use either `sudo` to install or reinstall with homebrew.

**Comment by jrox10** [comment]
Thanks Martin
I'll try to use sudo


2015-02-22 14:40 GMT+01:00 Martin Heidegger <notifications@github.com>:

**Comment by lightcastercoldheart** [comment]
Hi, I'm currently encountering the same problem, were you able to resolve this issue?

**Comment by martinheidegger** [comment]
@lightcastercoldheart Did you try the [installation suggestions](https://github.com/nodeschool/discussions/wiki/Installation-suggestions#mac)

**Comment by jrox10** [comment]
Yes, I'm using sudo and everythings works fine
thanks. Jesús Ortega

2015-03-02 7:26 GMT+01:00 Martin Heidegger <notifications@github.com>:

**Comment by lightcastercoldheart** [comment]
@martinheidegger Hi, Thanks for your reply, it works now after I uninstalled and reinstalled node with brew. Thanks!
