### ISSUE TITLE
Workshops don't launch

### ISSUE THREAD

**Issue by jobediah** [nodeschool/discussions#959]
My platform is OSX mavericks. I installed node via homebrew and the node version is v0.12.0 and the npm version is 2.5.1. I can install the workshops just fine, but then they don't launch when I type in the workshop name on the command line. I've tried ~four of the different workshops and none of them work on my machine.

**Comment by SomeoneWeird** [comment]
What is the output you get when you try and launch one?

**Comment by jobediah** [comment]
-bash: expessworks: command not found

**Comment by jobediah** [comment]
Below is the output from running npm install -g async-you:

/usr/local/Cellar/node/0.12.0/libexec/npm/bin/async-you -> /usr/local/Cellar/node/0.12.0/libexec/npm/lib/node_modules/async-you/async_you.js
async-you@1.0.0 /usr/local/Cellar/node/0.12.0/libexec/npm/lib/node_modules/async-you
├── async@0.9.0
├── workshopper-exercise@2.3.0 (after@0.8.1, visualwidth@0.0.1, chalk@0.4.0, tuple-stream@0.0.2, split@0.3.3, xtend@2.1.2, through2@0.4.2, i18n-core@1.3.2)
└── workshopper@2.3.1 (map-async@0.1.1, xtend@3.0.0, mkdirp@0.3.5, chalk@0.4.0, visualwidth@0.0.1, colors-tmpl@0.1.1, terminal-menu@1.0.2, optimist@0.6.1, i18n-core@1.3.2, msee@0.1.1)

I then get -bash: async-you: command not found.

**Comment by martinheidegger** [comment]
https://github.com/nodeschool/discussions/wiki/Installation-suggestions#mac

**Comment by martinheidegger** [comment]
The output of `npm config ls` and the output of `echo $PATH` would be good to know.

**Comment by a0viedo** [comment]
@jobediah and `sudo npm config ls` could help too

**Comment by jobediah** [comment]
npm config ls:
; cli configs
user-agent = "npm/2.5.1 node/v0.12.0 darwin x64"

; builtin config undefined
prefix = "/usr/local/Cellar/node/0.12.0/libexec/npm"

; node bin location = /usr/local/bin/node
; cwd = /Users/jodyhansen
; HOME = /Users/jodyhansen
; 'npm config ls -l' to show all defaults.

echo $PATH:

/opt/local/bin:/opt/local/sbin://anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/jodyhansen/myscripts

**Comment by a0viedo** [comment]
that's weird. execute `PATH=$PATH:/usr/local/Cellar/node/0.12.0/libexec/npm/bin` in your terminal and try again please

**Comment by jobediah** [comment]
Done! Works perfectly. Thanks a million!

**Comment by a0viedo** [comment]
no problem, come back if you have any questions!
