### ISSUE TITLE
How to listen to change event from web service node.js

### ISSUE THREAD

**Issue by uppalapati41** [nodeschool/discussions#961]
[Is there anything like web-service watch]

I have app.js file where am listening to web service using request module. When ever there is change in data am pushing data change with web service but how to handle the change event in node.js without keeping timer on request module.

```JavaScript
request('http://rss.cnn.com/rss/edition.rss', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    return (successHandler(body) )
  }
});
```
Am using socket.io to send data to client and consuming data using request module!!

**Comment by martinheidegger** [comment]
I don't know of a module that does that. But if I were you I would search in [the npm registry](https://www.npmjs.com/) and as on http://stackoverflow.com/tags/node.js . If you find the answer it would be nice to post it here. I am sure other people are interested in the answer too.

**Comment by uppalapati41** [comment]
Posted question in stack searching in registry!! Hard luck till now!!

**Comment by olizilla** [comment]
Maybe https://www.npmjs.com/package/rss-watcher or similar?

**Comment by uppalapati41** [comment]
This is fine but it will just return header which is even possible with request module. Thanx for that came to know new thing!!

**Comment by uppalapati41** [comment]
@olizilla So when ever there is change in that service [Something like new article added everytime] watcher will watch the change??

Is this correct?? [Not able to watch]

feed = 'http://github.com/nikezono.atom'
watcher = new Watcher({feed:feed, interval: 2000 })
watcher.on('new article',function(article){
     console.log(article)
})
watcher.run(function(article){
     console.log(article)
})

**Comment by martinheidegger** [comment]
@uppalapati41 as far as I read the read me your code should work. Probably nothing changed in the short timespan. If it doesn't I suggest that you post a bug in the issues or search for another library.

**Comment by martinheidegger** [comment]
I saw that you posted [a request](https://github.com/nikezono/node-rss-watcher/issues/9) at rss-watcher. Will close this issue.

**Comment by uppalapati41** [comment]
Yeah sure!! Once again thanx for support!

On Wed, Feb 25, 2015 at 10:59 PM, Martin Heidegger <notifications@github.com
