### ISSUE TITLE
Too many files in patchwork\contributors to view the one I've just (hopefully!) added

### ISSUE THREAD

**Issue by lymeswold** [nodeschool/discussions#962]
First, this is a *great* tutorial - thank you to Jessica Lord.  Second, as the 1,851st (?) user to work through BRANCHES AREN'T JUST FOR BIRDS and with a username beginning with 'L', after pushing my branch I cannot see my file since Github will only list the first 1000 files (msg: <<Sorry, we had to truncate this directory to 1,000 files. 851 entries were omitted from the list.>>).

I guess my question is "Can I filter the list of files in patchwork\contributors so I *can* check the file is present?". Maybe I also want to suggest an enhancement to the tutorial, that the files placed into patchwork\contributors are split into multiple sub-directories, maybe using the first letter of the username, ie patchwork\contributors\a, patchwork\contributors\b etc. so future users don't hit the same problem. Realise it may be too late for that. TIA and apologies if this has already been raised - I've not learned enough yet to check!

**Comment by martinheidegger** [comment]
cc @jlord

**Comment by jlord** [comment]
@lymeswold Good question! This is something I hadn't thought much about at the beginning—what if 1,000+ people do Git-it—woah! 

I agree, it is a bummer that you can't view all the files in `/contributors` and I'd like users to be able to find their contributed file in the list. 

I like your suggestion about creating multiple folders. One of the most common problems completing Git-it, however, is people actually correctly putting their file inside of `/contributors`. Many still put it in the main (root) directory `/`. I worry that having multiple directories will make these instances rise and will require a bit more work to verify users have put themselves in the correct file.

But! I still think think multiple directories is a good idea—so what about after 1,000 files are in `/contributors` an archive folder is created, say `/contributors-date` with the date the archive folder was created. This way new users to Git-it will continue to put their contributions in `/contributor` and always be able to view their file online.

I'm going to open an issue on Patchwork and cross reference here. Thanks @lymeswold :tada:
