### ISSUE TITLE
Error in Expressworks workshopper

### ISSUE THREAD

**Issue by prashantbaid** [nodeschool/discussions#963]
I completed the learnyounode Workshopper and was trying to run Expressworks workshopper. And I got this error when I try to open any exrecise. Here is the screenshot

![screen shot 2015-02-25 at 9 15 12 pm](https://cloud.githubusercontent.com/assets/1553563/6373990/fd59b47c-bd33-11e4-8bb9-29efd8af980f.png)

I also get exactly the same error in Windows command prompt.

**Comment by martinheidegger** [comment]
Can you try to remove `npm r expressworks -g` and install it again `npm i expressworks -g` ?

**Comment by prashantbaid** [comment]
I tried the solution given in this page and it worked for me
https://github.com/azat-co/expressworks/issues/60

**Comment by martinheidegger** [comment]
:+1:  Closing issue then
