### ISSUE TITLE
LearnYouNode Exercises 11 help

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [nodeschool/discussions#964]
I want to dig my teeth deeper into nodejs and found this helpful workshop CLI utility. I've easily stormed through exercises 1-10 and even completed 11 at one point. Fast forward a few weeks of neglecting nodejs, I tried program11 and it no longer worked. In fact, it just hangs. I don't understand why I [COMPLETED] it but it does not work now? Searching online I read to update learnyounode so I reinstalled using npm and fetched the new version. Other solutions to this problem mention ```return res.end("Don't send POST")``` Here's my CLI:

![screen shot 2015-02-25 at 12 07 35 pm](https://cloud.githubusercontent.com/assets/91709/6377037/3b5b55fc-bce7-11e4-81d8-5e6561ce7c3e.png)

program11 solution (Now not working):
```javascript
// Start program11 process

// Get the http module for Node
var http = require('http')

// file stream
var fs   = require('fs');

var upper = function(stream) {
   return stream.toUpperCase();
}

http.createServer(function(req, res) {
   if(req["method"] != "POST")
      return;

   // The filename is simple the local directory and tacks on the requested url
   var filename = req.url;

   // This line opens the file as a readable stream
   var readStream = fs.createReadStream(filename);

   req.pipe(readStream);

   req.on('data', function(data){
      data.toString().toUpperCase();
   })
}).listen(process.argv[2]);
```

What is happening?

**Comment by martinheidegger** [comment]
Hello @TheMaverickProgrammer ! Welcome back!

It would be good if you focus on one problem per issue. I will now address only 11 (uppercaserer) if you don't mind.
For Uppercaserer need to process the `{body}` of the response, `{uppercase}` it and `{respond}` it
In schema:  `{body} > {uppercase} > {response}`

However what you are doing is `{request} > {reading filedata???} > {transform}` 
That cant work :wink: 

So first the question is: how to write {uppercase} in a way that is possible to send it to {response}. The explanation for uppercaserer does have a good example for how to solve that. Could you find it?

**Comment by TheMaverickProgrammer** [comment]
@martinheidegger Thanks for responding. I'm not sure why I was checking for a file, but I'm more confused why my program was tagged completed. Let me attempt the program again and come back with a more correct attempt.

**Comment by TheMaverickProgrammer** [comment]
Note: Your post mistakingly says 11 is uppercaser, when it is HTTP File Transfer

**Comment by TheMaverickProgrammer** [comment]
Ended up looking for help online and discovered that LearnYouNode does specify the file will be read from a command-line argument and not POST'd into the server like I originally thought. Why this worked before, I have not the slightest clue.
