### ISSUE TITLE
Duvidas nodeschoo.io

### ISSUE THREAD

**Issue by fabianosb** [nodeschool/discussions#965]
Ola gostarai de saber se o curso é para iniciantes, sou iniciante em javascript consigo acompanhar ??

**Comment by martinheidegger** [comment]
cc @lucasfcosta (i think its portugese)

**Comment by nelson777** [comment]
Se vc é iniciante em javascript, melhor começar com o exercício chamado 'javascript', ele ensina o básico necessário de javascript pra vc fazer os outros.
