### ISSUE TITLE
always error when i tried to follow javascripting "introduction" example

### ISSUE THREAD

**Issue by daixiaoxiao** [nodeschool/discussions#968]
i am a novice for the javascripting and node.js, i followed the instruction on Github about javascripting, installed the node.js and input the command"npm install --global javascripting" and then run the workshop and choose Introduction, i strictly followed the path
![image](https://cloud.githubusercontent.com/assets/11231852/6415708/aea497e4-bedb-11e4-9587-e342300f0a7f.png)
but when i wanted to get the final answer, e.g, when input "javascripting verify introduction.js" always got the error below
![image](https://cloud.githubusercontent.com/assets/11231852/6415825/6adf9c24-bedc-11e4-96d2-b2936e48a803.png)
So what's the reason for this?? could anyone help me??? thank you!!!!!

**Comment by notmatt** [comment]
The `SyntaxError: Unexpected token ;` is telling you that there's a problem with the JavaScript that you're written. Normally that list just below would provide a better clue as to where that is, but the way that the workshops function obscures that information.

My guess is that this is a quirk of the Windows terminal fonts the `(` and `<` characters are very similar, and you've written `console.log<'hello'>` where the correct syntax is `console.log('hello')`. If you try the second one, I think you'll succeed.

Let us know if that works!
