### ISSUE TITLE
hello just to point but the uses of English on your site

### ISSUE THREAD

**Issue by jrmackie** [nodeschool/discussions#969]
hi regarding the uses of English there are many places where your English grammar is poor at best

**Comment by martinheidegger** [comment]
Well, many of the people that write here are not native speakers, and those who are always have help of people like you that are better to fix things! Please help fixing it by opening PR (Pull Requests) on the website repo https://github.com/nodeschool/nodeschool.github.io

**Comment by jrmackie** [comment]
will do, there was no offence meant






Sent from Windows Mail





From: Martin Heidegger
Sent: ‎Friday‎, ‎27‎ ‎February‎ ‎2015 ‎19‎:‎52
To: nodeschool/discussions
Cc: james mackie





Well, many of the people that write here are not native speakers, and those who are always have help of people like you that are better to fix things! Please help fixing it by opening PR (Pull Requests) on the website repo https://github.com/nodeschool/nodeschool.github.io

**Comment by martinheidegger** [comment]
I have taken it as offending in the least. I know improvements can be done at a lot of places. Thanks for helping us out!
