### ISSUE TITLE
NodeSchool modules do nothing when I try to run them...

### ISSUE THREAD

**Issue by Liveo13** [nodeschool/discussions#970]
I have installed nodejs and npm and them installed both javascripting and learnyounode, but whenever I enter 'javascripting' or 'learnyounode' nothing happens.  I am using the latest Ubuntu.

**Comment by SomeoneWeird** [comment]
Did you install `node` from the apt repositories? This is the wrong `node`. Run `sudo apt-get remove node` and then follow the instructions on http://nodejs.org to install node properly for your OS.

**Comment by Liveo13** [comment]
Excellent.  That worked after a bit of messing around.  Thank you very much. I owe you one.  If you are ever in Kazakhstan or South Korea, you have a place to stay :)

**Comment by SomeoneWeird** [comment]
Haha, no problem. Glad I could help. If you have any more questions just open another issue!
