### ISSUE TITLE
learnyounode -RaspberryPi Issues

### ISSUE THREAD

**Issue by StampedePress** [nodeschool/discussions#971]
Hi,
I'm new to node and to linux so this may stem from this combination.

I've installed node v0.8.8 with the help of this site, https://gist.github.com/stolsma/3301813
npm is version 1.1.59.

I've installed workshopper along with learnyounode and javascripting. I'm very excited to use these new tools to learn Node.js and javascript. The problem I'm having is when I goto my terminal and type in learnyounode. I'm getting a message "bash: learnyounode: command not found". What can I do to solve this problem?

I tried doing this:
sudo su -
cd /opt
chmod a+rw /home/pi/node/lib/node_modules
chmod a+rw /home/pi/node/bin
echo 'PATH=$PATH:/home/pi/node/bin' > /etc/profile.d/node.sh
^D
(from:http://raspberryalphaomega.org.uk/2014/06/11/installing-and-using-node-js-on-raspberry-pi/)
Thinking it would help link the bash commands but it did not help.

I've also come to realize that I should have installed nodejs into the /opt directory. Live and learn, its in the main for the time being.

**Comment by martinheidegger** [comment]
Node 0.8.8 is really old. A newer node version is afaik required.

**Comment by StampedePress** [comment]
Ok, I was thinking that they only had an older version for ARM use in the Raspberry Pi. I'll try it out with a newer version and use the patches that (https://gist.github.com/stolsma/3301813) supplied.

**Comment by StampedePress** [comment]
Ok, so I found (http://elinux.org/Node.js_on_RPi) v0.10.28 has a raspberry pi version. I installed it using the steps I found (http://raspberryalphaomega.org.uk/2014/06/11/installing-and-using-node-js-on-raspberry-pi/) replacing their older node version with instructions to get v0.10.28. 

My issue is that when I type node --verison it still reads v0.8.8
Looking at the install tutorial I read for v0.8.8 (https://gist.github.com/stolsma/3301813) I'm wondering what I can do to remove it. Are these v0.8.8 patches what is causing the problem?

**Comment by StampedePress** [comment]
Ok, so I found (http://elinux.org/Node.js_on_RPi) v0.10.28 has a raspberry pi version. I installed it using the steps I found (http://raspberryalphaomega.org.uk/2014/06/11/installing-and-using-node-js-on-raspberry-pi/) replacing their older node version with instructions to get v0.10.28. 

My issue is that when I type node --verison it still reads v0.8.8
Looking at the install tutorial I read for v0.8.8 (https://gist.github.com/stolsma/3301813) I'm wondering what I can do to remove it. Are these v0.8.8 patches what is causing the problem?

**Comment by StampedePress** [comment]
Ok, so I found (http://elinux.org/Node.js_on_RPi) v0.10.28 has a raspberry pi version. I installed it using the steps I found (http://raspberryalphaomega.org.uk/2014/06/11/installing-and-using-node-js-on-raspberry-pi/) replacing their older node version with instructions to get v0.10.28. 

My issue is that when I type node --verison it still reads v0.8.8
Looking at the install tutorial I read for v0.8.8 (https://gist.github.com/stolsma/3301813) I'm wondering what I can do to remove it. Are these v0.8.8 patches what is causing the problem?

**Comment by StampedePress** [comment]
Got it! At least now there is no version of node installed!
I utilized information on this site (https://github.com/joyent/node/issues/4058)
but really just went through all my folders and used sudo rm -fr  to remove files and folders related to node. Now to re-install my new version  (v.10.28)

**Comment by martinheidegger** [comment]
Can you add your findings to https://github.com/nodeschool/discussions/wiki/Installation-suggestions later?

**Comment by StampedePress** [comment]
Yes definitely, I've tried installing it a few ways and the whole not being familiar with Linux thing is really killing me. I'm not sure what Raspbian is looking for that I'm not giving it.

 Currently I installed node js in /opt and was not able to get "node --version" working from terminal. 
 I tried re-installing everything in /usr/local/bin but no luck either. 

I'm going to keep at it and post what I'm doing wrong. it's most likely something very basic. 

I also tried following these instructions (http://elinux.org/Node.js_on_RPi) but they did not help.

**Comment by StampedePress** [comment]
So I finally solved the problem, it is a super user issue when installing the tutorials. And I found the easiest way to install node.

Before you follow my example just make sure to erase your (probably many) version(s) of node.

wget http://node-arm.herokuapp.com/node_latest_armhf.deb
Unpack using:
sudo dpkg -i node_latest_armhf.deb

Then you can install your node school tutorial with two important commands (sudo and --global)
sudo npm install --global learnyounode

Here's my blog post it: http://stampedepress.org/?p=346

**Comment by martinheidegger** [comment]
:+1: WAY TO GO! 

I added a link to the wiki: https://github.com/nodeschool/discussions/wiki/Installation-suggestions

**Comment by StampedePress** [comment]
Thanks for updating the nodeschool github!

Good luck to everyone learning Node!
