### ISSUE TITLE
Error connecting to submission server

### ISSUE THREAD

**Issue by ponkon** [nodeschool/discussions#972]
I'm having trouble with both the expressworks and the kick-off-koa packages. Whenever I try to run or verify my answer I get the following error:

```
Error connecting to submission server(http://localhost:55684/hello), options: {"timeout":5000,"maxRedirects":10}. Error: connect ECONNREFUSED
    at exports._errnoException (util.js:742:11)
    at Object.afterConnect [as oncomplete] (net.js:982:19)
```

However, if I specify the port number and run it with node --harmony koa-test.js 8080 I can go to 127.0.0.1:8080 and see "hello koa"

I've tried on both a vagrant machine running ubuntu 14.04 and on my windows 7 machine natively, both give a similar error.

I'm guessing this is a firewall issue but I'm not sure... any suggestions?

Source below:
```JavaScript
var koa = require('koa');
var app = koa();
var port = process.argv[2];

app.use(function* () {
	this.body = 'hello koa';
});

app.listen(port);
```

**Comment by gelogenic** [comment]
I don't have a direct answer, but the mention of Windows and firewall seemed familiar. I found a post which might be related to what you're experiencing. HTH.

http://blogs.technet.com/b/askds/archive/2007/08/24/dynamic-client-ports-in-windows-server-2008-and-windows-vista-or-how-i-learned-to-stop-worrying-and-love-the-iana.aspx
