### ISSUE TITLE
Mysterious ECONNREFUSED in expressworks - Hello World

### ISSUE THREAD

**Issue by brookinc** [nodeschool/discussions#973]
I'm getting an ECONNREFUSED error when I try to run or verify my solution to "Hello World" in expressworks:
```
vagrant@precise64:/vagrant/nodeschool$ expressworks run express01.js
✗ Error connecting to http://localhost:11033/home: connect ECONNREFUSED
^C
vagrant@precise64:/vagrant/nodeschool$ expressworks verify express01.js
✗ Error connecting to http://localhost:47504/home: connect ECONNREFUSED
✗ Error connecting to http://localhost:47505/home: connect ECONNREFUSED
^C
```

The funny thing is that if I just run the file directly with, say, `node express01.js 3131`, I can query the server successfully from another terminal window:
```
vagrant@precise64:~$ curl http://localhost:3131/home
Hello World!vagrant@precise64:~$ 
```

I've looked at possible solutions from similar posted issues:
https://github.com/nodeschool/discussions/search?q=expressworks+econnrefused&type=Issues 
...such as:
-running killall node (no instances were running)
-making sure my route is declared as `'/home'` (it is)
-running `npm init` and `npm install express --save` in my nodeschool project directory
-checking for mismatched parentheses / curly braces (none as far as I can tell)
...but to no avail.

Any ideas what might be going wrong, or what I can do to fix it?

Here's my solution code, for reference:
```javascript
    var express = require('express');
    var app = express();
    app.get('/home', function (req, res)
    {
        res.end('Hello World!');
    });
    app.listen(process.argv[2]);
```

Thanks,

Brook

**Comment by brookinc** [comment]
PS. Node version is 0.10.35, and ```npm info express``` prints:
```
nodeschool@1.0.0 /vagrant/nodeschool
├── express@4.12.0 
└─┬ expressworks@0.0.23
  └── express@4.4.5 
```

**Comment by brookinc** [comment]
There are some additional suggestions / workarounds listed at https://github.com/azat-co/expressworks/issues/43 :
-increase the timeout value in setup.js
-install express directly into the working directory
...but neither changes my results. :(

**Comment by brookinc** [comment]
I've resolved the issue -- it was in fact the same short timeout value mentioned in the https://github.com/azat-co/expressworks/issues/43 link above.

I had previously tried increasing it on my own with no effect, but that turned out to be because I had both a local installation of expressworks and a global one. I was editing the local file but the global one was running. I had to increase the setTimeout() value in the global file (/usr/lib/node_modules/expressworks/exercises/hello_world/exercise.js) to verify my solution without getting an ECONNREFUSED error.

On this topic, I notice that the setTimeout was increased from 500 to 1500 by @amahfouz back on Nov. 19th to address this issue ( https://github.com/azat-co/expressworks/commit/388757542f6fc02e491f8a846251b4826806fc0a ), but in the recent refactoring pass ( https://github.com/azat-co/expressworks/commit/b4dae67733c447fb9532a18d47ca60a439df0ff2 ) it got dropped back down to 500?
```
  setTimeout(query.bind(this, mode), 500)
```

It might be worth bumping it back up, or adding some text to the readme warning that slow machines may not pass successfully even if the code is correct...

**Comment by brookinc** [comment]
(Also, I realize this is really feedback / an issue for the expressworks package rather than nodeschool, so I'll close this issue and take it over there. :) )

**Comment by jkbits1** [comment]
Thanks for your detailed comments on the behaviour of the expressworks tutorial, and your suggested resolution after some thorough research :+1: . This is very useful feedback to receive.

I haven't looked into the issue beyond reading your comments here, but I just wanted to say that it is both usual (and welcome) for people to post questions here prior to raising an issue on the package itself. Some volunteers will also be only watching for issues here rather than on the individual packages, so posting here may get noticed earlier. Please continue to provide feedback, either here or on a specific package.

If you paste a link to this issue in the issue on the package itself, it will link the issues and so people who find and read this later on can see the responses and eventual outcome. It may save you having to write out all the information twice, too :smile:

**Comment by brookinc** [comment]
Thanks for the feedback! It's good to know that I wasn't out of line. :) The specific issue that was happening for me (slow machine exceeding the 500ms timeout) appears to already have an open issue for it in expressworks (#43, linked above), so I've linked to this one from there and added a few explanatory comments, so hopefully any interested parties will be able to find the relevant info. Thanks again for the reply!

**Comment by jkbits1** [comment]
That's fantastic! Thank you very much :clap:
