### ISSUE TITLE
File IO instructions

### ISSUE THREAD

**Issue by TechAn** [nodeschool/discussions#974]
The text of exercise 3 states 'The full path to the file to read will be provided as the first command-line argument. ' unless I'm reading this wrong process.argv[0]; should give the file path but I need process.argv[2]; for the test to pass. Am I missing something or are the instructions incorrect?

Thanks

Text ...
 MY FIRST I/O
 Exercise 3 of 13

Write a program that uses a single synchronous filesystem operation to read a file and pr
int the number of newlines it contains to the console (stdout), similar to running cat fi
le | wc -l.

The full path to the file to read will be provided as the first command-line argument. Yo
u do not need to make your own test file.

**Comment by jkbits1** [comment]
Thanks for clearly stating the behaviour you've come across, it's very helpful. 

This situation can seem a little strange at first, but the first argument related to the tutorials is always at process.argv[2], the second at process.argv[3] and so on. The first two arguments relate to the executable behind the tutorial (in this case, node.exe). For more information, have another look at the instructions for the second step (doing this will not affect which steps are marked as completed).

Thanks again for a clear description, and please post any other questions or thoughts you have about the tutorial.
