### ISSUE TITLE
Exercise 9 : juggling async

### ISSUE THREAD

**Issue by salmander** [nodeschool/discussions#975]
Hi All,

Node.js newbie here.

The instructions says:
"You must collect the complete content provided to you by each of the URLs and print it to the console (stdout). You don't need to print out the length, just the data as a String; one line per URL. The catch is that you must print them out in the same order as the URLs are provided to you as command-line arguments."

I am struggling on the ".. you must print them out in the same order as the URLs are provided" section. I checked and debugged the official solution and even that is not outputting in the same order of urls:

```
// Juggling ASync Excercise

// Get node http module
var http = require('http');

// Get b1 module (for collecting whole streams)
var bl = require('bl');

var urls = process.argv.slice(2);

//console.log(urls);

if (urls.length < 1) {
  console.error('Please provide some URLS as command line arguments.');
}

// bls is the list of url and its content
var bls = [];
count = 0;

// Go through each URL
urls.forEach(function (url, index) {
  //console.log('Processing URL: ' + url);
  console.log('Processing >> index: ' + index + ', url: ' + url);

  http.get(url, function(resp) {
    console.log('Resp url: ' + url);

    // Pipe response to the bl
    //resp.pipe(bls[count]);
    resp.pipe(bl(function (err, data) {
      if (err) {
        console.log('bl error: ');
        return console.error(err);
      }
      
      console.log('bls length before: ' + bls.length);
      // Add response to the bls
      bls[index] = {
        url: url,
        data: data.toString()
      };

      console.log('bls length after: ' + bls.length);
      if (bls.length == urls.length) {
        console.log('all complete..hurray...');
        console.log(bls);
        console.log();
      }
    }));

  }).on('error', function(err) {
    console.log('Error: ' + err.message);
  });
});

```
Please help.

Many thanks.

**Comment by davecocoa** [comment]
Hi @salmander  I think you'll find problems are often easier to solve if you state what you expected to see, and what you actually did see. You mentioned "not outputting in the same order of urls", but I think you could be even more specific about what's happening here.

Looking at your code, one piece of information that might be useful is that javascript arrays can have empty elements. This affects the value of the `length` property. For example:
```js
var array = [];
console.log(array.length); // 0
array[0] = "first element"
console.log(array.length); // 1
array[2] = "third element";
console.log(array.length); // 3
console.log(JSON.stringify(array));  // ["first element",null,"third element"]
```

Can you see how this could affect your code's use of `.length`?

**Comment by salmander** [comment]
Hi Dave,

Thank you for your response.

Below is the response of the above script:
```
vagrant@homestead:~/www/node2$ learnyounode run 9.js 
Processing >> index: 0, url: http://localhost:46407
Processing >> index: 1, url: http://localhost:39005
Processing >> index: 2, url: http://localhost:48569
Resp url: http://localhost:39005
Resp url: http://localhost:48569
bls length before: 0
bls length after: 2
Resp url: http://localhost:46407
bls length before: 2
bls length after: 3
all complete..hurray...
[ ,
  { url: 'http://localhost:39005',
    data: 'Flat out like a dob flamin as busy as a gone walkabout. She\'ll be right sook flamin we\'re going ya. It\'ll be no-hoper my she\'ll be right mate\'s rate. Get a dog up ya aussie rules footy also get a dog up ya cooee. ' },
  { url: 'http://localhost:48569',
    data: 'Flat out like a veg out bloody get a dog up ya sickie. As busy as a chunder with shazza got us some ten clicks away. She\'ll be right cleanskin mate mad as a counter meal. ' } ]

bls length before: 3
bls length after: 3
all complete..hurray...
[ { url: 'http://localhost:46407',
    data: 'Lets throw a hoon mate she\'ll be right galah. We\'re going aussie salute when gutful of boogie board. Gutful of roadie with lets get some franger. Get a dog up ya road train how lets get some deadset. ' },
  { url: 'http://localhost:39005',
    data: 'Flat out like a dob flamin as busy as a gone walkabout. She\'ll be right sook flamin we\'re going ya. It\'ll be no-hoper my she\'ll be right mate\'s rate. Get a dog up ya aussie rules footy also get a dog up ya cooee. ' },
  { url: 'http://localhost:48569',
    data: 'Flat out like a veg out bloody get a dog up ya sickie. As busy as a chunder with shazza got us some ten clicks away. She\'ll be right cleanskin mate mad as a counter meal. ' } ]

vagrant@homestead:~/www/node2$
```

Now this is odd!!! I have been trying to resolve this at work and every time, the order of the url would never be the same as the order of response. And I just tried it at my home pc, and as you can see here, the response is in the correct order.

Confused.
 On both PCs I am running vagrant environment (laravel homestead) and same version of node v0.12.0

**Comment by davecocoa** [comment]
I would recommend looking more closely at that output ;)

Notice the first response to come back is `39005`, which is the second URL, this changes the length of `bls` from 0 to 2. The next response is `48569` which is the third URL, this changes the length of `bls` from 2 to 3 and because the length is 3, we consider all fetches to be complete. The last response to come back, `46407` which is the first URL, is not included in the first print of the full array.

**Comment by salmander** [comment]
Ahhh thanks for pointing that out. "Javascript arrays can have empty elements. This affects the value of the length property". Now it makes more sense. As you can see above, this is why I have added debugging code "before" and "after".

So the simple solution to rectify this problem is, instead of using .length property, use a counter.

I am glad that the order in bls array is the same as input urls, i.e. 46407 then 39005 and then 48569.
```
[ { url: 'http://localhost:46407',
    data: 'Lets throw a hoon mate she\'ll be right galah. We\'re going aussie salute when gutful of boogie board. Gutful of roadie with lets get some franger. Get a dog up ya road train how lets get some deadset. ' },
  { url: 'http://localhost:39005',
    data: 'Flat out like a dob flamin as busy as a gone walkabout. She\'ll be right sook flamin we\'re going ya. It\'ll be no-hoper my she\'ll be right mate\'s rate. Get a dog up ya aussie rules footy also get a dog up ya cooee. ' },
  { url: 'http://localhost:48569',
    data: 'Flat out like a veg out bloody get a dog up ya sickie. As busy as a chunder with shazza got us some ten clicks away. She\'ll be right cleanskin mate mad as a counter meal. '}
 ]
```

Thank you very much for your help.

**Comment by davecocoa** [comment]
Yes, a counter is the simplest way to deal with this problem. Well done! :tada:

**Comment by salmander** [comment]
Thank you once again.

I will double check the issue, tomorrow when I go back to work.

Peace.

**Comment by salmander** [comment]
All good here.
 
Thanks.
