### ISSUE TITLE
Problems Getting Started with Node.js 

### ISSUE THREAD

**Issue by jegamboafuentes** [nodeschool/discussions#976]
I can´t getting started whith Node.Js

I´m follow http://nodeschool.io/#workshoppers guide.

But i´m in the cero step.

i can´t initial any workshopper, the error in npm is this:

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! cwd E:\Users\B993241
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ECONNRESET
npm verb exit [ 1, true ]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\Users\B993241\npm-debug.log
npm ERR! not ok code 0

This problem is for the proxy configuration; The question is.. What can configurate it ?

Greetings

**Comment by sbrefort** [comment]
Hi, 
I think this can help you :
npm config set proxy http://proxy.company.com:8080 
npm config set https-proxy http://proxy.company.com:8080
if you need an authentication :
npm config set proxy http://user_name:password@proxy.company.com:8080
npm config set https-proxy http://user_name:password@proxy.company.com:8080

**Comment by jegamboafuentes** [comment]
Yes !!!, That is the solution!!!

Thank you @sbrefort.

Greetings.
