### ISSUE TITLE
Cannot Find work-shopper excerise

### ISSUE THREAD

**Issue by Ap0ph1s** [nodeschool/discussions#978]
Trying to do ExpressWorks, and tried installing workshopper-excerise, but It still crashes and I can't do any of its tutorials

**Comment by empireconstruct** [comment]
Having a a similar issue, have  you found a solution?

**Comment by Ap0ph1s** [comment]
No :(

**Comment by empireconstruct** [comment]
While you're waiting for a proper solution, try reverting back to a previous version of expressworks.

**Comment by SomeoneWeird** [comment]
Can you paste the actual error please?

**Comment by empireconstruct** [comment]
Error: Cannot find module 'workshopper-exercise' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Module.require module.js:364:17)                                            at require (module.js:380:17) at Object.<anonymous (C:\Users\Anita\AppData\Roaming\npm\node_modules\expressworks\exercises\hello_world\exercise.js:3:21) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10)                             at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17)

**Comment by martinheidegger** [comment]
Duplicate of https://github.com/azat-co/expressworks/issues/60 Should really be fixed :(

**Comment by martinheidegger** [comment]
@azat-co maybe you can merge: https://github.com/azat-co/expressworks/pull/61

**Comment by ddelrio1986** [comment]
Just run npm install -g workshopper-exercise to get around the issue.
