### ISSUE TITLE
stream-advenure #7 gives not ok 3 successful exit code

### ISSUE THREAD

**Issue by mlennie** [nodeschool/discussions#979]
Just like the title please help. My code is 

```javascript
var http = require('http');
var through = require('through');

var server = http.createServer( function(request, response) {
    var toUpperCase = through( function(buf) {       // <--- !!!
        this.queue(buf.toString().toUpperCase()); 
    });

    if (request.method === 'POST') {
        request.pipe(toUpperCase).pipe(response);
    } else {
        response.end('send me a POST\n');
    }
});
server.listen(parseInt(process.argv[2]));
```

**Comment by jkbits1** [comment]
Hmm, the code looks fine, and works on my set-up. Have the previous steps worked ok? 

If you post the full details of the error message, that might give a clue. Also, if you include some info on your set-up and node version (node -v), someone may be able to spot something there.

**Comment by mlennie** [comment]
Thanks @jkbits1 Node version `v0.10.33`. 

TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
ok 2 should be equal
not ok 3 successful exit code
  ---
    operator: equal
    expected: 0
    actual:   143
    at: ChildProcess.<anonymous> (/usr/local/lib/node_modules/stream-adventure/problems/http_server/index.js:31:11)
  ...

1..3
# tests 3
# pass  2
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################

**Comment by mlennie** [comment]
Upgrading node to 0.12 did the trick! Thank You

**Comment by jkbits1** [comment]
It's a pleasure! Thanks very much for letting us know what made it work.
