### ISSUE TITLE
Juggling Async

### ISSUE THREAD

**Issue by romski** [nodeschool/discussions#981]
I am trying to solve the juggling async task and believe that the output below works (by adding console logging to view the order of processing), however when I try to verify the answer it fails. Is there a problem with my code that I cannot spot?

node v0.10.33
npm v1.4.28
Windows 7 x86_64

```JavaScript
var http = require('http');
var bl = require('bl');
var urls = [];
var output = [];
var waiting = 0;

/* gather urls from command line */
for (var i = 2; i < process.argv.length; i++) {
  urls.push(process.argv[i]);
}

urls.forEach(function(url, index){
  waiting++;

  http.get(url, function(response){
    response.pipe(bl(function (err, data) {
      if (err) {
        console.error(err);
      }
      
      output[index] = data.toString();
      waiting--;      
      complete();
    }));
  });
});


function complete(){
  if (!waiting) {
    output.forEach(console.log);
  }
}
```

**Comment by sudodoki** [comment]
It's just the way you output the result. `forEach` passes 3 arguments to function passed as an argument - item, index, allItems

**Comment by martinheidegger** [comment]
@romski Just to clarify: The problem is how you output the data. `output.forEach(console.log)` doesn't consider the fact that @sudodoki mentioned.

Does that clarify things?

**Comment by romski** [comment]
@sudodoki @martinheidegger Indeed changing my output does fix the problem. I see now that console.log in my original use is printing all 3 arguments. I guess this got lost in the noise as I did a cursory visual check. I've included my update in case anyone else makes the same mistake. Thank you for the help (and for the great tutorials!).
````
function complete(){
  if (!waiting) {
    /* output.forEach(console.log); <-- prints the item, index and all items */
    for (var i = 0; i < output.length; i++) {
      console.log(output[i]);
    }
  }
}
````
