### ISSUE TITLE
Can't run workshop

### ISSUE THREAD

**Issue by AssetMedia** [nodeschool/discussions#982]
I've installed latest version of Node and NPM.  All OK

I've run npm install -g javascripting. All OK.

But when I run 'javascripting', I just get an error "-bash: javascripting: command not found".

Can anyone suggest what I might be missing?

Thanks

Jason

**Comment by martinheidegger** [comment]
Did you check your [Installation](https://github.com/nodeschool/discussions#check-your-installation)

**Comment by infoshahin** [comment]
I also facing this problem how can I solve it? How can I run this installed javascripting work space?

**Comment by AssetMedia** [comment]
Hi Infoshahin, this is what fixed it in the end for me: http://architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/#.VP4Qq2TLf_l

Just needed to add my path to node to /etc/paths

**Comment by martinheidegger** [comment]
Adding link to the installation instructions, thanks @AssetMedia !
