### ISSUE TITLE
Turn off colours for tutorials?

### ISSUE THREAD

**Issue by GBNeil** [nodeschool/discussions#983]
Hi folks! 

Firstly thanks so much for this great system that lets me & so many others learn Node comfortably. I've only just started but find the content really useful.

Unfortunately I'm having some trouble with the various colours used, in fact I'm unable to see the characters sometimes. Is there a simple way to revert back to black & white?

Many thanks for any suggestions!

**Comment by martinheidegger** [comment]
We havn't figured out the best way for that yet. There are multiple discussions  on this (and related): https://github.com/nodeschool/organizers/issues/24
https://github.com/rvagg/workshopper/issues/95
https://github.com/rvagg/workshopper/issues/75
https://github.com/rvagg/workshopper/issues/70

It would be great if you could contribute to one of those discussions. :+1:

**Comment by GBNeil** [comment]
Many thanks for the prompt reply. I'll try & determine the precise issues/colours & then see if I can find a  solution.  Would a simple regex colour replacement (or similar) in the tutorials be viable?
Cheers!

**Comment by martinheidegger** [comment]
A simple color replacement might be the best solution. Good idea!
