### ISSUE TITLE
How to perform Clustering in node.js using mesos ?

### ISSUE THREAD

**Issue by github4f** [nodeschool/discussions#985]
I'm working on a project with Node.js that involves a server. Now due to large number of jobs, I need to perform clustering to divide the jobs between different servers (different physical machines). Note that my jobs has nothing to do do with internet, so I cannot use stateless connection (or redis to keep the states) and a load balancer in front of the servers to distribute the incoming connection...

I already read about the "cluster" module, but, from what i understood, it seems to scale only on multiprocessors on the same machine.

My question: is there any suitable distributed module available in Node.js for my work? I have heard that mesos can abstract multiple physical machines into a single server? is it correct? If yes, it is possible to use the node.js cluster module on top of the mesos, since now we have only one virtual server?

**Comment by martinheidegger** [comment]
Nodes [cluster module](https://nodejs.org/api/cluster.html) is made for general threading (not just http requests). You have to use [messaging](https://nodejs.org/api/cluster.html#cluster_worker_send_message_sendhandle) to tell each thread what to do. JavaScript has no concept of shared memory (afaik). If you wish to use shared memory you have to use [C addons](https://nodejs.org/api/addons.html). Sending data to the threads is a way to distribute the workload. Once you have threads (using clusters), mesos should offer good distribution to you.
