### ISSUE TITLE
process.stdin.read() end signal

### ISSUE THREAD

**Issue by dtrprasad** [nodeschool/discussions#986]
how to indicate the end of input so that 'end' event emits normally

**Comment by martinheidegger** [comment]
Can you explain that a little further? Maybe some sample code?

**Comment by notmatt** [comment]
@dtrprasad I'm guessing a little (like @martinheidegger says, a bit more context would be helpful), but if you're reading right from stdin with no file redirection or pipes, then `ctrl-d` is the usual way to do this from the command line on unix-y systems (apparently it's `ctrl-z` on windows - I've never had to do this though). It sends the EOF (End Of File) signal.

**Comment by dtrprasad** [comment]
i have a code like

process.stdin.setEncoding('UTF-8');

process.stdin.read('readable',function(){
 var chunk = process.stdin.read();
 if(chunk != null){
  process.stdout.write('read data:'+chunk);
  }
 });
process.stdin.on('end',function(){
   process.stdout.write('read ing completed'); 
});

how to get  'end' event to get emitted. only os specific termination ctrl+c[windows] causes termination not end event.
i read stdout and stderr won't fire finish event

**Comment by martinheidegger** [comment]
@dtrprasad Could it be that you are looking for the `exit` event? https://nodejs.org/api/process.html#process_event_exit
