### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by akbzaman** [nodeschool/discussions#988]
how to code a login page with only node.js and css3 ? please give a example with a simple login page.

**Comment by martinheidegger** [comment]
@akbzaman The first page of google results yields: http://blog.knoldus.com/2014/03/06/a-simple-login-application-in-node-js-and-mongodb/ Does that do it for you?

**Comment by akbzaman** [comment]
Thanx Martin :)

**Comment by martinheidegger** [comment]
:+1: cheers
