### ISSUE TITLE
learnyounode -- Baby Steps

### ISSUE THREAD

**Issue by santoshsankar** [nodeschool/discussions#990]
Hi,
I wrote the below code for Exercise 2/13 - Baby Steps in learnyounode. While I test it independently and get the proper result, the verify function tells me otherwise. Any thoughts? Thanks in advance!

```javascript
console.log(process.argv);

var store = process.argv;
var sum = 0;

for(var i = store.length-1); i>=2; i--){
    var tank = Number(store[i]);
    sum = sum + tank;
};

console.log(sum);
```

**Comment by gelogenic** [comment]
Check parentheses matching in your for() statement - looks like you're either missing one or have one too many.

**Comment by santoshsankar** [comment]
Still no luck--

```javascript
console.log(process.argv);

var store = process.argv;
var sum = 0;

for (var i = store.length-1; i >= 2; i--) {
	//console.log(Number(store[i]));
	var tank = Number(store[i]);
	//console.log(tank);
	sum = sum + tank;
};

console.log(sum);
```

**Comment by martinheidegger** [comment]
Please always include the verification output. It helps to have a reference. Also: you should remove the first  `console.log` because that also becomes part of the output.

**Comment by martinheidegger** [comment]
@santoshsankar Did you manage to get it to work?

**Comment by tchillingworth** [comment]
The official solution here wants you to use a loop that counts up, not one that decrements from the end of the array. This may be causing your problem

**Comment by nitinpund** [comment]
Following solution works...!!!

var store = process.argv;
var sum = 0;

for(var i = store.length-1); i>=2; i--){
    var tank = Number(store[i]);
    sum = sum + tank;
};

console.log(sum);

**Comment by santoshsankar** [comment]
sorry for being tardy. I got it working! Many thanks!

On Thu, Mar 19, 2015 at 1:57 PM, nitinpund <notifications@github.com> wrote:

> Following solution works...!!!
>
> var store = process.argv;
> var sum = 0;
>
> for(var i = store.length-1); i>=2; i--){
> var tank = Number(store[i]);
> sum = sum + tank;
> };
>
> console.log(sum);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/discussions/issues/990#issuecomment-83694365>
> .
>



-- 
Santosh Sankar
santoshsankar@gmail.com | (410) 340-9288
www.santoshsankar.com

Penn State IFC/Panhellenic Dance Marathon | www.thon.org

**Comment by dskv** [comment]
Here is my solution: it also looks to make sure you have int and not words, check it out a little more then what is needed but helpful for people who are starting.

///////////////////////////////////start//////////////////////////////////
var args = process.argv
var sum = 0
var temp = 0

//console.log(process.argv)	
if ((args.length === 1) || (args.length === 2)) {
	console.log("Pass some int arguments when invoking this script!");
} else {
	args.forEach(function(arg, i) {
		if ((i === 0) || (i === 1)){
			//continue;
		}else {
			//console.log(i + ': ' + arg);
			temp = parseInt(arg,10);
			if (isNaN(temp) ){
			  console.log("Argument: %d not a integer", i-1);
			}else{
			  sum = temp + sum
			}
		}
	});
}
console.log("Sum is: " + Number(sum));

///////////////////////////////////end//////////////////////////////////

**Comment by SomeoneWeird** [comment]
@dskv Put ***```js*** on the line before your code, and ***```*** on the line after it :)
