### ISSUE TITLE
I am stuck on the number-to-string issue on the javascripting tutorial

### ISSUE THREAD

**Issue by viciousmelicious** [nodeschool/discussions#991]
Right now I put in my text editor:

var n = 128;
console.log(n.toString());

and saved it in the directory user/viciousmelicious/javascripting/variables/number-to-string.js

and put in my terminal the command javascripting verify number-to-string.js and I get this as a result:

Melissas-MacBook-Pro:~ viciousmelicious$ javascripting verify number-to-string.js
{ [Error: Command failed: /bin/sh -c node "/Users/viciousmelicious/number-to-string.js"
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/viciousmelicious/number-to-string.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/Users/viciousmelicious/number-to-string.js"' }
Melissas-MacBook-Pro:~ viciousmelicious$ 

Is my directory wrong, code snippet wrong or both? Any help is greatly appreciated thanks!!

**Comment by notmatt** [comment]
Hi @viciousmelicious,

I'm pretty sure it's that you're running it from the wrong directory; I'll try to explain, starting with your command: `Melissas-MacBook-Pro:~ viciousmelicious$ javascripting verify number-to-string.js`

The `~` in the promp is unix-y shorthand for "home directory", which is `/Users/visciousmelicious`. Then your command doesn't give any sort of path to the `number-to-string.js` file, so the command assumes you mean it's in the current directory. You've got a few choices here:
  - move the file to the current directory (simple but disorganized in the long run)
  - change to the same directory as where you saved the file and run the same command from there
  - change the command to give a relative path: `javascripting verify javascripting/variables/number-to-string.js` (the path is 'relative' to where you run the command, so the full path here would end up being `/Users/visciousmelicious/javascripting/variables/number-to-string.js`)
 
Let us know if that helps & thanks for trying things out!

**Comment by viciousmelicious** [comment]
Hi Matthew,

Thank you SO much for this explanation. The third option worked for me, and
just typed out the command to the relative path yay! Of course now I moved
onto the next exercise (if statement) and it's giving me a strange result.
My code snippet:

var fruit = "orange";
if (fruit.length > 5) {
  console.log('The fruit name has more than five characters.');
}
else {
  console.log('The fruit name has five characters or less.');
}

and when I type into the terminal, I get:

Melissas-MacBook-Pro:~ viciousmelicious$ javascripting verify
javascripting/variables/if-statement.js

-------------------

# *O-oh, something isn't working.*


# *But don't panic!*


-------------------

## *Check your solution:*


Solution

===================


128



Your Attempt

===================


The fruit name has more than five characters.



Difference

===================


The fruit name has more than five characters.128



## *Additional troubleshooting:*


- Did you type the name of the file correctly? You can check by running ls
javascripting/variables/if-statement.js, if you see ls: cannot access
javascripting/variables/if-statement.js: No such file or directory then you
should create new file / rename existing or change directories to the one
with file

- Make sure you didn't omit parens, since otherwise compiler would not be
able to parse it

- Make sure you didn't do any typos in the string itself

so i typed and got:

Melissas-MacBook-Pro:~ viciousmelicious$ ls
javascripting/variables/if-statement.js

javascripting/variables/if-statement.js

Melissas-MacBook-Pro:~ viciousmelicious$

Thanks again for such a quick response before! Learning Node while learning
JS is much more practical in my eyes, and the baby steps that the
nodeschool tutorial takes is perfect for me :)

Melissa

**Comment by martinheidegger** [comment]
Are you sure you selected the correct exercise?
