### ISSUE TITLE
learning communities and hackatons

### ISSUE THREAD

**Issue by bruennijs** [nodeschool/discussions#994]
Hello,
I will have my sabbAtical in July this year and I want to join self directed or managed communities where skills for modern Web applications (e.G. js,node,cloud technologies,git) can be learned.I would like to meet people working and learning with. Can you give me some hints of maybe different places or communities in Berlin or Hamburg where I can join forms hackatons and learn programmes? I couldnt find any programmes or time slots with shorter periods to you.
My time period is about some weeks,  2 or 3.

Thank you very mubch for your help,Olli

**Comment by martinheidegger** [comment]
@finnp ?

**Comment by finnp** [comment]
Hey @bruennijs ,

sorry I didn't see this issue back then. Starting Juli there is another batch of hackerschool in berlin, you can apply for this now: http://www.hackership.org/apply/ However this program is multiple months.

Also NodeSchool Berlin and Hamburg have regular meetups: http://nodeschool.io/berlin/ and http://nodeschool.io/hamburg/

You should also have a look at: http://www.opentechschool.org/berlin/

Also there is http://schoolofma.org/, which is a bit more broad and about technology and art in gerneral.

Have you found anything else yet?
