### ISSUE TITLE
javascripting - "IF STATEMENT"

### ISSUE THREAD

**Issue by brightfielddev** [nodeschool/discussions#999]
I'm not sure if I'm mistaken but it seems that this lesson may be incorrect (if it's not then I'm confused!).

Here is what the lesson asks of the user:

## The challenge:

Create a file named if-statement.js.

In that file, declare a variable named fruit.

Make the fruit variable reference the value orange with the type of String.

Then use console.log() to print "The fruit name has more than five characters." if the length of the value of fruit is greater than five.
Otherwise, print "The fruit name has five characters or less."

Here was my original answer which was 'incorrect':

`var fruit = 'orange'

if (fruit > 5) {
        console.log('The fruit name has more than five characters.');
} else {
        console.log('The fruit name has five characters or less.');
}`

Here are the results through the verifier:

Difference
===================

The fruit name has more than five characters or less.

Here is the answer that was deemed correct when ran through the verifier:

`var fruit = 'orange'

if (fruit > 5) {
        console.log('The fruit name has five characters or less.');
} else {
        console.log('The fruit name has more than five characters.');
}`

It would seem (TO ME) the verifier has the string that console.log() should print backwards. I read the code and lesson as: "If 'fruit' is greater than or less than 5 then print "The fruit name has more than five characters." BUT the verifier seems to want the opposite. It seems to want "If 'fruit' is greater than or less than 5 then print "The fruit name has more than five characters." Am I confused or is this incorrect?

**Comment by sethvincent** [comment]
Hi! Take a look at the `fruit > 5` part of the code.

The description for this challenge only hints at the solution: to get the number of characters in a string you'll need to use the `.length` property.

`fruit.length` will return `6` so `fruit.length > 5` will be true.

When not using the `.length` property, `fruit > 5` is checking to see if `'orange'` is greater than `5`.

**Comment by martinheidegger** [comment]
@brightfielddev does that help?

**Comment by bradonomics** [comment]
I too wrote 'fruit > 5` same way @brightfielddev did. I stared at my code for 20 minutes and still couldn't figure it out. Only when I asked a friend for help, did I get it. Probably should add a note about this in the error output.
